### ISSUE TITLE
[TODO] Add pane to change options

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#10]
roughjs has a bunch of options regarding line width, stroke/bg color, various patterns/roughness... We should add a pane where we can modify all those values for each element.

**Comment by paulomenezes** [comment]
I'll start to work with this tonight, I tought in a left panel with the tools and roughjs options similar to zwibbler

**Comment by vjeux** [comment]
Yeah, that would be great!

**Comment by paulomenezes** [comment]
Start to work in the panel, some suggestions? The idea is when the user select an element, show some options to customize below Export section. 
<img width="2032" alt="image" src="https://user-images.githubusercontent.com/10564179/71758774-bf664c00-2e82-11ea-850b-d089958d5de2.png">

**Comment by vjeux** [comment]
This looks great!

Do you want to first send a PR for this that we can merge in before you implement the per-element configuration?

**Comment by paulomenezes** [comment]
Of course.
