### ISSUE TITLE
Deleted elements reappear in SVG export

### ISSUE THREAD

**Issue by KMahoney** [excalidraw/excalidraw#1019]
Steps to recreate:

1. Draw some stuff
2. Delete it
3. Draw some more stuff
4. Export as SVG - the deleted items appear.

I'm using Chrome if that helps.

**Comment by KMahoney** [comment]
Refreshing the page before export seems to work around the issue.

**Comment by KMahoney** [comment]
Very quick fix! Well done.

Also a related minor bug: the deleted elements still affect the 'bounds' of the export, so if you create a really big picture and then delete that to make a smaller one, the exported picture will be very small.

**Comment by dwelle** [comment]
Interesting. Reopening..
