### ISSUE TITLE
Lines and Arrows cannot be moved or "extended"

### ISSUE THREAD

**Issue by fnky** [excalidraw/excalidraw#1022]
After drawing an arrow or line and trying to drag it, will try to "extend" the arrow or line rather than dragging. While in "extended" mode, moving the mouse will move the second point of the arrow but trying to click to apply the extending won't do anything.

Pressing ESC will cancel the operation and reset the arrow or line to its original state.

### Steps to reproduce

1. Select Arrow or Line tool.
2. Draw an Arrow or Line.
3. Click/drag on the Arrow or Line
4. See that it doesn't work

![excalidraw-lines](https://user-images.githubusercontent.com/995050/77177601-b4a07800-6abd-11ea-91c0-4a84f2f5111f.gif)

### Expected behavior

It should be possible to select, drag and extend arrows and lines. Ideas for how the UX could be:

- Click once (Tap) should be able to select it (show handles) without extending it.
- Mouse down and move (Tap + Touch Move) should drag the selected arrow/line without extending it.
- Double click (Double Tap + Touch Start on mobile) should create a point and enable extending the arrow.
  - Moving the mouse (Touch Move) while extending should move the new point.
  - Clicking (Touch End) once should add the point at the current mouse position.
  - Escape (Touch Cancel) should finish the operation and keep the added points.

**Comment by dwelle** [comment]
Fixed. Thanks for the report!
