### ISSUE TITLE
Resize elements from center point

### ISSUE THREAD

**Issue by fnky** [excalidraw/excalidraw#1024]
Allow the user to hold the Option/Alt modifier while dragging a handle to resize from center point.

### Example

![resize](https://user-images.githubusercontent.com/995050/77180119-61c8bf80-6ac1-11ea-9161-0424809b4059.gif)

**Comment by dwelle** [comment]
Agreed.

- Figma uses `Alt` (on Windows) as you said.
- Affinity uses `Ctrl` (on Windows)

We should investigate what's the industry standard, and whether it differs across platforms.

**Comment by fnky** [comment]
Sketch and Photoshop uses Option/Alt as well and would consider those pretty industry standard.

**Comment by dwelle** [comment]
You're on Mac, right?

**Comment by fnky** [comment]
I am on Mac myself, yes.

**Comment by jdestgermain** [comment]
Just wanted to chime in that I also instinctively have tried to use this feature many times while using Excalidraw and very much support/desire it.

**Comment by xixixao** [comment]
I think this can be closed now, since this was implemented.
