### ISSUE TITLE
Excalidraw app for G Suite

### ISSUE THREAD

**Issue by wokalski** [excalidraw/excalidraw#1026]
No filesystem and cloud sync is a bit annoying limitation for such a wonderful tool. Excalidraw desktop solves the former. I thought about addressing the latter by leveraging G suite marketplace. It would allow people to open excalidraw within google drive and have an instant sync of .excalidraw there.

**Comment by dwelle** [comment]
Hello. This sounds interesting, but how would this be implemented? At this stage, we want to keep excalidraw UI/UX simple & minimal, and not add any authentication. How would the sync work, exactly?

**Comment by wokalski** [comment]
I was thinking about an app like draw.io/diagrams.net for google drive.

https://gsuite.google.com/marketplace/app/diagramsnet/671128082532

I'm not quite sure how it's technically implemented but it seems lightweight enough. Once your app is launched from within google drive you don't need additional auth.

**Comment by dwelle** [comment]
What we don't want is a welcome screen ala draw.io. The GDrive integration could in theory be implemented as a button during save dialog, or a separate button elsewhere, which I think would be acceptable.

Would need to be thought through so that it's just an enhancement, and doesn't add any extra friction to our app.

Were you interested in implementing this yourself?

**Comment by wokalski** [comment]
@dwelle I totally agree with the design principle.

To be clear I thought about **embedding** excalidraw inside google drive/g suite like draw.io does. So you're authenticated "by default" because you enter the editor from google drive. Think a third party file type for google drive that's as seamless as google spreadsheet to edit.

**Comment by wokalski** [comment]
and no, I'm not interested in implementing it myself. I'm satisfied with excalidraw as it is now but I heard this complaint from some people I recommended excalidraw to.

**Comment by lipis** [comment]
Here is a good start: https://developers.google.com/gsuite

Would be nice to store `.excalidraw` files directly in G Drive somehow..

**Comment by andreadellacorte** [comment]
+1 on this - I (clumsily) lost a file while trying the sharing function. This feature might take inspirations from apps https://stackedit.io/app# and https://dillinger.io/ - I might try my hand at it.

**Comment by cherniavskii** [comment]
Hi there 👋
Just wanted to let you guys know, that I've released Excalidraw for Google Drive! :tada:
Check it out - https://cherniavskii.com/meet-excalidraw-for-google-drive/

**Comment by andreadellacorte** [comment]
> Hi there 👋
> Just wanted to let you guys know, that I've released Excalidraw for Google Drive! 🎉
> Check it out - https://cherniavskii.com/meet-excalidraw-for-google-drive/

Thanks a lot Andrew! That's exactly what we needed over here!!

Unfortunately it's failing on my side with this error:

> Cannot create new file. Make sure you're logged into appropriate account.

I have checked and I am indeed logged in to the correct account (I can see my email in the top right) - Not sure why this is happening.

**Comment by cherniavskii** [comment]
Hi @andreadellacorte 
Thanks for your feedback!

This error appears, when you're logged into account **A** in your Google Drive, and then try to create a new file being logged into account **B** in Excalidraw.
If you still get same error, feel free to join me on Discord so that I can investigate it further. My username is `cherniavskii#2985`

**Comment by jhoogeboom** [comment]
After installing and using on an existing .excalidraw file on google drive, I cannot open it with the add-in
<img width="743" alt="Screenshot 2020-09-03 at 14 48 23" src="https://user-images.githubusercontent.com/1828504/92117265-42b2b580-edf5-11ea-9ffb-8c06c5461ffc.png">

@cherniavskii how is this sort of thing normally governed from an open source perspective? these google drive plugins requires to prove ownership of a domain in this I guess excalidraw.app? Also is your plugin open sourced somewhere?

**Comment by cherniavskii** [comment]
Hi @jhoogeboom 

> After installing and using on an existing .excalidraw file on google drive, I cannot open it with the add-in

Weird, did you refresh Google Drive page after installing? I noticed, that it apps do not appear on the list without refresh.
Also, can you make sure there's Excalidraw app on the list in Settings > Manage apps?

I've checked this few times on different accounts and different devices, and it works just fine.

> anyone could technically make an excalidraw google drive plugin

Correct!

> Is yours open sourced?

Not currently

**Comment by andreadellacorte** [comment]
Hey @cherniavskii, I signed out and back in into my Google account from the excalidraw page and it works now

When are you planning to open source the integration?

**Comment by jhoogeboom** [comment]
Ah, I see what's going on. I tried this on a file on a shared drive first, they have a different handling. Works well on a normal google drive file.

One question maybe, every time I open a file, it asks again to authorize and choose the account even though I'm already logged in. Is that intentional?

**Comment by cherniavskii** [comment]
Hey guys, sorry for a late reply

@andreadellacorte 

> I signed out and back in into my Google account from the excalidraw page and it works now

Awesome!

> When are you planning to open source the integration?

No plans for now, will you be willing to contribute?

@jhoogeboom 

> I tried this on a file on a shared drive first, they have a different handling

I'll definitely look into this, seems like nice to have feature

> every time I open a file, it asks again to authorize and choose the account even though I'm already logged in. Is that intentional?

It is not intentional, but I've seen this behavior on iPad Safari. What's your system/browser?
No need to authorize over and over on desktop Chrome though :)

**Comment by andreadellacorte** [comment]
My main use case for asking for the code is because it would help with the
security approval at my company :)

And I'm happy to collaborate too!

**Comment by Jan-M** [comment]
I would also love to see the google app integration being open sourced.

**Comment by lipis** [comment]
Not match tractions nor resources for this one.. maybe in the future.

**Comment by wjdp** [comment]
Hi @cherniavskii 

I've been using Excalidraw on and off for a while, but your Google Drive integration has really helped make it a usable tool! We use Google Drive heavily at work and having it as the backend for sharing / storage of Excalidraw docs would be very useful.

I've hit the issue where it works well on my personal drive, but when a doc is in a team drive it cannot be opened:

![image](https://user-images.githubusercontent.com/1690934/128688992-be17ba3c-2508-4041-bf9e-14a6d7b26983.png) vs 
![image](https://user-images.githubusercontent.com/1690934/128689059-22b3a620-31a0-4a98-b9c2-92224f1f96af.png)

- Have you had a chance to look into this?
- Is your version going to be open sourced? Would rather have this conversation on the issue tracker for excalidraw.app vs the main one.

**Comment by cherniavskii** [comment]
Hey @wjdp ,
I'm using Excalidraw for Google Drive with both personal and team drives (had to install the app on each drive separately, since those are separate accounts).
Maybe this has something to do with your team settings?

I might be opensourcing it this weeked.
Would you be willing to contribute?

**Comment by emindeniz99** [comment]
> Hey @wjdp , I'm using Excalidraw for Google Drive with both personal and team drives (had to install the app on each drive separately, since those are separate accounts). Maybe this has something to do with your team settings?
> 
> I might be opensourcing it this weekend. Would you be willing to contribute?

Hello, thanks for your works.
Did you make it open source?
And I wonder the version of excalidraw that you used.
If you made it open source, it can be more beneficial.
Thanks

**Comment by cherniavskii** [comment]
Hey @emindeniz99 
I haven't updated excalidraw for months.
Would you be willing to contribute?

**Comment by emindeniz99** [comment]
> Hey @emindeniz99
> I haven't updated excalidraw for months.
> Would you be willing to contribute?

Yes, I am willing to try contributing. Even if I can not do it, someone could help us.

**Comment by cherniavskii** [comment]
@emindeniz99 https://github.com/cherniavskii/excalidraw-google-drive
Welcome :)

**Comment by bttd** [comment]
> @emindeniz99 https://github.com/cherniavskii/excalidraw-google-drive Welcome :)

Can you make it available again? I wanted to use your plugin with my self-hosted excalidraw instance in possible.

**Comment by parthmakadiya12** [comment]
@cherniavskii If possible can you make it open source so that everyone can use it and contribute.

**Comment by cherniavskii** [comment]
> @emindeniz99 [cherniavskii/excalidraw-google-drive](https://github.com/cherniavskii/excalidraw-google-drive) Welcome :)

The app was open source for a while but was later acquired.
I don't own it anymore.

**Comment by StefanRiedAV** [comment]
https://gdrive.excalidraw.com/
Seems not to be maintained or available for the current excalidraw version. 

In general, Google Drive would be a very good replacement/alternative of a storage backend for excalidraw. 
People find and share files with co-workers via Google Drive like any other Google Docs.

There are some early projects like this one: https://github.com/krabhi1/excalidraw-drive 
But it is missing the google drive integration like with the Workspace Addon (https://gdrive.excalidraw.com/)
It is just an early version of the google drive autosame.

However, an auto-save to Google Drive is not really a real-time collaboration!
excalidraw has opensourced its collaboration rooms for this: https://github.com/excalidraw/excalidraw-room 
A rooms-server can also be easily self-hosted similar to the commercial excalidraw+ service.

**The ideal solution would be a combination of both.** 
You create and share excalidraw files on Google Drive. But once you open the Drive File, you immediately create a collaboration room with the UUID of the google drive ID as a unique room ID.  
So, if other people click on the same google drive file, they would not get conflicts in the autosharing, but would have the real-time co-editing experience you are used to with Google drive. 

Maybe somebody who is capable of developing this and has time would pick up this idea. 
Thanks

**Comment by kampiamodikuesto** [comment]
Use google drive to publish excalidraw was an incredible idea. But if i understand correctly the gd addon for excalidraw doesn't work anymore (i get alway an advice for authorization). So the only soluzion is via obsidian publisher or excalidraw+?

**Comment by voronkovm** [comment]
This version can store files on gdrive https://workspace.google.com/marketplace/app/canvsio_whiteboard/766909155776
