### ISSUE TITLE
Move to `deletedIds` map again

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#1030]
It turns out that moving from `deletedIds` map to keeping deleted elements in `elements` array introduced a very large amounts of bugs, some not reported yet, and some we don't even know about. Even if we fix all those, we'll be forever plagued by the fact we need to keep in mind we always need to filter deleted elements outs before consumption.

Some of the issues include:

- rendering/export
- z-index manip
- bounding-box computations (centering scene etc.)
- various interactions (hitbox detection, history management...)
- who knows what else (we'd need to search for `getAllElemenets(` calls and investigate all code paths)

Unless we figure out some miraculous solution, I propose moving back to `deletedIds` map, because whatever complexity it'll add, it'll turn out minor in comparison to current implementation.

Some solutions that we considered but rejected were:

- making `getAllElements` by default return only non-deleted elements:
  - will deteriorate perf, looping over all elements on every access.
  - there are higher-order APIs such as `ActionManager` which pass it to `perform` callbacks of all actions, but some actions need all elements (even deleted), and some don't, so we can't decide for them upstream. Similarly for when passing elements to child components.
- Passing only non-deleted elements to `<LayerUI>`:
  - actually implemented already as a hotfix: https://github.com/excalidraw/excalidraw/pull/1029, but it doesn't solve everything, and may introduce issues of its own, esp. in the future.

/cc @petehunt @vjeux

**Comment by petehunt** [comment]
IMO, I think the correct solution is:
* Rename `getAllElements()` to `getElementsIncludingDeleted()`
* Add a new `getElements()` method which only returns non deleted elements.
* Audit the callsites to call the correct function (most will be `getElements()`).

filter()ing over 8192 elements with the debug console open took 3 hundredths of a millisecond on my mac from a few years ago in Chrome, so I don't think this will be much of a performance bottleneck.

I definitely think we should continue to keep the deletion state in the `ExcalidrawElement` array. As of right now, we have 1 unified way to sync all of the state of the drawing with no special cases. If we were to move back to a `deletedIds` array, I anticipate that we'd have to write a bunch of special-case syncing logic that will be similar-but-not-the-same to what syncs the elements array today which will cause a lot of the multiplayer jankiness that we saw before this refactoring was introduced.

Happy to make the change described above if we're all in agreement.

**Comment by dwelle** [comment]
I disagree. The collab syncing is a small part of the codebase, and that special-case logic would be kept encapsulated to 2-3 places at max. Whereas if we keep them in the array, it'll pollute the whole codebase, and we'll always need to keep in mind that the elements array contains deleted elements, which isn't intuitive.

Separating the `getAllElements` won't help, as I mentioned cases like the `ActionManager` which is agnostic of the the downstream use cases of individual actions. So we'd need to rewrite how `ActionManager` works. This may also apply to different parts of the app.

We'd need to make a thorough review of the codebase to figure out the complete impact.

**Comment by petehunt** [comment]
Here’s an example of what I mean. If two people delete the same element and one of them rapidly undos their delete, we will have a conflict and a race condition. In order to resolve it we will need to reimplement very similar, but slightly different, logic to add a version number to the deleted ids map. If we keep this state in the element itself we can reuse the same conflict resolution that works for everything else, and when we have multiplayer aware undo someday we won’t have to implement it twice.

**Comment by dwelle** [comment]
Yes, but that's a very small price to pay and this complexity will stay in the syncing logic (and maybe in history manager), and that's it. Whereas keeping them in the array forces us to rewrite the whole codebase, and keep this in mind for all days to come.

**Comment by dwelle** [comment]
We also won't be able to do identity checks to bail from react updates and similar since filtering the array will renew it every time.

**Comment by petehunt** [comment]
It’s a bit late here so I need to log off. But what I’ll do is try to send a rough rfc pr that tries to accomplish hiding the complexity from the rest of the app while keeping the state in the array and we can decide if it looks ok or not and make the call. However I do think that the multiplayer feature of excalidraw isn’t something that can be modularized in the way you’re describing. For example, we’ll probably need to completely rewrite the history system to move away from taking state snapshots and towards a command pattern-like architecture for undo to work well in a multiplayer environment. If we want to see other people’s selection state we will fundamentally have to change how that works too. Just my 2 cents though and it’s late so I might be missing something.

**Comment by dwelle** [comment]
I still think it's a mistake, but don't worry, I'm not going to make any rewrites before we reach consensus. So here's some more thoughts.

The history rewrite is unrelated to this --- we can decide to store deleted elements to history even if we keep them separate from `elements`. There are also other considerations, such as z-index handling that will likely force us to have history implementation completely independent of the architecture design of the `elements` array.

Similarly with collab syncing --- we shouldn't inform our architecture based on one spec that can be IMO kept completely separate from other parts of the app (but jury's still out on this one). There may also come other features later that will require completely different mental model, and I don't think collaboration should be the only part that dictates everything.

The memoization consideration is a big one. Right now (production), performance is completely destroyed on larger scenes (or scenes with lots of deleted elements) because the `<LayerUI>` memoization is broken due to filtering out [deleted elements](https://github.com/excalidraw/excalidraw/pull/1029) (granted, this was a hack, but you won't be able to optimize this much, unless you'll want to cache two `elements` arrays (one for all elements, and one for non-deleted elements) that you'll be passing around for memoization purposes --- and then you'd need to take care of cache busting which opens another can of worms. Note: we can't do element comparison, even if we deem it fast enough, because element modification such as during drag would redraw the UI unnecessarily).

There's also the consideration of needing to pass `getAllElements`/`getElementsIncludingDeleted` helpers everywhere in place where we pass `elements` because each part of the app will have different requirements.

And, from then on, devs will need to keep in mind these considerations in mind ("can I pass just non-deleted elements to this compo? Hold on, there's this one callback that takes elements and require deleted ones (or if not, what if someone adds it in a later PR).. ok so I'll pass everything. But then I'll need to ensure the whole component tree filters them out unless needed. And I'll need to implement custom memoization resolving..").

**Comment by vjeux** [comment]
For the custom memoization, you can use the version system we use for syncing to know if something has changed.

**Comment by dwelle** [comment]
The trouble is, we don't want to redraw UI on (most) element modifications.

**Comment by vjeux** [comment]
We could have two versions: ones that redraw and ones that don’t. We used to have this using the history enabling/disabling.

The other consideration is how hard it is to fix/repro. Even though collaboration is one use case compared to the rest of excalidraw which is a lot of use cases, it is way more costly both in terms of experience and debugging to be wrong on the collaboration side than anywhere else in the system.

I am personally in favor of keeping the deleted flag within the element.

**Comment by dwelle** [comment]
> We could have two versions: ones that redraw and ones that don’t. We used to have this using the history enabling/disabling.

Which would be adding even more complexity just to accommodate this design decision. As for history, don't recall, but I think we moved to memoization so that we didn't have to depend on that hack.

Anyway, I'm still not seeing what this design decision solves, and how it outweighs the downsides.

But, it's two against one, so fair enough.

**Comment by petehunt** [comment]
@dwelle I sent a draft PR that will address some but not all of your concerns. Specifically the ones about having to keep track of whether you want to pass in all elements or just non deleted ones all over the place.

@vjeux @dwelle is right that we probably can't use the version system to keep track of these changes for this purpose since we want to invalidate `LayerUI` less often than we bump versions (i.e. when we drag elements around -- I think I'm understanding this correctly?). But I think relying on the identity of the array for this is a bit fragile -- it wasn't clear to me as a newcomer that this was something to consider.
