### ISSUE TITLE
Missing corner handles for multiline

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#1039]
For some reason, it's missing the corner handles. This means that I can't resize a small element.

![image](https://user-images.githubusercontent.com/197597/77239093-e3891d80-6b93-11ea-9be6-caa3c39e4370.png)

![image](https://user-images.githubusercontent.com/197597/77239102-01568280-6b94-11ea-87f6-5ecc61ec50c4.png)

**Comment by dwelle** [comment]
Likely because we remove center handles for small elements which we apply to multi-point elements, too:

![image](https://user-images.githubusercontent.com/5153846/77246538-aa4ebd00-6c28-11ea-8db3-e941ad054db9.png)

**Comment by vjeux** [comment]
We always want the corner ones, and have the inner ones be removed as it gets smaller. But in this case the corners don’t even appear which is the bug

**Comment by dwelle** [comment]
Because arrow/line elements don't have corner handles, only center ones.

**Comment by j-f1** [comment]
Why don’t they have corner handles?

**Comment by dwelle** [comment]
Now that I think of, I don't see much reason. I bet there was one, once. Or maybe it's even a regression :).
