### ISSUE TITLE
Undoing a delete does not restore selection state

### ISSUE THREAD

**Issue by petehunt** [excalidraw/excalidraw#1042]
Steps to repro:
* Draw a few shapes
* Select a subset of them
* Delete
* Ctrl-z

Expected: the previously deleted shapes are selected
Actual: the previously deleted shapes are added back to the canvas but are not selected.

**Comment by Shriram-Balaji** [comment]
@dwelle I'd like to take a stab at this. Also, it looks like the behavior occurs even in there's a single shape, and doesn't seem to be specific to be for more than one shape.

**Comment by dwelle** [comment]
@Shriram-Balaji let's do it!

I wanted to give you some pointers and it looks like it's as easy as adding a line here:

https://github.com/excalidraw/excalidraw/blob/2bfc1c20b6676efa369464fbb29563ddc31f6087/src/appState.ts#L65-L80

You can investigate if there aren't any side effects, and make the PR :).

**Comment by Shriram-Balaji** [comment]
@dwelle Thanks for the pointers, I just figured it out as well. The codebase is neatly structured, and it was quite straightforward for a new contributor to start of with :smile:
