### ISSUE TITLE
Add a translation for Hungarian

### ISSUE THREAD

**Issue by andrasbacsai** [excalidraw/excalidraw#1044]
I can help to translate it to Hungarian. Love the app!

**Comment by j-f1** [comment]
Here you go: https://crowdin.com/translate/excalidraw/10/en-hu

Let us know when you’ve got enough translated for it to be useful to add to the language dropdown in the app and we’ll be happy to do so!

**Comment by andrasbacsai** [comment]
Thanks! I already finished it! :smile:

**Comment by lipis** [comment]
#1043

**Comment by j-f1** [comment]
What text should we put in the language dropdown for Hungarian?

**Comment by j-f1** [comment]
It looks like @lipis put in “Magyar” but we can update that if it’s incorrect.

**Comment by andrasbacsai** [comment]
That is totally good!
