### ISSUE TITLE
Design question: understanding why this was done in canvas

### ISSUE THREAD

**Issue by rgangopadhya** [excalidraw/excalidraw#1051]
Hi there, thank you for this great project! I really like the focused UI here. I, like many others, found this through HN and I was especially interested given that my team is working from home these days with the current state of the world.

So, I am interested in contributing. Currently, I am playing around with the source code a bit, mainly in service of this issue https://github.com/excalidraw/excalidraw/issues/755 and https://github.com/excalidraw/excalidraw/issues/791.

As I was looking through the source, I realized that a lot of the complexity comes from managing canvas state, which something like a pure SVG approach might not suffer from as much. I understand of course that the app has already been written using canvas and a ton of great work has been done, but more curious as someone new here -- why was canvas chosen over SVG as an initial approach? My sense is that SVG is better-suited for a small number of simple elements.

I think the main reason was to provide the experience of hand-rawn shapes and text, which is much easier to do in canvas via Rough.js. From a user experience perspective, I wonder how much of this could be done using SVG filters, and whether that would be a better trade-off for performance and maintenance. Given explorations like [this one](https://heredragonsabound.blogspot.com/2020/02/creating-pencil-effect-in-svg.html), definitely seems like a non-trivial effort to reproduce that hand-drawn experience in SVG, but perhaps worthwhile. And, we are exporting to SVG already, so likely that is not too bad already?

To be clear, I'm not suggesting that converting to SVG is something that should be done. It would definitely be a lot of work to make that conversion, if it could be done. For my understanding and education, I was curious why canvas the choice for implementation.

**Comment by vjeux** [comment]
I've heard all those horror stories of people doing data visualization in SVG and suffering from bad performance, then having to switch to canvas or webgl. I decided to go with canvas right away not to be in a bad situation.

At this point, the rendering code is relatively well abstracted away so it shouldn't be too hard to switch to a svg rendering (which rough.js provides and we use to export to svg) to see if there are any material wins to be had. If you or someone else wants to try it out and see if performance is better, please be my guest!

**Comment by vjeux** [comment]
I personally want to play with a webgl renderer for excalidraw when I get some motivation and time.

**Comment by rgangopadhya** [comment]
Thanks for the fast response! I've had good experiences with SVG in data visualization, but using a smaller number of elements (< 1000), but not a ton outside of that, so defer to your knowledge there.

The bigger benefit to me is whether the code would start to look more like a traditional React app: because SVG elements are just DOM elements, you would have all of the event handling and such for free, and could express the app as a set of React components without too much in the way of . So I actually expect the code itself to become simpler. This is just from spending a little bit of time poking around, having not fully grokked the source yet, though.

**Comment by dwelle** [comment]
If each element (shape) was its own DOM element with click/drag etc. handlers, that would not scale at all, and I don't believe it would help in code complexity either.

**Comment by rgangopadhya** [comment]
Thanks for the feedback @dwelle, I'll spend some more time with the source to make sure I understand the origin of the complexity better, then. Closing

**Comment by vjeux** [comment]
In terms of complexity, there are a few things going on:
- Hit testing. I don't know if we can get mouse events based on svg paths with a 10px padding. That would remove some complexity to let the browser handle it.
- Shape caching. In order to avoid re-computing the roughjs svg paths on every render we compute it once and cache it. This will need to stay.
- Canvas caching. Instead of painting the elements on every render, we draw it once and then copy the pixels. We won't technically need it but we'll likely want something similar for svg.

I don't see anything else that would change if we use svg rather than canvas.

My guess is that you're unfamiliar with how the code is structured but I don't think that switching to SVG would drastically change the complexity of the application.

**Comment by rgangopadhya** [comment]
Thanks @vjeux, I really appreciate your kindness in explaining. Now I can read the source with more understanding about the problems you are trying to solve there. Thank you!

**Comment by dwelle** [comment]
We should maybe keep a rough explanation of how Excalidraw works (and description of the codebase) in `CONTRIBUTING.md`.

**Comment by rgangopadhya** [comment]
Yeah, that would be super helpful. I think part of my goal will be to write up a description of the system myself. I'll share that (it'll likely have holes) and maybe that can be a seed. That said, someone else much more familiar with the system would be a better candidate, but happy to help as it definitely would have helped me!

**Comment by yashrsharma44** [comment]
Hi, I was quite curious about understanding the codebase, so wondering do we have any documentation for studying the whole architecture?
