### ISSUE TITLE
Zooming with large numbers of elements is slow

### ISSUE THREAD

**Issue by petehunt** [excalidraw/excalidraw#1056]
Repro:

* Load a [big file](https://drive.google.com/open?id=1Yb4UPBiHVXQMmqMN73tirl2zHkKlabE3) into excalidraw
* Pinch to zoom in and out

**Comment by dwelle** [comment]
Very likely due to the perf regression caused by rerendering UI on every element modification (caused by passing new array of elements to `<LayerUI>` as I pointed out previously.

**Comment by j-f1** [comment]
Yikes, that’s really bad

**Comment by dwelle** [comment]
I take it back, it's not due to UI rerendering (which *is* rerendering, but was always due to `appState.zoom` change), but likely because zooming clears elements cache.

**Comment by vjeux** [comment]
The way the browser handles those kind of "smooth" zoom transitions is to keep the wrongly sized canvas element and do dynamic resizing. Then, on a debounce recomputes the properly sized canvas and do one more rendering.

I believe that we can do the same here.

**Comment by petehunt** [comment]
I think this is a big contributor: https://github.com/excalidraw/excalidraw/blob/master/src/renderer/renderElement.ts#L248

If I remove the `canvasZoom !== zoom`, the UI gets very snappy (but it becomes buggy). We should probably scale the canvas while zooming and then redraw when the zoom is completed.

**Comment by dwelle** [comment]
That's the idea, except I'm not sure if doing so is gonna be easy, or won't introduce ugly hacks. Right now we're simply updating state. We'd need to delay elements rendering on zoom (e.g. schedule it for next tick).

**Comment by j-f1** [comment]
Here’s an example of the native pinch-zoom in Safari (slowed down for clarity). Note that it doesn’t re-render the text until you stop zooming.

![My Movie 2](https://user-images.githubusercontent.com/25517624/77374072-30115c00-6d40-11ea-8888-094c8358e9eb.gif)

**Comment by vjeux** [comment]
If someone wants to give it a shot shouldn’t be too hard:
- Add a field zoom next to every cached canvas that tells at that zoom level it was cached
- tweak the draw operation to use both the current zoom level and the cached zoom level
- remove the cache busting line on zoom change
- add a debounce around the multi finger onTouchUp to reset the cache
- reset the cache when clicking the +/- directly (or key binding)

**Comment by vjeux** [comment]
Here's the big file #json=6295615189286912,tdPzpRsPvL3FPt7FZ0KrbQ
