### ISSUE TITLE
Brave: Export as PNG (to file/clipboard) broken in special cases

### ISSUE THREAD

**Issue by mbomb007** [excalidraw/excalidraw#1061]
Nothing happens when I click "Copy to clipboard" in the Export popup. Pasting in a text file doesn't paste anything, and pasting in Excalidraw doesn't either. It just pastes whatever was in the clipboard before I clicked the button.

**Comment by lipis** [comment]
What's your browser?

**Comment by mbomb007** [comment]
[Brave](https://brave.com/) - Version 1.5.115 Chromium: 80.0.3987.149 (Official Build) (64-bit)

**Comment by Fausto95** [comment]
I have Chrome with version `80.0.3987.149 (Build officiel) (64 bits)` and it works for me.
Is this a Brave issue?

**Comment by dwelle** [comment]
@mbomb007 the copy button in export copies a PNG, so you can't paste it in a text file. The tooltip should definitely explain what it does.

**Comment by dwelle** [comment]
Tried in latest Brave and works as intended. I'll update the button label, otherwise it should be fine.

**Comment by mbomb007** [comment]
It doesn't work if I try it paste it in Outlook or Word, though. As I said "It just pastes whatever was in the clipboard before I clicked the button", which means nothing was copied from Excalidraw.

**Comment by mbomb007** [comment]
> Tried in latest Brave and works as intended. I'll update the button label, otherwise it should be fine.

Brave has many different settings. Maybe it only works with certain configurations.

**Comment by dwelle** [comment]
> It doesn't work if I try to paste it in Outlook or Word, though. As I said "It just pastes whatever was in the clipboard before I clicked the button", which means nothing was copied from Excalidraw.

Oh, I thought that was related to pasting into excalidraw

> Do you have to have 3rd party scripts allowed?

Absolutely not.

> My "Clipboard" access setting is set to "Ask before accessing". But adding Excalidraw as a exception doesn't help.

Shouldn't be a problem. Writing to a clipboard shouldn't prompt for permissions, but even if it did, it should ask. Lemme see.

**Comment by mbomb007** [comment]
I found the cause of the issue. The "Disable HTML5 Autoplay" extension causes the copying to not work for some reason. Does the copy button require autoplay?

**Comment by dwelle** [comment]
> The "Disable HTML5 Autoplay" extension causes the copying to not work for some reason. Does the copy button require autoplay?

Not that I know of. We use [Async Clipboard API](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard_API), which is specced, but implementation in browsers is still not settled.

**Comment by tomayac** [comment]
The Async Clipboard API definitely has nothing to do with `autoplay`. I also can't reproduce this on Brave version 1.5.115 Chromium: 80.0.3987.149 (Official Build) (64-bit) with the [extension](https://chrome.google.com/webstore/detail/disable-html5-autoplay/efdhoaajjjgckpbkoglidkeendpkolai/) installed. Probably something else. 

@mbomb007, can you try the [demo](https://async-clipboard-demo.glitch.me/) and report back?

**Comment by mbomb007** [comment]
Never mind about the extension. I tried disabling every extension and it still didn't work. The demo works for me, but Excalidraw still didn't.

The cause is actually Brave's "Shield".

![image](https://user-images.githubusercontent.com/22807401/77333964-2e20ac00-6cf2-11ea-8797-7229fdd16885.png)

**Comment by dwelle** [comment]
That blocks our Google Analytics, and is definitely not the cause:

![image](https://user-images.githubusercontent.com/5153846/77334182-c041a800-6d24-11ea-9c32-10d1214859ae.png)

**Comment by tomayac** [comment]
I get the same Shield thing. None of this is handled in Google Tag Manager.

**Comment by tomayac** [comment]
<img width="349" alt="Screen Shot 2020-03-23 at 16 38 22" src="https://user-images.githubusercontent.com/145676/77334259-d94a5900-6d24-11ea-8d1b-4011dc1de2bf.png">

**Comment by mbomb007** [comment]
You're right, when clicking the "copy" button, it blocks a separate script.

![image](https://user-images.githubusercontent.com/22807401/77334360-ad15e480-6cf2-11ea-9267-412e8f0a6fb1.png)

**Comment by mbomb007** [comment]
Changing "All device recognition blocked" to "Cross-site device recognition blocked" seems to work.

**Comment by dwelle** [comment]
Now I can repro. I had to set this manually:

![image](https://user-images.githubusercontent.com/5153846/77334750-84f3a900-6d25-11ea-9fd4-cb50e435e315.png)

**Comment by dwelle** [comment]
Also I have no clue why changing a reporting setting changes actual browser behavior.

Also, this not only disabled copy-png, but also save as PNG.

**Comment by mbomb007** [comment]
My setting was already on "cross-site blocked", but I had to manually change it, then change it back for some reason.

**Comment by tomayac** [comment]
This is interesting, since clipboard isn't listed in [Brave's fingerprinitng protections](https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections). This is probably worth filing a Brave issue for (please link it here).

**Comment by dwelle** [comment]
It's prob best if we file it ourselves, linking to the code in question. I can do it later.

**Comment by tomayac** [comment]
Canvas fingerprinting is definitely something they [try to prevent](https://github.com/brave/brave-browser/wiki/Fingerprinting-Protections#fingerprinting-methods-randomized-with-fingerprinting-protection-mode).

**Comment by mbomb007** [comment]
It should be noted that using "Canvas Fingerprint Defender" on Chrome does not break export.

**Comment by dwelle** [comment]
This should be fixed by now. @mbomb007 lemme know if you're still experiencing any problems.
