### ISSUE TITLE
Memoize shareable links

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#1065]
When creating shareable link for a scene, we should optimize it so that we don't create new and new links for the same scene (mainly to conserve server space).

This can happen in cases when the user creates a link, but forgets to copy it (or closes the dialog, or overwrites the clipboard...) and then needs to create the link again to retrieve it.

## implementation

On first creation, cache the link and keep it until user modifies the scene in any way. We don't necessarily need to track changes, we can just hash the `appState` combined with `elements` to figure out if change occurred (suggested by @lipis).

## caveats

If we wanted to retain the ability to generate different link even for the same scene (for some edge case, though not sure which one), then we can have a separate button for it. But for a start I think we can do without it.

**Comment by dwelle** [comment]
Another avenue for optimization is to make scenes created from external domains (e.g. `localhost`) live only temporarily.

**Comment by lipis** [comment]
I think we can skip optimize it for localhost.. storage is cheap.

**Comment by dwelle** [comment]
If we disregard storage considerations, then what's left is latency+processing time when generating links. Is that what you meant to optimize with this issue?

**Comment by lipis** [comment]
No I meant that tests from localhost are significantly less from the actual usage..

**Comment by vjeux** [comment]
I wouldn't spend time thinking about this. The server-side part of it is cheap including storage. For the client, it seems like it takes a second or so to save so also not really a huge issue.

**Comment by dwelle** [comment]
> No I meant that tests from localhost are significantly less from the actual usage..

You haven't seen me in action :).

> I wouldn't spend time thinking about this. The server-side part of it is cheap including storage. For the client, it seems like it takes a second or so to save so also not really a huge issue.

Ok, I'm closing this then.
