### ISSUE TITLE
Write a test for z ordering including deleted elements 

### ISSUE THREAD

**Issue by petehunt** [excalidraw/excalidraw#1069]

**Comment by vjeux** [comment]
Quick and easy fix for that would be to include both selected elements AND deleted elements ids to be moved. It’ll do a few more manipulations but should be correct

**Comment by dwelle** [comment]
Much easier is to simply ignore the deleted elements.

**Comment by vjeux** [comment]
How do you “ignore” them when mutating the array indices?

**Comment by dwelle** [comment]
I meant as described inhttps://github.com/excalidraw/excalidraw/issues/989 --- maybe I'm misunderstanding what you meant.

**Comment by petehunt** [comment]
fixed in #1077, thanks @dwelle !
