### ISSUE TITLE
Https certificate problems

### ISSUE THREAD

**Issue by nanot1m** [excalidraw/excalidraw#107]
I have a problems while accessing website via safari

![61162FEB-67D2-4406-AA0E-D8C81B3ADE69](https://user-images.githubusercontent.com/9278185/71765037-5548b800-2f11-11ea-9b90-6fb93f502e61.png)

**Comment by vjeux** [comment]
Is it still an issue? Seems to be working fine for me

**Comment by nanot1m** [comment]
It's working now!

**Comment by dwelle** [comment]
Ok, so there seems to be a problem when accessing the bare-domain via `https://` -- it doesn't redirect to https, which results to the aforementioned connection-not-secure error.

- https://www.excalidraw.com/ :heavy_check_mark: 
- http://www.excalidraw.com/ :heavy_check_mark:
- http://excalidraw.com/ :heavy_check_mark: (redirects to https)
- https://excalidraw.com/ :x: (doesn't redirect to https)

**Comment by dwelle** [comment]
Reminder that this is still an issue stopping people in their tracks: https://mobile.twitter.com/functiondog/status/1214148490772832256

**Comment by vjeux** [comment]
I’ll take a look in a few hours

**Comment by vjeux** [comment]
Is it still an issue?

**Comment by nanot1m** [comment]
Yes, It's still reproducing

**Comment by vjeux** [comment]
What are the repro steps?

**Comment by nanot1m** [comment]
Trying to access https://excalidraw.com/ with safari leads to connection not secure error

**Comment by vjeux** [comment]
Ok, I can reproduce now!

**Comment by vjeux** [comment]
I just created a ticket for github, hopefully they will be able to help, I'm not really sure how to troubleshoot.

**Comment by vjeux** [comment]
Someone from Github was helpful in confirming that this is indeed a problem. I'm waiting for a reply to see if they have suggestions on how I should go about fixing it.


> Thanks for reaching out about this! We don't currently support creating a certificate that covers both your root domain and your www subdomain. We only generate a certificate for the exact domain that you specify in the custom domain input box. I will add your +1 to that feature request internally though!

>Keep in mind that this redirect will only work when using a protocol-less or http:// link.

> Typing excalidraw.com, https://www.excalidraw.com or www.excalidraw.com will load properly, but if you explicitly specify **https://**excalidraw.com/ you will still encounter a certificate error.

**Comment by dwelle** [comment]
Bad GitHub :). I thought LetsEncrypt already supports wildcard certificates to make this easier for them.

**Comment by vjeux** [comment]
Github got back to me saying that they can't have both www and non www in the same certificate. So we're basically out of luck. The rep brought this up to the product team.

I think in the meantime we should move to zeit or netlify. Too bad because I like github pages and it's almost working correctly.

**Comment by vjeux** [comment]
We moved to netlify, it should be working now.

**Comment by dwelle** [comment]
Awesome!
