### ISSUE TITLE
Instructions for complete self hosting?

### ISSUE THREAD

**Issue by ml-eds** [excalidraw/excalidraw#1078]
Hello,

this is truly a great project. Thank you!

Are there instructions how to completely self-host excalidraw?

As I see it, we have

- excalidraw - frontend
- excalidraw-json - json push/pull server
- excalidraw-room - websocket server

In [src/data/index.ts](https://github.com/excalidraw/excalidraw/blob/master/src/data/index.ts#L22) you need to adjust the following configuration constants to point to the self-hosted machines:

```
const BACKEND_GET = "https://json.excalidraw.com/api/v1/";

const BACKEND_V2_POST = "https://json.excalidraw.com/api/v2/post/";
const BACKEND_V2_GET = "https://json.excalidraw.com/api/v2/";

export const SOCKET_SERVER = "https://excalidraw-socket.herokuapp.com";
```

Is this correct? 

Anything else (e.g. other external dependencies) to consider? 

If the self-hosting process will get sufficiently clear to me, I will be more than glad to contribute a PR extending the README.md with instructions for it (if you want me to).

Marc

**Comment by petehunt** [comment]
hi @ml-eds,

we're definitely motivated to make this easily self hostable. i think ideally we would publish a `docker-compose.yml` to make it very easy to stand up a staging version of excalidraw.

that should be pretty easy to do with `excalidraw` and `excalidraw-room`, but i think we would need to migrate `excalidraw-json` to some data store other than google app engine NDB in addition to everything that you listed above.

**Comment by mapbakery** [comment]
Does anybody already have done a complete self-hosted (preferably with Docker) installation of excalidraw?

**Comment by mhoyer** [comment]
@mapbakery, this is my quick hack to make it run locally as docker container:

### Dockerfile

```Dockerfile
FROM node:13-alpine AS build
  RUN apk --no-cache add git

  WORKDIR /app

  ARG COMMIT_REF=master
  RUN git clone --depth=1 --branch=$COMMIT_REF https://github.com/excalidraw/excalidraw.git . \
    && rm -rf .git

  RUN npm install
  RUN npm run test:all
  RUN npm run build:app

FROM nginx:1.17-alpine AS runtime
  COPY --from=build /app/build/ /usr/share/nginx/html
```

### docker-compose.yml

```yaml
version: '3'
services:

  excalidraw:
    build: .
    container_name: excalidraw
    ports:
      - "8080:80"
    restart: always
```

I hope this helps and maybe is a first step to produce a regular docker image as part of this wonderful project? I guess then a proper versioning of the source and docker images is essential.

**Comment by mapbakery** [comment]
@mhoyer Thanks! I'm going to find someone who can test it (I can't test it myself)

**Comment by perryrh0dan** [comment]
It would be soo awesome to self host excalidraw together with excalidraw-json.

**Comment by xeruf** [comment]
See https://github.com/excalidraw/excalidraw/issues/1772
