### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by Fausto95** [excalidraw/excalidraw#109]
Since many of us liked the logo proposed by @vjeux on this comment https://github.com/excalidraw/excalidraw/issues/68#issuecomment-570647168

I started working on something similar
![Excalidraw](https://user-images.githubusercontent.com/23306911/71765346-d3966180-2ef3-11ea-8092-356daf4cbc6b.png)

**Comment by vjeux** [comment]
Can you try using rough to render it by any chance? :)

**Comment by Fausto95** [comment]
> Can you try using rough to render it by any chance? :)

Yes

**Comment by Fausto95** [comment]
Btw I picked the same font we use in the app

![excalidraw-rough-rendered](https://user-images.githubusercontent.com/23306911/71766793-3ee82f80-2f04-11ea-84a6-1388187de2ac.png)

[Code](https://codesandbox.io/s/admiring-mountain-rb8yf)

**Comment by dwelle** [comment]
Would prob lower roughness to 1.5 or something, and handpick the best, otherwise, good job. :heart: 

![image](https://user-images.githubusercontent.com/5153846/71767334-a2c22680-2f0b-11ea-9bb3-6ade8e5471e4.png)

**Comment by Fausto95** [comment]
With less roughness(1.5)

![Excalidraw-rough-3](https://user-images.githubusercontent.com/23306911/71767498-1d3f7600-2f0d-11ea-9f8e-c0e2e8be8dff.png)
