### ISSUE TITLE
Load automatically the correct locale

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw#1092]
The best match from the `navigator.languages`

On the first load.. when and if changed later should keep the selected language.

**Comment by kbariotis** [comment]
@lipis is there an issue with the current implementation. I see the `LanguageDetector` [plugin](https://github.com/excalidraw/excalidraw/blob/master/src/i18n.ts#L81) will use `navigator` to select the appropriate language.

**Comment by lipis** [comment]
hmmm.. I just (wrongly) assumed that we don't have that in place.. :)

**Comment by lipis** [comment]
It actually works! :)
