### ISSUE TITLE
Are there plans to develop applications???

### ISSUE THREAD

**Issue by SecretCastle** [excalidraw/excalidraw#1093]
It's an awesome web project, I can't wait for that. haha

**Comment by dwelle** [comment]
There's a work-in-progress desktop app https://github.com/excalidraw/excalidraw-desktop. No plans for mobile apps if I'm aware.

**Comment by j-f1** [comment]
I started on a mobile app for iOS a while back, but it seems like Apple might not be allowing apps that are mostly a web app on the App Store after a preliminariy rereading of the App Store guidelines.

**Comment by lipis** [comment]
Progressive Web App for mobiles :)
