### ISSUE TITLE
Do hit detection on mouse move

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#110]
We don’t need to wait for a mousedown to check if there’s something under the cursor. If we highlight on mousemove it’ll make the app feel faster and less error prone, same way we did when we start selecting it shows before we mouseup

**Comment by dwelle** [comment]
How do you intend to highlight the element? Change its stroke color (what about elements with different stroke colors)? I'd not highlight by showing the selection border, which would make it unclear what's selected and not.

**Comment by nanot1m** [comment]
Maybe we can draw the same shape with roughness = 0, smaller stroke width and colored in blue?

**Comment by dwelle** [comment]
> Maybe we can draw the same shape with roughness = 0, smaller stroke width and colored in blue?

That would often not closely follow the original shape, I reckon.

**Comment by dwelle** [comment]
But I guess we could in fact draw the selection border, but in much lighter gray color than the actual selection.

**Comment by vjeux** [comment]
Fixed by #280
