### ISSUE TITLE
Text is incorrectly offset when zoomed in

### ISSUE THREAD

**Issue by gaearon** [excalidraw/excalidraw#1100]
1. Draw a rect
2. Pinch to zoom
3. Double click its center to edit text

Expected: text is edited in the center
Actual: text is edited with an offset and then jumps to center

![ezgif-2-f841cabcfee2](https://user-images.githubusercontent.com/810438/77833579-61ba6680-7136-11ea-9836-65f295dff024.gif)

**Comment by vjeux** [comment]
I can reproduce, looking into it right now
