### ISSUE TITLE
keyboard shortcuts for formatting pane

### ISSUE THREAD

**Issue by vullankib** [excalidraw/excalidraw#1104]
The Shape selection and color selection keyboard shortcuts are really helpful and was thinking as an enhancement, if we can have keyboard shortcuts for formatting pane, would be amazing for increasing the speed at which the drawings can be made and during collaborating. 

btw, I fell in love with this tool and would be happy to contribute. 

![image](https://user-images.githubusercontent.com/19988462/77836877-1436fd00-7128-11ea-9738-d0d6f1e2e447.png)

**Comment by vjeux** [comment]
Agreed, that would be great! There are a lot of options in there, I wonder if you have ideas on how to assign key bindings for all those.

**Comment by vullankib** [comment]
I can make initially suggestions here with screenshots on the assignment of key bindings and if you like we can take it from there.

**Comment by vjeux** [comment]
Sounds like a plan!

**Comment by vullankib** [comment]
![image](https://user-images.githubusercontent.com/19988462/77870095-1c656a00-7206-11ea-8768-dbded6b436cf.png)
Thanks for waiting... Here are 2 suggestions I could come up with and please let me know your inputs and I have compared with existing tools as well to see how this aligns. Another suggestion which I didn't include is to have a combination of Keys with Suggestion 1: with Shift or some other options.

**Comment by vjeux** [comment]
Arrgg, sorry I haven't replied earlier. This is great! Looks like you found a key for each setting, and also have them on the left side of the keyboard! Please do add them :)

**Comment by lipis** [comment]
Closing this in favor of #2649 where I gathered all the information from this issue.
