### ISSUE TITLE
Weird behavior when resize + shift a 2-point line

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#1106]
Repro steps:
- Create a 2 point line
- Hold shift
- Start resizing the line from the first point you created
- Move the cursor around, see it jumping all over the place

![ezgif-7-12af98688ab5](https://user-images.githubusercontent.com/197597/77837508-fca74680-711e-11ea-8abd-4c71a25178f5.gif)

**Comment by jquintozamora** [comment]
Hello @vjeux ,
I created a new branch and solved this issue, but when I try to push I'm getting Permissions denied issue.

**Comment by lipis** [comment]
Can you fork this repo under your own account and create branch there? Then the GitHub UI will suggest a PR here.

**Comment by jquintozamora** [comment]
Thanks @lipis !
