### ISSUE TITLE
Middle mouse button behavior is broken

### ISSUE THREAD

**Issue by petehunt** [excalidraw/excalidraw#1108]
Steps to repro:
* Load excalidraw.com in win10 chrome
* Click and hold middle mouse button. Do not move mouse.

Expected: no movement of canvas
Actual: canvas rapidly scrolls

**Comment by dwelle** [comment]
Cannot repro on win7 chrome.

**Comment by vjeux** [comment]
I can't repro either on window 10 home edition + Chrome

**Comment by lipis** [comment]
I can reproduce it on a Mac + Chrome, and Logitech mouse with a scroll.. :)

**Comment by janriemer** [comment]
I can't reproduce either on Linux Kubuntu 18.04 + Firefox. @lipis  @petehunt Does the app needs to be in a certain state for this to happen (e.g. shapes drawn on the canvas)?
