### ISSUE TITLE
Ability to set names

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#1113]
Right now we only display cursors but when you're more than 2, it helps having names attached next to the cursor. We have most of the implementation ready, just need to be able to edit the actual name. https://github.com/excalidraw/excalidraw/pull/971

**Comment by kbariotis** [comment]
@vjeux how are you thinking about this? Should we allow each user to edit their name and that will be display on the cursor on each end of the rest of the collaborators?

Could we generate random names maybe?

**Comment by vjeux** [comment]
If you want more on your plate in the same area, https://github.com/excalidraw/excalidraw/issues/1109 is the last thing that is really annoying me with live collaboration!

**Comment by lipis** [comment]
By the way.. the #1175 seems to be done.. is there anything missing?! If we are happy with the double circle we can merge it.

**Comment by dwelle** [comment]
I'm laying the ground work for #1109.

**Comment by lipis** [comment]
@kbariotis you're off the hook for the #1109 it seems :)
