### ISSUE TITLE
Can I add a multi-language cursive font?

### ISSUE THREAD

**Issue by hmmhmmhm** [excalidraw/excalidraw#1114]
Hello, I would like to add a korean cursive font to this page.
May I do this and post a Pull Request?
If possible, I wonder if these multilingual fonts have been done before.

**Comment by lipis** [comment]
We are not planning to change or add a new font, but in the past we improved our support for other languages... https://github.com/excalidraw/excalidraw/pull/720 not sure how easy it is to add Korean support there :)

**Comment by hmmhmmhm** [comment]
OK, Thank you for letting me know.

**Comment by j-f1** [comment]
We could always add a fallback font in our font stack for the Korean characters.
