### ISSUE TITLE
Add stats for nerds for debugging

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw#1119]
and not only for debugging.. some people are interested in seeing more things..

YouTube has it:

<img width="502" alt="Screenshot 2020-03-29 at 1 21 36 AM" src="https://user-images.githubusercontent.com/125676/77850587-3f7b2400-71dc-11ea-9775-1ed4f2b09d24.png">

----

So we could add it in our right click menu.. and show things like:

- FPS
- Total number of elements
- Size dimension of the current scene (the bounding box of all elements)
- Size (in JSON bytes)
- Extra size in PNG/SVG when embedding the scene
- More things :)

**Comment by dwelle** [comment]
Partially overlaps with https://github.com/excalidraw/excalidraw/issues/968 (e.g. the FPS, total number of elements, JSON size could be used during development/debugging).
