### ISSUE TITLE
New feature: Link tiers app with Excalidraw

### ISSUE THREAD

**Issue by davidbonan** [excalidraw/excalidraw#1124]
Hi !

I make a website of live stream for a special domain and i want a whiteboard inside my app (collaboration with webRTC and socketIO one-to-one) so I have two choices : 
- Make my own whiteboard with poor support...
- Provide en link to Excalidraw but every user need to create and share session

So, I propose to provide an API or a shortcut in Excalidraw to automate create peer session and link it on tiers app.

In this time, many app like mine want that feature i think ;)

What do you think ?

**Comment by vjeux** [comment]
In order to create a session you just need to generate a link of this form:

```js
https://excalidraw.com/#room=[0-9a-f]{20},[a-zA-Z0-9_-]{22}
```

Example:
```js
https://excalidraw.com/#room=91bd46ae3aa84dff9d20,pfLqgEoY1c2ioq8LmGwsFA
```

**Comment by davidbonan** [comment]
It's no security to provide a custom link without access to it on Excalidraw ? So great !!! Thanks for all !

**Comment by vjeux** [comment]
The first set of digits is the room. This is visible from the server that's going to dispatch messages to everyone that knows this number.

The second set of digits is the encryption key. The excalidraw server doesn't know about it. This is what all the participants use to encrypt/decrypt the messages.

**Comment by vjeux** [comment]
We should document this somewhere. cc @lipis, @dwelle

**Comment by davidbonan** [comment]
@vjeux I make a npm package for embed a link with id and key ! https://www.npmjs.com/package/excalidraw-share-peer-link

**Comment by kbariotis** [comment]
@davidbonan great work you did there! thank you.

@lipis made [a great effort already](https://github.com/excalidraw/excalidraw-howto/blob/master/content/howto/create-collaboration-session-manually.md) on this. I wonder what's the state of the how-to site. Can I help @lipis ?

**Comment by lipis** [comment]
As far as I know, it's just an idea.. https://github.com/excalidraw/excalidraw-howto waiting for some more docs to be filled in :)
