### ISSUE TITLE
Panel overflows offscreen

### ISSUE THREAD

**Issue by gaearon** [excalidraw/excalidraw#1127]
Select both text and a shape. The details panel overflows offscreen so I can't adjust opacity.

<img width="404" alt="Screenshot 2020-03-30 at 00 50 52" src="https://user-images.githubusercontent.com/810438/77864469-960a5180-7220-11ea-853e-6410efeaa4d2.png">

**Comment by yongdamsh** [comment]
Since shape actions are increasing, I think we should solve this issue. How about this way?

![panel_overflow](https://user-images.githubusercontent.com/4126644/78179339-01138c80-749c-11ea-9876-fe97fec919fd.gif)

**Comment by vjeux** [comment]
@yongdamsh thanks! Adding an overflow scroll makes sense to me!

**Comment by lipis** [comment]
And we should stop adding more things to this panel :)
