### ISSUE TITLE
Zen Mode

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#1128]
If you’re drawing a black and white scene, you almost never need to use the left menu, the zoom selector (key bindings), language selector, github corner, export... the only thing that’s useful is the list of shapes.

Would be nice to have a zen mode that hides everything so that you’re focused on drawing and not distracted.

I’m not 100% sure how the UI would look like, maybe a “full screen” icon somewhere and animating out all the elements like drawers. Ideas welcome.

Thanks to @gaearon for the idea

**Comment by j-f1** [comment]
Maybe drop the box shadow too?

<img width="834" alt="Screenshot_2020-03-30 09 57 43" src="https://user-images.githubusercontent.com/25517624/77920824-f45d2180-726c-11ea-9df7-b1dfb949dbef.png">

alternate style:
<img width="732" alt="Screenshot_2020-03-30 10 01 54" src="https://user-images.githubusercontent.com/25517624/77921274-8cf3a180-726d-11ea-92bc-65c5d9cb1862.png">

**Comment by gaearon** [comment]
Need to check how it feels. :-)

**Comment by lipis** [comment]
I like the less is more version (the first one without the box shadow).. Maybe dropping it completely? (We need a designer)

**Comment by vjeux** [comment]
I like the shapes section without the drop shadow.

**Comment by ad1992** [comment]
This looks interesting somewhat like distraction-free mode and I was looking for something like this. Can I pick this up?

**Comment by dwelle** [comment]
Go for it!
