### ISSUE TITLE
Add stroke style: `solid`, `dashed`, `dotted`

### ISSUE THREAD

**Issue by hepin1989** [excalidraw/excalidraw#1129]
![image](https://user-images.githubusercontent.com/501740/77881089-bc67d580-7290-11ea-98bd-9a7d70eab867.png)
I want this to be dot line.

**Comment by dwelle** [comment]
If anything, I think we should support ~3 line types for every shapes (including arrows/lines): `solid`, `dashed`, `dotted`.

**Comment by tychota** [comment]
@dwelle Is it something a new contributor can potentially contribute or it is complex/very-complex.

I may be interested in chiming in providing it takes a reasonable time and I have some guidance.

**Comment by dwelle** [comment]
I think it needs to implemented upstream in [roughjs](https://github.com/pshihn/rough) (/cc @pshihn), but before that we should figure out how we'd implement it UI-wise. Do we another set of 3 buttons in the menu under `Stroke style`, or should we come up with a different solution with respect to our simple-UI & do-not-become-another-photoshop principle?

**Comment by pshihn** [comment]
You don't need much to implement the basic version of this, because canvas itself provides the `setLineDash` method and can be used with roughjs without making any changes, especially if you want to affect only the shape outline (not the fill)

e.g.
```javascript
// square
rc.rectangle(10, 10, 200, 200);
    
// dashed square
ctx.setLineDash([20, 10]);
rc.rectangle(280, 10, 200, 200);
```

![Screen Shot 2020-04-19 at 3 27 52 PM](https://user-images.githubusercontent.com/833927/79701551-e0488680-8252-11ea-9c4a-0bf140f533b6.png)

live: https://glitch.com/~sunny-polydactyl-friday

**Comment by dwelle** [comment]
That's cool. Ok, so what remains is figuring out how we want to implement this, UI-wise.

**Comment by lipis** [comment]
Should also support all shapes (including lines, arrows, random shapes)

**Comment by garyelephant** [comment]
+1

**Comment by gaearon** [comment]
I imagine "Stroke": "Solid / Dashed" as options next to "Sloppiness". Really miss this feature.

**Comment by dwelle** [comment]
Because this fits to Excalidraw very well (design-wise), I'll look at this, and add them to the UI as you suggest. Though long-term, we should maybe think of another solution, because we're adding too many buttons to the menu.

**Comment by ooker777** [comment]
can we have this for pencil as well?
