### ISSUE TITLE
Shape fillStyle

### ISSUE THREAD

**Issue by Fausto95** [excalidraw/excalidraw#114]
I'm wondering if we should set the `fillStyle` to solid rather than the default one

In the example below, the rectangle is using `fillStyled: solid` and the circle is using the default one
<img width="298" alt="Capture d’écran 2020-01-04 à 16 47 26" src="https://user-images.githubusercontent.com/23306911/71767949-03546200-2f12-11ea-8a3c-61eae8473a41.png">

**Comment by dwelle** [comment]
Personally, I like the current version. Ultimately, we should allow the user to choose.

**Comment by Fausto95** [comment]
https://github.com/excalidraw/excalidraw/pull/179
