### ISSUE TITLE
Offering new option "save as"

### ISSUE THREAD

**Issue by istvank** [excalidraw/excalidraw#1143]
tl;dr: There should be a "save as" option if you do not want to overwrite a previously opened file.

Currently there is a "Load" and a "Save button". When clicking "Save" without having loaded a file first, we get a file system dialog with "Untitled.json" (at least in Chrome). When I open a file, then change the drawing, and finally click "Save" it only offers me "Save changes" and "Cancel". There is no option to save a new file. The workaround is to reload the browser.

**Comment by lipis** [comment]
Maybe also overriding the `Cmd+S` (`Ctrl+S`) for it..

**Comment by istvank** [comment]
That is right, but overall also a bit tricky. As I wrote in my Tweet https://twitter.com/istinhere/status/1244884566055309320 we probably need some kind of UI pattern. For example, when I open a file, and then refresh the browser tab, I lose the file handle, thus I can no longer overwrite. How do users cope with that, what do they expect!? Should there be a warning on refresh!? Excellent opportunity to trial that with Excalidraw! 😀

**Comment by lipis** [comment]
Hmm.. we technically can't override anything without user's input.

> Should there be a warning on refresh!?

No I wouldn't add any warning on refresh.

**Comment by istvank** [comment]
Ah, right, so a new "Save as" button would be a viable solution, and the "Save" button can save as it is (because there is the "Save changes" alert anyways).

Concerning the refresh: I guess you are already doing it right with keeping the drawing content "alive" over refresh. Otherwise, I guess the users would expect a "Don't you want to save the file?" as it is default in any native app.

**Comment by lipis** [comment]
Maybe we'll do something special with the [native app](https://github.com/excalidraw/excalidraw-desktop) but it will be in a distance future :)

**Comment by dwelle** [comment]
If we implement `save as` button, it should appear only when there's no open file handle (i.e. you didn't open from a file yet).

**Comment by lipis** [comment]
We have a save as now..
