### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by zachrip** [excalidraw/excalidraw#1148]
Is this planned? If not, I'd be up to implementing it depending on the complexity of the task (seeking input from maintainers on that)

You can of course change the background using the color box, but I'd like to be able to change it based on whether the user has dark mode enabled.

**Comment by vjeux** [comment]
I think that'd be cool. Changing all the colors of the UI and the scene to be dark.

**Comment by j-f1** [comment]
One challenge with this would be handling custom colors but we could apply a transformation like my non-evidence-backed [smart invert color](https://observablehq.com/@j-f1/smart-invert-color) which swaps the S and V channels of the color.

**Comment by lipis** [comment]
Yes, we should invert the custom colors as well I guess.. that would be interesting :)

This will just be a visual change, right? If you download the file or share it (collaboration) it will all be normal on the other side.

**Comment by farskid** [comment]
is there an ongoing work on this? otherwise, I'd like to take this.

**Comment by zachrip** [comment]
> is there an ongoing work on this? otherwise, I'd like to take this.

I've started work on a bigger feature around "theming" that has dark mode included in it. If you want I can pass on my code to you or if you just want to start fresh it's all yours.

**Comment by farskid** [comment]
> > is there an ongoing work on this? otherwise, I'd like to take this.
> 
> I've started work on a bigger feature around "theming" that has dark mode included in it. If you want I can pass on my code to you or if you just want to start fresh it's all yours.

Theming sounds great! are you planning to continue working on it? if so, I can help. starting fresh might not be feasible considering theming is already under development.

**Comment by zachrip** [comment]
> > > is there an ongoing work on this? otherwise, I'd like to take this.
> > 
> > 
> > I've started work on a bigger feature around "theming" that has dark mode included in it. If you want I can pass on my code to you or if you just want to start fresh it's all yours.
> 
> Theming sounds great! are you planning to continue working on it? if so, I can help. starting fresh might not be feasible considering theming is already under development.

I'd love help on it. Shoot me an email (zach@zachrip.net) and we can find a better way to collaborate on this.

**Comment by bernard357** [comment]
+1 for dark mode - as a work around, I put a large square form with dark background and then draw forms in white on top of it - this works, but is a tedious process, not mentioning that selection lines are not so visible over a dark background - thank you for your work on this topic!

**Comment by dwelle** [comment]
@bernard357 :)

You can also put a dark-gray color as the scene bg.

![image](https://user-images.githubusercontent.com/5153846/81106283-9b407780-8f15-11ea-9e3b-74760837d814.png)

**Comment by bernard357** [comment]
@dwelle thank you! It was just under my nose but I could not see it! And since the scene background is saved along the rest into .excalidraw files, then it is automatically restored on file upload. You made my day :-)

**Comment by Shriram-Balaji** [comment]
This seems like a really cool feature, and personally using all things in Dark Mode, I'd love to also view Excalidraw that way.

**Comment by Hammster** [comment]
Just to pick up https://twitter.com/fortysevenfx/status/1268884972875677697

This actually works astonishingly good, there are definitly some scenarios that need manual adjustment's like orange.

**Comment by franky47** [comment]
Hah, I wanted to post it here, @Hammster beat me to it!

It's only a visual effect though, the export will still use black lines and white background, and it has issues with lightness and contrast on some colors (though the default ones in the Excalidraw palette seem to work OK). A better color inversion filter would be one proposed by @j-f1 in  https://github.com/excalidraw/excalidraw/issues/1148#issuecomment-606953421.

**Comment by xixixao** [comment]
I want this probably more than anything else :) I've been thinking about it:

1) Colors of icons (black to white) should not be just flipped, they're annoyingly bright
2) The rest of the UI needs work, things like "toolbar background" doesn't work flipped (you'll notice this for any dark mode UI, it's not actually inverting, it's darkening)
3) The biggest question though is the color of elements the user can input. I think we should show the color codes as displayed, but stored them in a unified format so that the mode can be flipped (I guess this can be done losslessly by storing as RGB and doing the hue conversion on the fly)
