### ISSUE TITLE
i want to add arabic

### ISSUE THREAD

**Issue by mohammadameer** [excalidraw/excalidraw#1149]
I want to add the Arabic language to the excaldraw

**Comment by dwelle** [comment]
Note: for the most part this won't be a problem, but some UIs will have trouble with RTL.

**Comment by lipis** [comment]
Yes, that will be interesting.. :)

@mohammadameer here you are: https://crowdin.com/project/excalidraw/ar#

**Comment by j-f1** [comment]
How much should we adapt the UI to RTL languages? (for example, it would be better to put the shape editor on the right side but that would also be a lot of work)

**Comment by lipis** [comment]
> to put the shape editor on the right side

I also thought about that..

**Comment by mohammadameer** [comment]
@lipis I have translated all the words and sentences :smiley:

**Comment by j-f1** [comment]
It looks like “اَلْعَرَبِيَّةُ” is the Arabic word for the Arabic language. Is this correct @mohammadameer? (for the language dropdown)

**Comment by mohammadameer** [comment]
You can use "عربي" or "العربية"

**Comment by j-f1** [comment]
Also, I’m starting to mirror the UI. Should I mirror these icons (click to view)? [Share link](https://fontawesome.com/icons/link?style=solid), [Save](https://fontawesome.com/icons/save?style=solid), [Open](https://fontawesome.com/icons/folder-open?style=solid), [checkmark](https://fontawesome.com/icons/check?style=solid), the layer icons (like [bring to front](https://fontawesome.com/icons/bring-front?style=solid))

**Comment by j-f1** [comment]
- Should I reverse the location of the “%” sign in the zoom level? (i.e.  “%100” instead of “100%”)

**Comment by lipis** [comment]
https://excalidraw-git-l10nmaster.excalidraw-team.now.sh/

**Comment by mohammadameer** [comment]
Any icon should be reserved if it had an rtl lang

I think this guide will help you to much with this

rtlstyling.com

**Comment by mohammadameer** [comment]
@lipis i have found this bug there is no layer actions in crowden
![image](https://user-images.githubusercontent.com/35637666/78164758-8a9a6e80-744a-11ea-81e2-89c87147290b.png)

**Comment by lipis** [comment]
The branch was out of sync.. it's an old copy. Should be fixed in few minutes if you refresh the page.
