### ISSUE TITLE
Idea: make [Enter] add a new line

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#1158]
Right now writing multi-line text is not super obvious in Excalidraw and I've personally observed + been told that it is a source of frustration.

One suggestion is to make [Enter] not commit the text but instead add a new line. I feel like this is something worth trying. In order to commit you can either press escape or click anywhere else, so it's not super difficult either. It'll also avoid having to write a hint for shift-enter.

Thoughts?

This is the code that's responsible for it btw: https://github.com/excalidraw/excalidraw/blob/722c498abea3ca3a000f7384f5d6611c2fd5bd73/src/element/textWysiwyg.tsx#L99

**Comment by lipis** [comment]
Yes, I think it makes more sense and worth trying. Less hints is obviously a plus.

**Comment by zachrip** [comment]
Please, this is so frustrating currently!
