### ISSUE TITLE
Website doesn't publish

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#116]
I thought that we had something in place to push the website on every commit. It doesn't seem to be working.

**Comment by Fausto95** [comment]
The auto deploy GitHub action is not working right now, so the gh-pages branch is not up to date with master.

**Comment by vjeux** [comment]
@nanot1m you were the last one to publish it. Would you be able to do another manual publish as we've made a ton of good changes since yesterday?

@giovannigiordano you setup the automatic publish process. Do you know how to fix it so that it actually works?

**Comment by nanot1m** [comment]
Publsihed

To manually deploy app to gh-pages you can run this two commands
```
npm run build
npx gh-pages -d build
```

**Comment by vjeux** [comment]
Thanks!

**Comment by giovannigiordano** [comment]
I am working on it on the #68 .

**Comment by giovannigiordano** [comment]
In the #150 I added the ACCESS_TOKEN as said in the README of [this actiion](https://github.com/JamesIves/github-pages-deploy-action).

**Comment by giovannigiordano** [comment]
Resolved with the #150 and tested with #151

**Comment by vjeux** [comment]
Yay, thanks <3
