### ISSUE TITLE
Add `cross` as tool icon

### ISSUE THREAD

**Issue by jquintozamora** [excalidraw/excalidraw#1164]
When drawing I sometimes use cross symbol to indicate something not allowed. 
Right now I have to add two lines, but I think that could be good to have.

![image](https://user-images.githubusercontent.com/12530031/78226170-3c758180-74c3-11ea-828c-c54432e76591.png)

![image](https://user-images.githubusercontent.com/12530031/78226325-76df1e80-74c3-11ea-8a83-69d5a122445f.png)

**Comment by lipis** [comment]
Nah.. I think we have enough shapes for now :)

**Comment by lorisdev** [comment]
@jquintozamora  I guess your request fits in this more general issue #1091

**Comment by lipis** [comment]
We'll close this for now :)
