### ISSUE TITLE
Half of the elements are disappearing when I move all of them and rotate one :)

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw#1167]
https://excalidraw.com/?id=5461085259825152

The gif was too big :)

**Comment by lipis** [comment]
![Kapture 2020-04-02 at 15 07 26](https://user-images.githubusercontent.com/125676/78247564-bc1b4480-74f3-11ea-9f30-8ec78042fa66.gif)

Sorry for the Minecraft quality :)

**Comment by dwelle** [comment]
can't repro :(

**Comment by jdestgermain** [comment]
I also can't reproduce

**Comment by dwelle** [comment]
I'll take a look at the code later, but could this be GPU/RAM issue?

**Comment by lipis** [comment]
Could reproduce the same issue with a smaller scene.. but no issues with much smaller.. Very strange.. no errors in the console.

**Comment by j-f1** [comment]
Are they actually gone or just not rendering?

**Comment by lipis** [comment]
Not rendering sorry.. because as soon as I delete the rotated element, they are rendered.

**Comment by lipis** [comment]
If it's only me and it's not reproducable.. let's close it
