### ISSUE TITLE
Allow rotation of multiple elements at once

### ISSUE THREAD

**Issue by jdestgermain** [excalidraw/excalidraw#1168]
Now that we have [rotation support](https://github.com/excalidraw/excalidraw/pull/1099) the next nice addition will be allowing us to select multiple elements all at once and be able to rotate them together as a group.

**Comment by dwelle** [comment]
Will need a rewrite of multiselection in general.

**Comment by jdestgermain** [comment]
I wonder if this is any easier now that you all have implemented 1648

**Comment by dwelle** [comment]
Sadly, no. The grouping mechanism is just an abstraction, but underneath we're still working with regular elements (and even if not, we'd still need to apply those transformations individually upon ungroup).

**Comment by dai-shi** [comment]
It would require a lot of coding and I don't feel like implementing it at the moment, but this is something possible with our current data structure.

![excalidraw-group-rotate-demo](https://user-images.githubusercontent.com/490574/83992798-787a0680-a98c-11ea-9444-65e51b5f51b7.gif)

(Animation created with [excalidraw-claymate](https://github.com/dai-shi/excalidraw-claymate).)

**Comment by dai-shi** [comment]
I took another approach for simpler implementation. see #1960
