### ISSUE TITLE
Fix scrollbars

### ISSUE THREAD

**Issue by j-f1** [excalidraw/excalidraw#1170]
- (maybe) don’t let them overlap — macOS does allow overlap so maybe it’s ok
- move the dropdown farther away from the edges to allow adequate spacing between it and the scrollbars

<img width="164" alt="Screen Shot 2020-04-02 at 09 08 43" src="https://user-images.githubusercontent.com/25517624/78252934-9a08ce80-74c1-11ea-8219-9cd2c988d917.png">

**Comment by jquintozamora** [comment]
I agree @j-f1 , 

I would also add grid-gap: 4px to App-menu, so we can have space between toolbar and actions menu:
![image](https://user-images.githubusercontent.com/12530031/78276415-eb897b80-750a-11ea-9995-6fd6d13ff342.png)
