### ISSUE TITLE
Two points-arrows/lines shift-locking for 22.5 degree?

### ISSUE THREAD

**Issue by dai-shi** [excalidraw/excalidraw#1171]
Hi, just looking at #1152, I realized that SHIFT-locking is for 45 degree.

As I made rotation SHIFT-locking for 22.5 degree (=`Math.PI / 8`) in #1099, would it be nice to make it consistent? My vote is obviously for 22.5 degree for lines/arrows.

**Comment by dwelle** [comment]
Yep, wanted to suggest this myself.

**Comment by jquintozamora** [comment]
Ey @dai-shi , @dwelle,
I also agree with it.
I'm working on it. Also I suggest creating a configuration file where all of these common configs are stored. So if we have to change in the future we only do once.

**Comment by dwelle** [comment]
fixed in https://github.com/excalidraw/excalidraw/pull/1216
