### ISSUE TITLE
Allow to drag THEN press alt to duplicate

### ISSUE THREAD

**Issue by xzab** [excalidraw/excalidraw#1177]
Mirroring figma/sketch actions, allow user to drag a layer, but after dragging is initiated, then pressing/holding alt allows layer to be duplicated and then dropped.

Demo using figma:
https://drive.google.com/file/d/1jp5jzxty8KylF7DRt2Zrm4Tosndd_vVz/view?usp=sharing

**Comment by vjeux** [comment]
There's no mind blown emoji on github. I had no idea that Figma worked that way. If someone wants to enable it, that would be nice.

**Comment by xzab** [comment]
Yeah and the reason I'm asking is because I regularly have trouble using alt drag to duplicate layers in Excalidraw. I usually somehow end up accidentally moving the layer I'm intending to duplicate and possibly attribute it to how fast I'm grabbing the layer. Just a thought not sure if it's just me. :smile:

**Comment by tomdohnal** [comment]
If there's nobody else working on it right now I'd like to give it a shot :)

**Comment by lipis** [comment]
@tomdohnal Go for it!

**Comment by tomdohnal** [comment]
Thanks :) 
I've got a usability question. When I tried duplicating elements in Figma, it starts the duplication process when I press the alt key but then when I keep dragging the duplicating element and *release* the alt key it reverts the duplication and continues as if it never occurred.

So the question is if we want to mimic this behaviour in Excalidraw? The alt-and-drag method for duplication doesn't revert it after releasing the alt key in Excalidraw.

**Comment by dwelle** [comment]
That's a tough one. At first the Figma behavior makes sense, but I must sense I often end up not duplicating the element because I release the alt too early.

**Comment by dwelle** [comment]
I vote for once-alt, always duplicate.

Either way, we should certainly not go full-Figma in that when you press alt before pointerdown, and then release it mid-way it reverts back to non-duplicating. That's super weird and I like our behavior much more.

**Comment by dwelle** [comment]
@tomdohnal seems like our team (whoever's online) agrees, so let's go with this behavior: once you duplicate the element during drag, keep it duplicated until release (regardless of `alt` state).

**Comment by j-f1** [comment]
Plus it’s pretty easy to delete the “original” if you didn’t mean to press alt.

**Comment by tomdohnal** [comment]
OK, thanks for the clarification :) I'll try to send a PR within the next few days

**Comment by xixixao** [comment]
Implemented (although @dwelle doesn't particularly like it and I think it's kinda weird that it doesn't duplicate at the original position at which you started dragging - but it's a strange interaction either way, and it complicated the code significantly).

**Comment by dwelle** [comment]
@dwelle actually likes this a lot :), I just don't like the fact it regenerates the original instead of the element being dragged, is all.
