### ISSUE TITLE
I'd like to translate to Dutch

### ISSUE THREAD

**Issue by Haroenv** [excalidraw/excalidraw#1182]
It doesn't seem to be available on crowdin yet, so the instructions say to open an issue :)

**Comment by lipis** [comment]
Thanks for following the instructions: https://crowdin.com/project/excalidraw :)

**Comment by lipis** [comment]
Also how is the Dutch in Dutch? (To put it in the list of languages)

**Comment by Haroenv** [comment]
"Nederlands", I'm done translating :)

**Comment by lipis** [comment]
That was fast! Thanks... https://github.com/excalidraw/excalidraw/pull/1187 as soon as it goes green.. we have Dutch on production!
