### ISSUE TITLE
Plugin for confluence/jira

### ISSUE THREAD

**Issue by OrenMe** [excalidraw/excalidraw#1189]
Would love to be able to open this as a widget in confluence or jira and be able to save and re-edit each time.
There’s the new Atlassian Forge which might be suitable for use, but as of this day I think it is still in beta.

**Comment by ericsampson** [comment]
This would be killer!

**Comment by thecatontheflat** [comment]
Hey community!
We have created a free integration with Jira as part of the Atlassian Codegeist Hackathon.
It is waiting for approval by the Atlassian Marketplace team to be publicly listed, and I will post an update here as soon as it becomes public.

Please vote 🐱 
https://devpost.com/software/jira-excalidraw-integration

**Comment by OrenMe** [comment]
@thecatontheflat absolutely beautiful! Thank U!
Will it be available for confluence as well? Should be an easy addition from what I read.
Can you share some details on the solution?
@vjeux FYI 🔥🔥🔥

**Comment by thecatontheflat** [comment]
Indeed, accomodating this tool in Confluence makes sense! That'll be the next step once the first iteration is published 🐱

**Comment by thecatontheflat** [comment]
It's live! 
https://marketplace.atlassian.com/apps/1223092/excalidraw-integration-for-jira?hosting=cloud&tab=overview

Will post once we have one for confluence

**Comment by ericsampson** [comment]
@thecatontheflat super dumb question as an Atlassian newbie, would it be hard to make these plugins available for a on-prem confluence/jira installation? Cheers!

**Comment by lipis** [comment]
@thecatontheflat Somehow I missed this one..! Looks great.. is the source for the integration available anywhere?

**Comment by thecatontheflat** [comment]
@ericsampson I'll plug it here once we have it for Confluence :)

@lipis The integration has not been open-sourced yet due to the hackathon, but we consider doing it down the line

**Comment by dkonchekov** [comment]
@thecatontheflat Is there any news about Confluence plugin?

**Comment by thecatontheflat** [comment]
@dkonchekov thanks for poking! We have put it on the shelf due to the (relatively) low interest, so no news here, unfortunately.

**Comment by lipis** [comment]
We'll close this is as out of scope for the core team..

**Comment by dangoor** [comment]
@thecatontheflat FWIW, I have absolutely zero interest in this for Jira (despite the fact that we use Jira) and quite a bit of interest in a Confluence version. I have done a little work making Confluence add-ons, and I totally get the pain of doing them!

(Thanks for making the Jira one, but a definitely +1 for a Confluence one should you decide to do it!)

**Comment by dcoales** [comment]
Plus 1 from me for the confluence plugin.  I currently make notes in Obsidian with embedded Excalidraw diagrams and would love to move them up to confluence when I've finished polishing them.

**Comment by samputer** [comment]
Another +1 here! I use Excalidraw almost daily and would love to be able to integrate it into my Confluence documentation

**Comment by dalexanco** [comment]
I found this one :
https://marketplace.atlassian.com/apps/1226438/excalidraw-for-confluence?tab=overview&hosting=cloud

But does not seem to be something official

**Comment by bvirkler** [comment]
I would also like to see Excalidraw in Confluence.

**Comment by chhantyal** [comment]
Hi everyone, we have released **Excalidraw** integration for Confluence as **FREE** app.

Please try it from there: https://marketplace.atlassian.com/apps/1230327/excalidraw-whiteboard-diagrams-flows-for-confluence-free

**Comment by DexterWoo** [comment]
> Hi everyone, we have released **Excalidraw** integration for Confluence as **FREE** app.
> 
> Please try it from there: https://marketplace.atlassian.com/apps/1230327/excalidraw-whiteboard-diagrams-flows-for-confluence-free

any chance to bring that to **Confluence Server** as well? it doesn't have to be a freeware

**Comment by lumos0** [comment]
here is another confluence server/dc plugin, but it charges a lot
https://marketplace.atlassian.com/apps/1226438/excalidraw-whiteboard-mermaid-uml-mindmap-for-confluence

**Comment by ikattur-ota** [comment]
@chhantyal any chance the app could be updated? Seems like it's grown a bit old now and missing the latest features.
