### ISSUE TITLE
Ability to change various draw options

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#120]
For every element we should be able to change some of the way it's drawn:

Ellipsis, Rectangle, Arrow:
- strokeWidth
- strokeColor
- roughness

Ellipsis, Rectangle:
- fillStyle
- fillColor

Text:
- textContent
- fontSize
- font (maybe give a handful of fonts)

All: 
- Opacity

The description of the API can be found here: https://github.com/pshihn/rough/wiki

**Comment by paulomenezes** [comment]
Working on this.

<img width="1920" alt="image" src="https://user-images.githubusercontent.com/10564179/71773352-59d59680-2f3a-11ea-86ae-08f948a231cf.png">

**Comment by vjeux** [comment]
Yay!

**Comment by paulomenezes** [comment]
Is better use a range or a select with some options? 

<img width="244" alt="image" src="https://user-images.githubusercontent.com/10564179/71773554-aa9abe80-2f3d-11ea-8bd8-636afc2bf768.png">

**Comment by vjeux** [comment]
I like how zwibbler does it, where they put the options inline and only pick a handful

![image](https://user-images.githubusercontent.com/197597/71773577-2c75f200-2f14-11ea-9c90-9bfb302f8e43.png)

**Comment by paulomenezes** [comment]
By the #179 we're almost there, but is missing the Text properties

**Comment by davidbonan** [comment]
Text properties is include in #183

**Comment by vjeux** [comment]
Last part was landed with #278 !
