### ISSUE TITLE
Undo isn't being applied on the collaborators' end

### ISSUE THREAD

**Issue by kbariotis** [excalidraw/excalidraw#1204]
I drilled down a little bit on it and I think the issue is that the `undo` action is restoring a previous version of the canvas, but it seems that we [always broadcast the latest version](https://github.com/excalidraw/excalidraw/blob/master/src/components/App.tsx#L919-L922). 

This sort of logic is applied in other places as well, especially in the consolidation algorithm so I found it a bit hard to put my hands on it.

**Comment by dwelle** [comment]
Yea, history and collaboration doesn't work well together right now.

**Comment by ad1992** [comment]
This works fine now AFAIK after [this](https://github.com/excalidraw/excalidraw/pull/1641). Then we can close this issue unless there is some corner case for which it's still not working!

**Comment by dwelle** [comment]
Yep, seems fine now.
