### ISSUE TITLE
Allow FullScreen 

### ISSUE THREAD

**Issue by mbj36** [excalidraw/excalidraw#1211]
Should we allow fullscreen ?

**Comment by lipis** [comment]
Why not!

**Comment by vjeux** [comment]
What does it mean to “allow fullscreen”?

**Comment by mbj36** [comment]
On a click of a icon, page will stretch to full screen

**Comment by lipis** [comment]
Try that from console:

```js
document.documentElement.requestFullscreen();
```

**Comment by Fausto95** [comment]
Honestly, I don't see the need to add an extra button into our UI for this since this is a browser feature.

**Comment by dwelle** [comment]
Closed as rejected, further info here: https://github.com/excalidraw/excalidraw/pull/1212#issuecomment-609073624
