### ISSUE TITLE
Resize multiple elements

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw#1218]
### The plan

As an initial version we will support resizing multiple elements, but **always keeping the initial aspect ratio**.

- [x] Resize from NW
- [x] Resize from NE
- [x] Resize from SE
- [x] Resize from SW
- [x] Resize curved lines/arrows
- [x] Resize 2-points lines/arrows
- [ ] Text
- [ ] ~Resize to negative values (invert)~ (not for this issue)

### Rationale 

It would be totally fine, if we didn't support rotation, but since we support rotation that becomes an issue. If you try to resize a rotated rectangle in random proportions you will end up in a "irregular" element that we don't support (at the moment). Keeping the initial ratio will not have this issue.

### Example of random ratios from Figma

Notice how the rotated rectangle and ellipse are losing their initial properties.

![Kapture 2020-04-03 at 14 59 10](https://user-images.githubusercontent.com/125676/78424519-dfbac800-7676-11ea-93dc-f497ac6574ed.gif)

-----

More in #672

**Comment by dai-shi** [comment]
@lipis Here's my plan for the remaining items.
- I should be able to work on two-point lines some time soon.
- I don't see good use cases of resize-to-negative (we can't create a mirror diagram), and its implementation will be very complicated to maintain (unless someone have good ideas/refactorings). I wouldn't do it in this iteration. Would you remove it from this issue and create a separate one for tracking?
- I am interested in supporting texts. We need to do support text resizing alone first. We could create a separate issue if it will take time.

**Comment by dwelle** [comment]
Agreed on all three points.

**Comment by dai-shi** [comment]
For the last but not least one, there's a serious issue with resizing texts.
As we found https://github.com/excalidraw/excalidraw/pull/1650#issuecomment-634324144, the width and height of an text element is discrete numbers changed by `1`.
This prevents resizing multiple elements with texts. I can think of a workaround if a selection has at most one text element, but if there's multiple of them, the resizing behavior won't be consistent.

**Comment by dai-shi** [comment]
So, what I propose is when resizing, we make font size to fit in the bounding box, and not change width/height after measurement. We only change width/height from the measurement if the font size is explicitly changed. I think this would work without breaking anything (only we need to be careful that font size and width/height are not always in sync.)
