### ISSUE TITLE
Double text rendering

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#1226]
Can’t find a good repro but sometimes when in collaboration mode the text is duplicated which is very confusing.

![E75B9315-AE11-4CEC-A8A2-EF44161A2EDB](https://user-images.githubusercontent.com/197597/78458717-4edcf000-7668-11ea-93e5-983632e14fb6.png)

It was reported by @joesavona as well

**Comment by vjeux** [comment]
I can repro consistently on mobile:

- Go to excalidraw.com
- Clear the canvas
- Double tap to add a text with character “A” (works fine)
- Zoom out
- Double tap to add a text
- Dual text rendering bug occurs!

**Comment by dwelle** [comment]
I can repro on Android, but not on Desktop.

Also, the dual rendering is gone after editor commit. Are you seeing the same thing? If so, this suggests it was introduced when I started syncing text during editing. Not sure why it's not reproducible on desktop. Will investigate.

**Comment by dwelle** [comment]
I've made the same fix in my PR (https://github.com/excalidraw/excalidraw/pull/1783) as I did in #1231 and can't repro anymore. Will close this on merge. If you can still repro then, please reopen.

**Comment by bevand10** [comment]
And again today: 

![image](https://github.com/excalidraw/excalidraw/assets/5892030/edc7dbfd-57b8-4e57-b935-bad297f77292)
