### ISSUE TITLE
Text Components can't be resized.

### ISSUE THREAD

**Issue by inyigo** [excalidraw/excalidraw#1229]
First of all, thank you for building Excalidraw. I use it a lot!

Now, it seems I can not resize Text components, nor add new lines.

Example: 
https://excalidraw.com/#json=5177390078623744,Yt-kLrUdPOC9uoyPbLtf_g

Is there a new way to do it?

![screencast 2020-04-05 13-52-48](https://user-images.githubusercontent.com/405883/78467950-edd71a00-7744-11ea-84f1-fab99d3d5de1.gif)

Notice that my example above has 2 lines, but that was done a week ago. Now that I am trying to update it, I can't add new line, nor resize the text component.

**Comment by inyigo** [comment]
Next line (Enter) works again.

**Comment by dwelle** [comment]
Yes, we switched from `Shift+Enter` to `Enter`. I was arguing for keeping both, but we decided to make `Shift+Enter` finalize the text, instead.

**Comment by inyigo** [comment]
@dwelle ohh took me a while to figure it out. Thanks for the info!
