### ISSUE TITLE
Resize jumps on first mouse move

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#123]
![ezgif-7-9cd65cf32015](https://user-images.githubusercontent.com/197597/71770430-3f230380-2ee1-11ea-9e79-ff01e5937c46.gif)

We need to remember the delta the mouse is at rather than using the actual mouse position.

cc @paulomenezes

**Comment by paulomenezes** [comment]
Someone want to work on this? I'm busy these days 😭

**Comment by voluntadpear** [comment]
I'd love to work on this!

**Comment by vjeux** [comment]
Go for it
