### ISSUE TITLE
Incorrect selector logic with rotated elements

### ISSUE THREAD

**Issue by dai-shi** [excalidraw/excalidraw#1232]
While I was testing with #1193, I found this bug...

![exdraw18](https://user-images.githubusercontent.com/490574/78491031-7379ba80-7783-11ea-986b-53cb9d0d427f.gif)

**Comment by dai-shi** [comment]
@dwelle Do you have an insight why this would happen? Something may not be using `hitTest`.

**Comment by dwelle** [comment]
I can't repro. Can you share a scene that does this?

**Comment by lipis** [comment]
Happens with any rotated shape..

**Comment by dwelle** [comment]
Probably related to high-DPI screens & `devicePixelRatio` coz it works for me fine (I'm on `devicePixelRatio: 1`).

**Comment by dwelle** [comment]
Though I can repro something similar:

![excal_select_rotated](https://user-images.githubusercontent.com/5153846/78550153-df9c0300-7803-11ea-893b-77563715c26b.gif)

In the above case, it shouldn't select the shape until it's completely inside the selection.

But still can't repro the OP case.

**Comment by lipis** [comment]
try this: https://excalidraw.com/#json=5705661568516096,4TzUOEbeFGPChSzDDbxq5g

**Comment by dai-shi** [comment]
So, my observation is that it's detecting the unrotated element (`angle=0`). I can dig into the code.

**Comment by dwelle** [comment]
I can now repro on large shapes like the scene @lipis shared. On smaller elements it's not noticable.

**Comment by lipis** [comment]
It's basically doesn't get into the consideration the rotation from what I can observe, and selecting the original element with angle `0`

**Comment by lipis** [comment]
Yes, my theory is kind of right I think: https://excalidraw.com/#json=6208840676671488,3Wh16qC3wKkxzbPXuJBFQw
