### ISSUE TITLE
Add a button for help `?` that opens the keyboard shortcuts

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw#1233]
After we merge #1224 

Probably next to the language select

**Comment by Fausto95** [comment]
<img width="237" alt="Capture d’écran 2020-04-06 à 10 03 28" src="https://user-images.githubusercontent.com/23306911/78536427-1f57f000-77ee-11ea-9e09-91474711eed8.png">

This seems a bit off for me

**Comment by lipis** [comment]
Indeed...
