### ISSUE TITLE
Close any dialog with ESC

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw#1236]
Right now we have 3 dialogs (if not more) and only the Export dialog is closed using ESC... we should have a general solution and not per dialog.

Try to get the error dialog by opening an invalid JSON file or open the keyboard shortcut dialog by pressing: "?"

**Comment by mbj36** [comment]
@lipis In Export Dialog..on pressing ESC, Modal hides but on other dialog(s)...it doesn't, can you point me to code...how on Export dialog it's happening ?

**Comment by kbariotis** [comment]
@mbj36 all dialogs are using the [Modal](https://github.com/excalidraw/excalidraw/blob/82ce068972eda930c72808660efe321a6bb04d79/src/components/Modal.tsx) that has an(optional!?) `onCloseRequest` prop.

See how the [ExportDialog](https://github.com/excalidraw/excalidraw/blob/82ce068972eda930c72808660efe321a6bb04d79/src/components/ExportDialog.tsx#L233) is passing the `onCloseRequest` callback. None of the other dialogs are passing that callback. :)

**Comment by mbj36** [comment]
@kbariotis 

https://github.com/excalidraw/excalidraw/blob/793e0e4aa0b86a7d3ff37f54dfa5ed5ff3b4c81d/src/components/RoomDialog.tsx#L147

This RoomDialog also seems to be using the onCloseRequest but it doesn't gets close on pressing Esc

**Comment by mbj36** [comment]
To be more precise..i am trying to find reason why it console on ExportModal and not on other Modal(s)

File - https://github.com/excalidraw/excalidraw/blob/9a0889c698d40f6f87122eb22efe94f710baba22/src/components/Modal.tsx#L17

```
 const handleKeydown = (event: React.KeyboardEvent) => {
    if (event.key === KEYS.ESCAPE) {
      console.log("Hello")
      event.nativeEvent.stopImmediatePropagation();
      props.onCloseRequest();
    }
  };
```

**Comment by mbj36** [comment]
@lipis Any inputs ?

**Comment by lipis** [comment]
No, sorry. Haven't looked at this one.
