### ISSUE TITLE
Add a shortcut to change background, stroke, fill colors

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw#1238]
It would be nice to be able to open the color pickers for

- [ ] Canvas Background
- [ ] Stroke color
- [ ] Background color

It's partially part of #1104 but this could be done easier I think and we can have it in steps.

I have no idea what the shortcuts could be.. Single letters maybe as we have for the elements.

**Comment by badabam** [comment]
Great idea, I am missing that feature a lot. 
I would suggest `alt+1`, `alt+2` and `alt+3` from top to bottom (canvas, stroke, background) with the alternatives `alt+c`, `alt+s` and `alt+b`. There is already a shortcut with the `alt`-key (toggle zen mode).

**Comment by buttercu** [comment]
I would additionally appreciate a hotkey to clear the style and reset to default (black stroke, transparent color).

**Comment by dwelle** [comment]
I'm gonna close this in favor of https://github.com/excalidraw/excalidraw/issues/631. The canvas color shortcut isn't tracked there, but it is in https://github.com/excalidraw/excalidraw/issues/2649 (but ultimately I think canvas color is not used that often to necessitate a shortcut).
