### ISSUE TITLE
Override the save command to actually save as `.excalidraw`

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw#1239]
On `Cmd + S` (and `Ctrl+S` on Windows if I'm not mistaken) we could simply do what we do on save action. Downloading the file.

Is it possible to prompt for a name before saving as `.excalidraw`?

**Comment by j-f1** [comment]
If we were to make a custom dialog, we could wire up the save button in the dialog to be an `<a download={name + ".excalidraw"} href={blobURL}>`.

**Comment by lipis** [comment]
Maybe just download now it's fine.

**Comment by lipis** [comment]
https://stackoverflow.com/questions/11336663/how-to-make-a-browser-display-a-save-as-dialog-so-the-user-can-save-the-conten

**Comment by kbariotis** [comment]
@lipis shall we close this and create a new one for the title prompt?
