### ISSUE TITLE
Resize doesn't work well with negative width/height

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#124]
![ezgif-7-0f107e5ba7b0](https://user-images.githubusercontent.com/197597/71770465-91fcbb00-2ee1-11ea-94e9-cac6b7986d0a.gif)

Please don't fix it by disallowing negative width/height, it's useful for directed elements like arrows. Instead make sure to handle correctly when it's negative.

cc @paulomenezes

**Comment by paulomenezes** [comment]
Another option, is never to be negative, when the height is negative we can update the Y position, which one is better? I don't know what is easier.

**Comment by vjeux** [comment]
I tried that but then you lose the direction for arrows. Right now the entire system works with negative offsets (thanks to getAbsoluteXY01 helper when needed). I think we should keep it working that way.

**Comment by nanot1m** [comment]
It seems to me that fixing #123 (use delta instead of mouse position) will fix this issue also

**Comment by nanot1m** [comment]
Oh, is it fixed already?

**Comment by paulomenezes** [comment]
I guess, when the "se" handler is sent above "ne", I change the handlers, so the "ne" is now "se" and "se" is now "ne". I guess, the handlers should be always the same, independent of his position. 

It's a little hard to explain, sorry.
