### ISSUE TITLE
Codesandbox throws exception while loading excalidraw when cross-site cookies are blocked - Brave Browser

### ISSUE THREAD

**Issue by Shriram-Balaji** [excalidraw/excalidraw#1240]
When trying to open the codesandbox link on Brave, the browser blocks cross-site cookies by default, and hence excalidraw seems to throw an error.

![brave-local-storage](https://user-images.githubusercontent.com/11358903/78505490-65cb3180-7791-11ea-8499-e3572f5f7dd1.png)

I'll be able to send in a PR fixing by handling the error this if the issue sounds valid to you folks :)

**Comment by Shriram-Balaji** [comment]
@dwelle Wrapping the localStorage access with a try-catch should solve this. Do we want an error to be logged in the console, mentioning that `localStorage` is inaccessible. 

BTW, this would also happen in chrome I believe when 3rd party cookies are disabled.

**Comment by dwelle** [comment]
How is this related to cookies?

I don't think we should wrap it in a try/catch. Even if this solves a case of codeSandbox & Brave, it would also mute it when it brakes in normal use.

**Comment by Shriram-Balaji** [comment]
@dwelle although they aren't directly related, I believe it could be something related to how chromium handles blocking external cookies. Note this issue in react devtools - https://github.com/bvaughn/react-devtools-experimental/issues/292

The issue also mentions a couple of bugs filed on chromium that might be related, albeit they seem to be in the context of chrome extensions. Also, if I'm not wrong brave shield is also a chrome extension.

**Comment by dwelle** [comment]
I see, interesting. So it's a Chromium bug, which will hopefully be resolved.

Though we may end up needing handling this case anyway: https://github.com/excalidraw/excalidraw/issues/1245
