### ISSUE TITLE
Memory usage: This webpage is using up significant memory

### ISSUE THREAD

**Issue by haikyuu** [excalidraw/excalidraw#1246]
A friend of mine is working on a big excalidraw drawing (1.1 Mb JSON file) and is getting this warning in Safari.

![Capture d’écran 2020-04-05 à 20 11 11](https://user-images.githubusercontent.com/8558836/78507743-c2225700-7779-11ea-842a-13a5ceb3c0f6.png)

She also notices that sometimes, Excalidraw is stuck for a couple of seconds when zooming in and out and in other operations.

I recorder a performance profile on Firefox. And it's included here. Note that the buffer was full after less than a minute of the recording !

I don't know much about profiling but i guess it this recording would be useful for debugging. 

[profile.zip](https://github.com/excalidraw/excalidraw/files/4434604/profile.zip)

![image](https://user-images.githubusercontent.com/8558836/78508011-9f913d80-777b-11ea-8bdd-196a2749859c.png)

**Comment by haikyuu** [comment]
Here is a snapshot of memory usage taken from firefox

[snapshot.zip](https://github.com/excalidraw/excalidraw/files/4434634/snapshot.zip)

![image](https://user-images.githubusercontent.com/8558836/78508149-889f1b00-777c-11ea-8cd9-4c4fa441210e.png)

**Comment by vjeux** [comment]
Hmm, it’s only 22meg from this screenshot. That seems reasonable. I wonder if it’s hiding something

**Comment by vjeux** [comment]
@haikyuu would it be possible for you to mangle the strings in the scene (to avoid any sensitive content from leaking) and uploading the scene so we can try to profile and understand what is going on?

**Comment by dwelle** [comment]
Or if it's semi-private and can afford being seen by a few eyes, you can send it to luzar.david@gmail.com

**Comment by haikyuu** [comment]
Even better. Here is the file.
I used a simple VIM macro to replace all texts.

[debug.zip](https://github.com/excalidraw/excalidraw/files/4435030/debug.zip)

**Comment by lipis** [comment]
> Here is the file.

That's the biggest real life Excalidraw scene :) We should do something smart with the scroll to content.. because it leads to nothing in this case.. but that's another story.

**Comment by haikyuu** [comment]
using something like excel sheets might be a good idea 🤔

**Comment by haikyuu** [comment]
The idea is to only load the current sheet in memory.

![excalidraw-202045221027](https://user-images.githubusercontent.com/8558836/78513224-fc9fea00-77a1-11ea-8f39-5096d01e3d7b.png)

In terms of User experience. It's good to have a way to organize my work. As it's not practical to have a huge file that contains everything. I do get lost !

And we would only load the current sheet in memory, which would make things fast.

That's of course regardless of the optimizations we could make

**Comment by vjeux** [comment]
So for the memory aspect, it starts at 6meg of js heap, which is totally reasonable.

Where things get a bit out of hands is that any time we select something, we add a new entry to the history. This means that we serialize the entire state and keep one more giant string into memory. Each string saved is adding ~1meg of retained state.

For such a massive scene, we should invest in storing a delta in the history.

**Comment by vjeux** [comment]
The server won't let us upload a file that big:
```js
{"description":"Internal Server Error","error_class":"BadRequestError","error_code":500,"error_message":"Internal Server Error","error_name":"internal-server-error","status":"error"}
```

**Comment by vjeux** [comment]
For exporting the png, the canvas crashes in a funny way in Chrome:
![image](https://user-images.githubusercontent.com/197597/78522298-c3578200-7781-11ea-8ed3-c012ead5ee30.png)

**Comment by vjeux** [comment]
On the bright side, scrolling through the scene is silky smooth at normal zoom level on my macbook pro. On minimum zoom it's not 60fps but closer to 50, it's totally reasonable.

**Comment by vjeux** [comment]
> Excalidraw is stuck for a couple of seconds when zooming in and out

I only enabled zoom cache busting delay for continuous touch gestures. We could extend it to do the cache busting in a requestIdleCallback so we don't starve out other work while we're regenerating all the textures.

**Comment by vjeux** [comment]
For those at home, this is how the scene looks like:

![image](https://user-images.githubusercontent.com/197597/78522618-e0408500-7782-11ea-8103-8b55fd428754.png)
![image](https://user-images.githubusercontent.com/197597/78522643-efbfce00-7782-11ea-8e59-e5070b18c2a6.png)

**Comment by vjeux** [comment]
> The idea is to only load the current sheet in memory.

What you could do is to use your file system in order to get organized. You can save/load a different file for each sheet you are interested in.

The nice part about infinite canvas is that there's less of a cognitive hurdle to start a new page, you can scroll to a different part and keep drawing :)

**Comment by vjeux** [comment]
Thanks so much for you and your friend for helping out! It's great to have a real example of a large scene.

Overall it feels like Excalidraw is doing really well handling such a big scene. All the optimizations we've done recently are bearing fruit. It looks like history management and cache busting are the two areas that are in need of more sophistication as well as improving error messages.

**Comment by haikyuu** [comment]
You're welcome. I'm glad we could help.

Excalidraw is by far the best and simplest doodling app out there.

> The nice part about infinite canvas is that there's less of a cognitive hurdle to start a new page, you can scroll to a different part and keep drawing :)

That's true. And it's one of the best features of excalidraw.

What i was suggesting belongs to a new issue i guess, for further discussion. I'm using firefox containers for now. And it's good enough

**Comment by lipis** [comment]
Feel free to open new issues with whatever ideas you have!

**Comment by vjeux** [comment]
@haikyuu we just merged big improvements related to memory usage. Could you try again and let us know if it helps?
