### ISSUE TITLE
Proper error message when exported canvas is too large

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#1256]
See: https://github.com/excalidraw/excalidraw/issues/1246#issuecomment-609554365

We should mention the max size and let user know they can select which elements they want and retry.

**Comment by Swarajsm** [comment]
Can I try to solve this issue? I am new to github and programming but with a little guidance maybe I can do this?

**Comment by jackdbd** [comment]
I created a PR for this issue: https://github.com/excalidraw/excalidraw/pull/2210
