### ISSUE TITLE
Scroll to content should go to an element

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#1260]
See https://github.com/excalidraw/excalidraw/issues/1246#issuecomment-609494036

Instead of scrolling to the middle of the bounding box, we could look for the closest elements from the current location and scroll to that.

**Comment by lipis** [comment]
and scroll that element to the center!

**Comment by ad1992** [comment]
@lipis was there anything left in the https://github.com/excalidraw/excalidraw/pull/1415 as it was approved but closed without merging ?

**Comment by lipis** [comment]
To be honest.. not sure what happened to that :/

**Comment by lipis** [comment]
The OP decided to close it for some reason.

**Comment by ad1992** [comment]
Got it. Since the OP already deleted the branch so will create new PR and then we can merge if it looks fine.

**Comment by lipis** [comment]
Sure.. go for it
