### ISSUE TITLE
Filling closed multi-point lines

### ISSUE THREAD

**Issue by pshihn** [excalidraw/excalidraw#1262]
Not sure if this is a common use case, but when creating a sketch today, I wished there were a way to fill a closed path - draw a multipoint line but the last point of the line closes the loop. 

Simple closed loops could be detected by measuring the distance between first and last point, and if it's within an error of margin. 

There are cases where paths could have multiple loops or n points in the middle create a loop.

**Comment by dwelle** [comment]
How would you implement hitbox testing for an arbitrary shape?

**Comment by pshihn** [comment]
For clicking with the shape?
Good point. This can get complicated. Quick thought, perhaps reduce the shape into a polygon and then use something like https://en.wikipedia.org/wiki/Point_in_polygon. 
I suspect https://github.com/maxnachlinger/point-in-svg-path does something similar.

**Comment by pshihn** [comment]
But yeah, don't want too much computation if it's something that would happen often

**Comment by dwelle** [comment]
Also, to make sure I understand --- this request is also about filling in background, right? In which case we wouldn't be able to use a low-resolution polygon heuristic...

**Comment by vjeux** [comment]
I’ve been wanting that as well! Would love to see it happen. It also fits nicely without having to add anymore UI.

**Comment by lipis** [comment]
Also those..! 

<img width="284" alt="Screenshot 2020-04-06 at 5 58 09 PM" src="https://user-images.githubusercontent.com/125676/78572476-2f90bf00-7830-11ea-9478-a0ef9b6d6f71.png">

**Comment by pshihn** [comment]
The [https://en.wikipedia.org/wiki/Even%E2%80%93odd_rule](even-odd rules) allows filling of shapes like these. 
Roughjs supports filling of arbitrary SVG paths but it does that using pattern fills which are not as performant. 

I will create a fork to play with this, and hopefully get this feature when I have some time this week. Perhaps enhance roughjs as well if I get it right.

**Comment by pshihn** [comment]
Implemented a polygon approximation for curves in rough (unreleased). Luckily I had some code lying around that I could reuse. 
![curve-fitting-min](https://user-images.githubusercontent.com/833927/78606478-41fc0000-7812-11ea-8d74-82913e504329.jpg)

Excalidraw could call that same function in roughjs geometry module to get the polygon for hit testing. 

Will try that tomorrow perhaps.

**Comment by gregor** [comment]
I was just looking for this feature. Great to see that it is going to be available soon.
