### ISSUE TITLE
Unable to preventDefault errors in Chrome

### ISSUE THREAD

**Issue by nanot1m** [excalidraw/excalidraw#128]
<img width="820" alt="image" src="https://user-images.githubusercontent.com/9278185/71770899-a928c080-2f54-11ea-954e-5fbe3cbdd3f2.png">

It seems that by default  in Chrome `onWheel` is passive event

**Comment by vjeux** [comment]
Can you explicitly mark it as active?

**Comment by nanot1m** [comment]
Do not know if it possible for react synthetic events. But it is possible to use `addEventListener('wheel', handleWheel, {passive: false})` on canvas ref

**Comment by vjeux** [comment]
Looks like not. Let's do manual event listening then: https://github.com/facebook/react/issues/14856

**Comment by nanot1m** [comment]
Closed by #130
