### ISSUE TITLE
Scroll to content displayed when wysiwyg text in an empty scene

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#1285]
Repro:
- Have an empty scene
- Double click somewhere to write text
- See the "Scroll to content" button show up

The reason is because scroll to content is using the number of elements being drawn as a heuristic. This was a lazy attempt by me. We can either do the right thing and compute proper visibility (likely bigger change) or change the current heuristic to bail if wysiwyg element is active (should be a half a line change)

**Comment by lipis** [comment]
This is not reproducible anymore.
