### ISSUE TITLE
Middle Mouse click is pasting 

### ISSUE THREAD

**Issue by vincent-paing** [excalidraw/excalidraw#1289]
Currently my deskop doesn't have touch pad. I have to use middle click to navigate around since it's faster than using scrollbars. Currently clicking on middle click is pasting my clipboard, which is really tedious to delete, is there an option to turn this off?

**Comment by vincent-paing** [comment]
Related to #961, closing this

**Comment by dwelle** [comment]
Btw, you can also use `Space + drag`.
