### ISSUE TITLE
Text being currently edited gets properties of previously edited text

### ISSUE THREAD

**Issue by kokaneka** [excalidraw/excalidraw#1291]
## Bug
Let's say we have 2 texts on the whiteboard:
text1 - very large, hand drawn
text2 - small, code

click on 'text1' and modify it to 'text1edited'
now, double click on 'text2' and modify it to 'text2edited' and after clicking outside, you will see that text2modified will have taken the properties that text1 had, i.e. it will now be very large, hand drawn instead of small, code.

**Comment by dwelle** [comment]
This was fixed yesterday in https://github.com/excalidraw/excalidraw/issues/1281. Is it possible you're on older version? Can you still reproduce?

**Comment by kokaneka** [comment]
Yes. Seems to have gotten fixed now. Thanks :)
