### ISSUE TITLE
Page title is too big for search results

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw#1292]
<img width="618" alt="Screenshot 2020-04-07 at 12 12 17 PM" src="https://user-images.githubusercontent.com/125676/78651512-1be56700-78c9-11ea-99ed-e0f129f63fb6.png">

Also says that is [not mobile friendly](https://search.google.com/test/mobile-friendly?url=https://excalidraw.com/&utm_source=gws&utm_medium=metaline&utm_campaign=notmobilefriendy)

**Comment by lipis** [comment]
Any ideas here: https://github.com/excalidraw/excalidraw/blob/master/public/index.html#L6-L7

**Comment by dwelle** [comment]
How about something on the lines of:

> Excalidraw | Hand-drawn • Collaborative • Secure`

![image](https://user-images.githubusercontent.com/5153846/78651980-606d0480-78c1-11ea-851c-71ee70d03a1b.png)

Though, I don't like the "Hand-drawn", because that doesn't describe it.

Or emoji version:

> Excalidraw | Hand-drawn :clap:  Collaborative :clap:  Secure

(a joke.. also google doesn't support emojis in results, or do they?)

**Comment by dwelle** [comment]
Variation:

> Excalidraw | Hand-drawn diagrams • Collaborative • Secure

![image](https://user-images.githubusercontent.com/5153846/78652543-27815f80-78c2-11ea-85e9-b4625cf13ab9.png)

**Comment by lipis** [comment]
No emojis please! :D

> Excalidraw | Hand-drawn look • Collaborative • Secure

**Comment by vjeux** [comment]
Lots of people have called it a Virtual Whiteboard fwiw

**Comment by j-f1** [comment]
> Also says that is [not mobile friendly](https://search.google.com/test/mobile-friendly?url=https://excalidraw.com/&utm_source=gws&utm_medium=metaline&utm_campaign=notmobilefriendy)

Seems like the errors are “Text too small to read” (likely referring to the shortcut things) and “ Clickable elements too close together” (likely referring to the shape switcher)
