### ISSUE TITLE
Incorrect Alignment of github corners in codesandbox preview

### ISSUE THREAD

**Issue by Shriram-Balaji** [excalidraw/excalidraw#1295]
In the below GIF the github corner can be seen to be incorrectly aligned on initial loading. I cannot however this issue on excalidraw.com, when the device width is smaller.

![Excalidraw-github-corner-issue](https://user-images.githubusercontent.com/11358903/78658915-6e824b80-78e8-11ea-8a70-27b67b3e8de6.gif)

Steps to reproduce:
1) Open codesandbox url mentioned in the readme.
2) Reload the codesandbox preview on the right side.

**Comment by lipis** [comment]
We should also hide the `Excalidraw` that appears for a brief moment..

**Comment by j-f1** [comment]
This is because the CSS hasn’t loaded yet, so the code that positions the corner and handles RTL for it isn’t enabled.

**Comment by lipis** [comment]
Shall we move it to `index.html` and remove the title?

**Comment by dwelle** [comment]
Or we can move the GH logo into `Ppp.tsx` or `LayerUI` and avoid this.
