### ISSUE TITLE
Resizing with SHIFT loses the pointer position

### ISSUE THREAD

**Issue by dai-shi** [excalidraw/excalidraw#1296]
Is this already tracked? I have the understanding why it happens.

![exdraw20](https://user-images.githubusercontent.com/490574/78660067-6be31e80-7907-11ea-9272-9bb4a2b7273d.gif)

**Comment by lipis** [comment]
Yes, it should go back to the cursor if you leave SHIFT.

**Comment by dai-shi** [comment]
Implementation note: Basically, we shouldn't depend on `lastX` and `lastY`. If we solve it completely, `resizeElements` doesn't take `lastX` and `lastY`, I suppose.

**Comment by dai-shi** [comment]
From: https://github.com/excalidraw/excalidraw/issues/1298#issuecomment-610412378

> @dai-shi, Yes, I can see that #1296 is related to the changes I'm implementing for #1024 , the fact that we should return to the previous position.

@jquintozamora Although I'm not 100% following #1024, yeah, it's likely.
Do you get what I mean by "not depend on lastX and lastY"? We should only use the absolute position not delta.

**Comment by jquintozamora** [comment]
I guess we need lastX and lastY to calculate the new coming deltaX. 

As per the implementation, I was thinking on somehow store the element info when we press SHIFT so we can recover it later on. But still haven't tested it fully.

What do you think?

**Comment by dai-shi** [comment]
If I don't care about #1024, and just focus this issue, I don't think we need deltaX and deltaY, even if we support SHIFT.

Input: the current element position [x1, y1, x2, y2] , the handle like "se", the pointer position [px, py], and if SHIFT is pressed or not
Output: the new element position [x1, y1, x2, y2]

Basically, I've done this for multiple element resizing. If you read the code, it will better explain.

https://github.com/excalidraw/excalidraw/blob/c3b83fba385cc0455cb1fa46f95259852eec8af0/src/element/resizeElements.ts#L384-L398

This keeps the aspect ratio. So, it's not exactly the same.

**Comment by jquintozamora** [comment]
Ey @dai-shi , 
Your idea works fine for the scenario with no rotation.
When we have rotation, we still need lastX and lastY:
`const [deltaX, deltaY] = rotate(x - lastX, y - lastY, 0, 0, -angle);`

Do you think `rotate` function could be also used without `lastX` and `lastY` ?

**Comment by dai-shi** [comment]
I believe so. I didn't spend time to really think about it, but there's no reason it's not possible.

**Comment by jquintozamora** [comment]
Thanks @dai-shi , I got it,

I've something working for `se`:

```js
          const [x1, y1, x2, y2] = getElementAbsoluteCoords(element);
          const cx = (x1 + ((x2 - x1) / 2));
          const cy = (y1 + ((y2 - y1) / 2));
          const [dRotationX, dRotationY] = rotate(x, y, cx, cy, -angle);
          const handleOffset = 4 / appState.zoom; // XXX import constant
          const dashedLinePadding = 4 / appState.zoom; // XXX import constant
          const scaleX = (dRotationX - handleOffset - dashedLinePadding - x1) / (x2 - x1);
          const scaleY = (dRotationY - handleOffset - dashedLinePadding - y1) / (y2 - y1);
          const width = element.width * scaleX;
          const height = event.shiftKey ? width : element.height * scaleY;
          mutateElement(element, {
            width,
            height,
            ...adjustXYWithRotation("se", element, width - element.width, height - element.height, angle),
          });
```

I'm going to refactor it and make work for other areas as well.

**Comment by dai-shi** [comment]
Looks clean.

**Comment by dai-shi** [comment]
@jquintozamora Instead of always using `scaleX`, we could do a little better which scale we use if SHIFT is active, depending on the pointer position.

<img width="736" alt="image" src="https://user-images.githubusercontent.com/490574/78766184-ea04fb00-79c3-11ea-94b1-db81539667b2.png">

**Comment by jquintozamora** [comment]
Yup agree, that would be the `Math.max(width, height)` then.

**Comment by jquintozamora** [comment]
@dai-shi , just to give you an update, I'm working out the maths for `sw`. I tried the one used for multiple selection and doesn't work for rotation in a nice way:

```javascript
      case "sw": {
        const scale = Math.max(
          (x2 - handleOffset - dashedLinePadding - x) / (x2 - x1),
          (y - handleOffset - dashedLinePadding - y1) / (y2 - y1),
        );
        if (scale > minScale) {
          selectedElements.forEach((element) => {
            const width = element.width * scale;
            const height = element.height * scale;
            const x = element.x - (x2 - element.x) * (scale - 1);
            const y = element.y + (element.y - y1) * (scale - 1);
            mutateElement(element, { width, height, x, y });
          });
        }
        return true;
      }
```

I'll write down all the maths in a paper and see what happens.
Any ideas are welcome :)

**Comment by dai-shi** [comment]
Would you create a PR? Hope I get time to take a look later.

**Comment by jquintozamora** [comment]
Sure, I'll clean up little bit and push my latest changes

**Comment by dai-shi** [comment]
Nice.

In my experience, you might want to try just "w" for a start instead of "sw".

**Comment by jquintozamora** [comment]
I've created PR -> https://github.com/excalidraw/excalidraw/pull/1330/files#diff-d5be54db4e227384b3d070c24f8c86a2R259-R286

**Comment by jquintozamora** [comment]
ups, looks like I solved it, but changing `width - element.width` by the reverse on `adjustXYWithRotation`:

```javascript
            ...adjustXYWithRotation(
              "sw",
              element,
              element.width - width,
              height - element.height,
              angle,
            ),
```


I was missing that part 🤦🏻‍♂️

**Comment by jquintozamora** [comment]
Also I separated clearly between linear element vs no linear element, so future PR for multi points are easier to handle...

**Comment by jquintozamora** [comment]
@dai-shi , I've done all the sides now.
Now all the resize logic is calculated based on absolute coords. 
* Note: only the logic for `applyResizeArrowFn` is using `lastX` and `lastY` still. Should we leave that for other ticket in order to not block other PR?

Please check the PR: https://github.com/excalidraw/excalidraw/pull/1330/files

**Comment by dai-shi** [comment]
Thanks! I will take a look at the PR in a couple of hours.
Yeah, let's leave `applyResizeArrowFn` this time and leave it for another issue/PR.
