### ISSUE TITLE
[TODO] Zoom in/out

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#13]
Would be nice to be able to zoom in / out for the canvas. This way we can see different parts of the scene.

**Comment by giovannigiordano** [comment]
As said in the #14 , how this will be handled? Mouse wheel (with some modifier key) or buttons to select the zoom modifier?

**Comment by vjeux** [comment]
Not sure... zwibbler has a button + and -

**Comment by giovannigiordano** [comment]
Ok, for now we can use buttons and then reiterate the feature if needed.

**Comment by nanot1m** [comment]
I've found pretty cool demo of handling mac's pinch-to-zoom gesture https://stackblitz.com/edit/multi-touch-trackpad-gesture

**Comment by vjeux** [comment]
Scaling and rotating doesn't seem to be working on my macbook pro on either chrome or safari :(

**Comment by enzoferey** [comment]
I do have a little bit of time in the next few days to work on something and this feature seems important to me. Do you value it over another issue? I don't have a strong opinion on what to work, I just want to help on something by the end of the week 👍 

cc @vjeux @dwelle

**Comment by vjeux** [comment]
Go for it!

**Comment by enzoferey** [comment]
Yes yes, that's another feature potentially 😄 Gonna do zoom in / zoom out with + and - buttons 👍

**Comment by lucasverra** [comment]
plus one for zooming out 
other apps use (on MacOS) cmd + scroll up/down (on trackpad)

**Comment by enzoferey** [comment]
Using scrolling is yet another step in my opinion. Zoom level should be continuous for sure, but in the first iteration only being able to jump between discrete values via the zoom buttons sound like the right level of complexity to aim for I believe.

**Comment by enzoferey** [comment]
Closed via https://github.com/excalidraw/excalidraw/pull/716.
