### ISSUE TITLE
Properly calculate bounds of rotated elements

### ISSUE THREAD

**Issue by dai-shi** [excalidraw/excalidraw#1303]
From: https://github.com/excalidraw/excalidraw/pull/1273#issuecomment-610385649

This is more like request for comment.

I'm not sure if it's correct wording, but let's call `Coords` and `Bounds`.

For unrotated diamonds:
<img width="467" alt="image" src="https://user-images.githubusercontent.com/490574/78682424-ea03ed00-7928-11ea-8772-0255b231a941.png">

For rotated diamonds:
<img width="464" alt="image" src="https://user-images.githubusercontent.com/490574/78682722-5252ce80-7929-11ea-9940-43e051b888a1.png">

Now, Coords is used for resizing and rotating, and Bounds is used for selection detection and calculating canvas size. Bounds are also currently used for multiple element resizing.

Issue 1:
https://github.com/excalidraw/excalidraw/pull/1273#issuecomment-610345053 The selection doesn't detect the diamond because it's smaller than the Bounds.

![image](https://user-images.githubusercontent.com/5153846/78666694-03c91400-78d8-11ea-8c0a-18cc5cdda6fb.png)

Issue 2:
When exporting, there is an extra margin compared to unrotated elements.

<img width="794" alt="image" src="https://user-images.githubusercontent.com/490574/78683149-e6bd3100-7929-11ea-882a-3c2a02e3b936.png">

----

What would be an ideal solution and maybe a practical workaround?

(edit)
We go with this https://github.com/excalidraw/excalidraw/issues/1303#issuecomment-610462010 and revisit the UI issue later.

**Comment by dwelle** [comment]
For diamonds, I'd make them behave as rotated squares. Currently, the bounding boxes differ for no real reason:

![image](https://user-images.githubusercontent.com/5153846/78684301-95dd1680-78f0-11ea-9f6e-0d3b758cb264.png)

https://excalidraw.com/#json=5396828187000832,PfGsO7QjqI1d4HJ0jrp4Ig

This won't fix ellipses. There, we'd need to do the same we do with squares: make sure the bounding box aligns with the edge.

**Comment by dwelle** [comment]
Or... maybe not. Why don't we make the bounding boxes as such:

![image](https://user-images.githubusercontent.com/5153846/78684902-53680980-78f1-11ea-9dbb-8f96c5c55e45.png)

![image](https://user-images.githubusercontent.com/5153846/78684910-55ca6380-78f1-11ea-9736-67386328b1aa.png)

**Comment by lipis** [comment]
> Or... maybe not. Why don't we make the bounding boxes as such:

Because resizing those will be tricky..

**Comment by dwelle** [comment]
Not for UI. What about use those only for calculating selection & export?

**Comment by dai-shi** [comment]
> Or... maybe not. Why don't we make the bounding boxes as such:

Then, how do you rotate?

**Comment by dai-shi** [comment]
So, the question is probably, which bounding box we should show for multiple element resizing. It's about the UI.

**Comment by dwelle** [comment]
Not much choice. Both Figma & Affinity does the same, but they differ in updating the UI.

Figma updates immediately:

![figma_common_bounding_box](https://user-images.githubusercontent.com/5153846/78687394-66c8a400-78f4-11ea-90a6-b18c878cb58c.gif)

Affinity updates on re-select:

![affinity_common_bounding_box](https://user-images.githubusercontent.com/5153846/78687275-4862a880-78f4-11ea-9273-5f2f2936675a.gif)

**Comment by dai-shi** [comment]
The 3rd choice of mine is to calculate the Bounds properly and give up the Coords gets outside of Bounds when selecting multiple elements. That's what I was originally going to implement.

**Comment by dwelle** [comment]
Can you visualize that 3rd choice?  How does it differ from Figma/Affinity?

**Comment by dwelle** [comment]
Actually, Figma is incorrect when the multiselection contains ellipse:

Figma:

![image](https://user-images.githubusercontent.com/5153846/78688739-d9864f00-78f5-11ea-9eff-243d77a1eb50.png)

Affinity:

![image](https://user-images.githubusercontent.com/5153846/78688746-db501280-78f5-11ea-9fb6-a77efef66778.png)

**Comment by dai-shi** [comment]
This 

<img width="505" alt="image" src="https://user-images.githubusercontent.com/490574/78689661-8b8f3c80-7931-11ea-885d-15ba3e0c20e1.png">

will become like this:

![image](https://user-images.githubusercontent.com/490574/78689568-70243180-7931-11ea-991f-89573d9ecbe0.png)

**Comment by dwelle** [comment]
So how Figma/Affinity does it. (The individual items' bounding boxes I assume are not intended).

**Comment by dai-shi** [comment]
@dwelle No, they are intentional and that's my point. That's for highlight. With this way, we don't need to create new UI, and it requires no refactoring. To me, it's an acceptable solution, but curious how you think. I hope changing the box style (ex. lighter) mitigates it.

**Comment by dwelle** [comment]
I'm not sure what showing individual element's bounding boxes solves? Either way, we need to calculate the common bounding box Figma-style for export/selection-detection, which you show correctly in your image above --- so I'm not quite sure what you're proposing.

(I'm off for today)

**Comment by dai-shi** [comment]
> Either way, we need to calculate the common bounding box Figma-style for export/selection-detection

Okay. Sure, I'm not oppose to it. What I'm proposing was a tiny UI issue once it's implemented.

**Comment by dwelle** [comment]
Anyway, you don't need to convince me, I trust your judgement. As long as it fixes export and selection, it's fine, and we can tweak it as we go along.

**Comment by dai-shi** [comment]
(Yeah, I know.)

My original issue title was misleading. Basically we need to properly calculate bounds of rotated elements. (In code, improve `getElementBounds`.) What I would like to have discussed was the UI issue that may only happen with multiselection. I actually wondered if there could be any totally different solution.

Now, I think the multiselection UI issue is trivial (just make the coords lighter, or we will come up with better ideas later). This issue is all about calculating bounds properly.

Could there be anybody here (or in the internet) who might be interested in tackling this???
