### ISSUE TITLE
Common description

### ISSUE THREAD

**Issue by Fausto95** [excalidraw/excalidraw#1304]
### Some of the descriptions

* Excalidraw is a virtual collaborative whiteboard tool that lets you easily sketch diagrams that have a hand-drawn feel to them.
* Excalidraw is a whiteboard tool that lets you easily sketch diagrams with a hand-drawn feel.
* Virtual whiteboard for sketching hand-drawn like diagrams.
* Excalidraw is a virtual collaborative whiteboard tool to sketch diagrams with hand-drawn look & feel.

### Should be used on

- [x] [Twitter](https://twitter.com/excalidraw)
- [x] [Blog](https://github.com/excalidraw/excalidraw-blog/blob/master/gatsby-config.js#L6)
- [x] [How to](https://github.com/excalidraw/excalidraw-howto/blob/master/gatsby-config.js#L6)
- [x] GitHub
- [ ] [OpenCollective](https://opencollective.com/excalidraw)
- [x] `README.md`
- [ ] `index.html`

Lets pick one and use it everywhere

**Comment by kbariotis** [comment]
On [OpenCollective](https://opencollective.com/excalidraw) as well.

**Comment by dwelle** [comment]
Is this still actionable @Fausto95 @lipis or do we close this?

**Comment by Fausto95** [comment]
Just created some PR, I'll close this when they get merged

**Comment by Fausto95** [comment]
I recall we discussed about the description in the `index.html`(about being too long or something like that), so I will leave it as is.
I don't have an Open Collective account, so I can't change the description there.

I think this issue is fixed now.

**Comment by lipis** [comment]
Perfect! Thanks.
