### ISSUE TITLE
Failure to detect resize handles after selection (related with text input?)

### ISSUE THREAD

**Issue by dai-shi** [excalidraw/excalidraw#1311]
~I don't yet know stable steps to reproduce the issue, but sometimes we can't grab the handle especially "se". It less happens to "nw".~ Interestingly, browser refresh solves the issue. Maybe, it's related with other issues.

**Comment by dai-shi** [comment]
This is probably the same behavior that @enzoferey  reported in https://github.com/excalidraw/excalidraw/pull/1193#issuecomment-609387186.

**Comment by dai-shi** [comment]
Well, it's not only with multiple elements, but it happens with just one element.

**Comment by dai-shi** [comment]
Finally, I was able to reproduce the issue successfully. It was nothing to do with multiple elements or resizing.

![exdraw22](https://user-images.githubusercontent.com/490574/78782869-a919e000-79dd-11ea-8345-4edb7c74bc37.gif)

**Comment by dai-shi** [comment]
https://github.com/excalidraw/excalidraw/issues/1311#issuecomment-610866537 This can be different one.

**Comment by dwelle** [comment]
Steps:

1. create circle
2. select it via drag-select

**Comment by dai-shi** [comment]
It's probably related with multiple element selection logic. I think there exists an invisible text element or something.

**Comment by dwelle** [comment]
Maybe related to my change of handling text elements during edit. I'll look into it later.

**Comment by dai-shi** [comment]
I got the reason. It's a deleted element.

in renderScene.ts, `selectedElements` doesn't include deleted elements,
but in App.tsx, `selectedElements` includes deleted elements.

I confirmed that by filtering out elements that `isDeleted`, the issue is resolved.
Not quite sure which part to fix in App.tsx. Can you take it over?

**Comment by dwelle** [comment]
Yep. Let's wait for https://github.com/excalidraw/excalidraw/pull/1068 first. I'm wrapping it up as we speak.
