### ISSUE TITLE
Add an always-visible lock icon to the desktop UI

### ISSUE THREAD

**Issue by petehunt** [excalidraw/excalidraw#1313]
We should add an always-visible giant lock icon that says "END-TO-END ENCRYPTED" so everyone knows that Excalidraw is safe to use in a corporate setting.

The lock icon should have tooltip that reads: "Your drawings are end-to-end encrypted so Excalidraw's servers will never see them. [Read our blog post to learn more.](https://blog.excalidraw.com/end-to-end-encryption/)"

**Comment by petehunt** [comment]
If someone wants to come up with better copy I'm all ears

**Comment by vjeux** [comment]
Agreed! I feel like we could even drop the github corner in favor of this icon.

**Comment by dwelle** [comment]
If we do this, we may want to remove the lock next to the shapes as part of https://github.com/excalidraw/excalidraw/issues/1206, otherwise there'll be too many locks and confusion.

**Comment by ad1992** [comment]
@petehunt @dwelle can I pick this up?

**Comment by lipis** [comment]
Sure you can.. and we can iterate once the PR is ready! Go for it.

**Comment by ad1992** [comment]
where should I add the icon ? How about next/prior to zoom functionality on bottom left ?

**Comment by dwelle** [comment]
That might suggest actionability. But now that I think about it, it must be actionable if we want to allow the "tooltip" (which must be a modal then) to contain a link to our e2e blogpost.

**Comment by lipis** [comment]
What about top right as @vjeux suggested?
