### ISSUE TITLE
Make a 90 second demo video

### ISSUE THREAD

**Issue by petehunt** [excalidraw/excalidraw#1314]
It's a bit hard to learn how to use Excalidraw. We should make a very quick demo video (English-only hosted on YouTube with internationalized captions) to demonstrate how to do things like enable collaboration and draw curved lines. We can include a link to the demo video somewhere in the UI with a "take a tour" call to action.

**Comment by dwelle** [comment]
[Rapid Mockup Creation Using Excalidraw by Michael Liendo](https://youtu.be/JvDmJybANCQ) via https://github.com/excalidraw/excalidraw-blog/issues/47

/cc @mtliendo

**Comment by jspreddy** [comment]
Maybe use Zoom to record an architecture session with the developers collaborating using excalidraw while explaining the architecture of excalidraw?

**Comment by lipis** [comment]
- https://www.youtube.com/watch?v=JvDmJybANCQ
- https://www.youtube.com/watch?v=fix2-SynPGE&t=423s

I think we can close this :)
