### ISSUE TITLE
Feature: Align items

### ISSUE THREAD

**Issue by Haroenv** [excalidraw/excalidraw#1316]
Once you select items, it would be useful to be able to align them left / right / center, as well as vertical.

In other design tools I also often use the "distribute evenly" tool, however that is more complex and shouldn't necessarily be done at the same time.

**Comment by Haroenv** [comment]
Not sure if I should open a new issue for this as well, but text aligning left would be a nice option for longer text

**Comment by dwelle** [comment]
Duplicate of https://github.com/excalidraw/excalidraw/issues/772
