### ISSUE TITLE
Avoid using fontawesome for size

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#132]
Looks like 14% (30kb) of the bundle is fontawesome for just 5 little svg.
![image](https://user-images.githubusercontent.com/197597/71771283-77c8da00-2eed-11ea-8ad7-93d5039371a5.png)

We should probably just inline the svg instead of loading the entire dynamic library to generate them.

**Comment by dwelle** [comment]
IIRC, there are libs that support tree-shaking FA icons (not sure if FA itself supports it, via some additional steps).

**Comment by vjeux** [comment]
![image](https://user-images.githubusercontent.com/197597/71771508-f5dab000-2ef0-11ea-8625-f3a8f7f2e741.png)

So 226 - 190 = 36kb that's been reclaimed :)
