### ISSUE TITLE
add newline on shift+enter

### ISSUE THREAD

**Issue by xzab** [excalidraw/excalidraw#1322]
Lost the ability to hit shift+enter to create a manual line break in text;  That was better than nothing, but preferably we could just resize the text box and it would auto wrap (If I can suggest what is preferred :)

**Comment by Fausto95** [comment]
You can `enter` to break the line

**Comment by dwelle** [comment]
> preferably we could just resize the text box and it would auto wrap

Maybe as a bonus feature this would work, but by default the text box should auto expand and not wrap unless you want it to wrap.

We're investigating whether we should keep both `shift+enter` and `enter` to add a newline, and finalize on `cmd/ctrl+enter` only.

**Comment by dwelle** [comment]
Ok, it seems that Figma & Affinity uses both, so let's align it.

I'm gonna hijack this issue to track it.

**Comment by xzab** [comment]
> You can simply press `enter` to break the line

Oh! I think I must have gotten used to the other way I didn't even realize.  Thanks!

**Comment by dwelle** [comment]
@xzab you can now use both :smile:
