### ISSUE TITLE
Do not exit wysiwyg editor when changing properties

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#1325]
steps:

1. enter wysiwyg editor
2. change property from the menu
3. blurs & exits the editor (for empty editor this means it removes the element completely and hides the menu)

Originally reported in https://github.com/excalidraw/excalidraw/pull/1213#issuecomment-609008553

This also aligns it with Figma & Affinity, and necessary in anticipation of https://github.com/excalidraw/excalidraw/issues/1126

**Comment by kbariotis** [comment]
That seems to be more complicated than I though initially :P. It seems that the editing element is being finalized on blur, which is when you click anywhere in the window.

So we could probably remove the `onblur` event and try to manually finalize it on demand but then I will probably need to update the editing element in place, when a property changes.

@dwelle let us know if you have any hints on that.

**Comment by dwelle** [comment]
lemme see

**Comment by kbariotis** [comment]
https://github.com/excalidraw/excalidraw/pull/1387 will finalize this. Closing.
