### ISSUE TITLE
Do not non-center aligned text to center when typing

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#1326]
Followup to https://github.com/excalidraw/excalidraw/pull/1213

Current behavior (left-aligned text):
 
![excal_left_aligned_center](https://user-images.githubusercontent.com/5153846/78828490-167d3f00-79e5-11ea-8fef-7b6b01201d2f.gif)

Desired behavior (Figma/Affinity):

![affinity_left_aligned_center](https://user-images.githubusercontent.com/5153846/78828529-2137d400-79e5-11ea-9023-73ce7f760704.gif)

**Comment by dwelle** [comment]
Blocks https://github.com/excalidraw/excalidraw/issues/755

**Comment by xixixao** [comment]
Agree this feels broken atm. Combining text alignment with text-block alignment would make more sense. Alternatively, there should be a separate "block align" control.
