### ISSUE TITLE
Do not vertically center left/right aligned text

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#1327]
Currently, we're not only horizontally centering, but also vertically centering.

Should we not vertically center for left/right aligned text? Or not vertically center at all?

Current:

![excal_left_aligned_center](https://user-images.githubusercontent.com/5153846/78828645-4e848200-79e5-11ea-8711-107379e429ac.gif)

Note that Figma et al. allows to modify this behavior:

![image](https://user-images.githubusercontent.com/5153846/78828813-94d9e100-79e5-11ea-97a2-05411dccdff6.png)

Potentially blocks https://github.com/excalidraw/excalidraw/issues/755

**Comment by getvega** [comment]
Exactly what I was looking for 👌 

For the horizontal centering, I would make it depend on the currently selected alignment:
- left align: left border does not move
- center align: middle does not move
- right align: right border does not move

Same would go for the vertical centering... but in the meantime (awaiting the vertical align feature) I would kill the auto centering (top border does not move). 
It is more annoying than useful at the moment imho.

(BTW you are killing it, this is the first whiteboarding tool that I truly stick to. Particularly useful these days.... 👍)
