### ISSUE TITLE
Negative resize swaps arrow direction

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#1334]
Side effect of https://github.com/excalidraw/excalidraw/pull/1237

Steps:

1. create multi-point arrow/line
2. grab corner handle and drag it to the negative on both sides at the same time

![](https://user-images.githubusercontent.com/5153846/78660213-fb1f1080-78cc-11ea-9350-d1db47350e9f.gif)

/cc @lusingander @dai-shi

**Comment by dai-shi** [comment]
@dwelle Can you reproduce this behavior after we merged #1427 ?

**Comment by dwelle** [comment]
Not reproducible!
