### ISSUE TITLE
Enhance aspect ratio tools

### ISSUE THREAD

**Issue by gregor** [excalidraw/excalidraw#1342]
You currently can fix the aspect ration of a rectangular to a square by pressing the shift button. Likewise you can fix an ellipisis to a circle. I am looking for a more flexble solution that allows me to rescale a shape whos aspect ratio I am happy with by fixing while doing so. Any mouse movement will then increase affect overall size but not change the aspect ratio.

**Comment by quuu** [comment]
Gave this a tackle: #1467

**Comment by dai-shi** [comment]
Oops, I wasn't aware this issue. Adding this to #1298.

**Comment by dai-shi** [comment]
Is it related with #690?

**Comment by dwelle** [comment]
> Is it related with #690?
Seems like it

**Comment by Jnforja** [comment]
@dwelle Can I have this assigned to me?
