### ISSUE TITLE
Do we really need to store the `lastCommittedPoint` in the JSON?

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw#1353]
How is it used when we are done with the element? Is it really needed to be stored?

**Comment by dwelle** [comment]
Nope.

**Comment by ReneCode** [comment]
Can I work on that issue ?

**Comment by dwelle** [comment]
Sure. I suggest you create `clearElementsForLocalStorage` & `clearElementsForExport` in `src/element/index.ts`, and use them wherever we use `clearAppStateForLocalStorage`/`cleanAppStateForExport`.

**Comment by ReneCode** [comment]
Good to discuss it before - I've only thought about changing ``serializeAsJSON`` .
But your are right - it's good to clean up the localStorage as well. And to separate the clean up functionality.

Should I consider on element.type / only remove on ExcalidrawLinearElement ? (lastCommittedPoint is only used at that elements)

**Comment by dwelle** [comment]
> Should I consider on element.type / only remove on ExcalidrawLinearElement ? (lastCommittedPoint is only used at that elements)

Yep, TS wouldn't allow otherwise (unless you type-asserted). Just set it to `null` for linear elements.

**Comment by dwelle** [comment]
Technically you can delete it completely to save even more space.

**Comment by ReneCode** [comment]
> Technically you can delete it completely to save even more space.

sorry, I do not understand what you mean. 

I would make a pure functional aproach - like that:
``` 
export const clearElementsForExport = (
  elements: readonly ExcalidrawElement[],
) =>
  elements.map((element) =>
    isLinearElementType(element.type)
      ? { ...element, lastCommittedPoint: null }
      : element,
  ) as readonly ExcalidrawElement[];
```
and use it like here:
```
JSON.stringify(
    {
      type: "excalidraw",
      version: 2,
      source: window.location.origin,
      elements: clearElementsForExport(getNonDeletedElements(elements)),
      appState: cleanAppStateForExport(appState),
    },
    null,
    2,
  );
```

**Comment by dwelle** [comment]
Sure. You could also just leave the `lastCommittedPoint` prop out altogether (you can set it to `undefined` so that `JSON.stringify` doesn't include it if you wanna keep the code "functional").

Also, now that we have the helper, you can move the `getNonDeletedElements()` inside `clearElementsForExport` as well.
