### ISSUE TITLE
Chrome becomes unusable after being part of collaboration for quite some time

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw#1357]
https://excalidraw.com/#room=2f3e6599902ede009e55,l5Y6REPDQ3eoP-K7EHe_zA

<img width="406" alt="Screenshot 2020-04-10 at 5 00 16 PM" src="https://user-images.githubusercontent.com/125676/78996262-e81a7380-7b4c-11ea-95fd-f5913c21a409.png">

The CPU goes back to normal when I close that window.

**Comment by vjeux** [comment]
Maybe due to this: https://github.com/excalidraw/excalidraw/issues/1258

**Comment by dwelle** [comment]
closing as part of https://github.com/excalidraw/excalidraw/pull/1632. If need be, let's reopen or create a new one.
