### ISSUE TITLE
Add a button to show all content, if the zoom allows it.

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw#1360]
Maybe a button next to the zoom actions..

Calculate the zoom (10% - 100%) to show all elements of the scene in the center.

Cap the results to [10, 100]

https://excalidraw.com/#room=2f3e6599902ede009e55,l5Y6REPDQ3eoP-K7EHe_zA

**Comment by j-f1** [comment]
Icon from macOS Preview app:

<img width="41" alt="Screenshot_2020-04-10 12 03 47" src="https://user-images.githubusercontent.com/25517624/79004729-5c402180-7b23-11ea-8619-e8c7cb59d427.png">

**Comment by lipis** [comment]
https://thenounproject.com/

**Comment by jspreddy** [comment]
how about this icon: "Center"
https://thenounproject.com/search/?q=center&i=482070
