### ISSUE TITLE
new CSP rules broke FF on localhost

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#1385]
It appears https://github.com/excalidraw/excalidraw/pull/1379 broke Firefox (doesn't load at all) on localhost:

![image](https://user-images.githubusercontent.com/5153846/79053804-50964d00-7c40-11ea-8521-39347abb825f.png)

/cc @Shriram-Balaji

**Comment by tomdohnal** [comment]
I'm not a security expert but I wonder if it makes sense to use CSP rules on the localhost (in the dev mode)...
If we need to use it to suppress the warning mentioned in https://github.com/excalidraw/excalidraw-desktop/issues/82 then we could just put a wilecard `*` into the CSP header in the dev mode...

**Comment by Shriram-Balaji** [comment]
@tomdohnal Agreed, we could actually do that. I had a hunch that the connect-src csp was a little restrictive and might just break things unintentionally, but the other policies should ideally work on development also - as we have set to `default-src` to be `self`.
