### ISSUE TITLE
Multi-selection bounding box is wrong with diamond

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#1393]
This is just a diamond and a circle:

![image](https://user-images.githubusercontent.com/197597/79057907-85dc7400-7c1b-11ea-8b0b-497326a3a2ab.png)

https://excalidraw.com/#json=6316540404170752,p4szxVkgrVrRRm0jey9fBQ

**Comment by dai-shi** [comment]
ooops.
