### ISSUE TITLE
[TODO] Scroll

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#14]
Ideally we want an infinite canvas where you can draw anywhere. In order to avoid people from getting lost, we could only make the canvas exist for half a screen around the closest object. If you draw something on the edge, it automatically expands it.

**Comment by giovannigiordano** [comment]
How this will interact with the #13 ? The zoom in/out will be handled with mouse wheel or not?
I think, we need even to allow the expansion of the canvas by an interaction that is not drawing a shape, maybe a button at the bottom edge.

**Comment by dwelle** [comment]
> How this will interact with the #13 ?

I'd zoom using `Alt+WheelUp/WheelDown` (or `Ctrl/Cmd`).
