### ISSUE TITLE
New CSP rules broke CodeSandbox project

### ISSUE THREAD

**Issue by CompuIves** [excalidraw/excalidraw#1400]
Hey all!

I recently saw that Excalidraw didn't load up anymore in CodeSandbox, I believe it was introduced when the CSP changes were added. CodeSandbox bundles Excalidraw in the browser, which uses some web workers and scripts from codesandbox.io/cdnjs/unpkg.

Would it make sense to add these domains to the CSP, or remove the CSP rules in dev mode?

It can be verified here: https://codesandbox.io/s/github/excalidraw/excalidraw
Standalone: https://dnn4h.csb.app/

![image](https://user-images.githubusercontent.com/587016/79068124-ce9c3780-7cc4-11ea-8290-4d20623eddb5.png)

**Comment by dwelle** [comment]
Yea, it's caused by a recent change. Thanks for the report!

/cc @Shriram-Balaji
