### ISSUE TITLE
Japanese translation

### ISSUE THREAD

**Issue by kuy** [excalidraw/excalidraw#1405]
Hello, I'd like to contribute Excalidraw as translator of Japanese. Could you add Japanese on Crowdin?

**Comment by lipis** [comment]
https://crowdin.com/project/excalidraw

**Comment by lipis** [comment]
Hey @kuy :) Just a friendly reminder.. are you still up for it?

**Comment by lipis** [comment]
How is Japanese in Japanese?

**Comment by kuy** [comment]
@lipis Thanks for adding Japanese. I'm working on it 😃

**Comment by lipis** [comment]
Thank you @kuy!

We also need the Japanese in Japanese for the drop down.

**Comment by kuy** [comment]
@lipis Oops, thanks. I didn't noticed that, sorry. I've just forked but too late, you looks like already added Japanese locale on the branch `l10n_master`.

Thanks for sharing very useful tool. I'm happy to contribute Excalidraw! ⚔️

**Comment by lipis** [comment]
https://github.com/excalidraw/excalidraw/pull/1508 :) Just take a look and approve it if it's all good! Once approved we'll merge it.

**Comment by lipis** [comment]
It's live :) Thanks again.. @kuy
