### ISSUE TITLE
Consider reducing proprietary meta tags

### ISSUE THREAD

**Issue by tomayac** [excalidraw/excalidraw#1425]
Currently there're [a lot of proprietary meta tags](https://github.com/excalidraw/excalidraw/blob/7df16c1b1d51c8622403ec65943713a7635dea6e/public/index.html#L91-L140) on the page that are proprietary to Apple devices. Additionally, maintaining the required [splash screen images](https://github.com/excalidraw/excalidraw/tree/master/public/splashscreen_images) for all current and future devices is annoying. 

[PWACompat](https://github.com/GoogleChromeLabs/pwacompat/) is a library by my colleague @samthor that generates the resources dynamically based on the Web App Manifest.

It can be [dynamically loaded](https://github.com/v8/v8.dev/pull/310/files) on Apple devices, so not every user gets to pay for it.

Thoughts?

**Comment by lipis** [comment]
Whatever can be automated I'm down for it.

**Comment by tomayac** [comment]
If there's agreement amongst the maintainers, please assign me the Issue and I can get going.

**Comment by dwelle** [comment]
If it has no downsides (no huge library etc.), then let's do it.

**Comment by j-f1** [comment]
Sounds good as long as we make sure it still works on iOS!

**Comment by lipis** [comment]
There is only one way to find out! :) The lib seems small.. @tomayac let's do it ;)
