### ISSUE TITLE
Sticky notes

### ISSUE THREAD

**Issue by gwww** [excalidraw/excalidraw#1428]
Given the collaborative nature of this tool, having the ability to place notes on the canvas would improve the collaborative abilities.

I would see this as the ability to drop a coloured note on the canvas and to be able to start typing in the note right away.

Implementation wise this could be a coloured rectangle with an initial fixed size and text box. The would be text locked to the rectangle and would have the usual text properties (size, bold, etc).

**Comment by lipis** [comment]
Basically having a new Text element with a background and stroke?

**Comment by gwww** [comment]
Nice! Yes. Maybe with larger margins on the background to make it look more like a note vs a part of the drawing?

**Comment by lipis** [comment]
<img width="251" alt="Screenshot 2020-04-14 at 4 10 43 PM" src="https://user-images.githubusercontent.com/125676/79228661-80c13400-7e6a-11ea-91e3-33479ee0f180.png">

**Comment by lipis** [comment]
and I guess they shouldn't be part of any export or anything :) Interesting..

**Comment by pA1nD** [comment]
It could be a valuable feature if the text resizes automatically to fit in the post-it.

**Comment by matt-hammond-bbc** [comment]
Another way to get sticky-notes would be to allow text to be placed inside any shape (rectangle, diamond, circle) - e.g. you double click the shape and you can add text within it. The text ideally would word-wrap to fit the bounds of the shape or its bounding box.

Avoids needing a separate tool.

I'd also find this a really valuable addition.

**Comment by dwelle** [comment]
> Another way to get sticky-notes would be to allow text to be placed inside any shape (rectangle, diamond, circle) - e.g. you double click the shape and you can add text within it. The text ideally would word-wrap to fit the bounds of the shape or its bounding box.

You can already do that, plus if you hit `Enter` while an element is selected, it creates text centered to it.

**Comment by vjeux** [comment]
You can already double click near the center of a rectangle/oval to write text within in a centered manner.

One thing that I hope we’ll get to is to link shapes together so that if you move the rectangle, it’ll move the text along without needing to select it.

**Comment by matt-hammond-bbc** [comment]
> You can already double click near the center of a rectangle/oval to write text within in a centered manner.

Ah, I always assumed it was just coincidence and a good aim on my part when I double clicked :-)

> One thing that I hope we’ll get to is to link shapes together so that if you move the rectangle, it’ll move the text along without needing to select it.

This is the key part - that the text is, conceptually, inseparable from the rectangle. Creating a separate text label doesn't really make it easy to treat the text+rectangle combo as a sticky-note that you can just move around the whiteboard.

**Comment by dwelle** [comment]
> This is the key part - that the text is, conceptually, inseparable from the rectangle. Creating a separate text label doesn't really make it easy to treat the text+rectangle combo as a sticky-note that you can just move around the whiteboard.

In the meantime, you can select both → rightclick → `group selection`

**Comment by sojusnik** [comment]
> <img alt="Screenshot 2020-04-14 at 4 10 43 PM" width="251" src="https://user-images.githubusercontent.com/125676/79228661-80c13400-7e6a-11ea-91e3-33479ee0f180.png">

Is there a reason why this sticky note has a header bar?

I was thinking more of a simple version with some shadow, like:

![grafik](https://user-images.githubusercontent.com/1245718/90631523-363e3280-e223-11ea-8b0d-ea81f6750083.png)

**Comment by sojusnik** [comment]
> One thing that I hope we’ll get to is to link shapes together so that if you move the rectangle, it’ll move the text along without needing to select it.

One way to implement this could be: If a shape is selected and you use "enter" or "double-click" within that shape to add text, then the text would automatically be grouped with that shape and also word-wrapped.

**Comment by AlexStapleton** [comment]
> > One thing that I hope we’ll get to is to link shapes together so that if you move the rectangle, it’ll move the text along without needing to select it.
> 
> One way to implement this could be: If a shape is selected and you use "enter" or "double-click" within that shape to add text, then the text would automatically be grouped with that shape and also word-wrapped.

This is exactly the feature I'm looking for in this tool. The inability to wrap the text inside a shape makes it cumbersome to quickly capture ideas.

**Comment by sojusnik** [comment]
Another way to capture ideas could be through a mindmap, as proposed [here](https://github.com/excalidraw/excalidraw/issues/1737).
Sticky notes are a good candidate for the [intended API](https://github.com/excalidraw/excalidraw/issues/2189).

**Comment by vmkazakoff** [comment]
> One way to implement this could be: If a shape is selected and you use "enter" or "double-click" within that shape to add text, then the text would automatically be grouped with that shape and also word-wrapped.

And we also need wrap text inside box. And (maybe) adjust font-size.

![image](https://user-images.githubusercontent.com/5445543/103125086-0b655e80-469b-11eb-9535-e3e0df55ad8b.png)

**Comment by tomdyson** [comment]
+1 for this! This is the main thing keeping me in Miro, which does this really well (see screencast).

![screenshot 2021-02-19 at 16 40 23](https://user-images.githubusercontent.com/15543/108533909-73b67200-72d1-11eb-85c9-d1a18948e852.gif)

**Comment by locofocos** [comment]
IMO the big thing missing here is text wrapping. 

Most of the issues people have mentioned so far, there are workarounds that aren't very painful. For people who want sticky notes to look a certain way, they can draw one and save it in their library. Manually creating text and grouping it within the rectangle is doable.

But even if you do those things, not having text wrapping can really be a big pain. Going back to make small changes to the text means manually and painstakingly re-flowing the text by hand. There's really no workaround, so I think starting with text wrapping would give users the biggest benefit at the smallest cost.

Not to downplay the benefit of having first-class sticky notes though! I just think there are smaller victories too.

**Comment by itsam** [comment]
Hi all, any news on the issue? Thank you in advance

**Comment by ad1992** [comment]
closing this as we support binding text to shapes now https://twitter.com/aakansha1216/status/1471509326674030592

**Comment by mateusppereira** [comment]
> support binding text to shapes now

IMHO this is not "sticky notes" 🥲 

Do we have someone working on this? If not I can give it a try

**Comment by patrick-boatner** [comment]
Consider, you can create a sticky note object and save it to your library. That allows customizing the color, text alignment, etc.

<img width="1320" height="430" alt="Image" src="https://github.com/user-attachments/assets/4778ce52-f5cd-46f4-b70f-f96370c8fbb6" />

It's easy to use (for power users that look for it), and it solves the big problem from before - text wrapping.

**Comment by mateusppereira** [comment]
It's still far from the experience provided by Miro, for example, which, by the amount of 👍 in [this comment](https://github.com/excalidraw/excalidraw/issues/1428#issuecomment-782194463), I'm assuming is invaluable for its users.

I'm not complaining, just trying to understand if the maintainers agree that there's value on doing this or not.

**Comment by eldelacajita** [comment]
To me, the key element that is missing is not **text wrapping** (already implemented for basic shapes) but **text scaling**. Meaning: more text → smaller text size while keeping the "host shape" intact.

If you currently use a rectangle and add text into it (which is currently the simplest way of creating a sticky-note-like thing). once the text takes all the space, it starts making the rectangle longer. That makes you end up with different sized rectangles which are more difficult to arrange and different in visual weight (unlike real sticky notes).

So, fixing issue #9123 would solve this for me. In the meantime, I can't consider this solved.
