### ISSUE TITLE
Export/Import State

### ISSUE THREAD

**Issue by azz** [excalidraw/excalidraw#143]
Currently there's no way to save the diagram in a way that can be re-imported back into the application, so if you make a diagram you can't come back later and edit it.

It would be nice to generate a JSON file that could be checked into source control that exports:

- The `elements` object
- The version of the state (for backwards compat)

**Comment by vjeux** [comment]
We do have the ability to save all the elements and load them back: https://github.com/excalidraw/excalidraw/blob/master/src/index.tsx#L703-L723

Right now we only store it in localStorage and for history (cmd-z) but would be nice to be able to share it across computers! There's no reason it wouldn't work.

**Comment by azz** [comment]
PR incoming 😉

**Comment by vjeux** [comment]
<3
