### ISSUE TITLE
Use our own MIME type and extension

### ISSUE THREAD

**Issue by tomayac** [excalidraw/excalidraw#1431]
I have plans to implement file sharing and file handling features for Excalidraw. For these to work properly, we should store files with their own extension (bikeshedding proposal: `.excalidraw`) and probably mint a new MIME type (bikeshedding proposal: `application/vnd.excalidraw+json`), albeit this is probably more of academic nature. At this point, I would like to get your thoughts on switching from `.json` to `.excalidraw` (or whatever the bikeshedding results in). Thanks!

**Comment by lipis** [comment]
Have you tried to download a file?! We are already using `.excalidraw` as an extension.

**Comment by dwelle** [comment]
@lipis we actually don't when using Native File System API.

**Comment by tomayac** [comment]
> [W]e actually don't when using Native File System API.

This is https://github.com/WICG/native-file-system/issues/80 and then the current MIME type taking precedence: https://github.com/excalidraw/excalidraw/blob/722c498abea3ca3a000f7384f5d6611c2fd5bd73/src/data/json.ts#L33

So if the legacy approach already uses `.excalidraw`, can I safely assume you're fine with it in the general case?

**Comment by lipis** [comment]
https://github.com/excalidraw/excalidraw/blob/722c498abea3ca3a000f7384f5d6611c2fd5bd73/src/data/json.ts#L31

OK.. haven't see what is actually going on.. but yes, I'm down to have a proper MIME and `.excalidraw` extension for all.
