### ISSUE TITLE
Background colors are hidden behind properties

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw#1444]
<img width="277" alt="Screenshot 2020-04-16 at 9 01 05 PM" src="https://user-images.githubusercontent.com/125676/79490432-8616ae00-8025-11ea-8839-2d626a2b2fde.png">

**Comment by dwelle** [comment]
This was introduced in https://github.com/excalidraw/excalidraw/pull/1435 via the `backdrop-filter`. Setting `z-index` nor forcing the container into own stacking context doesn't help. It feels like a bug in the `backdrop-filter` implem.

**Comment by dwelle** [comment]
Okay, this doesn't seem to be a problem with `backdrop-filter`, but a feature of stacking contexts... I'm out of my CSS depth here.

**Comment by dwelle** [comment]
Got a fix I think.
