### ISSUE TITLE
Type error: null is not an object

### ISSUE THREAD

**Issue by iphoneprogramozo** [excalidraw/excalidraw#1447]
Hi, I get this error several times. Macbook, safari Version 13.1 (15609.1.20.111.8) Before this error, the playground freezed. Browser refresh was solve this problem for few minutes.
Thanks

<img width="1440" alt="Screenshot 2020-04-16 at 11 38 27" src="https://user-images.githubusercontent.com/10113696/79551102-851f6400-8099-11ea-9caa-946ab6d04e85.png">

**Comment by kbariotis** [comment]
This is the same error with https://github.com/excalidraw/excalidraw/issues/1538. It suggests that `context` was at some point null.

I wonder if it has been fixed in newer releases since we haven't seen it since.
