### ISSUE TITLE
Is it possible to change the discrete rotation steps from 22.5 to 15 degrees?

### ISSUE THREAD

**Issue by mapbakery** [excalidraw/excalidraw#1451]
Now the discrete steps when pressing the SHIFT key are 22.5 degrees. But 15 degrees is IMHO more useful/logical because then it will be possible to make also 30, 60 etcetera degree diagonals (which are useful in for example transit map sketches)

This is related to my  #1351 issue

**Comment by dai-shi** [comment]
I just found diagrams.net uses 15-degree locking. So, at least it's another example to indicate the reasoning.

I'm OK with it. @lipis @dwelle ?

**Comment by lipis** [comment]
30, 45, 90 are there.. so I'm fine with it.

**Comment by dwelle** [comment]
I'm down too. Figma and Affinity uses 15deg, as well.

**Comment by dai-shi** [comment]
OK, I'll draft a PR.
