### ISSUE TITLE
Finnish translation

### ISSUE THREAD

**Issue by Klipi** [excalidraw/excalidraw#1462]
I'd love to take a look at providing translations in Finnish. Could you add it in Crowdin?

**Comment by lipis** [comment]
Added: https://crowdin.com/project/excalidraw

**Comment by lipis** [comment]
How would you say `Finnish` in `Finnish`?

**Comment by Klipi** [comment]
`Suomi`

**Comment by lipis** [comment]
Well of course!

**Comment by lipis** [comment]
Released!! Thank you very much! Test it out.. and if you see anything wrong, you can always fix it from Crowdin :)

**Comment by Klipi** [comment]
Nice! Looks good to me!

One thing I couldn’t figure out is how to check the error states. Any tips?

**Comment by dwelle** [comment]
@Klipi import this JSON file [error_on_click.zip](https://github.com/excalidraw/excalidraw/files/4511799/error_on_click.zip)

**Comment by Klipi** [comment]
Great, thanks for the quick turnaround! Happy to contribute to such a fantastic project 🙂
