### ISSUE TITLE
Feature suggestion: Import an image to draw over

### ISSUE THREAD

**Issue by nandwana92** [excalidraw/excalidraw#1464]
This could be outside the scope of this tool, but here goes. Consider the use case of being able to import an image onto the canvas and annotate over it. One could draw shapes over the image and then be able to export the canvas as an image. Check out this example,

![image](https://user-images.githubusercontent.com/36832784/79830143-6c2cf080-83c2-11ea-8299-119b1f8d6014.png)

I used another photo editor to overlay one image over the other but this won't work as well if you let's say want to annotate multiple things or draw many shapes over the image.

**Comment by dwelle** [comment]
Thanks for the suggestion. You can track it over here: https://github.com/excalidraw/excalidraw/issues/19
