### ISSUE TITLE
Feature request: Allow the creation of double-headed arrows 

### ISSUE THREAD

**Issue by pranjaljately** [excalidraw/excalidraw#1465]
It would be great to create a double-headed arrow e.g. ↔ to denote two-way data flow instead of drawing two separate arrows.

![image](https://user-images.githubusercontent.com/30666375/79862546-28d87f00-83ce-11ea-945f-1d361b9506bb.png)

**Comment by dwelle** [comment]
This falls under https://github.com/excalidraw/excalidraw/issues/616
