### ISSUE TITLE
Set up Gitter

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#147]
This may sound a bit overkill, but how about we set up a Gitter community for Excalidraw? It'd be useful even now, to discuss things without having to create whole issues for simple questions.

Will need to be done by @vjeux 

https://gitter.im/cypress-io/cypress#createcommunity

https://gitlab.com/gitlab-org/gitter/webapp/blob/develop/docs/faq.md#why-isnt-my-github-organisation-or-repos-appearing

Thoughts?

**Comment by vjeux** [comment]
Great idea! Will set it up in a few hours

**Comment by azz** [comment]
Gitter or Discord?

**Comment by dwelle** [comment]
Discord feels a bit too heavy for our app, and Gitter has GitHub integration, which is a plus.

**Comment by vjeux** [comment]
I think I created it: https://gitter.im/excalidraw/community#

Can someone join to see if it works?

**Comment by OrenMe** [comment]
Works! :-)

**Comment by dwelle** [comment]
Awesome :sparkles:. Closing.

Btw, to enable threads (beta):

![image](https://user-images.githubusercontent.com/5153846/71783798-23585400-2fec-11ea-9cdb-57036161050b.png)

![image](https://user-images.githubusercontent.com/5153846/71783799-24898100-2fec-11ea-9da0-7d3ce4e9c9fb.png)
