### ISSUE TITLE
Your page is not mobile friendly

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw#1476]
<img width="721" alt="Screenshot 2020-04-23 at 3 23 52 PM" src="https://user-images.githubusercontent.com/125676/80099058-87406180-8576-11ea-8fe6-d8d2b92d2394.png">

https://search.google.com/test/mobile-friendly?url=https%3A%2F%2Fexcalidraw.com%2F

**Comment by vjeux** [comment]
- **Text too small to read**: There is no text lol
- **Clickable elements too close together**: I don't think we should change that.
