### ISSUE TITLE
Feature: support different color inputs (e.g. "red" instead of "ff0000")

### ISSUE THREAD

**Issue by warrenseine** [excalidraw/excalidraw#1478]
Browsers have different ways to input colors, using hexadecimal (`#00ff00`), RGB (`rgb(0,255,0)`), names (`green`)... In some situations, I'd prefer to type in "red" rather than selecting the color from the color picker. Another use case would be when trying to fit a diagram in a pre-existing website whose stylesheet was not written with hexadecimal values.
I believe this would be a nice, transparent, "discoverable by accident" feature.

Here's how that'd work (_in the video, when I select some text, I also copy / paste to keep it short_):
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/539804/80100187-e64ea800-856f-11ea-8d73-d185967fa384.gif)

I also have an incoming patch to implement this feature request.

**Comment by warrenseine** [comment]
From a UX perspective, I'm aware that it can be unnatural to input any else than hexadecimal in a text box prefixed with "#". I don't really have an alternative, so tell me if that's a problem or if you have a solution.

**Comment by vjeux** [comment]
Closed by #1479

**Comment by j-f1** [comment]
Shouldn’t this override the colors to use open-colors where possible instead of the harsher browser default colors?
