### ISSUE TITLE
Curved arrows

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#148]
This could be implemented as part of #24.

Discussing the feature with [Dan](https://mobile.twitter.com/dluzar/status/1213803170813620224), there are several possibilities how to implement this (we can support each).

1. Two-point bezier curve, where you'd manipulate the end points' bezier handles to create the curve:
	
	![2-point-curve](https://user-images.githubusercontent.com/5153846/71780448-b54b6700-2fc2-11ea-92d9-338cc69d10a1.gif)

2. Three-point bezier curve, where you could manipulate the middle point. Here, we can also decide whether to even show the bezier handles for the middle point, or whether to use some uniform default.

	![3-point-curve](https://user-images.githubusercontent.com/5153846/71780433-87feb900-2fc2-11ea-89c7-aba31f287e93.gif)

**Comment by giovannigiordano** [comment]
I prefer the second solution. 
In the #24 @vjeux has proposed a multi-point line.

**Comment by hmaurer** [comment]
I think a bezier with control points might be overkill; perhaps an array of points that the curve has to pass through would be enough, as per https://github.com/pshihn/rough/wiki#curve-points--options (referenced in #24 ).

**Comment by vjeux** [comment]
I think that it’s a three step process. First we need to allow you to create arrows with more than two points, so you can draw a path.

Then, and only then, we need to figure out how to connect those points. The first version will be straight, then we will add some automatic curvature using bezier.

And finally we will let you configure each particular bezier curve. But that last step may not be needed at all if the previous step works reasonably well.

**Comment by dwelle** [comment]
> I think that it’s a three step process. First we need to allow you to create arrows with more than two points, so you can draw a path.

Sounds good.

Here, we need to decide how that should be done:

1. Keep the tool active, and make next clicks extend the arrow by adding new points:

	![multi-point-arrow-pre](https://user-images.githubusercontent.com/5153846/71783690-d7f17600-2fea-11ea-9ffa-30baa0a7bc1b.gif)

2. Create two-point arrow, and allow to later add new points in the middle (via `Ctrl/Cmd+Click`):

	![multi-point-arrow-post](https://user-images.githubusercontent.com/5153846/71783692-ec357300-2fea-11ea-8c77-b0e0ceffffe4.gif)

3. Both of the above.

**Comment by vjeux** [comment]
I feel like the first one is more intuitive, at least for a first version.

**Comment by dwelle** [comment]
Should we close this and open separate issue(s) for the improvements? @GasimGasimzada

**Comment by lipis** [comment]
I would say so.. we kind of have curved arrows now. We just need to be able to edit the segments somehow.

**Comment by GasimGasimzada** [comment]
I have some other tasks at hand right now. I am planning on doing them afterwards. If someone wants to get on it, I am also willing to help out with.

**Comment by vjeux** [comment]
We shipped it!
