### ISSUE TITLE
suggestion: remove dialog/overlay on Load canceling

### ISSUE THREAD

**Issue by antonklimov** [excalidraw/excalidraw#1482]
The dialog and overlay do not seem to serve any purpose. The current text is "Error The user aborted a request" 1) Why it should be considered an error? 2) Whom is this messaged addressed to? It says "the user" in third person. It might be appropriate in server logs rather than being presented to the user directly.

**Comment by dwelle** [comment]
Unclear what you're referring to exactly. Can you post steps to reproduce?

**Comment by antonklimov** [comment]
1) Click on "Load" button. 
![image](https://user-images.githubusercontent.com/26126237/80150755-c9b17080-856d-11ea-94ac-d30a2b7b1b41.png)
2) File selection dialog pops up.
3) Cancel that.
4) Observe:
![image](https://user-images.githubusercontent.com/26126237/80150877-02514a00-856e-11ea-97ec-8dded5ecb3ed.png)

**Comment by dwelle** [comment]
Oh, didn't know about that. Thanks!

**Comment by kbariotis** [comment]
I can only guess that is coming [from here](https://github.com/excalidraw/excalidraw/blob/master/src/actions/actionExport.tsx#L110-L116) but I cannot replicate. @antonklimov what's your browser?

**Comment by dwelle** [comment]
It's related to native FS, and I stand corrected, it doesn't come from external lib, but is a native error thrown by `chooseFileSystemEntries`.

So we'll have to catch and ignore that error ourselves.
