### ISSUE TITLE
Feature: Icon presets

### ISSUE THREAD

**Issue by kbariotis** [excalidraw/excalidraw#1484]
It would be nice to have a preset of icons to use on our diagrams. Some examples could be:

- a user icon
- a data store icon
- a server icon
- a cog icon
- etc

Next step could be to have icons of existing services, like AWS/GCP icons to use while drawing such architectures.

Now for the first set of icons, in order to make them feel more hand-drawn we could do some of our own (using rough.js) and have them as presets. For the second set of existing services could be trickier but something for the future maybe.

If we do predefine the first of set of icons on our own, we could even have them respect current font, so a user icon could be drawn with the current scene font style.

What do you think?

Example:
![image](https://user-images.githubusercontent.com/605742/80276313-db1a8a00-86df-11ea-9c8a-3c899bb242f6.png)

**Comment by dwelle** [comment]
This falls under https://github.com/excalidraw/excalidraw/issues/1091
