### ISSUE TITLE
Hebrew Translation

### ISSUE THREAD

**Issue by motcke** [excalidraw/excalidraw#1488]
Hello, I would like to translate Excalidraw to Hebrew

**Comment by j-f1** [comment]
Here you go: https://crowdin.com/translate/excalidraw/10/en-he

Is “עברית” the correct word for Hebrew (so we can put it in the language dropdown)?

**Comment by motcke** [comment]
Yes.
Thanks.

**Comment by j-f1** [comment]
I’ve merged the PR with the translations so far and it should be live shortly!
