### ISSUE TITLE
Can't resize in zen mode

### ISSUE THREAD

**Issue by gaearon** [excalidraw/excalidraw#1510]
1. Toggle zen mode
2. Draw a rect at the left side of the screen
3. Can't resize it. I think something invisible is obscuring the cursor.

**Comment by dwelle** [comment]
Yea, it's the menu scaffolding. We should either hide it (after it animates away), or add a `pointer-events: none`.

![image](https://user-images.githubusercontent.com/5153846/80602396-5ad18d00-8a2f-11ea-9c15-a360b6bf86f8.png)
