### ISSUE TITLE
Inserting newline and text in a previously existing text object: another newline gets added above

### ISSUE THREAD

**Issue by blipp** [excalidraw/excalidraw#1513]
### How to reproduce
1. start with fresh canvas
2. enable the text tool
3. click in the empty space to insert text
4. type a single letter (let's say an "m"), then Enter, then another m
5. click somewhere else to end the text entering/loose focus from the text object
6. enable the text tool again
7. click on the text object
8. press Ctrl+Enter to go to the very end
9. press Enter, type another m
10. click somewhere else to end the text entering/loose focus from the text object

### What happens
After step 10, when the text object looses focus, a newline appears between the first and the second line. Also, the text object moves to the top.

### What should happen
The y position of the first line should be the same/the text object should not move to the top. There should not be another newline appearing between line 1 and 2.

### Environment
Ubuntu 19.10, Firefox 75.0

After step 4 | After step 8 | After step 10
------------ | ------------- | -------------
![Screenshot from 2020-04-29 20-10-25](https://user-images.githubusercontent.com/138279/80632492-a566ff80-8a57-11ea-83a0-05ad4e3b3ed1.png) | ![Screenshot from 2020-04-29 20-10-46](https://user-images.githubusercontent.com/138279/80632490-a4ce6900-8a57-11ea-9412-d1f3c1bf9ad1.png) | ![Screenshot from 2020-04-29 20-10-56](https://user-images.githubusercontent.com/138279/80632484-a39d3c00-8a57-11ea-9070-040349ead084.png)

When I pressed “Print Screen” on my keyboard after step 4, this had the side effect to select the text object (finishing editing). The same happened when I pressed “Print Screen” after step 9; and this had the same effect as step 10. (I carefully cropped the screenshots exactly the same).

This is a “minimal example”. The same effect (newlines appearing in the middle of a text) with larger texts; there, newlines would appear at multiple locations, basically doubling empty lines.

**Comment by dwelle** [comment]
this one is possibly fixed in https://github.com/excalidraw/excalidraw/pull/1195 - can you check here https://excalidraw-a5olj9qd2.now.sh/?

**Comment by blipp** [comment]
I can confirm that in this version, there are no random newlines added :)

However, the text is still moving in the y direction when it looses focus after editing.

**Comment by dwelle** [comment]
I'm not sure if I understand what you mean with the `y` position. Note that the leading/trailing newlines are trimmed after you confirm the text, so that may explain the jump you're seeing.
