### ISSUE TITLE
Just an idea: save .excalidraw directly in IPFS

### ISSUE THREAD

**Issue by karanganesan** [excalidraw/excalidraw#1515]
just had this idea 
what if we can save a drawing directly into IPFS Storage System

just another option to this
<img width="279" alt="Screenshot 2020-04-30 at 10 26 55 AM" src="https://user-images.githubusercontent.com/6049925/80673520-1eed0500-8acd-11ea-80df-28f45a8ea808.png">

url can be appended with the IPFS hash and shared across :)

**Comment by lipis** [comment]
We are not planning on implementing this and keep things simple.
