### ISSUE TITLE
Scroll Horizontally

### ISSUE THREAD

**Issue by jose-donato** [excalidraw/excalidraw#1518]
Shouldn't it be expected to scroll horizontally with shift+Scroll?

[Example](https://www.w3schools.com/howto/howto_css_menu_horizontal_scroll.asp)

Edit: 
browser: Chrome Version 81.0.4044.129 (Official Build) (64-bit)

**Comment by dwelle** [comment]
Didn't know about this, but can confirm this is how it works in Figma and Affinity.
