### ISSUE TITLE
App should have a link to this repo

### ISSUE THREAD

**Issue by bgrosse-midokura** [excalidraw/excalidraw#152]
...or alternatively to the related twitter account, or some help/about page.

**Comment by giovannigiordano** [comment]
PRs are accepted for this. 👍

**Comment by abhikulshrestha22** [comment]
@giovannigiordano Hi, I would like to take this up. Could you please clarify more about what is needed? the link to repo, twitter. Or another page?

**Comment by vjeux** [comment]
I put an icon on the top right but after the new layout it is now behind the canvas and hidden... we should add a zindex to fix it!

**Comment by vjeux** [comment]
Done
