### ISSUE TITLE
Hershey Fonts? 

### ISSUE THREAD

**Issue by msurguy** [excalidraw/excalidraw#1520]
This is a long shot, but what the user could choose from a variety of fonts to label their drawings? 
There is an interesting venue to explore: single stroke fonts, aka Hershey Fonts. 

For example, in this repo you can find a few dozen SVG fonts in this single stroke format, which might bring variety while keeping the unique style to the drawings produced within the application.

Check out the fonts in the repo : https://gitlab.com/oskay/svg-fonts
And the examples of those fonts in use: 
![samples](https://user-images.githubusercontent.com/585833/80786342-30b7c200-8b38-11ea-9b64-da32c1bce577.png)

You can see an example app I created using these fonts: https://msurguy.github.io/cnc-text-tool/

**Comment by lipis** [comment]
We are not planning on adding a font selector or changing the default font at the moment.
