### ISSUE TITLE
There should be the Yakut language translation

### ISSUE THREAD

**Issue by aalliikk** [excalidraw/excalidraw#1521]
Hello! 

Please, someone, add the Yakut language to the list! SO I could start right away the translation process!

Thanks!

**Comment by dwelle** [comment]
Hello. I've given this a quick look, and while I appreciate the offer, it [seems](https://en.wikipedia.org/wiki/Yakuts) that the speaker base is ~500K, 90% of which already speak Russian. That makes the Yakut target around 50K (though I'd be very surprised if those that would use Excalidraw didn't already speak either Russian or English).

On top of that, there are other considerations:

- You'll probably be the only one to be able to translate to Yakut, which means the localization would cease to be up to date should you be unable to continue.
- Apart from bundle size (we currently don't code-split localizations, but this can change in the future), we also probably don't want to end up with a huge list of languages that most users would need to scroll and scan through to be able to find the commonly used languages.

**Comment by aalliikk** [comment]
Thank you for your list of considerations, and I believe, your logic in this list is quite clear. And I think it is the problem here. On the other hand, I don't have authorities to make such decisions as which language should be on the list, but I think I have the authority to explain what the problem is from my point of view. 

On more time, it is just expressing my thoughts, not trying to argue. 

I think you are suppressing the speakers of "those languages" with your statements like "target is around 50K" and it seems to me that you are saying "no need to support those languages as they aren't commonly used". I thought that the Internet is kind of place where everybody can stand out and express themself, even languages, if it is not against the common rules. 

I will surely not be able to stand "for those languages" if I didn't put extra work to learn English language, but I learned English not to forget my own language, but to help my own language. And I thought the project mission is just great and why not these creative people will start supporting any humble beginnings even it is by adding "around 50K" speakers based languages? 

I don't have this influence, for instance, add Yakut language alphabet in iPhones, but it does not mean I can try. That's it. 

Anyway, thank you for your time, and if there is not such possibilities, I think it's OK as well you said, we (with mother tongue around 50K daily usage) can talk in Russian English, may be because of it, because of this mindset.

**Comment by dwelle** [comment]
I didn't want to come across as harsh, but I can see how what I said can be interpreted that way.

Let's go over some of your points.

> I think you are suppressing the speakers of "those languages" with your statements like "target is around 50K" and it seems to me that you are saying "no need to support those languages as they aren't commonly used".
>
> I will surely not be able to stand "for those languages" if I didn't put extra work to learn English language, but I learned English not to forget my own language, but to help my own language. 

I don't believe I was suppressing speakers of a language --- I'm simply making a decision on where to allocate resources, and ensuring the app's scope is maintained.

I think it's great what you're doing, and it's not my place to give my opinion on whether translating technical texts on graphic design software is the best way to preserve a language. But even if it was, our focus at Excalidraw isn't language preservation, so I don't think it's fair to judge us by our efforts in this respect.

> I don't have this influence, for instance, add Yakut language alphabet in iPhones, 

If Yakut uses custom, non-standard alphabet (as opposed to e.g. Cyrillic, which was my impression Yakut uses, but I must be wrong) then the system fonts we're using for UI will likely not support it either.

> one of the reasons you mentioned is "people will be tired by scrolling the list". Don't you think that it would also make them "wow" by the support of languages even with "50K speakers" has the platform?

Yes, that is one consideration, but unrelated to the UX/app-design which should take precedence.

Anyway, this is mostly my own opinion, and that's why I kept this issue open for discussion.

**Comment by aalliikk** [comment]
Thank you very much for such a detailed answer! I highly appreciate it. 

At this point of discussion, I think, it would be better to update README file and add some details to the Translation section. 

So did I. 

https://github.com/excalidraw/excalidraw/pull/1539

Please, review it.

**Comment by dwelle** [comment]
Sorry for the delay in response.

I've taken a look at the PR, and here are my closing thoughts:

The number 500K/50K isn't a magical number that can be applied as a blanket rule for whether we accept a translation or not. Yes, it's *a* factor that helps us gauge *potential* benefit/utility. But we also look at real-word analytics (which take precedence). In your case, the ISO code of Yakut language (`sah`) doesn't appear even once in our data.

If the language doesn't pass either of those checks, we fall back to the reasoning points I've given in my previous comments.

I must note that your case is unique as it has never happened to us yet. Thus I believe adding it to the README doesn't feel necessary as of yet. If we get more requests for adding languages which we don't think are a good fit for us at the time, we will indeed consider adding a mention about it to the README.

Thanks again for your interest and offer to help, and I wish you well in your journey to help preserve and strengthen the Yakut language.
