### ISSUE TITLE
Should we start showing zoom in zen mode ?

### ISSUE THREAD

**Issue by ad1992** [excalidraw/excalidraw#1522]
If you trying zooming in zen mode and then refresh the page you won't realize how much zoomed in you are and how to come out of it unless you know the cmd+0/ctrl+0 short cut keys which is not very intuitive.
Thoughts?

**Comment by dwelle** [comment]
Maybe show zoom level only when it diverges from 100%? Could also be displayed in a more minimal fashion than we do in base mode.

**Comment by ad1992** [comment]
Yes, we can show it when it diverges from 100%, but what do you mean by displaying in minimal fashion? Coz the whole zoom footer is important in case we show it. Or just show how much percentage is zoomed with the reset icon? I think then we can always show the icon if we are just showing the percentage with reset option. Thoughts?

**Comment by dwelle** [comment]
> Or just show how much percentage is zoomed with the reset icon? 

Yes, something like that.

Not sure if we want to show it all the time because it might be most people don't use zoom and it would just be in the way -- you were the one to propose to make zen mode as minimal as possible :).

**Comment by ad1992** [comment]
Yes I know I wanted to keep it minimal  to acheive distraction free drawing but now when I use it I feel zoom is something where people might get lost as cmd+0 is not that intuitive. The only worry is if we dnt show it always and only when zoomed then will it become distractive as it will keep coming and going.. what do you guys think ?

**Comment by dwelle** [comment]
Let's keep it always-on then. Shouldn't be that big of a problem (esp if we don't show the +/- button, and only the reset button + percetange).

**Comment by ad1992** [comment]
Yup only percentage with reset icon.will give pr for the same then 👍
