### ISSUE TITLE
Scroll Horizontally with Mouse

### ISSUE THREAD

**Issue by jsjoeio** [excalidraw/excalidraw#1527]
I'm not sure what changed, but I used to be able to scroll horizontally by holding shift and moving my external mouse wheel.

Now, it does not work. I was able to reproduce this in Chrome too.

The weird thing is that if I hold shift and scroll horizontally with my built-in trackpad, it works as expected. 

Browser: Firefox 75.0
Desktop: macOS Catalina 10.15.3

Not sure if it's related to #1519. 

Note: I tested horizontal scroll [here](https://www.w3schools.com/howto/howto_css_menu_horizontal_scroll.asp) using shift + mouse scroll wheel and it works as expected.

**Comment by dwelle** [comment]
We've recently landed an explicit support for `shift + wheel` to scroll horizontally (https://github.com/excalidraw/excalidraw/pull/1519), so  maybe it broke some native behavior that worked on some devices prior to that?

Can you try if the commit previous to that PR works for you? https://excalidraw-ds54689kr.now.sh/

**Comment by jsjoeio** [comment]
> Can you try if the commit previous to that PR works for you? https://excalidraw-ds54689kr.now.sh/

So thankful for Netlify - I was worried you'd ask me to fork, check out the previous commit and test locally 😂 This is way easier! 

I can confirm that using that commit (the Netlify link) works as expected with the shift + mouse wheel. 

![2020-05-02 12 12 48](https://user-images.githubusercontent.com/3806031/80873543-44fddb00-8c6e-11ea-9370-56eb39d2b927.gif)

**Comment by dwelle** [comment]
> So thankful for Netlify 

Yes, it's awesome. But it's actually Zeit (well, Vercel actually...).

> I can confirm that using that commit (the Netlify link) works as expected with the shift + mouse wheel.

Mhm.. Not sure how to fix this. It seems that on Mac, `shift + wheel` produces `deltaX` instead of `deltaY` as on Windows. I guess we can do `event.deltaY || event.deltaX`, provided `deltaY` will by `0` in your case. I wouldn't wanna detect platform, because I'm not confident it's guaranteed to always work on Mac this way.

**Comment by dwelle** [comment]
Give this a try: https://excalidraw-git-fixwheeldeltax.excalidraw.now.sh/
