### ISSUE TITLE
Firefox cannot add text

### ISSUE THREAD

**Issue by bgrosse-midokura** [excalidraw/excalidraw#153]
Firefox 71.0 on linux won't add the text: after the prompt, I can see a flicker of the "shape options" appear and disappear in the sidebar, and nothing in the drawing area.

It works fine with chromium.

**Comment by giovannigiordano** [comment]
Can you provide a video?

**Comment by dwelle** [comment]
I can repro on Win, so this seems platform independent. The element is still created, but for some reason is invisible or doesn't have dimensions.

**Comment by bgrosse-midokura** [comment]
It's https://developer.mozilla.org/en-US/docs/Web/API/TextMetrics `TextMetrics.actualBoundingBoxAscent`, only supported by Chrome and Safari.

Will submit a PR shortly.
