### ISSUE TITLE
Thank you!!!

### ISSUE THREAD

**Issue by varunarora** [excalidraw/excalidraw#1531]
I am certain that issues is not the right place for this comment, but THANK YOU for creating such an excellent and easy-to-use tool for free, and making it p2p. This is just the pure gold in a world of garbage-sold-as-SaaS-subscription.

My best to @vjeux and all the other contributors. You did this with the react ecosystem and now this and much more to come.

**Comment by vjeux** [comment]
Awww! Thanks so much, that made my day! I'm happy it was useful to you. The only recommendation I would have is to not denigrate the other projects, the authors and contributors are likely working hard on them to make a living.

**Comment by varunarora** [comment]
The tool is wildly useful! I taught a 4-hour lesson on it day-before-yesterday, and each little detail you sweat on made it so painless to use <3

You are 100% right, @vjeux. My apologies! I got carried away by HN posts where indie hackers say they figured out a growth hack and now make $100k per month for a one-person app, charging non-affluent people around the world. I somehow care for some weird and more just utopia when it comes to what the web enables for people.
