### ISSUE TITLE
Feature Request: Copy Elements between 2 Canvas

### ISSUE THREAD

**Issue by garyelephant** [excalidraw/excalidraw#1537]
When I open two excalidraw canvas in two different browser tabs, is it possible to copy element that I have just drawed from one canvas to another.

**Comment by dwelle** [comment]
This falls under https://github.com/excalidraw/excalidraw/issues/859, although your exact request currently doesn't make sense because tabs within the same browser share the same localStorage, thus upon refresh they'll both be synchronized to the same scene (which you probably weren't aware of).

**Comment by franky47** [comment]
Not if you are using one in private browsing, that's usually how I open Excalidraw links to avoid erasing my local sketch.

Having the option to copy/paste from other sketches would open lots of interesting use-cases. I use Excalidraw to do UI mockups, this feature could let me copy/paste my [mobile frames](https://francoisbest.com/posts/2020/mobile-device-frames-for-excalidraw) and other UI elements (buttons, lists, cards etc).

**Comment by dwelle** [comment]
@franky47 That's a good use case I wasn't even aware of. Either way, as per https://github.com/excalidraw/excalidraw/issues/859, supporting this is indeed under consideration. I'll investigate when I get some time.

**Comment by lipis** [comment]
This should work now..
