### ISSUE TITLE
Feature request: Double-sided arrow

### ISSUE THREAD

**Issue by kyldvs** [excalidraw/excalidraw#1548]
Maybe it's possible already and I couldn't figure it out! But would it be possible to add an option to arrows to enable the arrowhead on both the start and end of the line? Right now I have to draw two arrows each time I want a shape like this.

Thanks for building this BTW, It's wonderful to use so far :)

**Comment by dwelle** [comment]
This will be implemented part of #616 (see https://github.com/excalidraw/excalidraw/issues/616#issuecomment-624578470)
