### ISSUE TITLE
Slow scroll in Firefox

### ISSUE THREAD

**Issue by eunjae-lee** [excalidraw/excalidraw#1550]
Hi there,
I didn't have much on the screen. I scrolled fast in fullscreen mode in Firefox and Firefox Nightly. It was lagging.

With the same file, I tried it on Chrome fullscreen and it was fine.

I'm on MacOS. Let me know if you need more information. I'm happy to provide more!

**Comment by dwelle** [comment]
Can you elaborate?

- Are you experiencing a lag, or just slow scrolling? Firefox handles scrolling differently -- for me the scroll steps are very small, too.
- You mention fullscreen (I assume `F`/`F11`), does that mean the issue doesn't happen when you're outside fullscreen?

**Comment by eunjae-lee** [comment]
Hi there, 
I experienced a lag during the scroll.
I tested and without fullscreen mode (F) it was the same.

https://drive.google.com/open?id=15weU9_VTBJYD-7pLuMQdS5aw3KoOPWnX

This is the video of me trying the scroll both in Firefox and Chrome.

**Comment by mcchrish** [comment]
>Are you experiencing a lag, or just slow scrolling? Firefox handles scrolling differently -- for me the scroll steps are very small, too.

For me this is what I experience. Other browsers seems fine. What's different in firefox's handling?

**Comment by dwelle** [comment]
Firefox uses different browser & JS engine, so differences are expected. There's nothing we can really do to target Firefox performance directly. We'll need to address this in an ongoing effort to improve general performance.

**Comment by lipis** [comment]
Seems pretty smooth to me, and since we are not doing anything browser specific, I'm going to close this issue.
