### ISSUE TITLE
Left aligned text is not anchored properly

### ISSUE THREAD

**Issue by kyldvs** [excalidraw/excalidraw#1552]
I would expect a left aligned text box to be anchored on the left side, but it seems to be anchored at the center. This results in pretty weird behaviors where I add text and then the text box moves unexpectedly and I always have to reposition it every time the text changes. It's especially bad when working with a multi-line text box because the entire thing shifts if you add a longer line of text below the existing shorter line.

- In the first example I start with "Hello" aligned to the red line, then type in " world" and it shifts to the left.
- In the second example I start with "Hello World" aligned to the red line then add a longer line below it and it shifts to the left.

<img width="297" alt="Screen Shot 2020-05-07 at 10 52 12 AM" src="https://user-images.githubusercontent.com/1830497/81328124-3853fb00-9051-11ea-9fa6-2439191ef28a.png">

**Comment by dwelle** [comment]
Hello. This is (probably) on track to be fixed sometime https://github.com/excalidraw/excalidraw/issues/1327
