### ISSUE TITLE
Text uses incorrect style on initial load in P2P

### ISSUE THREAD

**Issue by kyldvs** [excalidraw/excalidraw#1553]
(I'm using mac/firefox)

When loading a document in P2P that already has some text, the initial load does not have the correct text styling. After modifying/adding any object the styling appears to get updated correctly.

Initial load:

<img width="1185" alt="Screen Shot 2020-05-07 at 11 11 17 AM" src="https://user-images.githubusercontent.com/1830497/81329763-dfd22d00-9053-11ea-8853-660da01490fa.png">

After adding a circle:

<img width="1218" alt="Screen Shot 2020-05-07 at 11 11 36 AM" src="https://user-images.githubusercontent.com/1830497/81329798-e82a6800-9053-11ea-92f5-e1eefb4b7614.png">

**Comment by dwelle** [comment]
Thanks for the report. I was fixing this in https://github.com/excalidraw/excalidraw/pull/1197, but apparently didn't account for collab scenes. I'll take a look.

**Comment by dwelle** [comment]
@kyldvs can you check if this is fixed in https://excalidraw-git-fixfontloadingforgood.excalidraw.now.sh/?

**Comment by kyldvs** [comment]
Yes, confirmed that it's fixed there! Thanks for the quick turnaround!
