### ISSUE TITLE
Need option to have extra margin for generated image.

### ISSUE THREAD

**Issue by karanganesan** [excalidraw/excalidraw#1556]
eg.

<img width="100%" alt="Screenshot 2020-05-08 at 4 19 39 PM" src="https://user-images.githubusercontent.com/6049925/81398902-ba265000-9147-11ea-8986-a09ab13187ea.png">

it would be great to have 4 margin values to add or a single input to get padding values in pixels

**Comment by dwelle** [comment]
We used to have an input where you could set custom padding, but removed it for simplicity's sake. What's your use case?

**Comment by kcaran** [comment]
I've had to edit exported images before sharing them with coworkers. The default minimum padding on exported images make them feel cramped. I would be happy even with a slightly more generous default padding.

**Comment by dai-shi** [comment]
> I would be happy even with a slightly more generous default padding.

I actually agree with this.

**Comment by dwelle** [comment]
@kcaran @dai-shi still --- what app/website/environment would benefit from more padding? Can you describe a case where it feels too cramped? Usually, when you display an image somewhere, there's a padding added by the website/app itself on top of the image.

**Comment by dai-shi** [comment]
This is controversial and I don't have a strong opinion to break backward compatibility. All I can say is that I _feel_ so. My use case is to copy png to the clipboard and paste it in Slack. Here's the result.

<img width="450" alt="image" src="https://user-images.githubusercontent.com/490574/81409647-70a32880-917a-11ea-83e7-291b36cc2705.png">

The same with Twitter: https://twitter.com/dai_shi/status/1256522186967248896

----

> removed it for simplicity's sake. 

I personally like the simplicity, so I wouldn't customize padding even if there's an option.

**Comment by kcaran** [comment]
I don't think you can assume that the underlying application will add an appropriate padding. For example, Outlook has a black background for displaying images. This is an example of an image I needed to post-process.

![Screen Shot 2020-05-08 at 9 38 52 AM](https://user-images.githubusercontent.com/2607333/81413063-d0fe7f80-9112-11ea-9057-ab2a317a00d2.png)

For the default, I'd rather have it be more generous because cropping is a much simpler post-processing edit than expanding the background.

**Comment by lipis** [comment]
I don't think that we should have an option for it.. bit maybe increasing a bit the padding should be ok.

**Comment by kyldvs** [comment]
I would really like some padding options, I had to wrap my entire drawing in a box unnecessarily so that the image would not feel cramped when sharing. In particular when sharing an image directly with someone and it's viewed in some lightbox the padding is necessary for content around the edges to look decent

**Comment by dai-shi** [comment]
@kyldvs Do you need to change the padding size occasionally in your use cases, or just increasing works for most of your cases? Do you have a specific number in that case?

**Comment by vjeux** [comment]
This sounds like a reasonable change to increase the default padding. @kyldvs do you want to play with the padding and send a PR to what you feel is right?

**Comment by kyldvs** [comment]
I think the problem with a static size is that I drew a relatively large diagram, so when I send it and it is viewed in a lightbox it gets scaled down which makes the margins seem smaller. If I were to pick a fixed size appropriate for this large diagram I suspect it would be too large for smaller diagrams.

I think I would prefer it to be either a 3-state small/medium/large padding, or set a default but allow people to write in a custom padding.

**Comment by vjeux** [comment]
Can you think about reasonable thresholds for when to have smaller or larger paddings based on the situation?

**Comment by kyldvs** [comment]
It looks like I picked a margin of ~80px for my large diagram, when it is scaled down to the size of my screen it is ~16px.

An approach may be to have a default margin of some size (8px?) and then as the exported image grows increase (probably in increments of 4) up to a certain cap (64px? 128px?)

**Comment by vjeux** [comment]
For anyone reading, I'm happy to accept a pull request if someone can come up with a heuristic for padding that seem reasonable.

**Comment by dwelle** [comment]
I'll repost my sentiment from the PR: I think the case for adaptive padding isn't a good fit when embedding images in blog posts and similar (Medium, Twitter etc.). It'll make the image smaller to fit on screen/tweet, and thus harder to read bigger diagrams.

We should think about what's the most common case for PNG exporting, and tailor to that case first.

I'm not against customization in this regard.

**Comment by keul** [comment]
I'm reviving this issue because I've a _similar_ need, but the other way around: the fact that I find padding around my exported object is an issue for me.

I think that a controllable padding would be very useful (in my case: I need a 0 value)

**Comment by lipis** [comment]
> For anyone reading, I'm happy to accept a pull request if someone can come up with a heuristic for padding that seem reasonable.

As we're not going to add an option for it.. I'm closing this issue.

**Comment by architchandra** [comment]
Would love to see an option to control the padding around the exported image. Have to do all kinds of image manipulation stuff that I'm not good at to get the correct padding right now. Thanks!

**Comment by kcaran** [comment]
I know this is closed but I have a workaround to the padding issue that works well for me. I add an invisible rectangle around the image that frames it. The export includes the frame and the space between it and the actual image. I wrote a blog post which hopefully includes more detail: https://www.kcaran.com/posts/excalidraw-add-padding-around-exported-image.html
