### ISSUE TITLE
Freehand drawing and upload image

### ISSUE THREAD

**Issue by JeromeD84** [excalidraw/excalidraw#1559]
Hi,

Congretulations for Excalidraw. it's one of the best.

I would like deploy it in my company, but i think that it's not possible because of missing 2 main fonctionnalities :
- The first is Freehand drawing. With a real whiteboard, we draw with a pen. It's very imprtant
- Upload picture (technical diagram) to work on it

Peraphs this functions exist ? Then, can you tell me how i can use them ?
Or Can you tell if you will developp them ?

Regards

Christopher

**Comment by z3ky** [comment]
I'm also missing both mentioned functions. With those, I could perfectly use excalidraw in classrooms. But I think freehand drawing is not a part of Rough.js. Maybe the line tool with multiple points can be used in a way to realize it.

**Comment by dwelle** [comment]
Hello. For freehand drawing, there's https://github.com/excalidraw/excalidraw/issues/25#issuecomment-626177434, and for there's https://github.com/excalidraw/excalidraw/issues/19, so add your likes there.
