### ISSUE TITLE
Catalan locale (ca-ES)

### ISSUE THREAD

**Issue by HerbCaudill** [excalidraw/excalidraw#1561]
I'm willing to contribute translations.

**Comment by kbariotis** [comment]
Thank you @HerbCaudill! I added the PR and @lipis probably will setup the new language on Crowdin so you can start the translation.

**Comment by lipis** [comment]
https://crowdin.com/project/excalidraw/ca

**Comment by lipis** [comment]
Just a friendly reminder @HerbCaudill

**Comment by HerbCaudill** [comment]
👍👍 done! I brought the other romance languages back up to 100% while I was at it. 

![image](https://user-images.githubusercontent.com/2136620/82122030-54fadc00-9791-11ea-81a6-1c9b5de69a5e.png)

**Comment by lipis** [comment]
Thank you!! Live in few minutes..

**Comment by lipis** [comment]
Hey @HerbCaudill, we've updated quite a few strings.. could you give us a hand again with Catalan? https://github.com/excalidraw/excalidraw/pull/2620
