### ISSUE TITLE
FontAwesome Icons support?

### ISSUE THREAD

**Issue by kokanek** [excalidraw/excalidraw#1564]
It would be a great feature to add FontAwesome icons support to the tools panel.

Is this being considered as an addition in the future?

I am thinking of giving it a shot.

Let me know if there are any threads regarding any discussions in that direction.

**Comment by dwelle** [comment]
Do you mean like a drop-in assets that you can use in your drawings? https://github.com/excalidraw/excalidraw/issues/1091

**Comment by kokanek** [comment]
I was thinking more around the lines of adding a new tool in the toolbar called "Icon". 
Selecting this tool would let us include one of these free font awesome icons in the canvas by maybe searching through an interface:
https://fontawesome.com/icons?d=gallery&m=free

**Comment by dwelle** [comment]
What you describe still falls under an asset library, except you'd also like to make these particular assets (fontAwesome icons) added to the shapes toolbar --- this will likely not happen. If we do implement an asset library, even that might not get a dedicated button in the toolbar (which we want to keep minimal), but if it does, it should include all assets, not just a subset (fontAwesome).

As such, I'd close this issue in favor of #1091, and you can comment there with your specific proposal.

**Comment by Mrazator** [comment]
I agree it could be a good idea! Let's track it in #5034, as once we support svgs in libraries, we could publish librariers containing some popular fontawesome icon bundles.

@barnabasmolnar @maielo we might want to have separate categories for libraries in the future, i.e.: "Icons" category in this case.

Anyway, I don't think though that we will be adding "searching through an interface" specifically for font awesome.

**Comment by PHHENS** [comment]
Thanks for your feedback, supporting svg in libraries and having libraries containing 
font awesome icons would bring a major improvement in Excalidraw.
Would be happy to try it as soon as possible ;-)
Thanks
