### ISSUE TITLE
free draw and load pdf 

### ISSUE THREAD

**Issue by JOEMAIER101** [excalidraw/excalidraw#1569]
Is there a fix to **load pdf or pasting an external image** and **draw free-style**.

I've tried adding code fix, but the fixes are sitting behind the canvas, and hence are of no visual help

**Comment by dwelle** [comment]
Hello. For freehand drawing, there's https://github.com/excalidraw/excalidraw/issues/25, and for image uploading there's https://github.com/excalidraw/excalidraw/issues/19.

As for uploading pdf, there's no issue yet, but I don't understand how that would work.

**Comment by kbariotis** [comment]
#25 is closed and we are working on #19 now. @JOEMAIER101 thank you for your suggestions, hopefully we will finish this really soon. If you want to track progress or be involved in any way, join us on #19. 

I will close this.
