### ISSUE TITLE
Add "Show/hide UI" button to right-click menu (zen mode to context menu?)

### ISSUE THREAD

**Issue by mxstbr** [excalidraw/excalidraw#1581]
Figma has a "Show/Hide UI" button that triggers the entire UI being hidden which is very useful for demoing/screen sharing.

Would love to see that in Excalidraw!

**Comment by dwelle** [comment]
We already have Zen mode, which hides most (but not all) buttons. But it's accessible only by a hotkey at the moment --- `Alt + Z` (you can check the shortcut help dialog at the bottom right of the screen).

**Comment by mxstbr** [comment]
Ohh that's already super close, nice!

**Comment by kannes** [comment]
Commenting on this because I ended up here when googling if I could hide the GUI: On a QWERTZ layout, the shortcut is Alt+Y.
