### ISSUE TITLE
Can’t find undo when using Safari on iPad

### ISSUE THREAD

**Issue by sbuettner** [excalidraw/excalidraw#1584]
Undo functionality not visible in viewport when using Safari on an iPad. Neither in horizontal or vertical mode.

![image](https://user-images.githubusercontent.com/1607241/81775448-2957c780-94ed-11ea-91fb-710ac8dd0ebe.jpeg)

![image](https://user-images.githubusercontent.com/1607241/81775464-2f4da880-94ed-11ea-932f-e3164cc4c5a4.jpeg)

**Comment by dwelle** [comment]
Yea, we're using mobile UI scheme based on dimensions, not user-agent. Maybe we should reconsider? /cc @j-f1 @Fausto95

**Comment by Fausto95** [comment]
We should consider something hybrid

**Comment by j-f1** [comment]
Or we could make the undo/redo always visible

**Comment by acowlikeobject** [comment]
Just stumbled upon Excalidraw.  It looks fantastic!  But also happened to be on an Android tablet  and spent a good while looking for an undo.

Love the speed and minimalism of the site, but undo/redo may be sufficiently core to most people's workflows to merit a space on the toolbar, at least on phones/tablets.  Without them, usability suffers badly.

**Comment by pojntfx** [comment]
I can confirm this happening (Safari & Chrome on iOS 14) - it's a deal breaker for my personal usage as I do potentially destructive actions all the time.

**Comment by dwelle** [comment]
Closing in favor of more generic https://github.com/excalidraw/excalidraw/issues/1584

**Comment by j-f1** [comment]
@dwelle that’s this issue

**Comment by dwelle** [comment]
Thanks — I'm doing this all too often :). I meant: https://github.com/excalidraw/excalidraw/issues/3162
