### ISSUE TITLE
Free draw selection

### ISSUE THREAD

**Issue by bratsos** [excalidraw/excalidraw#1586]
First of all, I'm really glad to see this project evolving that much and so quickly! Great job to everyone!

After using free draw on my laptop and on my iPad I found out that most of the time, when using free draw I don't want to select the shape I justed draw; I just want to continue with my drawing.

For example, this simple drawing requires 12 clicks (half of them are switching between selection/free draw tool).

On desktop I can handle this using the hotkeys, but on tablet its unintuitive 
<img width="365" alt="Screenshot 2020-05-13 at 12 27 41 PM" src="https://user-images.githubusercontent.com/12677111/81795764-2670cd00-9515-11ea-9784-5303be2e25e8.png">

What do you think?

I can send a PR with a fix if we all agree that this is an issue.

**Comment by dwelle** [comment]
That's what the lock is for:

![image](https://user-images.githubusercontent.com/5153846/81799181-44d4c980-9511-11ea-8ed0-91d5b2ff1517.png)

We need to make it more intuitive.

There's also an open proposal for making it the default https://github.com/excalidraw/excalidraw/issues/1206

**Comment by bratsos** [comment]
Wow I'd never thought about clicking that lock button for this. TIL 😅 

Thanks, I guess there's nothing more to discuss here 🚀

**Comment by vjeux** [comment]
@dwelle I think for free drawing, we should keep it enabled by default. For shapes, I very frequently want to move it around after drawing them but hasn't been my experience for free drawing. Thoughts?

**Comment by dwelle** [comment]
> I think for free drawing, we should keep it enabled by default.

Maybe, although it will create a behavior inconsistency between shapes. Also, would you force it for free draw, or would you want to auto-lock with the ability for users to unlock if they wish to?

> For shapes, I very frequently want to move it around after drawing them but hasn't been my experience for free drawing. Thoughts?

True. One thing I didn't mention in https://github.com/excalidraw/excalidraw/issues/1206#issuecomment-609011447 is that with the hybrid proposal, you can even move shapes by dragging their outline (not body):

![excal_hybrid_tool](https://user-images.githubusercontent.com/5153846/81842055-aade4280-954b-11ea-9c55-8f3de9143305.gif)

This is of course a long-shot proposal, and even if implemented we should probably still support the previous two modes.

**Comment by lc3t35** [comment]
@bratsos hi, could you please state which ipad iOS version you have, are you using Safari or Chrome. Mine is 12.4.4 and I can't draw anything, the only thing that works is adding a text, but I can't select or move it. I'm updating to 12.4.7 to see if it fixes the problem.

**Comment by bratsos** [comment]
Hey @lc3t35 sorry for the late reply. I'm on iPad 13.4.1 and Chrome 81.0.4044.124
