### ISSUE TITLE
Is there a logo.svg

### ISSUE THREAD

**Issue by tiensonqin** [excalidraw/excalidraw#1590]
First of all, thank you for this project, I have a lot of fun with this!

I'm working on an offline notes app, currently, I'm using an iframe to add excalidraw to the app, 
and I want to show your logo on the page header instead of another draw icon.

**Comment by Fausto95** [comment]
Hi there, we’re glad that you find the app interesting. 
All the logos live here https://github.com/excalidraw/excalidraw-logo

**Comment by tiensonqin** [comment]
ah, my bad, :+1:
