### ISSUE TITLE
Feature Request: Ability to provide a custom font-size

### ISSUE THREAD

**Issue by tusharmath** [excalidraw/excalidraw#1591]
Hi,

Is there a way we can add a custom font-size option. Sometimes `Very Large` isn't large enough. I guess, there should be a text box for it so that one can enter a custom value for the font.

**Comment by dai-shi** [comment]
In terms of simplicity, it would be nice to make texts resizable like other shapes. That would relates to #1218.

**Comment by lipis** [comment]
This is fixed already! You can simply resize the text elements now.
