### ISSUE TITLE
TypeScript error in /usr/src/app/src/components/App.tsx(134,22): Could not find a declaration file for module 'lodash.throttle'. 

### ISSUE THREAD

**Issue by mohammadrabetian** [excalidraw/excalidraw#1593]
I get this error when I try to build the container..
I cloned the project and tried to build it with `docker-compose up --build -d`

```bash
Step 6/10 : COPY . .
 ---> 55c910bb8468
Step 7/10 : RUN npm run build:app
 ---> Running in 0bf1ba6d20ae

> @ build:app /usr/src/app
> REACT_APP_GIT_SHA=$NOW_GITHUB_COMMIT_SHA react-scripts build

Creating an optimized production build...
Failed to compile.

/usr/src/app/src/components/App.tsx
TypeScript error in /usr/src/app/src/components/App.tsx(134,22):
Could not find a declaration file for module 'lodash.throttle'. '/usr/src/app/node_modules/lodash.throttle/index.js' implicitly has an 'any' type.
  Try `npm install @types/lodash.throttle` if it exists or add a new declaration (.d.ts) file containing `declare module 'lodash.throttle';`  TS7016

    132 | } from "../data/localStorage";
    133 | 
  > 134 | import throttle from "lodash.throttle";
        |                      ^
    135 | 
    136 | /**
    137 |  * @param func handler taking at most single parameter (event).


npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build:app: `REACT_APP_GIT_SHA=$NOW_GITHUB_COMMIT_SHA react-scripts build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ build:app script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-05-14T10_54_57_965Z-debug.log
ERROR: Service 'excalidraw' failed to build: The command '/bin/sh -c npm run build:app' returned a non-zero code: 1
```

**Comment by dahawk** [comment]
Maybe this helps a little, it definitely confused me quite a bit.

Quickly to my background, I work with docker a lot but have no significant experience with development in nodejs or ts. I normally just run the builds and deployments, using docker. I was trying to deploy excalidraw when I encountered a road block in form of the error message mentioned in the message by mohammadrabetian.

When you run docker build, you will get the same error as stated above. This is not much surprise as docker-compose up --build just runs a regular docker build.

However, if you run a node:14-alpine image interactively (_docker run -ti -w /usr/src/app node:14-alpine /bin/sh_) and run the steps that are outlined in the dockerfile as shown below, the build succeeds (as the dockerfile runs two copy commands at different times, I have to add them via docker cp for the same effect -> italics = docker commands outside the interactive container, code-block = shell commands inside the interactive container).

Assumption: the current working directory outside the container is this git repo.

`export NODE_ENV=production`

_docker cp package.json package-lock.json <container_id>:/usr/src/app/_

`npm install`

_docker cp * <container_id>:/usr/src/app/_

`npm run build:app`

This will produce a valid build output that can be deployed.

**Comment by vincentfretin** [comment]
Because of 
`ENV NODE_ENV=production`
The command `npm install` doesn't install devDependencies declared in `package.json`.
You can remove the line `ENV NODE_ENV=production`
and define it inline like this:
`RUN NODE_ENV=production npm run build:app`

**Comment by mohammadrabetian** [comment]
Thank you @vincentfretin
