### ISSUE TITLE
Feature Request: Animated Drawing

### ISSUE THREAD

**Issue by erikras** [excalidraw/excalidraw#1597]
I really adore the hand-drawn effect you guys have created. I've already used some Exalidraw drawings in some keynote presentations. The other day I discovered a "Line Draw" build animation in Keynote and it made me think how cool it would be if Excalidraw could do something similar. It's unclear to me how deep Excalidraw would want to get into creating a "timeline", but maybe the drawing of some selected group of items could be exported to a gif or something?

Here's what I can do in Keynote, and sort of what I'm imagining in Excalidraw:

![Screen Recording 2020-05-14 at 17 00 53](https://user-images.githubusercontent.com/4396759/81951676-c017a780-9605-11ea-80ee-5361b330d9bc.gif)

Just a thought. @dwelle [suggested I make an issue](https://twitter.com/dluzar/status/1260922584436269057).

**Comment by dwelle** [comment]
Thanks for issue.

I could see this go two ways:

1. Animate on screen, which could be used for #253 if that ever gets implemented. This implementation would have many open ended questions: when does the animation start/stop. How to add it to the UI etc.

2. On export, allow to export to GIF which would automatically animate everything on screen.

(2) feels like something that we could add with minimal impact on UI complexity.

As for implementation, I think the biggest hurdle (but it may turn out to be the smallest one) is to ensure everything animates the way it should. I have no experience in this regard.

Recording itself could be done via [HTMLCanvasElement.captureStream()](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/captureStream), or [spite/ccapture.js](https://github.com/spite/ccapture.js/).

Let's see if more people are interested in this, or if anyone has other ideas of how this should work.

**Comment by dai-shi** [comment]
I am interested (as a user).

**Comment by dai-shi** [comment]
And actually, I'm interested in it as a developer. https://twitter.com/dai_shi/status/1261683775924105218

**Comment by dwelle** [comment]
Also, since you both expressed interest, what was your intended use case? Having GIFs in blog posts, or on social media or something?

**Comment by erikras** [comment]
My interest: I was putting together [a talk](https://youtu.be/pn0pIgdQvhU) that involved the particular animation I included above. And I'm a huge fan of Excalidraw, looking for nails to hammer with it ever since learning of its existence, so I thought, "Wouldn't it be cool if the thing that looks like it was sketched, could be sketched before your eyes?" Sort of like what's cool about the [RSA Animate](https://www.youtube.com/watch?v=u6XAPnuFjJc) video series.

My imagined use case was for both presentations, explainer videos, gifs that animate as you scroll down on some corporate homepage, or even just gifs for sharing on social media (like [Let Me Google That For You](https://www.lmgtfy.com)).

Not all of us can afford a Maggie Appleton. 😄

**Comment by dai-shi** [comment]
Almost all covered. I was imagining YouTube videos like RSA Animate. I personally don't do it though. My personal use case would be for Tweets. Manual animation doesn't work for me. I would like to have it ideally fully automated, even if it's not 100% intended.

**Comment by erikras** [comment]
This project released today might be relevant here... [Rough Notation](https://roughnotation.com)

**Comment by dwelle** [comment]
That's made by one of our own, and none other than the creator of roughjs itself (the library we're building excalidraw on): @pshihn --- good job on that one!

**Comment by garyelephant** [comment]
Need this feature +1

**Comment by dai-shi** [comment]
@garyelephant Have you tried the unofficial tool [excalidraw-animate](https://github.com/dai-shi/excalidraw-animate), or not?

**Comment by garyelephant** [comment]
> @garyelephant Have you tried the unofficial tool [excalidraw-animate](https://github.com/dai-shi/excalidraw-animate), or not?

Fantastic

**Comment by lipis** [comment]
We'll mark is at out of scope for the core functionality of excalidraw.. Use [excalidraw-animate](https://github.com/dai-shi/excalidraw-animate) by @dai-shi in the meantime.
