### ISSUE TITLE
Support resizing text

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#1603]
Prerequisite of https://github.com/excalidraw/excalidraw/issues/1218.

There's also been some requests to support other text sizes than the 4 we currently support, and this would partially address that.

**Comment by vjeux** [comment]
The data model already supports arbitrary font sizes. We could allow resizing text with the handle to change the font size and show the left panel size as undefined if it doesn’t fit one of the preset.

**Comment by dai-shi** [comment]
Cool. The hard part is the bounding box, especially resizing from `nw`. I haven't looked into the code yet. I assume it's calculated somewhere. I'd tackle this, once I finished group-resizing of two-point lines.

**Comment by dai-shi** [comment]
From `se` without rotation is fairly easy. Looks like we should have 10px at minimum.

![exdraw46](https://user-images.githubusercontent.com/490574/82816936-02c76280-9ed7-11ea-9668-53d9b0771a24.gif)
