### ISSUE TITLE
Support editing existing lines/arrows

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#1605]
We can support editing existing arrows on enter/double-click of an arrow, and then either:

1. **Non-bezier:** only display existing points, where you can select each and move it, or delete it. Adding new point could be done e.g. via `Cmd+click` anywhere (we would display hint).

    You can insert points in the middle of two points by hovering over the line between them, and click (or do what Figma does, and show a ghost point in the middle when hovering over the line between two points).

    ![image](https://user-images.githubusercontent.com/5153846/82116484-7a282400-976a-11ea-8178-ad33cfb1f651.png)
    
2. **Bezier:** on top of the above, display bezier handles

    ![image](https://user-images.githubusercontent.com/5153846/82116491-81e7c880-976a-11ea-8c67-8219197c726c.png)
    
I'd personally start with (1), even if we wanted to ultimately support (2)

/cc @petehunt @vjeux @dai-shi

**Comment by dai-shi** [comment]
IMO, (2) is too much, but it doesn't hurt my usage anyway (I mean I'd ignore). It would be nice to delete points of "draws".

**Comment by vjeux** [comment]
Agreed about (2), I wouldn't show it. Just displaying points and mid-points is what I would expect for this feature.

**Comment by dai-shi** [comment]
> Bezier: on top of the above, display bezier handles

Now, I remember I saw this here. If we were to build a vector editor, it would be required to edit arbitrary svg path like this. Otherwise, we'd stick with import-only svg path (not editable).
