### ISSUE TITLE
Resizing non-solid lines may change the position of the object

### ISSUE THREAD

**Issue by lusingander** [excalidraw/excalidraw#1606]
Resizing non-solid lines (Lines, Arrows, Free draws) may change the position of the object.

![200517](https://user-images.githubusercontent.com/31386431/82133150-30e7db00-9823-11ea-90be-28558ffd7ef4.gif)

**Comment by lusingander** [comment]
In `resizeSingleElement`, I suppose that it is wrong that `[element.x, element.y]` and `[nextElementX, nextElementY]` have different values when `e`, `se`, and `s` are moved, but I didn't know any more...

**Comment by dai-shi** [comment]
Does this only happen with dashed and dotted? Interesting.

**Comment by dai-shi** [comment]
Hm, this simple one doesn't reproduce it.

![exdraw43](https://user-images.githubusercontent.com/490574/82133548-97bbc300-9828-11ea-952c-a2227cfb7ec5.gif)

**Comment by dwelle** [comment]
I can repro on dashed/dotted lines when resizing to the negative:

![excal_neg_resize_dotted](https://user-images.githubusercontent.com/5153846/82140214-62b26f00-982e-11ea-858f-4d4a7fbcedb8.gif)

I'll need to review the PR if there's something that could explain it.

**Comment by dwelle** [comment]
It seems it's related to rough's `disableMultiStroke`. When set to `true`, this resize bug manifests.

Do we in any way depend on internal implementation of what roughjs renders?

**Comment by dai-shi** [comment]
`getResizedElementAbsoluteCoords` does the job. We need to calculate the accurate coords while resizing. Only the way possible is to render with roughjs. ref: https://github.com/excalidraw/excalidraw/issues/1275#issuecomment-613245201

**Comment by dwelle** [comment]
I'm not seeing where `getResizedElementAbsoluteCoords` handles two-path shapes differently than single-path elements. Nor am I seeing difference in output when logging it.

**Comment by dai-shi** [comment]
BTW, have you already checked #1608?

**Comment by dwelle** [comment]
No... damn :smile:
