### ISSUE TITLE
TIP: implement tabs as projects

### ISSUE THREAD

**Issue by kleinpetr** [excalidraw/excalidraw#1609]
Hello,

it would be great to work with tabs inside excalidraw. I think its better way then using single projects.

I am implemented tabs in Vue.js here https://konfigurator.kmfire.cz which is configurator for electric cases, but the tabs are powerful I think. 

In this project I also saving data to the browser Local storage, but I am saving it in the List and every object in list is presented like a tab. User can rename the tab.

What do you think about it?

**Comment by dwelle** [comment]
Hello.

There's already feature request for tabs: https://github.com/excalidraw/excalidraw/issues/1543

The underlying implementation isn't so important right now, that will be figured out, but thanks for the suggestion.
