### ISSUE TITLE
Build to Docker hub

### ISSUE THREAD

**Issue by guillaumebriday** [excalidraw/excalidraw#1621]
Hey,

I think it would be great to publish this project on the [Docker Hub ](https://hub.docker.com/).

It already has a Dockerfile and it would be pretty easy to automated the build process with Github Action.

Would you accept a PR for this feature? 

Thank you for your work! 🙏

**Comment by kbariotis** [comment]
Yes @guillaumebriday, that would be great. We talked about it before and it would be awesome for people that want to self-host their own Excalidraw. Please go on with a PR and I will assist you as well because I've done some experiments before.

Thank you :)

**Comment by guillaumebriday** [comment]
@kbariotis I opened a PR if you want to take a look 😃
