### ISSUE TITLE
Show the degrees when using rotation locking

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw#1629]

**Comment by ansumanshah** [comment]
@lipis may I pick this up?

**Comment by dwelle** [comment]
Actually, I'd maybe discuss this first.

This feature may be more suitable to an "architect" mode or something, when we later introduce grid/object snapping etc.

If we add this right now, people will also want to add things like `x`/`y` coord labels when moving elements, `width/`height` labels and similar, and soon drawing on excal won't feel like drawing on a whiteboard anymore.
