### ISSUE TITLE
Double-click to add text

### ISSUE THREAD

**Issue by gaearon** [excalidraw/excalidraw#163]
Don't remember which tool does that but I've gotten used to it and miss it a lot. For example, after drawing a rectangle the first thing I do is try to double click it to write inside.

**Comment by vjeux** [comment]
For context, what zwibbler does is that rectangles also have a text property where it's displayed in the center.

Not sure what we want to actually implement but both would help solve this common use case.

**Comment by hmaurer** [comment]
@gaearon [Whimsical](https://whimsical.com/) is another tool (amongst many I'm sure) that does this.

**Comment by vjeux** [comment]
For people reading, we should definitely implement the original suggestion. PR welcome
