### ISSUE TITLE
Support multiple instances of Excalidraw / One instance of Excalidraw shouldn't affect other.

### ISSUE THREAD

**Issue by ad1992** [excalidraw/excalidraw#1637]
Currently multiple instances of excalidraw are not supported. If I try to render two versions of Excalidraw, the changes made in one gets affected in other.
As far as I have debugged its due to the sharing of global scene and history .
I am not sure if there was some specific reason to not attach these to the instance itself rather than keeping it global.
But I think we should fix so that the App in itself is independent and also gets cleaned up when unmounted. 

This will also lead to issues for example if later we add tabs then the drawings from one tab will get onto the other tab as well.

![Excalidraw _ Hand-drawn look   feel • Collaborative • Secure](https://user-images.githubusercontent.com/11256141/82751379-5309cc00-9dd4-11ea-932f-2f8aedfdd8ea.gif)

What do you guys think?
There are multiple approaches to solve this and I would be happy to take this up.

**Comment by kbariotis** [comment]
Tabs have also been requested on https://github.com/excalidraw/excalidraw/issues/1543.

Something to consider here is that currently the local storage comes handy when you close the tab and open it after a while. I'm not sure if that's the best approach but it is what is now and it will be altered if we removed the single local storage entry.

One way to go about this is every time you open Excalidraw, generate a new local storage entry. **BUT** once you close a tab, you can never go back to it.

Maybe in order to keep backward compatibility, we can also think about how to bring tabs accessibility on the UI. So even if you close a tab, you can open a new one and somehow navigate to previous entries. Essentially creating a file system using local storage.

@dwelle talked about local storage limitations in size, so that's something we need to consider. We talked about migrating to IndexedDB on #711 .

**Comment by dwelle** [comment]
I don't think we'll want to separate instances for each tab, but I haven't given it much thought yet.

**Comment by ad1992** [comment]
@kbariotis I am not sure If you got the issue correctly.. right now it's not possible to render multiple independent instances of excalidraw as you can see above I tried to render the `App` twice in `index.tsx` and both are sharing the same global scene and history which ideally shouldn't happen as both should have their own history and global scene. Whether we add tabs in the future but it would be better not to share the scene/history so adding such features (which will have multiple excalidraw) becomes easy as well.

I found this issue when I was integrating Excalidraw into HackerRank where we give a dropdown to add a question of type `whiteboard` so interviewer can add multiple whiteboards(which are essentially multiple excalidraws) so to fix this I had to add some hacks.


IMO every instance should be independent on its own and shouldn't affect the other instances.

Thoughts?

**Comment by petehunt** [comment]
big +1 to this! one of the annoying things to do will be to pass around references to the `globalAppState`. i wonder if we want to have a way to associate an `ExcalidrawElement` instance with it so we don't have to add an extra parameter anywhere...

**Comment by ad1992** [comment]
> big +1 to this! one of the annoying things to do will be to pass around references to the `globalSceneState`. i wonder if we want to have a way to associate an `ExcalidrawElement` instance with it so we don't have to add an extra parameter anywhere...

Yup once it's an instance property we will have to pass the references for history and global scene. But I didn't get what you meant by `i wonder if we want to have a way to associate an `ExcalidrawElement` instance with it so we don't have to add an extra parameter anywhere...`. Could you explain more @petehunt ?

**Comment by dwelle** [comment]
> one of the annoying things to do will be to pass around references to the `globalSceneState`. i wonder if we want to have a way to associate an `ExcalidrawElement` instance with it so we don't have to add an extra parameter anywhere...

Yea, DX will suffer. Not sure how to work around it. We can't store the instance reference on elements because we'd need to strip & renew on serialize/deserialize/clone/undo/redo. Similar for `WeakMap<element, instance>`.

**Comment by petehunt** [comment]
@dwelle i was gonna suggest that everywhere we create an element we store it in a `WeakMap<ExcalidrawElement, GlobalScene>` map. it's definitely a little questionable but it will make shipping this a lot easier :)

**Comment by dwelle** [comment]
> @dwelle i was gonna suggest that everywhere we create an element we store it in a `WeakMap<ExcalidrawElement, GlobalScene>` map. it's definitely a little questionable but it will make shipping this a lot easier :)

In theory, it should work, but we'll need to be extra careful to populate WeakMap in all the right places (cloning elements before storing them to history, etc.).

**Comment by ad1992** [comment]
If I understood correctly you are saying to attach the global scene to every Excalidraw element right? 
But do we need to attach the global scene to every element? 
Instead won't it be easier to maintain global scene at the class level and pass the reference wherever needed?

**Comment by ad1992** [comment]
My initial approach was to attach the global scene and history to class and pass the reference wherever needed so it gets destroyed when the component unmounts as well. 
I had to pass it to all the places where it was being used but this might be safe to do. 

@dwelle @petehunt what do you think?

**Comment by dwelle** [comment]
> My initial approach was to attach the global scene and history to class and pass the reference wherever needed so it gets destroyed when the component unmounts as well.

If we use `WeakMap` it should work the same way (memory-wise). I wouldn't want to be passing it everywhere as it would complicate the codebase a lot.

**Comment by dwelle** [comment]
Note that for the WeakMap workflow, we'll need to use workarounds for cases where we only work with `id` references, such as `LinearElementEditor.ts`. There we'll need to map it onto `appState.editingLinearElement` object (and ensure we renew on history undo/redo etc.). I'm sure there will be other cases.

So again, I want to ensure we're solving real problems here. AFAIK the only case we need this rewrite for is embedding excalidraw.

**Comment by ad1992** [comment]
@dwelle it's true I found this issue when integrating excalidraw but irrespective of it I think we should solve it as later also If we plan to add any such feature where multiple instances are needed then this rewrite will be needed for sure. So this rewrite would be worth it as right now its a limitation to support only one instance.

**Comment by marcospgp** [comment]
It seems this issue has returned? https://github.com/excalidraw/excalidraw/issues/4837
