### ISSUE TITLE
remove versionNonce

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#1639]
I propose we drop `versionNonce`, because it adds I believe unnecessary complexity that can only increase in time.

@petehunt you're right that my previous comment elsewhere about replacing `version` with `randomInteger()` was of course a nonsense. We indeed need it to be sequential so that we know which version is newer.

As for the reason for `versionNonce`, I understand we must deterministically decide between two identically versioned elements to ensure clients converge at correct state.

### Proposal

Make `version` into `Date.now()` (+ ensure we don't generate the same `version` twice, see below). This will make two different versions pretty far apart from each other, but that shouldn't matter.

This in itself will make `version` into high-enough precision to keep conflicts at minimum (and concurrent edits of the same element are rare to begin with), but in the unlikely event conflicts arise, we can do a deterministic decision using `JSON.stringify(localElement) < JSON.stringify(remoteElement)` (this should be deterministic, but if we're worried, we can run it through `.split('').reduce((c, x) => c + x.codePointAt(0), 0)`).

As for ensuring we never generate same version twice, we can do a simple check:

```
let newVersion = Date.now();
// this should be very rare as we generally increase versions in event callbacks
if (newVersion <= element.version) {
  newVersion = element.version + 1;
}
```

**Comment by dwelle** [comment]
Actually, just as I posted this I realized we can't depend on `Date.now()` being sequential across machines.

**Comment by dwelle** [comment]
Mhm, I just realized one reason for why we need `versionNonce`: history. We need something to use as a key (and a quick discriminant) in case of conflict. While this could be worked around, it's probably not worth it at this point.

We need a document explaining this so people don't waste time in the future figuring out why we need `versionNonce`.

**Comment by dwelle** [comment]
But here's a question: why do we use `version` anywhere except in collab syncing? We don't even need to use `version` anywhere in the history.

**Comment by vjeux** [comment]
version and versionNonce were added as a concept for collab syncing. They shouldn't be in use anywhere else.

**Comment by dwelle** [comment]
> version and versionNonce were added as a concept for collab syncing. They shouldn't be in use anywhere else.

They must be used at least in history. But we don't need to use `version`. We care about uniquely differentiating two elements across machines, and `versionNonce` should be enough.
