### ISSUE TITLE
Paste should always go inside viewport

### ISSUE THREAD

**Issue by gaearon** [excalidraw/excalidraw#164]
1. Copy something
2. Scroll far enough left and/or down so you don't see the original thing
3. Paste it

I think it should be pasted within viewport. Otherwise I have to scroll all the way up to find it, but I'm already where I want to put it.

**Comment by vjeux** [comment]
I think that makes sense and would be easy to implement. If anyone is up to implementing it.

**Comment by abhikulshrestha22** [comment]
Hi @vjeux , I would like to take this up. :)

**Comment by giovannigiordano** [comment]
@abhikulshrestha22 PRs are accepted
