### ISSUE TITLE
Alt-drag to copy

### ISSUE THREAD

**Issue by gaearon** [excalidraw/excalidraw#165]
Like in Keynote (I think?), alt-dragging should duplicate and move the duplicate, instead of moving the original.

**Comment by jaredpalmer** [comment]
Related: <kbd>Cmd + D</kbd> usually duplicates (e.g. sketch/figma)

**Comment by jeremyscatigna** [comment]
I’d love to help on this !

**Comment by dwelle** [comment]
fixed in #255
