### ISSUE TITLE
Offer Grayscale font as additional hand-drawn option

### ISSUE THREAD

**Issue by TimoSta** [excalidraw/excalidraw#1651]
There is a new faux-handwriting font on the block: [Grayscale](https://twitter.com/charliprangley/status/1264906341908447237)!

![grayscale sample](https://pbs.twimg.com/media/EY3ZryRXQAA0R_Z?format=jpg&name=medium)

I believe it would fit in perfectly with Excalidraw, as a middle ground between the current _normal_ and _hand-drawn_ options. I hope that may be more legible than the current hand-drawn one in small font sizes, without becoming sterile.

It looks like Charli, the designer of the font, [is interested in a collaboration](https://twitter.com/charliprangley/status/1264949691629912068).

Maybe worth considering? Curious to hear your thoughts.

**Comment by mapbakery** [comment]
I like the font, especially because the numbers are much more legible.

**Comment by lipis** [comment]
How many languages does it support?

**Comment by TimoSta** [comment]
@lipis -- Western European lanuages only at this point:

> Initially drawn by hand with a brush marker, Grayscale is a sans-serif font designed to look good in all-caps settings as well as in sentence case. Along with the standard letterforms, the font features **useful symbols and punctuation and has multilingual support for Western European languages**.

https://charlimarie.com/product/grayscale

**Comment by dwelle** [comment]
For those wondering, according to [this site](https://www.languagescientific.com/translation-and-localization-of-western-european-languages/), it includes:

```
Catalan
French-EU
Greek
Romansch
Dutch
French-Switzerland
Italian
Scottish
Dutch-Belgian
Gaelic
Italian-Switzerland
Spanish-Spain
English-British
German
Maltese
Turkish
Flemish
German-Austria
Portuguese-EU
Welsh
French-Belgian
German-Switzerland
```

**Comment by lipis** [comment]
We also support some Asian characters so that's not compatible with our current font. But having said that in general I'm down to get a font that is actively supported even if it's paid, as we can get support in an easier way and incrementally adding more characters.

**Comment by thorn0** [comment]
@dwelle What does that site have to do with this font? 🤔

**Comment by dwelle** [comment]
> @dwelle What does that site have to do with this font?

Not sure what you mean. I simply listed what languages belong to Western European languages. Whether Grayscale really includes characters for all those languages is unclear.

**Comment by xixixao** [comment]
I would love to see a better default font. I was thinking why I wouldn't use excalidraw in an interview, and the current font would be a blocker (if it was the only one - but then again now I have to explain to someone else that they should switch to use a non-default font - that's a bit complicated). This one looks awesome, handwritten-like yet readable (although I'd like to see some text written up in it), but the character set is really limited.

**Comment by xixixao** [comment]
I was thinking that maybe this one could work, but it feels too regular even on max settings:

https://www.recursive.design/

https://github.com/arrowtype/recursive

License and character set support look good.

<img width="1239" alt="Screen Shot 2020-07-23 at 21 09 36" src="https://user-images.githubusercontent.com/1473433/88359873-20734580-cd29-11ea-84e1-73a3e1bc4054.png">
<img width="1015" alt="Screen Shot 2020-07-23 at 21 10 23" src="https://user-images.githubusercontent.com/1473433/88359878-236e3600-cd29-11ea-9398-8ea1da4953bf.png">

**Comment by xixixao** [comment]
Interesting HN submission with more possiblities in the comments:

https://news.ycombinator.com/item?id=24205416

**Comment by vjeux** [comment]
We're looking for another handwritten font. If you could add suggestions for the fonts listed in this issue that'd be useful. Thanks! #2945

**Comment by lipis** [comment]
Thank you @TimoSta but this is out of scope of Excalidraw, as we don't want to add additional options.
