### ISSUE TITLE
[grouping] groups should have atomic z-index

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#1656]
![](https://user-images.githubusercontent.com/490574/82852062-ba429000-9f3c-11ea-8fa2-2d953c7db2b9.gif)

via https://github.com/excalidraw/excalidraw/pull/1648#issuecomment-633764618

**Comment by vjeux** [comment]
Looks like Keynote groups don't have this issue. Ungrouping them doesn't restore the original zindex either.

**Comment by dwelle** [comment]
Yes, Figma and Affinity doesn't retain original z-index either, so I reckon before we group elements we should simply sort the together in the globalScene array. Easy fix.

**Comment by dwelle** [comment]
Actually, it's not *that* easy a fix. We'll also need to account for z-index ordering within a group (when user edits the group and starts ordering). Maybe other considerations, so will probably leave for after the PR lands.

**Comment by vjeux** [comment]
If we never get to fix it, I wouldn't be sad btw.

**Comment by dwelle** [comment]
> If we never get to fix it, I wouldn't be sad btw.

Why. I can't think of a use case where current behavior makes sense, plut it's best to align with virtually everyone out there.

**Comment by petehunt** [comment]
it's an easy fix, i have a diff for it already
