### ISSUE TITLE
Straight lines drawn by Free draw tool are turning in line elements

### ISSUE THREAD

**Issue by nanot1m** [excalidraw/excalidraw#1663]
If you draw a straight line using the "Free draw" tool simple line element will be creating. 

![Screen Recording 2020-05-27 at 15 56 10](https://user-images.githubusercontent.com/9278185/83029679-3919f480-a033-11ea-82e8-50d540dbaf97.gif)

It's a little bit confusing because I'm able to rotate free drawn elements but not lines

**Comment by dwelle** [comment]
Took a while to repro with mouse. What's like going on: the simplification algorithm makes the line end up with 2 points, which many helpers then presume to be a line instead of a free-draw.

**Comment by xixixao** [comment]
What are the differences between simple line and free drawn line? Seems like we could get rid of the specialization of the simple line and let it be resized and rotated like any other shape?

(ah I see #1673 kinda agrees)
