### ISSUE TITLE
"Save As" feature

### ISSUE THREAD

**Issue by sompylasar** [excalidraw/excalidraw#1668]
My use case: I open an existing diagram file and use it as a template to create new ones.

Something changed recently, so when I save, it suggests to overwrite the template file instead of saving a new file with a new name that I made in the "export" dialog.

I understand this is useful when you're coming back to a file that you were editing before, but looks like now after I've opened and modified the template file, there is no way to save as another file, and there is no way to export the excalidraw JSON as file (like I do with PNG / SVG).

**Comment by vjeux** [comment]
@tomayac could you look into this? Thanks!

**Comment by sompylasar** [comment]
In the meantime, the workaround is to duplicate the template file via Finder / Explorer, and then save the changes (they will be saved as the original template name, which I can rename, then restore the template file from the duplicate).

**Comment by tomayac** [comment]
The proper solution for this would be to introduce Excalidraw template files, just like Word has `.docx` for documents and `.dotx` for templates. In the current state, I would say this is working as intended. 

Right now, when you open a file using the Native File System API, we [cache the file handle](https://github.com/excalidraw/excalidraw/blob/c427aa3cce801bef4dd9107e1044d3a4f61a201e/src/data/blob.ts#L24) and [use it again](https://github.com/excalidraw/excalidraw/blob/63c10743fbbe075cc3171c2b9caaae6e6be8c3b7/src/data/json.ts#L41) upon saving.

**Comment by sompylasar** [comment]
But what if I want to use any previously drawn diagram as a template for the next one? "Save as" exists in most apps that can edit and save something.

**Comment by sompylasar** [comment]
I think an easy way would be to support "Save as" with shift+click, cmd/ctrl+click, or option/alt+click on the "Save" button. Not sure about touch devices, maybe long tap.

**Comment by tomayac** [comment]
Why not simply have two buttons, as almost all applications do? We can still support the hotkeys of course. So my plan of action suggestion to tackle this issue would be:

- Establish an Excalidraw template format.
- Add a separate "save as" apart from the "save" button. 
  - The "save as" includes an option to save as an Excalidraw template file apart from just saving as a regular Excalidraw under a different name.

Maybe vote with the thumbs up/down feature, or comment if you disagree or have different thoughts. Thanks!

**Comment by sompylasar** [comment]
> Why not simply have two buttons, as almost all applications do?

Just saving some screen space, tradeoff for discoverability. Can be two buttons if there's room for both of them.

**Comment by sompylasar** [comment]
> Establish an Excalidraw template format.

I think this is unnecessary as long as we have "Save as" and "Open (from file)".

Also there are and will be more third-party tools that rely on excalidraw format (like excalidraw-animate), for now via copy-pasted code, but hopefully in the future it'll be some `@excalidraw/core` package that includes functions to parse/serialize, decrypt/encrypt. CC @dai-shi 

Having a second format would make similar integrations harder to maintain.

**Comment by tomayac** [comment]
> [A]s long as we have "Save as" and "Open (from file)".

Just to make sure I get you right, you are in favor of keeping the current "Save" (that just over-saves if a file is open)?

**Comment by sompylasar** [comment]
Yes, "Save" isn't going anywhere, but it's not required to fulfill the template use case, "Save as" is more powerful, "Save" is more of a convenience (you can always "Save as" choosing the same existing file and confirming overwrite).

**Comment by tomayac** [comment]
Cool, so the final plan of action would simply be to add a "Save as" button, but not establish a template file format. Sounds good to me. [KISS](https://en.wikipedia.org/wiki/KISS_principle) :-)

**Comment by dwelle** [comment]
Repost from https://github.com/excalidraw/excalidraw/issues/1691#issuecomment-636780492:

Can we make `Save` button save the file without dialog prompt (using the new FS API)?

**Comment by tomayac** [comment]
> Can we make Save button save the file without dialog prompt (using the new FS API)?

Yes :-D

**Comment by dwelle** [comment]
Cool :). I couldn't find any docs on it on MDN. I assume the download folder would be the default one set in the browser settings.
