### ISSUE TITLE
Rewrite excalidraw with state machines

### ISSUE THREAD

**Issue by brucou** [excalidraw/excalidraw#1672]
@vjeux quick shoutout to ask you if you mind if I reimplement excalidraw (hopefully the exact same thing, but that will depend on how much time I can allocate to that effort) with my [state machine library](https://brucou.github.io/documentation/v1/tutorials/model-with-machines.html). I have no commercial intent whatsoever, or even thinking about reusing the brand, I can always call this <another famous sword name>draw. It does not really matter it is just for demonstration purposes. 

There are a number of points that I want to make by doing this, that I can make without, but I believe an example with a real application is always best. I did the RealWorld application and currently refactoring it, but that's ugly as f,,,. so I believe excalidraw will make the point better.

So let me know if you see any impediment (I know it is MIT-licensed but still, I thought I should ask before) else I would start having a look at the code in a couple of weeks.

PS: If you know about another famous sword name, let me know too
PPS: Irrelevant, mostly inconsequential, but cocorico, baguette sous le bras et béret sur la tête, I am also French

**Comment by vjeux** [comment]
Be my guest, feel free to play with the code as much as you want and see where it would be useful or the abstraction break down.

That said, right now excalidraw architecture is working well and we have no intention of doing any big refactors. So we're very unlikely going to use any of the work you'll be doing or even looking at PRs for this.

Bon courage :)

**Comment by brucou** [comment]
@vjeux sure, that wasn't the goal in any case. Great, thanks!
