### ISSUE TITLE
Support rotating 2-point lines

### ISSUE THREAD

**Issue by pjebs** [excalidraw/excalidraw#1673]
I copied an item and pasted it but I want to rotate it.

**Comment by pjebs** [comment]
I want to rotate a line that I drew. It doesn't seem to let you but you can rotate rectangles.

**Comment by dwelle** [comment]
For 2-point lines, you'll have to rotate by one of the corner handles for now.

**Comment by pjebs** [comment]
How do I doing that?

**Comment by dwelle** [comment]
I said rotate, but it's not really rotation. I agree it's suboptimal because it changes the shape.

![excal_2point-line-rotate](https://user-images.githubusercontent.com/5153846/83244895-4accda80-a1a0-11ea-932f-458884315daa.gif)

**Comment by dai-shi** [comment]
Related: #1663

**Comment by dai-shi** [comment]
We could technically implement this like group rotation UI.

![excal79](https://user-images.githubusercontent.com/490574/88983589-666e7180-d306-11ea-90ef-cdbdae3adddc.gif)

https://excalidraw.com/#json=5414572366233600,xDketRyOW8k9x177Nk7_JA
