### ISSUE TITLE
Faulty z-index in the toolbar section

### ISSUE THREAD

**Issue by saranshbarua** [excalidraw/excalidraw#1675]
There's a slight issue with the canvas background colors toolbar. The # sign from stroke overlays the options. Not a major issue but if you want I can shoot a PR.

**Screenshot**
<img width="252" alt="Screenshot 2020-05-29 at 4 32 17 PM" src="https://user-images.githubusercontent.com/23500643/83253553-c8a5db80-a1ca-11ea-8184-fe17a6dd1ae1.png">

**Comment by dwelle** [comment]
Go for it, though I can't repro on Chrome or FF. Is that Safari?

**Comment by ad1992** [comment]
Works fine in safari, Its firefox.

**Comment by dwelle** [comment]
Can't repro on FF 76 on Win:

![image](https://user-images.githubusercontent.com/5153846/83267562-af9a2c00-a1c4-11ea-906e-17664b35c360.png)

**Comment by ad1992** [comment]
Ahh I am in firefox 76.0.1  mac and it's reproducible

**Comment by saranshbarua** [comment]
Yes, I'm using latest firefox on mac. I'll send a patch soon

**Comment by saranshbarua** [comment]
Closing this since it is fixed in #1711
