### ISSUE TITLE
Excalidraw always switches back to "Hand-drawn" font from other fonts

### ISSUE THREAD

**Issue by pranavpr** [excalidraw/excalidraw#1678]
Earlier after selecting a font, the font used to stay same across text boxes or session till a new font was chosen. But now the font always switches back to "Hand-drawn". This is a change from previous behaviour. Also if you select a font and then start a new text box, your choice is not honoured and it switches back to "Hand-drawn".

Can we please revert back to old behaviour?

**Comment by pranavpr** [comment]
I did some investigation and found that this issue started happening after #1635.

**Comment by vjeux** [comment]
cc @dwelle

**Comment by dwelle** [comment]
@pranavpr fixed, sorry for the inconvenience :).

**Comment by pranavpr** [comment]
@dwelle No inconvenience at all. Really appreciate the great work you guys are doing. 👍
