### ISSUE TITLE
Add Watercolor for the background as an option

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw#1689]
https://observablehq.com/@veltman/watercolor by @veltman

Or maybe as the default for the `solid`

<img width="988" alt="Screenshot 2020-05-31 at 5 24 53 PM" src="https://user-images.githubusercontent.com/125676/83354791-b0b58f80-a363-11ea-8c4d-ebeb112ed5a0.png">

--------

### Suggested options

<img width="316" alt="Screenshot 2020-05-31 at 5 25 01 PM" src="https://user-images.githubusercontent.com/125676/83354788-ac897200-a363-11ea-91f3-f242628f8df7.png">

People like it: https://twitter.com/excalidraw/status/1267100853715992576

**Comment by dai-shi** [comment]
Would be nice. Those options are way too flexible. Just up to three preset options work for me. I'm fine with `solid` too, but some would want the current Architect+solid.

**Comment by lipis** [comment]
Forth option would not be a big issue.. but of course we have to be very careful with that..

**Comment by pshihn** [comment]
While we are discussing alternatives to solid fill, using broad fill strokes horizontally or vertically  could be an option. Looks like felt pen filling
<img width="463" alt="Screen Shot 2020-05-31 at 11 43 34 AM" src="https://user-images.githubusercontent.com/833927/83360185-3ae5ff80-a334-11ea-9515-c7b220fc4f5f.png">

Live: https://glitch.com/~broad-stroke-fill

**Comment by dai-shi** [comment]
> Forth option would not be a big issue.. but of course we have to be very careful with that..

Yeah, it'd be ok if it's just one addition. This is hard. How about splitting into "Stroke sloppiness" and "Fill sloppiness"?
