### ISSUE TITLE
Save is not working as expected

### ISSUE THREAD

**Issue by pooran** [excalidraw/excalidraw#1691]
Save takes forever. Earlier flow was simple.

Save flow can be as simple as, just ask a name 'HelloWorld' and save the file as HelloWorld.excalidraw

Asking for folder dialog is overkill. 

Keep It Simple

**Comment by dwelle** [comment]
Hello @pooran. Removing unnecessary friction is something we're definitely interested in.

Related: https://github.com/excalidraw/excalidraw/issues/1668 --- if we add `Save as`, then `Save` could do without a save dialog, I think.

But, I'm not sure if it's possible using the new filesystem API. /cc @tomayac

**Comment by tomayac** [comment]
Let's close this issue and keep track of progress in #1668 instead indeed.
