### ISSUE TITLE
multipoint lines without rounded corners?

### ISSUE THREAD

**Issue by sbng** [excalidraw/excalidraw#1699]
I find the multi-points line are a great feature. I normally use it to create odd shapes object and make it into a closed so I can fill it with different color. However, at time I like the corners of such shapes to be straight. Is this possible? 
![Screenshot_2020-06-02 Excalidraw](https://user-images.githubusercontent.com/7722519/83461984-9fbc6980-a49c-11ea-8147-6d70afd39c6c.png)

**Comment by dwelle** [comment]
Hello, this feature request is already being tracked here: https://github.com/excalidraw/excalidraw/issues/1573
