### ISSUE TITLE
Export SVG dislocates elements

### ISSUE THREAD

**Issue by gunar** [excalidraw/excalidraw#1704]
Hi folks,

I could not find any open issue about this. I'm having problems when exporting SVGs (happened once).

#### Desired output:
![free-email](https://user-images.githubusercontent.com/7684574/83617904-a7097300-a581-11ea-8d71-c717c1465a21.png)

#### Actual output:
![image](https://user-images.githubusercontent.com/7684574/83618150-f18aef80-a581-11ea-87c3-05c1e165265e.png)

#### Link:
https://excalidraw.com/#json=5638882066432000,mXeaLa2IYyLwhtmJM5sJKQ

PS: ❤ Excalidraw.

**Comment by dwelle** [comment]
Looks like the regression was introduced in https://github.com/excalidraw/excalidraw/pull/1687

/cc @lipis  @YounessFkhach

**Comment by dwelle** [comment]
I'll revert the commit for the time being. Let's open the RTL PR again.

**Comment by lipis** [comment]
Thanks @dwelle for the quick fix... We need these tests :D
