### ISSUE TITLE
How to integrate with my own socket.io server instead of "excalidraw-socket"

### ISSUE THREAD

**Issue by vishnuasklua** [excalidraw/excalidraw#1707]
I want to have my own server in middle instead of using excalidraw's for socket connection.

**Comment by vishnuasklua** [comment]
Got the [repo](https://github.com/excalidraw/excalidraw-room). So closed the issue.

**Comment by gigincg** [comment]
@vishnuasklua Were you able to self-host Excalidraw with Collab?
