### ISSUE TITLE
Objects become ungrouped after copy-pasting

### ISSUE THREAD

**Issue by eendeego** [excalidraw/excalidraw#1708]
After pasting a grouped object, the objects will become standalone.

Steps to reproduce:
1) Draw two objects
2) Select and group them
3) Copy
4) Paste
5) Select one of the "just pasted" objects

Expected behavior:
- Group is selected

Actual behavior:
- Individual component is selected

**Comment by vjeux** [comment]
cc @petehunt

**Comment by dwelle** [comment]
Cannot reproduce.

![excal_group_paste](https://user-images.githubusercontent.com/5153846/83736623-341bfd00-a652-11ea-899a-bb15858d97a3.gif)

**Comment by dai-shi** [comment]
I thought I reproduced it, and then no, it's not copy-pasting, but text editing.

![exdraw54](https://user-images.githubusercontent.com/490574/83831524-93e1d900-a722-11ea-881f-d84b7597b68a.gif)

**Comment by dwelle** [comment]
Thanks @dai-shi for the investigation, this PR should fix it https://github.com/excalidraw/excalidraw/pull/1715

**Comment by dai-shi** [comment]
@eendeego Your description seems you have experienced something different. If you are able to reproduce the weird behavior, please reopen the issue preferably with a screencast.

**Comment by eendeego** [comment]
The screencast is very similar to what I was experiencing. I'll recheck.
