### ISSUE TITLE
Is not possible to move around the project using the arrows

### ISSUE THREAD

**Issue by gregorybarros** [excalidraw/excalidraw#1712]
I believe it would be useful to move through the window using the arrows and on click into background dragging the mouse. :+1:

**Comment by dwelle** [comment]
Arrow keys are currently used to move elements around (when selected). While we could make arrows keys for moving around the scene, it might not be immediately obvious what is being moved (scene vs element).

Unclear what you mean by differentiating between "moving through the window" and "on click into background dragging the mouse".

**Comment by gregorybarros** [comment]
I mean, by clicking and holding on an empty space, it would be possible to move the scene to the right or left, without having to look for the scroll bar at the bottom of the window

**Comment by dwelle** [comment]
I see. You can already do so in two ways:

- Hold `Spacebar` and move mouse.
- Click-dragging with middle mouse button (mouse wheel).

We don't want to make click-dragging move the scene, because that would prevent selecting elements.

**Comment by gregorybarros** [comment]
Ahh perfect, that's right
Perhaps, it would be good to describe these two shortcuts together with others, it would make it easier for users :)

Congratulations for the app :+1:

**Comment by dwelle** [comment]
> Perhaps, it would be good to describe these two shortcuts together with others, it would make it easier for users :)

For sure. I thought we had it in our shortcut-dialog helper, but we don't. Will keep this issue open to track i t.

**Comment by dwelle** [comment]
closing as fixed by https://github.com/excalidraw/excalidraw/pull/1784
