### ISSUE TITLE
Feature Request: Visually open saved projects

### ISSUE THREAD

**Issue by xzab** [excalidraw/excalidraw#1718]
Would be neat if there was a way to visually open saved projects.  I can never remember which drawing is which and I have to keep opening multiple until I find it.  Having a thumbnail to see them would be incredibly beneficial.  Have it save in the cloud would be an added benefit (I'd be fine with hooking up my google drive or something for storage too).  Just need that thumbnail to get back to the project I need.

https://drive.google.com/file/d/1At8DfMreBPW3CVp5zyqMsOW6nCkzfFnl/view?usp=sharing

**Comment by vjeux** [comment]
Agreed!

Do you know if Google Drive (or others) have APIs we can use to start saving files and reading them on-demand?

**Comment by vjeux** [comment]
I wonder if there's a way to get mac/windows preview to excalidraw files.

**Comment by lipis** [comment]
> I wonder if there's a way to get mac/windows preview to excalidraw files.

I think this is something for the Desktop app.. https://github.com/excalidraw/excalidraw-desktop/issues/136

**Comment by xzab** [comment]
Looks like it, using OAuth https://developers.google.com/drive

**Comment by xzab** [comment]
> I wonder if there's a way to get mac/windows preview to excalidraw files.

Here's how to do it on mac, but online would be even better
https://developer.apple.com/documentation/quicklookthumbnailing/providing_thumbnails_of_your_custom_file_types

**Comment by lipis** [comment]
This is outdated.. we don't have a list of stored files anymore.
