### ISSUE TITLE
Feature Request: Follow user's view

### ISSUE THREAD

**Issue by oliverbenns** [excalidraw/excalidraw#1721]
Problem: When my teammate is talking about something on a board over a call, I have to continually move the board around to find where their pointer is to understand the context. This breaks the flow of conversation. To get around this, we sometimes screenshare, but then this creates a new problem where I have to keep exiting slack/zoom full screen mode and change applications.

Solution request: Add the ability to follow a user which will have the client's viewport follow the target user's. It should follow the current view location of the user, as well as their zoom level. There may be some intricacies worth discussing to get this working well (what happens when the target user is on a 16:9 monitor talking about something at the horizontal edge when the following user is on 3:4, for example).

**Comment by dwelle** [comment]
>  There may be some intricacies worth discussing to get this working well (what happens when the target user is on a 16:9 monitor talking about something at the horizontal edge when the following user is on 3:4, for example).

Also:
- What about multiple users. Which one to follow?
- Does it mean you won't be able to scroll yourself (when you need to when drawing)?
- What if you don't want that. We'd need a separate UI for that.

**Comment by sg1705** [comment]
This feature is available in Figma and very useful. I'll describe how it works in Figma (apologies if you folks already know that).

1. Presence of users (who's in the diagram) need to be explicitly stated. Kinda like user avatars that show up when a user opens a doc in Google Doc.

2. In Figma, if you double click on an avatar, then you are indicating that you want to follow that user.

3. So, the center of your viewport is the same as the users. It doesn't matter how big my screen is. As long as the center of my viewport is the same as that of the user I am following.

4. You double click on user avatar to unfollow.

It is extremely useful feature.

**Comment by vjeux** [comment]
This is a good idea to show a list of all the connected users. I’ve always wanted to see who is there.

**Comment by oliverbenns** [comment]
Yes I remember using a tool that implemented the feature I described, but can't for the life of me remember what. It could very well may have been Figma.

I think you detached yourself from the user whenever you made some form of interaction like editing the canvas, click to drag viewport etc. You could still move your cursor, mind.

Once a 'detaching action' occurred, you would then need to 'refollow' the user. So when following you are not prevented in doing actions, it's just that those actions simply breaks the following state.

Having some form of list of users seems like a good first chunk of work that could be done. In my mind I thought a list could be in the live-collab menu, but the Gsuite-style avatars in the top right would save on clicks when following/re-following.

**Comment by dwelle** [comment]
Right. Note that since we don't have authentication, the avatars would just be colored icons with initials. And since we don't require users to pick names, lot of the time we couldn't even show any initials.

**Comment by sg1705** [comment]
I think the issue of avatars and initials goes back to first principles.

Is this tool meant for collaborating and discussing as much as it is for
creating. If it is for collaborating then what is the best way to identify
collaborators? Initials? Gravatar? Full name? Profile pic? And if P2P
collab design will support such a system? Identity is pretty crucial to
collab products.

**Comment by lipis** [comment]
The fact that we don't have avatars or initials it's OK.. I think once the list of participants will be visible, people will start editing their names.. For now we can just do colors and it's fine!

**Comment by sg1705** [comment]
I'd love to contribute by building this feature; at least the first part, which is to show user avatars with colored icons.

I looked at the contributing guidelines and saw that only an issue needs to be open.

Any advice on the process of contributing such a feature. Just send pull requests or should I share beforehand how I am planning to implement first?

**Comment by oliverbenns** [comment]
I just started on this work @sg1705 - literally only a few hours before your comment! I was going to get something up over the next couple of days, at least as a draft for us to review (especially design)

**Comment by lipis** [comment]
@sg1705 There are plenty of open issues if you would like to contribute with something else.. That was kind of a bit unusual and unlucky.. it's good that you asked :D

**Comment by sg1705** [comment]
Thanks @lipis . Is there any issue that you think I can pick that would be good for someone just starting out in this project.

**Comment by lipis** [comment]
You can click on the avatars now to go to their cursors!

**Comment by lfrancke** [comment]
I know this is old and closed. I landed here via Google as the current functionality does not really implement "follow" but "jump to" instead. I'm not sure if you'd like to reopen an issue or rather have a new one.
