### ISSUE TITLE
Can't rotate or resize groups with text

### ISSUE THREAD

**Issue by eendeego** [excalidraw/excalidraw#1728]
Repro

* Create multiple objects including text
* Rotate individually works
* Group objects
* Try to rotate

Expected behavior

* Handles for rotation and resize show up and can be used

Actual behavior

* No handles show up at all

![Screen Recording 2020-06-07 at 8 47 17 PM](https://user-images.githubusercontent.com/101878/83991358-61da9d80-a901-11ea-991c-add8b6783425.gif)

**Comment by vjeux** [comment]
Probably going to be fixed by #1726

**Comment by dwelle** [comment]
Resize, yes. Rotation won't be.
