### ISSUE TITLE
Group elements

### ISSUE THREAD

**Issue by jaredpalmer** [excalidraw/excalidraw#173]
As a user, I want to be able to quickly group and ungroup elements so I can move them around more easily. 

Keyboard shortcuts: 
- Group: <kbd>Cmd + G</kbd>
- Ungroup: <kbd>Cmd + Shift + G</kbd>

**Comment by chriskrez** [comment]
Hey! Can I work on this? :smile:

**Comment by vjeux** [comment]
Sure thing!

**Comment by jaredpalmer** [comment]
Related to this, when you implement / choose data structures, keep in back of mind that a layers panel could be super useful in the future.

**Comment by dwelle** [comment]
During the [PR review](https://github.com/excalidraw/excalidraw/pull/181#issuecomment-572554178), I've added:

> Grouping groups should retain the subGroups, so that later when ungrouping the superGroup, we again get the subGroups instead of individual elements (behavior of Figma et al.)

Is that out of scope (too complex) for this app, or do we want to implement that behavior?

**Comment by lipis** [comment]
I think we are done with this one :)

**Comment by tchalvak** [comment]
This is the main google hit for "excalidraw link layers" and "excalidraw group layers", is there documentation for how to do this?

**Comment by dwelle** [comment]
It's implemented exactly as per the original issue description (on top of the UI buttons). Was there anything unclear or hard to do from within the app if it necessitated a google search?

**Comment by fatso83** [comment]
@dwelle It's fine that this keyboard combination works, but how is one supposed to know that without searching and landing here? I was looking through the UI without finding that info myself, before I searched for it.

**Comment by Xiarno** [comment]
A list of groups would be useful.

**Comment by endlessblink** [comment]
Is there a shortcut for grouping layers together / ungrouping them?

**Comment by totheroh** [comment]
> Is there a shortcut for grouping layers together / ungrouping them?

Shortcuts are at the top of this thread.

**Comment by endlessblink** [comment]
They are not working for me. On a Windows PC and tried several combinations based on them.
