### ISSUE TITLE
Feature Request: Mindmap

### ISSUE THREAD

**Issue by pA1nD** [excalidraw/excalidraw#1737]
Problem
---
When I'm writing down my ideas in excalidraw as mindmap, each thought takes me quite a while to write: Write text, add circle around, make an arrow. This breaks my flow and I end up doing it on paper because I constantly loose my track of thoughts.

Solution request
---
Have a "MindMap" mode, where from every node I can add a next node that is connected via arrow and has a text and a circle.
It would be awesome to have the circle grow (or the text shrink) as I'm writing, so I don't have to interrupt the flow to adjust the size.

This would be a very valuable feature in my flow as I come constantly accross situations where I want to write down a bunch of thoughts in something like a MindMap.

The same functionality would also allow to do create flow-diagrams much easier. This would maybe require to change forms (e.g. a circle to a rectangle)

**Comment by lipis** [comment]
We are supporting attached icons now, but the rest of the features seems a bit out of the scope for Excalidraw..

**Comment by sojusnik** [comment]
Maybe this could be realized through the coming [plugin API](https://github.com/excalidraw/excalidraw/issues/2189).
The behaviour of [coggle](https://coggle.it/) could serve as an inspiration, especially its [keyboard shortcuts](https://coggle.help/article/24-keyboard-shortcuts).
