### ISSUE TITLE
Group / ungroup should not always be present in the context menu

### ISSUE THREAD

**Issue by petehunt** [excalidraw/excalidraw#1738]
* Group should only show up when multiple elements are selected
* Ungroup should only show up when a group is selected

**Comment by ReneCode** [comment]
Change the Action interface:  
`
contextItemLabel: string | (() => string)
`
That offers the opertunity to set a dependend contextItemLabel. That function is used in `actionGroup` and `actionUngroup`. 

The ActionManger.getContextMenuItems method will use 
`if (typeof action.contextItemLabel == "function") ....` 
to get that contextItemLabel on demand.

I'll give it a try.

**Comment by ReneCode** [comment]
it's fixed with PR [#1890](https://github.com/excalidraw/excalidraw/pull/1890)
