### ISSUE TITLE
self host instance: How to check version or release?

### ISSUE THREAD

**Issue by sbng** [excalidraw/excalidraw#1751]
I am running a self host instance of excalidraw. I do regular pull to make the docker image and subsequently deploy it in my cloud. Is there a knob that I verify or check the version of excalidraw that I am currently deploying?

**Comment by oliverbenns** [comment]
You can get the version from `build/version.json`. However this seems to be just be time-based on the build and not semver.
See: https://github.com/excalidraw/excalidraw/blob/master/scripts/build-version.js#L30

**Comment by dwelle** [comment]
tangentially related: https://github.com/excalidraw/excalidraw/issues/1665

**Comment by kbariotis** [comment]
@sbng we include a tag with GIT SHA of the deployed commit on the Docker image, unfortunately that's the only thing we have now.

**Comment by kbariotis** [comment]
Will close that due to inactivity. @sbng let us know of your thoughts.
