### ISSUE TITLE
Add Norwegian Nynorsk (nn-NO) translation

### ISSUE THREAD

**Issue by kvasimon** [excalidraw/excalidraw#1754]
Hi! I finished adding it through the JSON files before reading the readme (🤦), so I'm now opening an issue instead:

I would like to translate Excalidraw into Norwegian Nynorsk (`nn-NO`) 😄

In addition, the current locale code for Norwegian Bokmål is incorrect. It should be `nb-NO`, not `no-NO` which it currently is.

**Comment by kvasimon** [comment]
So to add, the languages should be called "Norsk bokmål" and "Norsk nynorsk", just like this.

**Comment by dwelle** [comment]
Without digging deep, it seems that Nynorsk accounts roughly for 12% of 5.32 million Norwegian speakers. It's also not clear whether all of those 12% can also fluently speak Bokmål. If so, do you feel it necessary to add the Nynorsk dialect?

I've looked at our analytics, and while there are 30 total `nb-NO`, we've had zero visits from `nn-NO`.

**Comment by dwelle** [comment]
As  for the `no-NO` code. Not sure where we got that from. It seems i18next [uses the correct code](https://github.com/i18next/i18next/issues/1321#issuecomment-529827782). @lipis can we change that? How does it tie into Crowdin?

**Comment by kvasimon** [comment]
@dwelle Nynorsk is a language, just like Bokmål, not a dialect :)

Norwegians also have virtually no problems with Danish or Swedish (or English for that matter), which could easily be an argument for not having Norwegian at all – but I think we should.

Regarding the analytics, many computers also come with Bokmål preinstalled even though users prefer Nynorsk. And I've visited using `nn-NO`, so there should at least be one. Otherwise perhaps the detection is a bit off (navigator.language can be tricky).

Anyway, as a Nynorsk user I do feel it necessary to add my language, and I'm more than happy to help with the translation :)

**Comment by kvasimon** [comment]
I've got the necessary changes running in a fork that I'd be happy to open a PR for too :)

**Comment by kvasimon** [comment]
Any updates to this? Not in a hurry, just making sure.

**Comment by lipis** [comment]
These are the options in Crowdin:

<img width="172" alt="Screenshot 2020-06-19 at 1 45 15 AM" src="https://user-images.githubusercontent.com/125676/85079063-9a665b00-b1ce-11ea-8b3f-fbab2e76c9f7.png">

We could be more specific, but adding both in a long run it will stay outdated if we don't have much traffic from those. We already have to think about removing some languages if they are below some kind of threshold.

**Comment by lipis** [comment]
We are more specific in Crowdin now as well.. https://github.com/excalidraw/excalidraw/pull/1776

**Comment by lipis** [comment]
<img width="793" alt="Screenshot 2020-06-19 at 1 59 35 AM" src="https://user-images.githubusercontent.com/125676/85079903-90455c00-b1d0-11ea-87ac-cad85fb434d1.png">

**Comment by kvasimon** [comment]
Okay, not sure I'm getting the point with the other languages as I'm literally offering to translate to it (and bokmål too for that matter). This is a very small project as far as translation goes, so it doesn't take very long.

It's good that you're at least calling it "Norwegian Bokmål" now (which is the _only_ correct name, by the way), but I'm a little disappointed that you won't add support for a minority language when someone offers to add it. 

It's _the_ exact reason why languages like Nynorsk struggle and now Excalidraw is contributing to that, which seems like an unnecessarily odd position to take.

But oh well, it's only ~700k people ¯\_(ツ)_/¯

**Comment by vjeux** [comment]
Hey, thanks for reaching out. We're talking through what's the best policy regarding languages as a result of this and other cases we've had in the past. Thanks for be willing to help out and we'll get back to you.

**Comment by kjellkvinge** [comment]
In the language list, we get "bokmål" - it should be "Norwegian Bokmål".

As a "Norwegian bokmål" user, I fully support @kvasimon in adding Nynorsk and other languages as long as there is people willing to do the translate work. Is there any technical reasons not to?

![Screenshot from 2020-06-29 13-16-30](https://user-images.githubusercontent.com/3092520/85998282-e2755100-ba0a-11ea-902e-b18335f72468.png)

**Comment by dwelle** [comment]
Until recently, we've been bundling all languages with the main app so we didn't want to add just anything as it would keep increasing the size users need to download. That's no longer the case.

There's also an [open PR](https://github.com/excalidraw/excalidraw/pull/1826) that ensures we don't display incomplete translations in the language picker.

After that is done, we'll be much more open towards new translations, mainly depending on whether Crowdin supports a given language.

Stay tuned.

**Comment by dwelle** [comment]
In fact, you don't need to wait on it, so we've added Nynorsk already. You can translate at: https://crowdin.com/translate/excalidraw/10/en-nnno

Thanks.

**Comment by kvasimon** [comment]
Very happy to see this happening. Thanks guys. Translation in place already 💪 
<img width="367" alt="image" src="https://user-images.githubusercontent.com/17279882/86064979-cb684a80-ba6e-11ea-899c-11023e121af3.png">

**Comment by kjellkvinge** [comment]
Nynorsk - the language of the vikings :smiley: nice work

**Comment by lipis** [comment]
Could you add it to the dropdown? https://github.com/excalidraw/excalidraw/blob/master/src/i18n.ts

**Comment by kvasimon** [comment]
Absolutely. PR open now :) https://github.com/excalidraw/excalidraw/pull/1843

**Comment by kvasimon** [comment]
Thanks for reconsidering this, I'm certain it makes Excalidraw even better for a lot of users! :)
