### ISSUE TITLE
Is getexcalidraw/excalidraw on DockerHub Your Official Builds?

### ISSUE THREAD

**Issue by zicklag** [excalidraw/excalidraw#1764]
Hey there, I found `getexcalidraw/excalidraw` on DockerHub and I was curious whether those were your guys's official builds or whether it was just somebody random hosting them. The build's aren't automated on DockerHub so I can't verify which repo they came from and I wanted to make sure I knew who I was pulling the containers from.

**Comment by dwelle** [comment]
Apparently yes: https://github.com/excalidraw/excalidraw/blob/master/.github/workflows/publish-docker.yml#L18

But I haven't worked with DockerHub, so best wait for @kbariotis to confirm

**Comment by dwelle** [comment]
@kbariotis: if we renamed the docker org to `getexcalidraw`, we should update readme to reflect that. (I haven't followed the PRs, so forgive me if it was already discussed.)

**Comment by kbariotis** [comment]
Oh I was not aware that we had that in the README, I thought we haven't announced it yet. 

@zicklag we are stuck with Docker registry as we are trying to get the `excalidraw` organization name back. I wouldn't use that image yet in case we rename it. We should be ready very shortly though and I will let you know on this issue. :)

@dwelle I will remove that from the readme.

**Comment by zicklag** [comment]
Thanks for the prompt response! :)

I'll stay tuned. :+1:

**Comment by daddydanny73** [comment]
Hi Krysta kay bitch thank u for everything Jenny is gonna be my wife in 3 wks

**Comment by kbariotis** [comment]
Official Docker image @zicklag https://hub.docker.com/r/excalidraw/excalidraw. Try it out and let us know of any feedback. :)

**Comment by zicklag** [comment]
Awesome thanks!
