### ISSUE TITLE
Suggestion - e2e encryption icon

### ISSUE THREAD

**Issue by jose-donato** [excalidraw/excalidraw#1765]
Use some icon more illustrative of encryption. I feel like the one use right now does not suggest "encryption".

Codesandbox link: https://codesandbox.io/s/excalidraw-encrypted-icon-ev87e
Before:
![image](https://user-images.githubusercontent.com/43375532/84674437-d1b0df80-af22-11ea-9b48-4a930bc5d3e5.png)

After (only a suggestion):
![image](https://user-images.githubusercontent.com/43375532/84674761-4a17a080-af23-11ea-987d-34a9e6866035.png)

**Comment by lipis** [comment]
We'll stick to what we have. Thank you!
