### ISSUE TITLE
Prevent connection to google / amazon

### ISSUE THREAD

**Issue by tim-krieger** [excalidraw/excalidraw#1768]
We have installed excalidraw on our server via docker. Nethertheless I can see that a connection to google (googletagmanager) and amazon (amazonaws.com) is established. Is there a possibility to prevent this behaviour for privacy reasons?

**Comment by dwelle** [comment]
Indeed I don't think we should bundle our analytics in the docker image.

As for the amazon thing, that's a new thing for me. I checked the codebase, and lo and behold, we're pulling an icon image from amazon :man_facepalming:

https://github.com/excalidraw/excalidraw/blob/60973f6dc5a3d9c9090fb493a126223e6e60d2c0/src/css/styles.scss#L371

**Comment by kbariotis** [comment]
Definitely, it's an absolutely reasonable request. I will see if I can remove the script completely when built inside the Docker image and moving forward we will assume that the Docker image will only be used for self-hosting, since `excalidraw.com` is deployed on Now.

**Comment by kbariotis** [comment]
Thank you @tim-krieger ! We've removed both Google analytics and Sentry from our Docker container. AWS asset is left now.

**Comment by tim-krieger** [comment]
Thank you!
