### ISSUE TITLE
History updating race conditions

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#1773]
1. Right now, if we resume recording via `history.resumeRecording()` via an update scheduled from `componentDidUpdate` (or an update that is scheduled for next event loop frame), the previous update will reset that flag (and if that update wasn't meant to be persisted to history, it will be instead of the intended one).

2. Also, due to update batching, when we schedule two updates --- one that's supposed to be persisted to history, and one that's not, we will end up persisting both.

It would be great if we could associate `commitToHistory` to a specific update. We could add `commitToHistory` to `appState`. That would solve (1), but not (2). But I'm not sure that (2) can ever be solved without completely changing how we make updates.

I've already hit (1) [in practice](https://github.com/excalidraw/excalidraw/blob/f0463fadc34df747c3119a05ad7fb498e96f3d7c/src/components/App.tsx#L505-L513), and (2) [in theory](https://github.com/excalidraw/excalidraw/issues/1742#issuecomment-644718324).

**Comment by Mrazator** [comment]
Such concurrency issues were addressed as part of #7348 and specifically later on with #7898.

Additional improvements, such as getting rid of scheduling recordings are going to be addressed as part of #7921.
