### ISSUE TITLE
Error message if wrong url

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#1786]
Two different people told me that they were confused because the room they created didn't work. It turns out they used the second part of the url needs to be of exact 22 length or the crypto library throws.

Would be nice to have a visible error message.

**Comment by ahasanen** [comment]
Thank you. Yes, better error message would help. And maybe also clearly verbally stating length of characters required in the how to create page.

**Comment by mishraa-soumya** [comment]
hi @lipis 
I want to contribute and take this Issue as my first contribution towards excalidraw. Can you please assign it to me?

**Comment by arieldamian** [comment]
Is this still open? I've tried to open a random URL and I got a Window message like this:
![image](https://user-images.githubusercontent.com/20516757/118730986-d9ea5c80-b80e-11eb-93d5-b6395e88808f.png)

If you are expecting some sort of different experience, which one would it be?

**Comment by AlexisBallo2** [comment]
I think this can be closed. 
<img width="450" alt="image" src="https://user-images.githubusercontent.com/41343138/188761804-56a4b3f0-f5c2-45fa-8603-6119870620a1.png">
