### ISSUE TITLE
Add color palette in stroke and background color

### ISSUE THREAD

**Issue by jaybhoyar** [excalidraw/excalidraw#1791]

**Comment by dwelle** [comment]
Can you elaborate what you mean by color palette?

**Comment by jaybhoyar** [comment]
A simple color picker when choosing a color for stroke and background, that will help user to get the specific color he wanted. 
Something similar to this =>
<img width="701" alt="Screenshot 2020-06-21 at 9 06 16 AM" src="https://user-images.githubusercontent.com/41126433/85216128-b3256b00-b39e-11ea-9c83-4e5d5e48009b.png">

**Comment by dwelle** [comment]
Oh, I see. That request is already being tracker here: https://github.com/excalidraw/excalidraw/issues/1517
