### ISSUE TITLE
Leading tab messes up text computation

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#1792]
Whitespace is removed from canvas rendering when using leading tabs.

![image](https://user-images.githubusercontent.com/197597/85217963-b131bc80-b34a-11ea-9791-2006c77ea2df.png)

![image](https://user-images.githubusercontent.com/197597/85217967-b4c54380-b34a-11ea-9e9a-7964e14e988c.png)

https://excalidraw.com/#json=5692215863017472,tST-jtHF5qJis2ao5AnACA

**Comment by dwelle** [comment]
AFAIK it's because canvas collapses tabs into single space. We should normalize tabs into spaces when pasted/inserted into the textarea.
