### ISSUE TITLE
Some languages were not included

### ISSUE THREAD

**Issue by erfanium** [excalidraw/excalidraw#1798]
For example: There is a `fa-IR.json` in locals folder, but I can't see Persian lang in production dropdown language selector.

**Comment by j-f1** [comment]
The file that stores which translations are visible is at https://github.com/excalidraw/excalidraw/blob/master/src/i18n.ts. Feel free to open a PR to add Farsi as an available language as long as it has been largely translated!

**Comment by kbariotis** [comment]
Thank you @erfanium. We currently only make languages visible on the app that is more than 85% translated to avoid a half-baked experience to users. 

I will close this and as @j-f1 said, please feel free to contribute a translation. :)
