### ISSUE TITLE
Edit colors of selected element

### ISSUE THREAD

**Issue by voluntadpear** [excalidraw/excalidraw#180]
When the user changes the stroke or shape background color and they have an element selected, they could expect to modify the color of that element instead of having to delete it and draw it again.

![changing colors doesn't affect currently selected element](https://user-images.githubusercontent.com/10501948/71787829-05462000-2ffb-11ea-8bc3-0d67ae25b61e.png)
*I select my element and then change the fill and stroke colors. The change doesn't affect the currently selected element*

![it does affect one a create afterward](https://user-images.githubusercontent.com/10501948/71787832-0d05c480-2ffb-11ea-9971-cb9778749ae9.png)
*The change is applied in the next shape I create*

I can work on implementing that feature if we think it'd be nice to have.

**Comment by Fausto95** [comment]
@paulomenezes is working on this here https://github.com/excalidraw/excalidraw/pull/179

**Comment by voluntadpear** [comment]
And it got merged 🎉 I'm closing this one. Thank you!
