### ISSUE TITLE
Cutting a text (CMD + x) doesn't work on same line consecutively.

### ISSUE THREAD

**Issue by eggei** [excalidraw/excalidraw#1809]
Thanks for this great tool. I love using it!

I discovered this two bugs:
- when I want to cut the same line of text consecutively
- when I do undo after that

Steps to reproduce:
**First Bug**
1. Open a new excalidraw plain
2. Create a text element
3. Write 2 lines of text
4. Select first line and cut it (cmd+x)
5. Paste it (cmd+v) under the remaining line (former 2nd line)
6. Then select the newly pasted line (current 2nd line/ the same text cutted on step 4) - **You will see it doesn't cut it**
8. Try to paste the clipboard some where - **it won't paste anything**

**Second Bug**
1. Do the same steps from above until the **step 5**
2. Hit "CMD + z" to undo. - **See it won't undo correctly**
Things get weird with undo from this point on. If you try some more copy-paste and undo, undo doesn't act right.

**Comment by dwelle** [comment]
Hello. It seems both bugs will be fixed as a side-effect of https://github.com/excalidraw/excalidraw/pull/1783.

You can try preview here, and let me know if you can still reproduce either bug: https://excalidraw-git-fixtextaligning.excalidraw.vercel.app/

**Comment by eggei** [comment]
Yes, you are right. They are both fixed!
