### ISSUE TITLE
don't export grid to PNG

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#1811]
Although we may allow to opt-in if there's demand for this. It may have applications.

![xxx](https://user-images.githubusercontent.com/5153846/85425559-9beea500-b579-11ea-9c0d-599ead91b93d.png)

**Comment by y9san9** [comment]
Is there a way to actually draw it? 😅  I want to grid to be exported

**Comment by dwelle** [comment]
Right now you'd have to take a screenshot manually :)

**Comment by y9san9** [comment]
Okay, thanks, can you please add it to TODOs?)
