### ISSUE TITLE
moving grouped elements jumps

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#1816]
steps:

1. create 2 elements and group them
2. try to move them

![excal_group_jump_bug](https://user-images.githubusercontent.com/5153846/85526535-6219af00-b60a-11ea-9d6b-2e393e24ef48.gif)

if (2) doesn't result in jump, try to drill down the the group first by double-click, then click away and try (2) again.

**Comment by dai-shi** [comment]
This looks like a behavior I had while developing #1788 and fixed for ungrouped elements. 🤔

**Comment by dwelle** [comment]
@dai-shi yes, it seems introduced in the grid PR.
