### ISSUE TITLE
text resizing results in incorrect bounding box/position

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#1819]
steps

1. resize like crazy
2. after a while, the text bounding box doesn't align with the rendered text

![excal_text_resize_bug](https://user-images.githubusercontent.com/5153846/85572125-04e72300-b635-11ea-99bb-3b46184e8de3.gif)

**Comment by dai-shi** [comment]
Can't repro on my end. But, I almost know where this issue would come from.
`measureFontSizeFromWH` in resizeElements.ts is really hacky.
I added "third measurement" in #1788 Does it cause the issue? Or even before?

This is "help wanted" for me. What we need to do for smooth resizing is, determine font size that best fits in the bounding box (not vice versa). We keep the aspect ratio while resizing, but the font doesn't necessarily keep the aspect ratio, so we may have some extra space (which should be small and not noticeable, which is not true in extreme resizing.)

That font dancing behavior in the gif is probably another issue we'd like to solve. I guess it's related with baseline.

Uh, I think I can repro to some extent, not that extreme. Maybe it's the same issue.

**Comment by dwelle** [comment]
Sometimes it's not reproducible even for me. Anyway, I checked and it's related only to `height`, not `baseline` (at least not in any major way) which was my first thought, too.

**Comment by dai-shi** [comment]
I'll draft a PR, please try with it.

**Comment by dai-shi** [comment]
Is your gif with zoom=100%?
I can't resize the text that small...

**Comment by dwelle** [comment]
yes
