### ISSUE TITLE
Export to SVG? 

### ISSUE THREAD

**Issue by msurguy** [excalidraw/excalidraw#182]
Would there be an export to SVG option?

**Comment by vjeux** [comment]
It wouldn't be too much work to do. But I'm curious, what's your use case?

**Comment by hejcz** [comment]
I'd love this feature as well. If you want to zoom part of canvas it gets blurry as it is raster graphic. SVG can be zoomed in and out without quality issues. If you want to create some bigger diagram e.g. department architecture it's must have :)

**Comment by msurguy** [comment]
Ditto ^. Plus, I'd love to experiment with drawing these diagrams with plotters like AxiDraw which accept vector files rather than raster. 

Also, it could be a way to implement state info for export / import if you embed some data in the SVG that can be picked up by the tool and recreate the diagram without any additional JSON files.

**Comment by GrimTheReaper** [comment]
A nice usecase for SVG that I tend to use, is being able to import it into other applications that have to scale it. Specifically for me that I've used in the last 24 hours, EagleCad, KiCad, and Fusion360.

**Comment by gillchristian** [comment]
Anybody working on this already? I might give it a shot otherwise on the weekend.

**Comment by vjeux** [comment]
Go for it

**Comment by gillchristian** [comment]
I did not have time during the weekend. If somebody else wants to take it feel free. Sorry 😅
