### ISSUE TITLE
Add Group / Ungroup icons to the Actions list

### ISSUE THREAD

**Issue by ashwinb** [excalidraw/excalidraw#1827]
@vjeux had to let me know that these are available via shortcuts but there's no UI for it. It would be good to add it. Seems like an important primitive.

**Comment by bduffany** [comment]
@ashwinb are you already working on it? If not, I have some extra time and can contribute

**Comment by ashwinb** [comment]
No I am not working on it. Thanks for taking it on!

On Jun 29, 2020, at 12:45 PM, Brandon Duffany <notifications@github.com<mailto:notifications@github.com>> wrote:



@ashwinb<https://github.com/ashwinb> are you already working on it? If not, I have some extra time and can contribute

**Comment by ReneCode** [comment]
The context-items for group/group are dependent of the current selection. I think the visibility of the action-icons should also be dependent.

**Comment by shikaan** [comment]
Did anything happen with this? I would like to contribute to the project and this feels like a good place to start

**Comment by lipis** [comment]
@shikaan go for it

**Comment by ReneCode** [comment]
@shikaan are you still working on that issue? may be I can help?

**Comment by shikaan** [comment]
Hadn't have time yet, it's going to happen likely next week as things are now. If it needs to go out I can free it for someone else to pick it up :)

**Comment by ReneCode** [comment]
I'll give it a try.

**Comment by ReneCode** [comment]
fixed with [PR #1956](https://github.com/excalidraw/excalidraw/pull/1956)
