### ISSUE TITLE
Poor performance using Dots fill pattern

### ISSUE THREAD

**Issue by whitfier** [excalidraw/excalidraw#185]
Drawing any large shape then selecting the Dots fill pattern causes the page to become unresponsive - even to the point where Chrome suggests I kill the tab.

![dots](https://user-images.githubusercontent.com/6414663/71788321-ff8a1380-2fd5-11ea-87ad-f5d7ca023c2f.PNG)

The Dashed and Zigzag-line similarly have poor performance, just to a lesser extent.

**Comment by vjeux** [comment]
cc @phsihn

**Comment by paulomenezes** [comment]
Maybe remove this pattern? I don't know if we can do something about this.

**Comment by vjeux** [comment]
Yeah, let’s remove them for now

**Comment by whitfier** [comment]
I'd be happy to make that change. While I'm at it, should there also be a "None" option that removes the fill?

**Comment by vjeux** [comment]
Having a none would be very useful indeed

**Comment by paulomenezes** [comment]
I don't know if there is a "None" option

**Comment by vjeux** [comment]
Please keep this in mind if you implement the none option: https://github.com/excalidraw/excalidraw/issues/104 (note: I believe that "none" should the default)

**Comment by vjeux** [comment]
I removed everything but solid, hachure, cross-hatch for now. We should keep this in mind if we want to add it back.
