### ISSUE TITLE
Question: how to select multiple elements 

### ISSUE THREAD

**Issue by OrenMe** [excalidraw/excalidraw#1851]
Sorry if this is possible and I missed it - but can I select multiple unrelated items?
Select with click+cmd/ctrl on several items and then be able to group them or move them together?

For now I can only drag-select and sometimes I want to select elements in an already element dense area so I can only select all elements there and not the ones I want

**Comment by dwelle** [comment]
You can `shift+click`. We should probably add it to the shortcut dialog.

**Comment by OrenMe** [comment]
Thanks @dwelle - not coming from UI/UX background too much.
Should have looked in the code I guess :-)
Thanks for the quick reply!

**Comment by lipis** [comment]
I think we can close it now :) @OrenMe let us know if there is still something unclear.

**Comment by dwelle** [comment]
> Should have looked in the code I guess :-)

If users need to read codebase to figure out how basics work, it means we've failed, not you :).

**Comment by johnnybaloney** [comment]
Along the same lines it would be nice to expand selection and add multiple objects with drag-select while `shift` is pressed as opposed to adding them one by one.
