### ISSUE TITLE
Opening a link overwrites existing state without warning

### ISSUE THREAD

**Issue by TobyEalden** [excalidraw/excalidraw#1861]
I'd spent about an hour on an architecture diagram when a friend sent a link to an excalidraw he'd done.

I clicked on the link and it opened in my browser, immediately overwriting my work of genius without any prompt or warning.

**Comment by dwelle** [comment]
Right, this is very unfortunate and we need to do something about it, at the very least prompt as you suggest.

Sorry for the work you lost!

**Comment by RichyRich** [comment]
In the interests of helping to debug, I sent this link: https://excalidraw.com/#room=715025950e33524fe255,HGv1FLWmW-snx59MSuuVcA 
It is a supposed to be a picture of Boris Johnson waving a flag.  Sorry for your loss Toby.

**Comment by dwelle** [comment]
@richkeenan thanks :). Fix already underway  https://github.com/excalidraw/excalidraw/pull/1862

**Comment by dai-shi** [comment]
So, it's a room link...

**Comment by richkeenan** [comment]
I think you meant to tag @RichyRich 👍

**Comment by dwelle** [comment]
Oops. Sorry :sweat_smile:
