### ISSUE TITLE
readonly mode in live collaboration rooms

### ISSUE THREAD

**Issue by NMinhNguyen** [excalidraw/excalidraw#1866]
Have you considered the ability to (temporarily) lock a live collaboration room to prevent edits? I'd imagine such a feature would be useful in workshops where there is a main person and a classroom. Not sure how exactly to implement in a P2P world though, but thought it's worth asking. I've found a related thread  https://github.com/excalidraw/excalidraw/issues/1071, so happy for this one to be closed and discussion to be moved there if you prefer.

**Comment by dwelle** [comment]
Was mentioned several times, but can't find a tracking issue yet.

**Comment by dwelle** [comment]
Writing down some implementation ideas we've discussed.

----

We'd use an asymmetric encryption, such as [RSA](https://en.wikipedia.org/wiki/RSA_(cryptosystem)). Not sure if the below makes any sense as I don't work with encryption.

Terminology:

- **Scene-modifying message** --- any operation the shouldn't be allowed for readonly clients, e.g. creating or editing elements. Cursor update messages do not fall under this.
- **Write-authorized clients** --- those which can send *scene-modifying* messages.
- **Public key** --- key shared with all clients.
- **Private key** --- key shared only with write-authorized clients.

Spec:

1. Clients detect whether they're readonly (and whether they should accept scene-modifying messages) by checking if url fragment does not contain a *private key*.
    
    1.1. If url fragment does contain a *private key*, the client is *write-authorized*.
2. When *write-authorized* client sends a *scene-modifying* message, it signs the message using its *private key*.
    
3. When a readonly client receives a message, it checks whether the message is of *scene-modifying* `type` or not. If it is, it verifies (using its *public key*) that it comes from a *write-authorized* client. If verification fails, it throws the message away.

**Comment by lipis** [comment]
More details in #2842
