### ISSUE TITLE
Feature request: box with rectangle on top

### ISSUE THREAD

**Issue by ajsaraujo** [excalidraw/excalidraw#1870]
Hey, it would be nice if we had a tool that drew a box with a little rectangle on top of it, like in the image below.

![Box with a line crossing it](https://i.imgur.com/BJxALEE.png)

Right now what I'm doing is creating a box, then drawing a line at the top. It's not that annoying, but it would be smoother if there was a tool that let me do these two things at once. It would be very useful for drawing class diagrams, for example.

**Comment by dwelle** [comment]
This sounds too specific to be supported in the base app. We try to be minimal in the tools we add.

That said, you may want to keep an eye on [this PR](https://github.com/excalidraw/excalidraw/pull/1787) which adds support for library of shapes. That way you can add these shapes and reuse them as later.
