### ISSUE TITLE
[Integration Request] VSCode extension for Excalidraw

### ISSUE THREAD

**Issue by alanzanattadev** [excalidraw/excalidraw#1877]
Hi,

I've found this extension for Draw.io https://github.com/hediet/vscode-drawio which is amazing and allows a very efficient workflow leveraging the file tree to open different documentations. We know that excalidraw is currently not supporting the multi files on the web interface which makes it painful to use if you have a lot of drawings to keep. What about creating such extension for VSCode ?

Best

**Comment by kbariotis** [comment]
Related to #1377

**Comment by lipis** [comment]
This is out of scope for the core team.. if anyone is interested we're happy to help.
