### ISSUE TITLE
Free draw icon is inconsistent

### ISSUE THREAD

**Issue by xixixao** [excalidraw/excalidraw#1879]
All of the icons in the primary toolbar are WYSIWYG:

<img width="390" alt="Screen Shot 2020-07-06 at 21 22 31" src="https://user-images.githubusercontent.com/1473433/86709463-cfe0b600-bfce-11ea-894e-ae886503232b.png">

except for the recently added "free draw" icon - which uses a pencil (number 7). It works, but is quite inconsistent and a bit illogical (everything in excalidraw looks like it's drawn with a pencil).

Is there a better icon we could use? Some sort of a squiggle?

**Comment by dai-shi** [comment]
Something like this?
https://excalidraw.com/#json=5264283508146176,4K4Ma4s2ndRiRXMizr9PpA

![image](https://user-images.githubusercontent.com/490574/86713320-ecc1cb80-c058-11ea-939d-1ee4009f9d47.png)

**Comment by Fausto95** [comment]
Or something like this?
<img width="50" src="https://user-images.githubusercontent.com/23306911/86838942-0edf3c00-c0a1-11ea-970b-66c7f5868c45.png"/>

**Comment by lipis** [comment]
We'll stick to what we have.
