### ISSUE TITLE
Feature Request: Dark Mode

### ISSUE THREAD

**Issue by NOAHGengo** [excalidraw/excalidraw#1886]
Hey, I love Excalidraw so far!

Dark mode would be really helpful for working with Excalidraw at night

I tried to just use the chrome extension Dark Reader but it only seems to affect the UI. The canvas is unaffected

**Comment by NOAHGengo** [comment]
I just found out you can change the color of the background at the top left. Beautiful

**Comment by dwelle** [comment]
Also there's https://github.com/excalidraw/excalidraw/issues/1148 already
