### ISSUE TITLE
Copied group shows as multi-selection when pasted (and old is selected)

### ISSUE THREAD

**Issue by xixixao** [excalidraw/excalidraw#1894]
Steps to repro:

1. Create a few shapes
2. Group them using cmd+shift+g (on macOS)
3. Copy the group using cmd+c (on macOS)
4. Paste somewhere using cmd+v (on macOS)
5. Observe that the grouped elements are shown as selected, and the old group is also shown as selected, which is confusing

Screenshot:
<img width="419" alt="Screen Shot 2020-07-08 at 21 06 02" src="https://user-images.githubusercontent.com/1473433/86995789-d7cf6000-c15e-11ea-9bd5-a05e20efad55.png">

This is not a problem using alt-drag duplication:

Screenshot (and what it should like above too):
<img width="411" alt="Screen Shot 2020-07-08 at 21 06 19" src="https://user-images.githubusercontent.com/1473433/86995877-0f3e0c80-c15f-11ea-9d12-1a6cc7f309f2.png">

(this is also how single elements copied look like)

**Comment by ReneCode** [comment]
This happens also on the duplicateSelection action.

I'll give it a try.

**Comment by ReneCode** [comment]
fixed with [PR#1963](https://github.com/excalidraw/excalidraw/pull/1973)
