### ISSUE TITLE
Choosing color before entering text content looks broken

### ISSUE THREAD

**Issue by xixixao** [excalidraw/excalidraw#1897]
Steps to repro:

1. Create a new text element
2. Before you type anything, try changing the stroke color to a different color

**What happens:**

The cursor color is changed, if you type you do get the new color. But the swatch keeps showing the color that was selected before you created the text element.

<img width="551" alt="Screen Shot 2020-07-08 at 21 44 01" src="https://user-images.githubusercontent.com/1473433/86997946-2af7e180-c164-11ea-97d5-e43c610d5001.png">

**What should happen:**

The swatch should reflect the newly selected color.

---

If you type at least one character this bug doesn't manifest.

**Comment by dwelle** [comment]
I can repro even if there's text.

**Comment by msal4** [comment]
I would like to work on it if no one is

**Comment by dwelle** [comment]
go for it!
