### ISSUE TITLE
support boolean operations on shapes

### ISSUE THREAD

**Issue by haan123** [excalidraw/excalidraw#1906]
Reference from #1905,
it would be great if this feature is accepted

### Supports:
Boolean operations: `Diference` `Union` `Exclusion` `Intersection`
Keyboard shortcuts:
Supports all basic shape except Arrow

#### Desktop
![captured](https://user-images.githubusercontent.com/5218341/87222203-20279180-c39c-11ea-83a7-bdb783863ad6.gif)

#### Mobile
![captured (1)](https://user-images.githubusercontent.com/5218341/87222409-98428700-c39d-11ea-9a94-2f28685790d2.gif)

**Comment by mth2610** [comment]
Nice feature, I hope it will be merged

**Comment by vjeux** [comment]
@haan123 hey, since excalidraw was started 6 months ago, no one ever mentioned shape boolean operations as something they would want.

Could you explain some of the use cases where having this feature be useful?

**Comment by haan123** [comment]
Hi @vjeux ,

Firstly, thank you for your great app 👍 

There are many use cases, they can be grouped into 2 main elements:

#### The creativity
Assume i want to built a prototype for my new mobile app from Excalidraw, then:

I need a **triangle** for **caret icon**, i can achive this by using the **Line tool**, but with all the curves, it does't look like arrow to me <img src="https://user-images.githubusercontent.com/5218341/87243630-b376ca80-c461-11ea-8eac-85671dbcc143.png" width="48">, by using new feature, i just need to draw **rectangle** and **diamond** shapes, then operate the **Difference action** <img src="https://user-images.githubusercontent.com/5218341/87243744-a73f3d00-c462-11ea-8f2b-2a55dd696bb2.gif" width="150">
Or i want to have a gear for my **settings icon** like this 
![captured (1)](https://user-images.githubusercontent.com/5218341/87245847-20469080-c473-11ea-908b-7520d4e1532d.gif)
Or a **avatar icon**
![captured (2)](https://user-images.githubusercontent.com/5218341/87245909-b8447a00-c473-11ea-8da5-1b59ff82a5a7.gif)

You can create any shape you want, `the limit depends only on your imagination`

#### The convenience
Have you tried to make a **caret** by using Excalidraw on **mobile**? well, i think the only way to make one is using the **Line tool**, but it's nearly impossible to close the path with your big thumb 👍 , so you will wish if you have ability to **cut out** a **rectangle** and a **diamond** to make this **caret**

I think this is a needed feature for all vector drawing tools, in fact, this is the most feature i have used when designing in **Inkscape**

Thanks!

**Comment by anbkit** [comment]
Fantastic feature. Thanks.

**Comment by tantv** [comment]
Nice feature. Thanks

**Comment by tholai-groove** [comment]
Fantastic feature. Thanks.

**Comment by lipis** [comment]
I love this feature too..

**Comment by tomhicks** [comment]
This is a great addition. I have a request though...

Having used these operations only occasionally in Oita of different packages, frequently I forget what does what, and what selection order or stacking order does to the behaviour.

Considering that my overwhelming experience of excalidraw is that it’s “not annoying” or even “anti-annoying”, it would be nice to keep up that trend. So I propose that these operations should be previewable in some way. For example, by hovering over each button, or by launching a dialog that lets you explore the options (and even let you change the selection ordering on the fly to see the effect).

I’ve not seen any other package do that, and I feel like it would be immensely helpful, especially as a way to lower the barrier to entry to these more complex operations.

**Comment by haan123** [comment]
Hi @tomhicks,
Thank you for your suggestions! but it requires large effort for that behavior because we will need some ways to store the origin states and we have to operate the boolean operation every time we hovering on the button (the boolean operation is expensive especially with multiple shapes selected), then reverse back to the origin state when moving out the button.

I think the best way is to use the **undo (cmd / ctrl + z)** to reverse back if your action is not what you meant

**Comment by vjeux** [comment]
@tomhicks this is actually a great suggestion for all actions in excalidraw. I can see how it would be better to be able to mouse over all the things in the left menu and see how they’d look and click to commit. Could you open a separate issue for this?

**Comment by lipis** [comment]
So back to this feature request.. what do you think @vjeux shall we move on with it?

**Comment by pynomaly** [comment]
I like this feature too. Thanks!

**Comment by lipis** [comment]
We decided to have a pass on this feature.

**Comment by tobei** [comment]
That's really a pity to see this closed, basically a feature of every existing vector based drawing thing... I wanted to quickly layout a floor map and instead of making everything not straight with the pen i quickly assembled together a few rectangles. But then of course impossible to get rid of of the intersecting lines everywhere while all i wanted was to make this a single shame. I don't think it's right to see deleting a few points or union/intersection as "advanced" or "complicated", in many cases it's even way faster than the alternative of drawing ugly and disalligned lines with the pen, and then not even have the option fo fill it.

**Comment by rupadarshiray** [comment]
This is solved by the script [Boolean Operations](https://github.com/zsviczian/obsidian-excalidraw-plugin/blob/master/ea-scripts/Boolean%20Operations.md).

**Comment by tinedel** [comment]
Too bad this didn't get merged
fantastic feature

**Comment by winter-loo** [comment]
we need this feature as it inspires creativity and fun.
