### ISSUE TITLE
Rounded rectangles

### ISSUE THREAD

**Issue by gaearon** [excalidraw/excalidraw#1916]
This is getting close to feature creep but I wonder if rounded rects were considered. Not as a separate shape but as an option, similar to Stroke Style or Sloppiness. My use cases would only be limited to rectangles and not any of the other shapes. I would be happy with a fixed predetermined radius.

**Comment by pshihn** [comment]
Hand crafting one and saving it in the library is a workaround: https://twitter.com/excalidraw/status/1281520753691828224?s=20 You can then replicate it easily whenever you need it

**Comment by dai-shi** [comment]
@pshihn I don't think we can create it with a single shape because we only support roughCanvas.curve: https://github.com/rough-stuff/rough/wiki
Lately, I've been thinking if we would need to support `path`, but let us know if you have any ideas to draw something like rounded rectangles and more complicated shapes.

**Comment by pshihn** [comment]
yes, I wasn't thinking of a single shape.  create something like this: https://excalidraw.com/#json=5643242062217216,pbsWg6KNCnymGMP0mk-H0A Group it. Add to the library. Now whenever you need a rounded box, pick it from the library. Not ideal, but a decent workaround. 

As to implement it, you can use the path, or use multiple draw steps, like we do in arrows. 4 lines and 4 arcs.

**Comment by dai-shi** [comment]
Nice.
Filling is not that bad either: https://excalidraw.com/#json=5643242062217216,pbsWg6KNCnymGMP0mk-H0A
(Honestly, I like this kind of creativity out of limitations.)

**Comment by lipis** [comment]
or draw one with the linetool carefully and close it. then you'll be able to have a filler and resize it to any size. 

https://excalidraw.com/#json=5644779392073728,5Wkha79ezS8QXMzOJi-x2w (could be better)

**Comment by pshihn** [comment]
@lipis  true. Updated yours a bit https://excalidraw.com/#json=4878539174182912,su5PdfsA54zavYLCHoz_0A

**Comment by lipis** [comment]
https://github.com/excalidraw/excalidraw/pull/1931 Looks very promising :)
