### ISSUE TITLE
upload image and then pencil sketch the image

### ISSUE THREAD

**Issue by cnscorpions** [excalidraw/excalidraw#1921]
It's not so easy for some guys to draw what they want. 

And it will be much convenient to upload an image and then get the corresponding drawing.

If it's hard to implement this functionality. Please consider adding some basic templates. 

thanks

**Comment by dwelle** [comment]
Hello, this would be part of https://github.com/excalidraw/excalidraw/issues/19

> Please consider adding some basic templates.

Common asset library is under consideration.
