### ISSUE TITLE
Add common library

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#1923]
On top of user library, we should have some pre-built, standard library of common shapes for people to use without having to draw them themselves.

Should probably live in the repo so people can make PRs for new shapes.

**Comment by sw-yx** [comment]
what are a good set of inclusion criteria for common shapes?

**Comment by dwelle** [comment]
I'd imagine: must be common, generic, and high quality.

Note that we don't even have consensus for this feature yet. The implementation needs to be figured out, too.

**Comment by lipis** [comment]
Having a repo for collecting those is a good idea.. but I'm not sure if we want to include the common library in general in Excalidraw.

**Comment by defint** [comment]
Upvote to this feature.
If I need to create a scheme (block-scheme, BPMN, UML, etc..) I go to draw.io or something else service to achieve my goal because other services have prebuilt shapes to save my time.

**Comment by lipis** [comment]
Since our target group is pretty wide, I don't think that we'll be able to find a common library for all users.. For now we can start with this https://excalidraw.github.io/excalidraw-libs/ and eventually we can think on how to incorporate it.

**Comment by mornir** [comment]
The link above pointing the libs is dead. Here's a new link: https://libraries.excalidraw.com

**Comment by sohailamjad256** [comment]
can we get your api to add library item
