### ISSUE TITLE
Import SVGs

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#1924]
I'm sure this has been discussed before, but maybe we could support importing SVGs by creating a new element type which would act as a regular shape except the rendering would use an SVG path(s) stored in the element.

We'll need to do something similar if we implement #19

Use cases:

- import any SVG asset for use or later reuse (by adding it to library)
- https://github.com/excalidraw/excalidraw/issues/1636 (?)

via https://github.com/excalidraw/excalidraw/issues/1904#issuecomment-658732054

**Comment by khanh-bes** [comment]
+1 for this, this would make excalidraw an amazing tool to quickly prototype a web/app screen.

**Comment by WELZ-gh** [comment]
I think this would be an excellent feature - upon importing it could just convert the SVG path(s) to an excalidraw group of paths

**Comment by lipis** [comment]
@WELZ-gh Something like this: https://github.com/excalidraw/svg-to-excalidraw? :)

**Comment by timrnd** [comment]
@lipis I was trying to build the repo (and couldn't) and then found this issue.  Based on the timing it looks like you are just now starting the project?  Let me know if I can help in anyway, I'm trying to convert the Azure SVGs (https://docs.microsoft.com/en-us/azure/architecture/icons/)

**Comment by lipis** [comment]
@timrnd yes we just started it.. and there is a first PR to it :) We really don't know how it's going to evolve.. but you are welcome to join our Discord and there is a channel called `#svg-to-excalidraw` for ideas and contributions

**Comment by ch-hellmich** [comment]
It would be great if you could just copy icons from [Tabler Icons](https://tablericons.com) or [Phosphor Icons](https://phosphoricons.com) and paste them into excalidraw. May have options to add a hand-drawn style to them.

**Comment by chhch** [comment]
It would be great if you could just copy svg icons from [Tabler Icons](https://tablericons.com) or [Phosphor Icons](https://phosphoricons.com) and paste them into excalidraw. May have options to add a hand-drawn style to them.

**Comment by steveruizok** [comment]
Ran into [this](https://github.com/jonobr1/two.js/blob/dev/src/utils/interpret-svg.js) today in the Two.js source, their methods for parsing down an SVG into component shapes. Could be useful as a reference for some of the trickier parts.

**Comment by dwelle** [comment]
> Ran into [this](https://github.com/jonobr1/two.js/blob/dev/src/utils/interpret-svg.js?rgh-link-date=2021-03-15T20%3A46%3A46Z) today in the Two.js source, their methods for parsing down an SVG into component shapes. Could be useful as a reference for some of the trickier parts.

@brochington @nicolas-goudry might be interested

**Comment by brochington** [comment]
@steveruizok Thanks for the link to the Two source! I'll happily use it as a reference.

**Comment by YesterKo** [comment]
I believe this issue can be closed, as we now have the import feature for pictures. Just tried it out and it seems to work for svg's too.

**Comment by WELZ-gh** [comment]
@YesterKo I disagree because I think the idea behind this wasn't so much as importing an image into Excalidraw as it was about converting an SVG into Excalidraw editable paths/shapes. (at least that's the way I envisioned it)

**Comment by dwelle** [comment]
Actually, @YesterKo is correct. This issue was just about importing SVGs. Unclear why I made it a separate issue from importing images.

Converting SVGs to excalidraw shapes is (at least for now) outside the scope of this project. There's a separate project handling this, but I'm not sure what state it's in: https://github.com/excalidraw/svg-to-excalidraw
