### ISSUE TITLE
Grid mode: Stick to grid mode when pasting

### ISSUE THREAD

**Issue by xixixao** [excalidraw/excalidraw#1927]
When pasting objects which otherwise stick to the grid are placed off grid. It would be nice if they were already in grid when pasted (via cmd+v).

**Comment by mauriceLC92** [comment]
@xixixao May I tackle this?

**Comment by dwelle** [comment]
Let's do it. If you hit a roadblock, ask on our [discord](https://t.co/jWJMO0IcUu?amp=1).

**Comment by mauriceLC92** [comment]
Awesome! Thanks Dwelle

**Comment by mauriceLC92** [comment]
@dwelle PR for this https://github.com/excalidraw/excalidraw/pull/2107
