### ISSUE TITLE
Context menu 

### ISSUE THREAD

**Issue by jaredpalmer** [excalidraw/excalidraw#193]
Right / Ctrl clicking an element should pop out a context menu

- Copy
- Delete
- Paste
- Move Forward
- Move Backwards
- Send to Back
- Send to Front

—-
Right clicking a selection with multiple elements should have the option to group, right clicking a group should have option to ungroup.

**Comment by vjeux** [comment]
Agreed, this way we don't have to put all those things on the left menu which is getting crowded!

**Comment by nanot1m** [comment]
I'll take it
