### ISSUE TITLE
Text resize via mouse drag is not in the undo/redo stack

### ISSUE THREAD

**Issue by schrockn** [excalidraw/excalidraw#1936]
Not sure when it was added, but one can now dynamically resize text. That's cool. However that act is not in the undo/redo stack so if you accidentally do it or do it imprecisely you can't undo that. Very easy to get yourself into a state where you can a bunch of different text sizings and you are forced to manually reconstruct all text to get things to be the same size.

**Comment by vjeux** [comment]
@dai-shi can you take a look?

**Comment by dai-shi** [comment]
Can't repro?
![excal71](https://user-images.githubusercontent.com/490574/87864691-7d2bd480-c9a6-11ea-8db5-f314bec960bf.gif)

**Comment by dwelle** [comment]
Can't repro either. If anyone supplies repro steps I can take a look at this since it'd be related more to history (my purview) rather than text resizing.

**Comment by schrockn** [comment]
I can no longer repro either! If I run into this I will reopen. Thanks for checking into and for tolerating this errant report. And of course thank you for your work on this great tool
