### ISSUE TITLE
Icons

### ISSUE THREAD

**Issue by jaredpalmer** [excalidraw/excalidraw#194]
- One for each fill style (probably need to be custom)
- One for each stroke style
- Send to front/back, etc. 
- Copy
- Delete

**Comment by jaredpalmer** [comment]
This will let us save some vertical space by making fill styles a grid and more wysiwyg-like

**Comment by vjeux** [comment]
I did an update which should require less custom icons:
![image](https://user-images.githubusercontent.com/197597/71794407-340dc780-2ff6-11ea-9e8a-d12eca84a9dc.png)

Also, if we implement context menu, we don't need for send front/back, copy, paste, delete

**Comment by jaredpalmer** [comment]
Ahh this is much better. I still think having icons for the fill styles would be useful

**Comment by GasimGasimzada** [comment]
@jaredpalmer do you know an icon in FontAwesome that is just straight lines parallel to each other?

**Comment by dwelle** [comment]
https://fontawesome.com/icons?d=gallery&q=bar

**Comment by GasimGasimzada** [comment]
This is just an idea but maybe something like this: https://codesandbox.io/s/heuristic-clarke-rbdh2

**Comment by dwelle** [comment]
@GasimGasimzada we've recently moved to inlining it, instead (see #134)

**Comment by jaredpalmer** [comment]
My suggestion would be to use react-icons since CRA supports react svg loader now

**Comment by GasimGasimzada** [comment]
@dwelle @jaredpalmer I was talking about how they look like. All I did was rotating and stacking (for cross-hatch) Bars icon. This can be easily implemented using some positioning + transforms. It is not necessary to use FontAwesome here as many icon libraries have bars icon in them.

**Comment by GasimGasimzada** [comment]
Also, I agree with @jaredpalmer. I think it will make it easier to set up icons if we use react-icons library. It looks like this library is treeshakeable.

**Comment by jaredpalmer** [comment]
I would use sketch or Figma and make a custom svg for each of those.

**Comment by lipis** [comment]
I think we got this!
