### ISSUE TITLE
Icons feature

### ISSUE THREAD

**Issue by viniciusoyama** [excalidraw/excalidraw#1947]
I use Excalidraw a lot and noticed that sometimes it would be helpful to be able to use some icons presets instead of drawing myself.

I believe that when we use a tool like this we want to quickly communicate an idea and the possibility to use icons would bring a big improvement on the time that we spend in order to express something. 

My suggestion is that we create a new tool on the main top menu. 
Also, we could utilize font awesome: a icon set that developers/designers area already familiar with. 

I could develop this feature if you think that it makes sense.

**Comment by dwelle** [comment]
Hello. I'd say this falls under https://github.com/excalidraw/excalidraw/issues/1923 & https://github.com/excalidraw/excalidraw/issues/1924.

It's not likely we'll want add a separate tool for icons.

**Comment by lipis** [comment]
I agree with @dwelle we want to keep the things simple..
