### ISSUE TITLE
resize elements at the edge-handle with "shift" broken

### ISSUE THREAD

**Issue by ReneCode** [excalidraw/excalidraw#1950]
If I resize an element at the edge-handle while pressing "shift" results a "strange" behaviour.
* The width/height ratio stays the same (that is the behaviour if and corner-handle is dragged)
* The element can only be resized to a larger size, making is smaller is not possible.

In a previous version of excalidraw dragging an edge-handle resizes with keeping the center on the same position - that behaviour is broken.

**Comment by dai-shi** [comment]
> The element can only be resized to a larger size, making is smaller is not possible.

I wasn't aware of this weird behavior.
![excal75](https://user-images.githubusercontent.com/490574/88284566-962ae180-cd28-11ea-87da-1957136572b1.gif)

----

> keeping the center on the same position

I don't know this behavior. Was it "shift"? not "alt"?

**Comment by ReneCode** [comment]
ah, @dai-shi you are right. "alt" and dragging the handles makes resize with keeping the center in the middle of the element.

**Comment by dwelle** [comment]
Ad the `alt` thing, there should be a hint for this. This PR addresses that part: https://github.com/excalidraw/excalidraw/pull/1952

**Comment by ReneCode** [comment]
That bug is gone / solved. Now it works fine.
