### ISSUE TITLE
Redirect www domain to bare excalidraw domain

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#1951]
- [ ] `www` subdomain is currently not whitelisted in the json server, so users can't share links [[**PENDING RELEASE**]](https://github.com/excalidraw/excalidraw-json/commit/84e9250b26bfcba23b0433d144a0970444a66b9a).
- [ ] It turns out the `www` subdomain and the bare domain do not share browser storage, which isn't good.

The fact that Chrome (and Safari?) hides url scheme and `www` subdomain does not help in debugging what's going on, either.

/cc @lipis

EDIT: FF does some kind of a redirect, but it seems to be a browser intervention (there's no request/response):

![image](https://user-images.githubusercontent.com/5153846/88330783-346c7680-cd2c-11ea-83fe-c9e2ae1b2cf4.png)

**Comment by lipis** [comment]
<img width="784" alt="Screenshot 2020-07-24 at 4 34 00 PM" src="https://user-images.githubusercontent.com/125676/88396688-903a0c80-cdcb-11ea-9454-7eb68d58cb40.png">

https://www.excalidraw.com redirects to https://excalidraw.com

**Comment by lipis** [comment]
I tried on Chrome, Safari, Firefox on macOS and it works.. also:

```
$ curl https://www.excalidraw.com
Redirecting to https://excalidraw.com/ (307)
```

**Comment by dwelle** [comment]
Clearing cache for `excalidraw.com` (all domains) solved it and the redirect started working.
