### ISSUE TITLE
Tamil Translation

### ISSUE THREAD

**Issue by saravanaselvan** [excalidraw/excalidraw#1954]
Hi,

I would like to translate it to Tamil, one of the Indian languages (If someone has not started already). This is the text for Tamil to display in the dropdown: **தமிழ்**

Thanks.

**Comment by dwelle** [comment]
Here yo go https://crowdin.com/project/excalidraw/ta# :)

**Comment by lipis** [comment]
@saravanaselvan How is Tamil in Tamil?

**Comment by lipis** [comment]
#1949
