### ISSUE TITLE
no button to start a fresh drawing. 

### ISSUE THREAD

**Issue by mwuf15** [excalidraw/excalidraw#1957]
There doesn't seem like a button to make a new drawing,  and ways to name the drawing.

**Comment by ReneCode** [comment]
* New drawing: Just remove the current drawing. Take the trash-can-button left side of the user-icon:
![image](https://user-images.githubusercontent.com/1595098/88422035-dbfbae80-cde9-11ea-9d14-a91a5c56f735.png)

* Name a drawing: you can name a drawing on saving it. Take the disk-with-pen-button.
![image](https://user-images.githubusercontent.com/1595098/88422117-fcc40400-cde9-11ea-867c-cf55924d0cc7.png)

**Comment by dwelle** [comment]
I'm aware of this pain point, the scene toolbar needs a redesign. I've seen many people confused what's what and how to accomplish certain tasks.

**Comment by cor-rine** [comment]
Is it possible for us to enable a new drawing with Ctrl/Cmd + N so that it is more familiar to those who are coming from a design background?

**Comment by cor-rine** [comment]
@vjeux - would you be able to provide some direction as to what you've been hearing about the menus/UX/UI so that we're all aware and can come up with a better design here?

**Comment by lipis** [comment]
Ctrl/Cmd+N creates a new tab.. so it's a no go.

**Comment by ReneCode** [comment]
> Ctrl/Cmd+N creates a new tab.. so it's a no go.

Good point to discuss about. I is allowed to overwrite general browser-shortcuts?

On a "normal" website Ctrl/Cmd+D is used for bookmarking the current page. But in excalidraw it's used for duplicateSelection. I think that is fine.

May be we exchange the trash-can icon to a "new" icon 
![image](https://user-images.githubusercontent.com/1595098/88511141-9f47d700-cfe4-11ea-8bdb-c6b5b5815246.png)
and put it left. It would look like:
![image](https://user-images.githubusercontent.com/1595098/88511433-154c3e00-cfe5-11ea-9030-d16ce66c2dee.png)

**Comment by dwelle** [comment]
> Good point to discuss about. I is allowed to overwrite general browser-shortcuts?

Generally we avoid it unless it has precedent (`Cmd+D` to duplicate selection is used in Figma). In certain cases browsers don't allow it, anyway (I believe `Cmd+N` is such a case).

> May be we exchange the trash-can icon to a "new" icon

I'd wait until we add #1543

**Comment by faraz16iqbal** [comment]
Is this issue still open?

**Comment by ReneCode** [comment]
> Is this issue still open?

@dwelle would like to wait until  #1543 is solved
I think that is a good idea because that has impact how new documents are created (clear the old one or create a new tab)

**Comment by justshrey** [comment]
Can we please remove the trash can icon. We just had a session today where someone clicked the trash icon thinking it will clear the element they were editing and did not read that it will clear the canvas for everyone !!! Luckily we had a backup "template" and it was in the beginning of the session so we were saved for recreating a lot of work !!   

For non-techies, and people who are not used to design software, the trash can icon is confusing, since the assumption is that there is a button to delete the object.

**Comment by dwelle** [comment]
Noted.

Btw, when you clear the canvas by mistake, you can always undo it via `Cmd+Z`.

**Comment by lipis** [comment]
We have the delete button and currently having one more button doesn't make sense.

**Comment by nemith** [comment]
The fact i came here from a google search 2.5 years later means that it's not clear and the current model doesn't make much sense (at least not to me)

**Comment by alecthomas** [comment]
Yep, same here. Excalidraw is amazing BTW :)

**Comment by gokulk16** [comment]
Please have an easier way to create a new canvas. It took me a few google searches to reach here and find the answer.

**Comment by ad1992** [comment]
@gokulk16 when you say an easier way to create new canvas you mean same functionality which we have via "trash" button ?
![image](https://github.com/excalidraw/excalidraw/assets/11256141/9bd087b2-ebad-49c1-b93d-55b1acf21b9a)

**Comment by gokulk16** [comment]
> @gokulk16 when you say an easier way to create new canvas you mean same functionality which we have via "trash" button ?
> ![image](https://github.com/excalidraw/excalidraw/assets/11256141/9bd087b2-ebad-49c1-b93d-55b1acf21b9a)
> 

Yes. Something with 'command + N' or 'command + R' could refresh the canvas

**Comment by ad1992** [comment]
Well in that case having another button for the same purpose doesn't make sense :/
May be we can rename it to "Clear and Start Fresh" or something better, would that help ?

**Comment by bebound** [comment]
I wouldn't believe the trash icon means creating new until I found this issue from search engine.
It pops this up when you click it, which is even more confusing.
![image](https://github.com/excalidraw/excalidraw/assets/2227874/ee1c1032-f50b-452f-81ce-e81d42ee734c)

**Comment by konashevich** [comment]
Dear developers, what are you trying to prove?
Clear canvas is not a good function to create a new drawing. This creates bad user experience, I myself lost some important diagrams this way.
There must be button Create NEW, this is THE only possible good UIX. The rest is just an attempt to prove something to someone without any clear reason.

**Comment by ad1992** [comment]
"**Start a new Drawing**" IMO would be more confusing as it would convey users to that your current drawing will be saved and you start with a new drawing which we don't support in the open-source editor. 

So in that case we should make it clear that the option will completely erase your current drawing and as per the feedback that's not clear right now.

So should we rename that ?
Would renaming to "Delete / Erase the drawing" help? open for better suggestions.

**Comment by bebound** [comment]
1. We do need a `New` button. (Though its behavior is the same as `Reset`)
2. When click new, a notification like this is less confusing: `Excalibrew does not support multiple tabs for now, the current canvas will be discarded/cleared. Please ensure that you have saved any changes before proceeding.`

PS: IMHO, reset usually clear the **current** drawing, but in excalidraw, it unlinks the current filename and start a new drawing.

**Comment by jamfor352** [comment]
Honestly I'm so confused. If I have a drawing open, I just want to save the link I have and move onto a new drawing. But I **don't** want the currently existing link for said drawing (when Save To Link exists) to now point to my new drawing, there should be a new link... but Reset The Canvas seems to keep the old link.

**Comment by jamfor352** [comment]
Isn't it just easier to rename "Reset The Canvas" to "Start New Drawing" since that's what it does from a user's perspective?

**Comment by joaowatchful** [comment]
> 1. We do need a `New` button. (Though its behavior is the same as `Reset`)
> 2. When click new, a notification like this is less confusing: `Excalibrew does not support multiple tabs for now, the current canvas will be replaced by a new one. Please ensure that you have saved any changes before proceeding.`
> 
> PS: IMHO, reset usually means clear the **current** drawing, but in excalidraw, it unlinks the current filename and start a new drawing.

And maybe have it as the first menu option? 🤔 That's how I picture the common place for such button to be

**Comment by itsobgraph** [comment]
> The fact i came here from a google search 2.5 years later means that it's not clear and the current model doesn't make much sense (at least not to me)

Same in 2024

**Comment by almeraikhi** [comment]
"Reset the Canvas" with a "trash" icon is confusing.

Just add "Create New Canvas" instead, and clicking it will show this prompt:

![CleanShot 2024-06-10 at 09 24 46](https://github.com/excalidraw/excalidraw/assets/130155541/4b1dd95f-bd38-4240-9553-40f1ea0ff9c0)

By default, "Create New" is greyed out. 

* Save File

If user clicks on "save file", and the file gets saved to their device, the "create new" button becomes available.

* Excalidraw +


If the user clicks on "excalidraw+", then we don't need to change the state of the button because we just assume they want to save it in the workspace. They will be routed to excalidraw + in a new tab.

Perfect opportunity to promote your paid solution that you are missing out on everyday. 

* Don't wanna save

if the user checks "don't save the current canvas" then "create new" becomes available.

**Comment by PandukaNandara** [comment]
It is really disappointing that the developers could not add simple New File or New Canvas Button. 🖕🏻

**Comment by lappi** [comment]
Dear developers! Maybe it's a first time when I come to graphic tool's github and asking the feature. We as users DO need the common way CREATE NEW button. It's a classic and the best UX ever, click NEW button, ask to SAVE, or to DISCARD the old drawing and go on. Why are you making a square wheels bike UX for so amazing product from other sides?

**Comment by cjj1120** [comment]
not sure why it's closed, users clearly dislike the delete button and it's still here.

**Comment by Ceaus** [comment]
> > The fact i came here from a google search 2.5 years later means that it's not clear and the current model doesn't make much sense (at least not to me)
> 
> Same in 2024

Same in 2025

**Comment by Ceaus** [comment]
> "**Start a new Drawing**" IMO would be more confusing as it would convey users to that your current drawing will be saved and you start with a new drawing which we don't support in the open-source editor.
> 
> So in that case we should make it clear that the option will completely erase your current drawing and as per the feedback that's not clear right now.
> 
> So should we rename that ? Would renaming to "Delete / Erase the drawing" help? open for better suggestions.


You can do as you wish, but it MUST MATCH the mental paradigm of how a user approaches an application. And since the early 90s of the last century the graphical UI idiom is CTRL-N for New, CTRL-S for Save, CTRL-W for Close (and a few others).

Every discussion on how to use the trashcan icon and its meaning is just a distraction: you're replacing a functional model with a technical model. As a user I don't want to deal with the technical model. Rephrased as a modern standpoint: Don't make think. If you have to explain the UI to me, there's something wrong with the UI.

**Comment by iandees** [comment]
Howdy. Coming here in August 2025 to mention that it's still not clear how to get a new blank drawing.

**Comment by jezewskiBNetrox** [comment]
I found Excelidraw lately and I really like this. However I cannot comprehend, how after 5 years there is no "New drawing" button or option. That's just confusing for new user.

**Comment by maiku1008** [comment]
Unsure why this has been closed.

October 2025.
In the last few days I opened the excalidraw that was shared with me by someone else, my colleague.
Today I need to create a new one, but my colleague's one is still visible.

How do I create a new one?
No "new" button.
It seems the way to go is to put the current one in the trash.
If I do that, will I delete my colleague's work?

It's just unclear :/
Can we start talking about this again?

**Comment by peterfisher** [comment]
You can start a new canvas (and delete your existing canvas) by using keyboard **shortcut: cmd+delete** (clear canvas)

**Comment by Andrewryanhyde** [comment]
> > > The fact i came here from a google search 2.5 years later means that it's not clear and the current model doesn't make much sense (at least not to me)
> > 
> > 
> > Same in 2024
> 
> Same in 2025

Same in 2026 🤯

**Comment by scubbo** [comment]
> > > > The fact i came here from a google search 2.5 years later means that it's not clear and the current model doesn't make much sense (at least not to me)
> > >
> > >
> > > Same in 2024
> >
> > Same in 2025
>
> Same in 2026 🤯

Same in August 2026
