### ISSUE TITLE
File Extension not set properly while trying to export to a PNG

### ISSUE THREAD

**Issue by kanhegaonkarsaurabh** [excalidraw/excalidraw#1958]
* I'm currently trying to export my excalidraw diagram to a PNG and when I click on the "PNG" option, this dialog box pops up. 
![Screen Shot 2020-07-24 at 2 28 52 PM](https://user-images.githubusercontent.com/25760507/88436862-12213a00-cdba-11ea-8982-940a580be9cc.png)

* Currently, I have to name my files with the ".png" extension to ensure that they get downloaded properly.

**Comment by dwelle** [comment]
Yea, I've noticed this too. It seems a regression.

**Comment by tomayac** [comment]
What browser version did this happen on?

**Comment by dwelle** [comment]
I'm on Chrome 84.0.4147.89

Only happen for the PNG/SVG export (`.excalidraw` works).

![image](https://user-images.githubusercontent.com/5153846/88452778-c4600c80-ce61-11ea-9978-fa4ca0f6507d.png)

**Comment by lili21** [comment]
still run into this issue. Has the fix been published?

**Comment by dwelle** [comment]
What's your browser/system?

It's possible you're still running an older version of excalidraw. Please paste this into console `window.__EXCALIDRAW_SHA__` and post here what it returns.

**Comment by lili21** [comment]
It's the cache problem. Thanks. @dwelle
