### ISSUE TITLE
Import PNG JPG images from local machine

### ISSUE THREAD

**Issue by divyakelaskar** [excalidraw/excalidraw#1961]
When I try to import any image from my machine, it shows the following : 

![screenshot](https://user-images.githubusercontent.com/56636487/88449161-4bad8000-ce62-11ea-80d0-36d913b5b2c4.png)

Would like to request the @excalidraw team to include the image import feature :pray:

**Comment by dwelle** [comment]
Hello. This is already track in #19

**Comment by divyakelaskar** [comment]
How can I add images ?

**Comment by dwelle** [comment]
> How can I add images ?

You can't. That's what the #19 request issue is about.
