### ISSUE TITLE
linearElementPoint-handles pickable but not visible

### ISSUE THREAD

**Issue by ReneCode** [excalidraw/excalidraw#1966]
The linearElementPoint-handles should be rendered on top of the elements. 
Below a solid filled element the handle is pickable, but not visible.

![point-handles (2)](https://user-images.githubusercontent.com/1595098/88486149-07160780-cf7c-11ea-8afd-9969e3b3fd1f.gif)

**Comment by dwelle** [comment]
Yea, I noticed this and forgot about it.
