### ISSUE TITLE
Feature Request: Ability to lock elements while Drawing

### ISSUE THREAD

**Issue by justshrey** [excalidraw/excalidraw#1976]
I would like to implement this feature where one could lock individual shapes while drawing. 

The main use case would be for templating. We could have a file which has some areas editable and people could effectively draw on the unlocked one. 

I have just implemented a basic version of this here 

https://excalidraw-git-test-element-locking.justshrey.vercel.app/

The  code for that is here

https://github.com/justshrey/excalidraw/pull/2

If the community finds it useful , would be really happy to make pull request. 

Do let me know what you all think :)

**Comment by dwelle** [comment]
We could in theory make those elements unselectable even without layer support. To select locked elements, you could either:

1. Use `Cmd+click`
2. RightClick→unlock

**Comment by justshrey** [comment]
So something i was thinking of was 

1) What if we basically don't select the locked object during any sort of drag select operation? 

2) We could say that if a group selection exist, any locked object automatically get deselected. If its only selection or if only  locked object  are selected, then its ok.

**Comment by justshrey** [comment]
Honestly, one of the bits  i would implement is a selection pane and the ability to "name" objects. 

That would really improve the overall experience when it comes to selecting objects over all.

**Comment by dwelle** [comment]
> What if we basically don't select the locked object during any sort of drag select operation?

You mean auto-deselect selected locked objects during drag?

> We could say that if a group selection exist, any locked object automatically get deselected. If its only selection or if only locked object are selected, then its ok.

Maybe. It'd get a bit messy for people to figure out what's going on.

> Honestly, one of the bits i would implement is a selection pane and the ability to "name" objects.

That's for another discussion, but I don't see this happening any time soon :).

**Comment by justshrey** [comment]
> You mean auto-deselect selected locked objects during drag?

Yes, this i think would be intuitive as well, since people don't  expect locked objects to get selected. 

> Maybe. It'd get a bit messy for people to figure out what's going on.

Yeah - that can happen. Let me think about some other way to do this.

**Comment by DennisSmolek** [comment]
> So something i was thinking of was
> 
> 1. What if we basically don't select the locked object during any sort of drag select operation?
> 2. We could say that if a group selection exist, any locked object automatically get deselected. If its only selection or if only  locked object  are selected, then its ok.

I agree with this idea. One thing the term "auto-deselect" kinda messed with me and I imagined the UI flickering. I would use "Ignore" but that's just semantics.

Typically locks are like your example where they can be selected singly (to change the lock toggle) but not during drag selection.

Also, locked elements usually cant be added to groups or selected item groups (like they can in your example with shift + click) you do a similar isLocked check and ignore them. 

Another weird semantics thing is that in most editors "locked" is more serious like position is fixed globally or literally all options are immutable. If the only thing not changing is position I think "Fixed" is more correct but I also understand that "Locked" is easier to explain with a simple icon.

Lastly, instead of adding a new row of buttons I'd suggest adding a lock icon toggle to the actions panel (like the group icon)

**Comment by justshrey** [comment]
> I agree with this idea. One thing the term "auto-deselect" kinda messed with me and I imagined the UI flickering. I > would use "Ignore" but that's just semantics.
> 
> Typically locks are like your example where they can be selected singly (to change the lock toggle) but not during drag selection.

Sorry, thats exactly what i meant

> Also, locked elements usually cant be added to groups or selected item groups (like they can in your example with shift + click) you do a similar isLocked check and ignore them.

Agreed

> Another weird semantics thing is that in most editors "locked" is more serious like position is fixed globally or literally all options are immutable. If the only thing not changing is position I think "Fixed" is more correct but I also understand that "Locked" is easier to explain with a simple icon.

Agreed, sort of :) -- I like the idea of locking only the position cuz  basically, that the thing that "accidentally" gets changed. That being said, i do agree that this may not be very intuitive and Locked actually makes more sense in the larger context ( especially on the collaboration front ). 

From an implementation perspective, do we want to disable all the control  on the panel - or hide them for lesser confusion?

> Lastly, instead of adding a new row of buttons I'd suggest adding a lock icon toggle to the actions panel (like the group icon)

Makes sense, i only did that way cuz it was quick way for testing the  context. Will change it.

**Comment by dwelle** [comment]
> Makes sense, i only did that way cuz it was quick way for testing the context. Will change it.

I'm not sure if it isn't better to hide under contextmenu since this feature is not as common to warrant adding another UI button. Will need more discussion.

**Comment by borekb** [comment]
My main use case for locking is to **avoid selection**. For example, a bunch of objects is easy to select on a plain canvas but hard to select while inside / on top of another shape:

https://user-images.githubusercontent.com/101152/118806290-2b462a80-b8a7-11eb-92e7-970514281fab.mov

Locking of UI controls solves this, see e.g. [how Balsamiq does it](https://balsamiq.com/wireframes/confluence/docs/cloud/adding-controls/#locking-ui-controls).

**Comment by dwelle** [comment]
I agree this is a useful feature. For a start, we can add it under the contextMenu:

1. locking should prevent selection through all ways except when you 
	1. right-click on the element
	3. cmd/ctrl click on the element
	4. you select the group it's nested in
2. you can unlock by selecting it (see above) and using the contextMenu again

@borekb  That said, we should also add support for https://github.com/excalidraw/excalidraw/issues/3601 which will help with your use case as well.

**Comment by ad1992** [comment]
+1 for this feature, this will be useful. We can start with showing it under context menu as suggested by @dwelle.

**Comment by a-theriault** [comment]
Curious if this is on the roadmap for the near-ish future - I've hit this problem frequently with people moving large background color-layers instead of the item sitting on top, or having to traverse well outside their bounds to do large selections of multiple elements.

**Comment by a-theriault** [comment]
> If no one takes this on, we will implement it ourselves but I can't commit to a date as there are multiple in-progress or higher-priority tasks on excalidraw.com and plus.excalidraw.com roadmaps.

Totally understandable. I'm curious how the exceptions for 1. work -- since right clicking enables the menu, I'm guessing those exceptions occur if I then choose _unlock_. 

_Or_ is the idea that right-clicking would select the locked element _and_ show the menu with the option to unlock?

**Comment by dwelle** [comment]
Yes, I think we'll have to allow some actions even on the locked elements (such as contextMenu) to be able to unlock them in some apart, barring having a layers menu (list).

As such, all 3 exceptions listed above would be doable on locked elements. We might skip (ii) if it proves annoying.

**Comment by zsviczian** [comment]
A similar request was raised on the Obsidian-Excalidraw issue log. 
[#492](https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/492)

**Comment by zsviczian** [comment]
@dwelle, I'd be happy to take a stab at this, however, building on your comment from July 2020, I would rather approach this by creating some simple UI for layers. Having layers in Excalidraw would bring lots of other benefits as well (locking, changing visibility, setting opacity, etc)

Have you given layers any thought?

I would attempt to build a UI similar to the one in Sketchbook.

**Comment by dwelle** [comment]
@zsviczian support for layers is something we don't want to add to Excalidraw at the moment. We must be careful about adding too many features (especially like these) lest Excalidraw becomes too bloated/complex.

As for the contextmenu workflow, since selecting will more-or-less be able to be done only via contextmenu again (the ctrl/cmd-click notwithstanding, if we even allow that), I'd also not expose the lock button in the UI other than in the contextmenu itself so that users don't lock their elements without having any idea how to revert that.

**Comment by chipbite** [comment]
Hi! I just want to underline and clarify the use case that @borekb brings up, which is similar/ same as mine.

## General use case: Lock element/image to use as background for whiteboard
This can support specific use cases, like 
* the template initially mentioned - business canvas, kanban board, etc etc etc
* discussing a complex diagram - (this is mine) insert the reference view of some complex thing (as an svg, works great!!), and then lock it to have it as a backdrop. Participants brainstorm, add notes, etc on top. Very useful!

**Comment by tom-sherman** [comment]
Just wanted to add that https://www.tldraw.com/ has a great UX around locking and unlocking. It sounds very similar to what's described in https://github.com/excalidraw/excalidraw/issues/1976#issuecomment-844165742

**Comment by dwelle** [comment]
Thanks @tom-sherman for taking it up!

Some questions for all: should arrow binding work on locked elements?

**Comment by tom-sherman** [comment]
I think in general we should disable everything (within practical reason) for locked elements as an MVP, then think about re-enabling features on locked elements as follow-ups.

**Comment by chipbite** [comment]
> should arrow binding work on locked elements?

my two cents: 
for a template or image backdrop such as a kanban board or imported diagram image use case it would not be needed. in that case (kanban board) it would likely be in the way. 

if one could import a diagram from another format, that would be different, then one might want to be able to bind connectors/arrows between the locked imported diagram and the new content that is created during a meeting, say...

**Comment by zsviczian** [comment]
I agree with @tom-sherman, locking an element should disable everything.

**Comment by chipbite** [comment]
> needed for containers 👍

Hi @LRTRC! FYI: Locking has been implemented already. Right click and you will find the menu option to lock an element. 
This topic is closed.

**Comment by LRTRC** [comment]
@chipbite Oh, great news ! thank you very much for explaining it to me !
