### ISSUE TITLE
Feature: New Action - Reseed button

### ISSUE THREAD

**Issue by Jan-M** [excalidraw/excalidraw#1978]
I would like to be able to reseed for a selected shape.

Especially when drawing squared boxes some seeds give double lines that are obstructing.

Having a button to press (e.g. in Actions) would be nice to have

fa-recycle comes to mind.

![image](https://user-images.githubusercontent.com/1443395/88829369-c9f48400-d1cc-11ea-99f4-cb2633f62ac8.png)

Example
![image](https://user-images.githubusercontent.com/1443395/88829995-a67e0900-d1cd-11ea-90cd-958e1f9be9fc.png)

**Comment by dwelle** [comment]
I don't think adding a dedicated button for a low-level feature like this is the right way to go --- our guiding principle for Exalidraw is to get the defaults right, and offer limited customization for the rest.

If the behavior on the whole is suboptimal, we should address that instead. We haven't gotten complaints on this yet (apart from yours).

But I agree that there are cases where it would be handy. Whether it warrants a new feature is another matter. If this gets rejected, we could possibly add a shortcut for it, for those that really care.

**Comment by DennisSmolek** [comment]
For reseeding specifically one suggestion would be to reseed by default when you change to the "sloppiness" from architect to Artist or cartoonist.

As UX goes they have already significantly changed the line-style (which is already unique for every drawn shape) so I don't think the line being slightly different while toggling options would be startling.

Ultimately I think the real complaint is is the multi-stroke line or the roughness in general.

[draw.io](https://draw.io) which uses the same underlying library (rough.js) exposes wayyy more options but two things they did for this are 

1. added a "Comic Style" which turns down the "roughness" and sets the [disableMultiStroke](https://github.com/rough-stuff/rough/wiki#disablemultistroke) Parameter for a simpler effect.
2. exposes a toggle for the **disableMultiStroke** directly. 

_[(Article on how they use rough.js)](https://www.diagrams.net/blog/rough-style)_

Some quick simple options:

1. as excalidraw already has an artist and comic "sloppiness" level I'd consider one of them having **disableMultiStroke** set to true
2. Choose one of the existing levels (say cartoonist) and if the shape is cartoonist expose a new stroke style of "clean" which is just a toggle of the **disableMultiStroke** property

**Comment by Jan-M** [comment]
That was quick, probably already helpful enough, but also kind of hidden. Thanks.

**Comment by lipis** [comment]
I think we can close that one!
