### ISSUE TITLE
Free draw should ignore zoom

### ISSUE THREAD

**Issue by xixixao** [excalidraw/excalidraw#1981]
If you zoom in, you should be able to draw "fine" curves.

If you zoom out, you should be able to draw "course" curves.

But today, zoom is not ignored, so zooming in doesn't allow you draw a more finely detailed drawings.

**Comment by dwelle** [comment]
Agreed.

**Comment by wasp77** [comment]
@xixixao I would like to take a whack at this but I'm not exactly sure what is being asked for. Is the idea that when you zoom in the line width gets smaller and when you zoom out the line width gets larger? I'm just not sure what you mean by ignoring the zoom?

**Comment by dwelle** [comment]
@wasp77 no, the idea is to set the line simplifier threshold dynamically based on zoom:

https://github.com/excalidraw/excalidraw/blob/e4f429f1c1ba4fb49491840e55b3de80508eded8/src/components/App.tsx#L2889

**Comment by ReneCode** [comment]
PR is merged - I think that issue could be closed.
