### ISSUE TITLE
Prettier support

### ISSUE THREAD

**Issue by GasimGasimzada** [excalidraw/excalidraw#199]
Would you be interested in adding Prettier to the project?

**Comment by dwelle** [comment]
Prettier is already set up (see package.json).

**Comment by GasimGasimzada** [comment]
I was asking this because there is no prettier config file here. Is there a specific configuration that is preferred?

**Comment by dwelle** [comment]
AFAIK, we're using the default.

**Comment by GasimGasimzada** [comment]
Okay, that makes sense!
