### ISSUE TITLE
Is there a way to make the scene data persisted to the server?

### ISSUE THREAD

**Issue by JToward** [excalidraw/excalidraw#1991]
Is it possible to make the scene data persisted to the server and accessing it using the session link? This will ease the integration with other collaboration tools such as Jitsi Meet and Matrix.

**Comment by petehunt** [comment]
This was being tracked in #1878 and there's a PR for it in #2188

**Comment by ramalingamvarkala** [comment]
Can we integrate Excalidraw into jitsimeet?

**Comment by dwelle** [comment]
@ramalingamvarkala feel free yo make one, similar to the Jira plugin https://github.com/excalidraw/excalidraw/issues/1189

I'm gonna close this issue as resolved
