### ISSUE TITLE
Suggestion: Make wildcard domain on *.excalidraw.com and remove redirect on sharable links

### ISSUE THREAD

**Issue by ctdlspace** [excalidraw/excalidraw#1993]
This easy and quick solution will allow me to use excalidraw like

myproject-1.excalidraw.com
myproject-2.excalidraw.com
myproject-3.excalidraw.com

this will be very convenient for those who working on few  projects in parallel. 

And second suggestion is remove redirect from JSON sharable links this will make links easy to bookmark

example: somebody sends me the link
https://excalidraw.com/#json=bla

right after link was open i've got redirected https://excalidraw.com and can't bookmark it 

i do believe that this two solutions can be implemented in a single day but working with multiple projects will became much more effective

**Comment by dwelle** [comment]
1) Not sure I understand your use case. You want us to redirect *.excalidraw.com to excalidraw.com?
2) That likely won't happen until after we make json links permanent (updatable). Though, we could in theory remove the url only after you make a modification.
