### ISSUE TITLE
Line Editor shouldn't allow creating rotated two-point lines

### ISSUE THREAD

**Issue by dai-shi** [excalidraw/excalidraw#1994]
Currently, two-point lines must always be unrotated. (`angle=0`)
With Line Editor, we can techniically create a rotated two-point line, which leads to unexpected behaviors.
Cc @dwelle 

![excal80](https://user-images.githubusercontent.com/490574/89116955-9e2b1400-d4d4-11ea-994b-500f842cb2ba.gif)

**Comment by dai-shi** [comment]
Slightly related: #1673

**Comment by dwelle** [comment]
This is gonna be fun :)

**Comment by dai-shi** [comment]
If we go that path, I'd suggest normalizing two-point lines like this:
```js
{
  angle: angle, // variable
  points: [[0, 0], [width, 0]],
  width: width,
  height: 0,
}
```

But, this is going to be a big change. Rotation handle might not be very easy to grab for long lines.

I guess @vjeux is one of who take seriously about normalizing two point lines?

**Comment by vjeux** [comment]
That ship has sailed on my end, do whatever you feel is good :)

**Comment by dai-shi** [comment]
In that case, we can simply support `angle` for two-point lines. That would simplify things. (We give up normalization. We sort of did with diamonds and 45-degree-rotated rectangles.)

**Comment by dai-shi** [comment]
The ideal goal for DX is no `element.points.length === 2` checks.
However, this means we "resize" straight lines, so I don't think it's easy to implement shift-locking for straight lines, which is bad in UX.

Maybe, we just enable rotate handle for two-point lines for now.

**Comment by dai-shi** [comment]
Or, make the line editor prohibit deleting points less than three.

**Comment by dai-shi** [comment]
@dwelle What do you think?

**Comment by dwelle** [comment]
> Or, make the line editor prohibit deleting points less than three.

I wouldn't go that path as it's non-intuitive and prevents several use cases (e.g. you're toying with a 3-point line and decide you want to get rid of the middle point).

If we removed, it'd still just be a temp solution as I don't think we'd want to retain this arbitrary limitation. As such, let's just fix the problem at hand instead of hacking it further.

**Comment by dai-shi** [comment]
Three perspectives:
1. Should we keep normalizing two-point lines/arrows, or introduce `angle?
2. Is showing rotate handle for all two-point/arrows a bit weird?
3. Can we totally remove `element.points.length === 2` checks?

**Comment by dwelle** [comment]
> Should we keep normalizing two-point lines/arrows, or introduce `angle?
> [...]
> Can we totally remove element.points.length === 2 checks?
> [...]
> Is showing rotate handle for all two-point/arrows a bit weird?

I think this is the way to go. One ring to rule them all. You can check how the behavior/feel be like here: https://excalidraw.com/#json=5934494666194944,GQinJzlXGA4-d2_lkaPDLg

**Comment by dwelle** [comment]
One problem though: not sure what will happen with SHIFT angle locking of 2-point lines after that change. Wouldn't wanna give it up :(.

**Comment by dai-shi** [comment]
Exactly what I said in one of my previous comments. 😄 

----

https://excalidraw.com/#json=6031004795928576,J1agJhYLd6A0ELo81o9_fA
If we are ok with this rotate handle.

**Comment by dwelle** [comment]
> Exactly what I said in one of my previous comments. 

Missed/forgot :sweat_smile:, but I don't quite understand what you mean by:

> However, this means we "resize" straight lines, so I don't think it's easy to implement shift-locking for straight lines, which is bad in UX.

> If we are ok with this rotate handle.

I think it's fine. Comes with the territory.

**Comment by dai-shi** [comment]
I almost mean the same as what you said.
If we were removing the 2-point special logic, it would be impossible to implement SHIFT locking on resize. I thought it's "bad in UX", but I guess it's worth giving up. SHIFT locking can probably be implemented when creating a new line.

**Comment by dwelle** [comment]
I'm not sure we *have* to give it up if we retained the special 2-point logic just for the SHIFT locking. We'd have to account for rotation though.

**Comment by dai-shi** [comment]
What would you do if the line is already rotated? Does SHIFT locking base on the scene canvas or the rotated element?
If you added the special 2-point logic, you'd end up again with inconsistent behavior with rotating 2-point line and the equivalent 3-point straight line.

**Comment by dwelle** [comment]
I'd just move the edge point with respect to the scene so that it's positioned at a given angle (accounting for rotation so that the angle stays the same).

**Comment by dai-shi** [comment]
On second thought, I think we should not support SHIFT **angle** locking on resize handles at all.

- SHIFT locking on resize handle is used for width:height=1:1 for most shapes, and exception for 2-point lines is just confusing (UX, DX)
- You can't distinguish 2-point lines and 3-point straight lines, and the behavior should be the same (UX)

So, my proposition is we should support SHIFT angle locking in line editor, which is more intuitive and SHIFT locking on resize handle keep the same behavior for all shapes.

**Comment by dwelle** [comment]
> SHIFT locking on resize handle is used for width:height=1:1 for most shapes, and exception for 2-point lines is just confusing (UX, DX)

I've taken this under consideration and arrived at the fact that proportion scaling of 2-point lines doesn't make sense (and would work identical if you SHIFT-locked to the same angle you're trying to proportionally resize)

> You can't distinguish 2-point lines and 3-point straight lines, and the behavior should be the same (UX)

True, but that's somewhat of an edge case.

---

At least we should support SHIFT locking during creation of 2-point line (as you suggested above somewhere).

Either way, you make good points --- it's just that I think SHIFT locking for lines is very valuable. But I'm willing to let it go if it won't make sense anymore. We'll see what others think. /cc @vjeux @xixixao
