### ISSUE TITLE
Add Galician language

### ISSUE THREAD

**Issue by barcia** [excalidraw/excalidraw#1999]
Add galician language to Crowdin, and I can add galician locales.

**Comment by dwelle** [comment]
https://crowdin.com/translate/excalidraw/10/en-gl

How do you say Galician in Galician (for the language picker)?

**Comment by barcia** [comment]
Galego

**Comment by dwelle** [comment]
Thanks, added. Waiting for you translation!

**Comment by arponpes** [comment]
Hi! I would like to translate the app to Galician. I saw this issue was opened in the pass but I can not find the language to translate it in Crowdin. Can you review it? Thanks!
