### ISSUE TITLE
[TODO] Resize handles on elements

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#20]
So we can easily resize rectangles, circles... We shouldn't do it for text.

We need to make sure that if the element is small, we can still move it instead of resizing it. It's going to be an interesting UX challenge with the hit targets.

**Comment by dwelle** [comment]
On top of this, each shape should define where the handles should be placed (which could be implemented as part of https://github.com/excalidraw/excalibur/issues/9) --- specifically, the `arrow` shape should only define 2 nodes, which will allow to easily change the start/end positions.
