### ISSUE TITLE
Side handlers don't work on mobile

### ISSUE THREAD

**Issue by xixixao** [excalidraw/excalidraw#2000]
Try grabbing the side handlers (not corners) on mobile and drag them - it doesn't work.

**Comment by dai-shi** [comment]
Thanks for opening the issue. For me, it sometimes works, but very severe. Not sure how this happens, but there must be a bug somewhere.

**Comment by xixixao** [comment]
I can repro in Chrome using dev tools Device Toolbar with Responsive on and resolution 1216x800

**Comment by dai-shi** [comment]
You can repro Chrome on Desktop? Tried Responsive 1216x800, but I can't. I could repro on iPhone.

**Comment by dwelle** [comment]
Can repro on Android. Cannot repro on Chrome desktop devTools emulation.

**Comment by vjeux** [comment]
Fixed by #2459
