### ISSUE TITLE
add elbow arrow support

### ISSUE THREAD

**Issue by scottyan19** [excalidraw/excalidraw#2001]
excalidraw is a very beautiful tool, I used it for a while, and I found I need elbow arrow function very much, for now, I must combine a line and an arrow to simulate an elbow arrow,  it'll be very nice if you could add elbow arrow support, thank you ~

**Comment by dwelle** [comment]
Instead of click-dragging, use click+click+click workflow when creating arrows (check the hint message below the tools):

![excal_elbow_arrow](https://user-images.githubusercontent.com/5153846/89275125-20851680-d642-11ea-9588-2a20865abf81.gif)

**Comment by scottyan19** [comment]
> Instead of click-dragging, use click+click+click workflow when creating arrows (check the hint message below the tools):
> 
> ![excal_elbow_arrow](https://user-images.githubusercontent.com/5153846/89275125-20851680-d642-11ea-9588-2a20865abf81.gif)

thanks very much for your reply , I'm sorry I didn't make it very clear,  I know this way, and I mean a right-angle arrow,  the arc angle always make the image looks strange.

**Comment by scottyan19** [comment]
thanks very much for your reply , I'm sorry I didn't make it very clear, I know this way, and I mean a right-angle arrow, the arc angle always make the image looks strange.

**Comment by dai-shi** [comment]
Do you mean like this? #1931 
![excal88](https://user-images.githubusercontent.com/490574/89619499-001abd80-d8c9-11ea-8e09-f609097b84d8.gif)

**Comment by scottyan19** [comment]
yes! exactly what I need. thanks ~

**Comment by nrgapple** [comment]
@dai-shi Is that a setting or did you modify the code?

**Comment by dai-shi** [comment]
@nrgapple It's modified in #1931. Net yet merged. You can try Preview too.
