### ISSUE TITLE
Multipoint lines/arrows are not snapping to grid

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw#2009]

**Comment by dwelle** [comment]
Known and already tracked in https://github.com/excalidraw/excalidraw/issues/1810, but we haven't created a separate issue for it yet, yes.

**Comment by dai-shi** [comment]
It's about creating new elements, right? I think it's a good first issue because the goal is clear.

**Comment by dwelle** [comment]
@dai-shi didn't you mention in a PR it was hard/non-trivial? :P

**Comment by dai-shi** [comment]
Yeah, it wasn't seem to be changing a line or two... Nor structured like line editor. So, it would basically require more effort than other shapes. If it's left for a long time, I would probably take a look.

**Comment by mauriceLC92** [comment]
@dai-shi  Can this be assigned to me please?

**Comment by dai-shi** [comment]
Sure!

**Comment by mauriceLC92** [comment]
Thanks 👌

**Comment by mauriceLC92** [comment]
PR for this issue: https://github.com/excalidraw/excalidraw/pull/2113

**Comment by nawed2611** [comment]
Is this issue still open to work on?

**Comment by mauriceLC92** [comment]
@nawed2611 you welcome to work on it if it is. It's completely dropped off my radar.

**Comment by dwelle** [comment]
this is now fixed
