### ISSUE TITLE
Suggesting regarding structuring more elements

### ISSUE THREAD

**Issue by GasimGasimzada** [excalidraw/excalidraw#202]
If it is okay with you, I would like to spend a bit of time restructuring the application (e.g moving things around; things like that).

I have been thinking about how to make all the "scene" related functions more contained and I have a suggestion (I am wiling to work on it as I have some free time in my hands in the next couple of weeks):

- [x] All the functions that use `elements` array should accept `elements` as an argument instead of relying on the global variable. This will significantly increase compactness of the functions and it will make it much easier to group functions into separate modules.
- [x] Instead of using a global elements variable, create a function such as `createScene` that returns these elements; so that, we can use them within the scope of Application component. This will allow containing the scene within a specific scope.
- [x] Move all scene related functions into a separate directory consisting of multiple files. We can call this directory `scene` or something similar. For example, we can extract export functions to `scene/export.ts`, element related functions into `scene/elements`, and scrollbars into `scene/scrollbars.ts`.
- [x] Extract components into their own modules
- [x] Extract History functionality into its own modules

EDIT: Add history functionality

**Comment by GasimGasimzada** [comment]
I have tried to move things around in this PR: https://github.com/excalidraw/excalidraw/pull/204. I am very happy with the result because the important thing is that I removed global dependencies from all the functions (well, except for global constants such as `SCROLLBAR_MARGIN`).

**Comment by vjeux** [comment]
This is awesome, I commented on the PR, I’m also happy with the results but let’s land it in smaller chunks so we’re less likely to make errors in the process and if we do, it’s easier to localize.

**Comment by GasimGasimzada** [comment]
Refering PRs: #207 and #208
