### ISSUE TITLE
Consistent icons across the UI

### ISSUE THREAD

**Issue by tomfejer** [excalidraw/excalidraw#2020]
I love that not only the code is using great open source libraries but the UI as well.
As I was looking into the current icons used they are coming from font awesome, feather icons, storybook and there are a couple of custom ones.
I have a proposal to only use [feather icons](https://github.com/feathericons/feather). "Feather is a collection of simply beautiful open source icons." 
_(Additional icons were made by me.)_

![image](https://user-images.githubusercontent.com/24651781/89804350-5d667700-db34-11ea-85c7-2648845da74b.png)

<img width="430" alt="Feather with additional icons" src="https://user-images.githubusercontent.com/24651781/89804421-71aa7400-db34-11ea-85ba-ad1b2c030370.png">

👉 [CodeSandbox](https://codesandbox.io/s/awesome-rgb-m5bng?file=/src/components/icons.tsx)
👉 [DEMO](https://m5bng.csb.app/)

**Comment by dwelle** [comment]
I wanted to migrate to feather icons myself but was unsure whether it contained all necessary icons. Now it's clear it doesn't, but I agree that it's not hard to draw them up ourselves (I do it in my projects using Feather icons, too).

**Comment by xixixao** [comment]
Sweet. Couple nitpicks:

- For the draw icon I'd prefer a wysiwyg icon (see https://github.com/excalidraw/excalidraw/issues/1879).
- (really minor thing) For the text icon it seems weird it's serif font when our default is sans (but so is the current icon)
- The canvas clearing icon seems less clear than the current one, I'd probably stick with the bin (this is ok in your demo)
- The checkmark for color codes looks too big (this is ok in your demo)

Last and more importantly:
- Let's make sure it works well for Dark mode too (https://github.com/excalidraw/excalidraw/pull/2006) (don't see a major reason why it wouldn't)

The move to flat icons is interesting. I like your toggles for the component editor (per your screenshot), the current style is super unclear to me (in normal mode and in dark mode - I never know which one is selected).

**Comment by lipis** [comment]
I feel the same way for the drawing icon.. feels strange.

**Comment by lipis** [comment]
@tomfejer could you open a PR, so we could see this in action? We want consistent icons for sure and we could iterate and gather feedback from the PR.

**Comment by tomfejer** [comment]
@xixixao updated the draw icon to the default one from feather (edit-3). 
![image](https://user-images.githubusercontent.com/24651781/90126425-f0392880-dd63-11ea-96dd-b2e6ed7c3216.png)


@lipis link to PR #2024
