### ISSUE TITLE
For the Right-To-Left languages the zoom controls should be all the way to the right.

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw#2021]
<img width="1413" alt="Screenshot 2020-08-11 at 5 17 07 PM" src="https://user-images.githubusercontent.com/125676/89908385-7df70580-dbf6-11ea-8459-57f3489f7228.png">

**Comment by johann-sonntagbauer** [comment]
@lipis may I claim this issue?

**Comment by dwelle** [comment]
@johann-sonntagbauer you may indeed
