### ISSUE TITLE
dark mode: export preview & output color scheme

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#2026]
Should we either, both, or none?

- support toggling dark mode on preview canvas
- support toggling dark mode of exported image (PNG/SVG/clipboard...)

**Comment by xixixao** [comment]
I would do what I had in the PR, a toggle only in dark mode that preserves dark rendering, with default on. (I didn’t have the rendering fixed and so it was cut from the PR)

**Comment by inwardmovement** [comment]
As I see it, there would be a copy of the dark mode toggle in the export window.

By default (each time we open the exporter window) its state would be set on the canvas' dark mode toggle state. It would toggle the dark mode for the export preview and export file simultaneously, while not changing the canvas' dark mode toggle state, so that we can export in a mode but continue working on the same mode we were working on.

**Comment by dwelle** [comment]
I think we should keep the export theme set to `light` by default irrespective of your current theme — so that what you export stays consistent and isn't subject to the time-of-day.

If users want to export in dark mode, they'll need to switch to that mode manually in the export dialog. That way it's obvious what will be exported.

**Comment by dwelle** [comment]
Not sure what the best placement for the button is:

![image](https://user-images.githubusercontent.com/5153846/104726883-b3b79180-5734-11eb-8c76-4f5d7c016a65.png)

**Comment by mariusz-r** [comment]
I would go with the second, counting from the top.

**Comment by inwardmovement** [comment]
I would go with the second from the bottom.

**Comment by dwelle** [comment]
I'm with @mariusz-r — 2nd from top. It'll be more clear IMO. Only issue is we must make it small enough to not cover (or only slightly cover) the preview.

If anyone wants to take this issue, feel free.

**Comment by mrchief** [comment]
It'd also be helpful to support dark mode export for selection only. I often use a giant canvas for various drawings but I only want to exports parts of at time as individual images.

**Comment by dwelle** [comment]
That will come with the bundle :), no need for any extra setting/code.

**Comment by mrchief** [comment]
I was referring to right click context menu but I see the main export dialog has a "selection only" option so that'd work too.

**Comment by dwelle** [comment]
If you mean:

![image](https://user-images.githubusercontent.com/5153846/106194862-aaf0a200-61af-11eb-8c08-8c5245746069.png)

Then that should use the same settings that you set in the epxort dialog.

**Comment by mrchief** [comment]
Yes. 

> Then that should use the same settings that you set in the epxort dialog.

Little obscure for my taste but acceptable. :)

**Comment by mrchief** [comment]
Haven't thought of it actually. You raise good points though - we don't want to clutter the menu either with multiple entries (one regular, one dark) as that's just plain horrible. I can see the wisdom in the original decision now :)

**Comment by lipis** [comment]
What about just another option in the list with the checkboxes if you have dark mode on...? And if that's checked.. the copy to PNG will take dark as default..

**Comment by mrchief** [comment]
> What about just another option in the list with the checkboxes if you have dark mode on...? And if that's checked.. the copy to PNG will take dark as default..

I think you'll run out of real estate with this design pattern. I think it'd be simpler if it just respects the mode on the canvas - dark mode > exports dark mode; light mode > exports light mode

**Comment by lipis** [comment]
Yes.. the best design is no design..! I agree.. let's start with that option to respect the canvas mode and that's it.

**Comment by dwelle** [comment]
I disagree with coupling this to the canvas. Let me list all the reasons:

- Dark mode is often being toggled based on time of day (in the future, we may even support to automate this, or respect the system's current scheme if that will become available — note, this would likely be different from `
prefers-color-scheme`). I don't believe the exported color scheme should be based on time of the day.

	As an example: you're working on a blog post and exporting multiple images as you go along. Then, at 6pm you switch to dark mode, and suddenly what you export is in dark mode as well, so half of your blog post images are in light and half are in dark mode.

- If you work in dark mode, but want to export in light mode (and vice versa), you'd have to painfully switch modes just before you open the export dialog, and switch back when you close it, and always remember to do so. This is a terrible UX.

- If you're exporting via a keyboard shortcut (to clipboard) you don't even see what the scheme will be like, and if you're always exporting in one preferred scheme, it could suddenly change under you based on what canvas color scheme you're using at the moment — which would be unintuitive. In the future we may allow exporting back to the same file, etc., which would again make this workflow non-deterministic.

- New users won't have a clue that toggling dark mode will change the export scheme (does your printer start printing white on black when you switch your word processor to dark mode?). Whereas if we add a toggle button for the export, it'll be immediately obvious what it does when it changes just the export preview.

**Comment by mrchief** [comment]
> If you work in dark mode, but want to export in light mode (and vice versa), you'd have to painfully switch modes just before you open the export dialog, and switch back when you close it, and always remember to do so. This is a terrible UX.

Why is it painful to toggle a simple switch? I find changing options in MS Office painful as they are buried deep under several layers. Are we keeping the right perspective here?

> New users won't have a clue that toggling dark mode will change the export scheme (does your printer start printing white on black when you switch your word processor to dark mode?). Whereas if we add a toggle button for the export, it'll be immediately obvious what it does when it changes just the export preview.

Not sure I completely feel this will be the case. Excalidraw's UX has been pretty intuitive from get go and most newcomers were able to pick up concepts very easily on their own. Toggling the mode via canvas is just an extension of that. 

We can't have a solution that's 100% perfect and simple at the same time. There might be surprises the first few times but they would/should be fairly obvious and that's the UX goal here IMHO.

**Comment by dwelle** [comment]
> Why is it painful to toggle a simple switch? I find changing options in MS Office painful as they are buried deep under several layers. Are we keeping the right perspective here?

If flipping a switch isn't at all painful to you, you'll be pleased the proposed toggle will be right in the export dialog where you need it :heart:.

> Not sure I completely feel this will be the case. Excalidraw's UX has been pretty intuitive from get go and most newcomers were able to pick up concepts very easily on their own. Toggling the mode via canvas is just an extension of that.

My point exactly. We care deeply about UI and intuitiveness at Excalidraw, and making the exported color scheme be tied to UI color scheme is definitely not that.

Anyway, there needs to be a persuasive argument as to why (1) tying export settings to your UI settings is a good idea, and (2) why it's better to have export color-scheme toggle in the canvas-UI instead of in the export dialog where it matters most. Otherwise, we're gonna go with the toggle-in-export-dialog option.

**Comment by mrchief** [comment]
@dwelle the issues you raise was already discussed in the previous comments.

**Comment by dwelle** [comment]
We went with a separate toggle and we'll see how it goes.

fixed via https://github.com/excalidraw/excalidraw/pull/3046
