### ISSUE TITLE
Enable copying across different tab / Enable opening multiple .excalidraw file in a page

### ISSUE THREAD

**Issue by XingyuJin** [excalidraw/excalidraw#2034]
I would like to copy some component across different page and reuse them.

**Comment by dwelle** [comment]
- the copy/paste issue is tracked here https://github.com/excalidraw/excalidraw/issues/859 (I'll try to look at it soon) --- NOTE: while it seems that you can open several browser tabs, they share the same browser storage, so after you refresh the other tab, it'll show the same content as the next one.
- multiple tabs tracked in https://github.com/excalidraw/excalidraw/issues/1543
