### ISSUE TITLE
Support Vietnamese language

### ISSUE THREAD

**Issue by nguyenvanduocit** [excalidraw/excalidraw#2041]
I really like this project, and would like to contribute to it a translation in Vietnamese. Please add a language in Crowdin so I can start contributing.

**Comment by dwelle** [comment]
Here you go https://crowdin.com/translate/excalidraw/10/en-vi!

How do you say Vietnamese in Vietnamese for the language picker?

**Comment by nguyenvanduocit** [comment]
My bad, sorry about that.

**Comment by nguyenvanduocit** [comment]
Thanks.
Vietnamese: Tiếng Việt

**Comment by dwelle** [comment]
thanks
