### ISSUE TITLE
Support importing/exporting to GitHub Gist

### ISSUE THREAD

**Issue by aubelsb2** [excalidraw/excalidraw#2060]
Would be nice, especially if you can update previous gists. I think it would suit nicely when encryption isn't necessary.

**Comment by aubelsb2** [comment]
Yep. @lipis is right. Sorry @dwelle  I should have put more effort into the request.

**Comment by xixixao** [comment]
What is the advantage of this over our existing URL link export option?

**Comment by aubelsb2** [comment]
Manual modification. Version control. Easy sharing. Advanced sharing features. A channel for comments to get back. Ability to make revisions and fork. A cloud "account" to hold your drawings. (Potential for syncing later.)

**Comment by kbariotis** [comment]
> Manual modification. Version control. Easy sharing. Advanced sharing features. A channel for comments to get back. Ability to make revisions and fork. A cloud "account" to hold your drawings. (Potential for syncing later.)

My 2 cents:

- _Manual modification_: The object produced by Excalidraw is not designed to be human readable. I don't see how usable would it be for a person to actually go and edit it.
- _Version control_: That's sensible I think and a good feature to have (but maybe not the right approach)
- _A cloud "account"_: That's also sensible but agaain maybe not the right approach

**If I may go off topic for a bit though**, I would say that a good discussion would be how to make that object actually human readable/editable. I think we've discussed before an approach similar to http://mermaid-js.github.io/mermaid/.

**Comment by lipis** [comment]
I think it's out of scope supporting more backends at this point.
