### ISSUE TITLE
Unexpected de-selection with bound multi-line arrow

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#2062]
Repro:
- Create a multi-line arrow
- Create a rectangle that is bound to the arrow
- Double click on the multi-line arrow to edit it
- Move the end of the arrow to be bound
- Click on the rectangle

Expected behavior:
- It selects the rectangle

Current behavior:
- It selects the rectangle and then unselects it

![ezgif-4-091d9162a236](https://user-images.githubusercontent.com/197597/90964418-32a1ea00-e475-11ea-8083-29a5be837a01.gif)

**Comment by Jnforja** [comment]
Hey! Can I give this a shot?

**Comment by dwelle** [comment]
Sure thing. But probably wait until https://github.com/excalidraw/excalidraw/pull/2093 is merged before writing tests for it. I'll try to merge it very soon (wanna do one small rename).

**Comment by Jnforja** [comment]
> Sure thing. But probably wait until #2093 is merged before writing tests for it. I'll try to merge it very soon (wanna do one small rename).

Ok! I'll keep that mind :)
