### ISSUE TITLE
Multi-line hint is cropping part of text

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#2063]
![image](https://user-images.githubusercontent.com/197597/90964510-1ce0f480-e476-11ea-9165-7631eac95163.png)

See the bottom of the "p" on the first line.

To see it, resize a rectangle.

**Comment by O4epegb** [comment]
It is possible to avoid cropping by adding another wrapper span around the text, but it still looks a little bit ugly. See how `hold` word does not have padding on the left or padding suddenly ends after `resizing,`.

<img width="461" alt="Screenshot 2020-08-24 at 13 55 47" src="https://user-images.githubusercontent.com/12836237/91037365-906b3900-e611-11ea-8375-ae48eea9e716.png">

Not quite sure if it is possible to fix it.

There are 2 other solutions, remove background all together or add background to `.HintViewer` directly like so:

<img width="467" alt="Screenshot 2020-08-24 at 13 55 03" src="https://user-images.githubusercontent.com/12836237/91037597-f3f56680-e611-11ea-9c5f-3c0648b0b80e.png">

I could make PR with any of this options :)

**Comment by dwelle** [comment]
The padding issue is present even in current solution.

Another fix is setting `line-height` to `1.7`+:

![image](https://user-images.githubusercontent.com/5153846/91039858-99f2a200-e60d-11ea-92d8-a490ab01fce5.png)

**Comment by dwelle** [comment]
So the decision should be between:

(1)

 ![image](https://user-images.githubusercontent.com/5153846/91040379-6ebc8280-e60e-11ea-9418-3505521ba8ab.png)

(2)

![image](https://user-images.githubusercontent.com/5153846/91040390-75e39080-e60e-11ea-8113-657f3f0b56f4.png)

**Comment by O4epegb** [comment]
`line-height` looks weird, too much space between lines, in my opinion. `span` wrapper is better (my first example).

**Comment by dwelle** [comment]
You can open a PR with what you think looks best and others can chime in there.

**Comment by xixixao** [comment]
Mentioned in #1990
