### ISSUE TITLE
Pinch zooming while typing text breaks the UI on Chrome Mac OS X

### ISSUE THREAD

**Issue by pedropb** [excalidraw/excalidraw#2075]
**Affected browser:**
- Chrome Mac OS X

**Steps to reproduce:**
1. double click on canvas to insert text
2. hover over the text (make sure to have the select text cursor)
3. use pinch zoom to zoom in
4. note that you no longer can see the toolbar and the zoom functionality is now broken.

![Kapture 2020-08-24 at 23 12 29](https://user-images.githubusercontent.com/15254163/91129748-617bb400-e65f-11ea-95ab-eeef4604aae0.gif)

**Comment by dwelle** [comment]
Should we keep this open for Safari? Also, does it affect both iOS and desktop?

**Comment by pedropb** [comment]
The issue described on #2075 does not happen on Safari iOS. Interestingly enough, excalidraw behaves much better on iOS version of Safari than the Desktop one.

On Chrome iOS, the wysiwg text is also behaving poorly: the pinch zoom gesture seems to be captured as a secondary click event, instead.

I'll see if I can reliably reproduce the problems and open up a new issue to fix the text wysiwg for multiple browsers. What do you think @dwelle ?

**Comment by dwelle** [comment]
@pedropb sounds good!
