### ISSUE TITLE
Add Romanian language

### ISSUE THREAD

**Issue by ExTranslate1** [excalidraw/excalidraw#2091]
Please add Romanian language to Crowdin, in order to translate. I apologise for reposting this, but it seems the original request has simply vanished.

**Comment by dwelle** [comment]
Here you go: https://crowdin.com/translate/excalidraw/10/en-ro

How do you say "Romanian" in Romanian, for the language picker?

**Comment by ExTranslate1** [comment]
Română

**Comment by dwelle** [comment]
Thanks.
