### ISSUE TITLE
[TODO] z-index support

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#21]
Need at bare minimum a way to do send to back, move to front.

**Comment by vjeux** [comment]
It's surprisingly useful and annoying when not present

**Comment by nanot1m** [comment]
Can two elements have the same z-index?

**Comment by vjeux** [comment]
The way to implement it in a concrete way is to reorder elements in the list. The ones that are last are drawn on-top of the others. Bring to front moves the element at the end of the array. Send to back moves it at the beginning

**Comment by vjeux** [comment]
Fixed by #98, #99, #100 and #101
