### ISSUE TITLE
Copy an element by holding the cmd/ctrl key

### ISSUE THREAD

**Issue by mani-ramaswamy** [excalidraw/excalidraw#2100]
In Office, one can copy an element by just holding the cmd/ctrl key and dragging it to some other place in the canvas. While cmd-c and then dragging can get the same thing done, it is easier if the former approach was also supported.

**Comment by dwelle** [comment]
Hey. We support this as well, except not via Cmd-drag but via Alt-drag, which is the more common variant among vector editors. Bonus in our application is you can press/release the Alt anytime during drag and it still (permanently) duplicates the dragging element.

Again, you can find this shortcut in our shortcut dialog.

![image](https://user-images.githubusercontent.com/5153846/91633442-92a20e80-e9e8-11ea-9093-c9cf0f7c20d5.png)

![image](https://user-images.githubusercontent.com/5153846/91633434-81f19880-e9e8-11ea-84a1-745433dcad6b.png)
