### ISSUE TITLE
Grid lines

### ISSUE THREAD

**Issue by mani-ramaswamy** [excalidraw/excalidraw#2101]
I am using this tool for so many doodles and quick diagrams!  One thing I occasionally need is alignment, so if we can also get some gridlines or points, that'd be great.

**Comment by dwelle** [comment]
Hello. Grid is already supported, except it's somewhat hidden at the moment.

You can either right-click to invoke contextmenu:

![image](https://user-images.githubusercontent.com/5153846/91633221-d1cf6000-e9e6-11ea-90d8-86f86606b776.png)

Or you can use a shortcut `Cmd/ctrl+'`. Check all (well, most) of the keyboard shortcuts here:

![image](https://user-images.githubusercontent.com/5153846/91633242-f75c6980-e9e6-11ea-9a27-336bbc0f1cbb.png)
