### ISSUE TITLE
moving arrow via keyboard should rebind

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#2103]
Moving an arrow via arrow keys should unbind/bind based on proximity to bindable elements.

![excal_bug_moving_arrow_should_unbind](https://user-images.githubusercontent.com/5153846/91636957-f4707180-ea04-11ea-917f-4bf420bc8cad.gif)

**Comment by Jnforja** [comment]
Hi! Mind if I take a shot at this?

**Comment by dwelle** [comment]
Go ahead!
