### ISSUE TITLE
Enhancement: Parallelogram

### ISSUE THREAD

**Issue by defint** [excalidraw/excalidraw#2111]
As a block-scheme master, I need to have a parallelogram to create schematic input data.

<img width="415" alt="Screenshot 2020-08-30 at 10 53 25" src="https://user-images.githubusercontent.com/1523848/91654121-0a3a7100-eaaf-11ea-99fe-7d1c5ded93dc.png">

Do we have this possibility on the excalidraw?
If not we can add an additional point on the rectangle to configure the tilt angle (the orange point on the screen below).

<img width="402" alt="Screenshot 2020-08-30 at 11 02 43" src="https://user-images.githubusercontent.com/1523848/91654313-576b1280-eab0-11ea-9fc1-d7e7ac035195.png">

**Comment by dai-shi** [comment]
What we can do now is this: https://excalidraw.com/#json=5647891951517696,f4xx9ivsDt2jMStnfw2VGg

![image](https://user-images.githubusercontent.com/490574/91654502-36bcb000-eae4-11ea-9cec-8f7ee22897ae.png)

**Comment by dwelle** [comment]
It's possible to create it via lines (with sharp conerners): https://excalidraw.com/#json=6325810277384192,qba6KkIlHPLJMq2xFg09gw

You can then add this shape to your library and use it in other diagrams.

**Comment by defint** [comment]
Looks usable, thanks.
I think this shape should be added to the community prebuilt common library (https://github.com/excalidraw/excalidraw/issues/1923).
But this topic can be closed.

**Comment by Sandwich1699975** [comment]
> https://excalidraw.com/#json=5647891951517696,f4xx9ivsDt2jMStnfw2VGg

Note that this may overwrite your entire series of tabs that have an Excalidraw project open
