### ISSUE TITLE
When double click on an object insert the text in the middle of it

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw#2133]
As it's happening when pressing enter. (hidden feaure)

**Comment by dwelle** [comment]
I think we want to reserve the doubleclick-on-object behavior for future in case we add support for editing shapes points same as we do with lines.

**Comment by lipis** [comment]
and endup with strange shapes? Wasn't aware of that and not sure I like the idea :) Arbitrary shapes can be done with lines now :)

**Comment by dwelle** [comment]
IMO it would serve 2 purposes:

1. Make it more general and intuitive. If there's no conceptual reason not to allow doing so, then why limit users.
2. Simplifying implementation. Do not differentiate between shapes that could in theory be identical. /cc @daishi

Current behavior:

![image](https://user-images.githubusercontent.com/5153846/92109718-cf577680-ede9-11ea-8b8d-5808acd10ed3.png)

**Comment by lipis** [comment]
hmm.. Not sure if that's desirable for most users.. I think having our primitive shapes unaffected it's not a bad idea. If somoene wants to draw a rectangle they won't choose the line IMO

**Comment by dai-shi** [comment]
On first thought, I'm not sure if it simplifies the implementation.

btw, we do have double click on a rectangle to insert a text in the middle, right?

**Comment by dwelle** [comment]
> Not sure if that's desirable for most users.. I think having our primitive shapes unaffected it's not a bad idea. If somoene wants to draw a rectangle they won't choose the line IMO

It's not about primitives, rather expectations of what you can do with them. There's nothing that says "if you create a rectangle, you can't edit it".

If you end up with several similarly looking shapes on your scene, you don't want to be surprised by different behaviors that you can do with them. In the above image, double-clicking on the top element currently creates text. Double-cliking on the bottom one edits it. Why? What's the difference? How does user know when looking at the scene which shape is which?
