### ISSUE TITLE
Typo in docker-compose file?

### ISSUE THREAD

**Issue by O4epegb** [excalidraw/excalidraw#2136]
So there is docker-compose file with volumes section:

```
    volumes:
      - ./:/opt/node_app/app:delegated
      - ./package.json:/opt/node_app/package.json
      - ./package-lock.lock:/opt/node_app/package-lock.lock
      - notused:/opt/node_app/app/node_modules
```

Is `package-lock.lock` a typo or not? Because npm lock file actually called `package-lock.json`.

**Comment by lipis** [comment]
looks like a typo @kbariotis

**Comment by reymon359** [comment]
Hi there! [I submitted a Pull Request to fix it ](https://github.com/excalidraw/excalidraw/pull/2162). 

I hope it helps to close this!
