### ISSUE TITLE
nepali language

### ISSUE THREAD

**Issue by ashiskharel** [excalidraw/excalidraw#2137]
Would like to request to include nepali language which is similar to hindi script which is devanagari. However, there are many differences in the way it's written.

**Comment by dwelle** [comment]
Here: https://crowdin.com/translate/excalidraw/10/en-nenp?filter=basic&value=0

How do you say "Nepali" in Nepali, for the language picker?

**Comment by lipis** [comment]
नेपाली

**Comment by ashiskharel** [comment]
Thanks @lipis
