### ISSUE TITLE
"Couldn't create shareable link" error

### ISSUE THREAD

**Issue by lachenmayer** [excalidraw/excalidraw#2143]
Hi folks, loving Excalidraw!

When trying to create a shareable link using the 🔗 button in the export menu, I get a dialog box telling me "Couldn't create shareable link" instead of a shareable link.

In the console, I see a failed `POST` to `https://json.excalidraw.com/api/v2/post/`, which fails with a 500 and the following response:

```json
{"description":"Internal Server Error","error_class":"OverQuotaError","error_code":500,"error_message":"Internal Server Error","error_name":"internal-server-error","status":"error"}
```

Looks like it might just be a victim of its own success, just wanted to raise it so you're aware.

Nice one, thanks a lot!

**Comment by vjeux** [comment]
Sorry about this, the free tier ran out and the credit card was expired. This should be up and running again.
