### ISSUE TITLE
Bug : Cannot save canvas 

### ISSUE THREAD

**Issue by ajubin** [excalidraw/excalidraw#2144]
## Description

On the website, when I want to save my drawing, I've got the following error in the console and nothing happens. 

When I clear app cache or in an incognito tab, I've still got the same issue. 

On chrome canary, I don't have the bug.

It has worked for some times
I can open existing file.
Not sure if it's related but I tried to install the app with the "+" icon and then deleted it

## Error in console

```
instrument.ts:128 
TypeError: Failed to execute 'chooseFileSystemEntries' on 'Window': The provided value 'save-file' is not a valid enum value of type ChooseFileSystemEntriesType.
    at file-save.mjs:2
    at c (runtime.js:63)
    at Generator._invoke (runtime.js:293)
    at Generator.next (runtime.js:118)
    at r (asyncToGenerator.js:3)
    at u (asyncToGenerator.js:25)
    at asyncToGenerator.js:32
    at new Promise (<anonymous>)
    at Module.<anonymous> (asyncToGenerator.js:21)
    at Module.default (file-save.mjs:2)
    at file-save.mjs:2
    at c (runtime.js:63)
    at Generator._invoke (runtime.js:293)
    at Generator.next (runtime.js:118)
    at r (asyncToGenerator.js:3)
    at u (asyncToGenerator.js:25)
```

## Chrome version

```
Google Chrome | 80.0.3987.132 (Official Build) (64-bit)
-- | --
Revision | fcea73228632975e052eb90fcf6cd1752d3b42b4-refs/branch-heads/3987@{#974}
OS | macOS Version 10.15.5 (Build 19F101)
JavaScript | V8 8.0.426.26
Flash | 32.0.0.414 /Users/antoinejubin/Library/Application Support/Google/Chrome/PepperFlash/32.0.0.414/PepperFlashPlayer.plugin
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.132 Safari/537.36
Command Line | /Applications/Google Chrome.app/Contents/MacOS/Google Chrome --flag-switches-begin --enable-experimental-web-platform-features --enable-features=TabGroups --flag-switches-end --enable-audio-service-sandbox --origin-trial-disabled-features=MeasureMemory
```

**Comment by salehmoh** [comment]
Can you check `chrome://apps` to see if excalidraw is still there?

**Comment by dwelle** [comment]
Try updating to latest Chrome 86. If you can still reproduce the error, lemme know.

**Comment by ajubin** [comment]
> Can you check `chrome://apps` to see if excalidraw is still there?
> 
> For what it's worth, it worked fine on my end (on Windows). I wasn't able to reproduce the bug.

excalidraw is not there

**Comment by ajubin** [comment]
> Try updating to latest Chrome 86. If you can still reproduce the error, lemme know.

I'm now to chrome 85 and still got the issue.

If I use safari, I've got no problem

**Comment by dwelle** [comment]
Try upgrading to 86 which is currently the latest version. That should fix it. (I'm surprised that on 85 it tries to use the new filesystem API and doesn't fall back to legacy).
