### ISSUE TITLE
Swedish translation

### ISSUE THREAD

**Issue by nilsjonsson** [excalidraw/excalidraw#2153]
Hi, I'd like to help translate the project to swedish, since it's my native tongue.

**Comment by nilsjonsson** [comment]
...and by opening this issue I would like someone to add Swedish(sv-SE) to the crowdin page.
:)

**Comment by dwelle** [comment]
Sorry, it got lost in the translation :). https://crowdin.com/translate/excalidraw/10/en-sv

How do you say "Swedish" in Swedish for the language picker?

**Comment by nilsjonsson** [comment]
"Svenska"

Thanks, will begin translating :)

**Comment by lipis** [comment]
Should be live soon :)

**Comment by nilsjonsson** [comment]
Awesome! 👍

**Comment by lipis** [comment]
If you notice something is wrong.. you can always update it in Crowdin and we'll get the changes automatically!
