### ISSUE TITLE
Encounters an error whenever Export is clicked in Firefox 80.0.1 (macOS)

### ISSUE THREAD

**Issue by jjclxrk** [excalidraw/excalidraw#2156]
The scene can be exported when it is loaded in Chrome however.

<img width="756" alt="Screen Shot 2020-09-12 at 3 17 42 pm" src="https://user-images.githubusercontent.com/37681031/92988012-29072180-f50b-11ea-84a2-c8f48af98300.png">

### Scene content
Content is too long. A file is attached.
[week6-solutions.excalidraw.zip](https://github.com/excalidraw/excalidraw/files/5212223/week6-solutions.excalidraw.zip)

### Sentry Error ID

486bb8b86afe43ce89141d6c8ceac727

**Comment by dwelle** [comment]
Can't repro on FF 80 Windows. The Sentry Error ID doesn't match anything in our Sentry log, which is super weird.

Is it happening right when you click on this button?

![image](https://user-images.githubusercontent.com/5153846/92990923-59859600-f4e0-11ea-9866-868354ff98f9.png)

If you can still reproduce it, can you copy the error stack trace from the console?

**Comment by jjclxrk** [comment]
Yeah, it happens immediately after clicking that button.

Opening the console, it seems I'm getting a bunch of CORS and ServiceWorker related errors. The following errors occur just opening excalidraw.com:
```
Failed to register/update a ServiceWorker for scope ‘https://excalidraw.com/’: Storage access is restricted in this context due to user settings or private browsing mode. serviceWorker.tsx:64:5

Error during service worker registration: DOMException: The operation is insecure. instrument.ts:128:35

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://sentry.io/api/5179260/store/?sentry_key=7bfc596a5bf945eda6b660d3015a5460&sentry_version=7. (Reason: CORS request did not succeed).
```
But I don't get any of those errors if I open the page in a Private browser. And I get the same error if I try to export the file from the private window, so maybe they are irrelevant?


```
window.__EXCALIDRAW_SHA__
"6ea9f2dde46453a6c1cbf073dc8e42bfbbc05d8e"
```

```
Exception
columnNumber: 0
data: null
filename: "https://excalidraw.com/static/js/main.508b7269.chunk.js"
lineNumber: 1
message: ""
name: "NS_ERROR_FAILURE"
result: 2147500037
stack: "Za@https://excalidraw.com/static/js/main.508b7269.chunk.js:1:78217\nno@https://excalidraw.com/static/js/main.508b7269.chunk.js:1:84614\nVl/<@https://excalidraw.com/static/js/main.508b7269.chunk.js:1:179891\nou@https://excalidraw.com/static/js/5.672452cb.chunk.js:2:168949\nyl@https://excalidraw.com/static/js/5.672452cb.chunk.js:2:188090\nt.unstable_runWithPriority@https://excalidraw.com/static/js/5.672452cb.chunk.js:2:206407\nBo@https://excalidraw.com/static/js/5.672452cb.chunk.js:2:130536\nvl@https://excalidraw.com/static/js/5.672452cb.chunk.js:2:187847\nhl/<@https://excalidraw.com/static/js/5.672452cb.chunk.js:2:187758\nA@https://excalidraw.com/static/js/5.672452cb.chunk.js:2:205346\nx.port1.onmessage@https://excalidraw.com/static/js/5.672452cb.chunk.js:2:204102\nEventHandlerNonNull*@https://excalidraw.com/static/js/5.672452cb.chunk.js:2:204026\nf@https://excalidraw.com/:1:561\n@https://excalidraw.com/static/js/5.672452cb.chunk.js:2:202521\nf@https://excalidraw.com/:1:561\n@https://excalidraw.com/static/js/5.672452cb.chunk.js:2:85416\nf@https://excalidraw.com/:1:561\n@https://excalidraw.com/static/js/5.672452cb.chunk.js:2:16169\nf@https://excalidraw.com/:1:561\n@https://excalidraw.com/static/js/main.508b7269.chunk.js:1:9017\nf@https://excalidraw.com/:1:561\n@https://excalidraw.com/static/js/main.508b7269.chunk.js:1:8551\nf@https://excalidraw.com/:1:561\nt@https://excalidraw.com/:1:430\nr@https://excalidraw.com/:1:293\n@https://excalidraw.com/static/js/main.508b7269.chunk.js:1:63\n"
```

**Comment by lipis** [comment]
Is that still an issue?! Can't reproduce it on macOS. Please report back and we'll repopen if needed.

**Comment by jjclxrk** [comment]
This actually just happened again. This time with Firefox 81.0.2, and different scene content.

```
The error with identifier c2850f807ce54525941053279eb0a266 was tracked on our system.
```

Here is the scene content that is causing the error. It is only occurring with rather large amounts of content, I can use the site with no issues with smaller scenes.
[week11-solutions.excalidraw.zip](https://github.com/excalidraw/excalidraw/files/5427606/week11-solutions.excalidraw.zip)

**Comment by dwelle** [comment]
Ok, can repro. This is caused by too large canvas. Sadly there's nothing we can do apart from displaying better error message. There's an open PR for that: #1256 

Note: I couldn't repro using the supplied file, but can repro e.g. on this extra-wide scene: https://excalidraw.com/#json=5084521158410240,Jsxb_oPkjtadjnylRVC-Ww
