### ISSUE TITLE
resize window does not keep the originX - depends on the zoom factor

### ISSUE THREAD

**Issue by ReneCode** [excalidraw/excalidraw#2163]
When resizing the window the origin should be fixed on the same screen position. Unfortunately this only works on zoom=100%.

![ezgif-2-14b92f51c590](https://user-images.githubusercontent.com/1595098/93102795-1b3cd200-f6ac-11ea-9ed2-e2b0830959ec.gif)

**Comment by ReneCode** [comment]
oh, that appState.scrollXY value seems to be sometimes:
* in sceneCoords (used in viewportCoordsToScreeneCoords)
```
  // utils.ts
  const clientXWithZoom =
    zoomOrigin.x +
    (clientX - zoomOrigin.x - appState.offsetLeft) / appState.zoom;
  const x = clientXWithZoom - appState.scrollX;
  return { x, y };
````
* in viewportCoords (used in renderScene)
```
  // App.tsx
  renderScrene(.... { scrollX: this.state.scrollX .... } ... )

  // renderScene
  context.translate(-sceneState.scrollX, -sceneState.scrollY);
```

or do I miss something ?

refactoring - as discussed in issue #940 would fix it.

**Comment by dwelle** [comment]
It's a mess, I couldn't even tell you if `appState.scrollX/Y` should be in viewport or scene coords (I'm surprised it works if we're mixing the two). If we don't fully enforce the types via TS we should at least rename all coords variables to explicitly contain whether it's in viewport or scene coords. I was doing it here and there, but didn't get to full codebase refactor yet.

**Comment by ReneCode** [comment]
@Jnforja thank you very much for solving that issue.

**Comment by Jnforja** [comment]
My pleasure to help 😁
