### ISSUE TITLE
Use classnames package instead of template strings

### ISSUE THREAD

**Issue by O4epegb** [excalidraw/excalidraw#2167]
Is that a good idea to start using `classnames` package (only 650 bytes minified) or something similar?

I saw some places where classes render in html as `false` or `undefined` (no big downsides but it tickles my OCD), like that:

<img width="350" alt="Screenshot 2020-09-17 at 12 34 31" src="https://user-images.githubusercontent.com/12836237/93453336-3abd4000-f8e2-11ea-945b-67acf44b0b0b.png">

and this type of code looks a little bit messy:

```
        className={`ToolIcon_type_button ${
          !props.hidden ? "ToolIcon" : ""
        } ${sizeCn}${props.selected ? " ToolIcon--selected" : ""} ${
          props.className
        } ${
          props.visible && !props.hidden
            ? "ToolIcon_type_button--show"
            : "ToolIcon_type_button--hide"
        }`}
```

If that's a good idea I could make PR and refactor all template string classes to `classnames()`

**Comment by lipis** [comment]
Class name should not have `false` or `undefined`.. :) I think it's a good idea.. what do you think @dwelle?

**Comment by dwelle** [comment]
Yeah, why not. There's even a smaller alternative btw: https://bundlephobia.com/result?p=clsx@1.1.1

**Comment by lipis** [comment]
@O4epegb go for it!
