### ISSUE TITLE
Support layers (list)

### ISSUE THREAD

**Issue by ubitux** [excalidraw/excalidraw#2170]
Excalidraw currently allows object grouping and layering orders. Going one step further would be to give access to the list of all the objects, and give the ability to (re)name them. This would be similar to the object list tree in Inkscape, where you can rename, reorder, group/ungroup, convert group into layers, etc.

![2020-09-20-141335-eigh8Rie](https://user-images.githubusercontent.com/34467/93711079-86beed80-fb4b-11ea-94e5-6e90bae7e771.png)

The reason I'm requesting this feature is that I currently have the following flow:
1. make the diagram in Excalidraw and export it in SVG
2. import the SVG in Inkscape where I rename (and convert to layer) group/objects to identify them
3. animate the objects/layers in Sozi

I would like to get rid of the Inkscape step in the workflow for several reasons:
1. its role is redundant with Excalidraw (but somehow I have more hope into having the missing Inkscape features into Excalidraw than the other way around)
2. Inkscape object editor is particularly buggy
3. the Inkscape intermediate step makes it impossible to adjust the drawing from Excalidraw again if I notice an issue during the animation
4. Using Inkscape only for naming objects is overkill

The access and control on the object list in Excalidraw still won't make it possible to get rid of Inkscape entirely in that flow (mainly because of https://github.com/excalidraw/excalidraw/issues/19), but it would be a huge step forward anyway.

Though, I'm not sure how that feature would fit into the vision of the development of Excalidraw, and where the project has to draw a line in the feature creep...

**Comment by dwelle** [comment]
Yea, layers idea was tossed around, but current consensus is (I believe) it doesn't fit into the UI simplicity principle of Excalidraw.

We'll see.

**Comment by lipis** [comment]
Yeah, not sure if it's proper to introduce something that _complicated_ into Excalidraw. The feature and use case is definitely useful and handy for many reasons. Maybe we can introduce some hidden features for nerds.. that will open only with a shortcut on desktop (as on mobile this is not going to be that easily done).

**Comment by lipis** [comment]
It doesn't fit in our simplistic UI :)

**Comment by ricky11** [comment]
How would i then select a background element that is locked? I cant find an easy way to select something underneath.

**Comment by subfuzion** [comment]
Simple, but not simplistic, should be the goal. Exposing support for layers with one more tool on the toolbar doesn't have to be an orthogonal goal, especially if it's exposed as a pro feature -- one that I, and I'm sure others, would gladly pay extra for. A simplistic UI doesn't compensate for the additional complexity created by not being able to work with layers. A layers feature supports so many different use cases, such as being able to show or hide different layers while walking through a system diagram (as just one example). I would literally be willing to pay a 50% premium over my current subscription for this single feature.
