### ISSUE TITLE
Support lines and figures animations

### ISSUE THREAD

**Issue by DmitrySoshnikov** [excalidraw/excalidraw#218]
I use Keynote and other tools for my lectures, and find using animations very valuable to show dynamics, how objects transit or created in a complex system. 

Would be great having the animations for the figures and lines connecting them. Example: a line draws a block figure, hachures the background, draws the connection line, going to the second block. This would be not a static image mode, but rather a presentation mode.

**Comment by pshihn** [comment]
See https://observablehq.com/@matthewturk/path-interpolation-roughjs 
One could use this same technique for creating such animation

**Comment by DmitrySoshnikov** [comment]
@pshihn: yeah, that's exactly what I mean -- with configurable timing, etc.

**Comment by vjeux** [comment]
Wahhh, this demo is so cool!

**Comment by lipis** [comment]
I think this is outside of our scope for Excalidraw.. at least for now.
