### ISSUE TITLE
Possibility of hexagon shape

### ISSUE THREAD

**Issue by ThingsTom** [excalidraw/excalidraw#2180]
Loving the tool! Can we have support for a hexagonal shape and my life will be complete ;-)

**Comment by dwelle** [comment]
Just draw some hexagons, add the to the library, and reuse: https://excalidraw.com/#json=5698362649083904,VEObfBmrJ9kKTyi3W8kUug

Anyway, this is a duplicate of https://github.com/excalidraw/excalidraw/issues/366
