### ISSUE TITLE
Size Option in Export Dialogue Confusing

### ISSUE THREAD

**Issue by malcolmbastien** [excalidraw/excalidraw#2183]
(Following up on Twitter request to file an issue)

The three buttons in the export dialogue of "x1", "x2", and "x3" don't clearly indicate that you are changing the size of the export. There is no tooltip, and on a canvas with some objects in it, the export preview doesn't change size either. The confusing part for me personally was that the only effect I saw was the apparent quality of the preview render changed, which lead me to have an incorrect assumption about what those buttons did.

![image](https://user-images.githubusercontent.com/62178/93933874-4d73b280-fcf0-11ea-8783-884078b8b31e.png)

**Comment by lipis** [comment]
Maybe we can even have this tooltip showing the exact size of the export PNG, for example: `Exported size will be 1024x256 pixels`. (Just an idea)

**Comment by dawneraq** [comment]
I'd like to pick this up, with 2 ideas.

1. I would start the tooltip with a verb, like `Scale 2x (1024x256)`, to match the other tooltips (e.g. `Export to PNG`, `Get shareable link`)

2. The scale number and the "x" should switch places. 1x/2x/etc is the convention as far as I know:
    - https://helpx.adobe.com/photoshop/using/export-artboards-layers.html#Exportfilesindifferentsizes
    - https://developer.apple.com/design/human-interface-guidelines/ios/icons-and-images/image-size-and-resolution/

**Comment by dwelle** [comment]
Sounds good!
