### ISSUE TITLE
load-balancing and session persistence

### ISSUE THREAD

**Issue by thecloudgarage** [excalidraw/excalidraw#2185]
What is the recommended way to manage session persistence while running multiple instances of excalidraw as docker containers in a Kubernetes setup.

**Comment by thecloudgarage** [comment]
Also wondering if Redis support is provided in the application

**Comment by kbariotis** [comment]
Hey @thecloudgarage, which container are you referring to? The frontend client or the socket server? 

The frontend client is basically a frontend app so there is no state/session server-side.

The socket server, well even excalidraw.com runs on a single instance and is able to handle a vast amount of requests. I would be surprised if you needed more than that but you know best of course. I would stick with a single instance of the socket server.

Re: Redis, we run a basic [implementation of socket.io](https://github.com/excalidraw/excalidraw-room) which supports persistent sessions using Redis out of the box but we would have to implement it.

**Comment by thecloudgarage** [comment]
I am basically running the docker image, which I believe has both the frontend app and the socket server. Please correct me if I am wrong. In this case, if I want to run multiple instances of the docker image (docker hub: excalidraw/excalidraw), both the frontend app and the socket server., both get scaled out. Is there a way to run the front-end app separately as a docker container and the socket server as a separate docker container. If that's possible, then I can independently scale the frontend app by running multiple containers and as per your suggestion run a single instance of the socket server.

On point 2, i.e. redis, do you have plans to implement that within the application as an option

**Comment by kbariotis** [comment]
There are two images atm:

- The socket server: https://hub.docker.com/r/excalidraw/excalidraw-room
- The frontend client: https://hub.docker.com/r/excalidraw/excalidraw

The latter can be configured through an env variable to point to your self-hosted socket server. Docs are not really up to date, something to fix. 

Try it and let us know how it went. :)

**Comment by kbariotis** [comment]
> On point 2, i.e. redis, do you have plans to implement that within the application as an option

No AFAIC but we could implement it as optional if someone would like to scale up the socket server.

**Comment by thecloudgarage** [comment]
Got it.. thanks a bunch... will try leveraging redis for the socket server (I did not see .env file earlier to the heroku url for socket server.. my bad)... One other question...in the .env file I see references to json server... is that a separate docker image that I can host and any guidance there will be helpful

**Comment by lipis** [comment]
Will mark this one as done.
