### ISSUE TITLE
Embedding fonts in SVG export

### ISSUE THREAD

**Issue by keul** [excalidraw/excalidraw#2192]
I'm using SVG exported images from excalidraw. I use the _hand-draw_ font in many of them.

Then I use those SVG inside an HTML source (generated by gitlab markdown... so I can't, for example, directly embed SVG in there... `img` tag is my only choice).

What I noted: it seems that when SVN is included with the `img` tag, browsers are not downloading external fonts.

I tried the same **embedding fonts** directly (I'm not an expert, I just followed https://css-tricks.com/using-custom-fonts-with-svg-in-an-image-tag/)... and it works. So it seems that when an SVG image contains embedded fonts the image is properly displayed by browsers (tested Firefox, Chrome and Safari so far).

I'm wondering if this can be a new feature for Excalidraw, something like a new "Embed fonts in SVG" export option.

**Comment by dai-shi** [comment]
Duplicate of #1972?

**Comment by keul** [comment]
@dai-shi thanks, seems the same feature request

**Comment by FlipFloop** [comment]
Maybe we can export the text as shapes for now? Or is that done already?
