### ISSUE TITLE
line editing: make point-adding more obvious

### ISSUE THREAD

**Issue by aqandrew** [excalidraw/excalidraw#2194]
@vjeux [mentioned on Twitter](https://twitter.com/Vjeux/status/1310610226379325441) that there was some discussion about presenting an affordance, indicating that a new point can be added, when a user hovers over a line's point in edit mode. He also said there was no issue open for this yet.

> We should make it more obvious, one of the proposals was to add a shadow point on mouse over near the middle.

(Personally, I deleted and redrew a line 3 times before noticing the hint at the top of the screen saying I could add points in edit mode. 😅)

I'm guessing the shadow point would behave something like this:

![image](https://user-images.githubusercontent.com/9038965/94770909-ba2f2280-036a-11eb-919b-3f17fcd993be.png)

IMO, when a point is selected, the cursor doesn't necessarily have to be hovering over that point for a shadow point to be previewed.

For case F (extending a line), it might make sense to display the shadow point at a distance that's the same as halfway between P3 and P2, just in the opposite direction. Thoughts?

## Related issues

- This likely falls under "add hover state for points" in #1985.

- Directly related to [#1895](https://github.com/excalidraw/excalidraw/issues/1895#issuecomment-656647100)

**Comment by vjeux** [comment]
Love the use of excalidraw for explaining the behavior you have in mind!

**Comment by aqandrew** [comment]
Looks like these affordances were added in #5641. Nice job @ad1992!
