### ISSUE TITLE
Lost the ability to "Save as"

### ISSUE THREAD

**Issue by rockem** [excalidraw/excalidraw#2198]
In the past few weeks, every time I hit the Save button, I get a download with names something like that for example: _Untitled-2020-10-03-1942 (3).excalidraw_

What I'm expecting is for it to work like before where either I'll get a dialog where I can choose where to save it and how to name it, or, if I loaded an existing file, just to save by its current name and location. 
Right now it will always download in either case.

I tested it both in Chrome & Safari, running on OSX Catalina on mbp 2019 16 inch

**Comment by dwelle** [comment]
Should be automatically resolved on Oct 8, see this comment: https://github.com/excalidraw/excalidraw-blog/issues/226#issuecomment-695979591

**Comment by rockem** [comment]
Thanks for the info! closing.
