### ISSUE TITLE
factor out collaboration logic

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#2213]
Part of an ongoing effort to factor out I/O from the core component we (will) publish to npm.

We shouldn't expose our proprietary backend collaboration logic to the npm component, since 1) host apps will want to roll out their own implementation, and 2) they couldn't/shouldn't use our own backend anyway.

We definitely don't want to factor out logic such as UI for collaborators list (and related event handling), rendering of remote pointers, or even reconciliation of remote updates, because this logic should be implem-agnostic (and also a pain to reimplement).

What we want to factor out: 

- [ ] Any logic relating to reads/writes to the backend(s), including WS set up and communication.
- [ ] UI for the collaboration dialog (at least to an extent, but host apps will almost certainly want to supply their own copy because E2EE might not apply for them etc.), but still support a hook for rendering a button to open that dialog and surrounding events (`onRoomCreate`, `onRoomDestroy`...).
- [ ] ...?

We'll also want to add a way for host apps to pass latest [remote] elements to component outside initialization which will be reconciled with current (or replaced verbatim if the host app chooses to implement their own reconciliation) --- some ideas around this discussed already with @ad1992.

/cc @ad1992

**Comment by Turakar** [comment]
I appreciate the proposed refactoring! I want to share my thoughts from a "hoster" perspective with you, as I want to work on a Nextcloud integration (the prototype without collaboration works). I currently aim for the following setup:

1. (JS) Client wants to open a file in the cloud.
2. (PHP) Server creates a collaboration session with the contents of the file as the initial data or retrieves an existing session from memory/DB.
3. Server replies with the collaboration room URL.
4. Client joins.
5. Server continuously retrieves changes from the collaboration room and saves them in the file storage backend.
6. At some time, the room becomes idle and the server closes it.

I expect that I must re-implement the collaboration server for this (although I'm happy if I don't). I need to hide the "collaboration start/end" and "export to public URL" dialog altogether. Thus, I don't need a replacement for the usual storage backend. Additionally, I would like to set the username. Managing the client's library server-side might be a cool thing to implement in the future.

It would be very nice if this refactoring leads to an easy implementation of this pattern! Of course I do not expect this to be the "one to rule them all" pattern.

**Comment by dwelle** [comment]
The work is now done. Check https://github.com/excalidraw/excalidraw/tree/master/src/packages/excalidraw. We still plan to release some how-to articles in the future, but for now you can just read the source on how we do it for excalidraw.com: https://github.com/excalidraw/excalidraw/tree/master/src/excalidraw-app (probably start in https://github.com/excalidraw/excalidraw/blob/master/src/excalidraw-app/index.tsx).
