### ISSUE TITLE
Font color while typing is always blackish

### ISSUE THREAD

**Issue by axelonet** [excalidraw/excalidraw#2220]
The ability to have custom background color is awesome. But if I have a dark background like just black, I can't see the text I am typing unless I complete typing. Having the text as white for darker background while typing would be great.

**Comment by dwelle** [comment]
Can't repor. Can you make a gif or post exact steps?

![excal_typing_on_black](https://user-images.githubusercontent.com/5153846/95651183-cc3a5f00-0ae8-11eb-9421-53ad4523f9e2.gif)

**Comment by xixixao** [comment]
I saw this too, it made dark mode pretty unusable, but I can no longer repro it.

**Comment by dwelle** [comment]
The dark mode bug was fixed recently in https://github.com/excalidraw/excalidraw/pull/2196, but as I understand this issue isn't about dark mode but custom background color.

**Comment by xixixao** [comment]
Then I would suggest to @axelonet to change the font color before typing. I don't think requires a fix on our side.
