### ISSUE TITLE
Error when klicking 3x in the export menu

### ISSUE THREAD

**Issue by soerenetler** [excalidraw/excalidraw#2223]
### Scene content
I can send you the content if needed. It is very big and I can not attach it to this issue.
![scene_content(1)](https://user-images.githubusercontent.com/25177792/95677527-5c020b00-0bc6-11eb-84bc-535f815ef7b5.png)

### Sentry Error ID
8086944de4db4020a39da130a217c75e

**Comment by dwelle** [comment]
That's likely a browser limitation of canvas size, but can't be sure without having access to the scene (the sentry error says `NS_ERROR_FAILURE` which doesn't tell me much).

We have an open PR to at least show a proper error message: https://github.com/excalidraw/excalidraw/pull/2210

**Comment by lipis** [comment]
@soerenetler can you send the link to the scene if not a secret?

**Comment by lipis** [comment]
Will close is because of #2210
