### ISSUE TITLE
Add a tooltip with an icon for embedding scenes into PNG/SVG

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw#2232]
https://github.com/excalidraw/excalidraw/pull/2219#issuecomment-707615427

**Comment by lipis** [comment]
This tooltip could also show the increased size in PNG and SVG

**Comment by Kartik1397** [comment]
Can I work on this issue?

**Comment by dwelle** [comment]
Sure! I'd tackle only the tooltip with an explanation first, and leave the size increases to a separate PR (it's also tracked in https://github.com/excalidraw/excalidraw/issues/2236).

**Comment by Kartik1397** [comment]
For this issue I have to add tooltip button (with same effects as shield button) next to embed scene checkbox. Should I create tooltip component mentioned as todo in  https://github.com/excalidraw/excalidraw/blob/8f269eb8408c9ce0d7652f9cfa912395e75eeb43/src/components/LayerUI.tsx#L323

**Comment by lipis** [comment]
@Kartik1397 yes.. that's sounds like a good idea and we could use it in other places too probably

**Comment by Kartik1397** [comment]
I have found that, there's already a component named Tooltip which is used to show username of user during collaboration session.
https://github.com/excalidraw/excalidraw/blob/8f269eb8408c9ce0d7652f9cfa912395e75eeb43/src/components/Tooltip.tsx#L10

**Comment by Kartik1397** [comment]
What would be the prefered style for ℹ️ button?
currently I have made like this...
![Screenshot from 2020-12-13 02-33-28](https://user-images.githubusercontent.com/24036721/101995735-6b9aee80-3cf2-11eb-932b-e8d306f27f85.png)

**Comment by lipis** [comment]
I'm wondering if a [question mark](https://fontawesome.com/icons/question) would be more appropriate.. (also changing the keyboard icon, but for another PR)

**Comment by dwelle** [comment]
Agreed on question mark, but I'd use this one: https://fontawesome.com/icons/question-circle?style=solid

**Comment by Kartik1397** [comment]
should I display tooltip for mobile?

**Comment by dwelle** [comment]
Let's not display it on mobile for now.
