### ISSUE TITLE
Embed data in PNG breaks when using certain characters like emoji / ™ in a text element

### ISSUE THREAD

**Issue by gersomvg** [excalidraw/excalidraw#2241]
Tested in both Safari and Brave. This is the error:

```
Uncaught (in promise) Error: Only Latin-1 characters are permitted in PNG tEXt chunks. You might want to consider base64 encoding and/or zEXt compression
```

@dwelle Thanks again for this killer feature!

**Comment by dwelle** [comment]
Yes, I missed that the PNG chunk encoder doesn't encode the string to byte string :(. There's already a fix ready to be reviewed and merged, with a bonus compression feature that reduces the file sizes drammatically :) https://github.com/excalidraw/excalidraw/pull/2240
