### ISSUE TITLE
Copying drawing to clipboard in Safari throws exception

### ISSUE THREAD

**Issue by thibmaek** [excalidraw/excalidraw#2244]
Trying to copy a drawing to the clipboard in latest stable Safari throws the following exception and does not copy:

<img width="1678" alt="image" src="https://user-images.githubusercontent.com/6213695/96242760-1ff2ef80-0fa4-11eb-80a9-781791e2b217.png">

**Comment by dwelle** [comment]
Good to see Safari is starting to implement FS API, but it apparently falls short. The [security restrictions](https://webkit.org/blog/10855/async-clipboard-api/) seem to be stricter than in Chromium, but what we're doing for this feature should work. Are you testing this on `https://excalidraw.com`?

I'm not Safari so can't debug. Can you repro @lipis?

**Comment by lipis** [comment]
Works fine for me :)

**Comment by lipis** [comment]
please report back if you still have issues

**Comment by 0xtf** [comment]
Still happening in Safari 17:

<img width="1478" alt="image" src="https://github.com/excalidraw/excalidraw/assets/24301448/4846d94f-f888-4b77-9d73-53127587df5a">
