### ISSUE TITLE
It should not be possible to overwrite a png with json data

### ISSUE THREAD

**Issue by pomdtr** [excalidraw/excalidraw#2250]
Steps to reproduce:
- export to a drawing png with embedded data
- open this png with excalidraw
- click the save button (overwriting the file)

Maybe excalidraw should export a new png with embedded data in this case ?

**Comment by dwelle** [comment]
Thanks for the catch. Fix: https://github.com/excalidraw/excalidraw/pull/2252

> Maybe excalidraw should export a new png with embedded data in this case ?

I think we shouldn't overload the `save` button to save a JSON file in one case, and export to PNG in another.

**Comment by pomdtr** [comment]
Yes you're right. What i did expect was to overwrite my existing png with the updated one

**Comment by dwelle** [comment]
You changed my mind in that I agree it'd be very useful. I've created a separate issue for this: #2261
