### ISSUE TITLE
when an element has a custom hex color, color palette keyboard shortcuts don't work

### ISSUE THREAD

**Issue by dawneraq** [excalidraw/excalidraw#2265]
## Repro steps
1. Change an element's stroke or background color to a hex color that's not one of the default colors. 
    - `#beeeef`, `#666`, etc
2. Open the color picker by clicking on the `button.color-picker-swatch`.
3. Try to pick a new color from the default palette by pressing the <kbd>1</kbd>-<kbd>5</kbd>, <kbd>q</kbd>-<kbd>t</kbd>, or <kbd>a</kbd>-<kbd>g</kbd> keys.
4. The `Picker.handleKeyDown` listener won't catch the `keydown` event.
    - For example, pressing <kbd>a</kbd> will **not** select the dark green color within the color picker. Instead, Excalidraw's arrow drawing tool will be selected.

This also occurs when setting the canvas background color.

---

I'm sure this is caused by fact that the `Picker` component doesn't get focused when it's opened while a custom color is being used. Since the `button.color-picker-swatch` retains focus in this situation, any `keydown` event will start propagating at one of the `Picker`'s parent components.

Can I pick this up?

**Comment by dwelle** [comment]
Go ahead!
