### ISSUE TITLE
Slovak translation

### ISSUE THREAD

**Issue by lavyda** [excalidraw/excalidraw#2274]
Hi, I would like to help with Slovak translation. Can you add it to Crowdin? 🙂

**Comment by dwelle** [comment]
Here you go: https://crowdin.com/translate/excalidraw/10/en-sk?filter=basic&value=0

Language picker label will be "Slovensky", I presume.

**Comment by lavyda** [comment]
Thanks. I think more fitting label would be `Slovenčina`

**Comment by dwelle** [comment]
Alright. Dealer's choice.

**Comment by lavyda** [comment]
OK, I added translations.

**Comment by dwelle** [comment]
Thanks, we'll merge it shortly.
