### ISSUE TITLE
Can't handle Chinese characters in text input

### ISSUE THREAD

**Issue by 1813927768** [excalidraw/excalidraw#228]
When I input Chinese characters in the text input, I got this error msg in console.
![image](https://user-images.githubusercontent.com/28707897/71875746-02b10b00-3160-11ea-89b4-b05441c2d35e.png)

This error occures beacause of the incapability of handling unicode in `window.btoa()`. 
And there is a workaround [here](https://developer.mozilla.org/en-US/docs/Web/API/WindowOrWorkerGlobalScope/btoa) according to mdn.

```js
// ucs-2 string to base64 encoded ascii
function utoa(str) {
    return window.btoa(unescape(encodeURIComponent(str)));
}
// base64 encoded ascii to ucs-2 string
function atou(str) {
    return decodeURIComponent(escape(window.atob(str)));
}
```

Maybe someone could help to fix this in the next PR.

**Comment by vjeux** [comment]
Thanks for raising this! We reverted the URL handling in the meantime so it shouldn't be an issue anymore.
