### ISSUE TITLE
Provide an Input Field to manually enter the Zoom Percentage

### ISSUE THREAD

**Issue by plxity** [excalidraw/excalidraw#2289]
<img width="493" alt="Screenshot 2020-10-27 at 3 30 30 PM" src="https://user-images.githubusercontent.com/28510494/97286521-94157900-1869-11eb-823d-8f07bd8e2bff.png">

There is no option to manually enter the zoom percentage. Only "+" and "-" are available.

**Comment by dwelle** [comment]
What's the use case for this? To go beyond the range the app currently allows? Or to get to the desired zoom level faster?

If the latter, you can always use `Cmd/Ctrl+mouseWheel`.

If the former (but it also touches on the speed), there's an issue for this: https://github.com/excalidraw/excalidraw/issues/2081

**Comment by lipis** [comment]
I agree.. we don't want to bloat the UI with more inputs.

**Comment by plxity** [comment]
The use case was to achive the desired zoom level faster. I wasn't aware about the command. I guess then it's not required.
