### ISSUE TITLE
Copy + Paste moves text inside rectangle

### ISSUE THREAD

**Issue by hejcz** [excalidraw/excalidraw#229]
I have rectangle with text inside. When I select and copy them both text in copy is aligned to left top corner instead of being in the same position relative to rectangle.

**Comment by vjeux** [comment]
This is likely related to https://github.com/excalidraw/excalidraw/pull/214
@abhikulshrestha22 could you look into it? cc @Fausto95

**Comment by Fausto95** [comment]
I was working on center it today, I will push something in a bit!
