### ISSUE TITLE
SVG export has no size

### ISSUE THREAD

**Issue by geraintluff** [excalidraw/excalidraw#2291]
The SVG root element has no width/height, so they end up drawn at unspecified size.  This also means that (as far as I can see) 1x/2x/3x export don't change anything for SVG.

Maybe something like this:

```
svgRoot.setAttribute("width", `${width}`);
svgRoot.setAttribute("height", `${height}`);
```

https://github.com/excalidraw/excalidraw/blob/5950fa9a40ea9aa6a78ae9e79c01395ba0647e63/src/scene/export.ts#L106-L108

**Comment by lipis** [comment]
Yes, 1x, 2x, 3x are affecting only the PNG.. we are not setting any specific size to the svgs.. what's the usecase? You can always resize wherever you're about to use it and that's the main purpose.

**Comment by dwelle** [comment]
As explain in [PR](https://github.com/excalidraw/excalidraw/pull/2292#issuecomment-718029377), it's easy to change it on user's side, and it's better to not constrain the size by default.

**Comment by geraintluff** [comment]
I've replied in more detail on the PR, but: if I'm including multiple diagrams directly in a web-page, I have to set the size for each one directly.  

To _find_ the correct size (to get consistent scale between diagrams), I have to look at the SVG source and take it from the `viewBox` attribute.

**Comment by dwelle** [comment]
That's a valid point we haven't considered. We're reverting our previous decision.

**Comment by geraintluff** [comment]
I just want to say: this was my first return to open-source collaboration after a long period of burnout.  Thank you for making it a pleasant one!

**Comment by dwelle** [comment]
Thank you as well — and we nearly blew you off :). @lipis, maybe this would also fix the enormous logos in readme of this repo: https://github.com/pclainchard/excalidrawLib (scroll down).
