### ISSUE TITLE
docker build failing

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#2304]
Docker action fails on build: https://github.com/excalidraw/excalidraw/runs/1322045132#step:4:168

Unclear why it's failing for docker action, and not for regular build on Vercel.

The only thing that could explain this is recent upgrade to CRA@4 (it started failing from this PR: https://github.com/excalidraw/excalidraw/pull/2302)

Maybe we should [upgrade](https://github.com/docker/build-push-action/blob/master/UPGRADE.md) to https://github.com/docker/build-push-action v2 and see if it helps, though that seems dubious.

/cc @kbariotis

**Comment by lipis** [comment]
Updating to latest seems like a good start.

**Comment by Jan-M** [comment]
Local Docker image build is failing for me with the above referenced errors too.

**Comment by kbariotis** [comment]
Thanks to @Mogztter for fixing this. #2348
