### ISSUE TITLE
Synchronizing React State with Canvas state

### ISSUE THREAD

**Issue by GasimGasimzada** [excalidraw/excalidraw#231]
Sorry about the weird title, couldn't think of anything better.

One thing that I noticed when extracting the components and functions was the usage of `forceUpdate` basically everywhere. I remember in reading one of the issues that there is an interest in adding `elements` array into application state. Now, there is a problem with how we use `forceUpdate` and adding `elements` array into application state. In majority of cases, we are mutating the elements array in-place, which causes the usage of `forceUpdate` to rerender the scene when things change.

By investigating the code, there are about 3-4 places where the elements array is being mutated outside the component. My suggestion is to convert these functions into utilities that return the final array instead of mutating them in-place. Then, perform array updates within the Application. This way, we can make the scene synchronized with app state.

Additionally, we can store `selectedElements` in a separate state instead of consistently looping through the `elements` array and comparing if an element is selected. This can improve performance because loops, mutations etc will be smaller. But mainly, this is going to separate logic and concerns from the elements. Because I personally look at selected elements as a UI tool instead of them being part of the scene (even if we do draw boxes around them, it still has nothing to do with the scene -- it is being only used by the Panels).

I suggest doing this in two (or three if you agree with the last change) parts:

- [ ] Remove mutations from scene, element, and history functions and change App component code to use those functions (we can do something like `scene.elements = newElements` to update the global elements array)
- [ ] Move elements array into application state and remove all the uses of forceUpdates
- [ ] Separate selected elements state array from elements state array and update application code.

**Comment by vjeux** [comment]
Yes to everything. That would be much better indeed :)

**Comment by enzoferey** [comment]
I can be of great help on this @GasimGasimzada, let me know if you want any help 👍 

This will be tricky to pull off with a lot of people contributing features because we will most likely have to rebuild them on top at the same time we refactor, but it should definitely be done sooner or later.

**Comment by GasimGasimzada** [comment]
@enzoferey I am currently working on a system that I call action system in this PR: #298. The goal of this PR is to modularize actions. If you want to, you can also get engaged in the discussion.
