### ISSUE TITLE
Search feature request

### ISSUE THREAD

**Issue by ghost** [excalidraw/excalidraw#2310]
Is it possible to add a search feature to center a map/sketch on a certain text label. And show the results similar as browsers do so that you can jump to the previous or next result? (see the attached example)
![Screenshot_20201028-204457](https://user-images.githubusercontent.com/63105006/97488932-3400fe80-195f-11eb-8f5c-ee98b3c961a5.png)

**Comment by lipis** [comment]
As a hidden feature on Cmd+F (or Ctrl+F) like GitHub does it.. but nothing visual to invoke it.

I like the idea.. not sure how useful it is though

**Comment by mapbakery** [comment]
It's especially useful on my phone (therefore I would like a search icon) because I can then center the map/diagram I'm working on correctly to the right place. Another use case is that I can check if I have certain things in my map/diagram although I've a workaround for that (by doing a text search in the source file).

Note: I use excalidraw for maps and diagrams which can be big and contains lot's of text labels.

**Comment by dwelle** [comment]
While exposing this under `Cmd/Ctrl+F` is plausible, I don't see us adding a UI button for it, especially on mobile where we've pretty much run out of space already.

**Comment by AaronRobinson** [comment]
+1

I'm mapping lots of named entities - it isn't possible to see if I've added something already.

**Comment by nschnierer** [comment]
The basic concept is not that complicated to implement.
However the hardest point I see, is to highlight the searched text. Maybe it's enough to just center the text element and to give some border color to it.

**Comment by lipis** [comment]
I'll mark it as out of scope for now.. not the most needed feature in a whiteboard diagram.

**Comment by russellaugust** [comment]
This is particularly useful for people working in a collaborative environment. I don't always know what's been added and it's much easier to do a fast search than to scroll around.  Our white boards get _massive_.

**Comment by gastonlrossy** [comment]
It would be very usefull, I always lose my diagrams in excalidraw and it's extremely difficult to find them...

**Comment by srgsanky** [comment]
Search on excalidraw is needed especially for large text based illustrations of systems.

As a workaround, I have been exporting the image as SVG and using browser's search feature to search on SVG.

**Comment by CuberL** [comment]
https://gist.github.com/CuberL/1dce8600f0f7e59c8b7f5b8690a0997f

Any who need search feature can use this Tampermonkey script.
