### ISSUE TITLE
Error using Opera Navigator

### ISSUE THREAD

**Issue by GOArango** [excalidraw/excalidraw#2312]
When I save a drawing using the Opera browser, it is left with zero size.

**Comment by dwelle** [comment]
I'm getting

> DOMException: The request is not allowed by the user agent or the platform in the current context.

Not sure what Opera is doing on top of Chromium that would cause this. /cc @tomayac thoughts?

**Comment by tomayac** [comment]
Sorry, but I don't know, and don't trust it enough to install it on my work computer. I suggest opening a thread on the [Opera forum](https://forums.opera.com/category/5/opera-for-computers).

**Comment by dwelle** [comment]
> Sorry, but I don't know, and don't trust it enough to install it on my work computer.

I had qualms about installing too, but then did it anyway. I hope I'm not part of a Chinese botnet now. :joy:

**Comment by GOArango** [comment]
> When I save a drawing using the Opera browser, it is left with zero size.

Thanks for comments...

Add some events from console:

[Violation] Added non-passive event listener to a scroll-blocking 'touchstart' event. Consider marking event handler as 'passive' to make the page more responsive. See https://www.chromestatus.com/feature/5745543795965952

The script has an unsupported MIME type ('text/html').

Error during service worker registration: DOMException: Failed to register a ServiceWorker for scope ('https://excalidraw.com/') with script ('https://excalidraw.com/service-worker.js'): The script has an unsupported MIME type ('text/html').

DOMException: The request is not allowed by the user agent or the platform in the current context. instrument.ts:129

**Comment by dwelle** [comment]
@GOArango yep, the relevant error is the last line. Not much we can do on our end, apart UA-string-detect Opera and use legacy FileSystem API, which I wouldn't want to do.

I may get around to create support ticket on their forum someday, or you can do it yourself, linking to this issue.

**Comment by lipis** [comment]
Yes, we wouldn't want to use legacy FileSystem.. so we will close this for now.
