### ISSUE TITLE
SW broken since CRA@4

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#2318]
Upgrading to CRA@4 seems to have introduced a bug where `service-worker.js` is no longer built: https://github.com/facebook/create-react-app/issues/9776

Judging by the fact the issue is open for 21 days (and the cadence of CRA patches), we'll need to fix this one ourselves.

EDIT: it seems we need to create a `src/service-worker.js` for the CW injection to kick in on build.

**Comment by MeRahulAhire** [comment]
when will this issue be fixed?

**Comment by dwelle** [comment]
It was fixed in #2320 — is something not working for you?

**Comment by MeRahulAhire** [comment]
actually not. I've seen the updated article on SW and its OK for me
