### ISSUE TITLE
Language Request - Burmese (Myanmar)

### ISSUE THREAD

**Issue by naingyeminn** [excalidraw/excalidraw#2321]
Hello!

I'd like to contribute to the L10n. I have translated to Burmese and covered 97% of the locale. Could you please add my language to the project so that I can submit my translation?

Best Regards,
Naing

**Comment by lipis** [comment]
Here you are https://crowdin.com/translate/excalidraw/10/en-my

How should write Burmese for the language selector?

**Comment by naingyeminn** [comment]
There are two words for Burmese, "ဗမာ" and "မြန်မာ". Although we are still using both interchangeably, I would go for "မြန်မာ" as it is an official word now.

Burmese = မြန်မာ

**Comment by dwelle** [comment]
Am I the only whose system renders the characters as such? :)

![image](https://user-images.githubusercontent.com/5153846/97801814-c8a97c00-1c3f-11eb-89b5-43a743f1cf50.png)

**Comment by naingyeminn** [comment]
Maybe the fonts in your system don't have Burmese characters. Could you please try to copy and paste my previous comment into the Unicode textbox of the following link?

http://www.rabbit-converter.org/Rabbit/

<img width="1552" alt="burmese" src="https://user-images.githubusercontent.com/7280181/97804072-f1e7fd80-1c7b-11eb-9f7d-93961f0838cf.png">

**Comment by lipis** [comment]
Works fine on macOS

**Comment by dwelle** [comment]
Let's ignore then... except maybe we should use ASCII for the language picker just in case.

**Comment by lipis** [comment]
For those who want that language it will appear correctly :)

**Comment by dwelle** [comment]
Sure, but I think having squares in language picker wouldn't be nice either way.

**Comment by lipis** [comment]
So what do we do?

**Comment by naingyeminn** [comment]
I agree. ASCII is better for now. "Burmese" is fine for us.

**Comment by dwelle** [comment]
Cool, I changed the label and we'll merge soon.

**Comment by lipis** [comment]
@naingyeminn We are live!

<img width="282" alt="Screenshot 2020-11-03 at 7 51 19 PM" src="https://user-images.githubusercontent.com/125676/98022184-f47a5c80-1e0d-11eb-8837-93176b446364.png">
