### ISSUE TITLE
Please add translation in hausa

### ISSUE THREAD

**Issue by alainlompo** [excalidraw/excalidraw#2322]
Hausa is currently spoken by more than a 100 million people and i"Hausa ranked second most-spoken native language in the world according to the Association of Hausa African Community"
See here for more details about the language: https://en.wikipedia.org/wiki/Hausa_language

**Comment by dwelle** [comment]
Sure: https://crowdin.com/translate/excalidraw/10/en-ha

Do I understand it correctly that you're interested in translating it? How do you say "Hausa" in Hausa, for the language picker?

**Comment by lipis** [comment]
Since only contributors are dealing with the translations.. if a language is very low on translated strings we are removing them from time to time until we find more contributors! Jus FYI

**Comment by alainlompo** [comment]
Hi Hausa is translated Hausa in Hausa, and yes I am interested in translating into Hausa. Regarding the comment from @lipis , in how much time do you normally expect a translation to be done?

**Comment by dwelle** [comment]
> in how much time do you normally expect a translation to be done?

Depends on how fast you translate. We also merge translation PRs only ~once a week or so.
