### ISSUE TITLE
Text selection range over the whole page 

### ISSUE THREAD

**Issue by rauchg** [excalidraw/excalidraw#2323]
I started dragging to select two shapes, managed to select the whole "text" of the page.
OS/Browser: iPadOS Safari

![7C0A34BD-9318-4456-A19A-3F44DBCB3C9F](https://user-images.githubusercontent.com/13041/97816580-14adee00-1c4b-11eb-9474-3b688018b7ca.png)

**Comment by lipis** [comment]
@vjeux can you reproduce this?

**Comment by vjeux** [comment]
I haven't been able to reproduce unfortunately :(

**Comment by lipis** [comment]
Let's close it then. @rauchg feel free to report back and steps to reproduce it if it's still happening.
