### ISSUE TITLE
Trap focus inside all modals/dialogs

### ISSUE THREAD

**Issue by ad1992** [excalidraw/excalidraw#2339]
This would help in Accessibility as well

**Comment by dwelle** [comment]
AFAIK we were trapping until recently, so this is a regression: 

https://github.com/excalidraw/excalidraw/blob/2a20c44338ab40b497348b8374ead1ee42e440a8/src/components/Dialog.tsx#L35-L54

**Comment by dwelle** [comment]
It seems I introduced it in #2215

**Comment by ad1992** [comment]
Interesting regression! :P
