### ISSUE TITLE
Clearing the canvas shouldn't affect the grid mode.

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw#2358]
If there was a grid on before clearing the canvas, I would expect the grid to still be visible..

**Comment by dwelle** [comment]
how about we merge this issue into https://github.com/excalidraw/excalidraw/issues/2358 (and rename)

**Comment by lipis** [comment]
@dwelle recursion

**Comment by dwelle** [comment]
:D, I meant https://github.com/excalidraw/excalidraw/issues/2334
