### ISSUE TITLE
When importing to library, show the library

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw#2361]
Because at the moment, nothing happens visually when dropping the lib file into the scene (or opening it)

**Comment by dwelle** [comment]
when we're at it, we should support dropping a file onto an open library itself, not just `<canvas>`.

**Comment by ikmrgrv** [comment]
I would like to help on this ...

**Comment by dwelle** [comment]
@ikmrgrv sure thing!

**Comment by ThangHuuVu** [comment]
hi @ikmrgrv , are you still on it? Otherwise I'd like to take over 😄

**Comment by lipis** [comment]
Go for it @ThangHuuVu!
