### ISSUE TITLE
Excalidraw.com Real Time Collaboration Broken. socket.io POST Request returns 404

### ISSUE THREAD

**Issue by nestorconde** [excalidraw/excalidraw#2362]
Real Time Collaboration seems broken. See https://excalidraw.com/#room=683d9f57254db33575d0,tCyN-n6Tw1ubownpYNQgVQ

Currently the server is returning a 400 Bad Request {"code":2,"message":"Bad handshake method"} to POST requests to https://excalidraw-socket.herokuapp.com/socket.io/?EIO=4&transport=polling&t={random}. So this could be the problem.

**Comment by dwelle** [comment]
Thanks for the catch. Caused by merging a major version update of socketIO, which I missed. We'll need to upgrade it properly, later.
