### ISSUE TITLE
Can we make the scroll bars bigger?

### ISSUE THREAD

**Issue by PeteDuncanson** [excalidraw/excalidraw#2368]
Some of my models of late have been pretty big which means I need to scroll around a bit. I've been struggling to grab the horizonal scroll bar as its been made so small, its quite a small target area to hit and causing frustration and break in flow.

I suggest we make it a bit bigger so its an easier target to hit?

**Comment by dwelle** [comment]
I must admit that in all my days I haven't used scrollbars once :).

I think the combination of canvas panning & zoom (`cmd/ctrl + wheel`) is enough.

**Comment by lipis** [comment]
I think scrollbars are there just to give you and idea how much space you are using

**Comment by PeteDuncanson** [comment]
Ahh now I know about the panning then yes this makes sense. Thanks all :)
