### ISSUE TITLE
Add a pan/drag option?

### ISSUE THREAD

**Issue by PeteDuncanson** [excalidraw/excalidraw#2369]
Related to #2368 sometimes I just want to click and drag the board around so I can navigate around quicker on bigger drawings. Wondered if clicking and dragging on the back ground could cause a pan (move the whole page within the view port) such as when grabbing the scroll bars.

Alternatively it could be an icon on the tool bar.

This feature might already be there but I've not been able to find it easily from the UI alone.

**Comment by dwelle** [comment]
> This feature might already be there but I've not been able to find it easily from the UI alone.

Yep, already there. Try `wheel-click + drag` or `spacebar + drag`.

You can find this in our keybinding help: 

![image](https://user-images.githubusercontent.com/5153846/98548363-b2339e00-2299-11eb-888a-8bf080d12350.png)

**Comment by PeteDuncanson** [comment]
You know I never even noticed that icon and when I did I thought it was for a touch screen keyboard or something, learnt a tonne of short cuts from there. Lovely, thank you :)

**Comment by dwelle** [comment]
Yep, I was thinking we could make it into a :question: icon. @lipis thoughts?
