### ISSUE TITLE
Letter keyboard shortcuts don't work with CapsLock

### ISSUE THREAD

**Issue by iamsaumya** [excalidraw/excalidraw#2372]
I was working with Excalidraw and hovered over the horizontal stack that has different shapes to select. As we know it's inconvenient to reach out to the shape to select it, I looked for the key combinations. 

The shortcut keys for selecting a rectangle shape is 'R' or '2'. The issue here is that it only works for 'r' or '2'. If I hit 'r' with caps lock on, the shape will not be selected. I assumed from the tooltip that it should work with 'R' which it is not. 

![Screenshot from 2020-11-10 01-22-59](https://user-images.githubusercontent.com/40148448/98589502-63b2ed80-22f3-11eb-83eb-ba62dc2d4343.png)

I think this could be a bad user experience?

**Comment by iamsaumya** [comment]
I'd love to contribute if this adds a value to the project. Thanks!

**Comment by lipis** [comment]
Should work with upper case letters as well I would say :)

Sure.. go for it.

**Comment by dwelle** [comment]
Actually, I don't think so. It'll preclude using `Shift+<key>` shortcuts.

**Comment by iamsaumya** [comment]
Thanks @dwelle, it makes sense. We definitely don't want to preclude `Shift+<key>` shortcuts. However, if the user has their capslock turned on then pressing `P` key will not work. 

It will be just a better UX to check if the capslock is turned on when `P` is pressed as the keyCode for `P` is the same for caps locks on and off. Here, I am assuming there are not any plans to add `CapsLock + <key>` shortcuts in excalidraw.

**Comment by dwelle** [comment]
Mhm... I've done some testing and it seems CapsLock can be detected after all, and the event only differs in `key` prop AFAIK. So I made a quick hack: https://github.com/excalidraw/excalidraw/pull/2373
