### ISSUE TITLE
Proposal: Selection like AutoCAD

### ISSUE THREAD

**Issue by ReneCode** [excalidraw/excalidraw#2376]
![selectionLikeAutoCAD](https://user-images.githubusercontent.com/1595098/98861330-5d448300-2465-11eb-81f8-9580917005e5.gif)

sometimes it's a little bit difficult to select an element because the selection window does not completely cover its bounding box. The way the selection windows it created can change the selection behavior:

- Draw a window from **left to right**. All objects **completely** inside the window frame will be selected. (current behavior)
- Draw a window from **right to left**. All objects **completely or partly** inside the window frame, will be selected. (additional behavior)

Window-selection / crossing-selection of AutoCAD explained here: 
https://www.cadtobim.com/object-selection.html

**Comment by dwelle** [comment]
Surprisingly, this was requested once already: https://github.com/excalidraw/excalidraw/issues/692

**Comment by dwelle** [comment]
While we're likely not implement the AutoCAD right-click behavior, we might investigate switching the behavior (but no promises).

I'm gonna close this one in favor of https://github.com/excalidraw/excalidraw/issues/2377

**Comment by lipis** [comment]
TBH I think the AutoCAD approach is the best from both worlds.. :) (I used to AutoCAD in the past)

**Comment by showdev** [comment]
I'm here looking for the same behavior. Quite confused by the maintainer calling it 'magical' in #692. I though it's a default behavior for all CADs and majority of graphical or 3d editors. I feel like somebody cut of one of my fingers when trying to edit things without it.

**Comment by driv** [comment]
I thought it was a default everywhere, I've just found out that it's limited to some CAD apps.
