### ISSUE TITLE
collaboration security issue 

### ISSUE THREAD

**Issue by MalteBoehm** [excalidraw/excalidraw#2378]
Hey guys, i love excalidraw a lot but there seems to be a security issue with the collarboration mode. When it was activated somebody logged into my drawing with my name and began live to delete my stuff :D .

I didnt share my link, i just tryed to save the URL to my drawing.

Greetings
Malte

**Comment by dwelle** [comment]
Hello.

Do I understand it correctly that you created a collaboration session, and right (or soon) after someone else joined in and started deleting elements on the scene?

That's disconcerting. I'll review our security rules.

(As for the name — a participant can choose any name, but first they'd need to read yours so they could change it to the same.)

**Comment by dwelle** [comment]
Also, if you still have the collab room link, can you please post it (provided it doesn't contain private data)?

**Comment by dwelle** [comment]
One other thing: can you elaborate on "began live to delete my stuff". Was the other party deleting elements one by one, or the whole scene at once?

If all at once, that could suggest they were in possession of the room `id`, which would allow them to overwrite the server persisted value. Even that alone is very improbable unless we have a security issue on Firebase (from my preliminary examination we don't).

But if they were deleting elements one a time, that would suggest they were actively "collaborating", which means they'd have to also possess the private `key` (which is not transmitted anywhere).

**Comment by dwelle** [comment]
Our preliminary investigation, taking into account all the details such as identical username etc., suggests that it's a synchronization issue rather than a security one (meaning, what you were possibly seeing was your client mistakenly connecting twice to the collab server, or that the update reconciliation was having glitches). Neither makes much sense, but the synchronization hypothesis is much more likely. We'll investigate further.

**Comment by MalteBoehm** [comment]
> Hello.
> 
> Do I understand it correctly that you created a collaboration session, and right (or soon) after someone else joined in and started deleting elements on the scene?
> 
> That's disconcerting. I'll review our security rules.
> 
> (As for the name — a participant can choose any name, but first they'd need to read yours so they could change it to the same.)

Yes, i started the session and a few minutes later someone joined and began to slowly drag stuff. 
I didnt share my session.

**Comment by MalteBoehm** [comment]
> One other thing: can you elaborate on "began live to delete my stuff". Was the other party deleting elements one by one, or the whole scene at once?
> 
> If all at once, that could suggest they were in possession of the room `id`, which would allow them to overwrite (but not read) the server persisted value. Even that alone is very improbable unless we have a security issue on Firebase (from my preliminary examination we don't).
> 
> But if they were deleting elements one a time, that would suggest they were actively "collaborating", which means they'd have to also possess the private `key` (which is not transmitted anywhere).

Two things. one by one

**Comment by jonasdebeukelaer** [comment]
I may have an alternate explanation for this - I've had this a couple times last week.

I too was in a shared room on my own (😢) and then another me turned up. I think perhaps connection issues (?) was a making the session think I was a second participant, and the other me was just a delayed version of my movements.

The one different is the other me never actually moved any items, just that the mouse moved around eerily. Stopping the session removed the other me, naturally.

**Comment by dwelle** [comment]
Yes, that's almost certainly what's happening since the original hypothesis is so improbable so as to border on the impossible.

@jonasdebeukelaer I can confirm I've encountered the very same, but usually only when developing and doing unusual things. Also, connecting to the same room using the same browser does similar things.

That said, I'm still not clear how to reproduce the OP behavior where the duplicate client started deleting things.

**Comment by lipis** [comment]
Report back if that happens again.. the explanation by @jonasdebeukelaer seems valid, as it's impossible to guess the room id
