### ISSUE TITLE
Draw a line from a formula

### ISSUE THREAD

**Issue by michelcaradec** [excalidraw/excalidraw#2380]
Hello,
Excalidraw is my tool of choice when it comes to quickly draw simple to complex schemas.
Here is a suggestion that could improve productivity for science oriented drawings.
The purpose is to draw a multi-points line from a formula of the type `y = function(x)`.
Some conventions should be followed in the writing of the formula (use of variable `x`, single line formula), and informations such as scale (i.e. value of one pixel when transposed to axes - 1 by default).
The Javascript `eval` function could be used, with some pre-parsing to avoid any code injection.

![LineFromFormula](https://user-images.githubusercontent.com/12159769/99184869-6b84ee80-2746-11eb-8379-d62619268963.png)

Thank you for all the great work.

**Comment by lipis** [comment]
I think this is completely out of scope for our little whiteboard app.. seems very advanced tool with bunch of parameters..

**Comment by tom-huntington** [comment]
Get a LLM to make an svg of the graph, then import it into excalidraw

https://chatgpt.com/share/67eca277-0a50-8010-aec8-e25039947ec5
