### ISSUE TITLE
Display shape size while resizing

### ISSUE THREAD

**Issue by keul** [excalidraw/excalidraw#2391]
While resizing a shape it could be useful to display the width/height of the resulting SVG somewhere, in a way similar to what Chrome does when resizing a window.

![resize-info](https://user-images.githubusercontent.com/284924/99643581-249c3f00-2a4d-11eb-81ec-beb1942c80f3.gif)

**Comment by dwelle** [comment]
This was discussed somewhere already. So far it seems as out of scope, but maybe for a special mode that will allow more precise editing (we already support grid mode).

**Comment by keul** [comment]
Grid mode is new to me, however I'm not sure it's fully out of scope. Having w/h mean also have dimension ratio, which can be useful in some cases.

**Comment by lipis** [comment]
we can allow stats now (context menu) and most likely will are not going to complicate the canvas to show extra info

**Comment by rizomer** [comment]
quite late in the conversation @keul but I find access to excalidraw json file very useful for precise re/sizing. 
for exemple looking for a specific "ellipse" shape, you can specify exact width and height along with many other variables :

```
		{
			"type": "ellipse",
			"version": 3558,
			"versionNonce": 1143420149,
			"isDeleted": false,
			"id": "qRNlpkZyhd0fa5XUHSVGY",
			"fillStyle": "hachure",
			"strokeWidth": 0.5,
			"strokeStyle": "solid",
			"roughness": 0,
			"opacity": 100,
			"angle": 3.1327370430924457,
			"x": 19.909762194334057,
			"y": -59.73310696693191,
			"strokeColor": "#000000",
			"backgroundColor": "000000",
			"width": 60,
			"height": 60,
			"seed": 378890101,
			"groupIds": [],
			"strokeSharpness": "sharp",
			"boundElements": [],
			"updated": 1668710031344,
			"link": null,
			"locked": false
		},
```


> While resizing a shape it could be useful to display the width/height of the resulting SVG somewhere, in a way similar to what Chrome does when resizing a window.
> 
> ![resize-info](https://user-images.githubusercontent.com/284924/99643581-249c3f00-2a4d-11eb-81ec-beb1942c80f3.gif) [ ![resize-info](https://user-images.githubusercontent.com/284924/99643581-249c3f00-2a4d-11eb-81ec-beb1942c80f3.gif) ](https://user-images.githubusercontent.com/284924/99643581-249c3f00-2a4d-11eb-81ec-beb1942c80f3.gif) [ ](https://user-images.githubusercontent.com/284924/99643581-249c3f00-2a4d-11eb-81ec-beb1942c80f3.gif)
