### ISSUE TITLE
Multi-point line

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#24]
Not sure if it's super useful but zwibbler supports it. Maybe we worth also having a smooth one using bezier curves

**Comment by iKlsR** [comment]
Open for using something like https://pomax.github.io/bezierjs/?

**Comment by vjeux** [comment]
Yes!

**Comment by pshihn** [comment]
https://github.com/pshihn/rough/wiki#curve-points--options 
is implemented using beziers. It could use some improvement  but should work for simple 3-4 point curves

**Comment by GasimGasimzada** [comment]
I have played with bezier curves within the app and this is the type of result I got:

![Screen Shot 2020-01-12 at 12 58 24 PM](https://user-images.githubusercontent.com/807231/72216518-6b6efd80-353b-11ea-9ee3-825af81c8eed.png)

Is this what we are looking for (don't worry about arrow's orientation).

**Comment by vjeux** [comment]
Nice!!

**Comment by GasimGasimzada** [comment]
@vjeux drawing bezier curves is not a hard task. However, I have no clue on how to find a point on a bezier curve. For the time being, I am going to do straight lines for the arrow and get it to a working condition (#338). Then, I will research and try to implement the necessary algorithms for bezier curves.

**Comment by vjeux** [comment]
We now have it!
