### ISSUE TITLE
Multiplayer doesn't work in local network without internet

### ISSUE THREAD

**Issue by hangmana** [excalidraw/excalidraw#2405]
Today faced a problem, our server is sending data to external resources.
And when we disconnect internet connections, multiplayer stop working... But solo is still working...

How to close access to the Internet so that multiplayer remains working in the local network?
or what server we have to install, to fix it?

Current server calls to "wss://excalidraw-socket.herokuapp.com/socket.io/?EIO=3&transport=websocket&sid=eNCyk5bXU0mT2txjANf5"
And another from here https://github.com/excalidraw/excalidraw/blob/master/.env
![изображение](https://user-images.githubusercontent.com/35597729/99964397-4296d600-2da4-11eb-988c-902106a5d7f3.png)

**Comment by dwelle** [comment]
As you have discovered, our collaboration works by exchanging messages through a WebSocket server, so it's not a P2P protocol. Without the internet that connection is lost.

We'll soon make it easier (when we publish a new Excalidraw npm package) to write your own servers and such, so you will be able to implement a P2P collaboration workflow yourself (if LAN P2P is possible in browser environments).

We ourselves do not have plans to do that.

**Comment by hangmana** [comment]
thx for response.
