### ISSUE TITLE
What if someone gets the URL / guesses the URL of Excalidraw links?

### ISSUE THREAD

**Issue by karuppiah7890** [excalidraw/excalidraw#2408]
When I say Excalidraw links, I'm referring to
- Share links
- Live collaboration session links

I'm bringing this up because people in our organization feel that this is a problem. They feel authentication should be present in the app.

My 2 cents - This concern looks like an authorization problem, with concern around confidentiality and maybe even integrity. And authentication is the first step to move to authorization. Both of these features would require a lot of development effort from the dev team side. This might also make Excalidraw a bit more complex than it is now. And to keep it easier, like how it is now, one would have to be able to use Excalidraw even without logging in, which would mean guest mode or something. Also, since there's authentication and authorization, there's more data to store in the backend and I'm guessing that the server needs to store some more metadata regarding the scenes, but it won't still store keys, yes, to ensure end to end encryption.

Given all of the above, I'm still raising this based on what I noticed other people say. Also, I think guessing the URL maybe probably hard? And maybe a note to the user saying "keep the URL safe" is key, or maybe it goes without saying? I don't know

**Comment by karuppiah7890** [comment]
What do other folks, including the maintainers, think about this?

**Comment by karuppiah7890** [comment]
Looks like there's a related issue https://github.com/excalidraw/excalidraw/issues/1026 which talks about keeping Excalidraw simple without authentication and also having less friction

**Comment by karuppiah7890** [comment]
Another point is - if someone feels that the app is not secure enough, they can -

- Fork and add some integration and host it themselves
- Or they could also take the current app and host it themselves within their closed network like a VPN, but that's just a network level security, but maybe the users trust it and are okay with it

**Comment by lipis** [comment]
As long as you keep the URLs safe, nobody can guess them or access them. We are not sharing the keys with our backends and the decryption is happening client side.

**Comment by netFLOw95** [comment]
Has anything changed here in the meantime? I am also looking for an authentication method (e.g. JWT).

**Comment by Recreabox** [comment]
I don't understand why there is no option to secure the access and don't let anyone use our public instance

**Comment by netFLOw95** [comment]
Latest information from Saghul: https://community.jitsi.org/t/protect-whiteboard-from-unwanted-access/138243
