### ISSUE TITLE
replace transparent color with transparent fill

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#2412]
1. It's not obvious that to get a no fill you need to change bg shape color to transparent
2. By default we use transparent color so that there's no fill. As such, changing a fill style does nothing in new scenes. This is unintuitive.

Proposal:

1. Remove `transparent` color from color picker.
2. Introduce `transparent` fill.

-----

Please upvote what ever you like/dislike in this thread. 👍 / 👎

**Comment by lipis** [comment]
I like the current behaviour, and we had no complains about being confused or anything.

**Comment by dai-shi** [comment]
I got confused with WYSIWYG icons, but I'm fine with the current behavior. No need to change.

**Comment by lipis** [comment]
Maybe a better idea would be to set a default background color to one of the choicess (except the transparent) so all shapes will have some random color assigned to them.

**Comment by dwelle** [comment]
Contra-proposal: change the fill color from `transparent` to something else only after you manually change the fill style.

**Comment by lipis** [comment]
> Contra-proposal: change the fill color from `transparent` to something else only after you manually change the fill style.

I like that one, as an additional to [my proposal](https://github.com/excalidraw/excalidraw/issues/2412#issuecomment-733693015) above.

**Comment by dwelle** [comment]
I'd not be against setting a default color IFF there was a transparent fill style on top. I bet that lots of people won't realize they can disable fill by setting the color to transparent.

**Comment by dwelle** [comment]
Also note that it may be that the default use case is quick prototyping/wireframing, for which having bg-color by default isn't useful.

**Comment by lipis** [comment]
> Also note that it may be that the default use case is quick prototyping/wireframing, for which having bg-color by default isn't useful.

That's why maybe actually doing nothing should be the right solution. The current behaviour is just fine.

**Comment by wietsevenema** [comment]
I don't think the current behaviour is confusing, and I also like this proposal.

**Comment by lipis** [comment]
We discussed about another solution.. will link here when it will be posted. Closing this one for now.
