### ISSUE TITLE
"No Fill" Option

### ISSUE THREAD

**Issue by GrimTheReaper** [excalidraw/excalidraw#243]
A resolution to https://github.com/excalidraw/excalidraw/issues/79 might be have an option to just have no fill. Right now its `Solid`, `Hatchure`, and `Cross-Hatch`. Might be worthwhile to have `None`.

Edit: Another note, there is no transparency option for fills either.

**Comment by vjeux** [comment]
Yes!

We should either have a no-fill option or a transparent background color. Either would work.

**Comment by vjeux** [comment]
I added the ability to select a transparent color
