### ISSUE TITLE
Create the excalidraw logo with excalidraw

### ISSUE THREAD

**Issue by GrimTheReaper** [excalidraw/excalidraw#244]
Just a thought, ideally the excalidraw logo should be able to be drawn in the excalidraw software without much difficulty. Without lines or polygons, I don't exactly see how one could achieve this without adding extra objects and making them white with a solid fill to "erase" parts of other objects. Maybe there needs to be more shapes or native types like lines and polygons, but this should be an actual major milestone is to be able to use the software to actually create the logo.

Also, a thought when it comes to lines, what if there is a menu option for extra settings, that can be displayed for each shape/object. IE: when you make a line, there could be an option to make it into an arrow. This would allow for more shapes without having to bloat the shape selection menu. Plus as stated with rotation, the diamond can be replaced with a rotated rectangle.

**Comment by vjeux** [comment]
> Just a thought, ideally the excalidraw logo should be able to be drawn in the excalidraw software without much difficulty.

Yes!

> Maybe there needs to be more shapes or native types like lines and polygons

Yes!

> Also, a thought when it comes to lines, what if there is a menu option for extra settings, that can be displayed for each shape/object

Yes!

**Comment by vjeux** [comment]
I feel like arrows are just lines with the cap being an arrow. We may want to add two shapes for the two since the use cases are usually distinct, but can represent them internally the same way.

Same for segment vs multi-point segment, we should figure out if we can have a single interaction for them. Random idea (please think more before implementing it), if shift is enabled, it lets you keep adding points.

**Comment by dwelle** [comment]
> shift is enabled, it lets you keep adding points.

I had the same idea when we were discussing curved arrows #148 but dismissed it because it felt like a hidden feature that no one will no about (I have some ideas how to tell users what they can do, but that implem will come later).

We should prob discuss this over at #24 or #148 instead of here.

**Comment by vjeux** [comment]
![image](https://user-images.githubusercontent.com/197597/72566405-996c7e80-3868-11ea-8d55-a3b524fdbee7.png)

This is now possible!
