### ISSUE TITLE
Show shortcut keys in the context menu (right aligned)

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw#2440]
Most of the things achievable via shortcuts so it's nice to show them where possible.

**Comment by ReneCode** [comment]
So the context menu would looks like:
```
----------------------------------------------
| Paste                               Cmd+V  |
| Copy to Clipboard as PNG   Shift+Option+C  |
| Copy to Clipboard as SVG                   |
| Select all                          Cmd+A  |
| Toggle Grid Mode                    Cmd+'  |
....
```

Actions without shortcut will leave blank ?

Can I take that issue ?  
The alignment would be a challenge. Using flexbox in ``<ul><li><button> text `` ...

**Comment by dwelle** [comment]
> The alignment would be a challenge. Using flexbox in `<ul><li><button> text ` ...

I'd use `grid`.

**Comment by ReneCode** [comment]
It would be useful to combine functionality from ``ContextMenu`` and ``ShortcutsDialog`` .

thinking about:
```
const getShortcutsFromLabelKey = (labelKey: string) => {
   case "labels.paste": return [getShortcutKey("CtrlOrCmd+V")];
   ....
}
```
Than in the ``ShortcutsDialog.tsx``
```
 <Shortcut
       label={t("labels.paste")}
       shortcuts={[getShortcutKey("CtrlOrCmd+V")]}
 />
```
will change to: 
```
 <Shortcut
       label={t("labels.paste")}
       shortcuts={getShortcutsFromLabelKey("labels.paste")}
 />
```
And in ``ContextMenu.tsx`` something like:
```
const shortcuts = getShortcutsFromLabelKey( action.contextItemLabel );
```

**Comment by dwelle** [comment]
Agreed that we should make a map for it, but not sure if using i18n labels to key by is a good fit. 

An idea is to have a map that looks like: 

```ts
Record<string, {
	labelPath: string; // the i18n path
	shortcuts: string[];
}>
```

Not sure if to make it lazily evaluated as you suggest (i.e. make it into a function call) or whether evaluating it on init is fine, perf-wise (if not, we could also make the `shortcuts` into just string to be passed into `getShortcutKey`).

**Comment by lipis** [comment]
For some shortcuts we have multiple options.. how will that work?

**Comment by dwelle** [comment]
In the contextmenu you mean? We'll use the first one in the list I guess?

**Comment by lipis** [comment]
For the context menu is not an issue.. because from what I can see there is only one way.

**Comment by ReneCode** [comment]
> An idea is to have a map that looks like:
> 
> ```ts
> Record<string, {
> 	labelPath: string; // the i18n path
> 	shortcuts: string[];
> }>
> ```
ok, but what would be the key on that map? action.name would be fine, but ``labels.paste`` or ``labels.delete`` not have a related action. So if using the i18n path that map can be simplified to:
```ts
Record<string,   // the i18n path  e.g.   "labels.paste"
 string[]>       // shortcuts
```
in source:
```ts
const labelPathToShortcuts: Record<string, string[]> = {
  "labels.paste": [getShortcutKey("CtrlOrCmd+V")],
  "labels.delete": [getShortcutKey("Del")],
  ...
};
```

**Comment by dwelle** [comment]
You can just come up with whatever (for a start, I'd just use the second bit of the label: `labels.<shortcurName>`, and if you encounter a name collision, change it to something else).

You can then reuse it everywhere else, including when getting the labels for shortcutDialog and elsewhere (or maybe leave this part for a separate PR).

**Comment by ReneCode** [comment]
if there is no shortcut, there will be no text.

it would look like:
![image](https://user-images.githubusercontent.com/1595098/101684378-9f61e400-3a66-11eb-8de3-10a97aa2353c.png)

**Comment by dwelle** [comment]
:+1: 

Let's decrease the opacity of the shortcut a bit, and make it smaller, so it's less prominent. And probably add a slightly more spacing between it and the text.

**Comment by ReneCode** [comment]
PR #2501 will add shortcuts to the context menu
