### ISSUE TITLE
Arrow attachment zone is too big

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#2446]
![image0](https://user-images.githubusercontent.com/197597/101098314-8ee9cf00-3577-11eb-82db-996defd494b6.jpg)

https://excalidraw.com/#json=4848604376203264,fhIoOWHKJB_1CRcTyGtJSg

cc @xixixao

**Comment by xixixao** [comment]
It's a feature. There should be a cap on the highlight size, and maybe we want to lower it (or add it if it's not there).

**Comment by vjeux** [comment]
I think it would be good to do another pass at the size, it makes sense to scale it with the size of the shape but in this case the size for this relatively small element seems way too big.
