### ISSUE TITLE
Suggestion: Support multiple active whiteboards

### ISSUE THREAD

**Issue by NateRadebaugh** [excalidraw/excalidraw#2447]
I use excalidraw to document a handful of different projects at once. Right now, I have to set up separate chrome profiles to easily switch from one to another, but this is a pretty clunky solution. It would be nice if there was a UX for switching between multiple whiteboards. Longer-term might be nice to sync this to accounts, etc. similar to how Codesandbox works.

Proposal:
1. Add dropdown to UI to switch between "scenes" or add a new scene.

Proposed UI:
![image](https://user-images.githubusercontent.com/130445/101171177-09acfb80-3605-11eb-82a9-cb24ba93ad6c.png)

**Comment by dwelle** [comment]
This falls under https://github.com/excalidraw/excalidraw/issues/1543 so I'll close this as a duplicate.

That said, this, and your suggestion for accounts, will come soon as part of our product focused on teams (but not only).
