### ISSUE TITLE
Somehow the palette menus became Gigantic

### ISSUE THREAD

**Issue by nickmilo** [excalidraw/excalidraw#2449]
I don't know how this happened. It's in Firefox. Chrome is okay. 

The regular `cmd--` and `cmd-+` don't change the palette menu's size, only the content (which is expected behavior). So what changes the palette menu's size??

<img width="1141" alt="Screen Shot 2020-12-04 at 9 42 32 AM" src="https://user-images.githubusercontent.com/35411533/101196147-3832d280-3615-11eb-89bd-a799b27511ca.png">

**Comment by dwelle** [comment]
We implement our own zooming for the canvas scene but every now and then you can mistakenly end up zooming the browser window itself. It's hard to catch all the cases and harder still to prevent the browser from zooming, especially on mobile.

You can reset the zoom from your url bar, in your case by clicking on the `210%`:

![image](https://user-images.githubusercontent.com/5153846/101198595-fb41fc80-3663-11eb-9dce-baa8e6fdfd39.png)

**Comment by nickmilo** [comment]
Thank you!!! Problem solved 💯
