### ISSUE TITLE
Migrate remaining text properties from text to icons

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#2454]
- [ ] fontSize
- [ ] fontFamily
- [ ] fontAlign #2379

**Comment by dwelle** [comment]
Possible icons for fontSize, via @steveruizok 

![](https://user-images.githubusercontent.com/23072548/101261646-ccde2300-3730-11eb-97c7-16efc44bc1f9.png)

Possible icons for fontFamily:

- hand-drawn
	![image](https://user-images.githubusercontent.com/5153846/101261871-74ac1e80-373a-11eb-9d71-be6b63479bd5.png)
	![image](https://user-images.githubusercontent.com/5153846/101261849-5c3c0400-373a-11eb-9496-5b066de24542.png)
	![image](https://user-images.githubusercontent.com/5153846/101261861-66f69900-373a-11eb-8883-65186eea5054.png)

- normal

	![image](https://user-images.githubusercontent.com/5153846/101261883-842b6780-373a-11eb-9664-1dfc154c0a76.png)

- code
	
	![image](https://user-images.githubusercontent.com/5153846/101261839-47f80700-373a-11eb-96f2-a2beabea6323.png)

**Comment by Kartik1397** [comment]
Hi @dwelle, can I work on this issue?

**Comment by dwelle** [comment]
not sure if @steveruizok didn't wanna take this one? If not, you can. But we should agree on which design/icons to use. /cc @lipis

**Comment by lipis** [comment]
For the font size I like the `S`, `M`, `L`, `XL` as for the family one we can start with the suggested ones and see how they look like in practice!

**Comment by mwufi** [comment]
for font, another idea could be: displaying a letter in that font? (wouldn't be an icon tho)

**Comment by lipis** [comment]
Which letter? The last two look very similar..

<img width="207" alt="Screenshot 2020-12-12 at 10 22 51 PM" src="https://user-images.githubusercontent.com/125676/101994114-94a68980-3cc8-11eb-819a-c1c30f59eda3.png">

**Comment by mwufi** [comment]
good point... maybe we can revisit the font thing if we change the normal font to something besides Helvetica :D

**Comment by lipis** [comment]
Yes.. and I don't think that we'll make that change very easily :)

**Comment by hitgo00** [comment]
Hi @lipis, can I work on this issue?

**Comment by lipis** [comment]
Sure you can!
