### ISSUE TITLE
Keep drawing mode

### ISSUE THREAD

**Issue by ahmedash95** [excalidraw/excalidraw#2458]
Hello, 
First of all thanks for this great project. and I'm sorry if the title is not clear enough. 

The problem right now is if you want to keep drawing with the pencil. every time you release the mouse you will have to select the pencil again. because it auto selects the shape once you release the mouse. I think there should be an option to keep drawing and that way you can keep drawing without selecting the pencil every time.

![image](https://user-images.githubusercontent.com/8272048/101268023-32e19f00-375f-11eb-8ede-b1a0f44f2cfa.png)

Thank you!

**Comment by lipis** [comment]
Press on the last icon: the locker :)

**Comment by vjeux** [comment]
We should make the lock by default when enabling the pencil. The current behavior is not intuitive.

**Comment by lipis** [comment]
@vjeux should we enable lock when pressing the draw item.. or just not changing it to selection after it's done without affecting the lock? (Because then we'll have to unlock it if pressed on something else and the lock was automatically enabled)

**Comment by dwelle** [comment]
@lipis yes, this why I stalled on implementing it because it's not clear how this seemingly simple feature should behave :/.

**Comment by lipis** [comment]
or just ignore the lock for the draw tool and not reset it to selection after it's done. Regardless of the lock.

**Comment by ahmedash95** [comment]
I did not notice the lock at all :D my problem is solved now. but +1 for @lipis suggestion. to ignore the lock for the draw tool. 

Regards

**Comment by mwufi** [comment]
@lipis do we... want to implement this? :) I can submit a PR (new contributor here!)

**Comment by lipis** [comment]
@mwufi Sure.. for it.. and we'll iterate over the PR. My idea is to not use the lock icon at all.. just not going back to the selection after the draw is done.

**Comment by dwelle** [comment]
@mwufi still wanna work on this?

**Comment by jaiwanth-v** [comment]
Hi @dwelle, I'd like to implement this. Can I go ahead?

**Comment by dwelle** [comment]
Go ahead @jaiwanth-v! :)

**Comment by jaiwanth-v** [comment]
Okay
