### ISSUE TITLE
Show collaboration stats in the stats dialog

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw#2481]
Add new category `Collaboration`

- [ ] Total users
- [ ] Traffic in
- [ ] Traffic out
- [ ] Ping with the server

For the traffic we can use the [`nFormatter`](https://github.com/excalidraw/excalidraw/blob/master/src/utils.ts#L344) to show per second the average speed.. (no clue how to get that info)

**Comment by ad1992** [comment]
we can use something like [network-speed](https://www.npmjs.com/package/network-speed)?

**Comment by lipis** [comment]
@ad1992  Are you up for it?

**Comment by ad1992** [comment]
Sure will pick it up soon 👍

**Comment by ad1992** [comment]
I have been checking few libraries as network speed doesn't have ping ability.
Listing few of the libraries 👇 
[speedtest-net](https://www.npmjs.com/package/speedtest-net) ~332.1kB (minified+gzipped).
[speed-test](https://www.npmjs.com/package/speed-test) - has only cli support.
[ng-speed-test](https://www.npmjs.com/package/ng-speed-test) - Unfortunately its just for angular.

So I think we can try with two libraries instead 👇 
1. [network-speed](https://www.npmjs.com/package/network-speed) ~ 753bytes (minified+gzipped)
2. [ping-monitror](https://www.npmjs.com/package/ping-monitor) - 2kb(minified + gzipped)
what do you say?

**Comment by lipis** [comment]
I think rolling our own is the way to go.. I just have no idea how :)

**Comment by lipis** [comment]
We basically want to check how fast is the connection to our collaborator server: https://portal.excalidraw.com

**Comment by tomayac** [comment]
Not sure how helpful it would be but you could request a pixel image with a random URL (each time a new one) on each hear beat and set up a `PerformanceObserver` to get stats on a regular basis.

**Comment by lipis** [comment]
Maybe useful one way or another:

- `navigator.connection`
- `window.performance`

**Comment by ad1992** [comment]
> I have been checking few libraries as network speed doesn't have ping ability.
> Listing few of the libraries 👇
> [speedtest-net](https://www.npmjs.com/package/speedtest-net) ~332.1kB (minified+gzipped).
> [speed-test](https://www.npmjs.com/package/speed-test) - has only cli support.
> [ng-speed-test](https://www.npmjs.com/package/ng-speed-test) - Unfortunately its just for angular.
> 
> So I think we can try with two libraries instead 👇
> 
> 1. [network-speed](https://www.npmjs.com/package/network-speed) ~ 753bytes (minified+gzipped)
> 2. [ping-monitror](https://www.npmjs.com/package/ping-monitor) - 2kb(minified + gzipped)
> 
> what do you say?

Sharing my findings here as discussed with @lipis 

There are few challenges for this since we are doing it for the client. 
the library I finalized doesn't seem to work as expected. `ping-monitor` works for node not browser so can't use it. 
tried [is-reachable](https://github.com/sindresorhus/is-reachable#readme) and it's working fine, however, it just checks if endpoint/favicon.io is reachable so we might just want to have our custom code instead of adding a library.

`network-speed` is not maintained and had to add some fix to make it work as it's broken but still, the data it gives doesn't seem to be right so can't trust the values.

**Comment by ad1992** [comment]
`navigator.connection.downlink` is not supported in all browsers so might not be a good option.

One more way could be by loading an image with a known file size then in its onload event measure how much time passed until the event was triggered, and divide this time in the image file size as suggested [here](https://stackoverflow.com/questions/5529718/how-to-detect-internet-speed-in-javascript#answer-5529841).

**Comment by lipis** [comment]
Even if it's not supported in all browsers it's not an issue.. we can simply disable (not showing the traffic) it. It will be mainly for us to monitor and make improvements/optimizations.

**Comment by lipis** [comment]
I like the idea of the image trick.. is basically what @tomayac mentioned in a way.. right?

**Comment by ad1992** [comment]
> Even if it's not supported in all browsers it's not an issue.. we can simply disable (not showing the traffic) it. It will be mainly for us to monitor and make improvements/optimizations.

Yeah, but it will always show max value as `10` for chrome based browsers as that's the max cap.

> I like the idea of the image trick.. is basically what @tomayac mentioned in a way.. right?

I think yeah but calculate speed instead of using perf observer.

**Comment by tomayac** [comment]
> I like the idea of the image trick.. is basically what @tomayac mentioned in a way.. right?

Correct, that's what I was proposing. Here is an [article paragraph](https://web.dev/custom-metrics/#resource-timing-api) that outlines the approach. The trick would be to create images with random URLs regularly to measure any changes over time.

**Comment by tomayac** [comment]
Almost needless to say: for all of these approaches we need to carefully balance wasted bandwidth vs. the actual usefulness of the obtained insights.

**Comment by lipis** [comment]
> Almost needless to say: for all of these approaches we need to carefully balance wasted bandwidth vs. the actual usefulness of the obtained insights.

_Uncertainty principle, also called **Heisenberg** uncertainty principle or indeterminacy principle, statement, articulated (1927) by the German physicist Werner Heisenberg, that the position and the velocity of an object cannot both be measured exactly, at the same time, even in theory._

**Comment by ad1992** [comment]
Will take a shot at it this weekend.

**Comment by lipis** [comment]
The attempt was left in this branch: https://github.com/excalidraw/excalidraw/compare/net-stats
