### ISSUE TITLE
Pinch To Zoom (Trackpad) in Safari on Big Sur Unresponsive

### ISSUE THREAD

**Issue by bx10f** [excalidraw/excalidraw#2482]
The pinch/expand to zoom in/out with a trackpad is unresponsive in Safari 14 on macOS Big Sur.

Issue persists with content blockers (and other plugins) disabled.

Firefox and Chrome work as expected. The hotkeys also work as expected.

**Comment by dwelle** [comment]
Hello, can you check please if the performance is present in this older version: https://excalidraw-e35zd5f5p.vercel.app/ — will help us figure out if this is a recent regression or not.

**Comment by bx10f** [comment]
Pinch/expand to zoom w/ trackpad works for https://excalidraw-e35zd5f5p.vercel.app/ but not for the other.

**Comment by dwelle** [comment]
Ok, let's dig deeper :smile: 

1. https://excalidraw-git-removegesturesupportios.excalidraw.vercel.app/
2. if above has issues, try https://excalidraw-git-dontopenmenumultitouch.excalidraw.vercel.app — if above (1) doesn't have issues, try https://excalidraw-git-fixmiddlehandle.excalidraw.now.sh/

**Comment by bx10f** [comment]
Doesn't pinch zoom:
https://excalidraw-git-removegesturesupportios.excalidraw.vercel.app/
https://excalidraw-git-fixmiddlehandle.excalidraw.now.sh/

Does pinch zoom:
https://excalidraw-git-dontopenmenumultitouch.excalidraw.vercel.app/

**Comment by dwelle** [comment]
Thanks. I thought it's only a performance issue, but you say pinch zoom doesn't work at all?

**Comment by bx10f** [comment]
That's correct. When I do the pinch/expand zoom gesture, nothing happens. It just sits there and doesn't respond. The hotkeys work fine in all scenarios.

**Comment by dwelle** [comment]
I see.

@vjeux looks like https://github.com/excalidraw/excalidraw/pull/2457 broke pinch-zoom on desktop Safari (I assume not on mobile, which you'd have notice). Can anyone with on Safari 13 and touchpad check if it doesn't work there, as well? (/cc @lipis @j-f1). Thanks!

**Comment by vjeux** [comment]
Ohhh interesting, so this is what it was for... I should have done some archeology. @dwelle can you revert my change and I'll find time to fix it correctly.
