### ISSUE TITLE
Can't copy + paste element with text

### ISSUE THREAD

**Issue by hejcz** [excalidraw/excalidraw#249]
I create rectangle and can copy and paste it. Then I add text inside. Can select both of them but Ctrl+V does nothing. Since now I can't paste anything - even empty rectangle.

**Comment by Fausto95** [comment]
Can you try selecting all of the content you want to duplicate and use the context menu to copy & paste(`right click on elements`)?

**Comment by vjeux** [comment]
I had something similar happen, where the focus was lost somewhere and couldn't paste anything. Clicking on the left menu fixed it. I don't have a repro but that's a real issue.

**Comment by Fausto95** [comment]
I could reproduce it by drawing elements then refreshing the page!

**Comment by hejcz** [comment]
@Fausto95 I have this effect after refreshing and after adding some text. I can copy paste bunch of rectangles and circles for example. Once I add text I can't paste anymore.

**Comment by vjeux** [comment]
I submitted a fix. I can't quite repro so I'm not sure if it's actually working.

Please re-open an issue if you can still experience this!
