### ISSUE TITLE
Grouped arrow and text don't behave as a group when moved by other objects

### ISSUE THREAD

**Issue by sojusnik** [excalidraw/excalidraw#2491]
If f.i. an arrow and text are grouped, then they don't behave as a group when the arrow is attached to other objects and has to follow them. In the following video the text should also move with the arrow, when the arrow follows the circle or square:
![excalidraw](https://user-images.githubusercontent.com/1245718/101541472-71629e00-3999-11eb-8a43-3884c3596191.gif)

**Comment by lipis** [comment]
This is some very tricky use case.. not even sure how that should behave. I mean it doesn't affect only the text, if you have multiple elements in a group and the arrows are attached, move only the arrows.

**Comment by sojusnik** [comment]
IMHO, it's very common to label arrows with text, as shown in my example, therefore I definitely would prefer, that the text should be moved with the arrow, when the latter is moved by other objects.

I didn't have a case where my arrow was grouped to other objects than text, but maybe in such a case an exception to my proposed behaviour would do the trick?

**Comment by lipis** [comment]
Even with that simple case, I don't think that group is the way to solve it.. what we need is actually to be able to link text objects to other shapes and arrows in general.. your issue is very close to this one: #1010

**Comment by bolerio** [comment]
+1 for having text (i.e. labels) associated with shapes. Nearly all drawing programs have that. One needs to be armed with a lot of patient to constantly adjust the position of a text when the shapes are moved around.

**Comment by mdroidian** [comment]
I think this is also very close to the use case / issue: https://github.com/excalidraw/excalidraw/issues/3857

**Comment by dwelle** [comment]
I'll close this in favor of https://github.com/excalidraw/excalidraw/issues/2491 — arrows shouldn't be bindable to shapes outside the group.

As for arrow text labels, that's now implemented ✌
