### ISSUE TITLE
Firefox scrolling is slow

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#2497]
Firefox `wheel` event deltas are really tiny in comparison to other browsers.

For example, in Chrome on my mouse, `deltaY` is `166`, whereas in Firefox it is `5`.

Known, WONTFIX issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1057252

(via https://twitter.com/midned/status/1336717295004037123)

**Comment by dwelle** [comment]
Maybe there's some normalization we can do, but would require extensive testing with all possible input modes (touchscreen, touchpad, mouse with continuous, non-discrete wheels...).

**Comment by dwelle** [comment]
The OP said Figma is affected as well, but I can't repro. So if Figma figured it out, we can too.

**Comment by stevesimmons** [comment]
I have the same problem in Firefox: scrolling with laptop trackpad is 20x slowwe in FF than in Chrome.

Also the "?" keyboard help suggests Space + Drag or Wheel + Drag to move the canvas. On my Linux laptop, Space + anything on my trackpad does nothing.

**Comment by adsick** [comment]
Just saw the web app in a video, tried it myself - looks nice but there is this annoying navigation issue when using Firefox + touch pad two-finger gesture panning (zooming&moving around) - it is not only slow but it has a significant delay which ruins the experience.
