### ISSUE TITLE
Free draw

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#25]
Not sure if super useful (I've never been able to draw in a reasonable way using a mouse / touchpad) but may be worth adding

**Comment by GrimTheReaper** [comment]
One thing to note: For those who use drawing tablets, any way to actually read pressure from the browser?

**Comment by pshihn** [comment]
@GrimTheReaper  https://developer.mozilla.org/en-US/docs/Web/API/PointerEvent/pressure

**Comment by GrimTheReaper** [comment]
neat.

**Comment by j-f1** [comment]
See https://github.com/excalidraw/excalidraw/issues/707 for some implementation ideas.

@Zaynex: https://codepen.io/michaelsboost/pen/cnCAL & https://github.com/szimek/signature_pad

@j-f1:
> I think there should be two modes here: create a multiline shape, or do the variable-width cubic-bezier thing the signature pad repo does. They both convey a handwritten style but in different ways.

**Comment by billba** [comment]
Ignoring artistic talent, free draw gets you closest to the physical whiteboard experience: grab a pen, start to draw. For me (and many members of my team who I'm trying to get to use Excalidraw) this is a key must-have feature.

**Comment by lipis** [comment]
> I've never been able to draw in a reasonable way using a mouse / touchpad

But if you have a pen and an iPad is not that hard anymore :)

**Comment by billba** [comment]
Yes exactly, lots of folks have iPads and we have a few Surfaces on my team as well.

**Comment by daneden** [comment]
Just came here to +1 this feature; I got an iPad to use as my second screen and would love to be able to open a shared Excalidraw with folks and doodle on the screen with a pen tool!

**Comment by Miq3l** [comment]
+1 Pen with iPad

**Comment by dwelle** [comment]
We need to figure out how to implement this. In most vector editors, free hand drawing results in a line composed of bezier curves.

![image](https://user-images.githubusercontent.com/5153846/81483342-d0aed300-923d-11ea-9f5b-4aa0ced417a3.png) ![image](https://user-images.githubusercontent.com/5153846/81483337-cab8f200-923d-11ea-83b1-29bdbdbe4a91.png) ![image](https://user-images.githubusercontent.com/5153846/81483345-d4daf080-923d-11ea-9f09-d6e5b385a0ed.png)

Obviously, we wouldn't display the bezier handlers, nor the points. The above screens just show how it will be implemented.

The more irregular the line, the more points are needed:

![image](https://user-images.githubusercontent.com/5153846/81483358-e7edc080-923d-11ea-9980-e1dff4c6ea09.png)

---

Another solution would be to draw pixels on canvas directly. Not sure how we'd convert that to SVG on export, though.

/cc @pshihn @kbariotis

**Comment by pshihn** [comment]
There's no reason to use roughjs for this. 
Bezier curves is the way to go in my opinion and you can render them easily on canvas and svg. See http://perfectionkills.com/exploring-canvas-drawing-techniques/ This page has other techniques as well but the one titled 'bezier curves'  will give you good results with least complexity. 

The other thing to keep in mind - you will collect A LOT of points based on just mouse position sampling. You can reduce the points significantly by running through [Ramer–Douglas–Peucker_algorithm](https://en.wikipedia.org/wiki/Ramer%E2%80%93Douglas%E2%80%93Peucker_algorithm). I have a javascript implementation here which could be adapted: https://github.com/pshihn/bezier-points/blob/master/src/index.ts#L90

**Comment by dwelle** [comment]
> There's no reason to use roughjs for this.

Other than to pipe it through roughjs renderer as if it was a multi-point line, to get a roughjs look?

Otherwise, I agree. I just wanted your opinion on this one :).

**Comment by pshihn** [comment]
I suppose you could run the points through roughjs' curves command like we do with the multi point lines. But with so many points, it is actually hand-drawn rather than emulating it. Why add extra complexity. :) No harm experimenting to see what looks better

**Comment by kbariotis** [comment]
Free draw landed on master. Closing this.
