### ISSUE TITLE
Add separators on context menu

### ISSUE THREAD

**Issue by alexlazovic** [excalidraw/excalidraw#2506]
We could add the separators here to help the user scan more easily through the options. Also, if possible, push the "Delete" option to the bottom and make it red to clearly communicate a destructive operation.

<img width="281" alt="Context Menu" src="https://user-images.githubusercontent.com/10381181/101933023-e45b5700-3bdb-11eb-9620-9dd707deca3d.png">

**Comment by lipis** [comment]
We also have these ones:

<img width="206" alt="Screenshot 2020-12-11 at 7 15 54 PM" src="https://user-images.githubusercontent.com/125676/101933780-597f5a00-3be5-11eb-9ac0-07b3702f54d7.png">
<img width="188" alt="Screenshot 2020-12-11 at 7 15 42 PM" src="https://user-images.githubusercontent.com/125676/101933784-5ab08700-3be5-11eb-947e-e6057178100a.png">

**Comment by dwelle** [comment]
Note for contributors, we'll likely want to finish this PR first: https://github.com/excalidraw/excalidraw/pull/2501

**Comment by Kartik1397** [comment]
Can I work on this?

**Comment by lipis** [comment]
Please do!

**Comment by kbariotis** [comment]
Go for it @Kartik1397, the main component for the context menu is [this one](https://github.com/excalidraw/excalidraw/blob/master/src/components/ContextMenu.tsx) and is being called primarily from the [App like here](https://github.com/excalidraw/excalidraw/blob/master/src/components/App.tsx#L3623).

**Comment by lipis** [comment]
@Kartik1397 If you're working on it.. create an early draft so we can test/review early if there are choices to be made :)

**Comment by Kartik1397** [comment]
Sure @lipis, I will open [WIP] PR as soon as I make some progress.
