### ISSUE TITLE
Additional option properties

### ISSUE THREAD

**Issue by pA1nD** [excalidraw/excalidraw#2513]
It would be great to have additional options to configure the excalidraw UI.

Creating this issue here as a follow-up on https://github.com/excalidraw/excalidraw/issues/1542

General usage today:

```
<Excalidraw 
  options={{...}}
/>
```
### Available options:

| Name                | type    | default | Description                        |
| ------------------- | ------- | ------- | ---------------------------------- |
| zenModeEnabled      | boolean | false   | Decides whether to enable zen mode |
| viewBackgroundColor | string  | #fff    | The background color of Excalidraw |

### Suggested options (to be completed):
| Name        | type    | default | Description                               |
|-------------|---------|---------|-------------------------------------------|
| language    | string  | ?       | Define UI Language                        |
| showLoad    | boolean | true    | Show/Hide loading button                  |
| showSave    | boolean | true    | Show/Hide save button                     |
| showSaveAs  | boolean | true    | Show/Hide save as button                  |
| showExport  | boolean | true    | Show/Hide export button                   |
| showReset   | boolean | true    | Show/Hide reset canvas button             |
| showSession | boolean | true    | Show/Hide start live collaboration button |

Thoughts:
A even deeper integration would be to allow to overwrite the functions the buttons offer.

**Comment by ad1992** [comment]
closing in favor of https://github.com/excalidraw/excalidraw/issues/3012

**Comment by ramesh61285** [comment]
how can hide saveAs or other button by using renderProps ?
