### ISSUE TITLE
align arroweheads schemas

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#2516]
I've completely missed during the review that the schema of `AppState` and `LinearExcalidrawElement` differs.

In `LinearExcalidrawElement` we have:

```ts
startArrowhead: Arrowhead | null;
endArrowhead: Arrowhead | null;
```

while in `AppState` we combine it:

```ts
currentItemArrowheads: {
  start: Arrowhead | null;
  end: Arrowhead | null;
};
```

This makes it hard to work with, and generally introduces and disconnect between the appState and the element type which shouldn't be there.

I propose we either split `currentItemArrowheads` into the two, or combine the element props.

Either way, we'll have to write a migration for this :(.

/cc @steveruizok

**Comment by steveruizok** [comment]
Oh good catch, I switched to `startArrowhead` / end later in that PR to match `startBinding`. I intended to change it everywhere.

**Comment by dwelle** [comment]
@steveruizok Actually, if we split the `currentItemArrowheads` as you suggest, we can dispense with the migration as it'll have almost zero effect on users.

**Comment by steveruizok** [comment]
I was just checking up on this—I think the only ones that are _used_ are startArrowhead and endArrowhead.

**Comment by steveruizok** [comment]
It looks like the `currentItemArrowheads` is just how the arrowheads are stored in client state, so I don't think it will require a migration. (None of the data related to elements would have no change). PR here to fix. https://github.com/excalidraw/excalidraw/pull/2517.
