### ISSUE TITLE
Clicking away when inserting text shouldn't insert another

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#252]
When you insert text via text shape tool, after clicking away it inserts another instead of confirming active text element.

When inserting via double-click, clicking away *does* confirm the text.

I propose aligning it: clicking away should always confirm, not create new text.

Moreover, I propose `Esc` to confirm active text element, too, instead of discarding it (is there an app that discard text upon `Esc`?).

**Comment by vjeux** [comment]
> I propose aligning it: clicking away should always confirm, not create new text.

Agreed, the current behavior looks broken.

> Moreover, I propose Esc to confirm active text element, too, instead of discarding it (is there an app that discard text upon Esc?).

I don't really have a preference.

**Comment by dwelle** [comment]
> > Moreover, I propose Esc to confirm active text element, too, instead of discarding it (is there an app that discard text upon Esc?).
> 
> I don't really have a preference.

Alright, then I'll make it not discard it, because it's dangerous without a confirm, and most apps don't discard.
