### ISSUE TITLE
`isVisibleElement` broken for non-zero canvas offsets

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#2528]
Looks like the [zoom-to-center PR](https://github.com/excalidraw/excalidraw/pull/2319/files#diff-75705f52bb37d26369ac21f8ba57eabe51e5c4fdf90f8f4c7d27fd6f04977821R753-R778) broke the `isVisibleElement()` calculation when the canvas has non-zero offsets (passed from upstream via `offsetLeft`/`offsetTop`).

Note, other helpers may be affected as well, didn't check.

Repro:
1. Go to `src/excalidraw-app/index.tsx` and modify the props passed to `<Excalidraw/>` compo:

	```
	width={dimensions.width / 2}
	height={dimensions.height / 2}
	offsetLeft={dimensions.width / 2}
	offsetTop={dimensions.height / 2}
	```
2. Create an element → it's invisible.

/cc @Jnforja 

We should add tests for it /cc @ad1992

**Comment by Jnforja** [comment]
I'll take care of it. Can you assign this issue to me @dwelle?

**Comment by Jnforja** [comment]
I think we can close this :)
