### ISSUE TITLE
Presentation Mode

### ISSUE THREAD

**Issue by jordwalke** [excalidraw/excalidraw#253]
It would be cool to have a "slides" mode where you can have multiple pages. Then you could hit some kind of a "play" button that full screens it and you can use the arrow keys to navigate the pages, and escape to exit slide mode.
One concern I have is that for a presentation, you might want to be able to use a font that is a _little_ bit more formal/legible (and ability to increase font size), though I do like the look of the font as it is for most use cases.

**Comment by vjeux** [comment]
Another similar request is the ability to have different “artboards” like in sketch. Maybe we could allow artboards and have a way to play full screen between them.

![](http://www.sketchappsources.com/resources/source-image/android-screen-sizes-moniquep.jpg)


Another related thought is that @compulves was asking if we could export excalidraw into a npm component, so that it could be used as a primitive to build something else. Maybe a presentation mode could be built outside of excalidraw.com.

I’m just brainstorming options at this point for how this could be done.

**Comment by bratsos** [comment]
I guess this boils down to 3 main tasks:

- Being able to create multiple canvases (and switch between them)
- Being able to increase the font size (maybe just stretch it with the mouse and increase font-size proportionally with the box's height?)
- Being able to "autoplay" a series of selected canvases at a configurable time interval (aka slideshow)

**Comment by vjeux** [comment]
Another thing we’re going to run into for presentation is that the size of the screen is fixed, but right now excalidraw has an infinite sized screen

**Comment by jeremyscatigna** [comment]
Could I help with this? :)

**Comment by vjeux** [comment]
Go for it!

**Comment by jeremyscatigna** [comment]
So I think the first thing would be to create an Artboard notion, maybe having the option to work on an infinite sized screen or on a fixed size artboard depending on if you work on a presentation or not.
When you enter excalidraw you begin with an infinite sized screen and maybe we could have a section on the left panel to create an Artboard so then you could work on something finite

**Comment by vjeux** [comment]
Yeah, let’s build the notion of artboard first, it’s going to be useful no matter what

**Comment by jeremyscatigna** [comment]
@vjeux would love to get some help on the design of the feature

**Comment by j-f1** [comment]
The way Figma implements this is that it allows you to add a “frame” which contains (and clips) any objects that are dragged into it.

**Comment by dwelle** [comment]
Yes, it should be implemented similarly, and can be reused for [Artboards](https://github.com/excalidraw/excalidraw/issues/253#issuecomment-572011987) or vice versa.

**Comment by sk8Guerra** [comment]
How is the status of this presentation mode? is there something I can help with?

Another way of presenting could be just to hide all configuration menus. 👇🏽

<img width="445" alt="3" src="https://user-images.githubusercontent.com/18681676/95264815-3f905800-07ed-11eb-9c8f-482bb7d2f4aa.png">
<img width="250" alt="1" src="https://user-images.githubusercontent.com/18681676/95264808-3e5f2b00-07ed-11eb-99a3-4e4824fade86.png">

<img width="222" alt="3" src="https://user-images.githubusercontent.com/18681676/95264977-81b99980-07ed-11eb-9d99-999a9ded5ba2.png">
<img width="195" alt="4" src="https://user-images.githubusercontent.com/18681676/95264980-82523000-07ed-11eb-9034-bcc5a02dd89d.png">

This way, the only thing that will show up, will be the sketches.

**Comment by dwelle** [comment]
> How is the status of this presentation mode? is there something I can help with?

Not a priority at this point (if it fits into base Excalidraw at all). It could be made into a plugin when we add support for them #2189.

> Another way of presenting could be just to hide all configuration menus.

This can be partially done today via zen mode (but some menus still show): `Alt-Z` (check keybindings dialog).

**Comment by sk8Guerra** [comment]
@dwelle Thanks for your quick answer.

> Not a priority at this point (if it fits into base Excalidraw at all). It could be made into a plugin when we add support for them #2189.

Sounds good to put this functionality into a plugin. I'll check the proposal.

> This can be partially done today via zen mode (but some menus still show): Alt-Z (check keybindings dialog).

Great! By now I'll present this mode to present.

**Comment by itsShnik** [comment]
@vjeux @dwelle While I understand that this might not be your priority, but having multiple pages (or maybe artboards) would be very useful. Not only will it enhance productivity but many (like me) who rely on excalidraw for diagrams will switch completely to using excalidraw for presentations.

**Comment by whilp** [comment]
@scastiel made a small app:

https://twitter.com/scastiel/status/1327252035218137089
https://github.com/scastiel/excalidraw-slides

!!

**Comment by inwardmovement** [comment]
It seems a next evolution step would be to be able to have hypertext areas in artboards that would lead to other artboards when clicked on, like Adobe XD prototyping feature.

**Comment by sanketsahu** [comment]
Open DevTools, look for .FixedSideContainer & <footer> and apply display: none;

I am good for my talk at the local meetup now. 😅 Thanks!

**Comment by tantaman** [comment]
Been re-writing this ancient presentation builder (https://github.com/tantaman/strut) and have embedded Excalidraw to power the shapes/drawing features.

https://user-images.githubusercontent.com/1009003/143776168-1656f447-6acb-48d6-a2e4-2f37431f9f0f.mp4

**Comment by juandspy** [comment]
any official news about this enhancement?

**Comment by 7flash** [comment]
> Hello - I wanted to express that progressive disclosure animation is super important to how I unpack visuals. It is the one part of story telling that is very necessary when discussing a complex visual where the final product is the necessary "now properly understood" (due to the progressive disclosure animation) is important. Showing non-relevant portions of a complex visual when explaining causes cognitive overload, inattention and lack of understanding.
> 
> In every other narrative in human life we call the effect of "knowing the end before hearing the narrative" a "spoiler" - but in complex visuals, we don't call it that and our explanations suffer.
> 
> Currently I group excalidraw shapes and PNG export them to google slides or powerpoint. Aside from being arduous, the paste is never quite the same size, so I have to fuss with resize to get the slide to look like the excalidraw.
> 
> The only visual diagramming tool I've see that builds in progressive disclosure as the main presentation mode is [Structuriz](https://structurizr.com) by the inventor of the C4 architecture diagramming nomenclature.
> 
> I have actually formulated a methodology I call Visual Microstories around why this is important, why it works and how to do it.
> 
> It would be fantastic if Excalidraw would support simply having grouped objects appear in an order I can edit. I'd be forced to buy it do to the time savings.
> 
> This is not about unhelpful animation features like spinning and bouncing. I use "fade" the most, but even if you only supported "appear" it would be enough. The usage of animation that is rightly called out as awful is when it is used to entertain rather than simply enable progressive disclosure.
> 
> I first iteration might be to support export to google slides where my grouped objects stay as google slides grouped objects and I use it's ability to add animation. Google slides can export to powerpoint.
> 
> I create these explanations for usage by teams, so in the long run I need export to google slides anyway because I can't afford an authors license for all presenters and I personally like PowerPoint's presenter mode a lot - it wouldn't seem to make sense to build out a complete presenter mode that matches slides or powerpoint - at least not initially.
> 
> Here are a couple examples of how progressive disclosure is the most effective way to present complex visuals:
> 
> * https://youtu.be/qAn3-9CrOHA?t=33
> * https://www.youtube.com/watch?v=BzvaHABBiL0&t=1741s
> * https://www.youtube.com/watch?v=BzvaHABBiL0&t=2622s
> 
> And I'm about to video record my first excalidraw visual of this:
> 
> ![CVBG-25-nobrand](https://user-images.githubusercontent.com/11597190/231734466-acb7f3a3-75df-4f43-8165-d4c4a9c09d22.png)

did you try Slideshow script by @zsviczian https://github.com/zsviczian/obsidian-excalidraw-plugin/blob/master/ea-scripts/Slideshow.md

**Comment by rothsandro** [comment]
I made a separate app based on Excalidraw that provides a presentation mode using frames, with a presenter view and PDF export: [Exsliding](https://exsliding.sandroroth.com/)

**Comment by lambdabundesverband** [comment]
> I made a separate app based on Excalidraw that provides a presentation mode using frames, with a presenter view and PDF export: [Exsliding](https://exsliding.sandroroth.com/)

Super cool, tanks :-) that's exactly how I would've imagined the functionality. Is there a chance for this getting implemented in excalidraw core?

**Comment by rothsandro** [comment]
> Is there a chance for this getting implemented in excalidraw core?

That's unlikely. Excalidraw already has a presentation feature but only for Excalidraw+ users: [plus.excalidraw.com](https://plus.excalidraw.com)

**Comment by 7flash** [comment]
In meantime, this is a script I have running in devtools console to play presentation with automatic animated switching slides:

```
async function december1(seq) {
    scenario = [
    ...seq
].map(bit => {
    const [cit, dit] = bit;
    const fit = ea.getSceneElements().find(it => it.type == 'text' && it.text == cit);
    if (!fit) throw 'no fit ' + cit;
    let git;
    const arhit = ea.getSceneElements().filter(it => it.type == 'rectangle' && fit.groupIds.filter(brit => it.groupIds.includes(brit)).length > 0);
    for (const hit of arhit) {
        if (git == null || hit.width * hit.height > git.width * git.height) {
            git = hit;
        }
    }
    if (!git) throw 'no git ' + cit;
    return {
        id: git.id,
        name: cit,
        timeout: dit * 1000,
    }
})
    for (const bit of scenario) {
        const cit = ea.getSceneElements().find(dit => dit.id == bit.id);
        ea.updateScene({
            elements: ea.getSceneElements().map(clit => {
                if (clit.groupIds.filter(brit => cit.groupIds.includes(brit)).length > 0) {
                    clit.opacity = 100;
                }
                return clit;
            })
        })
        await ga.defaultJumpMacro(cit, cit);
        await new Promise(resolve => setTimeout(resolve, bit.timeout));
    }
}

input = [
    ['youtube', 24],
    ['meet', 17],
    ['full', 15],
    ['icp-for-geeks.pdf', 18],
    ['pdf-ai', 18],
    ['full', 12],
    ['[MathAgent]', 16],
    ['ai-assistant', 22],
    ['ai-icp', 29],
    ['full', 32],
]

december1(input)
```

In this example I have added several text elements as seen above within corresponding rectangles and attention time, then

This is result: https://youtu.be/uB9bZn6jjjg

**Comment by 7flash** [comment]
> In meantime, this is a script I have running in devtools console to play presentation with automatic animated switching slides:
> 
> ```
> async function december1(seq) {
>     scenario = [
>     ...seq
> ].map(bit => {
>     const [cit, dit] = bit;
>     const fit = ea.getSceneElements().find(it => it.type == 'text' && it.text == cit);
>     if (!fit) throw 'no fit ' + cit;
>     let git;
>     const arhit = ea.getSceneElements().filter(it => it.type == 'rectangle' && fit.groupIds.filter(brit => it.groupIds.includes(brit)).length > 0);
>     for (const hit of arhit) {
>         if (git == null || hit.width * hit.height > git.width * git.height) {
>             git = hit;
>         }
>     }
>     if (!git) throw 'no git ' + cit;
>     return {
>         id: git.id,
>         name: cit,
>         timeout: dit * 1000,
>     }
> })
>     for (const bit of scenario) {
>         const cit = ea.getSceneElements().find(dit => dit.id == bit.id);
>         ea.updateScene({
>             elements: ea.getSceneElements().map(clit => {
>                 if (clit.groupIds.filter(brit => cit.groupIds.includes(brit)).length > 0) {
>                     clit.opacity = 100;
>                 }
>                 return clit;
>             })
>         })
>         await ga.defaultJumpMacro(cit, cit);
>         await new Promise(resolve => setTimeout(resolve, bit.timeout));
>     }
> }
> 
> input = [
>     ['youtube', 24],
>     ['meet', 17],
>     ['full', 15],
>     ['icp-for-geeks.pdf', 18],
>     ['pdf-ai', 18],
>     ['full', 12],
>     ['[MathAgent]', 16],
>     ['ai-assistant', 22],
>     ['ai-icp', 29],
>     ['full', 32],
> ]
> 
> december1(input)
> ```
> 
> In this example I have added several text elements as seen above within corresponding rectangles and attention time, then
> 
> This is result: https://youtu.be/uB9bZn6jjjg

You should make sure have window.ea = ExcalidrawAPI

and ga.defaultJumpMacro:

```
  private async defaultJumpMacro(input: ExcalidrawElement, output: ExcalidrawElement) {
    const TRANSITION_STEP_COUNT = 100;
    const TRANSITION_DELAY = 1000; //maximum time for transition between slides in milliseconds
    const FRAME_SLEEP = 1; //milliseconds
    const EDIT_ZOOMOUT = 0.7; //70% of original slide zoom, set to a value between 1 and 0
    const FADE_LEVEL = 0.15; //opacity of the slideshow controls after fade delay (value between 0 and 1)

    const getNavigationRect = ({ x1, y1, x2, y2 }) => {
      const { width, height } = ea.getAppState();
      const ratioX = width / Math.abs(x1 - x2);
      const ratioY = height / Math.abs(y1 - y2);
      let ratio = Math.min(Math.max(ratioX, ratioY), 10);

      const scaledWidth = Math.abs(x1 - x2) * ratio;
      const scaledHeight = Math.abs(y1 - y2) * ratio;

      if (scaledWidth > width || scaledHeight > height) {
        ratio = Math.min(width / Math.abs(x1 - x2), height / Math.abs(y1 - y2));
      }

      const deltaX = (width / ratio - Math.abs(x1 - x2)) / 2;
      const deltaY = (height / ratio - Math.abs(y1 - y2)) / 2;

      return {
        left: (x1 < x2 ? x1 : x2) - deltaX,
        top: (y1 < y2 ? y1 : y2) - deltaY,
        right: (x1 < x2 ? x2 : x1) + deltaX,
        bottom: (y1 < y2 ? y2 : y1) + deltaY,
        nextZoom: ratio,
      };
    };

    const sleep = (ms = 0) => new Promise(resolve => setTimeout(resolve, ms));

    let busy = false;
    const scrollToNextRect = async ({ left, top, right, bottom, nextZoom }, steps = TRANSITION_STEP_COUNT) => {
      const startTimer = Date.now();
      let watchdog = 0;
      while (busy && watchdog++ < 15) await sleep(100);
      if (busy && watchdog >= 15) return;
      busy = true;
      ea.updateScene({ appState: { shouldCacheIgnoreZoom: true } });
      const { scrollX, scrollY, zoom } = ea.getAppState();
      const zoomStep = (zoom.value - nextZoom) / steps;
      const xStep = (left + scrollX) / steps;
      const yStep = (top + scrollY) / steps;
      let i = 1;
      while (i <= steps) {
        ea.updateScene({
          appState: {
            scrollX: scrollX - (xStep * i),
            scrollY: scrollY - (yStep * i),
            zoom: { value: zoom.value - zoomStep * i },
          }
        });
        const ellapsed = Date.now() - startTimer;
        if (ellapsed > TRANSITION_DELAY) {
          i = i < steps ? steps : steps + 1;
        } else {
          const timeProgress = ellapsed / TRANSITION_DELAY;
          i = Math.min(Math.round(steps * timeProgress), steps)
          await sleep(FRAME_SLEEP);
        }
      }
      ea.updateScene({ appState: { shouldCacheIgnoreZoom: false } });
      if (false) {
        ea.setActiveTool({ type: "laser" });
      }
      busy = false;
    }

    try {
      const nexit = getNavigationRect({
        x1: output.x,
        y1: output.y,
        x2: output.x + output.width,
        y2: output.y + output.height,
      });
      scrollToNextRect(nexit);
      return 'ok';
    } catch (err) {
      console.error(err);
      return 'empty';
    }
  }
```

originated by 

https://github.com/7flash/obsidian-excalidraw-plugin/blob/f306b2044909bfabed16f6f9bce728737269bd33/ea-scripts/Slideshow.md

**Comment by rothsandro** [comment]
> @rothsandro thats a great implementation. The markdown notes, does it need to be in some specific format?

@deepu105 Yes, each slide should have a heading (level 2) with the name of the frame. I know, not obvious  😅 I should probably add some instructions or a template to download. Or maybe switch to the more common slide separator `---`. Let me know if you have an opinion on this.

```md
# Presentation

## Frame 1

Notes for first frame

## Frame 2

Notes for second frame
```

**Comment by deepu105** [comment]
@rothsandro yes some docs would be great. Also I think `---` is a better separator. Do you have a public repo for this implementation?

**Comment by rothsandro** [comment]
@deepu105 I will likely change the format to `---` when I have time. 

No, the code is too messy atm to be published 😅 For questions / bug reports you can contact me on [Mastodon](https://mstdn.social/@sandroroth), we shouldn't misuse this Excalidraw issue.

**Comment by conorseed** [comment]
> I made a separate app based on Excalidraw that provides a presentation mode using frames, with a presenter view and PDF export: [Exsliding](https://exsliding.sandroroth.com/)

Just stopping by to say thanks to @rothsandro for the export frames to pdf feature. That's perfect for my use case! Would love it in Excalidraw.

**Comment by dz-s** [comment]
> I made a separate app based on Excalidraw that provides a presentation mode using frames, with a presenter view and PDF export: [Exsliding](https://exsliding.sandroroth.com/)

Wow, that's incredible. KUDOS to you.
