### ISSUE TITLE
Cannot copy/paste text from color selection input.

### ISSUE THREAD

**Issue by jordwalke** [excalidraw/excalidraw#254]
If I copy a shape, and then copy some text from an input box (color selection) then try to paste the text in another color input box, it pastes the shape instead of pasting the text that was copied.

**Comment by vjeux** [comment]
We currently have copy/paste handler in the main div and not the canvas, we should either move it to the canvas, which may lose some events as it’s not clear it is focused or skip the behavior if we’re focused on an input text (we already do that in some cases, search for isInputLike).

Definitely a bug we should fix, thanks for reporting

**Comment by dwelle** [comment]
When we're at it, why do we use *actual* clipboard for canvas copy/paste? It has several disadvantages:

1. it asks for clipboard permissions on multiple pastes.
2. it overrides system clipboard with useless JSON data (and potentially overrides whatever useful thing was presently in system clip).

**Comment by vjeux** [comment]
So that we can copy and paste between two tabs of excalidraw. It’s super annoying not to be able to when the use case happens

**Comment by dwelle** [comment]
> So that we can copy and paste between two tabs of excalidraw. It’s super annoying not to be able to when the use case happens

Hmm.. no prob, we can share state between tabs via `localStorage`. Only case when this won't work is when you use 2 different browsers at the same time, but that's an edge case in my opinion.
