### ISSUE TITLE
Suggestion - Add more text modes

### ISSUE THREAD

**Issue by nickzuber** [excalidraw/excalidraw#257]
I'd like to suggest we allow a small amount of preset text modes/sizes:

 - Title (larger font than current default)
 - Regular (current default)
 - Small (smaller font than current default)

This way, we can continue with the spirit of keeping the customization to a minimum (less things for the user to worry about), but we can cover most of the use cases where folks want different sized fonts

**Comment by vjeux** [comment]
Agreed

**Comment by mattbhenley** [comment]
I love this idea. It seems like that is the big thing missing (although, it's a great program)

**Comment by vjeux** [comment]
#278 implemented it!

**Comment by nickzuber** [comment]
That was fast! Awesome stuff 🎉
