### ISSUE TITLE
packages/excalidraw: should hide non-functional buttons

### ISSUE THREAD

**Issue by dai-shi** [excalidraw/excalidraw#2588]
- shareable link button
- start live collaboration button (unless it's supported from the host)

and maybe something else?

cc @ad1992

**Comment by dwelle** [comment]
> start live collaboration button

You mean the collab dialog button? I thought we don't render it unless you supply `onCollabButtonClick` prop.

**Comment by dai-shi** [comment]
> I thought we don't render it unless you supply onCollabButtonClick prop.

Then, it's just a bug.

<img width="320" alt="image" src="https://user-images.githubusercontent.com/490574/102142920-801fe800-3ea6-11eb-96b9-5e06c0f2873a.png">

**Comment by dwelle** [comment]
The second part is now fixed as well (https://github.com/excalidraw/excalidraw/pull/2612), awaiting release.
