### ISSUE TITLE
Using Excalidraw embed without serving the assets from root

### ISSUE THREAD

**Issue by christophepas** [excalidraw/excalidraw#2605]
Hey there, 

I'm using the new `@excalidraw/excalidraw` package currently and am having trouble integrating it as I can't serve the assets straight from my lib and it seems this is currently mandatory.

A possible solution I could see would be to be able to specify an address and serve them from my cdn _for instance, my app runs at slite.com/app, I call the assets at slite.com/cdn/excalidraw-assets _

Cheers & keep up the good work!

**Comment by dwelle** [comment]
We're currently hard-coding the base path into CSS/JS files on build. I've pointed out this could be a problem before (we used to server directly from root), but not sure how to go about this apart from passing the resource path in runtime.

That said, I don't have much experience publishing packages which also need a cdn, so if anyone has any ideas how to do this in practice, that'd be great.

/cc @ad1992

**Comment by ad1992** [comment]
I will look into this. 
 Since our assets are available at cdn https://unpkg.com/browse/@excalidraw/excalidraw@0.1.1/dist/excalidraw-assets/ so theoretically path in format https://unpkg.com/@excalidraw/excalidraw@0.1.1/dist/excalidraw-assets/i18n-ar-SA-json.js should work, so will try it out.

**Comment by ad1992** [comment]
@christianalfoni could you try out `aakansha-excalidraw@0.2.1-cdn`, this will serve assets directly from CDN  https://unpkg.com  so you need not copy it anymore or serve from your CDN.

**Comment by christophepas** [comment]
You meant to mention me, right? 😅  I'll try today!

**Comment by christophepas** [comment]
I might be off but I believe you tried to mention me maybe? 😅 If so, just tried & works on my end!

**Comment by ad1992** [comment]
yep, sorry for the type 😂 . Thanks for confirming 👍

**Comment by christophepas** [comment]
Heyoo @ad1992,  HNY!

Just wanted to know if you were thinking of adding these changes to the main release?

**Comment by dwelle** [comment]
Currently we're blocked on deciding how to support both. I don't think cross-site requests to a 3rd party CDN should be the default. See https://github.com/excalidraw/excalidraw/pull/2614

**Comment by christophepas** [comment]
Sorry if the question is dumb but why the default isn't to serve the assets from excalidraw cdn instead of requiring the developers to duplicate and serve the assets in their project?

**Comment by ad1992** [comment]
@christophepas the main reason being since it's an open-source CDN so we can't assure about its uptime so users would want to host it from their own CDN rather than depending on an open-source cdn.  
I didn't get time to dig deeper to find a better solution. I will look more into it this weekend.

**Comment by dwelle** [comment]
> serve the assets from excalidraw cdn

Excalidraw would have to keep a CDN for each npm version. Right now, we don't have any proprietary CDN as we use Vercel. So we'd have to set it up and maintain it, which would also incur accumulative costs across time.

As such, the PR instead reads the files directly from GH by proxying them through an Unpkg CDN.

But even so, I still don't think forcing all npm consumers to use a 3rd-party (be it Excalidraw or Unpkg) is the way to go — it introduces another potential point of failure + may worsen UX by introducing latency that's out of your control.

> include the assets in the package instead

The npm package doesn't bundle everything because there are many files which we want to lazyload in runtime, such as i18n files. While I can imagine a way where the npm package allows the host app's compiler to handle this shenanigans on its own, I don't know if that's possible in current tool chain (or if it even would be desirable. It may be there's a Webpack plugin for this, but not everyone is using Webpack etc.). If you know of a way, that'd be great.

**Comment by christophepas** [comment]
Thanks for the clear answer. For the CDN, makes total sense. For the other part, lm ask to more knowledgeable folks in my team! (cc @D34THWINGS, @ Calyhre)

**Comment by ad1992** [comment]
Most of the open-source libraries like react, react-router, semantic-ui, etc use [cloudflare](https://cdnjs.com/), though react mentions [unpkg](https://reactjs.org/docs/cdn-links.html) in the docs but its in  Cloudflare as well and pretty much every library you will find in Cloudflare CDN. We should allow the consumers to directly load from CDN as well so they can load it via a script that directly.
And also we should expose dev builds as well so it can help in debugging.
What do you think @dwelle?

**Comment by dwelle** [comment]
Ok, so you wanna do:

- npm, self-host `/assets` (current workflow) + dev builds
- cdnjs (https://cdnjs.cloudflare.com/ajax/libs/excalidraw/x.x.x/umd/excalidraw.min.js) + dev builds

correct?

**Comment by ad1992** [comment]
> Ok, so you wanna do:
> 
> * npm, self-host `/assets` (current workflow) + dev builds

If we are using a CDN then we might want to use the same CDN for npm as well so users need not worry about hosting it themselves etc, we can start with it (as that would be the majority of cases) and then decide if self-hosting is needed and take steps accordingly.  What do you think ?

> * cdnjs (https://cdnjs.cloudflare.com/ajax/libs/excalidraw/x.x.x/umd/excalidraw.min.js) + dev builds
Yes
> 
> correct?

**Comment by dwelle** [comment]
I still am against the default being a CDN, but even if we make it the default, we should definitely offer self-hosting solution. We shouldn't force using 3rd-party solutions. How would that work with PWAs and stuff?
