### ISSUE TITLE
Improve error message when importing image

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#2617]
A co-worker tried to import images and was confused by the error message. It talks about raw scene data but the person didn’t understand it. They wanted to add a normal image.

The left menu disappeared as well which is probably a bug. It reappeared after refresh.

![B636D4F0-236A-4E47-BB2D-BAF332CF054F](https://user-images.githubusercontent.com/197597/102697575-9a7dfc80-41eb-11eb-9759-47c67da969bd.jpeg)

**Comment by dwelle** [comment]
Can't repro the menu disappearing issue.
