### ISSUE TITLE
Better colors

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#262]
The current colors for canvas background, shape background and stroke don't look super good. I'd love if someone could come up with better color palettes so that just clicking on random colors would make diagrams look good

**Comment by pshihn** [comment]
For discussion, here are D3's schemes:
https://github.com/d3/d3-scale-chromatic#api-reference

**Comment by vjeux** [comment]
@pshihn nice, they look great! Do you want to bring them to excalidraw?

**Comment by pshihn** [comment]
Haha, perhaps. Don't want to commit to anything :) If anyone else wants to do this, please go ahead. 
Should decide whether to have different palettes, or pick one of these. I like `schemeTableau10` and `schemePaired` from the D3 schemes.

**Comment by vjeux** [comment]
I think we should pick only one and make it good :)

**Comment by vjeux** [comment]
Actually, I think we should have one per type of colors. Canvas background, shape background and stroke colors should likely all be different.

**Comment by enzoferey** [comment]
@vjeux can I take this one ? Colors are pretty subjective for sure, but pretty confident I can setup something better than what we have and we can further iterate on those palettes 👍

**Comment by vjeux** [comment]
Fixed by #304
