### ISSUE TITLE
Creating a text near the center of a shape should put it in the center

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#264]
It's very common to build a shape (rectangle, ellipse) and want to have a label inside. Right now it's hard to click precisely enough, I almost always have to recenter the text after having written it. Would be nice if we could notice that you are trying to write something at the center and automatically "snap" it to the center.

**Comment by vjeux** [comment]
![ezgif-2-3d1c4e30c479](https://user-images.githubusercontent.com/197597/72002834-08a8f980-31fd-11ea-98c4-e478f1871288.gif)

**Comment by nanot1m** [comment]
> Also the little jump after the text has been written in annoying. I think we should get rid of the ascent behavior and just center it properly.

Fixed in #266
