### ISSUE TITLE
Add support for states in context menu instead of the word toggle

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw#2643]
Let's have something like this 

```
  ...
✔ Grid mode
  Stats for nerds
```

instead of the current menu

```
...
Toggle grid mode
Toggle stats for nerds
```

It's also hard to translate those for no reason.

**Comment by ReneCode** [comment]
That is a very good idea that improves the UI.

can I do it ?

**Comment by ReneCode** [comment]
would look like:


https://user-images.githubusercontent.com/1595098/102724509-43257c80-4310-11eb-9506-2dbd4a7a2c22.mov
