### ISSUE TITLE
Hide shortcuts on mobile view in context menu

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw#2646]
![102725918-1f1f6680-4323-11eb-96be-e4934807a7d9](https://user-images.githubusercontent.com/125676/102773997-cedfed00-4392-11eb-84e2-9d3031be82ba.png)

**Comment by harshilparmar** [comment]
@lipis Can you elaborate more ? I want to take this issue.

**Comment by lipis** [comment]
We should hide the shortcuts when on mobile view.. I updated the description.

**Comment by ReneCode** [comment]
@harshilparmar you can contact me - I've done it before, but it seems that it is lost on merging that red ``delete``item.

**Comment by harshilparmar** [comment]
@lipis I am using ```const isMobile = useIsMobile();``` to check weather its mobile view or not. But Its not getting updated to true 😅
Correct me if I am wrong 😀

**Comment by ReneCode** [comment]
@harshilparmar  use: 
```
@media #{$media-query} {
   ....
 }
```
in ``ContextMenu.scss``

**Comment by harshilparmar** [comment]
@ReneCode  thanks 👍🏼
