### ISSUE TITLE
Request to add Brazilian Portuguese

### ISSUE THREAD

**Issue by mtsgeneroso** [excalidraw/excalidraw#2651]
Hi guys! I'd like to contribute with brazilian portuguese (pt-br) translation. 

Could you add on the list?

**Comment by lipis** [comment]
Should we prefill with our Portuguese translations for it?

**Comment by mtsgeneroso** [comment]
Yes, it will be more easier to translate and adjust.

**Comment by lipis** [comment]
And how would it appear in the language selector?

**Comment by lipis** [comment]
Here you go: https://crowdin.com/translate/excalidraw/10/en-ptbr

**Comment by mtsgeneroso** [comment]
Can be: Português Brasileiro

**Comment by mtsgeneroso** [comment]
> Here you go: https://crowdin.com/translate/excalidraw/10/en-ptbr

Thanks!

**Comment by lipis** [comment]
Happy, translating!
