### ISSUE TITLE
`Browse libraries` link doesn't account for scrollable library

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#2652]
![image](https://user-images.githubusercontent.com/5153846/102794457-b4663d80-43ab-11eb-9139-bb007ad9cc62.png)

![image](https://user-images.githubusercontent.com/5153846/102794461-b6300100-43ab-11eb-8de0-12d37425b775.png)

**Comment by arnoob16** [comment]
Can you elaborate on how can I reproduce this issue, and what should it be like when the issue is resolved?

**Comment by dwelle** [comment]
The link shouldn't have fixed position, covering the scrollbar.

You can reproduce by adding enough items into the library so that scrollbar appears. You can load a few of the libraries from https://libraries.excalidraw.com/ to quickly populate your library.

It's also possible that on your OS (e.g. Mac if you don't use a mouse) you have `overlay` scrollbars, which I learned just yesterday. If that's the case, check this tweet how to temporarily force scrollbars so you can debug: https://twitter.com/JoshWComeau/status/1341819348059643904

**Comment by bodymovin** [comment]
@dwelle would wrapping the two `ToolButton` and the `a` tag in a div to use `display: flex` be a good option?

**Comment by benjakugler96** [comment]
Hello @lipis ! I created this pull request https://github.com/excalidraw/excalidraw/pull/2694 to work around this issue.

![browse-libraries](https://user-images.githubusercontent.com/53273645/103447293-d8f1cd80-4c67-11eb-8be4-2d3d7ae85e61.gif)
