### ISSUE TITLE
Put all media queries in constants and. unify if it makes sense

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw#2678]
<img width="354" alt="Screenshot 2020-12-27 at 3 17 57 PM" src="https://user-images.githubusercontent.com/125676/103171659-b66e4780-4856-11eb-86b2-946c84684b1e.png">

**Comment by dwelle** [comment]
In either case, we should rename the `media-query` variable :smile:

**Comment by lipis** [comment]
> In either case, we should rename the `media-query` variable 😄

Something for @j-f1 to think about :)
