### ISSUE TITLE
no PWA install option via any chrome-based browser, or Safari, in iOS14 or OSX10…

### ISSUE THREAD

**Issue by lwb52** [excalidraw/excalidraw#2688]
VERY odd behavior:
initially: no PWA install option in 3 chrome browsers or Safari under iOS14, or Safari under OSX10…
THEN hours later WAS able to install via OSX10 Chrome—AFTER stopping all ad/pop-up/tracker-blockers (turned them all back on, of course), BUT the ”app” did not function (they both started, but quickly Chrome, then immediately thereafter, the ”app” were unresponsive)…
SO, re-tried Safari in iOS, and DID /successfully/ install an /operable/ instance (hoorah)…

**Comment by dwelle** [comment]
I'm having some issues too. Installing on Chrome (87.0.4280.88) seems not to work and shows as uninstalled until you refresh. Doesn't happen on Edge (Chromium: 87.0.664.66) nor Brave (Chromium: 87.0.4280.101).

/cc @tomayac

Urelated: the UX of opening the website in a PWA isn't the best. I've tried clicking the app and it does nothing, and requires you to click "open" button which I didn't notice at first :smile:.

Just thought I'd let you know my experience.

![chrome_pwa_ux](https://user-images.githubusercontent.com/5153846/103239518-03811500-494e-11eb-8b00-2e673f3ef303.gif)

**Comment by dwelle** [comment]
I'm gonna reopen this because I suddenly can't install PWA on chrome at all (87.0.4280.88).

**Comment by tomayac** [comment]
I just successfully tested this on Chrome 87 on Windows 10, macOS, and Android. It was working fine everywhere. Please be sure to verify via DevTools that the service worker is correctly installed. If you navigate to `chrome://serviceworker-internals/?devtools` and search for `https://excalidraw.com/`, it should look like in the screenshot below.

<img width="792" alt="Screen Shot 2021-01-05 at 11 30 03" src="https://user-images.githubusercontent.com/145676/103635918-848d6d00-4f49-11eb-90ca-b624b3e7162f.png">

**Comment by dwelle** [comment]
SW seems fine, but the PWA doesn't want to install.

![image](https://user-images.githubusercontent.com/5153846/104912922-38045180-598d-11eb-8efa-158e1f8751e1.png)

**Comment by tomayac** [comment]
(If the installation prompt was shown and dismissed before, there may be a cooling down phase until it is shown again.)

**Comment by dwelle** [comment]
By installation prompt you mean this?

![excal_pwa_install_bug](https://user-images.githubusercontent.com/5153846/104921403-87507f00-5999-11eb-927f-772d0f56f0b4.gif)

**Comment by tomayac** [comment]
Exactly. Or the equivalent on mobile.

**Comment by dwelle** [comment]
Ok, so from the gif above you can see it doesn't do anything :(. Clearing site data doesn't work. Don't wanna reinstall chrome right now.

**Comment by tomayac** [comment]
Could you open a new Chrome bug on an affected browser via the link [crbug.com/new](https://crbug.com/new) (so the browser's metadata are part of the description) and paste the bug ID here?

**Comment by lwb52** [comment]
after you closed the issue, i tried again a few days later, and it worked that time! on iOS & osx both!
something is very odd that this issue seems to come & go…

**Comment by dwelle** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=1168110
