### ISSUE TITLE
Context menu position is off

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#269]
On mac, the context menu position is right under the cursor, and there's left padding to accommodate for the cursor position. But for excalidraw it's at a different position

----

Excalidraw
![image](https://user-images.githubusercontent.com/197597/72008655-2a0fe280-3209-11ea-8bec-7d71283a8c3d.png)

Mac
![image](https://user-images.githubusercontent.com/197597/72008665-3136f080-3209-11ea-9e8d-d745d00c5074.png)

**Comment by vjeux** [comment]
Would be nice to also match the colors of mac context menu since it looks so similar.

**Comment by dwelle** [comment]
I'll fix this as part of https://github.com/excalidraw/excalidraw/issues/240. Keep in mind that the contextMenu position will not be guaranteed though, because it often doesn't fit on screen.

**Comment by vjeux** [comment]
Mac os has a very fancy context menu where it puts top/bottom left/right when it overflows. If it’s still to big it scrolls inside.

You can also type and it’s going to select the item you typed...

I wish we could use the native context menu from the web instead of having to rebuild a poor mans version

**Comment by vjeux** [comment]
It’s also not bound by the window viewport
