### ISSUE TITLE
Add Punjabi language

### ISSUE THREAD

**Issue by satnamsvirdi** [excalidraw/excalidraw#2690]
Hello Excalidraw Team, 

I am willing to translate your project into Punjabi (pa_IN). Please provide me further details. 

Regards

**Comment by dwelle** [comment]
Here you go: https://crowdin.com/translate/excalidraw/10/en-pain

How do you say "Punjabi" in Punjabi, for the language picker?

Thanks

**Comment by dwelle** [comment]
@satnamsvirdi still interested?

**Comment by satnamsvirdi** [comment]
Yes, I am fully excited to make Excalidraw speak my language. 

Punjabi is spelled as ਪੰਜਾਬੀ in Gurmukhi script.

**Comment by satnamsvirdi** [comment]
> Here you go: https://crowdin.com/translate/excalidraw/10/en-pain
> 

Thanks @dwelle

**Comment by dwelle** [comment]
Thanks, added.

**Comment by dwelle** [comment]
You can monitor the status of your translation here: https://github.com/excalidraw/excalidraw/pull/2681

![image](https://user-images.githubusercontent.com/5153846/103462443-7bbc5180-4d25-11eb-9039-7fae3f807f87.png)

85% and above will make it to the production

**Comment by satnamsvirdi** [comment]
Balle balle! Translation successfully completed.

**Comment by dwelle** [comment]
Thanks! We'll be merging the translations soon.
