### ISSUE TITLE
Selection is broken after Undo

### ISSUE THREAD

**Issue by ReneCode** [excalidraw/excalidraw#2693]
- select one or multiple elements
- align elements (or anything else on selected elements)
- Undo
- => the selected elements are no more selected, 
 (only one element is selected, or nothing if the page was refreshed before)

https://user-images.githubusercontent.com/1595098/103445928-eb750280-4c79-11eb-96a9-078aaa5ef214.mov

**Comment by dwelle** [comment]
Yea, this is a duplicate of https://github.com/excalidraw/excalidraw/issues/2693 — it seems I wanted to fix that but somehow didn't get time. I'll see what I can do.
