### ISSUE TITLE
Public fonts can't be resolved in CRA@4

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#2695]
```
Error: Can't resolve '/excalidraw-assets/FG_Virgil.woff2'
```

When importing `"@excalidraw/excalidraw/dist/fonts.min.css";` in a CRA@4 app. See https://github.com/facebook/create-react-app/issues/9870

Haven't dug deep. Quick skim of CRA docs it seems they no longer allow referencing root/public paths from CSS files, though as per custom, it's not stated clearly anywhere so you have to read between the lines. Also, no mention in release notes.

For now, I hacked around this by adding the fonts into `src/` and importing them from there, not using the `fonts.min.css` file from the package.

/cc @ad1992

**Comment by ad1992** [comment]
Too many upvotes on the issue so might get fixed in CRA 🤞 . Lets wait for some time and can add a comment stating the font files will need to be added manually to the src folder if using CRA@4. WDYT?

**Comment by dwelle** [comment]
I wouldn't hold my breath on that one. But we can amend the readme to include a workflow for CRA@4, yea.

**Comment by ad1992** [comment]
closing this as this is fixed now in [0.2.1](https://github.com/excalidraw/excalidraw/blob/master/src/packages/excalidraw/CHANGELOG.md#021)
