### ISSUE TITLE
Keyboard shortcuts for shapes

### ISSUE THREAD

**Issue by TimonVS** [excalidraw/excalidraw#27]
Great project! It'd be nice to have keyboard shortcuts so that you don't have to move your mouse up and down the whole time. I'd propose: R for rectangle, O for oval, A for arrow, T for text. This should also feel familiar to people coming from Sketch as it's the same, except for A (A is for Artboard in Sketch, there's no shortcut for creating an arrow).

**Comment by vjeux** [comment]
Agreed! Pull request would be welcome!

Also, we could underline the letter like Windows 95 :)

**Comment by vjeux** [comment]
I didn’t think about artboards but that could be useful

**Comment by bratsos** [comment]
Hey @TimonVS @vjeux @giovannigiordano would you mind if I gave it a shot?

**Comment by vjeux** [comment]
@bratsos go for it!
