### ISSUE TITLE
Area where text is active should be smaller

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#271]
It looks like the entire width of the screen is considered to be the area for text input. This is a bit annoying as I usually click on the right of the text input to dismiss it, and it doesn't work.

It makes sense to have a small buffer (10-20px) but not larger than that

![ezgif-2-16bab2967eeb](https://user-images.githubusercontent.com/197597/72009767-69d7c980-320b-11ea-921f-2d48051585d9.gif)

**Comment by nanot1m** [comment]
I think it can be fixed with two ways:
- input with dynamic width (depends on typed text)
- contenteditable inline-block element

**Comment by vjeux** [comment]
contenteditable inline block element sounds promising

**Comment by vjeux** [comment]
Actually, both seem like they could work.
