### ISSUE TITLE
Add an ability to add comments

### ISSUE THREAD

**Issue by sojusnik** [excalidraw/excalidraw#2710]
Especially when collaborating, the ability to comment elements on a whiteboard would rock!

I'm thinking of comments like it's done in Google Docs or [Nuclino](https://www.nuclino.com/). For the latter see [here](https://help.nuclino.com/a6f815d8-comment-on-content) and [here](https://help.nuclino.com/bf0981c1-comment-on-items) for a good description.

**Comment by Edwin-Baranov** [comment]
Would be so useful to use as a description for specific drawn ui elements

(what is this button suppose to do?, :clicks it:, "This button will add a new entry into the todo list")

**Comment by dwelle** [comment]
We will be adding commenting to Excalidraw Plus since this is something that will if not require, at least heavily benefit from things like authentication.

**Comment by douglasgourlay** [comment]
+1 - for offline reviews in global orgs having a Google Docs style commenting would be huge for me in my org.  Thank you.

**Comment by fredhsu** [comment]
+1 it would really help with async collaboration on docs

**Comment by Cccceb** [comment]
+1

**Comment by ad1992** [comment]
Comments will very soon be available on Excalidraw+ 😊

**Comment by dwelle** [comment]
Forgot to update — comments launched last week https://twitter.com/excalidrawPlus/status/1552670831402225664!

**Comment by CMCDragonkai** [comment]
Is there a way to allow shared links to be commentable? I shared a read-only link (with no edit permissions) but there was no comment button.

**Comment by dwelle** [comment]
@CMCDragonkai not currently, but on the roadmap!

**Comment by GraceG7** [comment]
Is it also possible to attach/link a comment to a particular drawn element/text, would be super helpful when rearranging elements

**Comment by CMCDragonkai** [comment]
Comments should be allowed by anonymous users! What's the status?

**Comment by sharpshooter90** [comment]
Use cases for commenting for me: 

- eg: Inviting other team members for collaboration on a user journey review, currently this is a blocker for our team

**Comment by samgalam** [comment]
For those interested in this feature, I think https://github.com/excalidraw/excalidraw/issues/6227 might be the open issue for adding comments to shared links.
