### ISSUE TITLE
Allow to use Excalidraw to draw over a Map Background (google ou any other option). 

### ISSUE THREAD

**Issue by thierryc** [excalidraw/excalidraw#2711]
Hello, 👋

1st. I love Excalidraw as a designer I like simple and efficient tools. For me, only one tool is missing. 
The vector (draw) tools. (Like Sketch, Glyphs or Illustrator.)

I am working on an open source side project. 
For this project I would like to use Excalidraw as a drawing tools on a map (Google Map or any other map). 

I would like to be able to set and get the coordinate of some object relative to the map (to do calculations). Area, distance... ft, miles, and more. 

How is the best way to "try" do this ?
- Do a fork and to do this very specific feature on my side? 
- Extend Excalidraw in any way ? Plugins...
- Try to add this feature in the Excalidraw and pull a request ?

Any advice is welcome. 

How to add some user data value to the JSON Excalidraw format, for example ?
  
Thank you again for sharing this project.

**Comment by lipis** [comment]
Have you tried our recently release package?

https://github.com/excalidraw/excalidraw/tree/master/src/packages/excalidraw

**Comment by thierryc** [comment]
No, not yet, but I will. That blow my mind. 
Nice and smart.

Thank you.

**Comment by DoisKoh** [comment]
How'd this go? Is it easy to georectify excalidraw drawings onto the map? I'm thinking of trying this myself.
