### ISSUE TITLE
Command clicking should "xor" selection

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#272]
If you have command key held down and click on something, it should add it to the selection it if it wasn't selected or unselect it if it was already selected.

**Comment by dwelle** [comment]
IMO regular `Shift` should work like that (so that you don't need to switch keys when you mis-click). At least that's what Figma & Affinity does.

**Comment by vjeux** [comment]
Oh you are right, keynote does that as well!

**Comment by dwelle** [comment]
@giovannigiordano this is actually still on track.
