### ISSUE TITLE
Allow opening a .excalidraw file from a PWA with a keyboard shortcut

### ISSUE THREAD

**Issue by sojusnik** [excalidraw/excalidraw#2729]
When opening a `.excalidraw` file from a PWA (f.i. created by the Brave browser on Ubuntu) by `ctrl+o`, then the file is opened like [this](https://github.com/excalidraw/excalidraw/discussions/2714#discussioncomment-261437), but I would prefer to see the actual whiteboard.

It seems that `ctrl+o` opens the `open file` dialogue of Brave, but it would be better if the dialogue when clicking on the `open folder` icon (in the top left corner of Excalidraw) gets opened, because in this way the `.excalidraw` file is opened properly.

**Comment by lipis** [comment]
We already overriding the `Ctrl/Cmd+S` for saving the file.. why not for opening as well.
