### ISSUE TITLE
Shift drag should add to selection

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#273]
Right now shift drag unselects everything and makes the selection square, which is not the expected behavior. It should keep the current selection and whatever is under the selection be added to the selection.

Same for command, it should inverse the selection for everything under the new drag area.

**Comment by dwelle** [comment]
Agreed, but let's make the deselect use `Shift`-drag, to align with #272 (if we're in agreement there).

**Comment by vjeux** [comment]
Agreed

**Comment by dwelle** [comment]
Reopening since the PR was reversed.

**Comment by nanot1m** [comment]
Closed by #355
