### ISSUE TITLE
errorSplash strings should use interpolation instead of concateration

### ISSUE THREAD

**Issue by BasixKOR** [excalidraw/excalidraw#2730]
While working on Korean translation I noticed `errorSplash` strings are based on concateration approach, which may not work in all languages due to the differences in ordering of words.

I suggest using string interpolation instead of concatenating a variable between `pre` and `post` strings.

# References
[How to concatenate localized strings mindfully by Shopify](https://ux.shopify.com/how-to-concatenate-localized-strings-mindfully-bcc7b6d4961a)

**Comment by dwelle** [comment]
It's still unclear to me how we'd interpolate JSX elements, esp with event handlers and such:

https://github.com/excalidraw/excalidraw/blob/778e4b08af13a0e1a4a2a4c8052d51af40c87da3/src/components/TopErrorBoundary.tsx#L115-L131

**Comment by Rafi993** [comment]
Hi there, if this issue is not worked on I would like to help.

**Comment by lipis** [comment]
Sure.. if you have ideas!

**Comment by Rafi993** [comment]
Thank you @lipis

**Comment by Rafi993** [comment]
Hi there since I have been caught up in other things. I'm removing my self as assignee from this issue. Thanks for being awesome :)

**Comment by chrismendis** [comment]
Hi there! 👋 I've attempted to partially address this issue and provide an example for further progress: https://github.com/excalidraw/excalidraw/pull/4026.

**Comment by chrismendis** [comment]
> It's still unclear to me how we'd interpolate JSX elements, esp with event handlers and such:
> 
> https://github.com/excalidraw/excalidraw/blob/778e4b08af13a0e1a4a2a4c8052d51af40c87da3/src/components/TopErrorBoundary.tsx#L115-L131

There is unfortunately no easy answer to address these kinds of i18n issues. As the article linked in the issue description suggests, sometimes you need to [redesign a particular bit of UI to unblock i18n efforts](https://ux.shopify.com/how-to-concatenate-localized-strings-mindfully-bcc7b6d4961a#:~:text=If%20this%20is%20the%20case%2C%20we%20might%20consider%20updating%20the%20given%20design%20to%20avoid%20errors%20that%20jeopardize%20our%20localization%20efforts.).

**Comment by dwelle** [comment]
fixed via https://github.com/excalidraw/excalidraw/pull/6564
