### ISSUE TITLE
support non-react component npm package

### ISSUE THREAD

**Issue by Ezr1al** [excalidraw/excalidraw#2743]
Original:

> excalidraw何时会有一套API,让刚接触的人更容易上手，现在的状态下，是否可以把UI和功能分离，比如我不用react，只想使用里面的功能开发自己的运用

Google Translated:

> When will excalidraw have a set of APIs to make it easier for people who are new to contact? In the current state, is it possible to separate the UI from the functions? For example, I don’t use react and just want to use the functions inside to develop my own applications.

**Comment by dwelle** [comment]
Hello. Right now, we don't have any plans to publish a non-React component, as that would be non-trivial. Sorry :).

Btw, next time, please try to post in English (you can use Google translate, as well, if nothing else) as this is English-only repository. Thanks!
