### ISSUE TITLE
FR: Library Item Names On Hover

### ISSUE THREAD

**Issue by qodesmith** [excalidraw/excalidraw#2747]
One thing that would be awesome is if we could have a small description or name pop up when hovering over an item in the library dropdown. I recently added the Apple Devices library, but I couldn't tell which item in the list was what - iPhone 8, iPhone 11, etc.

**Comment by dwelle** [comment]
I agree. It technically falls under this issue: https://github.com/excalidraw/excalidraw/issues/2653 because the prerequisite is for the library authors to give names to individual items

**Comment by lipis** [comment]
Yeah.. I would close this as duplicate.
