### ISSUE TITLE
Locked size and position inside group

### ISSUE THREAD

**Issue by inwardmovement** [excalidraw/excalidraw#2767]
It may be out of scope, but it would have been useful to be able to lock an element's size and position according to another element, so that it doesn't scale when the group it's in is resized.

![ed](https://user-images.githubusercontent.com/9438102/104184965-94f38b00-5414-11eb-9d59-27dc9e5d989f.png)

**Comment by dwelle** [comment]
Note that in your specific case, even if we didn't scale the horizontal line at the end of the arrow, we'd still be scaling its `x` position proportionally. So you'd end up with something like this:

![image](https://user-images.githubusercontent.com/5153846/104186057-2283aa80-5416-11eb-8f4c-412b13e3408b.png)

**Comment by inwardmovement** [comment]
Indeed, I edited my post to cover this.

**Comment by inwardmovement** [comment]
On a more general approach, this may relate to https://github.com/excalidraw/excalidraw/issues/1218 and text resizing inside a group. I think text should not scale with the group it's in by default, like in Microsoft Visio for example.

**Comment by lipis** [comment]
I'll mark initial as out of scope for now.. and as for the second issue.. we don't connect texts to objects yet.. so that's why.
