### ISSUE TITLE
Window zoom decreases text sharpness

### ISSUE THREAD

**Issue by inwardmovement** [excalidraw/excalidraw#2771]
With Excalidraw installed as PWA (Chrome), text elements loose sharpness when the window (web view) is zoomed in. Or is it just a feeling?
Shouldn't text be vectorized so that zooming doesn't decrease text sharpness/definition?

**100%**
![100](https://user-images.githubusercontent.com/9438102/104337131-70bbab00-54f5-11eb-883a-819a7dc7e69c.png)

**125%**
![125](https://user-images.githubusercontent.com/9438102/104337133-70bbab00-54f5-11eb-941e-764094b2655a.png)

**Comment by dwelle** [comment]
In-app rendering is subject to various issues such as sub-pixel rendering and other things that may result in blurriness, mostly out of our control. It shouldn't affect exported output (PNG) though.
