### ISSUE TITLE
Live-collaboration is broken on excalidraw.com

### ISSUE THREAD

**Issue by lunar-debian** [excalidraw/excalidraw#2775]
Hi! Thanks for this great software. Sadly, the live-collaboration feature seems broken at the moment due to CORS issues. When opening the developer console, I get the following errors:

```
Access to XMLHttpRequest at 'https://portal.excalidraw.com/socket.io/?EIO=3&transport=polling&t=XXX&sid=' from origin 'https://excalidraw.com' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.

trycatch.ts:281 POST https://portal.excalidraw.com/socket.io/?EIO=3&transport=polling&t=XXX&sid=XXX net::ERR_FAILED
```

I have observed these errors with both Firefox and Chromium.

**Comment by ecolss** [comment]
Same issue for me, Chrome.

![image](https://user-images.githubusercontent.com/7928604/104474333-cf485e00-55b5-11eb-8552-f643a21d326a.png)

**Comment by dwelle** [comment]
I labeled it as bug, but I actually can't reproduce it. I was able to do so on Firefox, but it seems I was on an old Excalidraw version.

I'm not seeing any CORS errors between `portal.excalidraw.com` and `excalidraw.com` domains :(

**Comment by ecolss** [comment]
> I labeled it as bug, but I actually can't reproduce it. I was able to do so on Firefox, but it seems I was on an old Excalidraw version.
> 
> I'm not seeing any CORS errors between `portal.excalidraw.com` and `excalidraw.com` domains :(

@dwelle  How about trying this on the latest Excalidraw version?

**Comment by dwelle** [comment]
I did. No errors. We've tried collaborating among several team members and had no issues either.

I've now noticed the error message you supplied mentions it's related to `credentials`. Reading up on it, I wonder why it's not reproducing for everyone, as well. I'll see what we can do.

**Comment by dwelle** [comment]
Ok, I think it's because your browser must be stripping request headers. Do you have a browser extension that might be doing that? Some ad blocker or other privacy related extension.

**Comment by lunar-debian** [comment]
Ok, now I'm really confused. We've juste tried it again and it works!

**Comment by dwelle** [comment]
Good. Nevertheless, we'll make some changes that should fix that error in the future.
