### ISSUE TITLE
Github template for raising pull request, bugs and features 

### ISSUE THREAD

**Issue by Rafi993** [excalidraw/excalidraw#2777]
It would be awesome if there was template for raising pull request, bugs and features to bring little more structure to the issues and reduce the load on maintainers.

**Comment by dwelle** [comment]
For PRs, there's CONTRIBUTING guidlines: https://github.com/excalidraw/excalidraw/blob/master/CONTRIBUTING.md

As for templates, the current consensus it it'd add too much friction and we'd end up losing contributors and bug reporters. So far we're not suffering from "too many issues, gotta bring them down" syndrome :).
