### ISSUE TITLE
Ability to specify height, width or radius of inserted shapes

### ISSUE THREAD

**Issue by Rafi993** [excalidraw/excalidraw#2784]
It would be awesome if the user could specify height, width or radius of the inserted shape as numbers or edit those numbers for existing shapes.

**Comment by lipis** [comment]
For now the closest you can do is to open the stats (right click) and see the extra info for your shapes. We were thinking to extend this and be able to edit those values from there in the future..

**Comment by Rafi993** [comment]
Thank you @lipis  I could help with this PR if this is not already being worked on. I was thinking about adding height and width input box in the properties panel.

**Comment by lipis** [comment]
No we don't want to add anything on the properties panel.. and someone is already working on a component for editing stuff, I'll update here for any progress. THank you though.

**Comment by thisisamir98** [comment]
Hi @Rafi993 
I'm working on a component to be used for this, will keep the issue updated.
https://github.com/thisisamir98/slidable-input

**Comment by dwelle** [comment]
closing in favor of https://github.com/excalidraw/excalidraw/issues/5932
