### ISSUE TITLE
(UX/UI) Clarify help menu

### ISSUE THREAD

**Issue by inwardmovement** [excalidraw/excalidraw#2785]
Currently the help menu is labeled as "Keyboard shortcuts", with keyboard shortcuts on top and "useful links" (blog/guides/issue) below (those are even hidden below scroll viewport depending on screen height):
![image](https://user-images.githubusercontent.com/9438102/104568703-b0e37080-5650-11eb-85f2-3c7ced4b8c6b.png)
![image](https://user-images.githubusercontent.com/9438102/104570066-c1481b00-5651-11eb-90c5-75143139bd83.png)

**I think a better flow would be:**
help (ex: question mark) icon > useful links on top > keyboard shortcuts below

**Why?**
- users generally expect a "help" menu providing all kind of help
- keyboard shortcuts nicely fit in a "help" menu in my opinion 
- users should not have to scroll in order to discover and use the "useful links"

I could try to PR for this.

**Comment by lipis** [comment]
I like the idea!

**Comment by lipis** [comment]
@inwardmovement should I assign it to you?

**Comment by inwardmovement** [comment]
> @inwardmovement should I assign it to you?

Ok!
Can you just point out the files where I can find the code related to the keyboard-shortcuts icon and keyboard-shortcuts modal window? I haven't had a look to the codebase yet.

**Comment by lipis** [comment]
Awesome.

This is a good start...

- https://github.com/excalidraw/excalidraw/blob/master/src/components/HelpIcon.tsx
- https://github.com/excalidraw/excalidraw/blob/master/src/components/ShortcutsDialog.tsx

This should eventually change to `HelpDialog` and we can continue giving feedback on your PR. So as soon as you have something ready.. open a draft and we can take it from there.
