### ISSUE TITLE
Convert select option for selecting languages to datalist

### ISSUE THREAD

**Issue by Rafi993** [excalidraw/excalidraw#2789]
Right now the **select** tag is used for selecting language of the app. It makes harder to find if particular language is supported by the app. It would make users life little easier if **datalist** tag is used instead of **select** tag. since user will be able to search supported languages and select them.

![selecting_language](https://user-images.githubusercontent.com/8092120/104600999-b7e59f80-569f-11eb-9f5c-6328e4e6bf99.png)

**Comment by Rafi993** [comment]
Hi there. if this issue is not worked on by anyone I would like to help.

**Comment by lipis** [comment]
Not sure if it's going to be ideal.. plus you can type now as well.. try typing `sve..` or `eng..`

**Comment by dwelle** [comment]
First time I'm hearing about `datalist`. Doesn't seem to work/display correctly on Firefox.

**Comment by Rafi993** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist

**Comment by lipis** [comment]
and you have to delete in order to see other options.. right?

**Comment by lipis** [comment]
Exactly.. using only mouse you can't change language very easily.. I think we can skip it.

![Kapture 2021-01-14 at 16 16 02](https://user-images.githubusercontent.com/125676/104602226-d89ffc00-5683-11eb-81ce-9a85f689fc57.gif)

**Comment by Rafi993** [comment]
> First time I'm hearing about `datalist`. Doesn't seem to work/display correctly on Firefox.

You are right in Firefox data list elements appear only on searching this might not be what is needed.

**Comment by Rafi993** [comment]
Thank you @lipis and @dwelle for your time. Can I close this issue ?
