### ISSUE TITLE
Sync state between tabs on each change

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#2791]
Tabs share localStorage, but we do not sync (render) the changes until re-init. Regular reload will also not sync to other tab's state because current tabs state will be persisted to localStorage on unload, instead. But if you close a tab and reopen again (or open a new tab), it will contain last state from the other tab.

This results in unintuitive and seemingly non-deterministic behavior.

For new users it's not immediately obvious that we share state between tabs, and that they cannot create new drawings by simply opening new tabs.

### proposal

Check localStorage scene version on `focus` and rerender if out of sync.

**Comment by VaughnVernon** [comment]
Thanks @dwelle! Also I suggest a simple naming feature, and the name is the default for image save/download and scene save/download. Then you could use the scene name as a key internal to your single entry document structure (nested documents).

**Comment by bolazec** [comment]
I use excalidraw (which is superb btw) to prepare several drawings at once.
I find the ability to do this essential to my workflow.

If I understand it correctly, the proposed change to sync the state between tabs 
would seem to make my workflow impossible, and as such would be a step backward for me.

Have I understood the implications of the proposed change correctly?

**Comment by VaughnVernon** [comment]
From my perspective, no. It's just the opposite. The problem that I have experienced numerous times is: after drawing into perhaps 6 or so tabs, the most recent drawing (e.g. the 6th) will overwrite the previous 5. If you have not been careful to save the drawing to an .excalidraw file, they are forever gone.

**Comment by dwelle** [comment]
@bolazec  Yes, this issue is only about clarifying what is actually the current behavior: all tabs save to the same localStorage. The fact you don't see it reflected on the scene when switching between tabs is a "bug" that obscures this fact, and makes it prone for you to lose work.

Long-term, we should probably add multi-scene support, though.

**Comment by svenn71** [comment]
The fix of this issue make it only possible to work with *one* drawing at a time and not even look at a different drawing or copy-paste from it. even the filenames are lost.
