### ISSUE TITLE
Command palette similar to vscode 

### ISSUE THREAD

**Issue by Rafi993** [excalidraw/excalidraw#2793]
It would be awesome if there is a [command palette](https://code.visualstudio.com/docs/getstarted/userinterface#_command-palette) similar to vscode. That the user can open with ```ctrl + shift + p``` or ```cmd + shift + p ``` search and select on of the action from the dropdown and enter. Most developers are used to this shortcut (because of vscode, atom, sublime... ).

**Comment by Rafi993** [comment]
If command palette was there new user won't need to remember keyboard shortcuts to achieve different things rather they could open command palette and search and chose the command.

**Comment by lipis** [comment]
That's interesting :)

**Comment by dwelle** [comment]
@lipis https://github.com/excalidraw/excalidraw/issues/869 :smile:

**Comment by lipis** [comment]
Short term memory..

**Comment by lipis** [comment]
So closing as duplicate #869
