### ISSUE TITLE
Live collaboration via email invite?

### ISSUE THREAD

**Issue by ecolss** [excalidraw/excalidraw#2796]
Hey folks, I've been using excalidraw for quite some time and great experience so far.
If I may draw a comparison with Google drawings, I'm having muuuuuuch better user experience on excalidraw than Google drawings.

The only concern is that, typically when using Google drawings, we can invite people by email to collaborate, whereas on excalidraw, we don't have this feature and anyone with the session link can join.

This seems to be a concern to new adopters of excalidraw, and so I'm asking if we could have email-invite on live-collaboration of excalidraw?

Thanks

**Comment by lipis** [comment]
We don't support user authentication and it's not really possible without it. So at the moment this is out of the scope. Of course there are pros and cons in each solution, but right now we don't require any login to use it and the collaboration is end to end encrypted.
