### ISSUE TITLE
Does excalidraw allow export to json, csv or cypher ? 

### ISSUE THREAD

**Issue by steveyang331** [excalidraw/excalidraw#2815]
arrows.app isn't good. 

Does excalidraw allow export to json, csv or cypher ?

**Comment by lipis** [comment]
Not sure what exactly do you mean, but you can export in PNG, SVG or `.excalidraw` files which is basically JSON.

**Comment by steveyang331** [comment]
but it's not directly json file.

the cypher is graph database query language in Neo4j. 

https://neo4j.com/developer/cypher/

**Comment by dwelle** [comment]
> but it's not directly json file.

It's JSON, just have a different extension.

---

Not sure how/why we would wanna export to csv/cypher.

**Comment by steveyang331** [comment]
Bcz http://arrows.app/ is not much good for drawing . and also it's wrong cypher synatx for exporting. 

and some good drawing feature app don't support export to graph database ..
