### ISSUE TITLE
Filepicker Chrome 87.0.4280.77 iPad/iOS looking for images

### ISSUE THREAD

**Issue by lcardito** [excalidraw/excalidraw#2818]
Hey folks!

Seems like the file picker on iPad using Chrome v87.0.4280.77 looks for images and doesn’t allow me to pick json/excalidraw files..

![1DA44D56-6597-4B43-8527-B890953B2834](https://user-images.githubusercontent.com/5428750/104960388-65282280-59d4-11eb-9b78-14d63946c4a4.png)
![8F84C1F6-4D5F-4021-8482-AE4C3B377F05](https://user-images.githubusercontent.com/5428750/104960390-678a7c80-59d4-11eb-8d27-80707488ca7d.png)

suggestions?

**Comment by dwelle** [comment]
The second screenshot I assume comes from clicking on the "browse..." option, and it doesn't allow you to click on the grayed-out items?

/cc @tomayac

**Comment by lcardito** [comment]
Hey @dwelle, thanks for the swift reply! Yes, that's exactly right! Let me know if I can do anything to help out!

**Comment by tomayac** [comment]
I can't reproduce this. I just went though the flow of saving, clearing the canvas, and re-opening, and could select `.json` files in both Safari and Chrome (via the **Browse** option. Have you verified in the Files app that the file is there and has the right extension?

**Comment by lcardito** [comment]
> I can't reproduce this. I just went though the flow of saving, clearing the canvas, and re-opening, and could select `.json` files in both Safari and Chrome (via the **Browse** option. Have you verified in the Files app that the file is there and has the right extension?

Dang! My bad, yes! So in my use case I was saving the file initially as a `.excalidraw` one in GDrive from Chrome on Mac, then tried renaming it but yet could not get it to load on mobile. The trick is saving the file as `.json` initially from the desktop and everything works!

Apologies for the noise, perhaps I've missed some docs or we can add a note somewhere?

**Comment by dwelle** [comment]
Do I understand it correctly that it doesn't work with `.excalidraw`, but works with `.json`? That is a problem, since we're exporting to `.excalidraw` by default, and no one will know they need to manually rename. Shouldn't we reopen?

**Comment by tomayac** [comment]
No worries. While we [try to save as `.excalidraw`](https://github.com/excalidraw/excalidraw/blob/fb4d97ef7867ead32e16cd0fc657a6244a4b8cc8/src/data/json.ts#L40), Safari, which doesn't support the [File System Access API](https://web.dev/file-system-access/), refuses to use that extension and saves as `.json` (the MIME type) instead. We [accept `.json` and `.excalidraw`](https://github.com/excalidraw/excalidraw/blob/fb4d97ef7867ead32e16cd0fc657a6244a4b8cc8/src/data/json.ts#L50) when opening, but again Safari only accepts `.json`.
