### ISSUE TITLE
Buttons for Redo and Undo are absent in the desktop version, looks like they smashed into the "Reset Zoom" button

### ISSUE THREAD

**Issue by ylahdili** [excalidraw/excalidraw#2827]
When using Excalidraw in desktop browser, in the lower-left corner we can see three buttons: the "+" and "-" and one button that when clicked will reset zoom to 100%, but on it you will see the "anticlockwise arrow" icon which is usually for the "undo" action I believe. In fact, I can see no button for "undo" or "redo" unlike in the mobile version _(we still can use Ctrl+Z, Ctrl+Y)_. So I am wondering if it is deliberate not to have these two buttons on desktop version, or did they become hidden/collapsed into the reset zoom button.
![image_2021-01-20_200858](https://user-images.githubusercontent.com/22369170/105209825-55871600-5b5b-11eb-9be9-101eacb87e6b.png)

**Comment by dwelle** [comment]
No, we don't expose undo/redo on purpose because the shortcuts for these are pretty well known, and we try to ensure the UI isn't unnecessarily and overly complex to navigate.

**Comment by dwelle** [comment]
I've opened a PR to add `ctrl-Y` to `redo` which was missing. https://github.com/excalidraw/excalidraw/pull/2831

**Comment by dwelle** [comment]
Btw, if you come up with a better icon for zoom-reset, we're open to PRs.

**Comment by dinhani** [comment]
When using a tablet, there is no way to undo because there is no keyboard to perform CTRL+Z

**Comment by xfeldt** [comment]
> No, we don't expose undo/redo on purpose because the shortcuts for these are pretty well known, and we try to ensure the UI isn't unnecessarily and overly complex to navigate.

Im trying to use excalidraw on an active board at school (runs on Windows) and the absence of the undo-button is a real deal breaker. Can I add it somehow?
