### ISSUE TITLE
Scroll bar shows up even on an empty canvas

### ISSUE THREAD

**Issue by giovannigiordano** [excalidraw/excalidraw#284]
If I start with a blank canvas and I try to scroll up, the scroll is permitted but the scrollbar is not visible.

**Comment by dwelle** [comment]
Or scrolling down. Something is definitely going on.

**Comment by nanot1m** [comment]
It was intentional. Currently scroll only shows when some elements are out of screen.

**Comment by dwelle** [comment]
Mhm. Yea, but I think we're still scrolling even if the scrollbars don't show, and they also show sometimes even on empty canvas, when scrolling a lot. So it should be tightened up.

**Comment by nanot1m** [comment]
> and they also show sometimes even on empty canvas, when scrolling a lot

this should be definitely fixed. Can you say how to reproduce this bug?

**Comment by dwelle** [comment]
For me, wheel-scrolling upwards (downwards it doesn't happen FSR) for some time.

**Comment by nanot1m** [comment]
Scroll is usually bounded to some element of determined size. Canvas has an infinite size, so it's impossible to bound scroll to the canvas directly.

**Comment by dwelle** [comment]
@nanot1m good diagram, though I'm not sure what a *Page* represents here. If it's an element (or a bounding box of all elements), then that makes sense.

Anyway, I agree that the scroll is in relation to the bound box of all elements, and thus it doesn't make sense to consider it in isolation. With that said, we still seem to have some bug of how we handle the scrollbars, then (as my previous comment).

**Comment by vjeux** [comment]
I feel like it's working as intended overall. The only minor issue is that it's possible to see the scrollbar on an empty canvas if you scroll far enough. It's a super tiny detail though.
