### ISSUE TITLE
Remove copy/paste items from contextmenu on desktop

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#2868]
We should remove contextmenu `copy` & `paste` actions for non-mobile screen sizes because it's currently impossible to determine in cross-browser fashion whether a `paste` action will result in anything. As such, we should remove `copy` as well.

The reasoning is, that those actions' keyboard shortcuts are well-known enough to be ok. See discussion below.

### OLD ↓

~~Specifically, we should maybe disable it only for browsers that don't support `clipboard.readText()`, and whose in-app clipboard is empty.~~

~~![image](https://user-images.githubusercontent.com/5153846/106118149-17d64e80-6154-11eb-9796-01d83885b386.png) ![image](https://user-images.githubusercontent.com/5153846/106118160-1a38a880-6154-11eb-9f52-99d283499189.png)~~

~~Just a thought. It may not be a good idea, because `cmd-v` could still result in a successful paste, and this may dissuade users from trying. At the same time, clicking on `paste` when it's not doing anything is a bad UX as well.~~

**Comment by dwelle** [comment]
Another thought: remove copy/paste contextmenu items (at least on Desktop) altogether. This will fix the conundrum. Figma doesn't list them either, and they're pretty well-known keyboard shortcuts.

**Comment by lipis** [comment]
I like the idea of removing them..

**Comment by ad1992** [comment]
+1 for removing it

**Comment by lipis** [comment]
So do we agree to hide it completely if we can't use it? Let's change the title accordingly and add the related labels.

**Comment by h7y** [comment]
I would love to take this up once it's up for grabs :)

**Comment by dwelle** [comment]
Go ahead. Check the updated description for more info.
