### ISSUE TITLE
Allow host to control zenmode / gridmode completely

### ISSUE THREAD

**Issue by ad1992** [excalidraw/excalidraw#2882]
Right now we allow `zenMode` , `gridMode` to be passed via `initialData.appState` but thats only for initial load.
We should allow complete control to the host as well which means a controlled component.

**Use case**
The host can have some action that triggers these modes or if the host always wants to have a UI with any of these modes.

**Solution**
We can allow prop for `zenMode`, `gridMode`, and any such actions and if these props are true we shouldn't render the options in the context menu or buttons to exit these modes as well hence fully controlled by the host. 
And this will also avoid confusion in our codebase of when to consider host prop.

cc @dwelle

**Comment by dwelle** [comment]
Yea, that sounds reasonable.
