### ISSUE TITLE
Allow host to customize the colors for user

### ISSUE THREAD

**Issue by ad1992** [excalidraw/excalidraw#2891]
Right now we have a naive logic to determine the color to be shown for a remote collaborator.

We should also allow the host to pass the color for the user and those colors can be used to render the remote pointer/selection and avatar.

**Usecase**
If the host has some logic of assigning the colors then this will help the host to use the same when using Excalidraw in collab mode as well

Solution
Add an attribute `color` under the `user` prop which will help host to control it
```js
user: { 
  name: string,
  color: { backgroud: string, stroke: string }
}
```

EDIT since we don't use `user` prop anywhere so we can pass color in `collaborator` when updating scene

cc @dwelle

**Comment by dwelle** [comment]
Definitely. In my fork I've hacked it by generating them from `picture` (custom) to make them stable, but it has limitations and isn't generic enough. I wanted to do exactly what you propose and go with `background` & `stroke`, but was lazy.

But when we're add it, let's support images as well on top of `shortName` (initials).

**Comment by ad1992** [comment]
Are you talking about `Avatar`? then we should allow host to render it ?.

**Comment by dwelle** [comment]
Yea. Dunno if it's not easier to just do something like:

```
<Avatar /*...*/>
  {picture ? <img src={picture} alt={shortName} /> : shortName}
</Avatar>
```

instead of forcing users to render the whole avatar

**Comment by ad1992** [comment]
We could accept the `avatarUrl` as a prop and render it.  Since this an addition of a new prop let's track it as a separate issue.

**Comment by lipis** [comment]
Isn't that a bit too much for Excalidraw's philosophy?

**Comment by dwelle** [comment]
This is for consumers of the package, there it's fine.

**Comment by ad1992** [comment]
closed via https://github.com/excalidraw/excalidraw/pull/2943
