### ISSUE TITLE
Feature Request: allow syntax highlighting in `Code` font family

### ISSUE THREAD

**Issue by zalmanlew** [excalidraw/excalidraw#2892]
If the user chooses the Font family of **Code** - it would be nice to also support syntax highlighting for them.

Either they can select a language for the highlighting or it can be auto detected.

I assume some users would want to turn this off, so it should probably be optional.

**Comment by lipis** [comment]
I think we have to get that issue first #1126, before even discussing about if we want to support themes and syntax highlighting.. I'll mark it as out of scope for now.
