### ISSUE TITLE
group resizing broken if off-screen

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#2896]
A funny bug.

Any ideas what's going on @dai-shi?

![excal_bug_group_resize_off_screen](https://user-images.githubusercontent.com/5153846/106519343-6c265900-64db-11eb-953e-6df0b4b8a3b1.gif)

**Comment by dai-shi** [comment]
What!? I don't have any ideas instantly. Have you tried if this is broken from the start?

**Comment by dwelle** [comment]
@dai-shi missed your response. What did you "from the start"?

**Comment by dai-shi** [comment]
I think I meant if this was the issue when we merged the group resizing PR, or something after that.

**Comment by dwelle** [comment]
Yep, looks like it: https://excalidraw-8jy22fi1i.now.sh (https://github.com/excalidraw/excalidraw/pull/1607)

**Comment by dai-shi** [comment]
Thanks. It seems like it happens it it has lines.

**Comment by dai-shi** [comment]
Looked a bit in resizeElements.ts, but found no clue how it happens.

**Comment by dwelle** [comment]
Yeah I spent some time yesterday doing the same with the same results 😅
