### ISSUE TITLE
Too many modes

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#2897]
![image](https://user-images.githubusercontent.com/5153846/106519701-fd95cb00-64db-11eb-9a6e-9ab66a6a42e2.png)

We have too many modes which is confusing.

- Let's rename `grid mode` → `show grid`
- Rename `view mode` → `presentation mode` or `present` (what was the idea behind renaming to view mode @ad1992 ?)

**Comment by ad1992** [comment]
For the present mode we agreed that options like export, save as, lang footer etc might not make sense hence we decided to go with `view mode`. And these options will be helpful in read-only collab mode / shareable links as well. When used in collab  mode/shareable links, present mode might not make sense.

**Comment by h7y** [comment]
What are we gonna do about this? 🤔

**Comment by lipis** [comment]
@h7y Let's start with the easy one: 'Grid mode' -> `Show grid`.

**Comment by kbariotis** [comment]
What's the point of the "View mode"? What purpose serves? Naming should come naturally if we agree on that.

**Comment by dwelle** [comment]
In host apps it's used to prevent edits. On excalidraw.com, the only use case I can come up with is presenting (though in that case I'd remove the rest of nonessential UI).

**Comment by ElectricCookie** [comment]
They also differ in implementation apparently, as zen mode uses a transition and the presentation mode just removes the controls. Maybe just add a setting for customising the controls shown in general to allow some customisability. 
Dark mode button would also fit that menu.
