### ISSUE TITLE
History is saved when resizing or dragging elements

### ISSUE THREAD

**Issue by gmertk** [excalidraw/excalidraw#290]
### Repro:
Select an element.
Resize (or drag) the element.
Then press cmd(ctrl)+z to undo.
See that the element is resizing (or moving) as those states were saved in the history.

### Expected:
We don't want to save history when resizing or dragging an element.

![Jan-09-2020 20-23-27](https://user-images.githubusercontent.com/907281/72089892-fa063380-331d-11ea-9693-c66bcd285841.gif)

**Comment by vjeux** [comment]
This is a recent bug, we had the notion of skipHistory implemented to fix it. Probably because of the big refactor that landed earlier today. cc @dwelle

**Comment by gmertk** [comment]
I think this bug existed even before the refactor. 

Something with the component being updated and resuming the history before onMouse callbacks have a chance to skip it.

**Comment by dwelle** [comment]
Bisecting, it seems it was introduced in https://github.com/excalidraw/excalidraw/pull/248/files

**Comment by gmertk** [comment]
@dwelle that looks suspicious; every mousemove is updating the state and causing the history to resume in componentDidUpdate.

**Comment by vjeux** [comment]
This has been fixed. The other issue has also been fixed. See https://github.com/excalidraw/excalidraw/issues/307
