### ISSUE TITLE
iFrame integration support

### ISSUE THREAD

**Issue by dlitsman** [excalidraw/excalidraw#2902]
I'm integrating Excalidraw as an iframe with generated Excalidraw URL session in it (e.g., https://...com/#room=XXX,YYY). When a user has used Excalidraw before, he/she will see this alert message. Is there a way to suppress it and force a new session in the `#room=XXX,YYY` to be independent?

Is it possible to introduce a URL parameter for that?

Thanks!

![image](https://user-images.githubusercontent.com/963490/106642220-fb854800-657f-11eb-9033-6cb68422b4d8.png)

**Comment by dwelle** [comment]
this should be fixed via https://github.com/excalidraw/excalidraw/issues/2905 — lemme know if the problem persists
