### ISSUE TITLE
Add distance value overlays between elements when users press a modifier key

### ISSUE THREAD

**Issue by rohannair** [excalidraw/excalidraw#2903]
# Problem
When I'm trying to align items for a drawing, I find myself unclear about the spacing between elements. I often fallback to holding `option`, because Figma and Sketch both have this setting. Figma's version can be seen in this gif, with me holding down alt/option: 
![figma](https://user-images.githubusercontent.com/3764902/106649286-578ba480-655f-11eb-894b-2db62c649b7f.gif)

# Potential solution
1. Display the rounded calculated values between polygons
2. Bind this overlay to the `alt`/`option` key
3. [Add guides and snapping](https://github.com/excalidraw/excalidraw/issues/263)

**Comment by dwelle** [comment]
There are two problems with this, one is philosophical, other is technical.

1. Excalidraw philosophy is to enable fast, hand-drawn, rough sketching. As such, we want to limit the amount of information (especially technical) that we display. We do allow for more precision handling when user desires (e.g. grid mode, alignment...), but it's not the default and we try to keep the UI minimal.

	There were similar requests in the past, which we've turned down so far (e.g. https://github.com/excalidraw/excalidraw/issues/2391).

2. On `Alt`, same as Figma, we duplicate the element, but inlike Figma, we duplicate immediately and do not revert even if you release the `Alt` before you commit. So using `Alt` for displaying dimensions wouldn't work. Also, even if we reverted to Figma behavior, you'd still need to release Alt *before* committing at which point the dimensions would likely diverge on commit.

I think your use case is covered by grid mode (right-click the canvas → `grid mode`), especially after we support custom grid size.

**Comment by rohannair** [comment]
You bring up two good points that I had not remotely considered 🙂.

*1. Philosophical*
Makes sense to avoid a full blown analogous feature to Figma et al. I don't even think I want that as much as I want some alignment features that go slightly beyond the existing. I think the grid mode may suffice completely.

*2. Technical*
Makes sense. I would say it's more important to have a binding to `alt`/`option` than to have it on another key, as the latter would break heuristics established by design tools. 

Again, a grid mode would also make sense. I'm less interested in exact values (thus my suggestion to do some rounding, which probably amounts to some light `Math.floor`, and more in having values that I can roughly ballpark.

Lastly, @vjeux [asked for this issue on Twitter](https://twitter.com/rohan10/status/1356615015181221891) so going to hope that this tag suffices to tie together both convos.

**Comment by dwelle** [comment]
Note that grid mode is already implemented in case it wasn't clear :smile: 

![image](https://user-images.githubusercontent.com/5153846/106652767-38f4d000-6596-11eb-8184-34991a7a0fca.png)


> Lastly, @vjeux [asked for this issue on Twitter](https://twitter.com/rohan10/status/1356615015181221891) so going to hope that this tag suffices to tie together both convos.

Yes, that's our modus operandi — we want to discuss and gain consensus on everything before either accepting or rejecting a given feature.

**Comment by rohannair** [comment]
Okay I only just realized that grid mode existed. Let me play with it a bit and see if I can add more colour to this request/issue. Thanks @dwelle.
