### ISSUE TITLE
Losing work due to opening a rooms link

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#2905]
I've had a few people reach out to me because they opened a rooms link and that overrode their localStorage content and they lost valuable work as a result.

Another unrelated use case is when integrating the rooms feature into services, the dialog pops up saying that it's going to override local storage content which is not wanted.

Given those two things, I feel like the solution is when we're in a room environment, we disable reading from and writing to localStorage. This way you can open as many rooms links as you want without fearing of losing your work, we don't have the annoying popup. When you reopen the blank excalidraw you get back the work you were working on.

Thoughts?

**Comment by dwelle** [comment]
How should it work when you stop the session instead of close the tab? Should we show the message *then*?

**Comment by vjeux** [comment]
Yeah, that's not a bad idea to put the message then. This is likely a very minor use case so I'm not too concerned about this.

**Comment by dwelle** [comment]
> Another unrelated use case is when integrating the rooms feature into services, the dialog pops up saying that it's going to override local storage content which is not wanted.

Also, you're talking about `<iframe>` integration, right (https://github.com/excalidraw/excalidraw/issues/2902)? We don't officially support that, and there may be other problems with that approach.

**Comment by vjeux** [comment]
Correct, talking about this one.
