### ISSUE TITLE
Cannot switch tool with pointer

### ISSUE THREAD

**Issue by jakubpawlina** [excalidraw/excalidraw#2907]
# Cannot switch tool with pointer
## Description
It isn't possible to switch from free drawing tool (7) to any other using pointer (mouse nor touch screen). Switching tools using keyboard works correct.

## Screenshots
![2021-02-03 11-28-21](https://user-images.githubusercontent.com/29257057/106734560-73e91900-6613-11eb-93ce-ddb1be111fb5.gif)

## Possible solution
- enable pointer events for menus

**Comment by dwelle** [comment]
Cannot reproduce. What's you browser & OS please?

**Comment by dwelle** [comment]
Nvm, can repro. You first need to draw for it to do that.

**Comment by ad1992** [comment]
looks like this is a regression due to #2856

**Comment by h7y** [comment]
Removing `"disable-pointerEvents": appState.cursorButton === "down"`  on LayerUI.tsx fixes it. Probably `cursorButton ` is not updated when it's up.

**Comment by dwelle** [comment]
I'll take a look on it.
