### ISSUE TITLE
Combination of zen and view mode results in a strange mode

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw#2911]
Steps to reproduce:

- Option + Z: All good
- Option + R: All good (kinda)
- Option + Z: Does nothing
- Option + R: Works
- Option + Z: Works (back to original)

Maybe we shouldn't allow Zen mode when view mode is enabled.

**Comment by lipis** [comment]
Not sure what to do.. but we have to do something :)

**Comment by ad1992** [comment]
Right now we are not allowing mode switch to any other mode when the user enters view mode (Just noticed the exit zen mode button I missed out when zen+readonly :D )

But I agree this makes the behaviour inconsistent among other modes since we are preventing the users from using other modes so let's allow switching between modes even in view mode.[miro]( https://miro.com/app/board/o9J_lWKsD6c=/) also allows switching between modes when in the present mode.

**Comment by ad1992** [comment]
@lipis does this sound good?

**Comment by lipis** [comment]
I would keep it simple: Either View mode or Zen mode... not both :)

- If you enable View mode.. Exit zen mode (if in zen mode)
- If you enable Zen mode.. Exit view mode..


WDYT?

**Comment by ad1992** [comment]
I think it might lead to inconsistent UI and let users wonder why the mode is not showing up if we conditionally hide it. 
Hence I suggested showing the modes every time and let the user decide what to do.
And zen mode + view mode is more of a distraction-free view mode (present mode) which users might want to use.

**Comment by jakubpawlina** [comment]
> I would keep it simple: Either View mode or Zen mode... not both :) @lipis

If so, there is also an option to leave all modes in menu but disable switching between them. When user want to switch to the other mode, there can pop up a tooltip saying that different mode is disabled. To my mind it keeps the UI consistent and simple all the time. A second option is to automatically exit current mode after turning on a different one.

> And zen mode + view mode is more of a distraction-free view mode (present mode) which users might want to use. @ad1992 

I don't know if it's the best option but I also like the mode created by this accident 😄. It creates a useful view that was missing in some way.

<hr />

If the decision isn't unanimous, then maybe it's a good option to users (eg. on Twitter) if they like the mode shown on screenshot (in mind: Zen + View).

What do you think? 🤔

**Comment by ad1992** [comment]
We wouldn't want to disable switching between multiple modes, for example, zen mode + grid mode is a useful mode and similarly grid + view. And zen+view might be useful to people as well(I personally like the zen+view :) )
Hence It would be better to leave it upon users if they want to disable the mode or use it together. 
This way we need not have conditional modes and have a consistent UI as well.
We can iterate over this later as well if needed and take the call accordingly.
What do you say @lipis?

**Comment by lipis** [comment]
Yeah.. sounds good.. let's allow any combination.. from the menu and the shortcuts and see how it goes.
