### ISSUE TITLE
Scrollbars are not working when offsetLeft/offsetRight are set

### ISSUE THREAD

**Issue by christophepas** [excalidraw/excalidraw#2915]
My use case: I'm using the package library, and want to display Excalidraw in a large modal, with `offsetLeft` & `offsetTop` attributes set. 

When doing so, scrollbars display, but we can't select them with the mouse.

Here is a fix that worked in local. I'm not familiar with all the internal engineering of Excalidraw though, not sure if that can be just part of the fix or causing issues on other parts. 
![image](https://user-images.githubusercontent.com/6739099/106805178-aa03b880-6666-11eb-9039-3b8060f3ae1f.png)

**Comment by lipis** [comment]
Would be much easier if you create a PR and we can comment test on it directly..

**Comment by christophepas** [comment]
Sounds good will do that!
