### ISSUE TITLE
hide scrollbars on mobile

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#2923]
On mobile, scrollbars are usually not rendered in web apps. It's pretty hard to grab the scrollbars anyway. More screen real estate.

**Comment by h7y** [comment]
Yeah! This makes sense. "Scroll back to content" makes scrollbars even more redundant. I can take this up if a decision is made! :)

**Comment by lipis** [comment]
I would agree with @dwelle.. we can try removing them on mobile.
