### ISSUE TITLE
Double click on canvas results in error

### ISSUE THREAD

**Issue by hejcz** [excalidraw/excalidraw#293]
Stack from console after double click to add text.

```js
SyntaxError: An invalid or illegal string was specified main.ec845674.chunk.js:1
    V textWysiwyg.tsx:24
    onDoubleClick index.tsx:1122
```

**Comment by dwelle** [comment]
Can't repro :/. What's browser are you using?

**Comment by hejcz** [comment]
Firefox 72.0.1 (64-bit)

**Comment by dwelle** [comment]
Cool, can repro. Thanks.

**Comment by fjaguero** [comment]
@dwelle I'm getting the same error when attempting to add text. Same browser version.

![error](https://user-images.githubusercontent.com/716123/72160203-37220280-33be-11ea-80f1-eb4e43d8ac28.gif)

**Comment by dwelle** [comment]
Gonna push a hotfix for this in a bit.
