### ISSUE TITLE
Concept: layout dependencies (glue points/connectors/attached elements/grouping)

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#294]
I think that we are missing one concept in the current implementation: the ability to have some properties of layout (left, top, width, height) be dependent on some other element.

Two use cases I can see where it would be useful for:
- Arrows that are attached to the side of an element
- Centered text within an element

If we implement this dependency tracking, we would be able to move the element and the dependent elements (arrow or text) would move/resize accordingly.

**Comment by dwelle** [comment]
Arrow attaching is tracked in #157. Not sure about the centered text: do you think [element grouping](https://github.com/excalidraw/excalidraw/issues/173) is enough? I can certainly see the appeal of simply adding a text to center of object (already implemented), and making it stick to that object by default, though.

**Comment by j-f1** [comment]
The way Apple platforms implement this is by allowing any attribute to be set to match any other attribute, with an optional multiplier and constant.

**Comment by lipis** [comment]
The first part is done and the second has a duplicate issue #1010.. so closing this one.
