### ISSUE TITLE
Toast doesn't account for canvas offsets

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#2990]

**Comment by h7y** [comment]
<img width="369" alt="Toast on mobile" src="https://user-images.githubusercontent.com/22396000/107407621-e4ba9480-6b2f-11eb-9135-f429cc2fca18.png">

Are you referring to this?

**Comment by dwelle** [comment]
No, but this not ideal either :). What I was referring to is when you set `offsetLeft`/`offsetRight` props on the `<App/>` (relates to the npm package).

**Comment by ad1992** [comment]
closing this since this should be fixed by now. feel free to reopen if it still exists
