### ISSUE TITLE
Excalidraw package is difficult to embed in a scrollable page

### ISSUE THREAD

**Issue by gaearon** [excalidraw/excalidraw#2991]
I wanted to use the embedded `@excalidraw/excalidraw` package but ran into a number of difficulties. Its built-in CSS seems to assume that it's the only thing on the page — for example, it uses `position: fixed` which means I can't embed it in a scrolling page.

With code like this:
```js
export default function Example() {
  return (
    <>
      <h1>Editor 1</h1>
      <div style={{ border: '1px solid black' }}>
        <Excalidraw width={500} height={500} />
      </div>
      <h1>Editor 2</h1>
      <div style={{ border: '1px solid black' }}>
        <Excalidraw width={500} height={500} />
      </div>
    </>
  );
}
```

I would expect to see a header, a 500x500 editor, another header, and another 500x500 editor. Instead I'm seeing this:

<img width="918" alt="Screenshot 2021-02-07 at 22 45 05" src="https://user-images.githubusercontent.com/810438/107161669-24e60f80-6996-11eb-9d09-7cd165aa24aa.png">

As you can see, containment isn't respected.

I can try to override `.excalidraw` to have `{ position: static !important }` and give `position: relative` to the wrapper.

This provides a decent rendering (which doesn't respect the width, though):

<img width="823" alt="Screenshot 2021-02-07 at 22 50 03" src="https://user-images.githubusercontent.com/810438/107161766-d7b66d80-6996-11eb-8932-448bd474c89c.png">

However, there is another problem — all of the hit testing is wrong because it uses global coordinates. So as soon as I scroll the page, none of the interactions work correctly.

My next thought was to try rendering it inside an `<iframe>` using something like [react-frame-component](https://github.com/ryanseddon/react-frame-component) to fix the hit testing. However, that caused other problems. For example, it appears that CSS is injected at runtime as `<style>` tags. However, they're always injected into `document`, so I can't render it in an iframe without also moving the JS code into that iframe (which I'd rather not). The exact moment when it gets injected doesn't seem deterministic so I can't quite guess when I need to copy the `<style>` tags into each frame. However, even after that, interactions didn't work at all.

I understand that making it work in an iframe while JS runs outside is probably unreasonably complicated. But I do think it would be nice if one could just use `<Excalidraw>` on the page multiple times, especially when scrolling is involved — as you would expect with any `<canvas>` component. Maybe there's some fixes to hit testing that could be done? Finally, I would expect it to respect `width` and `height` for its UI.

I realize this might require extensive changes but wanted to flag it because these problems are very limiting, and a large number of use cases can be unlocked if they are solved.

**Comment by gaearon** [comment]
The practical workaround, for now, would probably be to actually run it as an iframe, move the related JS logic to run _inside_ that frame as a React root, and then build some kind of a bridge to make the component controllable.

**Comment by dwelle** [comment]
Yep, the `position: fixed` is a known issue and tracked here https://github.com/excalidraw/excalidraw/issues/2737. We should start addressing it soon(ish). This use case wasn't in our minds when we started Excalidraw back in the day :).

**Comment by ad1992** [comment]
As for the interactions we will have to compute offsets correctly and also the keyboard shortcuts also will get applied to all instances and history(undo/redo) as well. There might be more things to be handled.
Will soon create a list of all the tasks which are needed to make multiple instances of excalidraw work inside a scrollable container.

**Comment by ad1992** [comment]
Now we support Excalidraw inside a scrollable container  in  [v0.3.1](https://www.npmjs.com/package/@excalidraw/excalidraw) so closing this.  Let's track the issues to support multiple instances of Excalidraw in https://github.com/excalidraw/excalidraw/issues/3043
