### ISSUE TITLE
Add Half-Circle Shape

### ISSUE THREAD

**Issue by MorgeMoensch** [excalidraw/excalidraw#2999]
I would really like to be able to create half-circles in Excalidraw without much work. 

I've been able to create a good half-circle with the Line-Tool: 
![grafik](https://user-images.githubusercontent.com/62468040/107258013-9c21af00-6a3b-11eb-9229-b4a9ab0fd6e8.png)

However, if I start to remove the points to the left or add points between the existing ones to fix the shape to what i want, It does not stay. 

Is there a possibility to do this with the current toolset, or would a new shape be needed?

**Comment by lipis** [comment]
Thanks for the suggestion... but we are not going to add more shapes.. I think the best way is to create it and make add it to the library the best way possible with the current tools.
