### ISSUE TITLE
TS readonly breaks CodeSandbox

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#303]
Just noticed that [CodeSandbox](codesandbox.io/s/github/excalidraw/excalidraw) doesn't compile. From the error, it seems like the `readonly` is the culprit:

![image](https://user-images.githubusercontent.com/5153846/72187941-5a1dd800-33f9-11ea-9d93-fd9969aed38f.png)

I'll investigate tomorrow if we can do something on our end (`readonly` is pretty old TS, so I'm wondering if that's really what's causing the issue), or whether we need to raise an issue on CodeSandbox.

Since no once noticed this yet, how much is development on CodeSandbox a priority (i.e. how quick does this need to be fixed)?

**Comment by vjeux** [comment]
I noticed it but been busy this week and couldn’t contribute anyway. Would be nice to get it fixed

**Comment by dwelle** [comment]
I've created an issue on CodeSandbox: https://github.com/codesandbox/codesandbox-client/issues/3316

**Comment by dwelle** [comment]
The ice is moving (though it [got stuck](https://github.com/codesandbox/codesandbox-client/pull/3318) on some CI failure), so hopefully this will be fixed within a day or so.

**Comment by dwelle** [comment]
Should be up and working!
