### ISSUE TITLE
Zoom in & out with ctrl + scroll is weird on Firefox + Ubuntu

### ISSUE THREAD

**Issue by psarka** [excalidraw/excalidraw#3042]
As stated, zooming in and out with ctrl + mouse wheel scroll is weird on Firefox on Ubuntu.

On zoomed-in values of zoom (>= 110%) it zooms in and out at each discrete "scroll" by increasingly large chunks (for example 340% -> 400% in one "scroll"). This is totally fine.

On normal and zoomed-out values of zoom (<= 100%), however, it only zooms when scrolling vigorously enough. If I scroll regularly, no zooming happens, and I was about to fill a ticket that zooming does not work at all. But it does work, it just needs a lot of speed (infinite scroll type of wheel helps).

It would be nice if it zoomed in & out at each discrite "scroll" for small and regular (<= 100%) values as well.

**Comment by psarka** [comment]
Sketching today and bam, zoom works pefectly!

If you fixed it by accident, please take a note and don't unfix it :)

**Comment by dwelle** [comment]
We haven't done anything :). Maybe Firefox changed how wheel scrolling works.

**Comment by psarka** [comment]
Zooming has been working ever since, so I'll happily close this issue.
