### ISSUE TITLE
Center and align options

### ISSUE THREAD

**Issue by paulomenezes** [excalidraw/excalidraw#305]
I think that will be great to have the options to align and distribute the elements when more than one is selected, similar to Sketch and a more others:

<img width="238" alt="image" src="https://user-images.githubusercontent.com/10564179/72197795-3c09a500-3404-11ea-9168-fd5f46e39398.png">

What do you think?

**Comment by dwelle** [comment]
Closing as duplicate of https://github.com/excalidraw/excalidraw/issues/772 (even though this issue is older, that one is more visible and better illustrated)
