### ISSUE TITLE
Add a shortcut key for nerd stats

### ISSUE THREAD

**Issue by ad1992** [excalidraw/excalidraw#3051]
We should have a shortcut key to toggle nerd stats. May be `option+n`.

cc @lipis

**Comment by lipis** [comment]
Not sure about Nerds though.. it could be expanded in a way to edit values and stuff... so I wouldn't use N for now.. not sure which one though, that's why we left it without.

**Comment by alexkhismatulin** [comment]
Wondering what would nerd stats mean @ad1992

**Comment by ad1992** [comment]
@alexkhismatulin we show some useful stats which you can find in the context menu as shown 👇 
<img width="359" alt="Screenshot 2021-03-03 at 6 27 36 PM" src="https://user-images.githubusercontent.com/11256141/109809883-d7845780-7c4e-11eb-8131-adbaf8bb5c2b.png">

**Comment by alexkhismatulin** [comment]
@ad1992 sounds like a good task to play around with the project. Want me to take it?

**Comment by ad1992** [comment]
Sure @alexkhismatulin. But first, we need to finalize the shortcut key which we can use for showing nerd stats. 
@lipis had some concerns regarding `option+n`. How about `option+/`?
cc @lipis.

**Comment by narendrasinghrathore** [comment]
@lipis Would like to work on it, is it still in discussion ?

**Comment by lipis** [comment]
Yeah maybe `option + /` is fine.. sure go ahead and we'll take it in a PR.

**Comment by g4rry420** [comment]
Hii, not sure if anyone is working on this or not. But if not, Can I work on this issue ?

**Comment by arieldamian** [comment]
It was solved [here](https://github.com/excalidraw/excalidraw/pull/3552). This issue could be closed.
