### ISSUE TITLE
Feature request: editable charts

### ISSUE THREAD

**Issue by tkapler** [excalidraw/excalidraw#3055]
I like the option for pasting data to show the chart, the problem is, that once you paste it, there is no option to edit the data again.
It would be great to have chart type of object, with limited options for edit - same as with some basic chart library - min, max, type of chart, grid, colors... and the data. Imo if you work with data and design e.g. dashboards, it is very rare if you need some extra manual changes.
It would be also great to have more chart options - e.g.use full chart.js library and just apply that rough.js style to the generated output.

**Comment by lipis** [comment]
What you can do is to paste it in a text element, change the data.. cut and paste again..


https://user-images.githubusercontent.com/125676/108088178-d82ec280-7080-11eb-9927-88ad7d08e7ad.mp4


I doubt that we will add anything special to it, as all we do is to generate Excalidraw elements out of it and there is no connection to initial data whatsoever. 

Including full blown charts it's outside of the scope, but we could add more chart options if it makes sense.. (like pie charts were mentioned)

**Comment by dwelle** [comment]
Yes, we've had a few requests for this, but as @lipis stated it's out of scope since we're not a charting library. Apart from all the complexity of making the chart source data editable, there would be a problem of what's the ultimate source of truth — the graph, or the data.

Do note that you can already edit the chart manually (color, individual elements etc.), or you can do what @lipis suggested above.

We're open to adding more chart types, though.

One day when we support plugins, someone could make a full-blown charting library if they so wish :).

**Comment by tkapler** [comment]
ok, i have hoped to include something like https://nagix.github.io/chartjs-plugin-rough/ even on some very basic level for more advanced users, where it would be simple object with three option fields - type, data (csv) and json for options and you would simple generate there the chart by var myBarChart = new Chart(ctx, {
    type: 'bar',
    data: data,
    options: options
}); and do not allow any other modification by the excalidraw itself, so you would not have to care about all the chart possibilities, about any chart issues etc. as it would be simply some optional library. But ok, it could be then the plugin.
BTW some plugins could be also very simple realised by included transparent iframe.

**Comment by tkapler** [comment]
i wonder if you have some feature bounty activity. I am in the czech/slovak data analytics comumunity and i believe, that probably some other companies would want this and we could probably get some money to pay someone to make it. Either to you or to someone else, who could then make a patch with this feature based on your recommendations etc.

**Comment by dwelle** [comment]
It's not just about that. We consider what we add to Excalidraw based on complexity it'll add to the UI/UX, and the codebase (maintenance & complexity costs). We also want to keep the app lean because it's being integrated into other apps and websites.
