### ISSUE TITLE
feature request: Add Icons

### ISSUE THREAD

**Issue by tkapler** [excalidraw/excalidraw#3056]
It would be great, if it would be possible to add icons - include some big set of open source svg icons, e.g. https://icons.getbootstrap.com/.

**Comment by lipis** [comment]
We don't support importing SVGs and having more predefined icons it's outside of the scope for Excalidraw.. 

The closest thing right now is either choose something from the https://libraries.excalidraw.com or simply adding emojis 🐎 🦄
