### ISSUE TITLE
Scroll to content when loading from file or backend

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#306]
When importing from file or restoring canvas from localStorage, we should ensure we scroll to content.

For example, I was importing an example scene for #302, and upon import the content was scrolled way off and I had no idea where it is. This could have been caused by either me scrolling away before import, or the imported scene content being way off the center.

**Comment by Fausto95** [comment]
Agreed!

**Comment by Fausto95** [comment]
I also think that implementing a zoom in/out would be worth it

**Comment by vjeux** [comment]
I believe that we should store all the app state (scroll, latest colors, side panel expansion...) into local storage. Ideally, refreshing the page should restore the exact same state.

**Comment by vjeux** [comment]
localStorage does store the appState, but not from file. We should add appState content within the file. Should be pretty easy to

**Comment by dwelle** [comment]
But, even we should still scroll to content if for whatever reason we restore the state in such a way the we're scrolled off (e.g. when user deliberately or by mistake scrolls off before session close or export).

**Comment by lipis** [comment]
Not when restoring from local storage, because on refresh it should look exactly as it was, but if importing from backend or file it should be centered.

**Comment by dwelle** [comment]
Good point, but it should be smarter than that because you may open excalidraw after a long while and see a blank scene (even considered *you* were the one to scroll off content). So we should store `timestamp` (if we're not already) and scroll to content if older than e.g. 5 seconds (which would indicate it wasn't a browser reload).

**Comment by lipis** [comment]
Too much trouble for not much gain I would say.. who ever draws it it will be visible if tries to export :)

**Comment by dwelle** [comment]
If we implement only one thing, then I'd go with this heuristic: upon `load`, scroll to content if no pixel is visible.

This will ensure that refreshing while not being scrolled off completely doesn't reset position, but at the same time scrolls to content if you're way off. I don't see any potential downside (I can't imagine a use case against this).

**Comment by lipis** [comment]
For those cases we need a button (or shortcut).
