### ISSUE TITLE
Dynamic import not working with Next js app

### ISSUE THREAD

**Issue by hamza1220** [excalidraw/excalidraw#3060]
I am trying to use the package in a Create Next Application according to the instructions on the npm registry [here](https://www.npmjs.com/package/@excalidraw/excalidraw) but I get the error `ChunkLoadError: Loading chunk 736 failed`

sandbox [here](https://codesandbox.io/s/nextjs-boilerplate-forked-eewlu)

**Comment by cnollite** [comment]
The same error is currently throw in the [demo sandbox](https://codesandbox.io/s/excalidraw-ehlz3) of [@excalidraw/excalidraw](https://www.npmjs.com/package/@excalidraw/excalidraw/v/0.3.1).

**Comment by ad1992** [comment]
The codesandbox error in demo is due to https://github.com/codesandbox/codesandbox-client/issues/5401, downloading in local will work fine for dev/ prod builds.

For next js can you try with updating `__webpack_public_path__`  in local ?

**Comment by ad1992** [comment]
closed via #3068
