### ISSUE TITLE
Allow host to decide if elements should be scrolled to centered on mount

### ISSUE THREAD

**Issue by ad1992** [excalidraw/excalidraw#3062]
Right now scroll to center the elements on = mount but this shouldn't be mandatory for host apps as it can be confusing.

**Use case**
If the host has tabs and on switching tabs Excalidraw is mounted / unmounted, it will confuse the host as the position of elements will suddenly change.

**Solution**
There can be multiple approaches:

1. Accept a prop `scrollToCenterOnMount` to decide whether we should scroll to center.
2. Let the host decide whether elements should be centered completely since we expose the API.

Also, should we scroll to center when not needed (elements are not out of view port)  in Excalidraw for example  below case we shouldn't👇 

![Excalidraw _ Hand-drawn look   feel • Collaborative • Secure (4)](https://user-images.githubusercontent.com/11256141/108417352-dcf89f80-7255-11eb-806a-1344da0a7569.gif)

cc @dwelle

**Comment by dwelle** [comment]
What I'm doing in my fork is supporting `initialData.scrollX` & `initialData.scrollY`.

**Comment by ad1992** [comment]
@dwelle you mean the host will have to keep the last value of scrollX and scrollY ? Instead shouldn't excalidraw scroll only if elements out of view port ?

**Comment by dwelle** [comment]
> Instead shouldn't excalidraw scroll only if elements out of view port ?

Yea, that's a separate issue, but I agree.

> you mean the host will have to keep the last value of scrollX and scrollY 

Yes. I'd rather make it explicit. If we instead add `scrollToCenterOnMount`, then users will have to both set `scrollToCenterOnMount: false` and modify `initialData.appState.scrollX/Y` which seems weird. And you'll still need to cache `scrollX/Y` positions anyway, unless you keep `scene` state around after unmount.

**Comment by ad1992** [comment]
Right host will anyways need to cache scrollx , scrolly so that viewport coords are correctly ported to scene coords which is definately needed and supporting `initialData.scrollX` and `initialData.scrollY` so that this is preferred over calculating scroll to center. This is what you mean right?
But what I am wondering is if we allow the scroll to center only when elements out of viewport then will `initialData.scrollX` and `initialData.scrollY`  be needed?

**Comment by dwelle** [comment]
> But what I am wondering is if we allow the scroll to center only when elements out of viewport then will `initialData.scrollX` and `initialData.scrollY` be needed?

Question is, where are you caching those scene last positions then? From what I understand, you're talking about keeping them in the `initialData.appState`, but if they're not there, or they're ovewritten by remote state etc.?

**Comment by ad1992** [comment]
the host will anyways cache the `appState.scrollX, appState.scrollY` be it in local storage or DB or some backend. And Excalidraw will scroll to center only if out of viewport so that is what's expected.
Under what circumstances these values will not be there is what I am not getting or am I missing something?

**Comment by ad1992** [comment]
But I think we will still need to have support for allowing the host to decide whether elements should be centered as there can be cases like when a user starts drawing few elements go out of the viewport(as shown 👇 ) and few are in viewport then it will be confusing if scroll to center changes the element.
![Excalidraw (12)](https://user-images.githubusercontent.com/11256141/108530589-bf7e1100-72fb-11eb-9e88-bea09558a81f.gif)

So now the question is do we rely on `appState.scrollX & appState.scrollY` or we need `initialData.scrollX` and initialData.scrollY`. 
@dwelle once you confirm the scenario you are thinking of we can finalize the API :)

**Comment by dwelle** [comment]
What am I looking at above? When does the scroll-to-center happen? I'm not sure what case you're talking about, which would not be solved with supplying `initialData.scrollX/Y`.

I understand that supplying `initialData.scrollX/Y` *just* to disable scroll-to-center would be an overkill, but only provided that you would want to disable the scroll-to-center and leave the `scrollX/Y` position to be "random" (i.e. whatever the `initialData.appState.scrollX/Y` happens to have set).

> Under what circumstances these values will not be there is what I am not getting or am I missing something?

Usually, you don't persist `appState.scrollX/Y` to backend because it's client-specific (in multi-user environments).

**Comment by ad1992** [comment]
The above GIF is to simulate the below scenario
1. User draws some elements
2. Scrolls so it goes out of view port (see scroll to content after drawing 2 shapes)
3. user draws again.
4. Now Excalidraw mounts again (which can be due to tab switch for example)

All cases would be solvable with `initialData.scrollX/Y.` as mentioned above but what I meant is since the data will anyways be saved somewhere in frontend example local storage / indexdb then the `appState.scrollX/Y` would be the same as `initialData.scrollX/Y`

so we have two approaches for this
1. Pass  `initialData.appState.scrollX/Y` and also one more attribute `initialData.scrollToCenter` which decides if to scroll to center
2. Pass `initialData.scrollX/Y` and check if these supplied then dont scroll to center.

**Comment by dwelle** [comment]
How come in step (4) Excalidraw mounts again?

**Comment by ad1992** [comment]
Not really, it can happen for example if you have multiple tabs where each tab opens up a different view and for whiteboard you have a tab/modal which opens Excalidraw so it mounts and on close, it will unmount.

**Comment by ad1992** [comment]
Also to add to this since the above GIF is of Excalidraw App, on refresh, it is confusing so we might want to consider whether centering is really needed on mount as it can be confusing when elements / postion of elements change on refresh.

Any specific reason we started scrolling to center on mount?

As a user, it felt confusing to me when scrolled to the center on refresh as it's not possible to predict which elements will show up and where they will show up.

**Comment by dwelle** [comment]
> Not really, it can happen for example if you have multiple tabs where each tab opens up a different view and for whiteboard you have a tab/modal which opens Excalidraw so it mounts and on close, it will unmount.

But that shouldn't happen *while* the component is still mounted and rendered on the screen. If it does, that's a bug and would affect UX either way.

> Also to add to this since the above GIF is of Excalidraw App, on refresh, it is confusing so we might want to consider whether centering is really needed on mount as it can be confusing when elements / postion of elements change on refresh.

I think I argued for the "refresh shouldn't scroll to center" case once but we disregarded it as an edge case.

> Any specific reason we started scrolling to center on mount?
>
> As a user, it felt confusing to me when scrolled to the center on refresh as it's not possible to predict which elements will show up and where they will show up.

I agree with you on this. Let's make it opt-in only which we'll use for we load collab/link scenes. Does that make sense?

We can also add the `initialData.scrollX/Y` on top, either in the same PR or another one.

So in a way, yes, we'll end up with all of the above after all, but instead of opt-out, it'll be opt-in.

**Comment by ad1992** [comment]
> > Not really, it can happen for example if you have multiple tabs where each tab opens up a different view and for whiteboard you have a tab/modal which opens Excalidraw so it mounts and on close, it will unmount.
> 
> But that shouldn't happen _while_ the component is still mounted and rendered on the screen. If it does, that's a bug and would affect UX either way.
> 
What shouldn't happen is little unclear. Basically, I am talking about use cases where Excal can be mounted/unmounted on some action clicks which can be due to update in route for example.

> > Also to add to this since the above GIF is of Excalidraw App, on refresh, it is confusing so we might want to consider whether centering is really needed on mount as it can be confusing when elements / postion of elements change on refresh.
> 
> I think I argued for the "refresh shouldn't scroll to center" case once but we disregarded it as an edge case.

do you mean then we can stop scrolling to center on refresh ?

> > Any specific reason we started scrolling to center on mount?
> > As a user, it felt confusing to me when scrolled to the center on refresh as it's not possible to predict which elements will show up and where they will show up.
> 
> I agree with you on this. Let's make it opt-in only which we'll use when we load collab/link scenes. Does that make sense?
> 
Do you mean we should trigger scroll to center from excal app instead and remove calculate scroll to center from excal core ?
Then yes does make sense we should do that.

> We can also add the `initialData.scrollX/Y` on top, either in the same PR or another one.

If we do the above one (letting the host handle scroll to center then we might not need this right ?)

**Comment by dwelle** [comment]
> Do you mean we should trigger scroll to center from excal app instead and remove calculate scroll to center from excal core ? Then yes does make sense we should do that.

I'd not remove it from core coz people will want to use that as well (me included), and it's a non-trivial piece of code. Let's just have `scrollToCenter` prop, defaulting to `false`.

Now that I think about it, I'd maybe make the api as such:

```
scrollPosition: "center" | { x: number; y: number }
```

That's because if we supported `scrollToCenter: boolean` and `initialData.scrollX/Y`, there would be conflicts if you supplied to both. So we'd end up preventing to supply both at the same time, and it'd be annoying for host apps to make both props conditional.

**Comment by ad1992** [comment]
> > Do you mean we should trigger scroll to center from excal app instead and remove calculate scroll to center from excal core ? Then yes does make sense we should do that.
> 
> I'd not remove it from core coz people will want to use that as well (me included), and it's a non-trivial piece of code. Let's just have `scrollToCenter` prop, defaulting to `false`.
> 
I was suggesting to stop calling scroll to center on mount in core so that host can call the API `setScrollToCenter` whenever needed via refs. This will fix the refresh issue in excal app as well.
But I am ok with `scrollToCenter` prop as well but let's have it inside `initialData` so it is clear it's used once. For other times host can call the API `setScrollToCenter`.

> Now that I think about it, I'd maybe make the api as such:
> 
> ```
> scrollTo?: "center" | { x: number; y: number }
> ```
> 
> That's because if we supported `scrollToCenter: boolean` and `initialData.scrollX/Y`, there would be conflicts if you supplied both. So we'd end up preventing to supply both at the same time, and it'd be annoying for host apps to make both props conditional.

I think to scroll to x/y we can just expose a function via refs like `scrollTo(x,y)` which would scroll to `x,y`. 
Sorry but again coming back to the same question why do we need `initialData.scrollX/Y` ?

When `initialData.scrollToCenter` is true we can just retain the scrollX/Y from appState and when `scrollTo` is called host will pass `x,y` explicitly. WDYT ?

**Comment by dwelle** [comment]
We don't want to imperatively call `scrollTo` coz that will almost certainly cause a flicker as it would pretty hard to synchronize the `scrollTo` call to happen immediately after `App.initializeScene` does the initial render.

**Comment by dwelle** [comment]
Btw, if someone wants to scroll the scene imperatively *after* initialization, they can just do `updateScene()` (when we later support supplying `appState` directly). I wouldn't add an API for that as it seems like an edge case rn. But setting scroll positions during init makes sense and should be much more common.

**Comment by ad1992** [comment]
closed via #3070
