### ISSUE TITLE
Export only selected elements

### ISSUE THREAD

**Issue by Fausto95** [excalidraw/excalidraw#308]
While most of the apps allow this to be done, it'd be nice if we supported this feature, right now we're able to accomplish this using the copy to clipboard button but it should be done when we click the export button or we could add it in the context menu

**Comment by dwelle** [comment]
Do you mean supporting to ignore deselected elements during export? Because I'm confused by: 

>  right now we're able to accomplish this using the copy to clipboard button 

Both the "export to image" and "export to clipboard" work the same way, currently.

**Comment by Fausto95** [comment]
The code is exactly the same, but when copying to clipboard, you only get the selected elements!
With the export button, if you select elements and then click the button, all the elements in the canvas will be exported even those that aren't selected

**Comment by dwelle** [comment]
Cannot repro. Are we talking about this button?

![image](https://user-images.githubusercontent.com/5153846/72206026-a7e22100-3489-11ea-88ce-a6a08319f33b.png)

**Comment by Fausto95** [comment]
> (copy to clip, as in copy JSON to clip (for pasting later), indeed copies only selected elems, but I don't think you mean that).

That's what I meant

**Comment by dwelle** [comment]
I see. Well, yea, that's a different thing.

Let's keep this issue open and see what others think. What's your use case for that?

**Comment by vjeux** [comment]
I think that makes sense to export all the elements if none are selected, or export only selected elements if some are selected.

A common use case is that you write multiple diagrams in one scene and want to export different images for each section.
