### ISSUE TITLE
Cmd+Click should toggle a part of the selection

### ISSUE THREAD

**Issue by gaearon** [excalidraw/excalidraw#3095]
1. Select many items
2. Cmd+click one of them

Expected: it deselects _that item alone_ (and next Cmd+click adds it to the selection)
Actual: it deselects everything and selects the clicked item alone

https://user-images.githubusercontent.com/810438/108633816-3dfac000-746e-11eb-85f6-9dc66b99cc39.mov

**Comment by dwelle** [comment]
Excalidraw, same as Figma and many other vector editors, is using `Shift` for adding/removing from selection, whereas Cmd is used for exclusive selection.

**Comment by gaearon** [comment]
Ah, okay. I tried Shift but I guess I missed it, just checked that it works. I'm used to the Cmd+ shortcut from Keynote, which I assumed is the same everywhere.
