### ISSUE TITLE
Keyboard shortcuts for changing stroke and background colors

### ISSUE THREAD

**Issue by aakashns** [excalidraw/excalidraw#3100]
I'm using Excalidraw for live online classes, and it would be amazing if I could do everything in Zen mode using just keyboard shortcuts. While selecting and drawing shapes is possible, selecting the stroke and background color still requires exiting Zen mode, which is a bit distracting for viewers. 

A shortcut like Ctrl+Option+1/2/3... for selecting stroke color would be really helpful.

Another alternative would be to show a color pallete on the left/right/bottom in Zen mode for easily switching stroke color.

P.S.: Excalidraw is a great tool for live online teaching. Almost completely eliminates the need for a graphics tablet. Thanks!

**Comment by frantic** [comment]
Looks like Excalidraw already supports shortcuts for selecting stroke/background values:

![image](https://user-images.githubusercontent.com/192222/110059013-437ec280-7d18-11eb-8756-79bf76757e5b.png)

I think it would be really nice to have a shortcut to open that menu (from Zen mode as well!). It could work like this:

1. User presses "B"
2. Excalidraw opens "Background" menu
3. User presses "F"
4. Excalidraw applies yellow background

**Comment by AMGMNPLK** [comment]
It would be faster to assign one keyboard line for tools and another one or two for colors or better each color with each first letter.

Example:

I want to draw a white arrow: I click 5 (or A) and then W. 
I want to draw a freehand in blue: I click 7 (or F) and then B.

I think tools and colours are the main functions of Excalidraw and deserve this kind of hotkey preference to save time.

**Comment by dwelle** [comment]
fixed in https://github.com/excalidraw/excalidraw/pull/3318.

> I want to draw a white arrow: I click 5 (or A) and then W.
> I want to draw a freehand in blue: I click 7 (or F) and then B.

This would conflict with other shortcuts like the tools themselves as we wouldn't know whether you want to change color or pick a different tool.

If we were to implement something like this, I'd want to investigate using a shortcut context modes similar to Vim or this request: https://github.com/excalidraw/excalidraw/issues/3204
