### ISSUE TITLE
Prevent connection to storage.googleapis.com

### ISSUE THREAD

**Issue by tim-krieger** [excalidraw/excalidraw#3121]
We use Excalidraw at our own server without firebase and exalidraw-json. However, ublock shows me a connection to storage.googleapis.com. Is there a way to prevent this?

![image](https://user-images.githubusercontent.com/64839715/109010616-48a49780-76b0-11eb-9c73-129a85cfe5d3.png)

**Comment by dwelle** [comment]
You're using the npm package?

**Comment by tim-krieger** [comment]
We've installed Excalidraw via Docker. And delete the line with the firebase config in .env.

**Comment by dwelle** [comment]
I see. The Docker basically deploys the whole of excalidraw.com, even if it's not using parts of the app such as communicating with the server etc. But apparently it's still bundling the firebase client (no surprise), which seems to connect to the firebase server even if we're not actively using it.

**Comment by tim-krieger** [comment]
I looked a little bit deeper on it:

![image](https://user-images.githubusercontent.com/64839715/109614887-80d62b00-7b33-11eb-8894-8f28cc8c1bc1.png)

It seems this issue is caused by the following files:

```
./node_modules/workbox-build/build/cdn-details.json:3:  "bucketName": "workbox-cdn",
./node_modules/workbox-build/src/cdn-details.json:3:  "bucketName": "workbox-cdn",
./src/service-worker.js:21:  "https://storage.googleapis.com/workbox-cdn/releases/4.3.1/workbox-sw.js",

```

**Comment by tim-krieger** [comment]
This issue is introduced with #2338. Maybe it could be fixed by using local files #2320 ([here](https://developers.google.com/web/tools/workbox/modules/workbox-sw)).

**Comment by dwelle** [comment]
Oh, so it's unrelated to Firebase (or at least this part isn't)?

**Comment by tim-krieger** [comment]
Yes, I think it has nothing to do with Firebase. That would be really cool because Firebase could be deactivated simply by deleting the appropriate line in .env. It's important for using Excalidraw in german schools (GDPR). Thank you really much!

**Comment by tim-krieger** [comment]
I tested your PR: No more connections to storage.google.apis. Thanks!
