### ISSUE TITLE
Make toast message more informative on copy-PNG-to-clipboard

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#3125]
When I export PNG to clipboard either via a shortcut or contextmenu, it'd be great if the toast contained the following info:

- Was the whole canvas exported, or just the selection?
- What's the exported color scheme?

Both depend on your export-dialog settings and you may not remember what state you left it in (actually, now that I'm checking it, the `only selection` settings seems to reset each time — not sure if bug or not, but all the more reason for an explicit message).

What I'd imagine it would look like:

> Copied canvas to clipboard as PNG (light mode)

> Copied selection to clipboard as PNG (light mode)

**Comment by h7y** [comment]
I would love to take this up :)

**Comment by dwelle** [comment]
Thanks @h7y :)
