### ISSUE TITLE
Hosting in sub-path (not /)

### ISSUE THREAD

**Issue by geraintluff** [excalidraw/excalidraw#3127]
## Background

When you make a production build, you get the following message from React:

```
The project was built assuming it is hosted at ./
You can control this with the homepage field in your package.json.
```

So I tried it!  I changed that field in `package.json` to `"excalidraw"`, expecting to be able to host/use it at `https://example.com/excalidraw/`.

## Problem

It didn't quite work.  Here are some things I ended up changing, which (if we want to support this) we could derive from the `package.json` field:

* `EXCALIDRAW_ASSET_PATH` in `index.html`, set to `/excalidraw/` - without this, a few things were still loaded from `/static/` (instead of `/excalidraw/static`).  The interface appeared and editing worked, but export didn't.

* `start_url` and `file_handlers`/`action` in `manifest.json` - without this, when saved as a Progressive Web App, it pointed to the wrong page.

With these, it [seems to be working](https://signalsmith-audio.co.uk/excalidraw/) (that version has a custom font, which was my actual goal).

**Comment by geraintluff** [comment]
Edited to include the `manifest.json` changes, as I just ran into that issue.

**Comment by dwelle** [comment]
Are you self-building or using the npm package?

**Comment by geraintluff** [comment]
Self-building (to customise the font).

**Comment by dwelle** [comment]
Yes, to my knowledge we're not supporting `homepage` field. The `EXCALIDRAW_ASSET_PATH` is the [correct way](https://github.com/excalidraw/excalidraw/tree/master/src/packages/excalidraw#installation), indeed.

> `start_url` and `file_handlers`/`action` in `manifest.json` - without this, when saved as a Progressive Web App, it pointed to the wrong page.

No idea about this one. /cc @ad1992

**Comment by ad1992** [comment]
yep, we don't rely on the `homepage` field as we want to have `__webpack_public_path__` scoped to excalidraw package only and `homepage` is only useful when using CRA. So if you are building the package yourself, you could either update `window.EXCALIDRAW_ASSET_PATH` in host (recommended) or update the `publicPath` in [webpack config](https://github.com/excalidraw/excalidraw/blob/master/src/packages/excalidraw/webpack.prod.config.js#L17)

However, the best fix would be to allow customized fonts in Excalidraw package so the host can customize it.

**Comment by geraintluff** [comment]
Ah, thanks!  But uh, when you say "in the host", what do you mean?  You mean editing `index.html` before the CRA build, or something else?

> However, the best fix would be to allow customized fonts in Excalidraw package so the host can customize it.

I support this because I think fonts are quite a personal thing, as the recent discussions have shown.

For my personal case, I made several tweaks (from a personal palette to getting [really nitpicky about arrow sizes](https://github.com/excalidraw/excalidraw/commit/35273e9c2441ef9547f12f67adb7233fa74e15a0)), and some of that might be beyond what a config-file should attempt.

**Comment by dwelle** [comment]
`window.EXCALIDRAW_ASSET_PATH` is a runtime thing, since it will affect dynamically imported modules. You can put it anywhere that's executed before you start lazy-loading any modules. `index.html` in a `<script>` tag is the most ideal.

**Comment by geraintluff** [comment]
Ah, I think you're referring to embedding Excalidraw in another page, as a React component?

I just wanted a customised version of excalidraw.com served as static files using Nginx, and that seems to be working now, complete with the ability to install it as an offline app on my phone/Mac.  (Aside from the fact I just realised it's probably re-using your Google Analytics key, which I'll remove now, for GDPR reasons if nothing else.)

I think looking directly at React is just going to give me a headache, but I appreciate you patiently attempting to answer my queries. 😛
