### ISSUE TITLE
Can't delete a shape when iframe loses focus

### ISSUE THREAD

**Issue by gaearon** [excalidraw/excalidraw#3151]
It's gonna take me some time to make a reproducing example. But maybe you have a quick guess about where the bug is.

The repro is roughly as follows:

1. Embed `<iframe>` on the page. The iframe content page renders `<Excalidraw />`.
2. Draw a shape
3. **Click outside the iframe.**
    - Note the shape still appears selected — Excalidraw doesn't know you clicked outside the iframe. Not ideal but seems okay — I don't know if that's even fixable.
4. Click on the shape and press Backspace.

Expected: the shape gets deleted.
Actual: **the shape is undelete-able** — it ignores the key bindings.

The only way to fix it from that point is to draw another shape. Somehow after that, selecting the first shape attaches the key bindings again, and I can Backspace the first shape.

**Comment by dwelle** [comment]
I can reproduce it in https://www.notion.so/ (was lazy).

I have no mental models around iframes, the closest I was to working with them is integrating payments and testing them in Cypress :smile:.

From what I can see: clicking outside the iframe steals focus from it, and clicking back inside on the `<canvas>` doesn't give it back. But clicking on inputs within the iframe does regain focus, which explains why drawing new elements fixes it: the tool buttons are radio inputs. Thus, it's fixable by any other such operation, e.g. clicking inside color picker inputs.

As far as whether it's fixable, that's anyone's guess. Mine would be that no, as you suggest. You're venturing into a territory that we haven't really intended to support (though at one point we were thinking about making the npm package focused around iframes, until we decided to go with React compo).

Using both an `iframe` and the npm compo at the same time, that's cool though :).

**Comment by gaearon** [comment]
Yeah I'd rather not use iframes myself, but it's a crude (but effective) workaround for all the other issues related to containment (#2991, #3043).

**Comment by craigkovatch** [comment]
#3 should be easily fixable by checking `document.hasFocus` perhaps in a blur handler

**Comment by ccrystle** [comment]
I'm an amateur, but a brute force way might be to force the focus on re-entering the iframe. on iframe mouseout, capture and store the id of the last target element with focus, force a deselect, on iframe mouseover restore it.

**Comment by dwelle** [comment]
From quick tests I don't actually see any blockers.

I'm fairly certain it's caused by preventing default on `pointerdown` (though there may be other code paths, too):

https://github.com/excalidraw/excalidraw/blob/785a944ac2c325c213c4bb3b378f60b254ba8790/src/components/App.tsx#L2097-L2098

It was introduced very early in the project to prevent UI text selecting on drag.

**Comment by craigkovatch** [comment]
> It was introduced very early in the project to prevent UI text selecting on drag.

If that's the case, you should be able to just use `-webkit-user-select: none; user-select: none;` and be done! :)

**Comment by gaearon** [comment]
Thanks!
