### ISSUE TITLE
Drawing an arrow results in "Invalid array length"

### ISSUE THREAD

**Issue by christianalfoni** [excalidraw/excalidraw#3153]
On the Codesandbox example: https://codesandbox.io/s/excalidraw-ehlz3?fontsize=14&hidenavigation=1&theme=dark&file=/src/App.js, when I draw an arrow it results in "Invalid array length". Just wanted to report it in case it is "oh... of course", but will try to find time to dive deeper into it 😄

**Comment by christianalfoni** [comment]
I noticed you have to draw the arrow from an object (like attached to it) and into a blank space

**Comment by dwelle** [comment]
Hard to say what's going on without source maps. Also, why it manifest only in that codesandbox.

**Comment by christianalfoni** [comment]
Yeah, it happens when I use the project in my local app as well. This is where the error occurs:

![Screenshot 2021-03-02 at 11 35 19](https://user-images.githubusercontent.com/3956929/109636044-61e39300-7b4b-11eb-82d4-e5fc781fd08b.png)

**Comment by christianalfoni** [comment]
But hard to understand what goes wrong there. Funny thing is that that the arrow is drawn and it all seems good 🤔 

I can try running this with unminified code, but yeah... so weird that it does not happen on main site, cause I guess it is the exact same code running?

**Comment by dwelle** [comment]
> Yeah, it happens when I use the project in my local app as well. This is where the error occurs:

I've downloaded that CSB locally and it doesn't reproduce there.

> I can try running this with unminified code, but yeah... so weird that it does not happen on main site, cause I guess it is the exact same code running?

Almost. The npm package is using its own build.

**Comment by christianalfoni** [comment]
Interesting, I thought maybe it was `iframe` related... but my local project is not using an iframe and it happens there, hm hm

**Comment by christianalfoni** [comment]
I am getting it on exported Sandbox as well. Did you draw the line from the "attached indication" of a rectangle? It only happens then :)

**Comment by dwelle** [comment]
Actually, I can reproduce it even locally. The error must have gotten lost in all the console logs previously.

/cc @ad1992 should we start publishing source maps alongside the package so that we can debug these things?

**Comment by ad1992** [comment]
oops, I missed there was already an issue created for this bug :/. I had tried adding [sourcemaps](https://github.com/excalidraw/excalidraw/pull/2825) but it wasn't working with import syntax. For some reason, webpack wasn't able to identify that source maps in umd build. Will have to check if there is any way to communicate to webpack to load source maps for umd build, but if source maps doesn't work out well we can start exposing dev build in dev environment which will help to debug in host as well.
