### ISSUE TITLE
Can't import scene on Firefox 86.0 while I can on Chrome

### ISSUE THREAD

**Issue by JeffSkyrunner** [excalidraw/excalidraw#3155]
I have exported a scene using Firefox 86.0, in all the available formats (json, svg and png).

If I try to import it it doesn't do anything, it simply stays as a blank page.
If I try to import the same files using Chrome, everything works as expected.

**Comment by dwelle** [comment]
If the scene isn't private, can you upload it somewhere (or if small, copy the file contents and paste it here)?

If it is private, see if you can reproduce on another one, or anonymize it in some way. Other than that, you can check the console (`Cmd + Option + K` on Mac or `Ctrl + Shift K` on Win) if there isn't any error when you import.

**Comment by JeffSkyrunner** [comment]
Unfortunately, the scene is private, but I will try soon with a generic one.
In the meantime, here is what the console says me:

The following are as soon as I load excalidraw.com

```
Cookie “_ga” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite analytics.js:30:486

Cookie “_gid” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite analytics.js:30:486

Cookie “_gat_gtag_UA_387204_13” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite analytics.js:30:486
```

The following are after I tried to import the scene:

```
The resource at “https://excalidraw.com/Virgil.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. excalidraw.com

The resource at “https://excalidraw.com/Cascadia.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. excalidraw.com

```

**Comment by BartSymbaloo** [comment]
Same issue here.
I created a excalidraw (json) document last week with Firefox (maybe previous version) but when I try to open it again today (with version 86.0) nothing happens.
No problems (yet) with Chrome, Opera.


The console in Firefox shows this:

Some cookies are misusing the recommended “SameSite“ attribute 3
Cookie “_ga” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite analytics.js:30:486
Cookie “_gid” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite analytics.js:30:486
Cookie “_gat_gtag_UA_387204_13” will be soon rejected because it has the “SameSite” attribute set to “None” or an invalid value, without the “secure” attribute. To know more about the “SameSite“ attribute, read https://developer.mozilla.org/docs/Web/HTTP/Headers/Set-Cookie/SameSite analytics.js:30:486

The resource at “https://excalidraw.com/Virgil.woff2” preloaded with link preload was not used within a few seconds. Make sure all attributes of the preload tag are set correctly. excalidraw.com

**Comment by dwelle** [comment]
The only thing I can reproduce is that Firefox (86) doesn't seem to respect extension anymore and saves without one. But importing such a file gives you an error message:

![image](https://user-images.githubusercontent.com/5153846/109684417-87d75a80-7b80-11eb-8ed4-b4be208427a5.png)

So I suppose this is not the problem you're having?

**Comment by JeffSkyrunner** [comment]
I can confirm it is not saving with the extension.
I have added the json extension manually, but in both cases (loading a json file or a "no extension" one) I receive no error; it simply does nothing.

**Comment by dwelle** [comment]
> I have added the json extension manually, but in both cases (loading a json file or a "no extension" one) I receive no error; it simply does nothing.

In that case, I'd suggest opening it in chrome and mangle the contents to anonymize the file and try to repro on that. Without an access to a file on which we can repro, it'd be hard to diagnose :).

**Comment by dwelle** [comment]
The console error messages don't explain much. The first ones are analytics issues, and the latter ones are font preloading issues that shouldn't even affect the rendering of the text as a whole — but even if so, it would fall back to some system font (and I also don't assume your scene is composed entirely of text).

**Comment by BartSymbaloo** [comment]
clicking on the link opens the debugger on line 129 where I read

127        // this fails for some browsers. :(
128        if (originalConsoleLevel) {
129          Function.prototype.apply.call(originalConsoleLevel, global.console, args);
130        }

**Comment by BartSymbaloo** [comment]
I can confirm that the same issue appears also in Firefox 85.0.

**Comment by JeffSkyrunner** [comment]
This is a file I just made for testing that has the same problem.

I think you might want trying following these steps:

1. create a scene
2. save it with a random name
3. delete it (<- I feel this might be the key, but I am just guessing)
4. load your previously saved scene (or the following)

[Untitled-2021-03-02-1532.zip](https://github.com/excalidraw/excalidraw/files/6070443/Untitled-2021-03-02-1532.zip)

**Comment by dwelle** [comment]
I can't repro on the scene you supplied. Without the extension it shows the error message modal, and if I add the extension manually, it imports fine.

I've also tried repeating the steps (if by deleting you mean clearing the canvas via the trash button).

The only explanation that comes to mind you're on some very old Excalidraw version where the error modal wasn't implemented yet? Could you pop into console and type in `__EXCALIDRAW_SHA__`, and past the version back here?

**Comment by JeffSkyrunner** [comment]
There you are: "91eb8834e85caebeb795a20ae86d11ea091a753d"

**Comment by dwelle** [comment]
> 91eb8834e85caebeb795a20ae86d11ea091a753d

That's the latest :thinking:

**Comment by JeffSkyrunner** [comment]
I don't know what to say, I am sorry... 😄

**Comment by dwelle** [comment]
How are you importing the files btw? If via Drag&Drop, does it work here? https://excalidraw-egl927g8g-excalidraw.vercel.app/

**Comment by dwelle** [comment]
Ooh.. I can repro now in FF, using these steps:

1. try to import by using `open file` button
2. in the picker, choose "any file types" (Windows) 
3. does nothing!

**Comment by dwelle** [comment]
It looks like it'll require an upstream fix in `browser-fs-access`.

**Comment by BartSymbaloo** [comment]
The files that I couldn't open before in FireFox are now imported without any problem
Thank you!

**Comment by JeffSkyrunner** [comment]
Confirmed, it works for me too 😄 

Thanks, guys!
