### ISSUE TITLE
Legacy FS saves without file extension

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#3157]
In FF 86, it saves a file without any extension, which then can't be imported.

The filename looks like:

```
Untitled-2021-02-09-1354
```

**Comment by copernico** [comment]
Same in chromium.

**Comment by dwelle** [comment]
I suppose you mean _the_ chromium, not all chromium-based browsers. But even there I'm surprised it doesn't include the new FS API, unless you're running an old version.

**Comment by copernico** [comment]
Hi,

By chromium I mean chromium :-)

```
Chromium
Version 87.0.4280.66 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)
```

**Comment by dwelle** [comment]
I've checked Chromium `87.0.4280.0` for windows and it works. Maybe Native FS doesn't work on Linux :thinking: — one other possibility is you're on some very old Excalidraw version — can you paste `__EXCALIDRAW_SHA__` into the console?

**Comment by copernico** [comment]
Sorry for the dumb question, but.... how do I find the value of `__EXCALIDRAW_SHA__`?

**Comment by dwelle** [comment]
Sorry, what I meant, just paste `__EXCALIDRAW_SHA__` (it's `window.__EXCALIDRAW_SHA__` really) into the console and it'll print the value.

**Comment by copernico** [comment]
0d2f72f87e0b0e3cdd4550207b45c95d59af75fd

**Comment by dwelle** [comment]
Ok, that's really recent, I'm being too paranoid about this lately. So other than it being caused by Linux, I have no answers :). But we should hopefully fix it anyway.

**Comment by arnas** [comment]
I encountered this issue too. (windows 86.0, chrome works alright), Is there any reason why we not always append correct file extension?
![image](https://user-images.githubusercontent.com/13507001/110211334-cf225b80-7e9e-11eb-965f-8ed0780bb4b2.png)
It seems that this way both firefox and chrome works correctly.

**Comment by dwelle** [comment]
That works in chrome (Native FS) only because it incorrectly doesn't populate the input with suggested name. As such, we should make this only for legacy FS cases. It's best if the fix is made in https://github.com/GoogleChromeLabs/browser-fs-access — can you open a PR there, linking to this issue?

**Comment by dwelle** [comment]
There's a problem though: Safari saves it as `.json` (not sure where it's coming from — probably inferred). So better check what it does when you manually append `.excalidraw` to the filename.
