### ISSUE TITLE
Allow to update whole `appState` from `updateScene()`

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#3176]
#### The argument for this:

- Host apps should have control over everything if they want to. Let's say they need to hack a case we didn't account for yet (or don't want to account for).

#### The argument against this:

- Will expose internals which unless you know what you're doing could break the editor.

---

IMO, we should simply document only the recommended use cases, and leave the rest undocumented with a caveat that if the host apps touch the rest of the props and it breaks something, it's on them.

/cc @ad1992

**Comment by ad1992** [comment]
> Host apps should have control over everything if they want to. Let's say they need to hack a case we didn't account for yet (or don't want to account for).

The reason I am not in favor of this is when you say host apps should have control over it but that not true when using `updateScene`. For example, if you are updating zen mode via updateScene, then it should not get updated by Excalidraw (via context menu/shortcut keys) then only we can say that it is fully controlled by the host. To prevent this the host will have to hide the context menu options via CSS and also prevent the shortcut keys which is not ideal. The same applies for other modes and theme as well.

What I mean is if the host is controlling then it should fully control it and there shouldn't be any ambiguity in the flow.

**Comment by dwelle** [comment]
Yes, but that's the problem of the host app. We'd not document that you can use `updateScene` for changing `appState.zenMode` etc. If they do, that's on them. And there's also no reason why the should do that. It would be for cases we *don't* handle.

**Comment by ad1992** [comment]
Hmm so basically a hidden API with which you can update any state of Excalidraw which is not supported directly.
But I would suggest let's not support it right away unless there is a requirement and wait for some time till we figure out what are those cases and do we really need it.

**Comment by ad1992** [comment]
Now that we have a real use case https://github.com/excalidraw/excalidraw/issues/3485, let's allow the host to support updating the app state via the `updateScene` API.
