### ISSUE TITLE
Export the utilities from utils package in excalidraw package as well

### ISSUE THREAD

**Issue by ad1992** [excalidraw/excalidraw#3181]
We can start exporting the methods in [src/package/utils](https://github.com/excalidraw/excalidraw/blob/master/src/packages/utils.ts). 
This will allow the host to use these functionalities out of the box.
cc @dwelle

**Comment by dwelle** [comment]
I think we wanted to export the ones in `src/packages/utils.ts`, but otherwise yes.

**Comment by ad1992** [comment]
That would be better, so all utilities from utils are always available for excalidraw package
