### ISSUE TITLE
Add user-select property

### ISSUE THREAD

**Issue by imbsky** [excalidraw/excalidraw#32]
All the options are selected by just double-clicking somewhere, so I think we need to disable it with `user-select`. I'm already ready to open PR for this.

**Comment by vjeux** [comment]
I was hoping we could avoid doing that. Maybe adding event.preventDefault() to canvas mouse handlers would work?

**Comment by dwelle** [comment]
> I was hoping we could avoid doing that. Maybe adding event.preventDefault() to canvas mouse handlers would work?

That'd work, but clicks/drags on the labels would still select them. Is there any accessibility downside to disabling `user-select` on the labels?

**Comment by vjeux** [comment]
That’s why I asked in the other PR if there were best practices dealing with keyboard / mouse inputs.

I’m happy adding hacks if there’s no good way :)

Feel free to send a PR and we’ll merge it
