### ISSUE TITLE
feat: Implement the Web Share API for the collaboration dialog

### ISSUE THREAD

**Issue by tomayac** [excalidraw/excalidraw#3213]
This API supports sharing text-only and also files (image) on top (see [background article](https://web.dev/web-share/) for details). It is supported on Chrome and Safari. 

- It would be awesome to have this in the **collaboration dialog** so you can share the **room URL** (text-only):
  <img width="579" alt="Screen Shot 2021-03-09 at 16 20 49" src="https://user-images.githubusercontent.com/145676/110494138-94fdc780-80f3-11eb-92ac-c166bb1d26b4.png">

**Comment by h7y** [comment]
This is really cool! I would love to take it up :)

**Comment by tomayac** [comment]
@h7y Ideally you start with the **collaboration dialog** since it's the easiest. On supporting devices (see feature detection in the article), you can replace the existing copy button with the new share feature. 

We're aiming for this to land by Friday, March 12, because we would like to demonstrate this feature at an event. Do you think this would work for you time-wise?

**Comment by dwelle** [comment]
To elaborate on the previous comment. Let's split this task into two. For the export dialog we'll want to first hash out the design and UX considerations.

So what needs to be done by Friday is just the collaboration dialog part. And we'll discuss the export dialog in a separate issue.

**Comment by tomayac** [comment]
I'll open a new issue.

**Comment by h7y** [comment]
Yeah that would work. I can finish this up before Wednesday or Thursday max.

**Comment by tomayac** [comment]
The export dialog part has been split out into #3217.

**Comment by tomayac** [comment]
> May I know where I should get the share icon?

You can use “ios_share” and “share” from https://material.io/resources/icons/?style=baseline.

**Comment by tomayac** [comment]
Ideally the icon adapts based on the platform: Apple get “ios_share”, everyone else gets “share”. See this [snippet](https://github.com/tomayac/blogccasion/blob/522e416fa2b4a25ecbabbca2189f739b3db39b5d/js/share.mjs#L18-L19) for inspiration.

**Comment by h7y** [comment]
I think this can be closed now :)
