### ISSUE TITLE
Text editor shifts when zoom level is not 100%

### ISSUE THREAD

**Issue by ad1992** [excalidraw/excalidraw#3220]
The text editor shifts when when zoom is not 100%. 
This is due to https://github.com/excalidraw/excalidraw/blob/master/src/element/textWysiwyg.tsx#L73. We cannot remove this but need to find a better fix since removing this will break the cursor offsets in host and also possibly more things in Excalidraw App as well.
![Excalidraw](https://user-images.githubusercontent.com/11256141/110659059-3ebe8080-81e8-11eb-8c6f-6c0ce9d7893c.gif)

**Comment by dwelle** [comment]
techncially, this should fix it (but it doesn't):

```js
(
  appState.offsetLeft +
  appState.width -
  viewportX -
  Number(
    getComputedStyle(
      document.querySelector(".excalidraw")!.parentNode as Element,
    ).marginRight.slice(0, -2),
  )
) / appState.zoom.value - 8;
```

The more you type, the more it accumulates some tiny offset that ultimately pushes it over the border. Not sure what's going on there.
