### ISSUE TITLE
Fonts are not consistent after reload (Safari mobile, Chrome mobile iOS)

### ISSUE THREAD

**Issue by tim-krieger** [excalidraw/excalidraw#3229]
Steps to reproduce:

1. Delete browser cache (Safari mobile, Chrome mobile iOS)
2. Open excalidraw.com
3. Type something
4. Reload Excalidraw
5. The fonts seems not to be consistent (screenshot)

Workaround (after the following the previous steps)

1. Close the browser completly
2. Open excalidraw.com

You can reload the page as much as you want: the fonts looks well!

![excalidraw](https://user-images.githubusercontent.com/64839715/110911763-62321a00-8313-11eb-9472-6dee42dd02dd.png)

**Comment by renchap** [comment]
I am experiencing the same issue with Safari on macOS.
It is a bit hard to reproduce, but sometimes when opening Excalidraw the fonts are not loaded at all.

The console shows a warning that some .woff2 files have been preloaded but not used. I will try to investigate a bit more the next time it happens.
