### ISSUE TITLE
Feature: Transparent background to portray/vectorize some image

### ISSUE THREAD

**Issue by lein1013** [excalidraw/excalidraw#3233]
Often if i need a new symbol I just google for some inspiration. When I found an suitable drawing I need to redraw it for excalidraw.
The idea is to switch excalidraws background to transparent - capture the image manually and put it into the own library...

**Comment by dwelle** [comment]
Are you suggesting the canvas/web page's background be transparent so that you can see what's behind the browser window (if your OSS allows it)?

**Comment by lein1013** [comment]
If that would be possible, I think that could be a cool feature. I just did a quick search and found 
`shimmer.style.backgroundColor = 'transparent'; 
`
but I have too less js experience to know if this is technical feasible.
An alternative approach to portay an image would be, if we were able to paste the full image into excalidraw, put it into the background and draw on top of it.

**Comment by dwelle** [comment]
We've had a similar request once (can't find it now). I don't recall how it was accomplished that the browser window was made transparent and you could see what's beneath it. What's your workflow?

**Comment by lein1013** [comment]
I've found now by accident a tool which fits perfectly 
So, please check out  https://github.com/LorenzCK/OnTopReplica

![grafik](https://user-images.githubusercontent.com/72338417/112370912-44cf5980-8cde-11eb-91c3-86288c722432.png)

### Workflow:
1. find an image you want to redraw in excalidraw
2. view this image in awindow
3. start  OnTopReplica and select the Window with the image
4. set position the opacity to 50% and position the window in the middle of the screen
5. open excalidraw in the background
6. in OnTopReplica enable click through mode
7. draw the image

The original idea was to have the excalidraw window transparent, but it works also when it is reverse with the click through mode.

Although the original idea did not need an extra tool and would therefore be more convenient, I would say that this issue can be closed. (but maybe keep it in mind)

**Comment by dwelle** [comment]
Yes, I was gonna suggest a comparable tool that I've been using: [PureRef](https://www.pureref.com/).

Benefit of using these tools is you're not dependent on the whims and changes of the web apps. It also feels like a niche use case (I mean the transparent background, not the outlining). And lastly, we should add image support at some point anyway.

I'll close as you suggested.

**Comment by Cal369** [comment]
Anyone looking at this today, there is a switch within the Excalidraw plugin that sets all imports to include background or make transparent. So cancel whatever extra plugins or workarounds you're currently doing.

This is amazing for designing SVG's on the fly!!
