### ISSUE TITLE
Feature: support custom fonts

### ISSUE THREAD

**Issue by lein1013** [excalidraw/excalidraw#3240]
As there are several open issues regarding the readability of various letters (e.g. 2 (https://github.com/excalidraw/virgil/issues/21), or 4 (https://github.com/excalidraw/virgil/issues/41) , (https://github.com/excalidraw/virgil/issues/45))

It would be a great feature to change a custom font 

Maybe the library concept could be used to embedd custom fonts into the excalidraw file
e.g. some could add the own handwriting (http://www.yourfonts.com/)

**Comment by ad1992** [comment]
We are actively working on fixing the issues and improving the Virgil font. However the support for adding custom fonts to the app seems to be out of scope.

**Comment by haywirez** [comment]
I would be interested in this feature as well. Would be extremely handy when embedding images in Google docs etc. that use a custom (let's say serif) font.

**Comment by borekb** [comment]
@ad1992 is it still something that the team is against? For some of my diagrams, the hand-written font is too fancy while the normal style is too boring (I hate "Arial" even if it's probably something slightly better like Helvetica).

The ability to use Google Fonts, for example, would be great.

**Comment by ad1992** [comment]
@borekb we might support this in npm package so host apps could user their custom fonts but I am not sure if we would want to introduce in Excalidraw App, but this could a good use case for the plugins https://github.com/excalidraw/excalidraw/issues/5424, which would allow users to use addon functionalities (still in discussion!).

**Comment by DanielJGeiger** [comment]
@borekb The `ExcalidrawElement` subtypes system I've created (see #3915) could potentially enable a plugin to do this easily.  Currently the subtypes system allows adding custom properties to `ExcalidrawElement` and enforcing particular "standard" values for non-custom properties.  (My MathJax plugin does both of these things.)  But I imagine subtypes could also permit extended values for non-custom properties (like `element.fontFamily = 4`).

**Comment by JainamJhaveri** [comment]
Hi @DanielJGeiger, @ad1992 - Kindly advise if there's an update on this ticket - is there any plan soon to support custom fonts that we can add for text elements?

**Comment by Shobhit-Nagpal** [comment]
Hey, was curious to see if there's any updates on this :))

**Comment by JainamJhaveri** [comment]
Hi @Shobhit-Nagpal,

Pls check the below fork - we have added some custom fonts as per our requirement here: https://github.com/jainamjhaveri/excalidraw
Here's associated published package: https://www.npmjs.com/package/excalidraw-customization

Find the attached doc here for adding your own fonts after creating a custom package - [Steps to add custom fonts in excalidraw-customization.docx](https://github.com/user-attachments/files/15967345/Steps.to.add.custom.fonts.in.excalidraw-customization.docx)
-

Maybe this can help someone down the road to add their own custom fonts, thanks again @dwelle and excalidraw team for the package!
