### ISSUE TITLE
Add support for Windows share experience

### ISSUE THREAD

**Issue by h7y** [excalidraw/excalidraw#3259]
More details on this https://blogs.windows.com/windowsdeveloper/2017/04/06/new-share-experience-windows-10-creators-update/

**Comment by h7y** [comment]
I'll take this up :)

**Comment by tomayac** [comment]
Here's the official image from the Segoe font:

![e72d](https://user-images.githubusercontent.com/145676/111622657-bd6b7d00-87e9-11eb-83f5-cf839b950aba.png)

([Source](https://docs.microsoft.com/en-us/windows/uwp/design/style/images/segoe-mdl/e72d.png))

**Comment by h7y** [comment]
Closed by #3306
