### ISSUE TITLE
Ctrl+C stops working after editing any text object

### ISSUE THREAD

**Issue by bduffany** [excalidraw/excalidraw#3267]
In the latest version of Excalidraw (latest Chrome on Ubuntu 20.04) I'm seeing that copying / pasting shapes using Ctrl+C / Ctrl+V is sometimes not working. Haven't pinned down a pattern yet, but will update here if I have any more details.

**Comment by bduffany** [comment]
What seems to be happening is that it will work for the first few moments of a drawing session, then it will start getting "stale" (Ctrl+V will paste an old shape on the clipboard, no matter what I try adding to the clipboard via Ctrl+C).

If I refresh the page then it starts working again.

**Comment by dwelle** [comment]
I've recently made a fix that was actually supposed to prevent stale pasting (but even that was only happening in special cases where you copy/pasted stuff across apps/files — not within the single app), and generally simplified the code.

If could could come up with a concrete steps to reproduce, that would be great.

In the mean time, can you post what's your excalidraw version? Toggle the "stats for nerds" (via contextmenu) & click on the version (it'll copy the version to your clipboard).

**Comment by dwelle** [comment]
Correction: that fix was still not merged :smile: https://github.com/excalidraw/excalidraw/pull/3257

So in theory if you're pasting across browser windows/tabs, or are caching the clipboard to a file or something, then the stale pasting can happen.

**Comment by dwelle** [comment]
You can check the preview whether you can still reproduce the issue: https://excalidraw-git-improveclipboard-excalidraw.vercel.app/

**Comment by bduffany** [comment]
Nope! I was not able to reproduce in your preview deployment there.

In case you're still interested in concrete steps, I was able to reproduce by making any edit to any text object. After editing any piece of text, it appears that Ctrl+C no longer works. A page refresh fixes the issue.


https://user-images.githubusercontent.com/2414826/111395764-fc87ba00-8693-11eb-8e00-6848a68b1ddb.mp4

**Comment by dwelle** [comment]
Woah, that's interesting. Will investigate lest it pops up again in some edge case (even though the PR will probably fix it for good). Thanks!

**Comment by dwelle** [comment]
Turns out it's a recent regression unrelated to our clipboard handling (in a way).
