### ISSUE TITLE
library: hide export/clear if empty

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#3280]
I was told that those buttons are confusing when the library is empty, and I agree.

![image](https://user-images.githubusercontent.com/5153846/111868355-cdb26200-8979-11eb-9268-3922fa8ec75b.png)

**Comment by h7y** [comment]
Yeah! Makes sense. Why show it when it has no utility? +1

**Comment by ad1992** [comment]
Yep agreed 👍
