### ISSUE TITLE
Pasting rich text in name input doesn't change to plain text on Firefox

### ISSUE THREAD

**Issue by h7y** [excalidraw/excalidraw#3285]
## Demo
![Demo](https://media.giphy.com/media/uVJO5Rmn177enfhMmR/giphy.gif)

This only seems to happen on Firefox. Not happening on Safari  & Chrome.

**Comment by dwelle** [comment]
@ad1992 is working on migrating to an `input` which should fix this

**Comment by h7y** [comment]
Got it! I'll close this?

**Comment by dwelle** [comment]
fixed via https://github.com/excalidraw/excalidraw/pull/3286
