### ISSUE TITLE
Help toggle is not tabbable

### ISSUE THREAD

**Issue by h7y** [excalidraw/excalidraw#3287]
<img width="1257" alt="Screenshot 2021-03-20 at 8 28 08 PM" src="https://user-images.githubusercontent.com/22396000/111874402-1e967a80-89bb-11eb-8a32-1565b470b2ac.png">

I was thinking about changing it into a button. Is there any reason for it to be a `div`?

**Comment by dwelle** [comment]
Go for it!

**Comment by h7y** [comment]
Closed by #3310
