### ISSUE TITLE
Embeddable excalidraw doesn't ship with types

### ISSUE THREAD

**Issue by bduffany** [excalidraw/excalidraw#3301]
The embeddable version of excalidraw doesn't include a `.d.ts` file in the distribution folder, so when using typescript all the type info is lost.

**Comment by ad1992** [comment]
@bduffany we will be adding it soon. Its already tracked in https://github.com/excalidraw/excalidraw/issues/2514.
closing this as its duplicate of https://github.com/excalidraw/excalidraw/issues/2514
