### ISSUE TITLE
Unable to load from file in Brave browser

### ISSUE THREAD

**Issue by mhoyer** [excalidraw/excalidraw#3302]
I switched to Brave browser some weeks ago (coming from Edge Chrome) and now I face the issue that loading `.excalidraw` JSON files is not working anymore. Simply nothing happens after I  selected the file to be loaded and click the "Open" button. No errors in the Console nor any message.

I guess it's related to Brave browser itself, but I don't know where to look further. I also tried in a private window and with a brand new profile (w/o any extensions installed).

Any clue what's going on here?

I am working under Windows 10 (1909) with Brave Browser 1.21.77 (which uses Chromium 89.0.4389.90).

**Comment by h7y** [comment]
I just tested with the same Brave version on mac and can confirm that it's happening.

![Demo](https://media.giphy.com/media/EbZKrvQfxohLCS4lQu/giphy.gif)

**Comment by dwelle** [comment]
@tomayac it seems the fix in `browser-fs-access` for the AbortError I made isn't working on Brave. Can we get rid of the AbortError hack altogether rather than try to pile more hacks on top?

(Also, I thought Brave is already using the new FS API, but apparently not.)

**Comment by tomayac** [comment]
In my isolated [demo](https://browser-fs-access.glitch.me/) that uses v0.15.2 of browser-fs-access, I can open files just fine. Brave supports the File System Access API. I just tested on `Version 1.19.86 Chromium: 88.0.4324.96 (Official Build) (x86_64)`.

<img width="1312" alt="Screen Shot 2021-03-22 at 13 21 10" src="https://user-images.githubusercontent.com/145676/111988968-79da8100-8b11-11eb-92d2-75893fbe14a5.png">

They seem to have removed support for the API in `Version 1.21.77 Chromium: 89.0.4389.90 (Official Build) (x86_64)`, though, and I can reproduce the "nothing happens" behavior. Investigating further now.

**Comment by dwelle** [comment]
> They seem to have removed support for the API in `Version 1.21.77 Chromium: 89.0.4389.90 (Official Build) (x86_64)`, though, and I can reproduce the "nothing happens" behavior. Investigating further now.

Yeah, I'm on 89. Not very nice that they removed the API :(.

**Comment by tomayac** [comment]
Fixed in https://github.com/excalidraw/excalidraw/pull/3303 via https://github.com/GoogleChromeLabs/browser-fs-access/commit/9340b5810e4a311e3715a63121f765eecf6f829b
