### ISSUE TITLE
Add unit tests for `restore.ts` file

### ISSUE THREAD

**Issue by ad1992** [excalidraw/excalidraw#3307]
Since we are also exporting the functions  from https://github.com/excalidraw/excalidraw/blob/master/src/data/restore.ts in npm package as well it would be better to have unit tests for these functions.

**Comment by Dhairya3124** [comment]
Hey @ad1992 I would like to work on this issue. Can you please assign it to me?

**Comment by ad1992** [comment]
Here you go 👍

**Comment by Dhairya3124** [comment]
Hey @ad1992 I'm trying to make unit tests can you give any resource that how should I write them?It's a little difficult for me.

**Comment by ad1992** [comment]
We need to cover each function in `restore.ts` since these are utilities so for each scenario, you will have to call the function and assert on the result, you can check https://github.com/excalidraw/excalidraw/blob/master/src/tests/packages/utils.test.ts, https://github.com/excalidraw/excalidraw/blob/master/src/tests/utils.test.ts

**Comment by Dhairya3124** [comment]
Thank you @ad1992 :+1:

**Comment by rafaquelhodev** [comment]
I noticed that this issue has been idle for a little while, is it ok if I submit a PR for this one? @ad1992

**Comment by ad1992** [comment]
Sure go for it @rafaquelhodev 👍🏻

**Comment by rafaquelhodev** [comment]
Hi @ad1992! I've just raised a PR for this issue. I'm new to open source, so feel free to review and correct my code =)
