### ISSUE TITLE
Add unit tests for package/utils

### ISSUE THREAD

**Issue by ad1992** [excalidraw/excalidraw#3308]
Since we are exporting it in our npm package as well lets have unit tests for https://github.com/excalidraw/excalidraw/blob/master/src/packages/utils.ts

**Comment by hampuslavin** [comment]
Hi! 👋 
I haven't contributed here before, but I'd be happy to give this a go 🙂 Where would you like the tests to be located - in `src/tests/utils.test.ts`?

**Comment by ad1992** [comment]
@hampuslavin sure go for it 👍 
lets keep the tests inside `src/tests/packages/utils.test.ts` so that its clear that the tests are of the `utils` folder inside `packages` and not `src/utils.ts`.

**Comment by ad1992** [comment]
closed via https://github.com/excalidraw/excalidraw/pull/3357
