### ISSUE TITLE
Alt+Z does not trigger zen-mode

### ISSUE THREAD

**Issue by zsviczian** [excalidraw/excalidraw#3309]
Using Logitech MX Keys with ISO layout. Left Alt+Z shortcut for Zen-mode does not work.

Would be nice if the user could customize native Excalidraw shortcuts - maybe through the help "?" screen. Would provide a generic solution to solving problematic keyboard shortcuts.

**Comment by arphox** [comment]
Same for me, but for me, `Alt+Y` works instead (QWERTZ keyboard).
Seems like a physical vs logical key problem.

**Comment by dwelle** [comment]
Hey. This is a problem that we will improve (if not solve) later, but it will require a bit of work (basically rewrite the keyboard handling). I don't recall what all heuristics we can do, but it will be possible at least in Chrome and Edge browsers. At least until we support customizable keybindings (https://github.com/excalidraw/excalidraw/issues/3852).

Closing in favor of https://github.com/excalidraw/excalidraw/issues/3059
