### ISSUE TITLE
Tooltip Save / Save As.. / Open File etc.

### ISSUE THREAD

**Issue by pwtn** [excalidraw/excalidraw#3324]
<img width="323" alt="Capture d’écran 2021-03-25 à 14 15 04" src="https://user-images.githubusercontent.com/58598014/112478867-b954d780-8d74-11eb-9e24-04d6d401523f.png">

A tooltip indicating the purpose each button is for would be useful.
(Having hit several times the save instead of save as not knowing what it was for)

**Comment by h7y** [comment]
Tooltip does show up on hover.

**Comment by pwtn** [comment]
My bad, it does indeed... 
But I have to wait for 2 seconds for the tooltip to appear, which is less intuitive than the rest of the interface :)

**Comment by pwtn** [comment]
1.
