### ISSUE TITLE
Scrolling back to content

### ISSUE THREAD

**Issue by medaminemhiri** [excalidraw/excalidraw#3356]
Hi,
when something is drawn on the board , and then the user moves on to draw something else that could be more important .. When you scroll away, the feature of scrolling back to content is inconsistent. It doesn't always take you back to the same place.
The user should be able to choose the part to focus on or it could be the corner with the maximum of drawings.

**Comment by dwelle** [comment]
If I recall correctly, the button centers to the closest visible element. This feels like a good heuristic — if you scroll below the bottom element, it takes you back to it, and likewise when you scroll above the top element.

I'd not complicate it with seemingly arbitrary rules like "pockets with maximum drawing" (not to mention it'd be pretty hard to compute).
