### ISSUE TITLE
In the html source of https://excalidraw.com the meta tag with name "twitter:image" is present twice.

### ISSUE THREAD

**Issue by tzador** [excalidraw/excalidraw#3358]
After running https://www.seoprofiler.com/ on the excalidraw.com site, it discovered duplicate twitter:image meta tag:

    <meta property="og:image" name="twitter:image" content="https://excalidraw.com/og-image.png" />
    <meta name="twitter:image" content="https://excalidraw.com/og-image.png" />

Looks like the second one can be safely removed.

**Comment by h7y** [comment]
[TIL: Twitter allows us to substitute Open Graph <meta> tags for its own.](https://css-tricks.com/essential-meta-tags-social-media/#reconciling-meta-tags)
