### ISSUE TITLE
Add `screenshots` to `manifest.json`

### ISSUE THREAD

**Issue by h7y** [excalidraw/excalidraw#3363]
More context on this https://web.dev/add-manifest/#screenshots

## Example:
<img width="415" alt="Screenshot 2021-03-29 at 6 44 49 PM" src="https://user-images.githubusercontent.com/22396000/112842116-d95f0080-90be-11eb-8a44-fd2508185a37.png">

**Comment by anumithaapollo12** [comment]
I would love to work on designing the screenshots. I'll post an updates soon:)

**Comment by anumithaapollo12** [comment]
I have designed a couple of screenshots. Lemme know if I need to make  any changes to the screenshots!

<img width="853" alt="Screenshot 2021-03-30 at 1 41 14 PM" src="https://user-images.githubusercontent.com/38392250/112956184-d0713c00-915d-11eb-9942-620e1e9f78dd.png">

<img width="853" alt="Screenshot 2021-03-30 at 1 41 08 PM" src="https://user-images.githubusercontent.com/38392250/112956220-d8c97700-915d-11eb-8005-9e89fbdf5bd8.png">

<img width="853" alt="Screenshot 2021-03-30 at 1 41 00 PM" src="https://user-images.githubusercontent.com/38392250/112956237-df57ee80-915d-11eb-9a00-9b9e8882fa63.png">

<img width="853" alt="Screenshot 2021-03-30 at 1 40 53 PM 2" src="https://user-images.githubusercontent.com/38392250/112956331-f991cc80-915d-11eb-8202-9e4dc597fd56.png">

<img width="853" alt="Screenshot 2021-03-30 at 1 40 43 PM" src="https://user-images.githubusercontent.com/38392250/112956381-07dfe880-915e-11eb-9a3d-3e9a84865d95.png">

<img width="853" alt="Screenshot 2021-03-30 at 1 40 32 PM" src="https://user-images.githubusercontent.com/38392250/112956401-0f9f8d00-915e-11eb-8eb3-9a63944bd447.png">

**Comment by h7y** [comment]
> I have designed a couple of screenshots with 2 variants. I'll also make cards explaining each screenshot. Lemme know if I need to make any changes to the screenshots!

Looks good to me! I prefer the black phone variant since the background is white. Describing features in each screenshot would make it perfect. What do you guys think?

**Comment by anumithaapollo12** [comment]
Description of each screenshot with both variants. I have described Excalidraw in a nutshell with the screenshots! Lemme know what you think!

<img width="1201" alt="Screenshot 2021-03-30 at 2 34 16 PM" src="https://user-images.githubusercontent.com/38392250/112963696-40cf8b80-9165-11eb-8634-b4e18b9e3410.png">

<img width="1426" alt="Screenshot 2021-03-30 at 2 34 40 PM" src="https://user-images.githubusercontent.com/38392250/112963769-50e76b00-9165-11eb-8947-bc1a95e1cff7.png">

<img width="1201" alt="Screenshot 2021-03-30 at 2 34 26 PM" src="https://user-images.githubusercontent.com/38392250/112963735-488f3000-9165-11eb-9459-847ba5761a00.png">

<img width="1426" alt="Screenshot 2021-03-30 at 2 34 50 PM" src="https://user-images.githubusercontent.com/38392250/112963794-593fa600-9165-11eb-85f2-4df786f3d0b3.png">

**Comment by anumithaapollo12** [comment]
I have made a few changes to the existing iteration along with a new variation, explaining the screenshots with Virgil.


<img width="1426" alt="Screenshot 2021-03-30 at 4 15 43 PM" src="https://user-images.githubusercontent.com/38392250/112977593-dd992580-9173-11eb-9cbe-4fce20ec77e8.png">

<img width="1426" alt="Screenshot 2021-03-30 at 4 14 22 PM" src="https://user-images.githubusercontent.com/38392250/112977482-bcd0d000-9173-11eb-94ff-b57e29cfd361.png">

<img width="1426" alt="Screenshot 2021-03-30 at 4 14 46 PM" src="https://user-images.githubusercontent.com/38392250/112977332-8d21c800-9173-11eb-94a2-f7116013266e.png">

**Comment by h7y** [comment]
I really like the first and second row. My personal favorite is the first row :) 

What do you guys think?

CC:  @ad1992 @dwelle @lipis

**Comment by ad1992** [comment]
Thanks a lot @anumithaapollo12 for working on this. The screenshots look great ❤️ 

> 
> <img alt="Screenshot 2021-03-30 at 4 42 02 PM" width="1091" src="https://user-images.githubusercontent.com/38392250/112980029-f951fb00-9176-11eb-8742-6c4dad994265.png">
> 

Initial thoughts 
For collaboration can we show the dialog which comes up where user  has to enter name and start the session (shown below)  instead so it's more clear ?
<img width="399" alt="Screenshot 2021-03-30 at 9 40 26 PM" src="https://user-images.githubusercontent.com/11256141/113021399-2915f880-91a1-11eb-9db0-0664f1d4b61f.png">

Let's also add a screen shot for showcasing `libraries` as well.

Also we might want to reorder the screenshots (explore shapes and colors before live collaboration)
 
I like the first two rows, the 2nd row the most as its in Virgil :)

**Comment by dwelle** [comment]
I'd also change the screen for "make hand-drawn illustration & notes" to not contain that old Teams landing page :). I'd use some of the libraries shapes as examples.

Otherwise, looks great. Good job.

**Comment by ad1992** [comment]
closed via https://github.com/excalidraw/excalidraw/pull/3369
