### ISSUE TITLE
When you delete a directory containing the saved file and try to save again nothing happens

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw#3370]
### Steps to reproduce:

1. Create a new directory
2. Create a drawing and save it to that directory
3. Make changes and press save (as expected I'm getting a notification that the file is saved)
4. Delete the directory with that file in it
5. Press save again.

### Result:

1. Nothing happens visually (the user thinks that the file is saved)
2. Console throws an error: `DOMException: A requested file or directory could not be found at the time an operation was processed.`

-----

When you just deleting the file, and save again, the file is being created again.. so that's nice!

### Actions

We should probably ask for a file location again when that happens.

**Comment by dwelle** [comment]
> When you just deleting the file, and save again, the file is being created again.. so that's nice!

Hold on. This is actually what I've been discussing with @tomayac when auto-saving. In that case we want it to throw (and disable the autosave) instead of prompt for a file location.

**Comment by dwelle** [comment]
But yes, we should handle throwing for non-autosave cases like the OP, in which case we should prompt indeed.

**Comment by tomayac** [comment]
I'll keep this in mind when I come up with a suggested solution.

**Comment by dwelle** [comment]
Thanks. Also, I said opt-in but the example I gave is opt-out. I'm not sure which one of those is the best default. I don't care either way, but if you have a strong opinion which is the better default, be sure to go with that.

**Comment by tomayac** [comment]
I have just released v0.16.2 that contains a fix to deal with this. See https://github.com/GoogleChromeLabs/browser-fs-access/commit/c4ce7f0313f9dde923a2220c798e4d5365cdcf32 for details.
