### ISSUE TITLE
Menus and tools are tiny 

### ISSUE THREAD

**Issue by jacklynlaryea** [excalidraw/excalidraw#3372]
For some reason my menus and tools are incredibly small on my imac. (see attached image....using chrome). i've tried resetting the canvas and basically all the commands. can someone help me debug this? Is this a known issue or is there an easy fix?

![image](https://user-images.githubusercontent.com/81694332/113152589-46c87980-9204-11eb-88f0-b47115707be2.png)

**Comment by dwelle** [comment]
From your screens it's not obvious, but is it possible your browser window itself is zoomed out?

If you're in chrome, check the zoom icon in url bar top-right corner. Safari doesn't show you any indicator of zoom status, so you'll need to try to reset it by e.g. clicking inside the color input field and hitting  <kbd>Cmd</kbd>+<kbd>0</kbd>

**Comment by jacklynlaryea** [comment]
this is safari as an example. I've tried cmd+0 many many times. I've tried all the commands. 

The actual canvas is totally fine. it's the controls and tools that are really difficult to even see. 

this is what it looks like in chrome (hopefully the scale of the circle will help here):
![image](https://user-images.githubusercontent.com/81694332/113184800-a4b88980-9223-11eb-9cf0-f9542f669cb2.png)

This is safari below. Notice the actual controls are much larger in safari.
![image](https://user-images.githubusercontent.com/81694332/113184904-c0bc2b00-9223-11eb-97b0-541248510b54.png)

I can barely even see what i'm doing in terms of the controls on google chrome. the program is not actually usable in chrome anymore so I can only use safari. Is there any fix?

**Comment by dwelle** [comment]
Can you include the chrome window with the url bar in the screenshot? Also, what's your screen resolution?

**Comment by jacklynlaryea** [comment]
yes here you go!
![image](https://user-images.githubusercontent.com/81694332/113337054-3fcd6400-92f5-11eb-9efd-1a6da6e7885b.png)

i'm on a mac and my screen resolution is "default". I don't think it's a resolution issue as i've used this program for about a year at this point on this computer and the tools have always been normal size. I think I did something.

my browser is 100% as well. i've reset it many times :(

**Comment by dwelle** [comment]
> my browser is 100% as well. i've reset it many times :(

I think this icons begs the differ :)

![image](https://user-images.githubusercontent.com/5153846/113355498-281bcd00-9341-11eb-86c4-2e93067e6d83.png)

Try clicking on it.

**Comment by ad1992** [comment]
As pointed out by @dwelle, this should be fixed once browser zoom is reset. @jacklynlaryea feel free to reopen the issue if it still persists.
