### ISSUE TITLE
Allow dragging if click was inside shape rectangle

### ISSUE THREAD

**Issue by nanot1m** [excalidraw/excalidraw#339]
It's a little bit complicated to move elements around — if you click past the stroke all the selection removes.

Maybe allowing clicking inside bounding box to drag elements (as Figma does) around would work better?

![Kapture 2020-01-12 at 18 51 05](https://user-images.githubusercontent.com/9278185/72219882-bfdea100-356c-11ea-8fbd-014d19e53914.gif)

**Comment by dwelle** [comment]
Yes, I believe we should allow drag-inside even for non-bg shapes, IFF the shape is already selected. I think we even agreed on this in another issue/PR, but maybe I'm mistaken.
