### ISSUE TITLE
Popover position incorrect on Safari for non-zero offsets/scroll

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#3394]
Also for non-zero scroll offsets.

![image](https://user-images.githubusercontent.com/5153846/113505526-a645c280-953f-11eb-9c36-85cabe3d3bc3.png)

**Comment by dwelle** [comment]
This actually affects all popovers.

@ad1992 any reason why you made it `fixed`? https://github.com/excalidraw/excalidraw/pull/3018/files#diff-61cd250cd764c806c24bae993a1482b328fbf9df906e4f85afc50b7b6dcf99aeR3

**Comment by ad1992** [comment]
> This actually affects all popovers.
> 
> @ad1992 any reason why you made it `fixed`? https://github.com/excalidraw/excalidraw/pull/3018/files#diff-61cd250cd764c806c24bae993a1482b328fbf9df906e4f85afc50b7b6dcf99aeR3

Yes it was breaking context menu thats why kept it fixed and was working fine in host as well. is it just safari or all browsers ?
