### ISSUE TITLE
The typescript example has some errors

### ISSUE THREAD

**Issue by rxliuli** [excalidraw/excalidraw#3413]
Some types of problems were found when used in actual projects, please refer to:

before fixing: https://codesandbox.io/s/excalidraw-types-9h2dm
After modification: https://codesandbox.io/s/excalidraw-types-forked-wsp4s

![image](https://user-images.githubusercontent.com/24560368/113981971-d1e7e600-987a-11eb-8f8c-26f35cbd3eea.png)
![image](https://user-images.githubusercontent.com/24560368/113982261-1c696280-987b-11eb-99e3-1eb06a12c379.png)

**Comment by ad1992** [comment]
yep had kept the errors for users to play around with the types but looks like it created confusion. 
I have updated the example. Thanks @rxliuli 👍
