### ISSUE TITLE
Add line shape

### ISSUE THREAD

**Issue by nanot1m** [excalidraw/excalidraw#344]
Practically everyone whom I showed the excalidraw was wondering how to draw a simple line.

People from the twitter are using rectangles to draw lines:
https://twitter.com/sompylasar/status/1216240070631383041/photo/1

**Comment by vjeux** [comment]
Agreed. PR welcome

I was thinking that we'd wanted to have multi-point lines before doing it but we may be able to workaround by just adding single lines and people can combine them.

**Comment by muzakparov** [comment]
looking into it

**Comment by pshihn** [comment]
Have you all thought about keeping line/arrow the same, just with different 'end decorators'? Then you can have two-headed arrows, or any other end-decorators in the future.

**Comment by nanot1m** [comment]
Closed by #371
