### ISSUE TITLE
Docs: Excalidraw Development for Dummies

### ISSUE THREAD

**Issue by guettli** [excalidraw/excalidraw#3445]
I think it would be beneficial for Excalidraw, if you would explain how to setup a development environment.

I guess there are more people like me, who have some programming experience, but they never developed with JavaScript.

I have read CONTRIBUTING.md, but people new to JS need some help to get and running.

Questions which could be answered in this new text:

* Which IDE is recommended (I guess vscode)?
* How to install install and run yarn?
* ...

**Comment by ad1992** [comment]
You can always start with [codesandbox](https://github.com/excalidraw/excalidraw#code-sandbox) to avoid the steps needed to set up and run local.

> Which IDE is recommended (I guess vscode)?

Its up to you, you can start with whichever IDE you are comfortable with vscode, webstorm, sublime, ruby mine anything

> How to install and run yarn?

Though the set of commands are explained in https://github.com/excalidraw/excalidraw#commands

I think we can explain here the steps sequentially if anyone wants to run in local, that might help
```js
yarn
yarn start
```

**Comment by dwelle** [comment]
We should maybe link to yarn installation itself: https://classic.yarnpkg.com/en/docs/install

**Comment by guettli** [comment]
> You can always start with [codesandbox](https://github.com/excalidraw/excalidraw#code-sandbox) to avoid the steps needed to set up and run local.
> 
> > Which IDE is recommended (I guess vscode)?
> 
> Its up to you, you can start with whichever IDE you are comfortable with vscode, webstorm, sublime, ruby mine anything
> 
> > How to install and run yarn?
> 
> Though the set of [commands](https://github.com/excalidraw/excalidraw#commands) are explained in readme
> 
> I think we can explain here the steps sequentially if anyone wants to run in local, that might help
> 
> ```js
> yarn
> yarn start
> ```

Hi @ad1992 I know that you can choose any IDE you want. But if you want to make it easy for new comers, than it is great if there is one documented default way.
