### ISSUE TITLE
Performance. Cache rendered shapes in offscreen canvas

### ISSUE THREAD

**Issue by nanot1m** [excalidraw/excalidraw#346]
From the #302 

>The better solution would be to cache shape image in offscreen canvas, and then reuse it to draw the scene.
>
>It will help us to get rid of caching shape in the element and also will help to avoid expensive calls of draw function on every render.

**Comment by vjeux** [comment]
I feel like we should come up with proper measurement before looking into all sorts of performance optimizations. There are a few phases:

- Mousemove handler that modifies a bunch of javascript objects
- Converting the scene into draw commands
- Actually executing the draw commands

We should make sure that we know what is done with each phase, what are the costly operations within each and how big of a pie they represent.

Then, we can start strategizing around how to optimize them.

**Comment by vjeux** [comment]
Done!
