### ISSUE TITLE
Feat Request: Transparent Colors

### ISSUE THREAD

**Issue by mattlockyer** [excalidraw/excalidraw#3464]
Would be nice to be able to add transparency to strokes and backgrounds.

Using hex syntax would be easy to extend e.g. FFFFFFxx where xx is the alpha value.

Ref: https://www.digitalocean.com/community/tutorials/css-hex-code-colors-alpha-values

**Comment by dwelle** [comment]
You can already do that, no?

**Comment by mattlockyer** [comment]
OMG... you can! Sorry I thought I had tried this but it didn't work for me, I must have entered too many Fs ;)
