### ISSUE TITLE
iPadOS free draw occasionally causes text selection

### ISSUE THREAD

**Issue by kevinjalbert** [excalidraw/excalidraw#3468]
When using the free draw feature in Excalidraw on my iPad (iPadOS 14), it'll occasionally do a text selection. This makes it hard to use as that text selection will _eat_ up the drawing stroke.

![IMG_7BD0677E7F36-1](https://user-images.githubusercontent.com/574871/115176584-66342300-a09b-11eb-9e5d-ec2bab28b957.jpeg)

I've tried this in Chrome and Safari.

-----

Not sure if this is something that _can_ be fixed?

**Comment by aloknnikhil** [comment]
Yes. This is particularly annoying when you try to write text in free hand with the pen. It almost feels like Safari thinks I am trying to select text as I draw with the pen held against the screen for a long time (if you know what I mean).

**Comment by dwelle** [comment]
As I don't have an iOS device, can't debug, and it doesn't happen on Android. But from the screen it looks like some texts we have for a11y/SEO purposes (?) might be the culprit.

Can you try if it's fixed here? https://excalidraw-git-preventselectionofhiddenstuff-excalidraw.vercel.app/

/cc @j-f1 don't recall if you introduced those. If so, does it really play any part and can we get rid of them? These texts keep causing issues for us :).

**Comment by j-f1** [comment]
I don’t recall adding them, but they look like they’re intended for screen reader support.

**Comment by j-f1** [comment]
Screen reader support in Excalidraw right now seems borderline unusable so not sure how much value it is providing.

**Comment by aloknnikhil** [comment]
> Can you try if it's fixed here? https://excalidraw-git-preventselectionofhiddenstuff-excalidraw.vercel.app/

Yes! It works much better for me. There's no selection box popping up anymore. Although, something still seems to be eating up strokes. I keep having to go back and redo the strokes.


https://user-images.githubusercontent.com/8571509/116010868-80f42380-a5d6-11eb-8636-2203e37d3869.mov

**Comment by dwelle** [comment]
Mhm :( --- anyway, I'll merge that one to have at least some improvement! Can you create a new issue for the other thing please?
