### ISSUE TITLE
Allow cut event outside Excalidraw

### ISSUE THREAD

**Issue by zsviczian** [excalidraw/excalidraw#3475]
When Excalidraw is open on a parallel worksheet Ctrl+x: to cut part of the title of a worksheet in Obsidian copies an empty Excalidraw element instead. 
[https://screenrec.com/share/kvOCZ7WHxI](https://screenrec.com/share/kvOCZ7WHxI)
Issue confirmed with 0.6.0 and with 0.7.0-libs2

{"type":"excalidraw/clipboard","elements":[]}

**Comment by ad1992** [comment]
We already allow cut event when the target element is [input like](https://github.com/excalidraw/excalidraw/blob/d3106495b2d85af8244709f93ca8296b10df20a7/src/utils.ts#L58)  

The case where this can be a problem is when the host has custom cut events on non-input like elements that are not getting triggered coz of the `event.preventDefault` on excalidraw.

@zsviczian can you try if it's working in `"aakansha-excalidraw": "0.7.0-cutfix`

**Comment by zsviczian** [comment]
I confirm the issue is now resolved.

**Comment by ad1992** [comment]
Thanks for confirming @zsviczian 👍🏻  , will close once the pr is merged
