### ISSUE TITLE
Clicking on a rectangle, then text inside selects both

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#348]
Repro:
- Create a rectangle with background
- Create a text in the middle
- Click on the rectangle
- Click on the text (WITHOUT shift)
- Both are selected. Only the text should be selected

![ezgif-6-851fd2758827](https://user-images.githubusercontent.com/197597/72224305-e7fadf80-352d-11ea-9592-b47cdc7d0035.gif)

cc @dwelle

**Comment by dwelle** [comment]
Not just text, but anything:

Looks like the regression was indeed introduced in my last PR :/
