### ISSUE TITLE
use updateScene to set the appState.theme

### ISSUE THREAD

**Issue by zsviczian** [excalidraw/excalidraw#3485]
I'd like to use updateScene to set the appState.theme when loading a new drawing to the component, to avoid having to unmount and remount the component, and to avoid having to implement the theme button in the encapsulating application. 

Yes, the theme can be set via props, but then the UI will not show the built-in theme change button.

Currently the only solution is to unmount and remount and using initdata to set the theme.

dwelle — 2021-04-22 at 8:35 PM
ultimately we should really allow hosts to do what they want in the updateScene(), even if this case is probably best served with theme prop

**Comment by ad1992** [comment]
closed via https://github.com/excalidraw/excalidraw/pull/3576
