### ISSUE TITLE
Mobile UI is broken

### ISSUE THREAD

**Issue by xixixao** [excalidraw/excalidraw#3496]
Safari nor Chrome show the hamburger menu. I can't even remember what the app should look like.

|safari|chrome|
|---|---|
|![IMG_3390](https://user-images.githubusercontent.com/1473433/115977117-9a1cb600-a57d-11eb-8c85-2a027234dcec.PNG)|![IMG_3391](https://user-images.githubusercontent.com/1473433/115977120-9c7f1000-a57d-11eb-8fc2-623e944984f1.PNG)|

iPhone 11 Pro
ios 14.4.2

Apologies if this is a duplicate issue, I skimmed and couldn't find it.

**Comment by dwelle** [comment]
Mhm, Android has similar issue: 

![image](https://user-images.githubusercontent.com/5153846/115987339-e9caa400-a5b4-11eb-967e-cfc33b927be4.png)

The menu can be pulled up which scrolls the browser down. So it seems we're not making the app full-viewport on mobile.

**Comment by dwelle** [comment]
Should be fixed via https://github.com/excalidraw/excalidraw/pull/3508 — comment/reopen if there are any issues still.

**Comment by xixixao** [comment]
Fixed indeed <3
