### ISSUE TITLE
Financování místních developerů

### ISSUE THREAD

**Issue by RLCREAT** [excalidraw/excalidraw#3499]

**Comment by dwelle** [comment]
Co to :)

**Comment by RLCREAT** [comment]
Sorry .-)) něco jsem zkoušel si modelovat  .. a očividně v tom mám chaos  ..nepochopil jsem přesně tuto platformu ... vůbec nevím jak se to k vám dostalo 🙈 .. přeji hezký nedělní večer . Radek L 

Odesláno z iPadu
