### ISSUE TITLE
Project structure

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#35]
Let's discuss (and aggregate issues on) project structure, styleguide, etc.

- [x] Add Prettier.
- [x] Move to [TypeScript](https://github.com/vjeux/excalibur/issues/34).
- [x] ESLint (IMO, at least for react)?

# To be decided

- [ ] Currently, we're using classical React. Do we want to move to hooks?
- [ ] Testing. Jest? (actually, don't think we'll be able to test canvas workflow in Jest.)

**Comment by AndreBastos23** [comment]
IMO we should migrate to functional react, i dont see any benefit is us having this in classes. Maybe @vjeux could clarify if we have any technical blocker to migrate this to hooks.
I also think we should add eslint, it would help us alot when this project grows.
(In case we decide to add eslint) - We could also add a pre-commit hook using husky to lint and prettify the code before commiting.

**Comment by vjeux** [comment]
I started with hooks but couldn’t figure out how to read up to date variables when using addEventListener for window mousemove. If you can make it work that’d be awesome :)

https://github.com/vjeux/excalibur/commit/457800caa369bdb358727eeb3f193490d4400984

**Comment by vjeux** [comment]
I’d be happy with eslint, prettier, typescript and jest

**Comment by nanot1m** [comment]
Jest is already installed in the project (via react-scripts package)

**Comment by giovannigiordano** [comment]
@nanot1m @vjeux can we close it?

**Comment by dwelle** [comment]
ad 2: Cypress won't help here until they implement non-synthetic, native events (at least as far as interacting with the canvas is concerned). We could go with Puppeteer & CDP, or something like Selenium & WebDriver.

**Comment by giovannigiordano** [comment]
@dwelle with cypress you can interact with canvas using mouse events and maybe compare the result as a screenshot.

**Comment by dwelle** [comment]
@giovannigiordano I thought we'd need to fire proper events. I'll investigate if we can emulate the tests in Cypress by triggering mouse events programmatically.

**Comment by dwelle** [comment]
@giovannigiordano you were right, so far it seems we could make it work. https://github.com/excalidraw/excalibur/issues/63

**Comment by dwelle** [comment]
What's the latest on npm vs yarn? I thought we started with yarn.

So, have we settled on npm, and should we install everything via npm so that we keep `package-lock` up to date?

**Comment by giovannigiordano** [comment]
@dwelle I introduced yarn and then npm to use it in the deploy action, to avoid the usage of a custom action which integrates yarn (the nodejs action has npm). 
The project is small, we don't have too many dependencies, so let's focus on other features.

**Comment by GasimGasimzada** [comment]
Would you guys be interested in splitting the code into multiple files? I believe that it will improve dev workflow as it is easier to navigate through smaller files instead one large file.

**Comment by vjeux** [comment]
I feel like we've done the original scope of this issue.
