### ISSUE TITLE
Improve free-hand drawing

### ISSUE THREAD

**Issue by steveruizok** [excalidraw/excalidraw#3500]
By request from @vjeux, this week I'll be working to implement [`perfect-freehand`](https://github.com/steveruizok/perfect-freehand) in Excalidraw to improve the free drawing experience.

## Lines are hard

Like many vector tools, Excalidraw's pencil tool leaves something to be desired when it comes to writing words or glyphs. While it's fine for drawing shapes, annotation marks often lines with varying widths caused by pressure. This pressure can be real, if a device supports that type of input, or else simulated based on the movement of the pointer. In any case, when this part of the story is left out, lines can look a little bland.

![Kapture 2021-04-25 at 18 26 32](https://user-images.githubusercontent.com/23072548/116002928-cc68fa80-a5f3-11eb-878e-4565fe74c3ba.gif)

A few months ago I got hooked on this problem of drawing pressure-sensitive freehand lines, which to my surprise lacked an open source solution. After a few weeks of experimentation, I released the result as [`perfect-freehand`](https://github.com/steveruizok/perfect-freehand) and have spent the last few months doing gradual improvements. Still not quite "perfect" but there's lots to like and plenty of [knobs to turn](https://perfect-freehand-example.vercel.app/).

![Kapture 2021-04-25 at 18 24 28](https://user-images.githubusercontent.com/23072548/116002866-86ac3200-a5f3-11eb-804d-23e24d70e38d.gif)

## How would this look in Excalidraw?

Because the pencil tool was never _really_ meant for freehand drawing, adding in this feature raises some interesting product questions. I'd like to use this thread to discuss how improved free drawing will best fit in with the rest of the product, and to keep track of the progress. 

I'll kick things off with how I imagine it could work.

#### Leave the pencil tool as it is

In our case, I don't believe that we should change or replace the pencil tool. While not ideal for writing notes or annotations, Excalidraw's pencil tool is quite good at its other tasks, such as drawing lines or closed shapes that can be adjusted point-by-point or extended.

#### Introduce the pen tool

Instead, I would propose creating a new tool: the **Pen** tool. (I imagine this as more of a gel-pen than a fountain pen, though that's up for discussion.) This tool would have some significant differences when compared with the Pencil tool:

Separate marks made within a certain time frame would be considered the same mark, for purposes of selection. I've worked this out on another project [telestrator](https://github.com/steveruizok/telestrator), where such a system prevented letters at the beginning of a word from fading while a user was still writing letters at the end of a word. In our case, a user would probably want to select / move / delete an entire annotation that may be built of many separate marks.

The marks made by a pen tool would not be editable in the same was as lines drawn with the pencil. There's no reason why this _must_ be the case, but again the types of user behaviors around annotations are different than shape-making. You're more likely to undo and re-write a typo or poor line than adjust it.

The visuals of pen marks vs pencil lines are up for debate. I'll have to see how it looks to be sure, but my guess is that marks made with the pen tool would look a bit different from the rest of the rough.js family. That library approximates free-drawn shapes; this tool would support free-drawing directly (or at least more closely). Such differences may be removing sloppiness property and supporting only solid fills. 

As mentioned above, the `perfect-freehand` library has a lot of knobs to turn if you want to customize the way that pressure is used or simulated. In fitting with the rest of the app's approach to tools, I suggest we expose exactly none of these options, and instead have one line style with three widths.

Beyond those, I think these types of shapes would behave just as any other in Excalidraw.

What do you think?

**Comment by Milo123459** [comment]
I personally love this idea. Few comments on perfect freehand:
The dots, ie clicking sometimes get cut off (see video below)
Other then that, really cool! Would love to see this in excalidraw.

![img](https://salvage.is-inside.me/JLcPlglo.mp4)

**Comment by vjeux** [comment]
I would recommend replacing the Pen tool altogether. The current one doesn't produce great results when the orientation changes quickly:

![image](https://user-images.githubusercontent.com/197597/116010307-0b3a8880-a5d3-11eb-8363-6fb6c074965d.png)

In order to make lines with multi-points, you can already use the line tool and click many times. I don't think that it's necessary to be able to edit points for the pencil one.

One thing I want to figure out though is how to match the aesthetic of the two as much as possible. Right now they look distinctive enough, I wonder if there's a way to tweak the style.

**Comment by dwelle** [comment]
I agree with vjeux. The pencil is just an abstraction on top of line tool so we won't lose any critical behavior by replacing the pen tool (which means the migration of existing `draw` elements will simply consist of changing the type to `line`).

I've personally never used `draw` tool to create anything other than writing (but that's just my experience) as it tends to create too many points which are then hard to modify.

---

As for the implem: I'll just repost what I said in the chat about katachidraw not being based on excalidraw, in case you were depending on it for something. As such, you'll be breaking new ground here. My guess is you'll have to rasterize the SVGs, at which point it'll then behave as regular excalidraw elements like you said.

I agree that the new pen tool doesn't need to be editable (at least its points), but it may be valuable to allow erasure which was requested several times for our current free draw tool — for the new pen tool it might actually make sense (though, it would require adding yet another tool, so let's maybe leave that decision for the future).

**Comment by steveruizok** [comment]
> I personally love this idea. Few comments on perfect freehand:
> The dots, ie clicking sometimes get cut off (see video below)
> Other than that, really cool! Would love to see this in excalidraw.
> 
>  JLcPlglo.mp4

Hopefully I'm able to spend a bit of time toward the end of the week improving the library; or if nothing else, the app will benefit from later improvements. Having it working in Excalidraw should also generate a lot of good feedback and catches like yours. (Dots and short strokes are surprisingly hard to get right!)

**Comment by steveruizok** [comment]
Ok, I'll look at replacing the pen tool.

> On the other hand, users may want to move around even disconnected shapes that are not part of writing. E.g. if they draw two circles and they won't be able to move them around separately, that may not be nice.

That's a good point. We could do a pretty short timeout, or perhaps indicate in some visual way that an annotation has finished. I'll do some experimentation here later in the week.

As for erasing: we've got a few options. 

To help discussion, and maybe others in this thread, here's a quick breakdown of how the perfect-freehand algorithm works.

![image](https://user-images.githubusercontent.com/23072548/116058691-ff54d200-a677-11eb-9d2f-499a67be344f.png)*1. Starting from an array of points, usually captured from pointer movement.*

![image](https://user-images.githubusercontent.com/23072548/116058915-37f4ab80-a678-11eb-8d59-b8e9fb630b16.png)*2. Iterate through points, make some adjustments for a smoother line, and capture data for simulated pressure.*

![image](https://user-images.githubusercontent.com/23072548/116059161-74c0a280-a678-11eb-84bd-6c861424b78b.png)*3. For each point, create two new points on the left and right of a point. Add caps at the beginning, end or wherever we detect sharp turns.*

![image](https://user-images.githubusercontent.com/23072548/116059551-ded94780-a678-11eb-957a-83d3eff5b337.png)*4. Return these points in winding order. Use a separate algorithm to find curve segments for each point.*

### Erasing

A simple erase feature would check for collisions between the user's brush and any of those initial (orange) points and create new marks as needed (either by stripping points off of the start or end of the array, or by creating new arrays and marks when removing points from the middle). 

For thicker lines, this would mean that the brush may collide with the stroke but not with an initial point. So a better but more complex approach could check for collisions with tube points (or even the actual curve between tube points), and strip the associated initial point.

![image](https://user-images.githubusercontent.com/23072548/116060555-e3523000-a679-11eb-854e-f8d7b44471a3.png)

This would create more of a white-board style erasing. (And could look pretty cool). For a more simple feature, we could detect a collision and delete the entire mark.

![image](https://user-images.githubusercontent.com/23072548/116060717-04b31c00-a67a-11eb-82a7-74883f0ac7b5.png)

And if we used the type of related-mark-flattening approach I showed above, where separate marks made within a certain time-between-marks are considered part of the same "annotation", we could have any collision remove the entire annotation.

![image](https://user-images.githubusercontent.com/23072548/116061446-c4a06900-a67a-11eb-9244-62fa97cef6b6.png)

Again it's difficult to say which would be better. Forcing a user to chase down every point in their mark may be annoying; wiping out the full mark may be frustrating. I'd recommend starting broad and then implementing he more fine-grained erasing as needed.

**Comment by dwelle** [comment]
Thanks for the explanation, it's great.

> That's a good point. We could do a pretty short timeout, or perhaps indicate in some visual way that an annotation has finished. I'll do some experimentation here later in the week.

Yeah, both venues sound interesting but would require trying out. So I guess let's start with a short timeout since that's the easier way.

> Again it's difficult to say which would be better. Forcing a user to chase down every point in their mark may be annoying; wiping out the full mark may be frustrating. I'd recommend starting broad and then implementing he more fine-grained erasing as needed.

Sounds good. But again, I'm not even sure if everyone on the team is ok with adding an eraser tool, so let's leave it for last/later. (We could also experiment by using right-click-drag to erase, but that wouldn't work on mobile.)

**Comment by steveruizok** [comment]
Ok, first steps are in! You can follow along [here](https://github.com/steveruizok/excalidraw/tree/feature/freedraw).

![Kapture 2021-04-26 at 15 57 57](https://user-images.githubusercontent.com/23072548/116104316-40fd7100-a6a8-11eb-9d80-462af5c2bb5e.gif)

### How it works

Here's a quick description of how it works. You can see the fork here: :

1. Starting a drag with the draw tool selected creates a new element with the "draw" type. This element is a cut-down version of LinearElement with two additional properties: `simulatePressure` and `pressures`. We set `simulatePressure` to `true` if the initial pressure reported by the PointerEvent is anything other than `.5`.
2. As the user drags, we push points to the element's points array. If `simulatePressure` is `false`, we also push the input's pressure to the `pressures` array.
3. When we render the mark, we get the mark's polygon points using `perfect-freehand`, turn these points into SVG path data, and pass that data to `generator.path`.

### Notes

Free drawing is very performance-sensitive so I'm keeping an eye out for any opportunity to reduce the load while a user is actively free-drawing. For example, I noticed that we calculate bounds for all elements on every render, which for curves can be very expensive. Perhaps these checks can be cached, or even skipped while creating a shape?

Are there other ways that we can improve the "while-drawing" performance?

On a related note, the `getMinMaxXYFromCurvePathOps` became very hot while calculating the bounding box of a mark, due to its many points and number of operations. Luckily, these points are close enough together that we can use the points themselves (in the same way we would for a polygon) which together with our stroke-width will give an approximately correct bounding box.

For some reason, the `generator.path` function is not returning curved paths. I'll need to experiment with this to see why not.

![image](https://user-images.githubusercontent.com/23072548/116106910-70ad7880-a6aa-11eb-80d9-672fdfa9f8ab.png)

### Next Steps

- [ ] Clean up the options panel, which currently shows many of the linear element options that I've cut from the draw element.
- [ ] Collect related strokes into the same shape.
- [ ] Start thinking about erasing.

**Comment by pshihn** [comment]
@steveruizok rough's `generator` reduces the path to linear points so it will never return curves. Since you are actually very close to drawing by hand, maybe you don't need to pass your sketch through rough's reduction

**Comment by vjeux** [comment]
> Since you are actually very close to drawing by hand, maybe you don't need to pass your sketch through rough's reduction

Yeah, you want to generate the svg directly. You can look at the rendering for text for an example of how to bypass rough.

**Comment by vjeux** [comment]
> Are there other ways that we can improve the "while-drawing" performance?

You should trace everything happening while drawing and see if it makes sense and if not stop it from happening. Happy to go through specific cases you observe.

**Comment by steveruizok** [comment]
Oh yeah, that's much faster. 🐇 Something to work on tomorrow.

**Comment by dwelle** [comment]
Woah, nice progress.

One benefit of using Rough is we can apply different stroke styles to it: 

![image](https://user-images.githubusercontent.com/5153846/116145132-301b2280-a6dd-11eb-87c2-6508efefab0d.png)

But it's probably not that useful for free draw, so let's skip Rough for the perf benefits.

**Comment by dai-shi** [comment]
<img width="521" alt="image" src="https://user-images.githubusercontent.com/490574/116158646-f9b7c480-a729-11eb-8244-1ae1c216df42.png">

**Comment by steveruizok** [comment]
Ok, now that I'm caching things correctly, the performance issues have gone away. I'll note the performance optimizations but as they're no longer blockers, I'm not going to focus on them.

![Kapture 2021-04-27 at 13 14 55](https://user-images.githubusercontent.com/23072548/116239488-9e51fa80-a75a-11eb-8f81-b3559cb2dea3.gif)

One thing that is tripping me up is multiple-selection resizing. 

Single-item resizing works fine...

![Kapture 2021-04-27 at 13 19 04](https://user-images.githubusercontent.com/23072548/116240267-89c23200-a75b-11eb-9123-47ca28d4d481.gif)

But with multiple-item resizing, the rescaled bounding boxes are always off by some amount. This leads to "drifting":

![Kapture 2021-04-27 at 13 20 25](https://user-images.githubusercontent.com/23072548/116240202-7adb7f80-a75b-11eb-95b0-41054c6282db.gif)

I'm not sure why this is the case (or why there are two separate implementations for single vs multiple item resizing). My guess is that there is a problem with how points are scaled but I'm having a difficult time finding it. If anyone more familiar with this part of the codebase can spare a glance, I'd appreciate it!

**Comment by dai-shi** [comment]
It seems like the bounding box calculation for multiple selection is not correct. just from the last animation.

**Comment by dwelle** [comment]
Playing with it the behavior looks similar to https://github.com/excalidraw/excalidraw/issues/2896

![excal_group_resize](https://user-images.githubusercontent.com/5153846/116244908-aca71300-a768-11eb-8f7a-33ec5823e46d.gif)

**Comment by steveruizok** [comment]
Wrapping up my second day on this project: say hello to stroke shapes.

![image](https://user-images.githubusercontent.com/23072548/116261571-aec0a000-a76f-11eb-95ac-3226159d75c6.png)

There are three stroke shapes, each with its own configuration for the perfect-freehand algorithm. 

- **Gel** is streamlined but has no thinning. It is rendered as a stroked line rather than a polygon.
- **Fountain** produces a thicker line as pressure increases.
- **Brush** produces a thinner line as pressure increases.

The differences between the brush shapes are most noticeable when using a stylus. 

![Kapture 2021-04-27 at 15 54 13](https://user-images.githubusercontent.com/23072548/116263286-293def80-a771-11eb-97a9-5ba47c05d4b1.gif)

I'd like to have one perfect line, however different people tend to write in different ways. Depending on how you tend to push your mouse or stylus, you'll prefer one over another. Many annotation tools allow greater customization: adjusting the pressure curve, tapering, etc—my hope is that having three good shapes should be enough.

### Thicker lines?

I've gone with a slightly thicker line for the pen tool, as compared to the other tools. I'm hoping this provides the right contrast between hand-drawn lines and regular lines, but I'm happy to continue tweaking. (I have a hunch that the line width should really be based on zoom level, rather than strictly stroke width, and may experiment a little there).

![image](https://user-images.githubusercontent.com/23072548/116264923-9605b980-a772-11eb-87e1-ddf5f1058355.png)

**Comment by steveruizok** [comment]
Moving this into a PR so that we can get deployments going.

**Comment by solarkraft** [comment]
Please excuse my ignorance: Has this not been released yet? The drawing feature on Excalidraw.com doesn't appear to work anything like the perfect-freehand demo (appearing to lack pressure sensitivity, showing typical SVG stroke artifacts).

**Comment by solarkraft** [comment]
Never mind, it appears to behave much like the freehand demo, just without all of the options. 
Unfortunately this is a problem because the excessive smoothing eats up a lot of details.

**Comment by paolomainardi** [comment]
Does it require a special pen and/or a specific browser/operating system? Wanting to try it with a Wacom tablet, just asking before buying something wrong :)

**Comment by solarkraft** [comment]
Not this feature itself. But you may be disappointed about the level of detail you'll get out of your device. I've found that browsers on Android generally don't emit events at a high enough resolution, making this not very usable. The situation with desktop OSes may be different.
