### ISSUE TITLE
Firefox - Error importing PNG/SVG with embedded scene data

### ISSUE THREAD

**Issue by aganoza** [excalidraw/excalidraw#3513]
First thanks for the app it's super useful 😄 

Just discovered this functionality https://github.com/excalidraw/excalidraw/pull/2219 

But it seems to swallow the error when trying to import a PNG/SVG with embedded scene data in Firefox 88.0 (64-bit)

Tried the same in Chrome 90.0.4430.93 (64 bits) successfully.

Firefox to the left, Chrome to the right

![bug-firefox](https://user-images.githubusercontent.com/7707306/116286089-72337b00-a754-11eb-95d2-880676a0f4be.gif)

**Comment by dwelle** [comment]
Works for me. Can you share the file? You can rename the extension to `.txt` and github will allow you to upload it here as a comment.

**Comment by aganoza** [comment]
ok, this is the file [bug-firefox.zip](https://github.com/excalidraw/excalidraw/files/6387808/bug-firefox.zip)

**Comment by dwelle** [comment]
That file works for me as well on FF 88.0 :(.

**Comment by dwelle** [comment]
But it looks eerily similar to https://github.com/excalidraw/excalidraw/issues/3155 — will investigate later

**Comment by tomayac** [comment]
For the original poster, could you please see this [comment](https://github.com/GoogleChromeLabs/browser-fs-access/issues/53#issuecomment-863830427) and help test it? Thanks!

**Comment by bric3** [comment]
For reference I noticed this issue with AdGuard. Disabling it on excalidraw.com restored the feature.
