### ISSUE TITLE
Does @excalidraw/excalidraw have `exportToJSON`?

### ISSUE THREAD

**Issue by azu** [excalidraw/excalidraw#3532]
It looks [@excalidraw/excalidraw](https://www.npmjs.com/package/@excalidraw/excalidraw#onChange) does not have an export function to create `.excalidraw` file.

I want to get a JSON object(`.excalidraw`) from excalidraw instance to avoiding save dialog.

## Use Case

I'm creating integration with an editor like [Inkdrop](https://www.inkdrop.app/).
I want to save the content as `.excalidraw` automatically when editing the canvas.

illustration of code.

```jsx
       <Excalidraw
          initialData={savedData}
          onChange={(elements, state) => {
            const data = { elements, state }; // <= this is invalid format
            writeFile("path/to/file.excalidraw", JSON.stringify(date), "utf-8");
          }}
        />
```

However, `@excalidraw/excalidraw`  does not expose `serializeAsJSON` function.
It normalizes the `elements` and `state`.

https://github.com/excalidraw/excalidraw/blob/5c73c5813ce92d3c7b0610530f78ccb06a47d983/src/data/json.ts#L16-L29

Current workaround: I've copied the `_clear*` logics from excalidraw codebase.

https://github.com/azu/inkdrop-excalidraw/blob/79e1057813b61fe90db227c6bff23c9618fa32ab/src/providers/helper.js

**Comment by dwelle** [comment]
Good point. Will do.
