### ISSUE TITLE
Unable to share session

### ISSUE THREAD

**Issue by ssabnis** [excalidraw/excalidraw#3536]
I hosted the excalidraw in our internal setup, I am unable to share the session. 
Also following error after I setup on Mac and tried to share with other computer
![image](https://user-images.githubusercontent.com/1276281/117233401-e8c91c00-add7-11eb-9c51-a28f3372d123.png)

![image](https://user-images.githubusercontent.com/1276281/117233501-1615ca00-add8-11eb-880b-833509178e16.png)

**Comment by dwelle** [comment]
The [`window.crypto.subtle`](https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto) API is available only on secure domains (HTTPS) or on `localhost`. Judging by the fact you blurred the domain, I suppose you're running a localhost alias? That I believe doesn't count as localhost from that API's perspective.

**Comment by ssabnis** [comment]
Thanks for the reply, Yes it is localhost, if I have install HTTPS, what I need todo. On legit LINUX node?

**Comment by dwelle** [comment]
So do I understand it correctly the localhost is using a DNS record alias? If so, the simplest solution is to simply use `localhost` directly.

OS shouldn't be a factor, but I have never used SSL on localhost so you'll have to research that. I believe you can self-sign without involving a 3rd party certificate authority. If you figure it out you can post the steps here for others.

**Comment by dwelle** [comment]
Closing. If the issue persists, please supply more info as per previous comment!
