### ISSUE TITLE
public shareable urls

### ISSUE THREAD

**Issue by woloski** [excalidraw/excalidraw#354]
google drawing allows you to generate a public url that renders the drawing in png

use case: embed the image in a gh issue
https://twitter.com/vjeux/status/1216228555652075520?s=21

The benefit is that you get auto-updates on that image. Very useful for docs, wikis, etc like gh issues, notion, confluence, gdocs. Keep one source of truth.

It requires a server piece ofc. I think `zeit now` would be a good fit for this. You get great latency and cache through their cdn for free. And you can provide a one-click deploy experience for users who want to host it themselves.
cc @rauchg

**Comment by vjeux** [comment]
Agreed, would be great! We tried adding it in the hash but it ended up being too big and had to be reverted ( https://github.com/excalidraw/excalidraw/pull/220 ).

What we'd need is the ability to upload a json somewhere and get a unique id to retrieve it back. Do you know a (hopefully free and that doesn't require login) service that can provide that? You mentioned `zeit now`, do you know how that would work?

**Comment by vjeux** [comment]
Google drawings requires an account to start sharing. I guess what we could do is to make it loginless but if and only if you want to generate a shareable url, then you have to login.

I definitely don't want to put a login wall before being able to use excalidraw.

**Comment by woloski** [comment]
I think you can start with an anonymous scheme if you want to keep it lightweight. You want authenticated users to avoid abuse and provide other functionality, like “my diagrams”, “private diagrams”, permissions like gdocs (org wide, per user, etc). For all that you can use [Auth0](https://auth0.com) and can be invoked only when you want to share.

**Comment by vjeux** [comment]
Makes sense!

**Comment by gunar** [comment]
There's always https://jsonbox.io/ I guess…

**Comment by lipis** [comment]
You can now get a public shareable URL to your drawing, but it's just a copy.. any changes that happens in the original one won't be reflected.

**Comment by dwelle** [comment]
We should narrow this issue down. It mentions branching/forking and the ability to save to the same url (as I understand it). There's also a mention of auto-exporting a PNG to a public url.
