### ISSUE TITLE
Make crtl + z for undo

### ISSUE THREAD

**Issue by LetsXeri** [excalidraw/excalidraw#3541]
I mean that's important ^^

**Comment by dwelle** [comment]
`Ctrl + z` is already assigned to undo (on Windows). Is it not working for you?

**Comment by 532910** [comment]
It works for me on linux.

**Comment by LetsXeri** [comment]
Ah I see, when I'm alone it's working, but when I'm working together with outher users than nothing happens

**Comment by 532910** [comment]
It works for me even with multiple users.

**Comment by ad1992** [comment]
closing in favor of https://github.com/excalidraw/excalidraw/issues/3278
