### ISSUE TITLE
found missing/moved files in server log

### ISSUE THREAD

**Issue by thst71** [excalidraw/excalidraw#3570]
Hi! Thanks for creating excalidraw, we have given it a test run and are pleased!
 
Yet, while looking for the reason if we can do sth about the lag in coop mode (I see it is worked on it), I stumbled across these error messages in the docker log. 

We are running latest as suggested in the README.md

Does the latest docker build miss anything?

```
10.42.192.2 - - [12/May/2021:09:07:23 +0000] "GET /service-worker.js HTTP/1.1" 304 0 
│ 10.42.192.2 - - [12/May/2021:09:07:23 +0000] "GET /workbox/workbox-core.prod.js HTTP/1.1" 304 0 
│ 10.42.192.2 - - [12/May/2021:09:07:23 +0000] "GET /workbox/workbox-expiration.prod.js HTTP/1.1" 304 0 
│ 10.42.192.2 - - [12/May/2021:09:07:23 +0000] "GET /workbox/workbox-precaching.prod.js HTTP/1.1" 304 0 
│ 10.42.192.2 - - [12/May/2021:09:07:23 +0000] "GET /workbox/workbox-routing.prod.js HTTP/1.1" 304 0 
│ 10.42.192.2 - - [12/May/2021:09:07:23 +0000] "GET /workbox/workbox-strategies.prod.js HTTP/1.1" 304 0 
│ 10.42.192.2 - - [12/May/2021:09:07:23 +0000] "GET /workbox/workbox-sw.js HTTP/1.1" 304 0 
```

**Comment by dwelle** [comment]
Those requests seem to respond with 304 (Not Modified) so everything is fine?

**Comment by thst71** [comment]
Yes, at least it has nothing to do with performance issues in multiuser.
