### ISSUE TITLE
copy paste

### ISSUE THREAD

**Issue by TheKnarf** [excalidraw/excalidraw#359]
`cmd+c` and `cmd+v` does not seem to work as copy paste on Mac.

**Comment by GasimGasimzada** [comment]
Are you using Safari?

**Comment by TheKnarf** [comment]
Chrome on macOs

**Comment by TheKnarf** [comment]
And when I tested it today it started working, which was weird.

**Comment by dwelle** [comment]
I'm not surprised. The current copy/paste implementation is buggy because it uses system clipboard, which tends to fail on permissions.

**Comment by andrewmclagan** [comment]
Can we reopen this? Copy paste is also not working for me on OSX Chrome.

Chrome `Version 79.0.3945.117 (Official Build) (64-bit)`

OSX `10.14.6 Mojave`

**Comment by dwelle** [comment]
We need to do an overhaul of copy/paste. I'll open a new issue for this.

**Comment by GasimGasimzada** [comment]
Do you guys want to rewrite it? Or maybe use a clipboard polyfill?

**Comment by dwelle** [comment]
@GasimGasimzada check #386 for more info, and lemme know if you think those issues aren't substantial enough

**Comment by GasimGasimzada** [comment]
It makes sense now! A custom solution would be better then.
