### ISSUE TITLE
Disappearing connected arrow on drag

### ISSUE THREAD

**Issue by davidkpiano** [excalidraw/excalidraw#3598]
When connecting an arrow to two shapes and then dragging the target shape, the arrow mysteriously disappears:

https://user-images.githubusercontent.com/1093738/118711189-4bb1ae80-b7ed-11eb-8ebd-7a4ddf653215.mp4

**Comment by dwelle** [comment]
Hey David, if you still have the scene, can you just select the applicable elements, `cmd-c` and `cmd-v` here?

**Comment by davidkpiano** [comment]
{"type":"excalidraw/clipboard","elements":[{"type":"ellipse","version":334,"versionNonce":1214628250,"isDeleted":false,"id":"HWq4t_b26UP0V8z2V5rdv","fillStyle":"solid","strokeWidth":2,"strokeStyle":"solid","roughness":1,"opacity":100,"angle":0,"x":2899.6738281250023,"y":-881.3515625000013,"strokeColor":"#1864ab","backgroundColor":"transparent","width":62.68415178571422,"height":62.68415178571422,"seed":1749425021,"groupIds":[],"strokeSharpness":"sharp","boundElementIds":["eUOmVSWk0qBxWXRCpv-1S","8TzTlzb-g0VY-jDRUSASY","c1PdMFmyp3xt7wONNKKEr","akbqg5m5PtR1VUrwMq5M8","Q2eb1ueuanbEILTfXE9jY","abY72YmrSNSQhRkl9a_Qk"]},{"type":"ellipse","version":182,"versionNonce":965736538,"isDeleted":false,"id":"2rsTXhJbntt9TOk719tpU","fillStyle":"solid","strokeWidth":2,"strokeStyle":"solid","roughness":1,"opacity":100,"angle":0,"x":2880.4048549107165,"y":-1072.0825892857151,"strokeColor":"#d9480f","backgroundColor":"transparent","width":98.88392857142844,"height":113.56584821428578,"seed":1827181491,"groupIds":[],"strokeSharpness":"sharp","boundElementIds":["c1PdMFmyp3xt7wONNKKEr","akbqg5m5PtR1VUrwMq5M8","Q2eb1ueuanbEILTfXE9jY","abY72YmrSNSQhRkl9a_Qk"]},{"id":"abY72YmrSNSQhRkl9a_Qk","type":"arrow","x":2927.9690290178573,"y":-945.8619847751567,"width":0.27282955753207716,"height":56.456810492763566,"angle":0,"strokeColor":"#000000","backgroundColor":"transparent","fillStyle":"solid","strokeWidth":2,"strokeStyle":"solid","roughness":1,"opacity":100,"groupIds":[],"strokeSharpness":"round","seed":1745708698,"version":68,"versionNonce":1387472026,"isDeleted":false,"boundElementIds":null,"points":[[0,0],[-0.27282955753207716,56.456810492763566]],"lastCommittedPoint":null,"startBinding":{"elementId":"2rsTXhJbntt9TOk719tpU","focus":0.03797968397295142,"gap":12.686494025838485},"endBinding":{"elementId":"HWq4t_b26UP0V8z2V5rdv","focus":-0.11199145375240123,"gap":8.19323295575413},"startArrowhead":null,"endArrowhead":"arrow"}]}

**Comment by dwelle** [comment]
Thanks. It works for me on the elements you've suppled: can you still reproduce the bug on them on your end?

I dimly recall this happening before but can't remeber if it was fixed or not. /cc @xixixao

**Comment by xixixao** [comment]
Which browser and OS are you using?

**Comment by davidkpiano** [comment]
Chrome, latest, MacOS

**Comment by xixixao** [comment]
@davidkpiano Can you consistently reproduce this? Can you reproduce this from a blank scene?

If we can't repro we can't fix it.

**Comment by davidkpiano** [comment]
> @davidkpiano Can you consistently reproduce this? Can you reproduce this from a blank scene?
> 
> If we can't repro we can't fix it.

I cannot; must have been a Heisenbug. Feel free to close.
