### ISSUE TITLE
[TODO] Elements array should be a component variable, not a global one

### ISSUE THREAD

**Issue by AndreBastos23** [excalidraw/excalidraw#36]
Right now the elements array is a global variable. This works fine if we only have 1 file, but since we're going to get more and more files, we should move this inside the React scope, so components can re-render when necessary if this array changes.

My idea was to move this inside a useReducer hook, to make this elements available to all the children without having to pass then down using props.

What do you guys think?

I can also see a usage to create a useElements hook, where we have the information related to the elements there... All the elements, the selected elements, etc etc

**Comment by AndreBastos23** [comment]
@vjeux @dwelle @nanot1m @giovannigiordano What do you guys think about this?

**Comment by giovannigiordano** [comment]
@AndreBastos23 yeah. I think we should move elements to React state so the changes would be more predictable.

**Comment by vjeux** [comment]
Agreed! I started without react for the draw loop and then kindof added it but didn’t fully go with it. I think it makes a lot of sense

**Comment by AndreBastos23** [comment]
@vjeux dont know if you can help me, but could you explain to me what the drawScene function is supposed to do?

**Comment by vjeux** [comment]
It is basically the render() function but for the canvas. It takes all the elements and writes them on the canvas.

**Comment by GasimGasimzada** [comment]
I have removed all the dependencies from `elements` global variable from all the functions: https://github.com/excalidraw/excalidraw/pull/204. I am still creating `elements` in a global variable to keep it similar to previous version but now it can be easily moved to wherever necessary as long as "entry" functions are accepting proper elements array.
