### ISSUE TITLE
Clicking with no dragging creates shapes with zero width/height

### ISSUE THREAD

**Issue by gmertk** [excalidraw/excalidraw#360]
The title might sound weird. But the behavior is clearer in the screencast below.

We should either:
- not create any shapes if the dragging didn't start (Sketch's behavior)
- or create a shape with a larger default size (Google Slides' behavior).

![zero-size](https://user-images.githubusercontent.com/907281/72279687-94bc8600-362e-11ea-98d6-2b544aefa176.gif)

**Comment by vjeux** [comment]
Agreed!

**Comment by dwelle** [comment]
I'd also consider not creating (or removing if already created) when elements are resized below visibility threshold (though not sure how to determine that element isn't visible, or close to invisible).

Tiny invisible elements mess up export and users are left wondering why it exports beyond the visible shape.

**Comment by gmertk** [comment]
I’ll have a look and send a PR. I’m more inclined to implement the first option of not creating the element.

**Comment by giovannigiordano** [comment]
@gmertk can you open a PR for this?

**Comment by anil-sequoia** [comment]
@giovannigiordano : I am done with the fix. Can I raise the pull request, if you guys don't mind?

**Comment by simbathesailor** [comment]
Hey @giovannigiordano @gmertk  . I was to able to fix this issue.  I have raised the pull request !
@gmertk Could you please review it and I hope you don't mind it.
