### ISSUE TITLE
Howto link ("Follow our guides") 404s

### ISSUE THREAD

**Issue by getaaron** [excalidraw/excalidraw#3605]
## Reproduction Steps

1. Type `?`
2. Click **Follow our guides**, which points to `https://howto.excalidraw.com`

## Expected Behavior

I see a howto guide

## Actual Behavior

404

## Screenshots

<img width="744" alt="screenshot of follow our guides" src="https://user-images.githubusercontent.com/789577/118906157-d2948300-b8e2-11eb-80b1-43885a4f9196.png">

<img width="1011" alt="screenshot of 404 error" src="https://user-images.githubusercontent.com/789577/118906259-16878800-b8e3-11eb-810b-b0a2a3cf3854.png">

**Comment by h7y** [comment]
<img width="748" alt="Screenshot 2021-05-20 at 9 41 47 AM" src="https://user-images.githubusercontent.com/22396000/118917982-a19e6780-b94f-11eb-9393-8ec528dd673b.png">

I think you have an old version of Excalidraw. That link doesn't exist anymore.

**Comment by dwelle** [comment]
Yep. Try hard-refreshing (Ctrl-F5 on Windows, for Mac Safari/Chrome, see https://apple.stackexchange.com/a/325876).
