### ISSUE TITLE
Expose FontFamily from package and refactor fontFamily for better readability

### ISSUE THREAD

**Issue by ad1992** [excalidraw/excalidraw#3608]
Right now the [number](https://github.com/excalidraw/excalidraw/blob/f4e10c93e1760a2d6c687f9e95d1fc1b89989fb5/src/constants.ts#L65) corresponding to the font is stored in `currentItemFontFamily`, instead, we can start storing the font type `handDrawn, normal, code` which will be more clear and semantically correct as well. 

We could store font name as well but that would lead to unnecessary breaking changes if some font is updated later for consumers hence storing font type will be better.

**Comment by dwelle** [comment]
I would keep numbers:

- generic. When we support for custom fonts (e.g. in packages) those labels may not map to what the font looks like at all
- smaller output (when not compressing)

We can use an enum or something to make it semantic in our codebase instead?

**Comment by ad1992** [comment]
> generic. When we support for custom fonts (e.g. in packages) those labels may not map to what the font looks like at all

For custom fonts, the values will be different altogether afaiu (haven't thought of it yet).

> smaller output (when not compressing)
Yeah, that's right.

The reason I am not in favor of numbers is it makes it difficult to understand which font is for the current item unless someone checks the codebase, and for consumers also it will be a bit tricky since they need to check which number maps to which font and use accordingly unless documented in the right way (which can be avoided if the values are set right).

Also the variable name `currentItemFontFamily` is somewhat misleading as it's not a font family but an index.

> We can use an enum or something to make it semantic in our codebase instead?
we can try that, but in that case, we should update the state variable to `currentItemFontIndex`?
