### ISSUE TITLE
Duplication Glitch involving Undo

### ISSUE THREAD

**Issue by Mobuos** [excalidraw/excalidraw#3615]
Hello, I noticed something going wrong with excalidraw recently when you duplicate (Ctrl+D) objects. More specifically groups of objects after undoing a previous duplication. Let me explain:

How to reproduce:

1. Draw any two shapes
![image](https://user-images.githubusercontent.com/12601762/119240267-e0394b00-bb24-11eb-9931-685a2e90fecb.png)
2. Select both of them and group them (Ctrl+G)
![image](https://user-images.githubusercontent.com/12601762/119240293-0232cd80-bb25-11eb-8a34-6e2b3a9f5d44.png)
3. Duplicate the group (Ctrl+D)
![image](https://user-images.githubusercontent.com/12601762/119240300-0eb72600-bb25-11eb-8167-939c12adc6b8.png)
4. Undo (Ctrl+Z)
5. Duplicate a couple of times again now (Ctrl+D * 4+), and you should notice the problem...
![image](https://user-images.githubusercontent.com/12601762/119240317-2a223100-bb25-11eb-926d-b098ce94e3d8.png)
This quickly increases the amount of shapes on the screen, causing lag and other problems when trying to edit the shapes.
It's particularly bad because the original shapes will sometimes pop out of existence.
![image](https://user-images.githubusercontent.com/12601762/119240364-66559180-bb25-11eb-9bc2-42d3ce2e272e.png)

I have no clue how or why this happens. Just thought I would post this issue here after figuring the easiest way to reproduce it.
I couldn't find anyone mentioning this issue specifically, but sorry if this has already been addressed.

**Comment by dwelle** [comment]
Wow. What is going on here.

Thanks for the report and repro steps! I'll take a look tomorrow.
