### ISSUE TITLE
Exposing some more functions from excalidraw package?

### ISSUE THREAD

**Issue by dai-shi** [excalidraw/excalidraw#3634]
This is more like request for comments.

I've been developing an unofficial util [excalidraw-animate](https://github.com/dai-shi/excalidraw-animate), and now it's migrating to using the package. Previously, it was using git submodule to reuse some functions. PR 👉  https://github.com/dai-shi/excalidraw-animate/pull/16

Now, from my perspective, it would be nice if some functions are exposed from packages.

```
getFreeDrawSvgPath (too specific to my use case)
loadFromBlob
loadLibraryFromBlob
loadScene (too specific to my use case)
```

These are used outside React, so it's more for the former `@excalidraw/utils`.

cc @ad1992

**Comment by ad1992** [comment]
We can expose `getFreeDrawSvgPath`, `loadFromBlob` and `loadLibraryFromBlob` , but `loadScene` is specific to `excalidraw-app` as it imports from backend hence that would need to be implemented in consumer.
cc @dwelle

**Comment by dwelle** [comment]
> We can expose `getFreeDrawSvgPath`, `loadFromBlob` and `loadLibraryFromBlob` , but `loadScene` is specific to `excalidraw-app` as it imports from backend hence that would need to be implemented in consumer.

Yes
