### ISSUE TITLE
Base URL Config

### ISSUE THREAD

**Issue by rafaeluriarte** [excalidraw/excalidraw#3637]
I am running excalidraw under an alias ( https://example.com/exalidraw ). However, when I use it, the requests are made without the alias (for instance, https://example.com/static/js/1.d708ec08.chunk.js - 404).  Is there a place where I can configure the base URL to add this alias? 

Thank you

**Comment by vincentfretin** [comment]
I struggled with the exact same thing this morning! I got it working with the following changes.

In `public/index.html`
replace
```
window.EXCALIDRAW_ASSET_PATH = "/";
```
by
```
 window.EXCALIDRAW_ASSET_PATH = "/excalidraw/";
```

In `src/service-worker.js`
replace
```
importScripts("/workbox/workbox-sw.js");

workbox.setConfig({
  modulePathPrefix: "/workbox/",
});
```

by
```
importScripts("/excalidraw/workbox/workbox-sw.js");

workbox.setConfig({
  modulePathPrefix: "/excalidraw/workbox/",
});
```

**Comment by rafaeluriarte** [comment]
Thank you very much, it works and saved us a lot of troubles!
