### ISSUE TITLE
Save-to-current-file UI

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#3650]
The current solution of showing the save-icon next to darkMode when fileHandle is active is only temporary:

![image](https://user-images.githubusercontent.com/5153846/119819389-9cfa2600-bef0-11eb-8787-82f9ad027978.png)

The idea is to reimplement part of @j-f1's proposal (https://github.com/excalidraw/excalidraw/pull/3381) to display active filename + save icon somewhere in the UI:

https://excalidraw.com/#json=5822182374506496,fu593dJLqIKnA22ochvbeg

### Option (A)

![image](https://user-images.githubusercontent.com/5153846/119819967-46d9b280-bef1-11eb-9d3d-2edf11387fd2.png)

### Option (B)

![image](https://user-images.githubusercontent.com/5153846/119819998-4fca8400-bef1-11eb-9fe9-9c7745a04c09.png)

**Comment by h7y** [comment]
Personally I prefer Option (B) since it doesn't block more canvas.

**Comment by ad1992** [comment]
I would go with option b, All canvas actions at one place :)

**Comment by dwelle** [comment]
We can try (b) then.

My idea is the UI should contain the active filename, non-editable, ellipsified in case it's too long. Next to it should be a save button. Potentially we can also display an `x` button to destroy the fileHandle, but maybe let's start without it. Thoughts?

**Comment by ad1992** [comment]
Yeah sounds good, we can start with out "x" button

**Comment by h7y** [comment]
I'll take this up?

**Comment by ad1992** [comment]
Sure 👍🏻
