### ISSUE TITLE
Shape Strategy (△, ⬡, +)

### ISSUE THREAD

**Issue by felixakiragreen** [excalidraw/excalidraw#366]
_I think we agree that much of what makes excalidraw so great is its simplicity. And we don't want to just add every little thing because eventually the simplicity will be lost._

<img width="591" alt="Screen Shot 2020-01-13 at 16 03 13" src="https://user-images.githubusercontent.com/1843672/72291851-37b8d400-361e-11ea-8ce5-e4f9a15f7574.png">

I'd like to start the conversation on discussing the approach for adding more shapes. I've tried to read through all the existing issues that mention these and I've noticed some patterns.

### Lines (& multi-point lines)

https://github.com/excalidraw/excalidraw/issues/24
(Multi-point lines allow for drawing complex shapes we don't want to have presets for. Perhaps bezier curves could be toggled on/off)

https://github.com/excalidraw/excalidraw/issues/218
https://github.com/excalidraw/excalidraw/issues/344

### Basic Shapes & Polygons

https://github.com/excalidraw/excalidraw/issues/244

@vjeux has indicated being open to the idea of adding more shapes (that have additional settings).

Personally I would add primitives for triangles (options for △, ▹, ◸, rotate?), hexagons (⬡,⎔), and then maybe octagons or polygon(n sides)?

But I understand that not everyone shares my passion for hexagons, so some may think that it shouldn't be a primitive. Or there might be another shape more people would use as a primitive not included in my list.

I would be happy to submit a PR for adding hexagons as a shape, but I would prefer to validate that this is a feature people would like to use.

**Comment by dwelle** [comment]
> But I understand that not everyone shares my passion for hexagons

:sweat_smile:

**Comment by GrimTheReaper** [comment]
I personally would group Hexagons with Polygons, or add a shape that you can specify how many sides it has since there might be a need for both symmetrical polygons and asymmetrical polygons.

**Comment by vjeux** [comment]
I'm not opposed to have the ability to chose the number of sides when drawing a diamond (after the fact). Then you can copy paste if you want the same shape multiple times.

I don't think we should have a bunch of different shapes at the top though.

What would be good as well is to get proper multi-point drawing so that you can draw whatever shape you want and copy paste it for your needs.

**Comment by vjeux** [comment]
We could also keep the number of sides an inherited setting like stroke/bg color and change the icon to have more sides if you change it on one.

**Comment by dwelle** [comment]
Keep in mind that these new shapes will likely open a new can of worms for bounding boxes, resize handles, hitbox detection, bg painting (especially when we allow users to draw arbitrary shapes) etc. But these issues (albeit not as dramatic) will also arise after rotation support (#15).

**Comment by rachelnabors** [comment]
I wonder... what about copy-pasta-ing SVG from another program? That would let folks use logos and other complex shapes without having to recreate Adove Illustrator.

**Comment by dwelle** [comment]
We'd probably need to create our own parser/converter, and it'd be lossy since we only support a subset of what SVG does. It's a nice thought, though :).

**Comment by felixakiragreen** [comment]
What do you all think about a "Complex Polygon" shape, that implements SVG's polygon? The user could add, move, & remove points. Currently though the user doesn't interact with points; only bounds. So there would need to be work around that first.

**Comment by lipis** [comment]
I would love that.. We just need to think something smart about the design.. we don't want to overload it with more buttons.. some sort of handle on the polygon should do the trick by moving it around.

**Comment by jackdbd** [comment]
Inkscape has a "Stars and Polygons" button that—once clicked—displays this interface.

![inkscape-stars-and-polygons](https://user-images.githubusercontent.com/5048090/95788282-85f92180-0cdb-11eb-8b77-b708e136da49.png)

**Comment by lipis** [comment]
Not exactly what was asked for, but very close to it: https://twitter.com/excalidraw/status/1324858643074965505

**Comment by lipis** [comment]
https://excalidraw.github.io/excalidraw-libs/ :D

**Comment by lipis** [comment]
We already support multi point lines to be connected and any shape is possible. But adding native support for multiple polygons is out of scope, as it will affect how the binding works, adding new controls, supporting more shapes, etc. We still love hexagons as much as you do :D

**Comment by sugoidesune** [comment]
@lipis 
So triangles with round corners are out of scope 🥲
