### ISSUE TITLE
Every element must have unique id

### ISSUE THREAD

**Issue by gaearon** [excalidraw/excalidraw#3683]
Noticed this in the standalone component:

<img width="614" alt="Screenshot 2021-05-30 at 23 21 45" src="https://user-images.githubusercontent.com/810438/120121891-ddca9700-c19d-11eb-8750-3e66a6dbcf66.png">

This means you can't render two of them without id clashes.

**Comment by ad1992** [comment]
There are few places like the above one where we are using it for accessibility with `aria-labelledby`, to make it unique we can append the excalidraw id.
