### ISSUE TITLE
Use CMD modifier when dragging to unbind arrows from an element

### ISSUE THREAD

**Issue by wietsevenema** [excalidraw/excalidraw#3689]
Right now, you can press CMD to prevent arrows from binding. However, there is no symmetrical action to unbind an element that has arrows bound to it. 

## Current behaviour
If you try to move an element with arrows bound to it, this is what I do now: 

1. Start to drag the element and realize there are arrows bound to it. 
2. Release the element
3. CMD+Z until everything is in the right place. 
4. Select the element
5. Cut the element and paste it again. It is now free to drag
6. Adjust the element position 
7. (Optionally, move element backwards to fix overlaps)

## Proposed behaviour
I would like to use CMD when I start dragging to release all the arrow binding: 

1. Start to drag the element and realize there are arrows bound to it. 
2. Press and hold CMD (arrows unbind)
3. Adjust the element position

**Comment by dwelle** [comment]
The binding UX issues are long overdue. Your proposal is sound — and it seems I've already proposed it once here https://github.com/excalidraw/excalidraw/issues/2106 so I'm gonna close this as a duplicate.

I've also made a proposal a while back that would allow you to disable binding for selected shapes and/or all future shapes. You've likely seen it in the PR, but I've made it into an issue and tweaked it a bit if you wanna give your thoughts: https://github.com/excalidraw/excalidraw/issues/3690
