### ISSUE TITLE
Allow to disable arrow binding for selected/future shapes

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#3690]
(copied from https://github.com/excalidraw/excalidraw/pull/2146#issuecomment-739240175)

### Proposal A

Introduce an element-specific property `bindingEnabled: boolean` (accessible from element property menu), either for all linear elements, or just arrows (as is currently).

By default, new shapes would inherit it from `currentBindingEnabled` appState prop (same as we do with other shape properties), so it'd be easy to both disable/enable the behavior for all future shapes (so users who don't like auto-binding would simply disable it once for a scene, while still being able to enable this for a few specific elements on the scene as needed). The default would not change from current, so there would be no breaking change.

Bindable elements (non-linear elements) would keep auto-binding only to linear elements which have `bindingEnabled` set to `true`.

Apart from the benefits described above, I can see we could add binding support for lines as well, since it would not be as problematic as it is currently.

### Proposal B

Same as above, but also enable the same prop for non-linear elements such as rectangles, which would exclude these shapes from being bindable to arrow elements even if they were bind-enabled.

**Comment by griimick** [comment]
I generally face issues with arrows which i think is being solved by Proposal A. Proposal B is also a good addition to have and I think can be extended once Proposal A is implemented.
