### ISSUE TITLE
Brave Browser issues opening files

### ISSUE THREAD

**Issue by xzab** [excalidraw/excalidraw#3694]
Seems like quite often I cannot open files I've saved locally in excalidraw when using Brave.  Shields are off, and all plugins disabled.  The only error I see in the console is:

`Error with Feature-Policy header: Unrecognized feature: '*'.`

Sometimes after completely shutting down brave and then reopening it'll work and open the files.  I've even tried hard reload + empty cache without success.  When I try to open the same files using chrome, they seem to open fine.  Mac, Brave & Chrome latest.

**Comment by dwelle** [comment]
Cannot reproduce on `Brave 1.25.68 Chromium: 91.0.4472.77`. What's your version?

```
brave://version/
```

Judging from you saying it works intermittently, I won't ask for Excalidraw version nor the JSON file as it's likely irrelevant. Do you have any extensions? If so, try in incognito mode.

But yes, since it works everywhere else it's likely related to some Brave anti-fingerprinting or other related privacy thing.

**Comment by xzab** [comment]
Now it's happening 100% of the time.  I can't get it to open any files.  Updated to latest brave:



Brave | 1.25.73 Chromium: 91.0.4472.106 (Official Build) (x86_64)
-- | --
Revision | 574f7b38e4e7244c92c4675e902e8f8e3d299ea7-refs/branch-heads/4472@{#1477}
OS | macOS Version 10.14.6 (Build 18G9216)
JavaScript | V8 9.1.269.36
User Agent | Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.106 Safari/537.36


Also, here's a screenshot of the console errors.
![Screen Shot 2021-06-24 at 1 13 12 PM](https://user-images.githubusercontent.com/1554568/123326708-69f68280-d4ee-11eb-83a8-f54ea8b06b21.png)

**Comment by dwelle** [comment]
I'm pretty certain it's related to a bug in browser-fs-access (see https://github.com/GoogleChromeLabs/browser-fs-access/issues/53). In the meantime, you can use drag-and-drop as a workaround to import files.

**Comment by xzab** [comment]
I wish I knew about drag & drop for the last 2 months 🤦 
Thank you!!

**Comment by dwelle** [comment]
Yeah, there are many hidden gems in Excalidraw that most people don't know about! We'll try make them more discoverable through various means.
