### ISSUE TITLE
new language: kk

### ISSUE THREAD

**Issue by alanapapa** [excalidraw/excalidraw#3719]
Please add a Kazakh language thread to Crowdin. kk-kz

**Comment by dwelle** [comment]
Hello. Here you go: https://crowdin.com/translate/excalidraw/10/en-kk ❤️

How do you say Kazakh in Kazakh, for the language picker?

**Comment by alanapapa** [comment]
> Hello. Here you go: https://crowdin.com/translate/excalidraw/10/en-kk ❤️
> 
> How do you say Kazakh in Kazakh, for the language picker?

Cool! Thank you! You can just write "Қазақ тілі"

**Comment by dwelle** [comment]
Thanks, you check the progress here: https://github.com/excalidraw/excalidraw/pull/3718 — we'll be making the next release within the next few days.
