### ISSUE TITLE
Excalidraw not load in shared Notion page

### ISSUE THREAD

**Issue by ArthurKing99** [excalidraw/excalidraw#3735]
I am using Notion together with Excalidraw. So, I will have my work done on Excalidraw and then I embed the link from Excalidraw on Notion and it works fine. But when I try to share the Notion page through view-only link, the canvas that embeded does not load and I need to change the link access to (can-edit) and then click the view original option to load the canvas on Excalidraw itself. This can be quite inconvenient when I share my Notion page to others.

Here are some images:
1. This is what I see in my notion workspace
![image](https://user-images.githubusercontent.com/63594782/121836033-3d2fb780-cd05-11eb-9a70-3daac4c2e67a.png)
2. This is what people see when they use my notion page link
![image](https://user-images.githubusercontent.com/63594782/121836097-63edee00-cd05-11eb-8493-b93d782f711c.png)

Thank you.

**Comment by ad1992** [comment]
@ArthurKing99 probably when you are sharing the notion link, the data from the excalidraw link is not passed to excalidraw hence it's showing empty. As long as the `initialData` is passed to the Excalidraw component it will show the data.

**Comment by ad1992** [comment]
closing this as its related to `notion` integration and needs to be fixed in `notion`
