### ISSUE TITLE
Question, how to make a standalone excalidraw

### ISSUE THREAD

**Issue by bric3** [excalidraw/excalidraw#3737]
Disclaimer: I am not a JS or CSS developer, I have a bare understanding of React framework, or build tools like yarn.

What I'd like is the ability to open a local _index.html_ with Excalidraw (an offline version). But I have some difficulty to piece things together. The context of this is to load excalidraw in a Chrominium Embedded frame ([JCEF](https://bitbucket.org/chromiumembedded/java-cef/src/master/)) for an IntelliJ plugin.

I wanted to test what is described here : https://www.npmjs.com/package/@excalidraw/excalidraw#in-browser

```html
<script
  type="text/javascript"
  src="https://unpkg.com/@excalidraw/excalidraw@0.8.0/dist/excalidraw.development.js"
></script>
```

This is likely wrong, as nothing happens.

I can probably use whatever is built from the yarn directive in the dockerfile:

https://github.com/excalidraw/excalidraw/blob/6dee02e32062057cb5b18702f0b5fe1a3ef571fd/Dockerfile#L15

But isn't there a better / simpler alternative ? A prebuilt lib like the one on unpkg ?

Thnaks in advance

**Comment by bric3** [comment]
And many thanks for excalidraw it's awesome

**Comment by bric3** [comment]
Ok I think I lacked react and node related stuff knowledge a lot.

still I think the project’s documentation and example could be improved to be more precise, typically the package’s readme lithe code listing could add file paths and stress out that going in the code sandbox is critical to understand what should be done to get something working.

**Comment by dwelle** [comment]
Hey @bric3.

What did the problem you were facing turn out to be, so that we can improve our documentation? Also, feel free to open a PR or make suggestions on what we should improve.

Thanks! ❤️

**Comment by bric3** [comment]
@dwelle Hi,

Please keep in mind I'm not a frontend developers, so I probably lack many reflexes.

1. The first thing I looked at was to be able to make a simple `index.html` that load the necessary JS (and any other necessary) assets from a standard.

    And for that I went to the [repo's Readme][1], however this readme doesn't point to the documentation that I should use (as a consumer of the library). In fact I searched the Web and found the npmjs page mentioned above. Only to find a tad later it was available here in the [`src/packages/excalidraw`][2].

2. Then in this readme, I believed I found what I was looking for in just the following snippet (in-browser section).

    ```
    <script
      type="text/javascript"
      src="https://unpkg.com/@excalidraw/excalidraw@0.8.0/dist/excalidraw.development.js"
    ></script>
    ```

    However it doesn't work that way. It's true this section mentions _react_ and _react-dom_, yet this didn't kicked in immediately in my head. I believe this section should be rewritten with the `index.html` as the first snippet, and then eventually hidden `details` section with the `index.js` and finally the mention about production or development JS urls.

    One thing that confused me in the [codesandbox example][3] is the presence of `package.json`, and that led me to believe I needed tools that I didn't understand well at this point (`node`, `npm`, `yarn`, ...).

   So I think this example may need some more explanation.

After some iteration I finally got it working ...as part of a yarn lifecycle, this might have been avoided, but I went through this path. And then as searched over internet some examples were using the real react App approach.

3. So I tried to upgrade my simple HTML page to use react, however I didn't immediately caught that the section [_Web Bundler_, _Webpack_][4] was actually the right section as I already had been using `yarn` and `react-scripts`. Especially since the full example is collapsed (as well as the [codesandbox][5] link).

    I had issues to migrate the in browser code to actual web bundler code. Typically I didn't expect the `App` function to be rewritten (from `React.createElement` style to `<Excalidraw` style), maybe that's expected with react, but for me, a novice, it was a surprise.

    Also when looking at the [codesandbox][5], I noticed that I still wonder about
    * There's a `window.EXCALIDRAW_ASSET_PATH = "/";` in the `public/index.html` that I am not sure if I should use it in my app.
    * There's the `public/excalidraw-assests-dev` with fonts, and other stuff, that I am not sure if I need those, and I don't know how to grab them easily. 

At this stage I have a working minimal React app with excalidraw. But I still wonder if my setup is correct.


[1]: https://github.com/excalidraw/excalidraw/tree/master/README.md
[2]: https://github.com/excalidraw/excalidraw/tree/master/src/packages/excalidraw
[3]: https://codesandbox.io/s/excalidraw-in-browser-tlqom?fontsize=14&hidenavigation=1&theme=dark
[4]: https://github.com/excalidraw/excalidraw/tree/master/src/packages/excalidraw#using-web-bundler
[5]: https://codesandbox.io/s/excalidraw-ehlz3?fontsize=14&hidenavigation=1&theme=dark

**Comment by bric3** [comment]
Thank you @ad1992 for the feedback !

> Unfortunately github markdown we can't control the size of dropdown, we might move the examples to a different folder altogether so full example is at one place.

Maybe moving the link to the codesandbox outside the `<details>` element could help.

> Yeah in the browser we are just using React API in vanilla js and not JSX syntax hence it looks different. We can use jsx in browser with babel plugin but it will become slow and not suitable for production.

Actually this a very interesting aspects, I think it's work mentioning, I say that as a novice, but I think it's useful to explain the difference.

> Not sure if you went through the Installation section, but I will explain here.

Yes I did, but you explained this part better ! Actually since it's an IntelliJ plugin I need to download the assets to make them available "locally".

Actually I have one left question: What is the best option to access these assets? I just inspected the unpkg link
https://unpkg.com/browse/@excalidraw/excalidraw@0.8.0/dist/excalidraw-assets/, and noticed the same structure in `node_module/@excalidraw/excalidraw/dist`. Should I just copy these files manually to my specific destination dir ?
Or is there a `package.json` trick to copy them where needed ?

**Comment by ad1992** [comment]
> Actually I have one left question: What is the best option to access these assets? I just inspected the unpkg link

As mentioned above by default it will work out of the box and get served from `unpkg` so you need not make any changes at all unless you want to host it yourself. 

If you want to host it yourself then you have to move the folder `excalidraw-assets` and `excalidraw-assets-dev` to the path (basically your CDN path ) where your assets are served.

**Comment by bric3** [comment]
OK, thank you @ad1992 !

I've got another question is there a public API or a way to load a scene from an image file (SVG or png). The IDE infrastructure have it's own file infrastructure, which means I cannot use Excalidraw relying on the browser filesystem api. The documentation only points to API that accepts elements to load a scene. I've found this code.

* https://github.com/excalidraw/excalidraw/blob/5c73c5813ce92d3c7b0610530f78ccb06a47d983/src/data/blob.ts#L82-L113
* https://github.com/excalidraw/excalidraw/blob/5c73c5813ce92d3c7b0610530f78ccb06a47d983/src/data/image.ts#L106-L136

It's easy to re-implement, but this might be out of sync.

----

So I would like to use `loadFromBlob`, at this time hacking around didn't work.

Hacky that doesn't work :

```
import Excalidraw, {
    exportToSvg,
    exportToBlob,
    getSceneVersion,
    loadFromBlob,
} from "@excalidraw/excalidraw";
```

```
export default function App() {
    const excalidrawRef = React.useRef(null);

    window.loadBlob = (blob) => {
        return loadFromBlob(
            blob,
            excalidrawRef.current.getAppState());
    };

    window.exportAsSVG = (exportParams) => {
        return exportToSvg({
            elements: excalidrawRef.current.getSceneElements(),
            appState: {
                ...excalidrawRef.current.getAppState(),
                ...exportParams
            },
        });
    };

```

Export as SVG works fine, but with `loadBlob` I'm encountering a `Uncaught TypeError: Object(...) is not a function`. I somewhat expected an error since this function do not appear public or exported.

**Comment by ad1992** [comment]
@bric3 the API doesn't expose `loadFromBlob` hence you are getting the above error. We don't support [Importing images](https://github.com/excalidraw/excalidraw/issues/19) yet.

But we do embed scene data if "Embed scene" is checked as shown below (this will increase your export file size)
<img width="774" alt="Screenshot 2021-06-18 at 7 59 52 PM" src="https://user-images.githubusercontent.com/11256141/122576830-c2053300-d06f-11eb-92a2-b1321b551943.png">

We will be exposing `loadFromBlob` as well very soon, there is a similar request [here](https://github.com/excalidraw/excalidraw/issues/3634) as well post which you will be able to use it.

**Comment by bric3** [comment]
Cool thanks a lot.

**Comment by bric3** [comment]
@ad1992 Hello again, I have a question again on this scene embedding. I'd like to do that programmatically, However I can't seem to get excalidraw embed the scene when calling `exportToSvg`

```
import React from "react";
import Excalidraw, {
    exportToBlob,
    exportToSvg,
    getSceneVersion,
    serializeAsJSON,
} from "@excalidraw/excalidraw";

// placeholder for functions
window.saveAsSvg = null;


...

export default function App() {
    const excalidrawRef = React.useRef(null);

    ...

    window.saveAsSvg = (exportParams) => {
        return exportToSvg({
            elements: excalidrawRef.current.getSceneElements(),
            appState: {
                ...excalidrawRef.current.getAppState(),
                ...exportParams
            },
        });
    };

    return (
        <div className="excalidraw-wrapper">
            <Excalidraw
                ref={excalidrawRef}
                initialData={{ appState: {
                        exportEmbedScene: true
                    }
                }}
                ...
            />
        </div>
    );
}
```

I also tried to pass the `exportEmbedScene` to the `exportToSvg` directly (as part of the `appState`). But this doesn't seem to work. The scene never gets embedded. Looking at the code 

https://github.com/excalidraw/excalidraw/blob/5cd921549a7e2b67219ee3f10d98228e23103c0f/src/scene/export.ts#L68-L134

I believe `exportToSvg` cannot embed the scene. It's likely the same for the png / jpg exports. Is it expected ?

**Comment by ad1992** [comment]
> @ad1992 Hello again, I have a question again on this scene embedding. I'd like to do that programmatically, However I can't seem to get excalidraw embed the scene when calling exportToSvg

@bric3 do you mind asking this and #3752 as a QnA in https://github.com/excalidraw/excalidraw/discussions/categories/q-a ? We are gradually moving to [discussions](https://github.com/excalidraw/excalidraw/discussions) for any queries related to excalidraw npm package so that everything is well documented at one place and it will be helpful for future users as well.

**Comment by bric3** [comment]
Not at all. Thx for the pointer ! @ad1992

**Comment by bric3** [comment]
Done, question is asked here https://github.com/excalidraw/excalidraw/discussions/3756
