### ISSUE TITLE
Reset selection when viewModeEnabled becomes true

### ISSUE THREAD

**Issue by gaearon** [excalidraw/excalidraw#3739]
I have a button that turns on `viewModeEnabled`.

Unfortunately that gets the selection stuck:

<img width="517" alt="Screenshot 2021-06-16 at 03 34 33" src="https://user-images.githubusercontent.com/810438/122149354-d7057a80-ce53-11eb-8897-ff52ac33511e.png">

When `viewModeEnabled` changes, selection should be cleared.

**Comment by dwelle** [comment]
Thanks for the report. Now fixed, but will take a while until it lands in a stable release. Meanwhile, you can use [@excalidraw/excalidraw-next](https://www.npmjs.com/package/@excalidraw/excalidraw-next/v/0.8.0-5cd9215).
