### ISSUE TITLE
Unable to load file stored from very same firefox browser

### ISSUE THREAD

**Issue by teramawi** [excalidraw/excalidraw#3740]
Hi there,

I'm unable to load an Excalidraw file in Firefox that i just saved to disk using that browser.

* Loading the same file saved from Firefox in Chrome does work.
* Loading a file saved from Chrome in my Firefox does **not** work
** it also does not work when saving the scene as image with embedded data 
* I am able to copy paste parts of a scene from Chrome to Firefox and from Firefox to Chrome
* There are no errors recorded in the browsers console
* clearing the browser cache did not resolve the issue
* using private mode did not resolve the issue in firefox as well

## Environment

Firefox Version: 78.11.0esr (32-Bit)
Chrome Version:  91.0.4472.101 (Offizieller Build) (32-Bit)

## Reproduction

1. Create any scene in Firefox Version.
2. Save to .excalidraw file
2.1 (optional) clear canvas
3. Load from .excalidraw file

## Example

I attached the files I saved to disk, in case it helps to investigate the issue.
[excalidraw exports.zip](https://github.com/excalidraw/excalidraw/files/6662540/excalidraw.exports.zip)
As uploading .excalidraw files was not allowed i had to put them into a zip file.

Addition: Both files are from the same canvas as I used live collaboration to get the same data in both browsers.

## Further info

It would be very nice if you were able to resolve this issue, as i do not have the knowledge to do so. If i can help by providing more information, please let me know.

Meanwhile I'll be able to use Chrome as a workaround.

Greetings

**Comment by dwelle** [comment]
Both files work for me on FF 78.11.0esr.

Can you report your excalidraw version? Righ-click on canvas → stats for nerds → version (you can click-to-copy).

**Comment by teramawi** [comment]
Both Browsers are using the same Version noted below:

Firefox: 2021-06-13T15:56:55Z-6dee02e
Chrome: 2021-06-13T15:56:55Z-6dee02e

**Comment by dwelle** [comment]
That's the latest version.

I believe the issue is identical to this: https://github.com/excalidraw/excalidraw/issues/3513, and I have been unable to identify the cause as I cannot reproduce.

That said, what I could reproduce is the inability to import from image, but on Chrome. It seems to have been related to how we dynamically import the code to decode/encode the PNGs, and it resolved upon refresh (I may have been on an older version). But you're most likely seeing something different.

**Comment by teramawi** [comment]
I'll see if i can somehow get some more information from stepping through the code tomorrow using https://github.com/excalidraw/excalidraw/#local-installation

**Comment by dwelle** [comment]
That would be very appreciated. Lemme know if you need any help.

I'd probably start with debugging `loadFromJSON` function. In particular whether `fileOpen` call resolves to a proper `blob`, and whether `loadFromBlob` resolves to JSON data.

https://github.com/excalidraw/excalidraw/blob/5cd921549a7e2b67219ee3f10d98228e23103c0f/src/data/json.ts#L52-L68

**Comment by teramawi** [comment]
Wow, first time debugging Typescript sure is a hell of a ride.
I'm not really sure what I've found exactly, but here's my short list :

* When opening a file there is a caught `AbortError: The user aborted a request.` after selecting a file in the file dialog: https://github.com/excalidraw/excalidraw/blob/5cd921549a7e2b67219ee3f10d98228e23103c0f/src/data/json.ts#L53
* In Firefox the fallback implementation of "browser-fs-access" is used instead of the native implementation as in chrome. If you want you can check for your browser whats happening https://browser-fs-access.glitch.me/
* As I tried stepping through it several times there was one out of ten that somehow led to a succcessful file load. Sadly I have no clue how this happened.

Maybe you can check if there is something to my observations that deviates from yours. Or do you have another idea?

**Comment by dwelle** [comment]
Ok, the `AbortError: The user aborted a request` is all I needed to know :), since it was my suspicion https://github.com/excalidraw/excalidraw/issues/3513#issuecomment-828314914.

I've raised the issue upstream: https://github.com/GoogleChromeLabs/browser-fs-access/issues/53 — we may need your help in confirming it fixed, later.

Thanks for you help so far.

**Comment by teramawi** [comment]
> Ok, the `AbortError: The user aborted a request` is all I needed to know :), since it was my suspicion [#3513 (comment)](https://github.com/excalidraw/excalidraw/issues/3513#issuecomment-828314914).
> 
> I've raised the issue upstream: [GoogleChromeLabs/browser-fs-access#53](https://github.com/GoogleChromeLabs/browser-fs-access/issues/53) — we may need your help in confirming it fixed, later.
> 
> Thanks for you help so far.

Glad to hear I could help and thank you for your fast und helpful response. I've got notifications active so just drop a comment when testing is needed.

> (Btw, as an interim workaround, you can drag & drop the files onto the canvas instead of using the button.)

Works like a charm 👍  thanks

**Comment by tomayac** [comment]
For the original poster, could you please see this [comment](https://github.com/GoogleChromeLabs/browser-fs-access/issues/53#issuecomment-863830427) and help test it? Thanks!

**Comment by bric3** [comment]
Hi,
I have the same issue on excalidraw.com with Firefox (89.0.2) and Safari (14.1.1 (15611.2.7.1.6, 15611), when loading an SVG file having an embedded scene.

Drag and dropping the SVG file in the Safari or Firefox canvas work.
Loading the SVG file in chrome does work though.

Excalidraw.com version : 2021-06-28T20:43:49Z-2d279cb
macOs Catalina 10.15.7 (19H1217)

**Comment by dwelle** [comment]
@bric3 can you check if it works here? https://excalidraw-git-fixfscancelation-excalidraw.vercel.app/

**Comment by bric3** [comment]
@dwelle Hi, Yes this fixed the issue on Firefox, however this didn't work for Safari.

**Comment by dwelle** [comment]
I've updated the version to log any potential errors if you can check the console: https://excalidraw-gzurmwb90-excalidraw.vercel.app/

Also, what are exact the steps to reproduce? I'm Safari 14.0.2 and cannot.

1. are you using a mouse or touchpad?
2. are you double-clicking the file in the file picker or selecting and clicking the `choose for upload` button?

**Comment by teramawi** [comment]
> @bric3 can you check if it works here? https://excalidraw-git-fixfscancelation-excalidraw.vercel.app/

> I've updated the version to log any potential errors if you can check the console: https://excalidraw-gzurmwb90-excalidraw.vercel.app/

@dwelle I just checked as well and can confirm that I'm able to successfully open files from disk on both links you provided.

**Comment by dwelle** [comment]
Thanks for follow up!
