### ISSUE TITLE
footer UI incorrectly centered in viewMode

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#3742]
![image](https://user-images.githubusercontent.com/5153846/122221635-bff57580-ceb1-11eb-9b8b-e0c32f416eab.png)

**Comment by UdattaChowdhury** [comment]
Hey @dwelle!! I would like to work on this issue. I am a beginner so can you help me this in the codebase.

**Comment by dwelle** [comment]
Sure @UdattaChowdhury.

It seems the cause is coming from:

https://github.com/excalidraw/excalidraw/blob/5cd921549a7e2b67219ee3f10d98228e23103c0f/src/css/styles.scss#L517-L522

I think it should be applied only to the top menu, while right now it's applied to both the top and the bottom.

**Comment by mrkldshv** [comment]
I tried to reproduce it and it seems not to be the case anymore. I guess we can close it after confirming that it doesn't appear.

**Comment by dwelle** [comment]
It seems to have been fixed in https://github.com/excalidraw/excalidraw/pull/3832. Closing, thanks!
