### ISSUE TITLE
Editing text unbinds attached arrows

### ISSUE THREAD

**Issue by jeffpeterson** [excalidraw/excalidraw#3744]
Editing the content of a text shape causes any attached arrows to become unbound.

**Comment by dwelle** [comment]
To be more specific, it happens after the editor is confirmed. During editing it works.

The `id` of the text seems stable, so it must be something else.

**Comment by connor-pph** [comment]
Hi @dwelle – first time open source contributor here – apologize in advance for noob-y mistakes.

I looked into this a bit and found that removing an else statement in the handleText function in App.tsx seems to fix it – pull request with that change – #3754. Spent some time manually testing and couldn't think of anything that would break by removing that piece, but I obviously don't know the codebase well. I'm also not sure how to build a test for this – would appreciate any insights there.
