### ISSUE TITLE
select word change the font color but it actually changed the whole text(object)

### ISSUE THREAD

**Issue by jinrunheng** [excalidraw/excalidraw#3759]
hi,

as you see

![image](https://user-images.githubusercontent.com/48077575/122951085-9788e200-d3af-11eb-9925-ad6c1de075c6.png)

when I select the word "hello" ,and I want change the word to this color
![image](https://user-images.githubusercontent.com/48077575/122951780-20078280-d3b0-11eb-9142-76059d3d11a5.png)

I click,then

![image](https://user-images.githubusercontent.com/48077575/122952066-5a711f80-d3b0-11eb-9f7a-c5589e719119.png)

Whole text is changed

The correct result would be to only change the text that  I selected

**Comment by dwelle** [comment]
Hello. Yes, that's a limitation of our text editor and the renderer. There's an open request for this over here https://github.com/excalidraw/excalidraw/issues/1126

In the meantime, the workaround is to create separate text elements for each.

**Comment by jinrunheng** [comment]
Thank for your reply
