### ISSUE TITLE
Content Security Policy for https://unpkg.com/@excalidraw-assets/

### ISSUE THREAD

**Issue by adandekar-sfdc** [excalidraw/excalidraw#3763]
I am trying out a Live Quip app: https://quip.com/dev/liveapps/1.x.x/guide/get-started/

which uses `create-quip-app` similar to `create-react-app`. I installed Excalidraw using npm but after I started the server it throws the following errors

```
Refused to load the script 'https://unpkg.com/@excalidraw/excalidraw@0.8.0/dist/excalidraw-assets/vendor-5678a46e9c49ae846a9e.js' because it violates the following Content Security Policy directive: "script-src https://quip-cdn.com 'self'". Note that 'script-src-elem' was not explicitly set, so 'script-src' is used as a fallback.
```

![image](https://user-images.githubusercontent.com/58186826/123339793-155c0300-d500-11eb-9413-a9e0cec1ea72.png)

**Comment by ad1992** [comment]
@adandekar-sfdc the `unpkg` cdn is getting blocked due to content security policy so you will have to fix the policy by allowing the urls at your end by adding in `script-src` attribute as shown in the console.

**Comment by adandekar-sfdc** [comment]
I will add that, also when I am trying to install excalidraw via npm I am getting this error. I have to use `--legacy-peer-deps` option to install @ad1992

**Comment by ad1992** [comment]
@adandekar-sfdc we are using `react 17` and due to one of your dependency `sketch` which depends on `react 16` you are getting this error. So the peer dependency needs to be fixed on `sketch` as per the above error.

**Comment by ad1992** [comment]
closing this as its related to 3rd party
