### ISSUE TITLE
When changing the shape's sizes to "negative" values the arrows point to a wrong direction.

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw#377]
![Kapture 2020-01-16 at 1 02 10](https://user-images.githubusercontent.com/125676/72479049-fd0c9280-37fb-11ea-8bd3-b90d6b2c47c1.gif)

**Comment by lipis** [comment]
Same for other shapes as well.

**Comment by lipis** [comment]
There is already a PR fixing this bug #342

**Comment by voluntadpear** [comment]
The previous PR tried to normalize the `width` and `height` values and that in turn proved to be too problematic. I'll open a new PR to solve the UI issues without affecting our coordinates system.

**Comment by gmertk** [comment]
This can be closed I believe. #451
