### ISSUE TITLE
Horizontal and vertical flip for multiple selected shapes and also for groups

### ISSUE THREAD

**Issue by maxime1992** [excalidraw/excalidraw#3771]
If we select one shape, we can flip it horizontally and/or vertically

![image](https://user-images.githubusercontent.com/4950209/123538783-afa58c00-d736-11eb-8293-a833f7097162.png)

If we select more than 1 shape, we can't flip them at once

![image](https://user-images.githubusercontent.com/4950209/123538814-ccda5a80-d736-11eb-9d5f-e0675ac97593.png)

_(I've also tried the keyboard shortcut in case but it didn't work)_

I have tried to group them in 1 shape but same result, can't flip it:

![image](https://user-images.githubusercontent.com/4950209/123538837-f4312780-d736-11eb-884d-61555a87a156.png)

**Comment by dwelle** [comment]
Not implemented yet. It's tracked here, and we were close to fixing it, but it seems the issue is open again. https://github.com/excalidraw/excalidraw/issues/3771
