### ISSUE TITLE
Add open graph for better experience when sharing on social medias

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw#379]
- https://developers.facebook.com/tools/debug/?q=https%3A%2F%2Fwww.excalidraw.com%2F
  `og:url`, `og:type`, `og:title`, `og:image`, `og:description`
- https://cards-dev.twitter.com/validator

**Comment by vjeux** [comment]
Would be great indeed!

**Comment by giovannigiordano** [comment]
@lipis you can make a PR! 🚀

**Comment by lipis** [comment]
@giovannigiordano I'm sure you can do it too.. :D I did my part by reporting the issue.. :D
