### ISSUE TITLE
importing a file replaces elements and reverts versions

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#3795]
Importing a file imports the elements without 1) regenerating the ids (desired?), and 2) not keeping/incrementing the latest versions, and instead reusing the versions from the file.

This causes resolution issues on save/sync.

We can either regenerate ids on import (same as we do with paste), or use the latest version + 1 (and regenerate `versionNonce`).

Steps to repro:

1. import a file with element A with version 0
2. delete element A, which increments version to 1
3. import the file again, which replaces the element A, setting version back to 0
4. whatever `onChange` or sync resolution there is, it'll consider change (3) as a no-op, resulting in not syncing the change to database/clients.

**Comment by ad1992** [comment]
@dwelle won't this be resolved once we have the autosave feature?  As this happens when the latest drawing version is not saved to the file.

**Comment by dwelle** [comment]
No, that's unrelated. Whether you save back to the file you imported from or not shouldn't affect the state integrity.

If the host app (in our case Excalidraw+) persists to the database, we need to ensure the changed elements increment their version (and never decrement). This also affects collaboration.

**Comment by ad1992** [comment]
ok now it's clear since we are reverting the versions, the collaboration also gets affected.
I think we can increment the version and update the version nonce as well so the file import is treated as a new operation and the sync issue also gets resolved.

**Comment by dwelle** [comment]
Yes, I'm inclining towards incrementing versions as well. Will make a PR later.
