### ISSUE TITLE
Misaligned cursor: cursor shown higher than actually clicking

### ISSUE THREAD

**Issue by JakubKoralewski** [excalidraw/excalidraw#3798]
The cursor draws above where it's showing:

https://user-images.githubusercontent.com/43069023/124392054-f0337580-dcf3-11eb-9f80-002d45d29688.mp4

But not specific to a single tool it's for everything

https://user-images.githubusercontent.com/43069023/124392045-e6aa0d80-dcf3-11eb-9da6-452335e2e38c.mp4

It gets fixed after reloading the page.

# Reproduce

Seems to only happen after using a graphics tablet for a while. Then the issue stays regardless whether using mouse or pen. I also did a couple zooms in and out and that seemed to help trigger it as well.

**Comment by dwelle** [comment]
Strange. This never happened to me (apart from special cases, now fixed) so it really must be reproducible only on the tablet, but we haven't had any such reports till now.

What tablet are you using?

**Comment by JakubKoralewski** [comment]
Wacom Intuos, Windows 10 with the Wacom software installed, Windows Ink enabled in Pen mode not mouse

**Comment by dwelle** [comment]
I have Wacom Intuos 3 and Windows 10 as well. I'll try to repro.

**Comment by dwelle** [comment]
Cannot repro still.

**Comment by khalsah** [comment]
I'm having similar issues with the cursor becoming misaligned from where the canvas seems to "think" it is. There are two ways I notice this drift:

1. The drag and resize regions for objects starts to drift from where they are drawn on the screen.
2. Text shifts, seemingly by the same amount, when editing it. It then jumps back when deselected.

A few other notes:

1. I'm using a mouse, no tablet required.
2. I'm using Chrome (`Version 91.0.4472.124 (Official Build) (64-bit)`) on Windows 10 (Build `19042.1083`)
3. My display is scaled to %150 in windows settings.
4. Refreshing the app seems to reset the drift
5. Resizing the window seems to reset drift
6. I can't figure out what "triggers" the drift. I _think_ it slowly get worse over time.

**Comment by dwelle** [comment]
@khalsah thanks for the info. I wants able to reproduce once by setting the display scale to 150% and then playing with excalidraw for a bit! But after refresh I wasn't able to reproduce anymore no matter what I was doing — without consistent reproduction steps it'll be hard to fix :(

**Comment by khalsah** [comment]
After _way_ too much fiddling I think I have some reproduction steps and some more observations.

#### Steps to reproduce
1. On windows 10, set display scaling to 150%
2. Create ~256 text elements on the canvas (duplicate is your friend). Using multiple colors can be helpful for a later observation.
3. Zoom in to 1000% (smaller zooms _work_ but I think the error accumulates faster the more zoomed in you are).
4. Middle click to scroll the canvas, drag it continuously for several seconds.

#### Observations
1. You should notice that the cursor is misaligned, even if you zoom back out to 100%.
2. You should notice that there are now rendering artifacts along the top and left edges of the canvas where the screen is not getting cleared between renders. This suggests that the transform matrix of the canvas is not getting set back to the identity between rendering frames, and some small error there is accumulating.

![image](https://user-images.githubusercontent.com/4380/125466530-48f5d31c-4b46-471b-9f86-5bead3074cae.png)

#### Possible fix
Given that the canvas transform matrix is accumulating some error, a simple `context.resetTransform()`, or equivalently `context.setTransform(1, 0, 0, 1, 0, 0);` at the start of `renderScene`  (line 209) should prevent this error from accumulating across render frames.

https://github.com/excalidraw/excalidraw/blob/0749d2c1f3902ad32f0bdaeefa36bd3b0e137dc7/src/renderer/renderScene.ts#L208-L210

#### Unanswered questions
None of this explains _why_ an error is being introduced. It seems to only happen when `window.devicePixelRatio` is a non-integer value. (The probably does not appear to occur with the display zoom set to either 100% or 200%).

**Comment by dwelle** [comment]
Thanks for more info. With the above steps I can reproduce. More observations:

1. the more elements on the scene there are, the more quickly it seems to accumulate — though I'm not 100% certain of this.
2. staying on 100% zoom manifests the error as well, so it's likely not related to zoom.
3. The point above non-integer `devicePixelRatio`  seems correct. In fact, you don't even need to change display scane, just zoom the browser itself (put cursor in the the url bar and press `ctrl - +`).
4. for some reason Y axis harder to reproduce on and the error accumulates more on the X axis. One way to reproduce quickly is to hold mousewheel and drag from left to right in a quick fashion (you don't need to drag make the motion wider than ~200px)

> Given that the canvas transform matrix is accumulating some error, a simple `context.resetTransform()`, or equivalently `context.setTransform(1, 0, 0, 1, 0, 0);` at the start of `renderScene` (line 209) should prevent this error from accumulating across render frames.

Would have to check, but this would likely mess with zoom — we might also be doing other transformations of the canvas I don't remember.

**Comment by dwelle** [comment]
For whatever it's worth, I can't repro on Firefox nor Safari, only Chromium browsers.

**Comment by dwelle** [comment]
@khalsah actually, we may not be doing any transforms, and even if, if you reset the transform at the start of `renderScene()` it should be fine regardless. Feel free to open a PR!
