### ISSUE TITLE
Ability to search for a text

### ISSUE THREAD

**Issue by jaideeprana** [excalidraw/excalidraw#3826]
Currently I have a pretty big diagram and I am looking for an ability to quickly search for a given text but I am unable to find a way.

The browser search(Cmd/Ctrl + f) isn't helping.

Is there a way to do so in Excalidraw?

**Comment by dwelle** [comment]
Not currently. Similar feature is planned for http://plus.excalidraw.com/, but we may as well start with the support here.

I imagine we can hijack `cmd/ctrl-f` since there's not much keeping the native browser behavior.

**Comment by jaideeprana** [comment]
Sure.

Not sure how easy or difficult is to search for a text on the canvas. But I am eagerly looking forward to this feature.

**Comment by dwelle** [comment]
This feature would consist of 3 things:

1. Search for match across elements' texts

	Difficulty: **easy** to **medium** depending on whether we want to lexemize the tokens so that e.g. searching for `catch` matches `caught` (if so, we'll likely want to use a search library for this).

2. Build a search dialog

	Difficulty: **medium**

3. Support highlighting matches on canvas and scrolling them into view

	Difficulty: **medium** to **hard** (finding and scrolling to target text element position is easy, but finding exact position and dimensions of matched word may not be easy).

**Comment by connor-pph** [comment]
@dwelle can I take this one?

**Comment by dwelle** [comment]
Sure thing!

Let's implement it in stages, even if end up doing it in one PR.

For (1) I'd use something like https://github.com/bvaughn/js-search (he suggests using https://github.com/jedp/porter-stemmer for stemming). Both lightweight, but we can put them in conjunction with our implem code into a module that we dynamically import them once user starts to search.

Once that's done we can discuss next steps. Thoughts?

**Comment by connor-pph** [comment]
Sounds good! No questions right now - I'll reach out if something comes up

**Comment by tom-sherman** [comment]
I'm not sure on the value of doing any fuzzy searching, sounds really hard to do in a localised way. What's the use case for that? I think exact text search (like the browser find) is 95% of the use case.

**Comment by dwelle** [comment]
we can start with plain search and improve on later. But fuzzy/fulltext search shouldn't be hard either way, once we nail down the plumbing and UI stuff.

**Comment by dragonman225** [comment]
As far as I know, fuzzy search is useful in two cases:

1. to tolerate typos and capitalization, e.g. "excaldraw" would match "Excalidraw"
2. to query with non-exact phrases, e.g. "search text" would match "Ability to search for a text"

And these are helpful for people who are using Excalidraw not just for casual drawing, but to jot down thoughts and drawings that they're going to revisit later. (I'm one.)

I used a fuzzy search library called [Fuse.js](https://fusejs.io/) in a project before, it achieves the two cases I describe and it's easy to use.

Of course, exact text search is still viable when fuzzy search is present.

**Comment by dragonman225** [comment]
@dwelle I was thinking about text search and came across this. I hacked together a prototype quickly (#5435) that includes

- `Ctrl/Cmd+F` to bring up a dialog
- type to search and scroll matched text element into view
- navigate between matched text elements with `Enter` or buttons
- fuzzy search

I'd love to hear what you think of it.

**Comment by Thedineshk24** [comment]
@dwelle @ad1992  I've implemented text search which scroll to near by part of matched content

**Comment by EswaraSatya** [comment]
I am interested to contribute to integrate the search functionality as i had developed it already.
Can I get an opportunity here.

**Comment by dragonman225** [comment]
@EswaraSatya According to the [Contributing](https://docs.excalidraw.com/docs/introduction/contributing) documentation, you could to open a pull request for your implementation, and try to contact an Excalidraw developer to discuss how to merge it.

**Comment by sojusnik** [comment]
> I am interested to contribute to integrate the search functionality as i had developed it already. Can I get an opportunity here.

@EswaraSatya an additional feature could be an option to find text with colors used on the whiteboard to be able f.i. to search for red text.

**Comment by EswaraSatya** [comment]
Hi,

It means user can able to search the text which is red in color on the
white board if I am not wrong

Thanks,
Eswara Satya

**Comment by sojusnik** [comment]
> It means user can able to search the text which is red in color on the white board if I am not wrong

This is the idea :)

This would allow to not only search for text, but also for text written in a certain color, that is used on the whiteboard.

**Comment by EswaraSatya** [comment]
Where can I start can you please help me out

**Comment by liyu1981** [comment]
Hi, 

I am wondering that whether someone is on this one? Seems to be an important feature but missing. 

I hacked it a bit, and below is the result
![Image](https://github.com/excalidraw/excalidraw/assets/499599/db9bb808-fe77-489d-858b-fbb103d2c79c)

If this seems to be good enough, I can clean it up and create PRs. If so please just assign to me.

**Comment by sojusnik** [comment]
@liyu1981 That looks A W E S O M E !!!

**Comment by liyu1981** [comment]
I have created my changes as a pull request at #7300. I do not mind either mine or @dragonman225 's effort to be merged, but if this needs me, just @ me.

**Comment by Mrazator** [comment]
We've recently released the full-text search, championed by @ryan-di!

https://twitter.com/excalidraw/status/1834254530025779450
