### ISSUE TITLE
[Suggestion] Add Plugin System to integrate custom shape

### ISSUE THREAD

**Issue by MicleMing** [excalidraw/excalidraw#383]
Hi, It's awesome tool !  And I have found some issues is expanding shapes. if we have a plugin system to support users to expand they custom shapes by themself, It will more cool. for example: 
```
<App plugins={[]}>
```

**Comment by j-f1** [comment]
I was just thinking about how to do this and I think when we figure out artboards/frames it would be cool to be able to export one of those to an Excalidraw file and upload it to GitHub. People could then import a shape from your repo at a specific commit/branch and include it in their drawing. That would break offline support though

**Comment by lipis** [comment]
Not exactly a plugin versions, but we now support adding items to the library, so we'll close this for now :)
