### ISSUE TITLE
Creating Shareable link fails with CORS error on plus.excalidraw.com

### ISSUE THREAD

**Issue by essential-randomness** [excalidraw/excalidraw#3846]
Unsure whether this is the right place to report issues with plus. Do redirect as needed :)

I've been trying to create shareable links for my drawings on Chrome, but it simply hangs. The url for the drawing is https://plus.excalidraw.com/s/AWH4aJGGt8v/36CryJwGVzo.

Looking at the dev console, the following error appears when trying to share:

```
Access to fetch at 'https://us-central1-quickstart-1595168317408.cloudfunctions.net/api/scene/36CryJwGVzo/linkSharing' from origin 'https://plus.excalidraw.com' has been blocked by CORS policy: Method PATCH is not allowed by Access-Control-Allow-Methods in preflight response.
22.8d2bc220.chunk.js:2 PATCH https://us-central1-quickstart-1595168317408.cloudfunctions.net/api/scene/36CryJwGVzo/linkSharing net::ERR_FAILED
36CryJwGVzo:1 Uncaught (in promise) TypeError: Failed to fetch
```

**Comment by dwelle** [comment]
Hello, are you behind a company proxy/VPN?

**Comment by essential-randomness** [comment]
Nope! Just regular home wifi.

**Comment by dwelle** [comment]
I'm not sure what could be causing this. Do you have any browser extensions that could cause this? Adblocker, privacy extensions, etc.? You can try an incognito tab. Does it work in other browsers?

**Comment by essential-randomness** [comment]
I've tried in the past couple days on different machines and it seems like the error is gone. Might have been something in my configuration, though I feel like it was happening cross-browser. No harm done :) thanks for the quick reply!

**Comment by dwelle** [comment]
No problem!
