### ISSUE TITLE
Autolayout container to fit text

### ISSUE THREAD

**Issue by jenningsb2** [excalidraw/excalidraw#3850]
Hey team! 

I would love it if text boxes and shapes interacted with each other. Most flow chart software has a concept of auto-layout of text within the shape. This would allow users to have variable text body lengths while repeatedly using the same assets. 

**Current Behavior**:

![CleanShot 2021-07-20 at 12 29 45](https://user-images.githubusercontent.com/29644050/126361298-b166baff-a22b-4e35-bc9e-f645d096fca3.gif)

**Demo of proposed behavior:** 

![CleanShot 2021-07-20 at 12 25 34](https://user-images.githubusercontent.com/29644050/126360868-7460f2d5-6781-40ad-a909-30508b1e6bf5.gif)

**Comment by dwelle** [comment]
I'd say this is more or less a duplicate of https://github.com/excalidraw/excalidraw/issues/1428?

**Comment by jenningsb2** [comment]
You are correct @dwelle! Thanks for the call out. Closing this thread
