### ISSUE TITLE
arrow labels/text (binding)

### ISSUE THREAD

**Issue by jenningsb2** [excalidraw/excalidraw#3857]
A common pattern amoung diagraming tools is the ability to add text to a connection line. This helps describe the transition stages of a diagram, so it would be great to have in Excalidraw!

**Examples**

Miro:

<img width="1342" alt="CleanShot 2021-07-22 at 08 54 36@2x" src="https://user-images.githubusercontent.com/29644050/126642235-480613ab-9058-4042-916f-17177486d8d2.png">

FigJam:

<img width="1303" alt="CleanShot 2021-07-22 at 08 55 26@2x" src="https://user-images.githubusercontent.com/29644050/126642323-5da626cb-5296-4515-b422-6f0b60de52da.png">

**Comment by dwelle** [comment]
I'm sure this was requested before but I can't find the issue right now. Not sure how this would work with multi-point lines, but we could add this feature for two-point lines (or between two points of any multi-point line).

We should also figure out how this would work from user perspective.

**Comment by jenningsb2** [comment]
The most common pattern is double-clicking on the center of the connection line to start the text input!

Agreed, this should only apply to multi-point lines!

**Comment by dwelle** [comment]
Closing as now implemented.
