### ISSUE TITLE
Rewrite copy/paste to move away from system clipboard

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#386]
As discussed in https://github.com/excalidraw/excalidraw/issues/254 there are several issues with current implementation, which uses system clipboard:

1. Various permission issues & support issues, which may be behind all the reports: https://github.com/excalidraw/excalidraw/issues/382 https://github.com/excalidraw/excalidraw/issues/359 https://github.com/excalidraw/excalidraw/issues/249

    For example, on my system (win7) in Chromium-based browsers, paste doesn't work by default (for first access) and gives no indication of what action needs to be taken. I need to paste using contextMenu which only then shows a permission prompt. Lately, I also need to refresh afterwards before the paste starts to work:

    ![excalidraw_copy_paste_perms](https://user-images.githubusercontent.com/5153846/72519372-7e454300-3857-11ea-8ecb-cb062e890b19.gif)

	(also note that in the above GIF, what was actually pasted is some different clipboard from different scene, since it appears the copy didn't initially work, either).

2. Current solution overrides system clipboard with element JSON data (and potentially overrides whatever was presently in system clipboard).

If we move to in-app implementation (listening on `Cmd/Ctrl+C/V`), the above problems should disappear.

@vjeux also noted that one goal of current implementation is the ability to paste across different browser tabs. This can be solved by propagating the clipboard state using `localStorage`, which all tabs of the same domain share. On this note, since we're already storing scene state to `localStorage`, all tabs are being eventually synchronized, so cross-tab pasting doesn't make sense at this time, anyway.

**Comment by 0x11-lgtm** [comment]
We should use clipboard api with custom datatype, eg:`clipboardData.setData(new Blob(), 'application/excalidraw')`. Use localstorage as a fallback on safari and firefox.

**Comment by dwelle** [comment]
@0x11-lgtm Just to get on the same page, what you're mentioning is a prop on [ClipboardEvent](ClipboardEvent.clipboardData), while [Clipboard API](https://developer.mozilla.org/en-US/docs/Web/API/Clipboard) a different thing.

**Comment by 0x11-lgtm** [comment]
@dwelle Thanks for your reply.

It's much better with system clipboard. We also should set the corresponding data type for the data. Here are two benefits:
1. Web application can put the same symbol in different type, eg: `application/octet-stream` and `image/svg+xml`. Web app can read buffer as `application/octet-stream`, then parse it.  We can also paste the symbol as image to other application, eg: the office or im application.
2. Use `localStorage` as a downgrade.

The bug you mentioned happened after click on the `ToolIcon`. We need to dig it.

We are on same page BTW: [Clipboard API](https://w3c.github.io/clipboard-apis/#async-clipboard-api)  works for the context menu, and [Clipboard Event API](https://w3c.github.io/clipboard-apis/#clipboard-event-api) works for `CMD+C` or `CMD+V` shortcuts.

**Comment by dwelle** [comment]
@0x11-lgtm sorry for not getting back to you sooner.

Here's the plan for next week:

1. I'll investigate how this could be used for pasting into other apps, and whether it adds enough benefit to be worth sticking to Clipboard API. Are you saying that if we e.g. set `image/svg+xml`, Adobe Illustrator will be able to parse that SVG on paste? `image/svg+xml` seems like the only useful format we could export outside excalidraw (not sure what `application/octet-stream` would be for, as that's used for generic binary data --- what would we export exactly?).
2. if (1) pans out, then I'll fix https://github.com/excalidraw/excalidraw/pull/421 (and leave the MIME types for later because we don't support SVG export right now). The idea will be to at least always ask for permissions on copy/paste (if app doesn't have them yet) instead of silently failing and doing nothing.
3. if (1) isn't worth it, then I'll scrap Clipboard API in favor of combination of `copy`/`paste` event (for text pasting from system clipboard), and internal state to handle in-app copy/paste (via `CMD/CTRL+C/V`).

**Comment by dwelle** [comment]
After more investigation, here's the deal: AFAIK copy/paste via contextMenu, which is completely programmatic, won't be possibly due to browser support if we push forward with async Clipboard API. (Well, technically it might be possible via `execCommand` hack. Will need to investigate this, too).

**Comment by dwelle** [comment]
@0x11-lgtm do you have any experience with copying `image/svg+xml` to clipboard? It seems that Async Clipboard API doesn't support it yet (even though it's specced). Can't get it to work with sync Clipboard API. It's [supposedly](https://bugs.chromium.org/p/chromium/issues/detail?id=150835#c73) working for `execCommand`, but that I reckon would work only for actual svg images.
