### ISSUE TITLE
refactor: Open Color string translations should be based on base color and color variations, not listed individually

### ISSUE THREAD

**Issue by tomayac** [excalidraw/excalidraw#3887]
See https://github.com/excalidraw/excalidraw/pull/3871#pullrequestreview-717988529 for context.

**Comment by jorellana28** [comment]
@tomayac If you weren't going to work on this can I be assigned to it?

**Comment by ad1992** [comment]
@jorellana28 feel free to pick it up

**Comment by dwelle** [comment]
closing as it'll be addressed in the color picker redesign
