### ISSUE TITLE
[Feature] Add ability to move shapes between z-index layers

### ISSUE THREAD

**Issue by viglucci** [excalidraw/excalidraw#392]
**User Story**

As a user, I want to be able to change whether the shape I currently have selected is drawn on top of or below other adjacent shapes so that I can more precisely communicate the relationships between shapes.

**Potential Solutions**
- Move to top button
  - Clicking the "move to top button" moves the currently selected shape to the "topmost" z-index
- Move up button
  - Clicking the "move up button" moves the currently selected shape up one "index" in the z-index stack
- Layers system
  - Implement an entire layers system that allows users to define their own layers and select which layer they are drawing in, select all shapes in a layer, etc.

**Problem Example**

With the green rectangle selected, the user should be able to adjust the Z-index of the shape so that it draws on top of the red rectangle, rather than the red rectangle drawing on top of the green rectangle.

![image](https://user-images.githubusercontent.com/6305490/72542398-b5145c80-3849-11ea-9e6d-4f6cc7a1859f.png)

**Comment by viglucci** [comment]
This appears to already be implemented but is hidden behind a context menu on right click of an element. re: #21 

![image](https://user-images.githubusercontent.com/6305490/72543275-20126300-384b-11ea-91ac-283bf34fee2f.png)

**Comment by dwelle** [comment]
It's a valid point. Not sure if we should add a message about this to the hints manager #335, or if it was a good idea to remove it from the menu to begin with. I think we should maybe reintroduce it to the shape menu, using small icons:

![image](https://user-images.githubusercontent.com/5153846/72545087-ba44cc00-3888-11ea-873d-c58052271087.png)

**Comment by viglucci** [comment]
I'm personally in favor of it being included in the shape menu/not hidden behind a context menu, or for finding some way to communicate that extra actions are possible in a context menu.

I think unfortunately I'm trained that right clicking on a website will show me the context menu from the browser, so I didnt even consider there might be more actions I could perform that way.

The mock you've provided looks great IMO.

**Comment by dwelle** [comment]
> I think unfortunately I'm trained that right clicking on a website will show me the context menu.

Yes, it's a feature that's not very common on the web, though becoming used more often (Google Drive, Dropbox, ...), and thus not very intuitive.

> The mock you've provided looks great IMO.

It's actually from a desktop app. We'd need to create our own icon set, I believe, since icons like these are pretty specific (FontAwesome has these, but only two of them, and behind a paywall).
