### ISSUE TITLE
Feature Request: Requesting the ability to copy and paste images into stackedit

### ISSUE THREAD

**Issue by isConic** [excalidraw/excalidraw#3924]
I know that this is a tall order and many things need to be considered from an engineering aspect, however 
from a user experience standpoint:

This is the ONLY deciding factor between me using `FigJam` vs excalidraw. As I find `figjam` to be heavy and rigid. I really prefer excalidraw when it comes to making conceptual diagrams.  It's very easy/intuitive to use.

**Comment by dwelle** [comment]
Hey. Do you mean exporting the PNG to clipboard and pasting it to https://stackedit.io? They'd have to support this on their end.

**Comment by isConic** [comment]
@dwelle  
The interaction I have in mind is right-clicking and image outside of excalidraw and selecting `Copy Image`.   

Then via `ctrl+v` or right-click/paste inserting the image onto the canvas.

**Comment by dwelle** [comment]
oh, ok. Yes, that will work once we support images soon. You can try out the preview here: https://excalidraw-9im2ruy53-excalidraw.vercel.app/

Will close this for now
