### ISSUE TITLE
How to draw curved lines/arrows?

### ISSUE THREAD

**Issue by xjvs** [excalidraw/excalidraw#3925]
I've been searching and watching some videos, but failed to figure out how to draw curved lines/arrows, seem there should be a hand pointer appears when move to the border, but it doesn't show up for me, can someone help?
A gif is attached:
![excalidraw](https://user-images.githubusercontent.com/7976254/130251361-a5d26f12-f9bb-4bbf-bbc0-541458f4b45e.gif)

**Comment by dwelle** [comment]
Hey @xjvs — instead of click-dragging, use a click-click-click workflow.

At some point we will improve how you can create multi-point arrows so it's more intuitive.
