### ISSUE TITLE
Importing Excalidraw Hook Error

### ISSUE THREAD

**Issue by crashedpixel** [excalidraw/excalidraw#3935]
This is maybe a bit of a vague issue but I cloned the repo (yesterday) and was trying to include it on page. And I keep seeing this react hooks error:

<img width="877" alt="Screen Shot 2021-08-24 at 8 43 06 AM" src="https://user-images.githubusercontent.com/69129964/130627720-639ebbdb-f7d7-4ee2-8ccf-b866d4a9d91f.png">

When I inspect what line it's breaking on I see this:

<img width="472" alt="Screen Shot 2021-08-24 at 8 43 15 AM" src="https://user-images.githubusercontent.com/69129964/130627780-e311b2ee-45f4-492a-bfb4-494fe32d6c29.png">

It's complaining about the useEffect hook in the Excalidraw library? I checked out the codesand.io example and it seemed okay. Has anyone else run into this issue? I tried loading the component after the main component mounted but same result.

React/ dom versions:

```
    "react": "^17.0.2",
    "react-dom": "^17.0.2"
```

**Comment by crashedpixel** [comment]
@dwelle any idea?

**Comment by dwelle** [comment]
I've got this error a couple of times before and boiled down to several cases:

1. mismatch between React versions. I'd first try to ensure your app is using the exact version that Excalidraw is using (by which I mean what we have in package.json --- the UMD bundle on npm doesn't bundle the React itself).
2. if you're forking, which seems not be your case, there may be an error in the build (bundling) step
