### ISSUE TITLE
Help icon is not visible in Safari, Chrome and Firefox (iPad)

### ISSUE THREAD

**Issue by tim-krieger** [excalidraw/excalidraw#3938]
I can reproduce this with all mentioned browsers with my iPad 2019 (iPad OS 14.6). Portrait and landscape. The web inspector (Chromium, Linux) shows the help icon on all screen sizes.

![IMG_0403](https://user-images.githubusercontent.com/64839715/130687790-4d53849a-78c7-406c-8148-04a09a88b913.PNG)

**Comment by dwelle** [comment]
Thanks for catching this!
