### ISSUE TITLE
Feature Request: Powerpoint integration

### ISSUE THREAD

**Issue by dschmag** [excalidraw/excalidraw#3947]
Is there a way to integrate excalidraw drawings in a powerpoint slideshow?

Current workflow:
1. create excalidraw and save local (next to the powerpoint file)
2. export excalidraw to png 
3. drag and drop into presentation
4. change excalidraw -> goto 2
 
Desired workflow:
1. create excalidraw and save local (next to the powerpoint file)
2. drag and drop excalidraw into presentation - image is automatically shown
3. double click to edit excalidraw - save end exit excalidraw - image is automatically shown

**Comment by maielo** [comment]
Hey,

We implemented the feature to export presentations in [Excalidraw+](https://plus.excalidraw.com/) as PPTX last week. Additionally, we support exporting presentations as PDF files.

You can access this functionality through various options:

Use the 'Quick export' feature.
Find it within the scene in the presentation tab.
Export directly from the Excalidraw presentation interface itself.

Showcase:

https://github.com/excalidraw/excalidraw/assets/8983870/c74d5221-6624-41f7-9e1c-180eff900b89

**Comment by vhristev** [comment]
Any plan to do an object export? For example, I draw something in Excalidraw+ and then export it to PPTX as an object, which I can modify in PowerPoint.
