### ISSUE TITLE
Issue - Export Tool

### ISSUE THREAD

**Issue by JustAsteri** [excalidraw/excalidraw#3948]
The save image tool doesn't work for large scenes.
When it is empty, it works perfectly, but when it has content (especially big), it doesn't work.

**Comment by dwelle** [comment]
Hello. Browsers don't handle very large canvases well. You can check the dimensions (width, height) in the "stats for nerds" you can display by right-clicking on the canvas and choosing it from the context menu. Alternatively you can save to JSON and we can check ourselves.

Alas, not much we can do (apart from some non-trivial workarounds which we may do at some point, but not right now).
