### ISSUE TITLE
Scribble: Apple Pencil misses strokes

### ISSUE THREAD

**Issue by idvorkin** [excalidraw/excalidraw#3955]
**OMG Love this project, it's a game changer in the new world of remote work!**

(I also love using my apple pencil) I'm not sure what is going wrong but it always happens. When I try to use my pencil some strokes are drawn,  some strokes are missed,  and some strokes seem to be doing a selection/drag. 

In the attached video I'm writing hello world and you see the missed strokes (well you don't see them, :) ) 

Happy to help debug!

https://user-images.githubusercontent.com/280981/131703398-f4845501-c225-4bb8-9054-0b96a17a7a95.mp4

I'm on iOS 15, with the latest 12.9" iPad, happens on both chrome and safari.

**Comment by dwelle** [comment]
Hey. If you have `Scribble` enabled in your Pencil settings, then disabling it will improve this. Not great if you're depending on Scribble features though. We will try to fix this regardless of that setting.

It may not solve it entirely.

Question: if you drag-select all the elements (encompassing the ones missing), are some of them "invisible"?

![image](https://user-images.githubusercontent.com/5153846/131715649-5eb8df53-ccfd-4024-89b3-cf2056c7bb3e.png)

If so, then there's also a different bug in play.

**Comment by idvorkin** [comment]
Yes, to both.

1. Disabling scribble improves this drastically (though not perfect, and sometimes I get a zoom in behavior while drawing). 

2.  On the missing strokes, when I select it's picking up invisible elements.

Are there issues for the above I can follow? Also, out of curiosity what is going on in case 1 and how does scribble impact it?

**Comment by dwelle** [comment]
1. There's a bug in Safari https://bugs.webkit.org/show_bug.cgi?id=217430 — it can be potentially improved/solved by preventing certain events, though it'll likely affect some parts of our app. We'll want to investigate this soon.

	I don't think there's an issue for this yet, so we'll use this one to track it.

2. It's related to this bug https://github.com/excalidraw/excalidraw/issues/3564

**Comment by dwelle** [comment]
Here's an attempted fix for the Scribble missing strokes issue: https://excalidraw-git-fixscribble-excalidraw.vercel.app/ Lemme know if you can still reproduce!
