### ISSUE TITLE
Pasting doesn't work correctly within wysiwyg text

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#396]
Instead of replacing the selected part of the text, it replaces the entire text input with the paste value.

Reported by Ivan Babak

**Comment by dwelle** [comment]
I can fix this in a followup to https://github.com/excalidraw/excalidraw/pull/385 where I want to fix multiline pasting.

**Comment by jillesme** [comment]
@dwelle do you want me to merge mine now or in ~5/6 hours when I have time to address Christopher's comments?

**Comment by dwelle** [comment]
@jillesme take your time, this issue isn't going anywhere :).
