### ISSUE TITLE
Drag and drop from outside excalidraw throws unfriendly error

### ISSUE THREAD

**Issue by tommilligan** [excalidraw/excalidraw#3971]
Dragging and dropping a non-excalidraw object onto the canvas leads to a non-user friendly message `Cannot read properties of undefined (reading 'type')`.

I understand why we get this (we're not expected to be dragging other objects into the canvas), but suggest that the error message should be something nice like 'This object cannot be added to the Excalidraw canvas.'

See below for reproduction (Ubuntu 20.04, Chromium 93.0.4577.63):

![excalidraw drag drop error](https://user-images.githubusercontent.com/12255914/132213278-986ccc2f-0e9e-409e-9443-1f2413d89e7e.gif)

---

This feels simple enough for a first contribution, I will try and take a look this weekend.

**Comment by yuriybelike** [comment]
+1. It gets a bit annoying when you're using groups and you're used to double click every text in order to ungroup it from its rectangle, but when the text is not in a group the error happens. Well, it's exactly the above GIF's situation...

**Comment by tommilligan** [comment]
Thanks for the poke. There is now a PR for this here: https://github.com/excalidraw/excalidraw/pull/4890
