### ISSUE TITLE
Show the styles sidebar as soon as a tool is selected 

### ISSUE THREAD

**Issue by sompylasar** [excalidraw/excalidraw#398]
Currently the sidebar looks like this, showing one white color picker which doesn't seem to apply to anything:

<img width="231" alt="Screen Shot 2020-01-16 at 11 39 51 AM" src="https://user-images.githubusercontent.com/498274/72557122-f0685880-3854-11ea-9da7-5415eecac0c1.png">

But the tools implicitly apply some shared state of previously selected colors. This state is not visible to the user, so it's unexpected what will happen when I use the tool.

For example, after drawing a shape, then changing its stroke color to red, then adding some text (e.g. via double-click on an empty surface), the text will be red as well while I type it in, but the sidebar does not reflect that, keeps showing one white color picker. It only will show when I finish editing the text and select it with the arrow tool.

**Comment by sompylasar** [comment]
Also, even if the Text tool is not selected when entering text with double-click (#399), I'd expect the sidebar to show the current text styles while I'm typing the text.

**Comment by Fausto95** [comment]
> the text will be red as well while I type it in
This is due to the fact that the app uses a shared state ofc! I can't recall but seems that we've discussed about having separated states.

> I'd expect the sidebar to show the current text styles while I'm typing the text

Agree

@sompylasar PRs are welcome

**Comment by Fausto95** [comment]
- [x] Show Shape Actions Panel on shape tool select(https://github.com/excalidraw/excalidraw/pull/448)
- [ ] Fix global shapes state(backgroundColor & strokeColor)

**Comment by vjeux** [comment]
This has been fixed :)
