### ISSUE TITLE
ctrl click to select multiple objects

### ISSUE THREAD

**Issue by anashashmi** [excalidraw/excalidraw#3982]
On Windows, selecting more than one object is by either drawing a crosshair or pressing and holding CTRL and clicking each object that needs to be added to the selection.  

On Excalidraw, this can be achieved by drawing a crosshair and covering the object(s) entirely and/or by holding Shift and either drawing multiple crosshairs or shift+click on each object.

My request is to add Windows-like behavior of holding CTRL and clicking each individual object that needs to be added to selection.

# Feature Request

**Comment by dwelle** [comment]
Ctrl/Cmd-click has a behavior bound to it of its own: drill-select, child-box-select, and later will have at least one more. In other words, it's taken. Moreover, most graphics/vector apps do the same (shift-click to add to selection, only), and Figma is using ctrl/cmd-click behavior same as we do.
