### ISSUE TITLE
Adding group to selection doesn't add the whole group

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#3991]
steps:

1. create elements A, B, C
2. group elements B, C
3. select element A
4. hold `shift` and click on element B

**expected**

should add the whole {B,C} group to the selection

**actual**

adds only the element B instead of the whole group

**Comment by ishandeveloper** [comment]
Hey @dwelle, I was trying to play around with this but couldn't reproduce the issue you've mentioned. Is this fixed or could you tell me If you were referring to something else? Would love to contribute 🙂

https://user-images.githubusercontent.com/54989142/134592478-8a93ba99-c5d3-4ff1-862d-051b14c68b69.mov

**Comment by dwelle** [comment]
Strange, I can't repro either. It must have been under some special circumstances. Will reopen if I can repro later!
