### ISSUE TITLE
Hebrew translation disappeared in latest version

### ISSUE THREAD

**Issue by yhacohen** [excalidraw/excalidraw#3993]
Hi and thanks for the amazing product. 
In the latest versions i've noticed (not sure exactly when) that the hebrew translation is not available anymore in the language selector. Is this behaviour intended?

**Comment by dwelle** [comment]
Hey. Our automated translations work in a way that if a language falls under a given translation threshold (85%) it does not get included in the app. This can happen when we introduce more texts to the app.

You can track the Hebrew translation [here](https://github.com/excalidraw/excalidraw/pull/3858), and contribute on [Crowdin](https://crowdin.com/translate/excalidraw/10/en-he).
