### ISSUE TITLE
Graceful Handling of Invalid Encryption Key

### ISSUE THREAD

**Issue by ishandeveloper** [excalidraw/excalidraw#3994]
In the project README, where we guide people on how to [create a collaboration session manually ](https://github.com/excalidraw/excalidraw#create-a-collaboration-session-manually). We never explicitly mention about the number of characters a user needs to have in their encryption key. 

And if you go ahead with any other number of characters, let's say 20 for example. Things gets confusing... Since the Teams icon in top left turns green, a user would think that it's working in the correct manner, how it's supposed to be. However, if you open up the console and look at the flood of errors, you'd notice immediately that the collaboration feature doesn't actually work because of an invalid encryption key.

![image](https://user-images.githubusercontent.com/54989142/134407076-3a1421aa-78e1-46e5-a7d1-20e630a0a0c8.png)

and as a first time user, you have to look at `{22}` in the regular expression in the GitHub README, to figure out what's wrong and how to resolve it, which is a bad experience.

I propose that we should firstly update our README and explicitly mention that the encryption key should have a length of 22 characters and another thing is to add a check for the `roomKey` length in the method below have a fallback (a dialog or window.alert) to notify the user that they're using an invalid encryption key.

https://github.com/excalidraw/excalidraw/blob/7199d13f484b8c9a79ec241066e1058fe9ff7139/src/excalidraw-app/data/index.ts#L137-L141

Thoughts?

**Comment by ad1992** [comment]
Hey @ishandeveloper sure let's update the readme first, and then we can have bettor error handling so we can show an alert to the user informing about the error.

**Comment by ishandeveloper** [comment]
@ad1992 Raised a PR over here : #3995 for the README update.
For error handling and alert, do we already have a Dialog component or something that I could use, or should I go ahead with `window.alert` or a custom implementation?

**Comment by ad1992** [comment]
Yes we have Dialog but we can go ahead with `window.alert` as thats what we are using for other warnings as well.
