### ISSUE TITLE
the main file is getting bigger 

### ISSUE THREAD

**Issue by mohammadameer** [excalidraw/excalidraw#40]
the main file is gitting bigger we should modulize it

**Comment by mohammadameer** [comment]
i can work in that

**Comment by dwelle** [comment]
Yep, we should split it in the next few commits.

**Comment by mohammadameer** [comment]
i want to work in that :nerd_face:

**Comment by dwelle** [comment]
Not sure what's the progress on this one, but let's wait until at least #52, #55, #53 are merged. Also possibly until we rewrite codebase to hooks.

**Comment by giovannigiordano** [comment]
As @dwelle said we have to wait at least the #52 and then we can split the file.

**Comment by AndreBastos23** [comment]
From my understanding, @vjeux already migrated the elements variable inside the react-scope. I stop working on #52 since it's already done.

**Comment by vjeux** [comment]
I did not! I just moved drawScene from being a global to being run during componentDidUpdate

**Comment by GasimGasimzada** [comment]
This issue can be closed #202
