### ISSUE TITLE
Stale bindings when copying arrows.

### ISSUE THREAD

**Issue by steveruizok** [excalidraw/excalidraw#4000]
Copied arrows can sometimes maintain stale bindings.

![Kapture 2021-09-24 at 13 56 18](https://user-images.githubusercontent.com/23072548/134677846-33aba9b9-9a0d-409c-88e9-a22d64780d14.gif)

To reproduce:

- Bind an arrow to a box (A) and a second box (B)
- Select box A and the arrow
- Copy
- Paste
- Move the box A

Notes:

This bug does not happen if you move the selection before moving the box.

![Kapture 2021-09-24 at 14 02 08](https://user-images.githubusercontent.com/23072548/134678736-74a7f91d-e95e-450a-af18-c8b0350ee91b.gif)

This only seems to happen when only one of the arrow's bound-to shapes is copied together with the arrow.

**Comment by dwelle** [comment]
Looks fixed.
