### ISSUE TITLE
Resizing multiple linear elements often relatively misaligns them

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#4001]
It's related to some initial unspecified conditions most likely related to roughjs (or how we use the low-level coords coming from roughjs). Meaning, it manifests for the box below, but if you duplicate it (and hence regenerate the shape), chances are it won't reproduce (or reproduce differently).

AFAIK doesn't manifest with non-linear elements, which kinda makes sense because we're not touching roughjs data for those cases.

(Note that when duplicating via ALt, the shape you're dragging isn't the one regenerated)

![resize_misalignment_2](https://user-images.githubusercontent.com/5153846/134706438-0e6776fe-2a6e-4412-9302-8ae78e548d9d.gif)

https://excalidraw.com/?#json=5334617385074688,oOxke10L60t4kkkBC-JUUA

more examples:

https://excalidraw.com/?#json=5549363703054336,-0vFlwxR5g2UB-lT24WnNg

/cc @dai-shi any ideas?

possibly related to https://github.com/excalidraw/excalidraw/issues/2896

**Comment by dwelle** [comment]
Reproduces only for non-0 `roughness` line elements (not freedraw). Shift-locking makes it much worse.

![excal-line-element-shift-resize-bug](https://user-images.githubusercontent.com/5153846/183267994-ecb917a8-c788-4e8e-96a6-ea78fc60d1f3.gif)

**Comment by dai-shi** [comment]
I'm not sure how much code is changed since when I was working on, but it looks like the issue of calculating bounding box.

(I can only reproduce with either #2896 or pressing on and off SHIFT _while_ dragging.)

**Comment by alexforster** [comment]
Anecdata: I'm a pretty frequent Excalidraw user and many of the library shapes I regularly use have only recently started doing this.
