### ISSUE TITLE
Resize the diagram when another note is opened concurrently on the side

### ISSUE THREAD

**Issue by Fierce-Ninja** [excalidraw/excalidraw#4014]
When I open a new note on the side while keeping the excalidraw pane open, the pane itself resizes but the contents inside are hidden as they don't resize.  Please let me know if I am overlooking something.  If not, this would be a very helpful feature to add!

**Comment by dwelle** [comment]
Hey. We do not maintain the Obsidian plugin, but you can post the issue in the tracker here: https://github.com/zsviczian/obsidian-excalidraw-plugin/issues
