### ISSUE TITLE
Template error: Active view is null, can't overwrite content

### ISSUE THREAD

**Issue by Fierce-Ninja** [excalidraw/excalidraw#4015]
Hi I am using the excalidraw plugin in Obsidian. When I try to select View mode, I get an error saying this - Template error: Active view is null, can't overwrite content. What may be wrong there?

**Comment by dwelle** [comment]
Hey. We do not maintain the Obsidian plugin, but you can post the issue in the tracker here: https://github.com/zsviczian/obsidian-excalidraw-plugin/issues
