### ISSUE TITLE
Image_support: taking a photo does not work on iPad, + image button gets stuck

### ISSUE THREAD

**Issue by zsviczian** [excalidraw/excalidraw#4019]
@dwelle, I did some testing with Image Element on my iPad. It works mostly well, except for two small issues which I can’t debug.

## 1) The image button gets stuck. 

If you tap it you are offered three choices (image library, take a photo, browse for a file), if instead of choosing one of the 3, you tap the canvas, you will first need to select one of the other tools before the choices popup will show again. 

## 2) Taking a photo does not work

The other issue is with taking a photo. You can take the photo, but the picture never arrives to Excalidraw.

——-

It is a bit hard to describe these, I recorded a short screen capture, which you can find here:
https://youtu.be/kbR3C9IgJpI

**Comment by zsviczian** [comment]
The latest test deployment resolves this issue.
https://excalidraw-hkkhvfoxm-excalidraw.vercel.app/

**Comment by dwelle** [comment]
@zsviczian Yeah, I'm wondering if the hack (https://github.com/excalidraw/excalidraw/pull/4011/commits/6b51b611c19430b8feaec88a471ea21cbf1cda02#diff-86963609bec6fda3d34233676d5ae33f6aa4b9bbe2758a10cd4863b704b37093R3997-R4021) is reliable though. I'll need to apply it to the import-excalidraw-from-file as well. Can you check on https://excalidraw.com on ipad or macbook if it works to import files reliably (you'll need to clear canvas between imports to be sure)? For me it's a hit and miss.
