### ISSUE TITLE
Import from OneNote (Excalidraw Obsidian plugin)

### ISSUE THREAD

**Issue by slimhk45** [excalidraw/excalidraw#4029]
Hi it would be amazing if there was a feature to import notes from Onenote into Excalidraw in Obsidian. This feature could make easier the transition to Excalidraw for a lot of people.

I’m a great supporter of your app (through it’s obsidian integration) and I don’t mind paying for it :)

**Comment by dwelle** [comment]
Hey! We do not maintain the Obsidian plugin, but you can post the issue in the tracker here: zsviczian/obsidian-excalidraw-plugin/issues

**Comment by MaelImhof** [comment]
If anyone was wondering like me if this suggestion had been reported to the indicated repository, [here it is](https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/1002).
