### ISSUE TITLE
Stroke width should be kept in the global state

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#404]
The same way we "save" the stroke color, we should also save the stroke width, and probably other things like font, font size... We should audit all the ones we have and make sure we use the same treatment.

**Comment by giovannigiordano** [comment]
I agree, maybe we should even add a reset to default button.

**Comment by lipis** [comment]
Reset to default when clearing the drawing.

**Comment by vjeux** [comment]
Someone fixed it :)
