### ISSUE TITLE
New Crowdin language: Tamil & Bengali

### ISSUE THREAD

**Issue by GobinathAL** [excalidraw/excalidraw#4066]
Hey, my native language Tamil(language code:ta) is not in Crowdin. Can it be added?

**Comment by appledora** [comment]
@dwelle I would like to add translation for BN-Bengali. Should I create a PR ?

**Comment by GobinathAL** [comment]
> @dwelle I would like to add translation for BN-Bengali. Should I create a PR ?

Look at the Readme file. You need to create an _issue_ and not a _PR_.

**Comment by lipis** [comment]
Added in #cro
