### ISSUE TITLE
Add more fonts

### ISSUE THREAD

**Issue by Shwetago** [excalidraw/excalidraw#4078]
Can we add more fonts? It only supports Cascadia and Virgil. Is there any specific reason? I would love to add more.

**Comment by srihari-sridharan-tw** [comment]
Shall we add the ability to use system fonts?

**Comment by hulkbig** [comment]
@Shwetago hi, you can try my fork version: [https://excalidraw-zh.com/](https://excalidraw-zh.com/)

**Comment by Mrazator** [comment]
We've recently introduced more fonts with https://github.com/excalidraw/excalidraw/pull/8012! Even more will be coming in the future.
