### ISSUE TITLE
An overlay of the shortcuts when pressing "?"

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw#408]
Like on GitHub, Gmail, etc..

[`docs/shortcuts.md`](https://github.com/excalidraw/excalidraw/blob/master/docs/shortcuts.md)

- [ ] Press `?` to show a modal dialog
- [ ] Create / Use a function to determine the OS (mac, windows, linux)
- [ ] Display shortcuts depending on OS

-----

<img width="1046" alt="Screenshot 2020-01-17 at 1 10 49 AM" src="https://user-images.githubusercontent.com/125676/72570688-37426680-38c6-11ea-8c16-fa65deed6ef3.png">

**Comment by giovannigiordano** [comment]
There is another issue for this #335 . Please, check if there is already an issue before opening another one.

**Comment by dwelle** [comment]
#335 is a different issue --- it's about displaying context-specific hints. While this issue is about displaying all available shortcuts.

**Comment by OrenMe** [comment]
I noticed that the way the keyboard shortcut definition is built makes it impossible to get the shortcuts in a declarative way.
A shortcut is defined in a function called keyTest and is defined as code.
Interface was defined in https://github.com/excalidraw/excalidraw/pull/298

We need to separate the key bindings registration and handler.
Currently there is a mix where the keyTest contains code that both declares the keys and adds a logic that can check the app state and other elements.
The only action that utilizes the app state is in the https://github.com/excalidraw/excalidraw/blob/master/src/actions/actionFinalize.tsx action.

If we can move it to the perform function and totally remove the appState and elements from the interface we can make this truly generic.
@GasimGasimzada I see you added the finalize action, can you please review the comment and share your thoughts?

**Comment by OrenMe** [comment]
And in general I don't clearly understand the keyTest condition in actionFinalize
https://github.com/excalidraw/excalidraw/blob/d39c7d442145ce7e7c09c000ea84f667929674ab/src/actions/actionFinalize.tsx#L40-L45

What is the difference between Escape key and both conditions and Escape or Enter and other condition?
It should be straight forward to define a key binding(one or more) without any conditions for when it should work and then let the handler do the conditional access to the operation.

**Comment by dwelle** [comment]
@OrenMe likely needs to be updated, but currently `KEYS.ENTER` applies only to multi-point elements, while `KEYS.ESCAPE` applies to any element other than when dragging it.

As for this issue, it'll likely require a more thorough rewrite of keyboard handling.

**Comment by vjeux** [comment]
While the idea of having this dialog to be autogenerated from code is good, I don’t believe that it’s going to provide the best user experience.

I would recommend implementing the dialog by hardcoding all the shortcuts and organizing them in a way that makes sense for a human.

Then, and only then, try to figure out if we can help reduce duplication.

We only have so many shortcuts that I’m not too worried about both getting out of sync and causing trouble.

**Comment by dwelle** [comment]
I thought the main idea behind autogenerating it so that we display only context-specific hotkeys. I.e., don't list `ESC to confirm shape` when `ESC` would e.g. cancel transformation etc. Thus, making the `?` hotkey show a list of hotkeys that a user use at that point in time.

**Comment by GasimGasimzada** [comment]
@OrenMe the idea in keyTest for actionFinalize is that, the “active behavior” will be finalized based on two conditions:

1. If element is not in multi-mode (e.g multi arrows), ESC will finalize the behavior
2. If element is in multi mode, ESC or ENTER will finalize the behavior.

—-

> It should be straight forward to define a key binding(one or more) without any conditions for when it should work and then let the handler do the conditional access to the operation.

So, by that logic, if a key is found, the action performer will decide whether to update the state or not, right?

@dwelle What do you think of this? I personally think that it will simplify the behavior. So, we modify the implementation for handling keys to return `false` if the action did not change the state. We will stop the “actions loop” only when the action changes the appState or elements.

**Comment by lipis** [comment]
Fixed in #1224

**Comment by mbj36** [comment]
@lipis should overlay be hidden by pressing `?` again ?

**Comment by dai-shi** [comment]
In my case, I pressed `ESC`. 😅

**Comment by lipis** [comment]
> @lipis should overlay be hidden by pressing `?` again ?

I think esc is ok.. no?

**Comment by mbj36** [comment]
Yeah i will make a PR

**Comment by lipis** [comment]
ESC to close any dialog

**Comment by lipis** [comment]
@mbj36 here you are https://github.com/excalidraw/excalidraw/issues/1236
