### ISSUE TITLE
[Language request] zh-HK: Traditional Chinese (Hong Kong)

### ISSUE THREAD

**Issue by lifehome** [excalidraw/excalidraw#4096]
Hello there,

I just ran over the internet to find alternatives of Miro and Milanotes, and it seems excalidraw fits my use case!

For that purpose, I would like to contribute and translate the application into zh-HK for more Hongkongers to use. :DD

My crowdin username is `lifehome`, and if possible please also grant me a proofreader permission, so that I can get the translation approved as soon as possible.

Thanks again for the amazing work!

-- Ivan

**Comment by lipis** [comment]
The label is updated.. https://github.com/excalidraw/excalidraw/pull/4150
