### ISSUE TITLE
Viewport incorrectly calculated in textWysiwyg

### ISSUE THREAD

**Issue by zsviczian** [excalidraw/excalidraw#4098]
I have a long text element. 
- In the first instance, the whole text fits the visible canvas area. When I edit everything works as expected.
- In the second instance, I position the text to the right, such that most of it does not fit the canvas. When I click to edit the text jumps to the right.
- In the third instance, I close the sidebar next to the canvas and push the text to the right so that it does not fit the canvas. When I click to edit the text jumps to the right but just a little. 

https://user-images.githubusercontent.com/14358394/138605762-e3be14ac-48b0-41fe-b562-8f95d53d9154.mp4

The size of the jump seems to be correlated with the zoom level:

https://user-images.githubusercontent.com/14358394/138606578-80d096c9-fc25-4dfd-8e29-3d6ac2175182.mp4

It seems to me there is some issue with the sceneCoordsToViewportCoords calculation... but I can't figure out what.

**Comment by tom-sherman** [comment]
I can't repro this even on the link you've sent. Has it been fixed do you think?

**Comment by ad1992** [comment]
closing this as it was fixed in https://github.com/excalidraw/excalidraw/pull/4630, please reopen if the issue exists
