### ISSUE TITLE
Keep tool active upon element creation

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#41]
Do not switch to the `selection` tool upon element insertion. I'd say common use case is to create several elements in a row. I don't know of any editor which changes the tool after each insertion. Thoughts?

**Comment by vjeux** [comment]
Both Powerpoint and Keynote ask you to re-click on the shape every time you want to add a new one. Same for zwibbler. Do you have an example that doesn't?

**Comment by dwelle** [comment]
Mhm, I haven't used those in some time. What I've had in mind are tools like Affinity Designer/Photo, or Photoshop (IIRC).

Either way, to me it seems unintuitive and not very useful. But let's keep this open and see what other users feel like.

**Comment by vjeux** [comment]
I don't really mind either way to be honest

**Comment by giovannigiordano** [comment]
As @vjeux as said in other comments, I think that for now is preferable to deliver new features and then optimize the existing ones.

**Comment by vjeux** [comment]
We now have the lock icon for this
