### ISSUE TITLE
Bug: Joining a collaboration whiteboard without other participants doesn't load images

### ISSUE THREAD

**Issue by cnollite** [excalidraw/excalidraw#4108]
Steps to reproduce the bug:
* Open a collaboration session
* Copy the link of the whiteboard
* Add an image to the whiteboard
* Close the collaboration session
* Close the tab
* Open the collaboration link in a new tab
* The whiteboard does not load the image

**Comment by dwelle** [comment]
I've deployed a couple of fixes but there may be other bugs related to this. Please comment/reopen if you encounter similar issue again!
