### ISSUE TITLE
Add Cascadia Code font instead of plain old Courier

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw#413]
https://github.com/microsoft/cascadia-code

It's fancier, popular, made by Microsoft, and it's OK for Private or Commercial use https://github.com/microsoft/cascadia-code/blob/master/LICENSE

**Comment by lipis** [comment]
![image](https://user-images.githubusercontent.com/125676/72578618-3538d180-38df-11ea-8fc8-f539d5fa0644.png)

**Comment by wuweiweiwu** [comment]
I'd love to pick this up if its not claimed!

**Comment by giovannigiordano** [comment]
@wuweiweiwu go for it!

**Comment by fernandoalava** [comment]
Hey! It would be nice to change the way that font is selected, perhaps using a select component thinking in the future there could be more cools fonts to add. If you think that could be a good feature I would be glad to help with that.

**Comment by vjeux** [comment]
@fernandoalava do you have concrete examples of which fonts you’d like to see supported and why?

The goal with excalidraw is to keep things with few options as possible to avoid the paradox of choice ( https://en.m.wikipedia.org/wiki/The_Paradox_of_Choice ). I want people to just draw rather than spending mental energy thinking what is the exact font they want to use

**Comment by vjeux** [comment]
What would be useful is to change the labels to why we are using those fonts rather than the font names.

- Hand-drawn
- Normal
- Code

Or something along those lines

**Comment by fernandoalava** [comment]
Hi @vjeux, No I don't have any useful example or real use cases to add more fonts. I saw this open issue and I thought that maybe could be good but yeah I understand your goal on this app. 
Yes make more sense change that 👍

**Comment by lipis** [comment]
Yes I also agree to keep it to 3 different fonts and changing the names.

**Comment by lipis** [comment]
I created a separate issue for that, to keep this PR strictly to changing the font: https://github.com/excalidraw/excalidraw/pull/462
