### ISSUE TITLE
Images don't load in macOS

### ISSUE THREAD

**Issue by pgilfernandez** [excalidraw/excalidraw#4154]
Trying to load an image into the canvas ends up with a "no size" image
<img width="64" alt="excalidraw" src="https://user-images.githubusercontent.com/5942369/139592618-58605ca1-75d2-4b75-8c3d-3728b57b78d0.png">
Trying to scale it makes it disappear... it seems it's not being loaded anyway.

I tried with all my browsers (Chrome, Firefox and Safari) with the same behavior. I'm under macOS 10.14.6.
I tried with a phone and there it worked fine =)

BTW, this feature is awesome, thanks!!

**Comment by shiosai** [comment]
Same in windows, any browser (even tried edge)

**Comment by dwelle** [comment]
When does this happen?

**Comment by dwelle** [comment]
Oh, it happens always now. Must be a recent regression.

**Comment by dwelle** [comment]
Thanks for the report. Fixed!
