### ISSUE TITLE
Firefox: text is vertically misaligned

### ISSUE THREAD

**Issue by bgrosse-midokura** [excalidraw/excalidraw#417]
![image](https://user-images.githubusercontent.com/48123182/72603279-05a6bb00-3919-11ea-9210-f79afa799038.png)
It seems the text-anchor or whatever is not quite right on firefox. Might be related to #153 from where I remember the text-anchor/vertical alignment working right at some point.

**Comment by dwelle** [comment]
Investigating, I couldn't repro this in any commit since #153. But I instead found out that this latest PR #416 completely breaks text display on FF:

![excalidraw_ff_text](https://user-images.githubusercontent.com/5153846/72613452-d3548800-392f-11ea-86fd-00ff0e13df95.gif)

**Comment by Fausto95** [comment]
Oh yeah, I just had the same issue and I could repro when the text ends with white spaces.
