### ISSUE TITLE
Background color isn't synced with the background color picker's color when hex is partial

### ISSUE THREAD

**Issue by gmertk** [excalidraw/excalidraw#418]
It is a bit of an edge case, but it is weird that picker doesn't match the actual background color.

![bg](https://user-images.githubusercontent.com/907281/72603768-8feb2100-3911-11ea-9641-c8ff72a35f6b.gif)

**Comment by abhikulshrestha22** [comment]
what should be the expected behavior when the values are incomplete?
so let's say the code is #ffff should it be considered as #ffff00 ?

**Comment by gmertk** [comment]
That is an option. Another option could be to prefix zeros. One special case though: if it is 3 digits, it should double each digit. #57D becomes #5577DD.
No matter which option we go for, we need to make sure that the picker and background color match with each other.

**Comment by lipis** [comment]
this should be fixed now
