### ISSUE TITLE
Text rendering broken

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#419]
It seems that #416 completely breaks text rendering in all browsers:

![excalidraw_ff_text](https://user-images.githubusercontent.com/5153846/72613452-d3548800-392f-11ea-86fd-00ff0e13df95.gif)

/cc @nanot1m

**Comment by nanot1m** [comment]
I'll revert PR

**Comment by dwelle** [comment]
I'll probably cause this as it'd not be reproducible anymore. We just need to keep this in mind when you make another go at it.

**Comment by dwelle** [comment]
Umm.. maybe I've made a mistake in determining which commit caused this, because the reversal didn't help....

**Comment by dwelle** [comment]
Ok, it's this commit https://github.com/excalidraw/excalidraw/commit/e5e0e37f23ab4ec6126431161e760e1c3c3456ec#comments

I swear I checked that one and it seemed to work. My bad. Do you think we can maybe `push --force` to remove the reversal, or is that a no go? Sorry again :(
