### ISSUE TITLE
When pasting SVG images, Virgil font is not being used

### ISSUE THREAD

**Issue by OliverEberlei** [excalidraw/excalidraw#4190]
My first issue :). I just found this project and it is wonderful. Thank you so much for your work :)

While experimenting with a bunch of hacky ways to get data from my app into excalidraw, I came across this:

I am trying to paste a SVG into excalidraw which contains a bunch of text. I've prepared the file to use the font-family "Virgil", but no matter how I reference that font in the SVG file, the text always shows up without a font. This is probably not intended.

This is the SVG I am pasting into excalidraw:
```
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 viewBox="0 0 512 72" style="enable-background:new 0 0 512 72;" xml:space="preserve">
<style type="text/css">
	.st0{font-family:'Virgil';}
	.st1{font-size:36.0932px;}
</style>
<text transform="matrix(1 0 0 1 34.2061 45.1016)" class="st0 st1">Test SVG with Virgil Font</text>
</svg>
```

And it shows up like this:
![image](https://user-images.githubusercontent.com/1569926/139874111-1b87df67-15fd-4c99-b679-c824bf914b2f.png)

The same happens when I ```select a text in excalidraw -> right-click -> "Copy to clipboard as SVG". ```
When I then remove the ```<!-- svg-source:excalidraw -->``` Tag and paste this SVG back into excalidraw, it doesn't show up with the font.

**Comment by cmorty** [comment]
This is probably cause by https://github.com/excalidraw/virgil/issues/61

**Comment by Mrazator** [comment]
We've fixed this recently with (https://github.com/excalidraw/excalidraw/pull/8012).
