### ISSUE TITLE
I hope to add URLs to the text

### ISSUE THREAD

**Issue by ottopan** [excalidraw/excalidraw#4197]
![image](https://user-images.githubusercontent.com/18224971/140247012-132413d1-6280-4d59-b768-f8c5381f4244.png)

An idea
I hope you can add the link attribute to the text, both to link different EX documents and to jump to external links
Hope to see the creator's idea

**Comment by ad1992** [comment]
Hey thats definitely in the roadmap https://github.com/excalidraw/excalidraw/issues/1205

**Comment by ad1992** [comment]
closing in favour of #1205
