### ISSUE TITLE
Pen Input

### ISSUE THREAD

**Issue by peteole** [excalidraw/excalidraw#4199]
Hi, I just discovered excalidraw and find it pretty amazing.

One of the main use cases for me is quickly sketching something on my tablet (and I assume this must be a pretty common use case due to the rise of tablets for remote learning in the pandemic).

Now a pretty cool feature would be to introduce a "pen mode": In this mode, drawing input would only be accepted from a pen (which can be decided from the [PointerEvent.pointerType property](https://developer.mozilla.org/en-US/docs/Web/API/PointerEvent/pointerType) ). Like this one could safely place the hand on the tablet without drawing random lines or use the fingers exclusively to move the view.

To take this even further, one cloud determine the [button states](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events#determining_button_states) to use the pen as an eraser, which is a huge timesaver.

What do you think about it?

**Comment by melsophos** [comment]
I agree that this would be very useful!

**Comment by dwelle** [comment]
I've created a separate issue for pen mode/palm rejection https://github.com/excalidraw/excalidraw/issues/4202

> To take this even further, one cloud determine the [button states](https://developer.mozilla.org/en-US/docs/Web/API/Pointer_events#determining_button_states) to use the pen as an eraser, which is a huge timesaver.

The hard problem is adding support for erasing, which would not be easy for either the free draw tool nor other tools. For free draw a path may be opened once the new perfect-freehand library currently in development is released.

The tracking issue for freedraw eraser is here: https://github.com/excalidraw/excalidraw/issues/3682
