### ISSUE TITLE
Pen mode (palm rejection)

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#4202]
When `freedraw`ing with a `pen` `pointerType`, we should switch to a pen mode:

1. display a pen-mode button indicating we're in pen mode
2. reject `touch` events (including on UI) until the pen-mode button is clicked (probably require non-`touch` event as well) which will exit the pen-mode

**Comment by melsophos** [comment]
The original request #4199 mentioned using fingers to move the view (pan). For example, if `freedraw` is selected, it would be convenient to use one finger to pan, and two for zooming.

**Comment by dwelle** [comment]
Can we reliably differentiate between fingers and palms?

**Comment by melsophos** [comment]
A naive guess would be that palm / knuckles should be: 1) localized (happen all around a central point where the hand started to touch the screen), 2) erratic (it does not go in a single direction), 3) not immediate after touching but kind of continuous. So a (too?) simple heuristic would be to ignore the first point of contact, and also all movements around that zone if there is not a clear break (in time and distance). The latter condition would mean that one is removing the hand to start touching with a finger.

**Comment by dwelle** [comment]
fixed via #4532 

https://twitter.com/excalidraw/status/1488884968243740674
