### ISSUE TITLE
Support for "anchors"

### ISSUE THREAD

**Issue by FPierre** [excalidraw/excalidraw#4228]
My Excalidraw documents are often quite large and it is sometimes difficult to find a piece of information.

It would be nice to have an anchoring system that allows to:
- create a static point (a.ka. anchor itself) in the document (X, Y position of the cursor?)
- name it and list it somewhere
- when the anchor name is clicked in the list, the cursor jumps on the corresponding X, Y position

Thanks

**Comment by dwelle** [comment]
Duplicate of https://github.com/excalidraw/excalidraw/issues/3276 (via https://github.com/excalidraw/excalidraw/issues/1205)?

**Comment by FPierre** [comment]
💯 agreed, I close this issue
