### ISSUE TITLE
image cropping

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#4236]
Support cropping images, either before or after importing them onto canvas.

Suggested via chat (and I believe someone on twitter did as well).

Could be part of image post-processing support (https://github.com/excalidraw/excalidraw/issues/4235)

**Comment by dimateos** [comment]
This would be really useful.

* I usually paste a lot of screenshot clips or varied photos in quick succesion for reference.
* Then procede to edit/note them and I wish I could just crop a bit better some borders.
* Right know I have to screenshot and clip it again and it may lose some of the original quality.

**Comment by jwdinkel** [comment]
![CleanShot 2023-01-29 at 07 37 24](https://user-images.githubusercontent.com/7911734/215309605-ec2f2409-c936-45f0-b078-de0f9540633e.png)

I'd like to understand if there's a way to make the images pasted into Excalidra crisp like on miro.com.

I find the images rather fuzzy and the text is not crisp.

For the example above, I pasted the same image from my clipboard into miro on the left and Excalidraw on the right. This is inside Obsidian on a mac M1. New installation.

The difference is very vislble at this zoom level, but even at 1:1 it looks too fuzzy for my liking on Excalidraw.

Hope it's just a setting, if it's deeper, I hope it can be fixed.

I saw the same issue on reddit without an answer: https://www.reddit.com/r/ObsidianMD/comments/xsedlz/excalidraw_imported_images_are_blurry/

I have not read all the details here yet:
https://github.com/excalidraw/excalidraw/pull/4011

Apologies, this is day 2 of my journey with Excalidraw and Obsidian. Never used either before...
So please bear with me while I learn and complain and repeat..
Thank you.

**Comment by ctwhome** [comment]
Cropping images would be the perfect addition, manipulating screenshots outside makes it cumbersome. Google slides or Figma convert the resizing points into lines when cropping is activated: 
<img width="627" alt="image" src="https://user-images.githubusercontent.com/4195550/226111156-597bfd29-b238-41e4-91df-df6070a53ad4.png">

**Comment by karlhorky** [comment]
> I'd like to understand if there's a way to make the images pasted into Excalidra crisp like on miro.com.
> 
> I find the images rather fuzzy and the text is not crisp.

@jwdinkel Would you copy your comment above and report this in a separate issue? (this issue is about cropping, not about general image quality problems). Feel free to use my image / words below as well.

---

I have also noticed this phenomenon of quality loss of images and color shift when uploaded to Excalidraw. Eg. check out this PNG screenshot of GitHub and the same image when it is inserted into Excalidraw:

![Screenshot 2023-04-19 at 15 09 11](https://user-images.githubusercontent.com/1935696/233085074-7641dd55-f413-4da5-a47a-47f28d6eff65.png)

**Comment by dwelle** [comment]
The images are being compressed. We can try improve the compression, as well as increasing the size limits. But let's open a new issue for this and keep this one just to image cropping 🙏

**Comment by wbm1113** [comment]
I have this crudely working:

![image](https://user-images.githubusercontent.com/46951987/233766437-8e7889ba-73ab-4dcb-b9ca-fde4b35888b2.png)

What would be the best way to access the feature?  My best thought was to hijack resizing; if you're holding ALT and you click the resize handles, it'll crop instead.  Something about that approach smells bad, but I don't know what.

renderElement.drawElementOnCanvas also needs the original dimensions of the canvas before the crop started, as well as the cropped ratios (i.e. what percentage of the image you have cropped).  I'd assume we would have to keep that in the ExcalidrawImageElement and mutate it in the crop event handler (similar to the resize functionality).  Unless there's a better solution?

**Comment by dwelle** [comment]
> My best thought was to hijack resizing; if you're holding ALT and you click the resize handles, it'll crop instead.

No, we shouldn't change the behavior of Alt. Besides it's not intuitive nor discoverable. We'll just put a button in the properties sidebar when the image is selected. It should enter a crop editor, similar to Figma's image crop editor.

> renderElement.drawElementOnCanvas also needs the original dimensions of the canvas before the crop started, as well as the cropped ratios (i.e. what percentage of the image you have cropped). I'd assume we would have to keep that in the ExcalidrawImageElement and mutate it in the crop event handler (similar to the resize functionality). Unless there's a better solution?

Yes, we should keep the original image data intact, and probably use a clip mask for rendering. We can't modify or duplicate the imageData because a single image can be shared by multiple elements on scene using different crops.

For the `excalidrawImageElement` (in the `elements` array) itself, we'll store a `croppedSize: [xOffset, yOffset, width, height]` or something like that.

**Comment by karlhorky** [comment]
> @karlhorky in [comment 1514711934](https://github.com/excalidraw/excalidraw/issues/4236#issuecomment-1514711934): I have also noticed this phenomenon of quality loss of images (and also color shift)

Ah it appears the color shift issue (with dark mode) also has some explanation over here (although the author @anatoliibakhtin is actually reporting a different issue):

- https://github.com/excalidraw/excalidraw/issues/5312

It is apparently caused by the color inversion:

> @dwelle in [comment 1157697888](https://github.com/excalidraw/excalidraw/issues/5312#issuecomment-1157697888): we invert the colors using CSS, and then individually apply a counter filter on image elements

Also mentioned in #4616:

> @dwelle in [comment ](https://github.com/excalidraw/excalidraw/issues/4616#issuecomment-1250112100): Not something we do by choice, but due to how our dark mode works right now.
> 
> I assume you're using Safari? On other browsers that support canvas filters we selectively invert the images back (the double invert isn't 100% accurate, but for now it seems serviceable).

So I opened 2 issues:

- https://github.com/excalidraw/excalidraw/issues/6516
- https://github.com/excalidraw/excalidraw/issues/6515

**Comment by wbm1113** [comment]
I opened https://github.com/excalidraw/excalidraw/pull/6517 for this.

**Comment by wbm1113** [comment]
Pardon my inexperience, but I think the PR is ready for review.  I expected to see a button I could click to indicate that, or at least finish the testing steps, but I have no such option:

![image](https://user-images.githubusercontent.com/46951987/234862719-b6aabf77-9214-4590-abeb-0d022f8db6a4.png)

**Comment by namdao2000** [comment]
Would love this feature 🙏🏻

**Comment by dhruv-anand-aintech** [comment]
+1 for this feature

**Comment by accoumar12** [comment]
+1, would be really nice

**Comment by pickaxe828** [comment]
+1 for this feature

**Comment by mbrg** [comment]
+1

**Comment by dempstert** [comment]
+1

**Comment by farizazmip** [comment]
+1, it's a nice-to-have feature!

**Comment by somritabanerjee** [comment]
+1 for the cropping image feature!

**Comment by fourteen-1** [comment]
+1

**Comment by AMTQ** [comment]
+1

**Comment by quinn-p-mchugh** [comment]
+1

**Comment by vjanandr** [comment]
+1 is this feature available ?

**Comment by oubaydos** [comment]
+1

**Comment by kevinlinxc** [comment]
Cropping is the only thing stopping me from using excalidraw for everything

**Comment by knamnguyen** [comment]
Please!

**Comment by ctwhome** [comment]
I didn't know tldraw had that feature. In my opinion, they handle it the way it should be.

**Comment by MFredX** [comment]
This would be a great feature to have, hope the team can make this happen.

**Comment by jeanineharb** [comment]
+1

**Comment by MichaMican** [comment]
+1

**Comment by 726f6f6b** [comment]
+1

**Comment by MFredX** [comment]
I see that this feature has been released. We should be good to close this issue.
To see right click on a selected image and select 'Crop Image' for the options

**Comment by dwelle** [comment]
fixed via https://github.com/excalidraw/excalidraw/pull/8613

**Comment by karlhorky** [comment]
@ryan-di @dwelle thanks for #8613 🎉
