### ISSUE TITLE
Feature Discoverability Suggestion: In export dialog add tooltip/description of what "Embed Scene" means

### ISSUE THREAD

**Issue by verginer** [excalidraw/excalidraw#4237]
Loving the product!

I have a UX improvement suggestion, to make a killer feature of excalidraw more easily discoverable.
The ability to embed the scene into the png and then edit it again in the future, I think awesome, and one of those features that until you know it exists, you didn't know you needed.

I have exported plenty of figs, always keeping a separate `.excalidraw` file, just in case (obviously they get lost).
I saws the "embed scene" checkbox, but did not really understand it's purpose.

I think users will be fare more likely to use it if it had a more descriptive name or just a tooltip ℹ️ box or something.

**Comment by dwelle** [comment]
I agree, and I believe it was discussed once. I don't recall what were the suggestions for different names. Do you have some?


> just a tooltip ℹ️ box or something.

How would that differ from the `?` tooltip, apart from the icon change?

![image](https://user-images.githubusercontent.com/5153846/141282302-559bbdd9-7de1-4ea0-ba13-92c3f88be677.png)

**Comment by verginer** [comment]
This is exactly what I meant! I wouldn't change a thing. But it is the first time I see this tooltip.

I attach the view I get. I use Safari on https://excalidraw.com.

![Screenshot 2021-11-11 at 11 34 25](https://user-images.githubusercontent.com/1024636/141283477-b1ea582d-3e4c-43e0-a53b-424ed73b3e00.png)
