### ISSUE TITLE
[Feature Request] default attached text

### ISSUE THREAD

**Issue by orgalaf** [excalidraw/excalidraw#4239]
When I create text inside a shape in most cases I'd expect it to be attached to the shape.

**Comment by dwelle** [comment]
We're working on a way that when you hit `enter` while a rectangle is selected, or when you double-click in the center of it, it'll attach the text to that element, ad constraint it so it doesn't overflow the container, effectively making it into a "sticky note": https://github.com/excalidraw/excalidraw/issues/4270

**Comment by ad1992** [comment]
closing this as we support binding text to shapes now https://twitter.com/aakansha1216/status/1471509326674030592
