### ISSUE TITLE
[Feature Request] save colors in the colors palette

### ISSUE THREAD

**Issue by orgalaf** [excalidraw/excalidraw#4240]
When I add a new non default color, save it to the palette for easy reuse.

**Comment by inwardmovement** [comment]
It would be great to be able to customize the color palette.

**Comment by Elaws** [comment]
Hello,

Are there some news for that FR ?

Thanks !

**Comment by ad1992** [comment]
Yep its coming soon 🚀

**Comment by Elaws** [comment]
Thanks for your reply @ad1992, it's a great news :)

**Comment by ad1992** [comment]
closed via https://github.com/excalidraw/excalidraw/pull/4843
