### ISSUE TITLE
Property window should have permanent screen space

### ISSUE THREAD

**Issue by shaperilio** [excalidraw/excalidraw#4265]
![4266641d-683a-42e7-ab0d-10d1cbf74554](https://user-images.githubusercontent.com/26465923/142287219-901d4c41-775b-4b7c-a370-57b453565590.gif)

With Excalidraw +, the workspace sidebar has permanent space on the screen: that is, hiding it scrolls the canvas to the left, and expanding it, to the right.

The property window appears on top of the canvas. This can get cumbersome because, with an infinite canvas, it's easy to end up selecting an element which is right where the property window will appear, thus hiding the very element you're trying to modify.

The property window should be "docked" or its appearance should scroll the canvas just like the sidebar does.

**Comment by shaperilio** [comment]
See also #2191

**Comment by ad1992** [comment]
Yes we should definitely do something about this, since we already have an issue opened for this, hence closing this in favor of #2191
