### ISSUE TITLE
Rhombus shape should allow rounded corners

### ISSUE THREAD

**Issue by shaperilio** [excalidraw/excalidraw#4266]
The rectangle shape has this option, and I make rectangles and then rotate them ~45 to get rounded rhombi...

**Comment by ad1992** [comment]
Sure we can have the same option for rhombus as well

**Comment by jai-dewani** [comment]
I would like to give this a try

**Comment by jai-dewani** [comment]
Just to confirm @shaperilio, by Rhombus you mean diamond?

![Web capture_3-12-2021_13158_excalidraw com](https://user-images.githubusercontent.com/33520257/144564670-75a3a609-ce8b-4eba-8b55-cb930255c0e1.jpeg)

**Comment by shaperilio** [comment]
Yup, that's the one!

**Comment by jai-dewani** [comment]
Hey @ad1992 @dwelle, 
I am able to render rounded diamonds and now just need display options to the user to chose form round or straight corner.
I am having trouble finding the exact code section from where I could do this, could you guide me on this part? 

![image](https://user-images.githubusercontent.com/33520257/144751314-c3db3f31-865f-4f19-883c-291f5a5c3d39.png)

**Comment by dwelle** [comment]
@jai-dewani hey. Adding it to this list should do the trick:

https://github.com/excalidraw/excalidraw/blob/618f204dddd7b6309d10efa8b9227c71e11c99e7/src/scene/comparisons.ts#L31-L32
