### ISSUE TITLE
Text area tool

### ISSUE THREAD

**Issue by shaperilio** [excalidraw/excalidraw#4267]
It would be nice to have a text area tool, that is, draw a rectangle within which text auto-wraps.

It could perhaps replace the current text tool:
1. Double-click to start typing. This creates an auto-sizing text box (current functionality)
2. Deselect. This locks box size.
3. Further editing that box will attempt to wrap.

Click and dragging instead of double-click would create a fixed box size with wrapping from the get-go.

An indicator at the bottom right would show that text is overflowing the boundaries. Double-clicking on it would auto-size the height of the box, keeping the width the same.

The only sticky point is dragging the size handles. That currently scales the text as a graphic; in this mode, it should rescale the area the text is allowed to flow into.

**Comment by ad1992** [comment]
closing this as we support binding text to shapes now https://twitter.com/aakansha1216/status/1471509326674030592

**Comment by dwelle** [comment]
Text area (bounding box) is something which is separate from container-bound text, and we want to support this. The only thing to figure out is how it should behave.

- Figma allows you to draw a rectangle bounding box, but the height is not constrained at all (it overflows the bounding box).
- Miro allows you draw a "linear" single-line bounding box, and the box autogrows as you type (basically the same behavior as we have right now with container-bound text).

Figma and Miro approaches above are effectively identical except in UX.

**Comment by tom-sherman** [comment]
https://twitter.com/steveruizok/status/1524670756117958656

**Comment by jwdinkel** [comment]
Will this allow us to drag the rectangle tool also to adjust the width?

Currently I have to drag the corner, but this changes the height and I only want to extend the width without adjusting the height. (Same can be said of changing vertical dimensions).
