### ISSUE TITLE
export to PNG/SVG not working on Chrome or Vivaldi

### ISSUE THREAD

**Issue by vrischmann** [excalidraw/excalidraw#4271]
Hi,

since a couple weeks ago I would say, exporting a scene to a PNG or SVG doesn't work anymore.

When I click the PNG or SVG button nothing happens. I checked the developer console, there's no log. There are also no network requests happening.

I'm on Fedora Linux 35, with Cinammon; I tested the following Chrome based browsers:
* Chrome stable 96.0.4664.45
* Vivaldi stable 4.3.2439.65 
I tested with Excalidraw and Excalidraw Plus if that makes any difference.

Note that exporting works on Firefox 94 on the same laptop.

Let me know if you want me to test anything.

**Comment by ad1992** [comment]
@vrischmann there won't be any network request for this as its done on client side, could you share a video with the exact same steps ?

**Comment by vrischmann** [comment]
Here's a video showing the problem.

https://user-images.githubusercontent.com/1916079/142457678-d07071fd-0250-46ae-8447-7d96587c6dc6.mp4

**Comment by dwelle** [comment]
This is strange. Can you try reproducing in Incognito mode to ensure it's not an extension or something causing it?

It's surprising that both Vivaldi and Chrome doesn't work. This suggests a Chromium issue with the new filesystem API.

To eliminate this being a different Chromium issue, you can trying the export in the Brave browser (https://brave.com/) — they're using Chromium as well, but they're not using the new filesystem API.

If it works in Brave, then I'd also try the Edge browser (the Beta channel should work on Linux as well https://www.microsoftedgeinsider.com/en-us/download?platform=linux-deb) — they 're on Chromium _and_ using the new filesystem API.

Sorry for making you do all this stuff, but I'm not sure how else to narrow down. That said, I'm not even sure what we'd do next, but at least we'd have a better idea of the cause.

**Comment by vrischmann** [comment]
I can confirm that it works in Brave.
I can also confirm that it doesn't work in Incognito and neither in Edge.

**Comment by dwelle** [comment]
Hmm, so it seems related to the new filesystem API. I cannot reproduce on Windows nor Mac, so it may be related to Linux (possibly just to your Fedora distro).

@tomayac is there anything known related to this? I've skimmed crbug tracker but didn't find anything. Thanks!

**Comment by tomayac** [comment]
It sounds very much like https://crbug.com/1264708.

**Comment by dwelle** [comment]
@tomayac Thanks! I lived under the impression we're already logging abort errors to console. Made a PR to add this https://github.com/excalidraw/excalidraw/pull/4279. 

@vrischmann the above is only for debugging purposes, and won't help fix this issue, though. @tomayac would you suggest for us to catch AbortErrors and on Linux display the error with an alternative way to save the file (using the legacy API)?

To ensure this isn't just related to Excalidraw, can you check whether it works on https://browser-fs-access.glitch.me? Thanks!

One other question: does opening (importing) excalidraw files (or images) work?

**Comment by tomayac** [comment]
> @tomayac Thanks! I lived under the impression we're already logging abort errors to console. Made a PR to add this #4279.

LGTM'ed.

> @tomayac would you suggest for us to catch AbortErrors and on Linux display the error with an alternative way to save the file (using the legacy API)? Or maybe use legacy API on Linux altogether.

I believe while this bug exists, routing Linux to the legacy API is the (unfortunate) way to go. This will probably require some ugly dynamic `import()`-ing based on user agent sniffing. Checking for `AbortError` probably won't work reliably since your only way tp distinguish from legitimate `AbortError`s would be to time them to see if possibly a human could have canceled the dialog so quickly…

> To ensure this isn't just related to Excalidraw, can you check whether it works on https://browser-fs-access.glitch.me? Thanks!
> 
> One other question: does opening (importing) excalidraw files (or images) work?

Also curious to learn about the replies to the last two questions above.

**Comment by dwelle** [comment]
I virtualized Fedora. What doesn't work is exporting to PNG/SVG (as OP reports). Saving to `.excalidraw` or loading from it, as well as importing images, works fine.

**Comment by vrischmann** [comment]
> @vrischmann To ensure this isn't just related to Excalidraw, can you check whether it works on https://browser-fs-access.glitch.me? Thanks!
> 
> One other question: does opening (importing) excalidraw files (or images) work?

Exporting/Importing excalidraw files works fine.

On https://browser-fs-access.glitch.me, when I click on the buttons showed in @dwelle's screenshot I get an error on stdout from Vivaldi:
```
[32213:32239:1119/135358.507368:ERROR:select_file_dialog_impl_portal.cc(699)] Portal returned error: org.freedesktop.portal.Error.InvalidArgument: invalid filter: name is empty
```

**Comment by dwelle** [comment]
Hold the fort. It has nothing to do with MIME types. It just needs `opts.description`.

**Comment by dwelle** [comment]
@vrischmann also deployed to Excalidraw Plus. Thanks for reporting!

**Comment by vrischmann** [comment]
Nice, thanks a lot for the quick fix ! Another reason to love Excalidraw :)
