### ISSUE TITLE
Request to translate the application into Basque.

### ISSUE THREAD

**Issue by alexgabi** [excalidraw/excalidraw#4273]
I would like to translate the application into Basque and I ask you to open the possibility at crowdin.com

**Comment by lipis** [comment]
How do you say Basque in Basque?

**Comment by lipis** [comment]
https://crowdin.com/translate/excalidraw/10/en-eu

**Comment by lipis** [comment]
Euskara (according to google translate)

**Comment by alexgabi** [comment]
Yes. Euskara. Ok
