### ISSUE TITLE
Question: How do you create a semi-circle?

### ISSUE THREAD

**Issue by filipallberg** [excalidraw/excalidraw#4278]
How do you do this? I can't find there to be any way to "intersect" paths which is a common way to do it in other software, i.e. create a circle and a rectangle and subtract the rectangle from one half of the circle. Or through editing the bezier curve.

**Comment by dwelle** [comment]
Right now you have to get creative. Such as creating a circle, and then trace it with the line tool:

https://excalidraw.com/#json=oQIQuZznSLIayZsxlbl1n,1HBJaQDXLToWOtEtv3QEug

![circle_semicircle](https://user-images.githubusercontent.com/5153846/142599854-98d648e7-34a4-486f-a6e2-d2621ae8f7c9.gif)

**Comment by MrAnimaniac** [comment]
So as I was looking for this recently and this was the first thing I found. As the above solution is quite cumbersome, I want to update on this:
Excalidraw has a plug in called [Split Ellipse](https://github.com/zsviczian/obsidian-excalidraw-plugin/blob/master/ea-scripts/Split%20Ellipse.md?plain=1). You can use this to split a circle in half. This converts the ellipse into two lines. Note, the residual half circles are closed. But it is easy enough to grab the endpoint of the half circle and move it.

**Comment by zacharykeeton** [comment]
Or just draw a circle, then draw a white rectangle over half of it and group them.
