### ISSUE TITLE
Bug: choosing a tool while dragging the selection

### ISSUE THREAD

**Issue by frantic** [excalidraw/excalidraw#429]
1. Start selection
2. Press `R` for rectangle tool
3. Release the selection

Result: the selection rectangle stay on the scene without a way to remove it

![2020-01-17 10 40 19](https://user-images.githubusercontent.com/192222/72637411-1b66b100-3916-11ea-84d6-d958e9bd8d46.gif)

![image](https://user-images.githubusercontent.com/192222/72637474-4bae4f80-3916-11ea-9a8e-cf7cd2e2a040.png)

**Comment by vjeux** [comment]
Great catch!
