### ISSUE TITLE
process.env.REACT_APP_LIBRARY_BACKEND

### ISSUE THREAD

**Issue by zsviczian** [excalidraw/excalidraw#4300]
Publishing libraries from Excalidraw directly is a very useful new feature. I debugged excalidraw.com and found the value for process.env.REACT_APP_LIBRARY_BACKEND. I set the same in the Obsidian deployment, and the submission process worked. 
https://github.com/excalidraw/excalidraw-libraries/pull/272

My current solution, however, is a bit of a hack. Would be nice if by default Excalidraw would publish to the public library (i.e. the default value for BACKEND would be included in constants.

**Comment by dwelle** [comment]
I'm not quite sure what you're proposing, but until today we haven't been properly inlining ENV variables (https://github.com/excalidraw/excalidraw/pull/4311) which resulting in libraries not working in the npm package. So maybe that's what you meant?

**Comment by zsviczian** [comment]
#4311 resolves this. Thank you.
