### ISSUE TITLE
Possibility to use scene in iframes/website

### ISSUE THREAD

**Issue by tdeuling** [excalidraw/excalidraw#4308]
Is there a possibility to insert scenes directly into a documentation website, for example have flow chart in our documentation page and when I update the scene on excalidraw, it will update the documentations view as well. This could be a link to the svg or png embeded as image, or even the scene as iframe.

Is that somehow already possible? When it's not possible yet, this would be a great feature!

**Comment by herrstucki** [comment]
I also wondered, since Notion seems to "support" embedding Excalidraw scenes. It doesn't really work though for reasons that were already described in #2706

**Comment by ad1992** [comment]
@tdeuling embedding shareable links via iframe should work, have you tried that ? however the shareable links are immutable so once created you can't update the drawing, you will have to generate a new shareable link each time you update the drawing.

**Comment by herrstucki** [comment]
@ad1992 as described in #2706 they don’t. Maybe because Excalidraw wants to open a confirmation dialog which doesn’t work in an iframe (at least not in Chrome)

**Comment by ad1992** [comment]
> @ad1992 as described in #2706 they don’t. Maybe because Excalidraw wants to open a confirmation dialog which doesn’t work in an iframe (at least not in Chrome)

Thats a different use case, as mentioned once you generate shareable link you will not be be able to update the drawing in that link, but using that link in iframe should work, here is an [example](https://znsy3.csb.app/)

**Comment by tdeuling** [comment]
Thanks for your reply.
Target is to get a self updating embed, so that we're able to work in a team on a flow chart. The embed should not be editable, because it's in a public scope. Thus would us enable to keep others up-to-date without publishing the file after each change.
When that's not possible, we need to go the manual way :(

**Comment by 7flash** [comment]
Embedded self-updatable dynamic elements can be called "Meta Elements" https://github.com/excalidraw/excalidraw/issues/5684

**Comment by ShravanSunder** [comment]
related to https://github.com/excalidraw/excalidraw/issues/7097
embedding room share links in frames doesn't work atm

**Comment by dwelle** [comment]
We currently don't have plans to enable embedding live collab links into 3rd party websites. To collaborate freely, you can use excalidraw.com collab rooms directly.
