### ISSUE TITLE
Can't export as read only link

### ISSUE THREAD

**Issue by KurtJot** [excalidraw/excalidraw#4310]
Can't export my drawing as read only link https://excalidraw.com/#room=40ad746e3077927cab47,e8IMJopnJPwyVH4D1Rdf0Q
System gives "Couldn't create shareable link." error message

is it because my drawing file is about 2mb?

**Comment by dwelle** [comment]
Yes. Stay tuned, we'll ship compression support today which will greatly increase the size of files you can export as links.

**Comment by dwelle** [comment]
Deployed. Enjoy!

**Comment by KurtJot** [comment]
Hi Dwelle,

Thanks for checking but the issue still persists.
Just tried and it says  "Couldn't create shareable link."

**Comment by dwelle** [comment]
It's very likely you're still on the old version. Make sure all other excalidraw.com tabs are closed — then it should refresh to the new version. If it doesn't, try refreshing yourself, and if _that_ doesn't work, you can hard-refresh (Control-Fn-F5 on Mac or Ctrl-F5 on Windows).

The stats for nerds should show:

![image](https://user-images.githubusercontent.com/5153846/143266277-4f6fa6c1-196c-47e6-84ed-3144fe4d8fef.png)

(the date may be later than 2021-11-24T13:45:13Z if we do another release)

**Comment by KurtJot** [comment]
Thanks Dwelle, all good now!
