### ISSUE TITLE
Excalidraw showing enormous button

### ISSUE THREAD

**Issue by Gunnersonthego** [excalidraw/excalidraw#4317]
![Uploading Screen Shot 2021-11-25 at 15.53.55.png…]()

After refreshing the page still having an issue on Excalidraw, it shows enormous button. Please help if you have known any solution on this case.

Have not tried to delete cookies and history as I don't want to lose the history of work in my google chrome browser.

**Comment by dwelle** [comment]
closing in favor of https://github.com/excalidraw/excalidraw/issues/4318
