### ISSUE TITLE
Arrows shouldn't bind to shapes outside their group

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#4324]
Below, the red rectangle and the arrow are grouped together:

![excal_bug_arrow_groups_binding](https://user-images.githubusercontent.com/5153846/143610534-9302ef43-8eae-4032-b347-ad5ce44a94f6.gif)

**Comment by prajwal0024** [comment]
If you don't mind, I would like to try to work on this issue.
@dwelle @ad1992

**Comment by ad1992** [comment]
Sure go for it 🎉

**Comment by prajwal0024** [comment]
Just to make sure, I will have to fix vice versa case also right?

![arrow](https://user-images.githubusercontent.com/43070174/147355867-7ae391fd-a6d3-4016-8e37-13d0edfb2022.gif)

**Comment by dwelle** [comment]
> Just to make sure, I will have to fix vice versa case also right?

Unclear how it should behave if you selectively move an arrow (or its end point as you do above) that's inside a group, but I'd at least not bind nested arrows when you move the group as a whole.

**Comment by prajwal0024** [comment]
Okay Thanks @dwelle, got it. So will try to avoid something like this.

![nested_arrow](https://user-images.githubusercontent.com/43070174/147362622-639dfc39-7045-4dfc-a17d-ac90194e986a.gif)

**Comment by dwelle** [comment]
> Okay Thanks @dwelle, got it. So will try to avoid something like this.

yes 👍

**Comment by smyrman** [comment]
I raised an alternate suggestion. I have yet to experience arrow bindings _in general_ saving me more time than it costs me. Maybe it would be both better and easier to just remove the feature entirely?

**Comment by sjoelee** [comment]
Hi, is this still being worked on? If not, I'd like to pick it up.

**Comment by ad1992** [comment]
@sjoelee sure go for it

**Comment by sjoelee** [comment]
Suppose we have an arrow that belongs to a group, but we're only editing the arrow. That arrow should be allowed to bind to another element, right? 
![Kapture 2023-08-03 at 09 21 10](https://github.com/excalidraw/excalidraw/assets/1409392/8fb512aa-d97b-4a0a-99b2-8fa1dbb345d7)

**Comment by ad1992** [comment]
@sjoelee yes your understanding is correct so you can implement with it, however once PR is ready we might tweak the behaviour for case (2) as I am not sure yet which whether we should allow binding since its inside the group so we can discuss further in the PR

**Comment by sjoelee** [comment]
PR submitted: https://github.com/excalidraw/excalidraw/pull/6947. Please take a look when you get a chance.

**Comment by sjoelee** [comment]
@ad1992 how do I update the status on this issue? I was trying to update it to "In Review"
