### ISSUE TITLE
Excalidraw embeds in editor mode not working with new update

### ISSUE THREAD

**Issue by thomascurro** [excalidraw/excalidraw#4337]
I have downloaded the latest version which includes embedded pages in excalidraw but my excalidraw drawings are no longer rendering when transcluded in edit mode on a md page using Ozan's Image plugin

**Comment by ad1992** [comment]
Are you referring to https://github.com/ozntel/oz-image-in-editor-obsidian ? This will need to be fixed in the plugin itself, you can create the issue in the above repo instead.

**Comment by zsviczian** [comment]
I created an issue for this in the Obsidian plugin github. This can be closed.
https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/284

**Comment by ad1992** [comment]
Thanks @zsviczian 👍🏻
