### ISSUE TITLE
networking library - Topolgy diagrams

### ISSUE THREAD

**Issue by sergioprado010489** [excalidraw/excalidraw#4348]
Dear team, 

We already bought 4 license for our Networking engineers, we need the following:

- Library of network Icons (router, switch, firewall, server, VPN Tunnel)
- The ability to atache links that can move with the form. For example if a create 2 router and connect to eachother if any of both is moved that the link still atached 

Please your comments

regards

Sergio Prado
excalidraw account: prados@tigo.net.bo

**Comment by dwelle** [comment]
Gave it a try myself: https://github.com/excalidraw/excalidraw-libraries/pull/29

![network_topology_lib](https://user-images.githubusercontent.com/5153846/144309901-90e6a690-c489-4154-b2bf-683f57b9ec5e.gif)

**Comment by sergioprado010489** [comment]
It looks great, is that already a library available for networking?

regards

Sergio
