### ISSUE TITLE
What is the name of the font used in excalidraw?

### ISSUE THREAD

**Issue by mohith01** [excalidraw/excalidraw#4366]
First of all, Thank you for creating this wonderful project and open sourcing it. I use this for most of my designs and models. I just want to change my default font in my laptop to the font used in excalidraw? Can someone please tell me the name of this font and how can i use it in linux?
Thank you

**Comment by dwelle** [comment]
Thanks! It's Virgil (made by Ellinor Rapp), and it's hosted at https://github.com/excalidraw/virgil 🍉
