### ISSUE TITLE
Git throwing out error related to Husky while trying to commit

### ISSUE THREAD

**Issue by jai-dewani** [excalidraw/excalidraw#4368]
Device: Windows 10 

Problem: When I tried to commit, an error was thrown out `cannot spawn .husky/pre-commit: no such file or directory` 

Possible solution that worked for me: Adding `#!/bin/sh` to the first line of `.husky/pre-commit`. 

PS: I haven't tested if this would still work on Linux or not

**Comment by dwelle** [comment]
And I thought it's just me 😄

**Comment by jai-dewani** [comment]
> Possible solution that worked for me: Adding #!/bin/sh to the first line of .husky/pre-commit.

Is there any better solution to this than adding this shebang statement 🤔

**Comment by dwelle** [comment]
I think it won't work on Windows without it.  Do you want to make a PR?

**Comment by jai-dewani** [comment]
Yeah, I will go ahead and make a PR for this.   
I did some research and found out using `sh` over `bash` would be better as `sh` points to whatever will be the default scripting shell in that system. 

Btw which OS do you use @dwelle? I was thinking getting this PR checked by someone using Linux and maybe Mac as well before merging.

**Comment by dwelle** [comment]
> Btw which OS do you use @dwelle? I was thinking getting this PR checked by someone using Linux and maybe Mac as well before merging.

I can check all of them.
