### ISSUE TITLE
[Language request] Lithuanian language

### ISSUE THREAD

**Issue by Zigmas12** [excalidraw/excalidraw#4382]
Hello fellow enthusiasts,
I love using Excalidraw with my team and I would love to contribute and translate the application into Lithuanian 🇱🇹  language.

My crowdin username is Zigmas12. I assume it would be the best if you could also grant me proofreader permission. In that way I will be able to approve translations asap 💨 

And thanks a lot for the awesome work you do!

**Comment by ad1992** [comment]
Here you go https://crowdin.com/translate/excalidraw/10/en-lt?filter=basic&value=0 @Zigmas12 🚀 , how do you say "Lithuanian" in "Lithuanian"?

**Comment by Zigmas12** [comment]
> Here you go https://crowdin.com/translate/excalidraw/10/en-lt?filter=basic&value=0 @Zigmas12 🚀 , how do you say "Lithuanian" in "Lithuanian"?

Thank you! 
"Lithuanian" translates to "Lietuvių"

**Comment by lipis** [comment]
#4322 added
