### ISSUE TITLE
text positioning wrong when there is offsetTop and offsetLeft 

### ISSUE THREAD

**Issue by zsviczian** [excalidraw/excalidraw#4412]
When offsetTop !== 0 || offsetLeft !==0 TextElement editors and text elements after edit get positioned incorrectly.

By rolling back this change to getViewportCoords, I was able to fix the positioning of non-boundTextElements. 

![image](https://user-images.githubusercontent.com/14358394/146450216-cb2be84f-8eb5-407e-a088-5026008a4286.png)

Container bound TextElements, however, still get positioned incorrectly even after changing getViewportCoords. I haven't yet been able to work out the root cause, however, this seems part of the code results in an incorrectly positioned text element:

https://github.com/excalidraw/excalidraw/blob/98b5c37e452d56b7d0fdbce82ce31e6389ba5330/src/element/textWysiwyg.tsx#L414-L420

I also notice that container-bound text elements get rendered in 3 different ways:
- when I edit a container bound text element
- when I load a new scene that has a container-bound text element, it gets positioned in a new location compared to where it was when saving
- when I resize a container, the text element gets positioned correctly

https://user-images.githubusercontent.com/14358394/146451616-03d1555a-bb3f-4cc0-9f91-b33eb9839cbb.mp4

**Comment by zsviczian** [comment]
Without the getViewportCoords "fix":

https://user-images.githubusercontent.com/14358394/146453254-65824f41-9bc0-4635-9e29-ed6714f1ec52.mp4

**Comment by ad1992** [comment]
@zsviczian thanks for reporting this!

As per 👇🏻 , we can definately revert this change as it mistakenly got introduced as in https://github.com/excalidraw/excalidraw/pull/4343
<img width="798" alt="Screenshot 2021-12-17 at 1 07 54 PM" src="https://user-images.githubusercontent.com/11256141/146507406-4ef3eee0-822e-4021-86af-000c9232ca45.png">

For the binded text, I haven't yet tested in the package so looking into this

**Comment by ad1992** [comment]
@zsviczian can you try with version `aakansha-excalidraw@0.10.0-coord3` if its working fine ?

**Comment by zsviczian** [comment]
@ad1992, please see #4413. I think these issues are closely related. I actually think `getViewportCoords` should not be changed back, but rather `viewportCoordsToSceneCoords` and `sceneCoordsToViewportCoords` should be fixed. I am pretty confident that those functions are not correct in the as is code.

**Comment by zsviczian** [comment]
I tested the fix. It seems to work well for both TextElements and Container-bound TextElements.

There is one small issue... if an empty line is deleted in a container-bound element, the position is not updated until the element is resized

https://user-images.githubusercontent.com/14358394/146515643-7a11b2db-dc92-4321-b809-8601d2e00776.mp4

.

**Comment by ad1992** [comment]
> @ad1992, please see #4413. I think these issues are closely related. I actually think `getViewportCoords` should not be changed back, but rather `viewportCoordsToSceneCoords` and `sceneCoordsToViewportCoords` should be fixed. I am pretty confident that those functions are not correct in the as is code.

Yep I am looking into that as well, however after fixing the function, still I need to update the coords in `getViewportCoords` hence I might push this fix first and debug that one later for proper fix

**Comment by ad1992** [comment]
> I tested the fix. It seems to work well for both TextElements and Container-bound TextElements.
> 
> There is one small issue... if an empty line is deleted in a container-bound element, the position is not updated until the element is resized
> 
> I will record a better screen capture a bit later..
> 
>  2021-12-17.09-41-19.mp4

@zsviczian this looks like an issue in the app as well and not related to the package, could you open a new issue for this ?

**Comment by zsviczian** [comment]
@dwelle, @ad1992: I've just opened a new issue: #4418
Unfortunately, the issue is not resolved when the drawing is zoomed in/out.
