### ISSUE TITLE
getViewportCoords and viewportCoordsToSceneCoords don't transform into each other

### ISSUE THREAD

**Issue by zsviczian** [excalidraw/excalidraw#4413]
shouldn't this resolve to true?

```typescript
const [clientX,clientY] = getViewportCoords(x1,y1);
const { x2, y2 } = viewportCoordsToSceneCoords({clientX,clientY});
return x2===x1 && y2===y1;
```

and

```typescript
const { clientX, clientY } = sceneCoordsToViewportCoords (x1,y1);
const { x2, y2 } = viewportCoordsToSceneCoords({clientX,clientY});
return x2===x1 && y2===y1;
```

https://github.com/excalidraw/excalidraw/blob/98b5c37e452d56b7d0fdbce82ce31e6389ba5330/src/utils.ts#L209

https://github.com/excalidraw/excalidraw/blob/98b5c37e452d56b7d0fdbce82ce31e6389ba5330/src/utils.ts#L231

https://github.com/excalidraw/excalidraw/blob/98b5c37e452d56b7d0fdbce82ce31e6389ba5330/src/components/App.tsx#L1911

**Comment by zsviczian** [comment]
![image](https://user-images.githubusercontent.com/14358394/146503515-fcd2c4c4-2d14-4420-9dfb-5552d4b4ba39.png)

**Comment by dwelle** [comment]
It should.

I'd also love to get rid of the `zoom.translation`, it only adds unnecessary complexity. Instead, we should be updating `scrollX`/`scrollY` when zooming on a point.

**Comment by zsviczian** [comment]
@dwelle, @ad1992: What is the purpose of `zoom.translation`? The value seems like it is in viewport coordinates, but looking at the code I can't figure out the logic of what it is intended to do.

Put aside `zoom.translation` I believe `viewportCoordsToSceneCoords` function is correct. It is called from many places in the code when selecting and manipulating objects, and those functions work without problems... thus empirically I conclude this function is ok.

```typescript
export const viewportCoordsToSceneCoords = (
  { clientX, clientY }: { clientX: number; clientY: number },
  {
    zoom,
    offsetLeft,
    offsetTop,
    scrollX,
    scrollY,
  }: {
    zoom: Zoom;
    offsetLeft: number;
    offsetTop: number;
    scrollX: number;
    scrollY: number;
  },
) => {
  const invScale = 1 / zoom.value;
  const x = (clientX - zoom.translation.x - offsetLeft) * invScale - scrollX;
  const y = (clientY - zoom.translation.y - offsetTop) * invScale - scrollY;
  return { x, y };
};
```

`sceneCoordsToViewportCoords`, on the other hand, is incorrect. For starters, it does not transform into `viewportCoordsToSceneCoords`; also zoom.translation is in viewport coords, but used as if it were in scene coords in the equation.
```typescript
export const sceneCoordsToViewportCoords = (
  { sceneX, sceneY }: { sceneX: number; sceneY: number },
  {
    zoom,
    offsetLeft,
    offsetTop,
    scrollX,
    scrollY,
  }: {
    zoom: Zoom;
    offsetLeft: number;
    offsetTop: number;
    scrollX: number;
    scrollY: number;
  },
) => {
  const x = (sceneX + scrollX + offsetLeft) * zoom.value + zoom.translation.x;
  const y = (sceneY + scrollY + offsetTop) * zoom.value + zoom.translation.y;
  return { x, y };
};
```

Using `viewportCoordsToSceneCoords` as the template, the equations should correctly read like this:
```typescript
  const x = (sceneX + scrollX) * zoom.value + zoom.translation.x + offsetLeft;
  const y = (sceneY + scrollY) * zoom.value + zoom.translation.y + offsetTop;
```

I believe this is leading to some of the mystical number magic in textWysiwyg, such as this:

https://github.com/excalidraw/excalidraw/blob/c76784b7744109225e49a59b27cea430c63628f2/src/element/textWysiwyg.tsx#L192-L201

---

I am also confused by the idea of using height and width to calculate `translate.x` and `translate.y` here. Height and width have to do with sizing the textarea to fit the visible canvas, but not with positioning it:

https://github.com/excalidraw/excalidraw/blob/c76784b7744109225e49a59b27cea430c63628f2/src/element/textWysiwyg.tsx#L33-L54

Also, just by observing the surrounding code, I am pretty certain this is incorrect:
```typescript
  if (width > maxWidth && zoom.value !== 1) {
    translateX = (maxWidth / 2) * (zoom.value - 1);
  }
```
and it should rather read:
```typescript
  if (width > maxWidth && zoom.value !== 1) {
    translateX = ((maxWidth - offsetLeft * 2) * (zoom.value - 1)) / 2;
  }
```

But since we are converting scene coords to viewport coords here:

https://github.com/excalidraw/excalidraw/blob/c76784b7744109225e49a59b27cea430c63628f2/src/element/textWysiwyg.tsx#L171

I am not even sure why we need `translate.x` and `translate.y` here:
https://github.com/excalidraw/excalidraw/blob/c76784b7744109225e49a59b27cea430c63628f2/src/element/textWysiwyg.tsx#L203-L225

**Comment by dwelle** [comment]
> What is the purpose of `zoom.translation`? The value seems like it is in viewport coordinates, but looking at the code I can't figure out the logic of what it is intended to do.

It was introduced to support zooming on cursor (via ctrl/cmd-mousewheel). I don't recall why it was implemented in this way.

> `sceneCoordsToViewportCoords`, on the other hand, is incorrect.

I'm surprised it even works at all then. But I definitely agree with you that it should be reversible. We can try fixing it and see what it breaks (apart from wysiwyg, which as you say contains hacks that likely account either for this or for other things).

**Comment by zsviczian** [comment]
`sceneCoordsToViewportCoords` is only used for three purposes:
- textWysiwyg
- to check if scroll `isOutsideViewPort`
- `remotePointerViewportCoords`

It may be that `isOutsideViewPort` is broken as well, but I think you don't notice that so much if there is a bit of inaccuracy around the edges of the canvas. 

Similarly you would not notice if `remotePointerViewportCoords` was wrong.

That leaves wysiwyg which is very buggy when you have offsets and when you zoom.

So I think correcting `sceneCoordsToViewportCoords` is low risk, appart from the refactoring of wysiwyg...

**Comment by dwelle** [comment]
> It may be that `isOutsideViewPort` is broken as well, but I think you don't notice that so much if there is a bit of inaccuracy around the edges of the canvas.

That would explain why `calculateScrollCenter()` doesn't work correctly half of the time, but maybe that's related to something else.

Let's fix the `sceneCoordsToViewportCoords()` then — but we'll want to update wysiwyg at the same time, or at least make it account for the fix.
