### ISSUE TITLE
[FEATURE] open PDF files in Excalidraw 

### ISSUE THREAD

**Issue by JJger148** [excalidraw/excalidraw#4419]
what if excalidraw would be able to use a split screen with a pdf at one side and the normal excalidraw whitebard on the other side. 
If I scroll or zoom the PDF it would also zoom and scroll the whiteboard. 
I could take a lot of notes and draw lines to my PDF.

**Comment by batu** [comment]
I would use the "Insert Printout from PDF" functionality similar to one note.

Here is one example of a workflow that I would love to use excalidraw(++) with!
https://youtu.be/H3Bhlan0mE0?t=53

**Comment by Signynt** [comment]
This would be an extremely important feature for me too 👍

**Comment by Shahin-rmz** [comment]
I use [Rnote](https://github.com/flxzt/rnote) on my linux Machine.
it can open pdfs as svg.
in this way we won't loose quality of pdf on importing it.
btw excalidraw seems to be very promising when it can be used in joplin or other productive apps.

**Comment by JJger148** [comment]
excalidraw can be used in Obsidian quite well.

**Comment by njalooo** [comment]
@JJger148 which programs/plugins do you use in Obsidian to import pdf's?

Right now this is the main issue that's stopping me from effectively utilizing excalidraw.

**Comment by bendersej** [comment]
It is now possible to view, edit and fill PDF forms with Excalidraw using the `Web-Embed` feature, see PR for reference: https://github.com/excalidraw/excalidraw/pull/6810

**Comment by DanielJGeiger** [comment]
Closing as completed by #6810.

**Comment by applesoff** [comment]
How is one supposed to use the web embed feature to import a saved PDF? wouldn't PDF import directly or to svg be the best approach for ease of use?
