### ISSUE TITLE
Positioning of container-bound text when zoomed and partly scrolled outside visible screen area

### ISSUE THREAD

**Issue by zsviczian** [excalidraw/excalidraw#4421]
This issue is not fixed by #4420

https://user-images.githubusercontent.com/14358394/146630486-f1c7b9bd-1ffd-4688-bfe1-f85797f56b94.mp4

**Comment by zsviczian** [comment]
I think this happens because editable.clientHeight is used to calculate coordY here:

container.height is given, but eidtable.clientHeight will change depending on zoom and scroll.

https://github.com/excalidraw/excalidraw/blob/8b5657e1cea96e78f9f9dc6fbd608a33a11310af/src/element/textWysiwyg.tsx#L168-L172

**Comment by zsviczian** [comment]
In addition, I think the logic to use `editable.style.top` and `.left` to set `TextElement.x` and `.y` is not a good approach. You would achieve more consistent results if `getTextWysiwygSnappedToCenterPosition` would be called each time the TextElement position is determined.

**Comment by zsviczian** [comment]
@ad1992, are you working on these issues or shall I take a stab at them (including #4418, #4417, and #4413)?

**Comment by ad1992** [comment]
> @ad1992, are you working on these issues or shall I take a stab at them (including #4418, #4417, and #4413)?

@zsviczian yep I am looking into this
