### ISSUE TITLE
Typescript error: AppState cannot be null (in `restore` function)

### ISSUE THREAD

**Issue by GasimGasimzada** [excalidraw/excalidraw#444]
Was there any changes to `restore` function that caused null to be removed from it?

**Comment by dwelle** [comment]
What error exactly?

**Comment by GasimGasimzada** [comment]
It was an error that cannot assign `null` to an object. So, I added back the `null` type to the app state argument in restore function in the PR I am currently working on.

**Comment by dwelle** [comment]
Looking at `git blame`, it was `any` before, then narrowed to `AppState`, so there was never a `| null`. So no problem adding it now.

**Comment by GasimGasimzada** [comment]
Thank you for the info! :)
