### ISSUE TITLE
Editing text automatically resize shape

### ISSUE THREAD

**Issue by randomarno** [excalidraw/excalidraw#4450]
Hello,

Latest Excalidraw version has a new behaviour when editing text inside a shape. Previously, it maintained shape size, now it automatically resizes the shape. 

https://user-images.githubusercontent.com/77626973/146921575-d8185612-4aaf-49eb-bf43-38a3c3fbbb4f.mp4

I was able to resize shapes containing text, but now it forbids resizing under a fixed dimension (previously it resized the contained text to fit instead of blocking).

Could it be reverted to the old way or corrected ?

**Comment by dwelle** [comment]
This is the new default because we believe that when you create a text inside an element center, the usual case is you'll want it to be constrained to that element. We went with expand-element-height instead of resize-text-to-fit.

If you want to create an unbound text, you'll need to create the text outside the element center (or outside the element altogether) and position it manually.

**Comment by randomarno** [comment]
I understand that new feature, but why resize an element when it fits, like in my example with the black rectangle ? When correcting "TEST" to "T", the box size up instead of staying at initial size.

**Comment by dwelle** [comment]
The two lines being creating in specific cases, like the one with your `T` text, is a bug and will be fixed. But even there it should allow you to resize:

![excal-sticky-two-lines-resize-back](https://user-images.githubusercontent.com/5153846/146940506-b4dcbd52-064d-428f-b906-a79c7dc10136.gif)

**Comment by randomarno** [comment]
OK thanks for the information. 
I also noticed that adding text to a shape creates a second object, which requires you to group the two together afterwards (the shape and the text) if you want to manipulate the whole. Is this the normal behavior?

**Comment by dwelle** [comment]
Can you show an example? The text and the container (above, the rectangle), are separate elements but from the user perspective the should behave as one object (when moving, resizing, duplicating, ...). The only case where they are completely separate is when they're not bound together (e.g. you create the text outside (or out-of-center) and only move it inside the rectangle.

**Comment by randomarno** [comment]
I tried to show the behaviour here : 

https://user-images.githubusercontent.com/77626973/146945002-11863897-9dd4-48e1-8fb7-4e38c77d41b8.mp4

Unlike the old version, it is necessary to group the shape and the text to get the text controls on the object.

**Comment by dwelle** [comment]
Oh, now I understand. Yes, right now you have to start editing the text (`enter` or double-click) to get the text controls. But this is a good point: we might wanna make it act as if both objects are selected so you can modify the text settings without having to enter the text editor. /cc @ad1992 thoughts?

**Comment by ad1992** [comment]
Yep good point, I agree we should show text controls when container is selected

**Comment by ad1992** [comment]
Closing this via https://github.com/excalidraw/excalidraw/pull/4499, now you can select container to update text properties of bounded text
