### ISSUE TITLE
how to upgrage excalidraw into latest version??

### ISSUE THREAD

**Issue by sohailamjad256** [excalidraw/excalidraw#4451]

**Comment by ad1992** [comment]
You can refer to the [changelog](https://github.com/excalidraw/excalidraw/blob/master/src/packages/excalidraw/CHANGELOG.md#0100-2021-10-13) to upgrade to latest version, however if you want to test out the unreleased version you can use [@excalidraw/excalidraw-next](https://npmjs.com/@excalidraw/excalidraw-next)

**Comment by sohailamjad256** [comment]
already i have installed all the npm packages..just need to upgrade
![Screenshot 2021-12-21 190631](https://user-images.githubusercontent.com/53993286/146939078-43644408-a9c7-4053-a45f-f4f4f0a89838.png)
here i have added screen here in the menu i cannot see adding image icon

**Comment by sohailamjad256** [comment]
i have used that @excalidraw/excalidraw-next..but is it for permanent use or temporary use?

**Comment by ad1992** [comment]
> already i have installed all the npm packages..just need to upgrade ![Screenshot 2021-12-21 190631](https://user-images.githubusercontent.com/53993286/146939078-43644408-a9c7-4053-a45f-f4f4f0a89838.png) here i have added screen here in the menu i cannot see adding image icon.but in the latest version i can see image icon

Yes thats because we haven't shipped it yet in the official release, you will find it in `@excalidraw/excalidraw-next`. 

> i have used that @excalidraw/excalidraw-next..but is it for permanent use or temporary use?

We recommend not to use in production as the API's are likely to change in official release.

**Comment by sohailamjad256** [comment]
yes ..Thanks for the update and can you guys please update me when you guys will release officially

**Comment by dwelle** [comment]
If you pin (lock) the version it should be fine for production. You will just need to potentially migrate the API a bit later.

**Comment by ad1992** [comment]
closing this as the version was released [@excalidraw/excalidraw @0.11.0](https://www.npmjs.com/package/@excalidraw/excalidraw)
