### ISSUE TITLE
text container not atomic when selecting within a group

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#4456]
Container/text isn't atomic when selected within a group:

![excal-sticky-group-atomic-bug](https://user-images.githubusercontent.com/5153846/146979250-e4705302-4703-4946-8190-b302f14d9157.gif)

cause:

https://github.com/excalidraw/excalidraw/blob/8e6a747873a180a243cf5c467152ac2a70d02daa/src/element/dragElements.ts#L31-L45

**Comment by patrickhulce** [comment]
I seem to be able to reproduce without a group as well... Same issue?

https://user-images.githubusercontent.com/2301202/147026149-8aea779a-61cd-4e9b-98ba-71e935fb67a5.mov

**Comment by ad1992** [comment]
> I seem to be able to reproduce without a group as well... Same issue?
> 
>  Screen.Recording.2021-12-21.at.8.39.18.PM.mov

This shouldn't happen, looks like text is not binded at all for you.  Can you check the value of version by opening Nerd stats from context menu / option+/ ?

**Comment by ad1992** [comment]
Actually nvm, from the video its clear that you are on latest version, could you confirm the device/browser you are using ?

**Comment by ad1992** [comment]
> I seem to be able to reproduce without a group as well... Same issue?
> 
>  Screen.Recording.2021-12-21.at.8.39.18.PM.mov

Since this issue was related to grouping, wil open a separate issue linking this usecase
