### ISSUE TITLE
Can’t change font size of container bound text on iPad

### ISSUE THREAD

**Issue by zsviczian** [excalidraw/excalidraw#4464]
https://user-images.githubusercontent.com/14358394/147125571-6bb837d7-44c8-4547-ab86-7cf50642d443.MP4

**Comment by dwelle** [comment]
We should fix that regardless, but we will also make it so that you can change text settings if you just select the container.

**Comment by ad1992** [comment]
This issue is in android too but for all text properties

**Comment by ad1992** [comment]
Now you can select the container to update text properties https://github.com/excalidraw/excalidraw/pull/4499 so that would improve the UX for this

**Comment by ad1992** [comment]
@dwelle this is fixed already, must have been fixed along with the recent fixes which got pushed.
can you confirm if it works for you as well ?

**Comment by dwelle** [comment]
Works for me now in that it changes the text color of both the text and container. But doesn't work during text creation: https://github.com/excalidraw/excalidraw/issues/6202

**Comment by ad1992** [comment]
closing this was fixed and separate issue is created already for text creation
