### ISSUE TITLE
Text does not move with shape until resize/edit

### ISSUE THREAD

**Issue by patrickhulce** [excalidraw/excalidraw#4465]
Originally posted in https://github.com/excalidraw/excalidraw/issues/4456#issuecomment-999240531.

When a shape that contains text is moved, the text stays in its old position until the shape is resized or the text is edited.

https://github.com/excalidraw/excalidraw/issues/4417#issue-1083187152 appears to be remarkably similar although this issue is still persisting in latest.

OS: macOS Big Sur 11.6.1
Chrome Version: 96.0.4664.110
Excalidraw Version: 2021-12-22T13:46:49Z-64c2d76

https://user-images.githubusercontent.com/2301202/147026149-8aea779a-61cd-4e9b-98ba-71e935fb67a5.mov

**Comment by dwelle** [comment]
Can't reproduce on Chrome 96, Big Sur 11.6.2, and identical Excalidraw version.

Are you using any special device (mouse, ...) or touchpad? Pressing any modifiers (shift, cmd,...) when creating/confirming/dragging? Grasping at straws here.

Can you save the file and upload it here? (you can rename to `.txt` and it should allow you to attach it directly in a comment here.)

**Comment by patrickhulce** [comment]
Ah, this must have been fixed between yesterday and today but I had old objects from the broken version still on the page. When I create new objects this no longer occurs 👍

**Comment by ad1992** [comment]
> Ah, this must have been fixed between yesterday and today but I had old objects from the broken version still on the page. When I create new objects this no longer occurs 👍

Nice :) But you are drawing a fresh rectangle / text in the video shown above so you mean it was happening yesterday and not anymore ?

**Comment by patrickhulce** [comment]
> But you are drawing a fresh rectangle / text in the video shown above so you mean it was happening yesterday and not anymore

Yes, the video was taken yesterday. When I created this issue, I checked the *same* drawing to see if it was still happening but didn't think to create a fresh drawing to check if it was fixed. The same drawing was still buggy but new drawings are fine today 👍
