### ISSUE TITLE
Regression on copy-paste: pasted elements lose selection

### ISSUE THREAD

**Issue by ShayDavidson** [excalidraw/excalidraw#4471]
Hey! I'm using the paid version and lately I noticed a regression in the copy-paste functionality.

When I copy-paste a group of selected elements, all elements *besides text* lose selection. Just the pasted text elements remain selected.

- I either need to paste them in an "empty space" in the canvas or reselect.
- group before i copy, paste, and then ungroup.

both options harm the experience obviously.

before the bug, any pasted elements used to be selected which was great UX wise.

**Comment by ad1992** [comment]
@ShayDavidson do you mind recording a video with the above steps so its more clear ?

**Comment by dwelle** [comment]
This seems a regression in the editor itself. Looking into it.

**Comment by dwelle** [comment]
@ShayDavidson fix now deployed in Excalidraw+ too. Thanks for the report!

**Comment by ShayDavidson** [comment]
wow thanks for the quick turn around 🙏🏻
