### ISSUE TITLE
Help: hide the "dash rectangle" after selecting an item

### ISSUE THREAD

**Issue by mawnir** [excalidraw/excalidraw#4490]
after a day of searching, i didn't find my way to hide the "dash rectangle" after selecting an item:

<img width="298" alt="Screen Shot 2021-12-27 at 16 16 08" src="https://user-images.githubusercontent.com/62011430/147484868-b368090c-5a73-4c52-942e-354d478c2a7d.png">

any help is appreciated.. a newbie here!

**Comment by ad1992** [comment]
Hey @mawnir just clicking anywhere outside should work, does that not work for you ?
![Excalidraw](https://user-images.githubusercontent.com/11256141/147499973-c99dc1b1-1d3f-4953-a887-2db556b67058.gif)

**Comment by mawnir** [comment]
> Hey @mawnir just clicking anywhere outside should work, does that not work for you ? ![Excalidraw](https://user-images.githubusercontent.com/11256141/147499973-c99dc1b1-1d3f-4953-a887-2db556b67058.gif)

Thank you for your answer, but i need when i click the item.. the "dash rectangle" doesn't show up.
i know there is option for that, so i ask where in the source code i can do that.. 
my typescript knowledge is limited.
Thank you

**Comment by zsviczian** [comment]
If you want to make your own build without the selection box, this is where I would start to look:

https://github.com/excalidraw/excalidraw/blob/bae0e985b2025e89a6d7e7b218efd156ab52e38f/src/renderer/renderScene.ts#L605-L650

**Comment by mawnir** [comment]
> If you want to make your own build without the selection box, this is where I would start to look:
> 
> https://github.com/excalidraw/excalidraw/blob/bae0e985b2025e89a6d7e7b218efd156ab52e38f/src/renderer/renderScene.ts#L605-L650

exactly.. thank you!!!
