### ISSUE TITLE
undoing text property change doesn't re-wrap text

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#4500]
![excal-bug-undo-redraw](https://user-images.githubusercontent.com/5153846/147656248-9d05828c-bcf9-4309-bf5f-e239cba6de51.gif)

It actually doesn't undo the rectangle change & font-size change properly either.

**Comment by ad1992** [comment]
This only happens when selecting the text explicitly, Updating text props by selecting the container works fine
