### ISSUE TITLE
Add to Home Screen doesn‘t work the same for Excalidraw and E+

### ISSUE THREAD

**Issue by adinafxv** [excalidraw/excalidraw#4503]
Hello,
issue on iPad PRO (MTXP2FD/A) running 15.1 Software version. 

When opening Excalidraw from Safari, "Add to Home Screen" creates a new icon on Home. This opens Excalidraw in a nice fullscreen version. I didn‘t succeed to log in via this.

When login in in Safari and then hitting  "Add to Home Screen", I‘m faced with an icon that just opens new tab in Safari, no full-screen behavior.

I think there might be just some flag missing.

BTW, you‘re doing great job, this is my most favorite tool ever.

**Comment by dwelle** [comment]
Hey Adina (and hi from Brno),

Yes, right now, Excalidraw+ doesn't work like Excalidraw in this regard. To be technical, Excalidraw is a progressive web app (PWA) while Excalidraw+ is not — which among other things means it won't work offline. We don't rule out making it a PWA as well, but right now it'd add too complexity.

**Comment by adinafxv** [comment]
Hi to Brno from Prague 😁, 
oh, makes sense! Thanks for the explanation. 
best to the new year!
