### ISSUE TITLE
Sticky note resize results in Excalidraw deadlock when using a grid

### ISSUE THREAD

**Issue by zsviczian** [excalidraw/excalidraw#4505]
Open the sample file ([sample.zip](https://github.com/excalidraw/excalidraw/files/7793884/sample.zip)) in Excalidraw. Resize the rectangle to decrease its width. Excalidraw will get into an infinite loop.

https://user-images.githubusercontent.com/14358394/147773064-10d4f8dc-29cb-4f44-bda9-64a294238023.mp4

Location of the infinite loop:
https://github.com/excalidraw/excalidraw/blob/dd8e465304033681bf610f98d27cde833c39eba5/src/element/textElement.ts#L261-L331

**Comment by dwelle** [comment]
fixed via https://github.com/excalidraw/excalidraw/issues/4505
