### ISSUE TITLE
changing stroke color of container should also change color of bound text

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#4520]
Changing stroke when the container is selected, we should IMO change the text color as well.

![excal-stroke-color-container-text](https://user-images.githubusercontent.com/5153846/147825556-68e685a7-c307-4e92-9d06-7df0597dcfad.gif)

/cc @ad1992 @zsviczian

**Comment by zsviczian** [comment]
I could argue equally for our against. I think in Miro you set them separately

**Comment by ad1992** [comment]
We can do that, I am just little unsure about it being intutive but again since its binded text so updating stroke for text does make sense just like other props. And If a user wants to update color of text, then they could explicitly select text and update stroke color as well

**Comment by dwelle** [comment]
I can see arguments for/against as well,  but I think we should align with the general behavior where we select multiple elements, which the sticky-note acts like right now. Also, I'd say the common case would be to align stroke color with text color (aesthetically it looks better in most cases).
