### ISSUE TITLE
change the color of the handles border

### ISSUE THREAD

**Issue by mawnir** [excalidraw/excalidraw#4522]
i want to change the color of handles **border**
<img width="355" alt="Screen Shot 2021-12-31 at 21 46 39" src="https://user-images.githubusercontent.com/62011430/147838650-0f7c2c0a-ea4e-4a8e-9205-73683a37467a.png">

i checked in "renderScene.ts" file but no luck. i think its related to the theme.. so i checked in the "theme.scss" and nothing there also.
i'm new to TS.. so any help will be appreciated!

**Comment by ad1992** [comment]
Here is where local user color could be updated https://github.com/excalidraw/excalidraw/blob/master/src/renderer/renderScene.ts#L314 in case you are forking the repo.
For remote users, you can call [updateScene](https://github.com/excalidraw/excalidraw/blob/master/src/packages/excalidraw/README.md#updatescene) and pass `collaborators` 
Whats your use case ? We could support updating local user color as well via the API, so you don't have to fork the repo

**Comment by mawnir** [comment]
> 

i tried to change the color to : 
`selectionColors.push(oc.green[6]);`
and nothing changed, the border stayed black. am i doing something incorrect?
thank you

**Comment by mawnir** [comment]
@zsviczian please check this.. any help will be appreciated!
thank you

**Comment by ad1992** [comment]
> > 
> 
> i tried to change the color to : `selectionColors.push(oc.green[6]);` and nothing changed, the border stayed black. am i doing something incorrect? thank you

can you share your code ? Updating https://github.com/excalidraw/excalidraw/blob/master/src/renderer/renderScene.ts#L314 will update the selection color to green
<img width="410" alt="Screenshot 2022-01-02 at 7 34 51 PM" src="https://user-images.githubusercontent.com/11256141/147878364-ee0bc7a9-84d5-4126-9db6-9a9ccf8af79b.png">

**Comment by mawnir** [comment]
> Whats your use case ? We could support updating local user color as well via the API, so you don't have to fork the repo

i'm talking about the "handles borders" the squared used fo resizing
<img width="355" alt="Screen Shot 2021- " src="https://user-images.githubusercontent.com/62011430/147878550-eba1d16e-0458-4573-a550-7cf696ae66e4.png">

**Comment by mawnir** [comment]
@ad1992 have you find a way? thank you

**Comment by mawnir** [comment]
i found it , i added this line: 
`context.strokeStyle = "#fff"; `
after `context.save();` line 200 in "renderScene.ts"
