### ISSUE TITLE
Add Internationalization support/Follow Up

### ISSUE THREAD

**Issue by fernandoalava** [excalidraw/excalidraw#453]
Hello, Excalidraw it's a cool tool would be nice to add internationalization so more users can use it around the world. I would be glad to help with that if you think that it's helpful

### TODO

- [x] Add language selector somewhere in the screen to change the default language
- [x] Add Spanish version

**Comment by vjeux** [comment]
Would be great yeah! There aren’t that many strings so this should be a fairly small project.

**Comment by fernandoalava** [comment]
Perfect, I will start working on that 👍

**Comment by lipis** [comment]
If you need some flags :) https://github.com/lipis/flag-icon-css

**Comment by fernandoalava** [comment]
The first version merged here: https://github.com/excalidraw/excalidraw/pull/477
Follow Up task:

- Add language selector somewhere in the screen to change the default language 
- Add Spanish version
- Prefetch the JSON files of the most common languages

**Comment by lipis** [comment]
the files are too small.. no need to do some overoptimization to prefetch the json files.. we can load them all for now.

**Comment by fernandoalava** [comment]
what would be very helpful right now is know How we should show the language selector, I start looking UX better practices  about it and seems that the better option is as Facebook does:
<img width="786" alt="Screenshot 2020-01-21 at 13 12 19" src="https://user-images.githubusercontent.com/6731845/72800312-ba114b80-3c4f-11ea-883f-a642839bfd46.png">
What do you think?

**Comment by lipis** [comment]
we can start with bottom right, with a very small font. As long as we have few languages we can show them all and disabled the current one.

**Comment by lipis** [comment]
More strings:

- https://github.com/excalidraw/excalidraw/blob/master/src/scene/data.ts#L193-L195
- https://github.com/excalidraw/excalidraw/blob/master/src/scene/data.ts#L210
- https://github.com/excalidraw/excalidraw/blob/master/src/scene/data.ts#L266-L270
