### ISSUE TITLE
Palm rejection

### ISSUE THREAD

**Issue by Litt7e** [excalidraw/excalidraw#4532]
Palm rejection would improve the user experence greatly.
Would it be possible to implement some variation of palm rejection when using Apple Pencil, specifically with the drawing tools?

**Comment by Litt7e** [comment]
And there is a problem which is if the interval between two strokes is short, the second stroke will not be recognized

**Comment by dwelle** [comment]
It's planned! Hopefully things will start moving soon. https://github.com/excalidraw/excalidraw/issues/4202 (potentially https://github.com/excalidraw/excalidraw/issues/3838)

**Comment by dwelle** [comment]
As for the missed strokes: we will fix that, but first attempts didn't bear fruit. If you have Apple Pencil Scribble enabled, then disabling it should fix it: https://github.com/excalidraw/excalidraw/issues/3955#issuecomment-910493093
