### ISSUE TITLE
Feature request: Call scripts from the right-click menu

### ISSUE THREAD

**Issue by kazdonkai** [excalidraw/excalidraw#4539]
Scripts are very useful, and they are getting a lot. I'm wondering if it would be possible to register scripts in the right-click menu, since calling them with command menu or hot keys is annoying.

**Comment by dwelle** [comment]
@kazdonkai I believe this is a question for https://github.com/zsviczian/obsidian-excalidraw-plugin?

**Comment by zsviczian** [comment]
Correct, this is Obsidian related. Also, while I see the potential vaule of adding scripts to the context menu, I don’t think I’ll implement the feature. I am keeping customizations in the Obsidian build of the Excalidraw component to the minimum to ensure that the plugin can continue to benefit from the development of the core Excalidraw product.
