### ISSUE TITLE
Erratic freehand line ends that get bed with a graphic tablet

### ISSUE THREAD

**Issue by si14** [excalidraw/excalidraw#4551]
Hey there!

First of all, thanks for the awesome piece of software!

There is a bit of an issue with freehand drawing. Here is a random word handwritten on a wacom in the latest Safari:

<img width="637" alt="Screenshot 2022-01-07 at 23 19 02" src="https://user-images.githubusercontent.com/316910/148619818-ceb8bba6-1b0f-4ccd-9d42-287704815c46.png">

And here are a few random scribbles to showcase the issue:

<img width="407" alt="Screenshot 2022-01-07 at 23 19 32" src="https://user-images.githubusercontent.com/316910/148619832-3450df31-6add-4b60-a098-c2ab9ed4a7be.png">

As you can see, stroke ends almost always have that disconnected dot at the end which looks quite messy.

It's a bit better in Chrome, surprisingly, but not perfect either:

<img width="450" alt="Screenshot 2022-01-07 at 23 23 48" src="https://user-images.githubusercontent.com/316910/148619867-ee9b3899-6027-40e3-807b-7bf92a3232ff.png">

I haven't looked at the code, but it looks like pressure sensitive part of stroke drawing is a bit misaligned with the end-of-stroke-circle logic, which leads to those inconsistencies.

I looked through the issues and haven't found anything similar yet, apologies if it's a duplicate.

**Comment by valvas29** [comment]
can reproduce with my wacom intuos s on windows 11. Happens both in firefox and chrome, aswell as in the obsidian plugin.

![grafik](https://user-images.githubusercontent.com/75018284/159252834-0bd8e057-3a98-42fc-bcbf-50addc032321.png)
