### ISSUE TITLE
wysiwyg & text wrapping broken with specific decimal fontSizes

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#4563]
steps (in localhost):

1. set fontSize to `18.092888001469653`
	  
     ```
	  h.setState({ currentItemFontSize: 18.092888001469653 })
	  ```
2. paste this rectangle, and add text
	  ```
	  {"type":"excalidraw/clipboard","elements":[{"type":"rectangle","version":59,"versionNonce":1211285316,"isDeleted":false,"id":"MPershCwVYBUaRTcXOQgV","fillStyle":"solid","strokeWidth":2,"strokeStyle":"solid","roughness":0,"opacity":100,"angle":0,"x":-11.33950681451148,"y":1141.0550873424463,"strokeColor":"#087f5b","backgroundColor":"transparent","width":261.0000000000001,"height":82,"seed":1618216060,"groupIds":[],"strokeSharpness":"sharp","boundElements":[],"updated":1641748943024}],"files":{}}
	  ```
3. start typing

	![excal-bug-sticky-decimal-fontsize](https://user-images.githubusercontent.com/5153846/148698707-43f85559-2f7b-412d-aa13-88aa809adb33.gif)

**Comment by ad1992** [comment]
@dwelle this is fixed already, must have been fixed along with the recent fixes which got pushed.
can you confirm if it works for you as well ?

**Comment by dwelle** [comment]
seems fixed, though it may be just a side effect of changing the algo little so that the exact font-size to repro is now different. But let's assume it's actually fixed!

**Comment by ad1992** [comment]
> seems fixed, though it may be just a side effect of changing the algo little so that the exact font-size to repro is now different. But let's assume it's actually fixed!

We haven't updated the wrapping algo for a long time AFAIR apart from the recent emoji fix where the wrapping algo was touched.
Turns out that bug was fixed long back as part of https://github.com/excalidraw/excalidraw/pull/4573
