### ISSUE TITLE
Transparent backgrounds result in bleed/ghosting

### ISSUE THREAD

**Issue by voluntadpear** [excalidraw/excalidraw#457]
When the scene background color is changed to one with a low alpha value, the transition animation is laggy and moving elements around is affected.

![lag](https://user-images.githubusercontent.com/10501948/72688104-f4110f00-3ae2-11ea-86b9-2d8bf79d722a.gif)

**Comment by lipis** [comment]
try with: `transparent`

**Comment by voluntadpear** [comment]
If the scene background is set to `transparent` the previous positions of the moved elements are not cleared

![bug with transparent as scene background](https://user-images.githubusercontent.com/10501948/72693913-bbd4f500-3b11-11ea-895c-dd1698beed8c.png)

**Comment by vjeux** [comment]
If the background has transparence, we need to first clear it with solid color and then draw the background color on-top. A PR for this would be welcomr

**Comment by dwelle** [comment]
Yea, in both cases it's the problem of the previous scene bleeding into next one. Not a perf issue.
