### ISSUE TITLE
[Bug] Object actions panel behind zoom buttons in Obsidian on Ipad

### ISSUE THREAD

**Issue by unfamiliarish** [excalidraw/excalidraw#4571]
## Details 
When interacting with an object that has many attributes, the sidebar is displayed behind the zoom buttons, making it hard to delete objects. 

## Environment: 
- iOS 15.1 (2020 iPad Pro 12.9")
- Obsidian v1.0.5
- Excalidraw v1.5.16

## Video
https://user-images.githubusercontent.com/89762294/149051708-bfde9d0a-50f9-4e5b-9439-0bf37ea502f5.mp4

**Comment by zsviczian** [comment]
Can you check if the same happens for you using excalidraw.com?

I don't experience the same in Obsidian. The object actions menu is scrollable and not hidden behind zoom, it might be that your Obsidian theme is causing the issue. Can you try Excalidraw with the default Obsidian theme?

If you don't experience the same on excalidraw.com, then I'd ask you to open an issue for this on the obsidian-excalidraw github, where we can explore what might be causing this in your case. https://github.com/zsviczian/obsidian-excalidraw-plugin/issues

**Comment by zsviczian** [comment]
https://user-images.githubusercontent.com/14358394/149095171-b33d7c1a-7e18-46ec-b86f-813f415c623e.MP4

**Comment by unfamiliarish** [comment]
Looks like it was an issue with the theme. 

Switching back to the default obsidian theme allowed the sidebar to be scrollable. Testing on excalidraw.com was inconclusive - it was more zoomed out, and I couldn't get the sidebar long enough to overlap with the zoom buttons. 

I'll close this out and open a follow-up with the theme creator. Thanks!
