### ISSUE TITLE
 [Bug] Right-click object menu displays partially off-screen when Excalidraw component screen offset!=0

### ISSUE THREAD

**Issue by unfamiliarish** [excalidraw/excalidraw#4572]
## Details
When "right-clicking" or tapping-and-holding to open the object menu, the object menu displays partially off-screen, and cannot be dragged or scrolled to view cutoff items. 

### Workaround
Move the canvas so that the intended object can be selected from a higher part of the screen. Move back to continue previous work. 

This works, but is pretty annoying for workflow ergonomics.

## Environment: 
- iOS 15.1 (2020 iPad Pro 12.9")
- Obsidian v1.0.5
- Excalidraw v1.5.16

## Video
https://user-images.githubusercontent.com/89762294/149054776-b1c3e001-8362-4c0e-9ce9-315571419c76.mp4

### Details
* Create an object, right-click and delete it
* Create a new object, delete from menu is off-screen. Tried scrolling to access, but menu display is static

**Comment by zsviczian** [comment]
This is not an Obsidian specific bug, but seems to be related to how the context menu handles screen offsets.

![image](https://user-images.githubusercontent.com/14358394/149093451-31e6820e-0fad-4fa1-8c13-ab98313496b6.png)


When there is no offset, excalidraw handles context menu positioning well:

![image](https://user-images.githubusercontent.com/14358394/149093530-42c2da03-7629-41f7-a265-d3e6f2d361f7.png)

**Comment by unfamiliarish** [comment]
Hi @zsviczian! Are you confirming that this is a bug with excalidraw, or that it's instead something I should be adjusting on my machine? Thanks!

**Comment by zsviczian** [comment]
From what I can see, this is an excalidraw bug in the core Excalidraw package, not Obsidian specific.
