### ISSUE TITLE
[Bug] Incorrect scene loading that contains image

### ISSUE THREAD

**Issue by Enderedne** [excalidraw/excalidraw#4578]
The bug is easily reproducible in the [codesandbox](https://codesandbox.io/s/excalidraw-ehlz3) environment with the preset created by excalidraw. I did a single change so that the scene could be loaded:

```js
// where the loadScene value should be set to true, the default is false
UIOptions={{ canvasActions: { loadScene: true } }}
```
The scene that I'm trying to load can be found [here](https://excalidraw.com/#json=d5VNyQuUFkccjRuDuYdy0,qblPAbDL2qrglZvXhkC90Q).

Expecting to see:
![image](https://user-images.githubusercontent.com/5598831/149123800-7d8eedf7-3f0b-43c1-bf1e-a93ced51ca34.png)

Instead, the image is missing:
![image](https://user-images.githubusercontent.com/5598831/149123857-74144826-b16f-42a0-b0f6-023aedace640.png)

**Comment by ad1992** [comment]
The codesandbox link is using the `0.10.0` version of `@excalidraw/excalidraw` which doesn't contain image support. You will need to use `@excalidraw/excalidraw-next` to get the unreleased changes and it will work, here is the [codesandbox](https://1m7pt.csb.app/)

**Comment by techsmyth** [comment]
@ad1992 this does raise the question of when you are expecting to release the next version?
