### ISSUE TITLE
[Bug] Cmd+D doesn't work in obsidian on iPad

### ISSUE THREAD

**Issue by unfamiliarish** [excalidraw/excalidraw#4583]
## Details
'Cmd+D' in obsidian does not duplicate object. Does duplicate in excalidraw.com

## Environment: 
- iOS 15.1 (2020 iPad Pro 12.9")
- Excalidraw v1.5.16 in Obsidian v1.0.5
- excalidraw.com in Safari
- Logitech Combo Touch iPad Pro (5th gen)

## Video
https://www.dropbox.com/s/cpx81yovxbemmhj/excalidraw_obsidian_ipad_cmd%2Bd_not_recognized.mp4?dl=0

### Demo steps
* In Obsidian:
  * Using finger, draw diamond
  * Using keyboard, delete (success), cmd+z (success), cmd+d, cmd+d (nothing)
* In excalidraw.com:
  * Using finger, draw diamond
  * Using keyboard, delete (success), cmd+z (success), cmd+d, cmd+d (success)

**Comment by ad1992** [comment]
looks specific to Obsidian, cc @zsviczian

**Comment by unfamiliarish** [comment]
@ad1992 should I move this to https://github.com/zsviczian/obsidian-excalidraw-plugin/issues?

**Comment by unfamiliarish** [comment]
Closing, moved to https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/355

**Comment by ad1992** [comment]
Thanks @unfamiliarish
