### ISSUE TITLE
Vertical alignment of text in boxes

### ISSUE THREAD

**Issue by glenjamin** [excalidraw/excalidraw#4586]
I'm a big fan of the new "text in boxes" feature, thanks for adding this!

Currently it appears that the text alignment within a box can only be left/centre/right - it's always centered vertically. Would it be possible to add the option to apply top/bottom vertical alignment?

I use this most often when labelling a container that wraps other boxes.

<img width="337" alt="Screenshot 2022-01-13 at 11 52 57" src="https://user-images.githubusercontent.com/151272/149325568-7c8e81e9-e7e6-4feb-941f-d2eb7d9e2880.png">

**Comment by ad1992** [comment]
+1, sounds like a good addition, similar to Miro

**Comment by KeenShubham** [comment]
We would need to add some options in the text, correct?
We do support vertical alignment through [`newTextElement`](https://github.com/excalidraw/excalidraw/blob/master/src/element/newElement.ts#L120), right?
![image](https://user-images.githubusercontent.com/52590791/153163868-883b08e7-3f38-4c70-8a82-2f0f65f6592e.png)

**Comment by ad1992** [comment]
We can show the buttons for vertical alignment under the text alignment section. Right now we only support vertical-align `middle`, we need to support `top` and `bottom` as well and this would be just for bounded text containers

**Comment by ad1992** [comment]
closed via #4852
