### ISSUE TITLE
Delete entire words with ctrl + backspace

### ISSUE THREAD

**Issue by mortenfyhn** [excalidraw/excalidraw#4587]
When editing text, it would be nice to be able to delete entire words by hitting ctrl + backspace. This is a common keyboard shortcut in many application. I imagine many others in addition to myself use it frequently, and are trying to use it in Excalidraw.

In any case, thank you for this useful application!

**Comment by dwelle** [comment]
I just noticed this. It's a recent regression. We'll fix asap!
