### ISSUE TITLE
Ability to share drawings within the app via a link

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw#459]
### The design

- [ ] New share button (the final position to be determined)
- [ ] When the button is pressed:
- [ ] A pop up appears with the preview of the image and one button in the bottom that says `Click to generate` and following text caption: `Click to generate will upload the scene to http://json.excalidraw.com.`
- [ ] When `Click to generate` is pressed there should be a POST request with the JSON of the scene to `https://json.excalidraw.com/api/v1/post/` and read back `hash` from the response. Read more: https://json.excalidraw.com.
- [ ] Once the response is ready, the `Click to generate` disappears and instead there is an input box with the sharable URL: `https://excalidraw.com?json= cf441c7b5846d0d234c411538b703079` with an option to copy to clipboard.
- [ ] When user enters the URL with a `json` argument (`https://excalidraw.com?json= cf441c7b5846d0d234c411538b703079`) we should load the drawing with a given `json` from: `https://json.excalidraw.com/api/v1/cf441c7b5846d0d234c411538b703079.json`

### Comments

- Maybe instead of separate button, having the sharable link when exporting as image.
- In the future we might support other providers like Google Drive, Dropbox, etc..

### Screenshot

<img width="629" alt="Screenshot 2020-01-19 at 11 37 16 PM" src="https://user-images.githubusercontent.com/125676/72688919-a7dec280-3b14-11ea-8070-2a45a62d7e67.png">

### Notes

For any suggestions or changes to the backend (https://json.excalidraw.com) file issues directly in that repo https://github.com/excalidraw/excalidraw-json/issues

**Comment by lipis** [comment]
https://github.com/excalidraw/excalidraw/pull/356

**Comment by vjeux** [comment]
On most occasions I think that we should streamline the UI and remove steps but this is not one of them. People are creating sensitive things with excalidraw and we should not upload their content to a third party server without an explicit action on their part.

Whoever designs the flow mentioned in this issue, please keep this in consideration.

**Comment by lipis** [comment]
I updated the description to reflect that.

**Comment by AlanBreck** [comment]
Is there a way of deleting the JSON for a shareable link after being created?

**Comment by dwelle** [comment]
Not currently. We (I) were thinking of giving you 2 links, one read-only, and one admin. The admin link would allow you to delete it later. But it was adding too much unnecessary complexity.

If you haven't shared the link anywhere, you should rest easy that no one will be able to read it (the encryption is good, the key entropy is high).

For the future, if this use case is something you really want, I'd suggest https://plus.excalidraw.com (paid).

**Comment by dwelle** [comment]
@AlanBreck nevertheless, our policy so far is to comply with such requests. So if you send me the `id` (the part of the `#json` string that's before the comma (`https://excalidraw.com/#json=id,key`), we will remove the link for you.

**Comment by devnoname120** [comment]
@lipis Do you have updates with regard to a Dropbox integration for Excalidraw+? Ideally, I would like something that automatically exports all the drawings as PNG and upload them in a Dropbox folder.

Even better if there is a Dropbox Paper integration! It would be amazing to do live collaboration on Excalidraw drawings right from a [Dropbox Paper document](https://techcrunch.com/2015/10/15/dropbox-announces-paper-a-google-docs-competitor/).
