### ISSUE TITLE
Remove NOW, since we are using Netlify

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw#461]
I think at this point is not needed and it produces a lot of noise with posting messages everywhere.

**Comment by Fausto95** [comment]
Yeah, go for it

**Comment by dwelle** [comment]
Yay! The notifications from ZEIT are annoying.

**Comment by lipis** [comment]
@vjeux?

**Comment by vjeux** [comment]
Can we still see a preview without zeit? I use the annoying comment (i created a filter for it in my emails...) to preview pull requests

**Comment by lipis** [comment]
There is preview with Netlify too..

<img width="731" alt="Screenshot 2020-01-20 at 2 15 39 AM" src="https://user-images.githubusercontent.com/125676/72691044-cf408a00-3b2a-11ea-81f9-a5f04f1e57d9.png">

**Comment by lipis** [comment]
Without any comment... it's just there!

**Comment by lipis** [comment]
> Can we still see a preview without zeit? I use the annoying comment (i created a filter for it in my emails...) to preview pull requests

Also I'm not using emails for GitHub notifications.. using the UI and it's impossible to filter them.

**Comment by vjeux** [comment]
Now has the advantage of being ready within seconds of the pull request being published/updated. It seems like it takes a few minutes for netlify.

**Comment by lipis** [comment]
I disabled post processing.. should be faster now.. but still a bit slower than NOW.

**Comment by GrimTheReaper** [comment]
One of the nice parts of the comments though, is that it gives you the link then and there. With netlify you have to go down and click on details.

**Comment by lipis** [comment]
Regular contributors now will eventually learn about it. Netlify is quite popular so it's not a huge issue.

**Comment by vjeux** [comment]
We'll keep `now` for now. The links are really handy.
