### ISSUE TITLE
Rectangle automatic expansion due to middle-inserted text moves the cursor to the end of the text

### ISSUE THREAD

**Issue by ronlib** [excalidraw/excalidraw#4617]
![image](https://user-images.githubusercontent.com/7414411/149845311-ff995233-33ba-49aa-8769-414c4638d14d.png)

In the image: this is what happens when I type "word " 4 times (the last iteration is done when I move the cursor to be before the last word).

Reproduce:
1. Write inside a rectangle that has room for 1 line.
2. Before you hit the second line, start writing **before** the last word until the rectangle expands into 2 lines.
3. Watch as the cursor jumps to the end of the last word, no matter where it was.

**Comment by locofocos** [comment]
Here's a video demonstrating the issue. After I type all the `h` letters, I use the arrow keys to move my cursor and then type `qwer`. Notice how `qwer` is incorrectly split up.

https://user-images.githubusercontent.com/4809268/155026964-ef9c4f70-2b5b-4469-ad91-59db4eeaa887.mp4

**Comment by locofocos** [comment]
Temporary workaround: manually increase the height of the rectangle so that typing more text does not need to increase the height of the box.
