### ISSUE TITLE
Error trying to drag&drop selected text inside a text element

### ISSUE THREAD

**Issue by keul** [excalidraw/excalidraw#4621]
After selected text inside a text element by mistake I had been able to generate an error.

![error](https://user-images.githubusercontent.com/284924/149941603-9a55ba8a-e074-41ba-8d8a-9a2cc473e809.gif)

There's not other visible error in the browser's console.

Attached also the used excalidraw.

[error.excalidraw.zip](https://github.com/excalidraw/excalidraw/files/7889212/error.excalidraw.zip)

Problem reproduced in Firefox 96.0.1

**Comment by dwelle** [comment]
fixed via https://github.com/excalidraw/excalidraw/pull/4890
