### ISSUE TITLE
whenever i try to open excalidraw editor..then some console error is showing 

### ISSUE THREAD

**Issue by sohailamjad256** [excalidraw/excalidraw#4623]
Hi @ad1992 
**!important**
 whenever i try to open excalidraw editor..then some console error is showing and also in excalidraw editor loading scene is showing ..please help..i am attaching the console error image and excalidraw canvas image 
![error](https://user-images.githubusercontent.com/53993286/150283521-09cfcfc4-d26b-4ca5-8510-3b607507ca6e.png)
![loading scene](https://user-images.githubusercontent.com/53993286/150283577-14c54345-9328-432f-878c-17a305124e09.png)

**Comment by ad1992** [comment]
@sohailamjad256 as mentioned in the console error, the data you are passing as `elements` is not an array hence the error. Make sure the `elements` is an array.

**Comment by sohailamjad256** [comment]
> @sohailamjad256 as mentioned in the console error, the data you are passing as `elements` is not an array hence the error. Make sure the `elements` is an array.

close this issue please
