### ISSUE TITLE
resizing to close to 0 width/height locks up the shape size

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#4625]
sometimes it reproduces on first try, sometimes it's a bit harder:

![excal-bug-0-width-resize-bug](https://user-images.githubusercontent.com/5153846/150379526-e8e40482-75af-47aa-8dc2-e88c829435da.gif)

Applies to all shape types. Must be a recent regression.

**Comment by dai-shi** [comment]
related? #1610 (old freedraw)

**Comment by 0prodigy** [comment]
I want to understand the real problem so i can start working on that. I found this is only with ``WIDTH`` and but works perfect with ``HEIGHT``. Can anyone help me from where should i start tracking this issue cause or any suggestion

**Comment by dwelle** [comment]
I think it may be related to https://github.com/excalidraw/excalidraw/pull/4343 (not necessarily the PR itself, but even later commits related to it). At least I couldn't repro on commits before.

You can bisect the culprit deploy by going through the [commits](https://github.com/excalidraw/excalidraw/commits/master) and checking their vercel preview:

![image](https://user-images.githubusercontent.com/5153846/151722028-0ad1e2b6-9770-48e1-9929-ac1ab0a86cc8.png)

![image](https://user-images.githubusercontent.com/5153846/151722038-ef046f67-a2f1-40f0-8d3b-5c8cc257ffe1.png)

**Comment by dwelle** [comment]
> related? #1610 (old freedraw)

missed your comment. I'd have to do a deeper dive, but I think it's very recent.

**Comment by ceceliacreates** [comment]
@dai-shi @dwelle This may also be related to #1610, because it looks like the width there is `-Infinity`.

**Comment by ad1992** [comment]
fixed via #4804, feel free to reopen if it still exists
