### ISSUE TITLE
Issue with the popular "Minimal Theme"

### ISSUE THREAD

**Issue by jenshda** [excalidraw/excalidraw#4652]
## Issue
The minimal theme hides the top bar unless you bring your mouse to the top. This usually shows the top bar again, but this does not work in Excalidraw. As the top bar is the only way to enter the script store this causes issues. 

### Minimal Theme
1. Screenshot of normal empty document when top bar is hidden
<img width="1280" alt="Screenshot 2022-01-25 at 10 30 52" src="https://user-images.githubusercontent.com/83638075/150950228-fbe2b55c-a7cf-46ee-b481-13aa04fab4e1.png">
2. Screenshot of normal empty document when top bar is revealed through dragging the mouse to the top of the document
<img width="1280" alt="Screenshot 2022-01-25 at 10 30 58" src="https://user-images.githubusercontent.com/83638075/150950231-05399524-ce92-489d-b3f8-d43b48ff1fc2.png">
3. Excalidraw with minimal theme does not reveal top bar when dragging the mouse to the top making the top bar inaccessible using the minimal theme. 
<img width="1280" alt="Screenshot 2022-01-25 at 10 31 30" src="https://user-images.githubusercontent.com/83638075/150950233-29c40da1-9a6b-4b04-a254-7a8a192d3d43.png">

### Yin-Yang Theme
4. With another theme the top bar is visible again. 
<img width="1280" alt="Screenshot 2022-01-25 at 10 31 49" src="https://user-images.githubusercontent.com/83638075/150950234-100b7cfb-f431-4274-ac94-6e7e0b528d86.png">

## Solution
A work around could be to add another entry point into the top bar items for better access and redundancy, even if it would be great if the reveal function worked with Excalidraw.

**Comment by dwelle** [comment]
Hello, Is this related to https://github.com/zsviczian/obsidian-excalidraw-plugin?

**Comment by jenshda** [comment]
Yes! I'm sorry! I'll move this where it belongs
