### ISSUE TITLE
Cannot copy to clipboard as PNG any more

### ISSUE THREAD

**Issue by inwardmovement** [excalidraw/excalidraw#4659]
Copy to clipboard as PNG does not work any more in Firefox.
Any plan to fix this regression?

![image](https://user-images.githubusercontent.com/9438102/151589960-f76cef83-0662-4cc0-8ca9-9c1ba8fcdacb.png)

**Comment by dwelle** [comment]
Did it ever work?

> From version 87: this feature is behind the `dom.events.asyncClipboard.clipboardItem` preferences (needs to be set to true). To change preferences in Firefox, visit `about:config`.

https://developer.mozilla.org/en-US/docs/Web/API/ClipboardItem

**Comment by inwardmovement** [comment]
Yes I clearly recall using it, and seeing the two options (SVG + PNG) in the menu, strange...
Thanks, I toggled the config setting and it works now.
