### ISSUE TITLE
Undefined showed after leaving blank a text zone

### ISSUE THREAD

**Issue by Volubyl** [excalidraw/excalidraw#468]
👋 Just to report an issue.

I created a text zone. I erased the content and then I left the text zone blank. At the same location as the text zone, `undefined` is displayed.

I'm unable to edit or erase this `undefined` text. Another text zone is created.

Here is a small gif which show what I did :

![smallbug](https://user-images.githubusercontent.com/15958334/72720160-a693b100-3b79-11ea-874d-a2ac9eb23069.gif)

**Browser** : Firefox Developer Edition 73.0b6 (64bits)
**OS** : Mac OS 10.14.6

**Comment by lipis** [comment]
If the text is blank.. It should be deleted

**Comment by Volubyl** [comment]
or I should be able to edit the text zone (but the risk is to leave a lot of "empty" text box inside the DOM)

**Comment by lipis** [comment]
I'd it's not visible.. We don't need it

**Comment by dwelle** [comment]
It then blows the whole app upon refresh, and you must manually clear `localStorage`.
