### ISSUE TITLE
`Shift` + ` -` zoom: Can't use underscore

### ISSUE THREAD

**Issue by jpy-git** [excalidraw/excalidraw#4680]
When I create text and try to type an underscore (`Shift` + ` -`) the screen zooms out instead. Likewise for equals (`Shift` + ` +`) the screen is zoomed in. Looking at the shortcuts it should be `Cmd` + ` -`/`+` that handle this not `Shift`, both currently seem to work.

I'm pretty sure I didn't have this issue when I used the website the other day, so not sure what changed. I double checked on another laptop and have the same issue there as well.

**Comment by randomarno** [comment]
I have the same issue on a French Keyboard layout, `Shift `+ `+` should produce a +, instead it zoom in. `Shift `+ `)` should produce a °, instead it zooms out.

**Comment by dwelle** [comment]
Ooops. Fixing coming in!

**Comment by dwelle** [comment]
Thanks for the report @jpy-git @randomarno!

**Comment by jpy-git** [comment]
@dwelle amazing, thanks for the quick fix and awesome project! 😄
