### ISSUE TITLE
Manually set the size of a shape [ feature request ]

### ISSUE THREAD

**Issue by mrkoz** [excalidraw/excalidraw#4693]
As per: https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/367

I would like to be able to set the size of a shape in the text box, at the moment it seems like i can only change the size by dragging the handles. For example if i create a box, i'd like to set the PX size manually.

It would be nice to be able to edit the shape stats in the "stats for nerds" pane by clicking on them.

In the original issue - it was mentioned that this can be done using the script engine which is a great workaround!

**Comment by dwelle** [comment]
closing in favor of https://github.com/excalidraw/excalidraw/issues/5932
