### ISSUE TITLE
Add link button not available on mobile panel

### ISSUE THREAD

**Issue by zsviczian** [excalidraw/excalidraw#4697]
at least I can't seem to find it...

https://user-images.githubusercontent.com/14358394/152436681-fec9b858-413c-4c24-8f56-62c3ba9ffc21.mp4

**Comment by ad1992** [comment]
Yeah right now the way in mobile is via context menu. We should add "link, group/ungroup" under actions in the mobile selected shapes panel.

**Comment by dwelle** [comment]
Let's render the actions in the properties panel same as on desktop (at least whatever actions we don't already display in the mobile toolbar).
