### ISSUE TITLE
Privacy policy please

### ISSUE THREAD

**Issue by kaihendry** [excalidraw/excalidraw#4698]
I'm drawing potentially sensitive info on excalidraw. Can I have confidence it's private?

https://twitter.com/kaihendry/status/1487961156363108354

**Comment by ad1992** [comment]
Replied in the tweet, here is the blog on end to end encryption is handled https://blog.excalidraw.com/end-to-end-encryption/

**Comment by kaihendry** [comment]
That post doesn't describe how long live session URLs are alive for https://excalidraw.com/#room=b5db242f4fe07c826f6a,o95_Gq6x0eGk895A6kzILw

Is there no risk that this URL will be leaked? 

Ideally the room is perhaps cleared up after a period of inactivity?

**Comment by ad1992** [comment]
As long as you can keep the URL safe, it would not be possible to guess/access the url (as the entropy is quite high 16^22) and the keys are not saved on backend servers and decryption happens on client side.
The collaborations sessions are persisted so you can always come back and update your drawings
