### ISSUE TITLE
export hyperlinks to SVG image map

### ISSUE THREAD

**Issue by zsviczian** [excalidraw/excalidraw#4699]
like this:

![Untitled-2022-02-03-0917](https://user-images.githubusercontent.com/14358394/152507883-7c89dde1-5237-49c4-892f-34e120a22c8a.svg)

![image](https://user-images.githubusercontent.com/14358394/152508331-efeff2f0-e68a-41e7-a5ce-260e027dad58.png)

```html
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" viewBox="0 0 386 135" width="386" height="135">
  <!-- svg-source:excalidraw -->
  <a xlink:href="https://www.youtube.com/channel/UCC0gns4a9fhVkGkngvSumAQ">
      <rect x="0" y="0" width="386" height="135" fill="#ffffff"></rect><g stroke-linecap="round" transform="translate(10 10) rotate(0 67.5 57.5)"><path d="M1.14 -1.07 C27.95 1.32, 57.81 0.58, 136.13 1.63 M-0.76 0.31 C30.96 0.37, 63.12 -0.05, 134.14 0.7 M134.97 1.21 C134.75 43.38, 134.99 85.96, 133.63 113.43 M135.03 -0.09 C136.31 45.63, 136.42 90.2, 134.05 115.17 M133.37 115.88 C86.56 115.19, 32.43 113.78, 0.62 115.34 M134.92 114 C98.66 114.36, 63.26 113.14, -0.54 114.6 M1.81 115.84 C1.48 77.05, 1.75 40, -1.16 0.54 M0.55 115.76 C-0.47 87.75, 1 59.98, 0.05 0.59" stroke="#000000" stroke-width="1" fill="none"></path></g>
  </a>
  <a xlink:href="https://excalidraw.com">
      <g transform="translate(201 59) rotate(0 87.5 12.5)">
      <text x="0" y="18" font-family="Virgil, Segoe UI Emoji" font-size="20px" fill="#000000" text-anchor="start" style="white-space: pre;" direction="ltr">link to Excalidraw</text></g>
  </a>
  </svg>
```

**Comment by ad1992** [comment]
Do you mean links to be part of export ?

**Comment by zsviczian** [comment]
exactly

**Comment by dwelle** [comment]
I suppose we should only wrap into `<a>`, but don't render any link icons in this case?

**Comment by ad1992** [comment]
I think it would be better to render the link icon and wrap it in anchor tag, that way the look and feel will be same as it is in the editor as well.

**Comment by dwelle** [comment]
> I think it would be better to render the link icon and wrap it in anchor tag, that way the look and feel will be same as it is in the editor as well.

But the SVG export is for embedding/display purposes, not editing. So it's analogous to a PNG export.

**Comment by JRJurman** [comment]
Hello - I made a PR for this, if there's anything I can / should do, would love any reviews or feedback!

For now, there's no visual icon for the hyperlink, I think that's something that can be done in a follow up PR if that is really wanted (personally I'd rather not have it, and it seems like there are some issues / contentions about how it should be presented) - also this was easier to do without it 😆.

I'm actually hoping to get this merged in for work purposes, specifically for building C4 diagrams, and this feature would be a huge win for making that happen!

**Comment by JRJurman** [comment]
For my two cents, I think that there are other ways (such as color or font-decoration) that could be used to make linked objects obvious when they are exported to svg, and that can be done when building.

I like the idea that SVG mimics the PNG export, rather than the editor experience. 

And finally, I think if an icon would be additional work / potentially a breaking change, I think it is worth it to release just the link functionality, and then follow up with additional icons.

**Comment by zsviczian** [comment]
@JRJurman, I 100% agree.
If I want an image map on which links are obvious and highlighted, I will draw such a drawing. Else links should not be marked in the export with an icon.

**Comment by Shoggomo** [comment]
I think a visual presentation should be a separate discussion, that will only become relevant, when a basic export is available.
Your PR @zsviczian looks good to me. I would say, when this is approved, further discussions can start.
At least that's my view. I try to keep the scope of discussions small, before they get too cluttered.

**Comment by JRJurman** [comment]
I would love any advice for next steps, I see this `First-time contributors need a maintainer to approve running workflows` so I'm not really sure who I should be asking or how we move this PR forward 😅

**Comment by Shoggomo** [comment]
I wrote the team on discord and your workflows are running now. Now you need someone to review your PR. You could request a review from @dwelle or @ad1992.
