### ISSUE TITLE
mobile context menu won't show on long press

### ISSUE THREAD

**Issue by zsviczian** [excalidraw/excalidraw#4739]
At first I thought this was only Obsidian relevant, but after some testing the issue is there with excalidraw.com as well.
Long press on canvas in mobile view, and the context menu does not show.

https://twitter.com/onesentforth/status/1490661988221005830?s=20&t=YewwD_nu934eVNS7O8n2Fg

**Comment by dwelle** [comment]
What OS & browser? I can't repro on Android (Chrome) or iPad (Chrome & Safari).

**Comment by zsviczian** [comment]
I am on Android 9 with Chrome browser. It worked a few releases ago. It will take a bit of time to track back to the point it broke, but I can investigate if it helps...

**Comment by zsviczian** [comment]
on the same mobile, on Firefox the context menu shows. On Chrome, Chrome beta and Edge it does not.

**Comment by onesentforth** [comment]
Context menu is not working on Android 12 using Edge 97.0.1072.78 or Chrome 98.0.4758.87

**Comment by zsviczian** [comment]
I will create a PR to test this.
