### ISSUE TITLE
Expose sharable link button in the top left corner.

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw#476]

**Comment by dwelle** [comment]
Top-left is even more crowded. Or you want to put it inside the menu? That will wrap the icons.

**Comment by dwelle** [comment]
Also, what should it do? Export with the currently-enabled settings (e.g. `exportBackground`...)?

**Comment by lipis** [comment]
Yes export the whole scene with a background setting.. and show the copied to clipboard message.

I think we can have an example with 5 buttons there and examine.. maybe hiding open/save to json under the export popup. Making it import/export
