### ISSUE TITLE
LINK KO ON CHROME EDGE when I'm signed on excalidraw

### ISSUE THREAD

**Issue by eho9734** [excalidraw/excalidraw#4789]
When I click on an object with a link (Ctrl+K on an object) > it doesn't work !!! 

The only way to make it work is to click on the text link when you can edit/remove it.

Test it on free excalidraw and excalidraw +

**Comment by dwelle** [comment]
Hey @eho9734 — I've tested on Chrome & Edge (Windows 10) and it work in both apps. I assume you're on Windows as well?

Also, can you share the excalidraw version? You can view it when you open the stats for nerds (righ-click on canvas):

![image](https://user-images.githubusercontent.com/5153846/154088527-7114dfc3-441a-495a-a478-bb7e3594fe49.png)

**Comment by eho9734** [comment]
![image](https://user-images.githubusercontent.com/97898017/154199387-5eff5016-5371-471e-a4b5-e409f8873cdb.png)
Hello...
I can't read excalidraw version on my screen... i'm using Excalidraw plus

**Comment by ad1992** [comment]
In Excalidraw plus we use the excalidraw npm package which is already versioned so we don't show it in host. 
Is there any specific reason you are expecting the version here ?

**Comment by eho9734** [comment]
i have problems with links

----
When I click on an object with a link (Ctrl+K on an object) > it doesn't work !!!
The only way to make it work is to click on the text link when you can edit/remove it.
Test it on free excalidraw and excalidraw +
---
---
Dwelle ask me for version number
---
--

forget to tell you i'm on W11 laptop

**Comment by dwelle** [comment]
@eho9734 I have misread the issue. Ok, there was indeed a recently introduced bug on Excalidraw Plus. Now fixed.

It wasn't clear if you are experiencing the issue one excalidraw.com as well?

Also note, that in edit mode, only clicking on the link icon will redirect. If you want to click on the element itself, you'll need to be in view mode. But I assume you are aware, and were instead blocked on the aforementioned bug.

Thanks for the report!

**Comment by eho9734** [comment]
Thanks 

it's all right now ! 👍

**Comment by dwelle** [comment]
Glad to hear!
