### ISSUE TITLE
Clicking on shape tool prevents keyboard shortcuts

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#479]
Except for `Esc`, which is handled before we bail here:

https://github.com/excalidraw/excalidraw/blob/183a62627c529708b0f7c71bebe6f5431b710463/src/index.tsx#L286

Also affects other UI input-like elements which we still might want to not lock shortcuts (such as Opacity slider)

![excalidraw_focus_keyboard_bug](https://user-images.githubusercontent.com/5153846/72757234-b8a03e80-3bcf-11ea-8ef4-5962a5d3b6e1.gif)

**Comment by muzakparov** [comment]
made keyboard shortcuts work, but _outline_ which appear when tool icons are clicked on don't change or disappear
![image](https://user-images.githubusercontent.com/26898520/73140204-3f00c880-4087-11ea-9a14-791154f58ae2.png)

**Comment by dwelle** [comment]
You can manually `blur()` the button. And potentially `.focus()` the new one (@voluntadpear what's your a11y standpoint on this?).

Make a PR and we'll look at it.

**Comment by voluntadpear** [comment]
Manually blurring and focusing is fine for accessibility 👍

**Comment by muzakparov** [comment]
will submit PR for fix soon then
