### ISSUE TITLE
android app workflow to open and save drawings?

### ISSUE THREAD

**Issue by aisbergde** [excalidraw/excalidraw#4823]
I am trying to use the excalidraw Android app and to find an easy way to work with files in folders other than "download".

- I can only save a drawing using the "export" feature.
- this feature allows only to enter a filename and to press "save as file"
- this will save the file in the download folder, and I can't see a way to select a different folder.
- now I need to use a file explorer to copy or move the drawing to the target folder, for example to a working folder of a cloned git repository, so I can take it under source control

I am looking for a way:

- to open the file from a specific location (this is possible)
- to "save" and to "save as", like I would do in a text editor.  
But it looks like the only way is to export the file again, then it will be a new copy in the downloads folder and so on.
- I think this workflow is complicated.
- it would also be fine if the file extension could be associated with the app so it would be possible to use a file explorer to locate drawings and to just open the files from there in the app.

**Comment by dwelle** [comment]
> to "save" and to "save as", like I would do in a text editor.
But it looks like the only way is to export the file again, then it will be a new copy in the downloads folder and so on.
> [...]
> it would also be fine if the file extension could be associated with the app so it would be possible to use a file explorer to locate drawings and to just open the files from there in the app.

I believe features both require Chrome(ium) flags (as the APIs aren't stable yet) which you can't set on the mobile browser :(

**Comment by tomayac** [comment]
Currently there is no [File System Access](https://web.dev/file-system-access/) API support on Android, which means we fall back to `<a download>` (via [browser-fs-access](https://github.com/GoogleChromeLabs/browser-fs-access)). Getting proper support for the API on Android is tracked in https://crbug.com/1011535.

Proper [File Handling](https://web.dev/file-handling/) via file type association is currently only launched on desktop operating systems (still behind a flag). Your best bet is probably [Web Share Target](https://web.dev/web-share-target/), which Excalidraw implements.

**Comment by aisbergde** [comment]
it is good to know, why it is as it is.
My main usage will be on the desktop 🤔

In General I think the idea to develop one browser app for all platforms is a good idea, to concentrate the power on one product.

**Comment by tomayac** [comment]
Feel free to comment on the Android bug, especially describing your complex workaround that the lack of implementation of this API forces you on.
