### ISSUE TITLE
Can't add text in the middle of the text in a rectangle

### ISSUE THREAD

**Issue by Szureka** [excalidraw/excalidraw#4844]
When I want to modify some text in a rectangle when there's already a text, after some letters it skips to the bottom of the rectangle. Very frustrating.

**Comment by ad1992** [comment]
@Szureka can you share a recording for better context?

**Comment by dwelle** [comment]
I have a feeling it's related to https://github.com/excalidraw/excalidraw/pull/4655 — I forgot to wrap it up. I have a local diff fixing more things.

**Comment by Szureka** [comment]
Hi,

Hmm, I don't think so. This problem happens only in a paid version which
I'm using. Here is the screenshot presenting the issue:

[image: image.png]
There was some text on top and on the bottom of the container. I was
writing in the middle all the time word "test". Suddenly it jumped to the
bottom, just right behind the word "text".

It's very frustrating, almost a deal breaker for me because I often write
like this.

Best regards,
Adam Szurek

**Comment by Szureka** [comment]
And there's a video in an attachment.

Best regards,
Adam Szurek

**Comment by ad1992** [comment]
@Szureka unfortunately the video/image didn't upload, can you try uploading again ?

**Comment by Szureka** [comment]
Here's the link: https://we.tl/t-1t2O9QirAD

Best regards,
Adam Szurek

**Comment by dwelle** [comment]
Hey @Szureka. The issue you are facing should be fixed now (you'll need to reload your browser), can you try again if you can reproduce?

**Comment by Szureka** [comment]
I confirm, it works. Thanks for your quick response.

BTW. great tool, hope it stays as clean as it is.
