### ISSUE TITLE
Recently stored or loaded IDs, save in the local storage for later retrieval.

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw#485]
Something like that in the bottom left or right corner

<img width="243" alt="Screenshot 2020-01-21 at 2 08 50 AM" src="https://user-images.githubusercontent.com/125676/72765021-1d20c500-3bf3-11ea-9e69-52a2befb1bb7.png">

https://excalidraw.com/?id=5738294193160192

**Comment by nosnibor89** [comment]
Hi @lipis , I will like to help with this. Has anyone started with this yet? 
I think we need to place this dropdown at the bottom left corner as we already have the Language dropdown in the bottom right one 🙂 .

**Comment by lipis** [comment]
We can start and iterate on the design later.. sure.. go for it!

**Comment by lorisdev** [comment]
It would be great to be able to give a name to the ids as well !

**Comment by lipis** [comment]
Maybe on the next iteration.. if we'll start storing the name in the JSON
