### ISSUE TITLE
The preview doesn't respect horizontally flipped images

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#4850]
Repro:
* Insert an image
* Right click / flip horizontally
* The view on excalidraw works fine
* Click on the export to image icon
* The view doesn't show the image flipped
* Click copy to clipboard, it doesn't have the image flipped either

**Comment by dwelle** [comment]
Yeah, this is actually not just export preview, but SVG export in general. The CSS transforms get really messy when scale & rotation is applied.

**Comment by lvl0-i74134** [comment]
Yes, all flipped images are exported in the original view for png files.
