### ISSUE TITLE
excalidraw errors

### ISSUE THREAD

**Issue by sohailamjad256** [excalidraw/excalidraw#4861]
Warning: Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.
    in App (created by Excalidraw)
    in InitializeApp (created by Excalidraw)
    in Excalidraw (created by ForwardRef)
    in ForwardRef
    in ForwardRef (created by App)
    in div (created by App)
    in App
    in div

can you please explain what is this issue

**Comment by ad1992** [comment]
This error will happen when you are trying to update some state on a component that is not mounted, however this isn't critical as such, closing this in favor of https://github.com/excalidraw/excalidraw/issues/4679
