### ISSUE TITLE
excalidraw-utils 0.1.1 ReferenceError: React is not defined

### ISSUE THREAD

**Issue by JRJurman** [excalidraw/excalidraw#4865]
When trying to import the latest version of excalidraw-utils, an error is thrown on the page, expecting React to be defined. This appears to be a regression, as this error did not occur in version `0.1.0-temp`

Repo to Reproduce issue: https://github.com/JRJurman/test-excalidraw-utils

[With excalidraw-utils `0.1.0-temp`](http://jrjurman.com/test-excalidraw-utils/excalidraw-utils-0.1.0.html)
![image](https://user-images.githubusercontent.com/326557/156669284-60ed825d-ce5d-4689-998f-8263c4bbaa66.png)

[With excalidraw-utils `0.1.1`](http://jrjurman.com/test-excalidraw-utils/excalidraw-utils-0.1.1.html)
![image](https://user-images.githubusercontent.com/326557/156669243-db7d17b3-fbea-416b-a279-c0210d992132.png)

**Comment by JRJurman** [comment]
An initial hypothesis here, this dependency on React may have been introduced when exporting with [Dark Mode Export became available](https://github.com/excalidraw/excalidraw/pull/3046). It looks like the app tries to create the SUN / MOON icons, and fails which are react elements.

![image](https://user-images.githubusercontent.com/326557/156684280-d7228dec-09b1-48df-8cfc-06f14bdb5655.png)

That being said, while that is where this code fails, it looks like there are other references to `React.createElement` in the bundle now as well :thinking:

**Comment by JRJurman** [comment]
It is possible to have this work by including React, however the interface also appears to have changed, as exportToSvg now returns a promise? I was able to get it to work in the following example:

https://github.com/JRJurman/test-excalidraw-utils/blob/master/excalidraw-utils-0.1.1-with-react.html
http://jrjurman.com/test-excalidraw-utils/excalidraw-utils-0.1.1-with-react.html

**Comment by JRJurman** [comment]
After doing a git bisect, it appears this is the first commit where React became a dependency: https://github.com/excalidraw/excalidraw/commit/4b5270ab12bf13c2e8def10f5e264afea4e13bab

Additionally, it appears that this is the first commit where the interface for `exportToSvg` changes from being synchronous to asynchronous: https://github.com/excalidraw/excalidraw/commit/f861a9fdd044e72e5b528c6e2d3da619e78cce05

Honestly I think these can both be worked around with a documentation update. The React one seems odd since there's nothing clearly in the export flow that requires React, so ideally that one could be fixed. The promise one is most-likely fine since it's fairly trivial to work around, but it wasn't clear to me if that change was intentional or not.

**Comment by JRJurman** [comment]
After doing a git bisect, it appears this is the first commit where React became a dependency: https://github.com/excalidraw/excalidraw/commit/4b5270ab12bf13c2e8def10f5e264afea4e13bab @dwelle 

Additionally, it appears that this is the first commit where the interface for `exportToSvg` changes from being synchronous to asynchronous: https://github.com/excalidraw/excalidraw/commit/f861a9fdd044e72e5b528c6e2d3da619e78cce05 @ad1992 

Honestly I think these can both be worked around with a documentation update. The React one seems odd since there's nothing clearly in the export flow that requires React, so ideally that one could be fixed. The promise one is most-likely fine since it's fairly trivial to work around, but it wasn't clear to me if that change was intentional or not.

**Comment by ad1992** [comment]
@JRJurman should work now in `@excalidraw/utils@0.1.2`
