### ISSUE TITLE
Paste Style does not work with keyboard shortcuts

### ISSUE THREAD

**Issue by zsviczian** [excalidraw/excalidraw#4884]
Issue was originally recorded for the Obsidian plugin [#506](https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/506), but after some testing @Missionary2112 confirmed the same issue on https://excalidraw.com

### Describe the bug
I can copy style using keyboard shortcuts (option + command + C), but I cannot paste style with the shortcut (option + command + V)
However, it does work when I right-click and choose the option in the popped up menu

### To Reproduce

Use keyboard shortcut (option + command + C) to copy style
Use keyboard shortcut (option + command + V) to paste style
See error: Cannot paste style

### Environment
OS including version: macOS Monterey Version 12.2.1
Browser: Safari 15.3 
Keyboard: magic keyboard from MacBook Pro 2019

**Comment by dwelle** [comment]
I noticed this a few days ago as well. Not sure how it broke, but here's a fix https://github.com/excalidraw/excalidraw/pull/4886
