### ISSUE TITLE
in excalidraw canvas image is not showing after saving the image 

### ISSUE THREAD

**Issue by sohailamjad256** [excalidraw/excalidraw#4885]
Hiii... i have added image in   excalidraw canvas  an
[image is not showing after saving.zip](https://github.com/excalidraw/excalidraw/files/8196909/image.is.not.showing.after.saving.zip)
d image is not showing after saving the image ..iam attaching video clip

**Comment by sohailamjad256** [comment]
and can i load files with initial data to show image again in the canvas

appState: { viewBackgroundColor: "#f2f4f5", currentItemFontFamily: 1 },
    **files: {},**
    scrollToContent: false,

**Comment by sohailamjad256** [comment]
i tried  passing files with initial data ..it will work to show image in the canvas?

**Comment by sohailamjad256** [comment]
got the issue and resolved thanks

**Comment by ad1992** [comment]
closing this as its resolved

**Comment by DineshCodeFlow** [comment]
Could you guide me how you were able to resolve the issue?
I am facing the same issue, don't know what to do?

**Comment by seAfnan** [comment]
I am also facing the same issue.
I am saving elements, state, files in mongodb. When i get data then it fetch correctly, but not showing image, just shows skeleton just like above issue raiser video.
