### ISSUE TITLE
Idea: Save/Open drawings embedded in image files (e g mydiagram.excalidraw.png )

### ISSUE THREAD

**Issue by chipbite** [excalidraw/excalidraw#4891]
# Idea: Save/Open drawings embedded in image files (e g mydiagram.excalidraw.png )

Similar to what draw.io / diagrams.net does - make it so that excalidraw can save and open files locally as embedded image files, i e: The excalidraw drawing is embedded into e g the `.png` or `.svg` file. And conversely, excalidraw can open these files.

It makes for several benefits: 
* Adding drawings / images to a git repo, and referring to them in .md files, without having to bother with a separate source file for the drawing.
* Thumbnails. Most file UI navigating environments will show you a thumbnail of the `png`.
* A really simple way to store drawings, and ensure that the drawing source is not separated from the image.
etc

**Comment by dwelle** [comment]
Hey @chipbite, this is already implemented:

![image](https://user-images.githubusercontent.com/5153846/157491164-c82e1a5c-b220-4b13-ac54-0e287f5e32e8.png)

Would you have a suggestion for a better name so it is more obvious?

**Comment by chipbite** [comment]
Awesome! *duh* So sorry I missed this! 

I'll find my own way out now... ;-)

**Comment by chipbite** [comment]
Hmm, but I get this when trying to open the .excalidraw.png:
![image](https://user-images.githubusercontent.com/559199/157492383-7a047404-75e9-49fa-ae22-599cb03b3541.png)
Is there a special step? I used "Load"...

**Comment by dwelle** [comment]
That is strange. The error message would suggest the image contains the data but they couldn't be decoded for some reason. If the drawing isn't private, can you upload it here? If it is, can you try to reproduce on a new drawing (make sure you first save the file to regular `.excalidraw` so you don't lose work).

**Comment by chipbite** [comment]
I tried again and now it works nicely. Not sure why I got this error (twice) yesterday.
Sorry for taking your time. Thanks alot!
