### ISSUE TITLE
pen/writing issue.

### ISSUE THREAD

**Issue by jayliee** [excalidraw/excalidraw#4896]
Whenever I use the pen feature it almost always doesn't complete the full stroke cleanly. The line either gets cut off 2-5mm away from where I lift my stylus or makes a weird dot. 

I have a Huion Display tablet that works fine on any other drawing app and I'm using obsidian for the program I had excalidraw downloaded to as a plugin.

Please help :((

![image](https://user-images.githubusercontent.com/101372686/157781256-02dc56f6-d3d8-4d72-a587-aa9e05fdc3b1.png)
![image](https://user-images.githubusercontent.com/101372686/157781351-f2ca462c-3a5f-400e-94cb-de7ca872192b.png)

**Comment by valvas29** [comment]
#4551 duplicate here; same annoying problem.

**Comment by dwelle** [comment]
As per https://github.com/excalidraw/excalidraw/issues/4551#issuecomment-1074174494, closing this in favor of https://github.com/excalidraw/excalidraw/issues/4802
