### ISSUE TITLE
REACT_APP_BACKEND_V2_GET_URL and REACT_APP_BACKEND_V2_POST_URL

### ISSUE THREAD

**Issue by abhaymahajanwh** [excalidraw/excalidraw#4898]
@ad1992 
Can you please let me know where I can get code of APIs used in excalidraw 
REACT_APP_BACKEND_V2_GET_URL=https://json-dev.excalidraw.com/api/v2/
REACT_APP_BACKEND_V2_POST_URL=https://json-dev.excalidraw.com/api/v2/post/ 

I would like to host these on our server.

**Comment by ad1992** [comment]
@abhaymahajanwh you will need to fork [excalidraw-room](https://github.com/excalidraw/excalidraw-room), here is a more detailed answer https://github.com/excalidraw/excalidraw/discussions/3879#discussioncomment-1110524

**Comment by abhaymahajanwh** [comment]
@ad1992 Thanks.
