### ISSUE TITLE
Add background to the text block

### ISSUE THREAD

**Issue by s-charvin** [excalidraw/excalidraw#4909]
I hope to have the function that can add background to the text block, so that it is no longer a transparent bottom, which is convenient to overlay on linear tools such as arrows.

**Comment by abhaymahajanwh** [comment]
@s-charvin 
Hi,
Is this something like https://sharp-curie-5a59d5.netlify.app/ you want?

**Comment by s-charvin** [comment]
> 
I don't know if there is a problem with my network here. After opening the link you sent, I saw a blank Excalidraw page, but it has three more functions than [the official website](https://excalidraw.com/): Grab, Eraser, Stickynote. Is this the Stickynote feature you want me to see? If so, I don't think this is what I want. Specifically, you can take a look at the example shown in the following link or picture.

[Example](https://excalidraw.com/#room=91a4e9d9a1b4a5655549,24ERzloGDjQXXG_42S9UHw)

![image](https://user-images.githubusercontent.com/38879886/158006249-db8f0781-8889-4eeb-b35e-17f7ec288a5a.png)

**Comment by abhaymahajanwh** [comment]
Check text feature only. Sticky note is not proper.
I have added a background option for text.

**Comment by s-charvin** [comment]
thanks for your help!
I looked again and found it, but the background doesn't look quite symmetrical. Is this function only available through the link you sent? If so, I'll save this link for future use.

**Comment by KronosTheLate** [comment]
Duplicate of https://github.com/excalidraw/excalidraw/issues/4323. But I dont get why this is closed, as I am unable to make text with a background in the excalidraw app.
