### ISSUE TITLE
A shortcut to scroll the view to the center of the page

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw#491]
Sometimes you might overscrall, so it would be nice to have a shortcut to bring everything in front of you.

Having a shortcut means we don't need yet another button to keep it simple, but we need the #408 to start documenting possibly more hidden features.

**Comment by dwelle** [comment]
I wanted to do something similar. Also, we may want to add it at least to contextMenu so it's partially discoverable.

Related: https://github.com/excalidraw/excalidraw/issues/306

**Comment by lipis** [comment]
`"Scroll to center"` or something like that.

**Comment by lipis** [comment]
Also needed when loading from backend or local storage.

Sometimes the drawing is outside of the view.

**Comment by dwelle** [comment]
@lipis yep, that's what #306 is about. But in this case (or any case for that matter), centering may not be enough because there's no guarantee that content is in the center. Hence #306 is about scrolling to content. Not sure what strategy to implement (maybe both).

**Comment by lipis** [comment]
Since we don't support zoom, scrolling to center would be our best guess, or the median center (or whatever that could be called - where most of the objects are ;)
