### ISSUE TITLE
Docker image at docker-hub outdated

### ISSUE THREAD

**Issue by cmorty** [excalidraw/excalidraw#4925]
According to https://hub.docker.com/r/excalidraw/excalidraw/tags the latest version is 4 month old (04-11-2021). The last release is only a month old (2022-02-17).

**Comment by ad1992** [comment]
closing this via https://github.com/excalidraw/excalidraw/pull/5468, the docker build is fixed and published. 
For tagging we can have a separate issue which is already taken care by the above PR.
