### ISSUE TITLE
How to render on standalone html file

### ISSUE THREAD

**Issue by INF800** [excalidraw/excalidraw#4927]
I have `.excalidraw` file available as url [like this](https://raw.githubusercontent.com/INF800/whoami/master/assets/blogs/3js/01-simple_3d_character/3js-building-blocks.excalidraw) hosted on github.

How to display this file in standalone static html file which doesn't use any backend? 

Something like using iframe.

**Comment by ad1992** [comment]
do you mean you want to integrate Excalidraw into your app?

**Comment by INF800** [comment]
I have a blog (GitHub pages). I want to embed the drawing in my blog

**Comment by ad1992** [comment]
You can use `iframe` to render Excalidraw drawing as shown [here](https://codesandbox.io/s/znsy3?file=/index.html) using shareable links, for more functionality you can integrate Excalidraw in [browser](https://github.com/excalidraw/excalidraw/blob/master/src/packages/excalidraw/README.md#in-browser) directly

**Comment by INF800** [comment]
Neat. Thanks!!

**Comment by ad1992** [comment]
closing this as its resolved
