### ISSUE TITLE
Firebase Configuration

### ISSUE THREAD

**Issue by abhaymahajanwh** [excalidraw/excalidraw#4931]
Hi team,
I have created firebase database. 
But I miss some configuration,
Can you please provide configurations I need to done in firebase app.
Because currently files saved are not loaded for other users.

**Comment by dwelle** [comment]
hey @abhaymahajanwh — the collaboration part consists of two parts: 1) the websocket server (excalidraw-room repo), and 2) Firebase Firestore (used for persistence). For pure collaboration without persistence, you don't need the Firebase part.

But if you do want persistence, then the thing you need to set up is:

1. initialize the Firestore database
2. get the config, stringify it and add it to `.env` as `REACT_APP_FIREBASE_CONFIG` key (see  https://github.com/excalidraw/excalidraw/blob/master/.env.production#L12)
3. make sure you deploy the Firestore rules (https://github.com/excalidraw/excalidraw/blob/master/firebase-project/firestore.rules) — you can also paste the rules manually in the Firestore dashboard

**Comment by abhaymahajanwh** [comment]
Hi David,
I have added the same rule you have provided to me.
It is working for shapes but it is not working for images.
I am getting errors.
Can you please help to solve this.
https://firebasestorage.googleapis.com/v0/b/assetkloud.appspot.com/o/files%2Frooms%2F7cd3c0a3a02717be6da1%2F461d1178e420ce3f94eed46635344c2796ec348e?alt=media
[image: image.png]

**Comment by abhaymahajanwh** [comment]
Hi David,
I had added a rule you have shared.
But getting the same 403 Permission denied error.
Is there any other configuration or settings I will have to do in firebase
storage.
[image: image.png]

**Comment by dwelle** [comment]
Oops, you're right. The committed rules aren't up to date.

Here's what you need:

```
rules_version = '2';
service firebase.storage {
  match /b/{bucket}/o {
    match /{files}/rooms/{room}/{file} {
    	allow get, write: if true;
    }
    match /{files}/shareLinks/{shareLink}/{file} {
    	allow get, write: if true;
    }
  }
}
```

Edit the `if` conditions to your needs (refer to https://firebase.google.com/docs/storage/security)

**Comment by dwelle** [comment]
Missed the question. I forgot that Firebase Storage actually needs you to update/disable CORS, see this answer for details: https://stackoverflow.com/a/37765371/927631

**Comment by abhaymahajanwh** [comment]
Thanks David,
I am also able to resolve it using the same.
Also you have asked me for a link with a video feature.
Please find the link below which has a video feature.
https://thirsty-blackwell-0b50cd.netlify.app/#room=1dc2c0a3a02717be6da1,FemMywUyoExVA2IVMiE16w

Please share your thoughts on it.

**Comment by dwelle** [comment]
Cool!

**Comment by qifeikeji** [comment]
cool!!!! plus
