### ISSUE TITLE
Slovenian translation

### ISSUE THREAD

**Issue by bancek** [excalidraw/excalidraw#4953]
I would like to contribute Slovenian translation.

Could you please add it to Crowdin?

**Comment by ad1992** [comment]
Here you go https://crowdin.com/translate/excalidraw/10/en-sl?filter=basic&value=0 🚀

**Comment by bancek** [comment]
Thanks.

**Comment by ad1992** [comment]
@bancek how do you say Slovenian in Slovenian?

**Comment by bancek** [comment]
I have finished the translations.

Slovenian in Slovenian is "Slovenščina".

**Comment by bancek** [comment]
@ad1992 any progress on adding Slovenian language to the project? I keep translating new strings as they are added to Crowdin.

**Comment by ad1992** [comment]
@bancek so sorry I missed this. 
I have added it in https://github.com/excalidraw/excalidraw/pull/5186, so it should appear once the PR is merged

**Comment by bancek** [comment]
Thank you

**Comment by ad1992** [comment]
closing this via #5186
