### ISSUE TITLE
Cannot export an read-only Shareable link

### ISSUE THREAD

**Issue by yuhsinshih** [excalidraw/excalidraw#4965]
Steps to reproduce:
1. Create some drawing using the tools, and import a few icons from screenshot png image.
2. Click Export -> Export to Link
3. Shows "Couldn't create shareable link." error

**Comment by dwelle** [comment]
Works for me. Is it possible your drawing it too large?

**Comment by yuhsinshih** [comment]
The issue is I was in the company version of Excalidraw and it has certificate issue.

**Comment by dwelle** [comment]
Do you mean Excalidraw Plus? There's no "export to link" feature. You can enable link sharing, but that works slightly differently (you certainly won't be getting errors like you posted above), and isn't in the export dialog. Can you clarify what you were using?

Also, what certificate issue do you mean?

Thanks!
