### ISSUE TITLE
Excalidraw export image to clipboard is broken on MacOS Safari

### ISSUE THREAD

**Issue by orlp** [excalidraw/excalidraw#4967]
Problem occurs on Safari 15.2 (17612.3.6.1.6) on MacOS 12.1 (Apple M1).

Digging into the exception with the debugger, we see that we get a `NotAllowedError`. Reading a bit around the internet it seems that Safari has a different implementation of how it detects user events to allow writing to the clipboard? Is it possible to fix this?

**Comment by dwelle** [comment]
@orlp oops, I've had a WIP fix for this and then completely forgot about this. Will need a rewrite at this point, but last I checked it's def solvable. Safari just doesn't like setting the clipboard in the async way we're currently doing it.

I'll try to look at this over the weekend.

**Comment by dwelle** [comment]
Sorry for the delay. You can test the fix here: https://excalidraw-eb319ldm3-excalidraw.vercel.app — we'll deploy tomorrow!

**Comment by orlp** [comment]
@dwelle Thanks!
