### ISSUE TITLE
Implement schema & migrations

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#497]
As discussed in https://github.com/excalidraw/excalidraw/issues/471, we need to define schema for storing data and migrations for breaking changes so that we don't need to clear user's localStorage.

This also applies when restoring from backend (scene shared via url).

**Comment by vjeux** [comment]
We haven't had to do any breaking changes recently. Let's close this for now.

**Comment by dwelle** [comment]
We're actually doing breaking changes all the time, encountering many bugs and hastily fixing it in `restore()`, but it seems the ad-hoc migrations in `restore()` do the trick so far :).
