### ISSUE TITLE
TypeError: Cannot destructure property 'textAlign' of 'updatedElement' as it is null at updateWysiwygStyle

### ISSUE THREAD

**Issue by zsviczian** [excalidraw/excalidraw#4979]
```error
TypeError: Cannot destructure property 'textAlign' of 'updatedElement' as it is null.
    at updateWysiwygStyle (webpack-internal:///../../element/textWysiwyg.tsx:60:17)
    at eval (webpack-internal:///../../element/textWysiwyg.tsx:423:9)
    at Scene.informMutation (webpack-internal:///../../scene/Scene.ts:77:13)
    at Scene.replaceAllElements (webpack-internal:///../../scene/Scene.ts:73:14)
    at eval (webpack-internal:///../../components/App.tsx:2152:27)
    at batchedUpdates$1 (eval at <anonymous> (app://obsidian.md/app.js:1:1444405), <anonymous>:26024:12)
    at Object.eval [as updateScene] (webpack-internal:///../../utils.ts:387:75)
```

Arguably I can't reproduce this on excalidraw.com. This seems to occur when textWysiwyg editing is active and there is an `updateScene` call. Looks as if there is some sort of a race condition, as I can't reproduce the error with any specific set of steps instead I need to play with it for a few minutes. I don't quite know why the error state happens.

Regardless... here's the current code:

https://github.com/excalidraw/excalidraw/blob/127af9db23ad9297add8d8fbcf6767f927351d6a/src/element/textWysiwyg.tsx#L103-L108

`Scene.getScene(element)?` is there for a reason, and indeed in my case, it returns an undefined value.

As a simple (sticking plaster?) solution, we could do one of two things:
1
```typescript
const updatedElement = Scene.getScene(element)?.getElement(
  id,
) as ExcalidrawTextElement;
if(!updatedElement) {
  return;
}
const { textAlign, verticalAlign } = updatedElement;
```

2
```typescript
const updatedElement = Scene.getScene(element)?.getElement(
  id,
) as ExcalidrawTextElement;
if(!updatedElement) {
  return;
}
const { textAlign, verticalAlign } = updatedElement 
  ?? {
    textAlign: "left",
    verticalAlign:"middle"
  };
```

Which one would you prefer? Do you have a better recommendation?

**Comment by zsviczian** [comment]
I implemented option 1 in the Obsidian fork, and since then (not surprisingly) I can reproduce the error. Also I can't see any negative side effects of the solution.

Option 2 is not desired because there is a later reference to `updatedElement.originalText` for example, thus setting the values for textAlign and verticalAlign is not a sufficient solution.

**Comment by dwelle** [comment]
Let's go with (1) — we shouldn't have type-asserted in this place to begin with. Though I'm not sure what race condition is going on here either!
