### ISSUE TITLE
Text Alignment does not match settings

### ISSUE THREAD

**Issue by bchoii** [excalidraw/excalidraw#5000]
Steps to reproduce problem

1. Start new diagram.
2. Draw new box.
3. Double Click box to start text input.
4. Note the default settings for text alignment for a new box is TOP, LEFT
5. Start Typing.
6. Note that the text display is MIDDLE LEFT, despite the settings at (4)

https://user-images.githubusercontent.com/1185945/161155713-39ad14f2-4b2b-4e38-ae6b-53811a30a365.mp4

Expected result

1. Expect the the settings and display to be consistent.

**Comment by bchoii** [comment]
![161155713-39ad14f2-4b2b-4e38-ae6b-53811a30a365 mp4](https://user-images.githubusercontent.com/1185945/161208626-561b4ff5-2f70-4fc2-833c-ee2ec34e64db.gif)

**Comment by bchoii** [comment]
GIf to demonstrate the issue

![example](https://user-images.githubusercontent.com/1185945/161208875-9adf65ae-4bd4-4b0b-b79e-b2c66658429f.gif)

**Comment by bchoii** [comment]
@dwelle  I would like to help look into this issue, seeing as I raised it.
But I do not know where to start, could you give some insight ? (which file, module, etc...  what might be the error, what you think is an appropriate fix ?) I can raise an MR that goes in line with your suggestions .

**Comment by ad1992** [comment]
@bchoii apprecite your help :). The vertical align is set to `middle` for bound text so the alignemnt options should have gotten updated too but for your case it's not getting updated, you can start looking into the code from here 👇🏻  https://github.com/excalidraw/excalidraw/blob/master/src/components/App.tsx#L2299, this is where the alignment is set to `middle` vertically for bound text.
