### ISSUE TITLE
Bind label to arrow

### ISSUE THREAD

**Issue by zsviczian** [excalidraw/excalidraw#5010]
Original issue raised by @Dcarnik for the Obsidian-Excalidarw plugin ([#570](https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/570))

The arrow/line which connects two figures follows the figure when figure is moved to other position. That is great! We use text to identify the line (for process diagram), like numbers or other text parameters. In case the text is placed next to the line, after moving the figure, the line follows the  figure, yet text stays in same position (see fig. 1, 2)  

It would be nice that text moves together with lane (see fig. 3). 

The ideal solution. The line/arrow when double clicked allows to add text which is then connected with line/arrow. The line/arrow separates into 2 parts (see fig. 4). In case text manually moved to other position which do not intersects line, the line/arrow's 2 segments become as 1 segment. 
Good realization of that was said above at: https://www.diagrams.net/ 
Thanks.

![image](https://user-images.githubusercontent.com/57209269/161514050-c0f60359-f422-4501-8e76-924aec14e424.png)

**Comment by dwelle** [comment]
We are aiming for implementing (4) once time permits (or anyone submits a PR). I think the tracking issue is here: https://github.com/excalidraw/excalidraw/issues/5010 (needs better naming)

**Comment by russellaugust** [comment]
would love to see this as well, i was surprised to find it wasn't implemented. very helpful feature.

**Comment by urmilparikh** [comment]
+1 Very useful feature.

**Comment by lokhmakov** [comment]
+1

**Comment by dwelle** [comment]
We'll be working in this very soon!

**Comment by dampodraza** [comment]
are there any news about this feature?

**Comment by dwelle** [comment]
We're looking into starting to work on it during this week!

**Comment by ad1992** [comment]
Closing as we support labelled arrows with #5723
