### ISSUE TITLE
Video Element

### ISSUE THREAD

**Issue by abhaymahajanwh** [excalidraw/excalidraw#5019]
Hi team,
I have added Video element in my setup. 
It is working as expected. But when I clear canvas or delete it by selection or using eraser, 
I have set isDeleted : true 
and remove iframe tag using
var video_el = document.getElementById(el.id);
video_el.parentNode.removeChild(video_el);	
This is working locally. But when we are collaborating, It is not being removed from other clients.
Can you please help me.
![image](https://user-images.githubusercontent.com/78727993/161953301-9f0da6c4-f475-43ce-81c8-7bd2629f3b2b.png)
![image](https://user-images.githubusercontent.com/78727993/161953464-e74db17e-f158-40f6-8ac4-26011efbe0cd.png)

**Comment by dwelle** [comment]
Hi. From the code it seems you're managing the video elements separately, so once you delete the element, only the element update itself is propagated to the other clients. They'll need to take care of removing the video from the DOM. Is my assessment correct?

(unrelated: you're deleting all elements on the canvas, not just target element, in your `.map()`).

Btw, would love to see how it works in practice if your app is public anywhere. I assume the video elements are on top of the canvas, so you won't be able to interleave it with other elements on canvas.

**Comment by abhaymahajanwh** [comment]
Hi David,
I am adding iframe tags for every video element. But I am managing video
elements like you have managed other elements like text and image.
When I add video to one client it is rendering over canvas inside a div
with position absolute and I am considering x and y as left offset and top
offset.
I also added code to remove iframe in *actionClearCanvas *and
* deleteSelectedElements.* If you can help me to find a function which is
being called on another client when we clear canvas that will be great.

But now I am facing typescript *Object is possibly 'null' *issue suddenly
and now the project is not being compiled.

Below is a link to a demo.
https://sleepy-bassi-dcb209.netlify.app/

It is not updated.
I will update you once I am able to deploy the latest changes here.
I have added Eraser, Stickynote, Grab and multiple images upload and pdf
upload.

**Comment by qifeikeji** [comment]
can you share code.
i want test video local
