### ISSUE TITLE
Copy to clipboard with Dark Theme is Light mode

### ISSUE THREAD

**Issue by CatSharkShin** [excalidraw/excalidraw#5023]
![image](https://user-images.githubusercontent.com/53709818/162496563-d8cb3d79-9f41-4b21-9f67-751e15e6f070.png)
When copying to clipboard using the Dark Theme
It generates a light theme image
![image](https://user-images.githubusercontent.com/53709818/162496681-2c69ee9b-267b-4ee9-be31-de33c5206c5f.png)

**Comment by dwelle** [comment]
Hey @CatSharkShin — that action (and any export action) uses the export theme setting (you can set in the export dialog. It's saved.), not the UI theme setting:

![image](https://user-images.githubusercontent.com/5153846/162498322-1f684613-fd56-436c-80a3-1da5692b5eed.png)

**Comment by CatSharkShin** [comment]
Thank you @dwelle. How do I bring this dialog up? I tried exporting and saving in all kinds of ways but I still have never seen it. @dwelle

**Comment by dwelle** [comment]
Really? If you're using excalidraw.com, then:

![image](https://user-images.githubusercontent.com/5153846/162514959-3bb07676-6c8a-4665-a8fc-db9ce00b1a41.png)
