### ISSUE TITLE
feature request : Need text attached to lines

### ISSUE THREAD

**Issue by 9kartik** [excalidraw/excalidraw#5033]
Just like other closed polygons, need text attached to lines which would change angle along with the line. If possible, the text should also have an ability to hover over the line and the user can change its position. Can be extended to poly-line as well.
![image](https://user-images.githubusercontent.com/2690844/162880500-3dae45f0-4a0a-4415-930d-25fc8288e9d7.png)

**Comment by 9kartik** [comment]
marked as duplicate

**Comment by denislutz** [comment]
Hi, Is this feature implemented? I love the tool and this is the one missing part. Thanks in advance....

**Comment by ad1992** [comment]
Coming soon 🙂
