### ISSUE TITLE
Add image button not working on iPad (but still works on Android)

### ISSUE THREAD

**Issue by zsviczian** [excalidraw/excalidraw#5036]
Pressing the add image button (9) activates the Image Element Properties on the left, but the chose-image dialog does not come up on iPad OS. 

![09A528FF-FBCF-490D-8867-290D09BDCE2B](https://user-images.githubusercontent.com/14358394/163269524-09a85d7c-02e1-4970-ba56-21743a48c19b.jpeg)

**Comment by dwelle** [comment]
(please let it not be another legacy-fs race condition!)

**Comment by dwelle** [comment]
Also ensure you're on latest. There was a 1-2 day period where it was broken a while back.

**Comment by dwelle** [comment]
Ok, can repro. It was introduced in https://github.com/excalidraw/excalidraw/pull/4955

**Comment by zsviczian** [comment]
So I see where the issue is. Are you working on the fix, or should I create a PR?
