### ISSUE TITLE
SVG image not displaying in Firefox - missing width/height attribute in <svg> element

### ISSUE THREAD

**Issue by GuillaumeD-cemea** [excalidraw/excalidraw#5043]
Hi,

I'm trying to add the [following image](https://www.svgrepo.com/svg/70333/mixing) to excalidraw ; import works fine, but I cannot see the image after in Firefox. 

I can see there is something because I can select it : 
![excalidraw_firefox_only](https://user-images.githubusercontent.com/101114641/163547042-5157917f-9447-45c0-b706-1d2079f3d4c9.png)

The issue is present in Firefox 99.0, both on Linux & Windows, I tried with a blank profile. It happens on version 2022-04-14T14:20:35Z-70b3a9d (the one deployed on excalidraw.com)
On chrome 100.0, the image import & display fine.

If I start a collaborative session with Firefox & Chrome, I can import the svg & see it fine in Chrome, but not in Firefox : 
![excalidraw_collab](https://user-images.githubusercontent.com/101114641/163547231-6544abf5-79d7-4f45-a375-b5c83baca211.png)

Other SVG files (like [this one](https://upload.wikimedia.org/wikipedia/commons/f/f6/Gnome-camera-web.svg)) works fine. 

Editing the SVG by adding `width="60" height="60"` to the <svg> element resolves the issue, but it's a bit hacky (and annoying to do).

Happy to help if more debug is needed,

**Comment by dwelle** [comment]
Thanks for the report!
