### ISSUE TITLE
text element disappear on double click selection

### ISSUE THREAD

**Issue by mritunjayz** [excalidraw/excalidraw#5048]
Excalidraw - @0.11.0
Browser - Chrome
System - Mac pro

text element disappear on double click selection. not happening ever time but once it starts it keeps on happening until refresh. 

Console error - 
<img width="1342" alt="Screenshot 2022-04-14 at 15 23 41" src="https://user-images.githubusercontent.com/22472097/163678957-51caa053-eac8-4188-baea-a1ee0b73252d.png">

Video - 

https://user-images.githubusercontent.com/22472097/163679004-b4a2dc18-e640-413d-afff-b73c295247ad.mov

**Comment by mritunjayz** [comment]
I am trying that getting some other error while setting up excalidraw-next. `vendors~hackerrank_r_app.js:34880 Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.`

**Comment by ad1992** [comment]
> I am trying that getting some other error while setting up excalidraw-next. `vendors~hackerrank_r_app.js:34880 Uncaught Error: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.`

Are you using the exact same version I pinged above of excalidraw-next ? If not please use the exact same version to avoid other breaking changes.

**Comment by mritunjayz** [comment]
@ad1992 I don't have defined way to reproduce it but I have tried to reproduce it multiple times and it is not happening with the above version you have mentioned for ex-next. I will update this thread by more testing by day end.

**Comment by ad1992** [comment]
> @ad1992 I don't have defined way to reproduce it but I have tried to reproduce it multiple times and it is not happening with the above version you have mentioned for ex-next. I will update this thread by more testing by day end.

The bug was fixed in the commit version above hence asked to test in that exact version. 
You can use that version in prod too as it doesn't have any changes in the API, here is the commit log for the [diff](https://github.com/excalidraw/excalidraw/compare/0896892f8ad03f42d1bd8312fe6bd938f6a3f8aa...6d0716eb6bd23685fc92277ae86dd3ea5745270f) for your reference.

**Comment by mritunjayz** [comment]
got it. Thanks @ad1992

**Comment by ad1992** [comment]
closing this as it's resolved. Please feel free to reopen if the issue persists
