### ISSUE TITLE
Perfect resizing with shift button is broken for flipped elements

### ISSUE THREAD

**Issue by gmertk** [excalidraw/excalidraw#505]
![Jan-22-2020 00-14-04](https://user-images.githubusercontent.com/907281/72854431-3f2a4e00-3cac-11ea-92fc-deb8115fc61e.gif)

**Comment by dwelle** [comment]
Yup, I've [mentioned it in the PR](https://github.com/excalidraw/excalidraw/pull/342#issuecomment-575083515) that normalizes handles, but forgot to create an issue. Thanks.

**Comment by gmertk** [comment]
@dwelle ah sure I'm assigning to you then. If you can't find time, feel free to pass it back to me. Btw I did some small refactoring for delta values on https://github.com/excalidraw/excalidraw/pull/430 it might be better to build up on that branch.

**Comment by gmertk** [comment]
Just tested this with all the shapes, flipped, shift pressed, etc. Works great! Thanks @dwelle.
