### ISSUE TITLE
exportToSvg() does not respect window.EXCALIDRAW_ASSET_PATH

### ISSUE THREAD

**Issue by thfrei** [excalidraw/excalidraw#5063]
Dear excalidraw team.

First of all, thank you for your great efforts. I am working on integrating the excalidraw library into the trilium note app (https://github.com/zadam/trilium/pull/2798). Since trilium is mainly self-hosted, it is important to self-host all assets.

After setting `window.EXCALIDRAW_ASSET_PATH` it seemed to solve the issue when using the react version. However, since we use `exportToSvg()` to save an SVG-image, I found, that some assets are still loaded from a 3rd party. This time not unpkg.com, but excalidraw.com. 

I did not have time to do a solution, but I found the lines that indicates the problem.

- https://github.com/excalidraw/excalidraw/blob/c5a7723185f6ca05e0ceb0b0d45c4e3fbcb81b2a/src/scene/export.ts#L125
- https://github.com/excalidraw/excalidraw/blob/c5a7723185f6ca05e0ceb0b0d45c4e3fbcb81b2a/src/scene/export.ts#L129

Thank you for your time.

Best regards
Thomas

PS: Of course, we could just string-replace the url of the fonts, but it looked like a minor bug to me.

**Comment by ad1992** [comment]
Hi @thfrei 👋🏻, you are right, the fonts path is not using the asset path when exporting. We will look into this.

**Comment by thfrei** [comment]
@ad1992 Thank you very much! 💐

**Comment by ad1992** [comment]
@thfrei you will need to use [@excalidraw/excalidraw-next](https://www.npmjs.com/package/@excalidraw/excalidraw-next) if you want this change, we will be soon releasing it in the official version as well.

**Comment by bric3** [comment]
Hi @ad1992, I'm the developer of the IntelliJ plugin that integrates Excalidraw. And I am actually interested by the opposite. In order to work offline and to interface with IntelliJ, Excalidraw is self hosted in the IJ process.

However when exporting to SVG I would like to keep the standard assets path, i.e. the one that goes to excalidraw.com. I looked at the change and I'm not sure it is easily doable.
