### ISSUE TITLE
Missing images

### ISSUE THREAD

**Issue by tekumara** [excalidraw/excalidraw#5064]
I have added external svg images to my scene. But when I reopen the scene they are missing:

<img width="600" alt="Screen Shot 2022-04-19 at 9 52 16 am" src="https://user-images.githubusercontent.com/125105/163894565-69e45fff-0e36-4bd7-aced-170d375c6bec.png">

I have to drop them back onto the scene.

Is there anyway to avoid this?

**Comment by dwelle** [comment]
This is on excalidraw.com right? There are some subtle race conditions and it can happen from time to time — I haven't yet figured out when.

Nevertheless, the solution should be for us not to clear "unused" images on each load, but only unused images older than a day or something.

**Comment by tekumara** [comment]
Yep on excalidraw.com. Same experience here - sometimes it works, sometimes not, and I haven't worked out the exact conditions either.

**Comment by DallasCarraher** [comment]
For me, images stopped persisting and I started getting CORS errors from the api.

**Comment by ad1992** [comment]
> For me, images stopped persisting and I started getting CORS errors from the api.

Is this on [excalidraw.com](https://excalidraw.com) ?

**Comment by DallasCarraher** [comment]
no, I haven't tested that. I've been using plus. There's no special network setup either; it just looks like the service layer isn't open to taking requests from the domain. Here's a screenshot:

![image](https://user-images.githubusercontent.com/4131693/188015749-40c4c4aa-9253-430c-b5e7-cf871d71842b.png)

**Comment by dwelle** [comment]
@DallasCarraher I forgot to get back, but this should have been fixed for some time now. If you are still experiencing any issues, please contact us on `support@excalidraw.com`, thanks!

**Comment by FateRiddle** [comment]
fuck, I saved some meme's there... didn't know it's not a safe place.

**Comment by godisme1220** [comment]
still happened why? Is there any limit photo amount?

**Comment by dwelle** [comment]
@godisme1220 no inherent limit. But browsers often clean up IndexedDB if there's not a lot of disk space (happens to me a lot these days because my disk is nearly full). Could this be your case as well?

Other possibility there's a bug in our "clean up unused images" though I was reviewing it just yesterday and it seems solid.

**Comment by YeHang-GitHub** [comment]
same thing happened to me and it's not svg, it's a normal image...

**Comment by dsmabulage** [comment]
Same thing here

**Comment by FreyzerFault** [comment]
I found 1 of my boards lost ALL of the images. No image shown, all lost...
Bye bye to my Hollow Knight analysis :'(

But ALL the other boards have all their images saved. Even older boards.

![Image](https://github.com/user-attachments/assets/40f6da30-1f4d-4646-964d-5a2434f8352e)

**Comment by Wavez** [comment]
still happens, just lost every svg in my diagram

**Comment by a1q0** [comment]
can confirm it still happens

**Comment by javierpitaglezcampos** [comment]
just happened to me. Any possible solutions ?

**Comment by scele** [comment]
This keeps happening to me too. FWIW in my case, I noticed it happens whenever I'm loading a scene while on company VPN. Then all images fail to load with:

```
GET https://firebasestorage.googleapis.com/v0/b/quickstart-1595168317408.appspot.com/o/files%xxxx?alt=media net::ERR_CONNECTION_RESET
index-9XBrXsYZ.js:4437 Failed to fetch file xxxx after 4 attempts: Failed to fetch
```

Once I disconnect VPN and reload the page, those requests succeed and the images are back.

**Comment by spuder** [comment]
This just hapend to me today. 
I found a work around if you have a previous backup. 

1. Export the (broken) drawing to `foo.excalidraw` file
2. Load a previous .excalidraw file from backup.
(Observe that the images are loaded correctly)
3. Re-Import the newly exported `foo.excalidraw` file
Observe that the images are restored. 

Granted you shouldn't have to export the file over and over like its 1995, and the chances that people have local exports of the file are slim. But if you do, then this will restore the images to the file.

**Comment by FreyzerFault** [comment]
Thanks @spuder, but didn't work in my case, maybe it's because I don't have 1 local workplace, I paid for the paid version so I have all in the cloud, and your solutions seems to work in a local account.

**Comment by niemes** [comment]
This is still happening, We are paying for excalidraw plus. Work on presentations. Every other days images inside the presentations stop loading and are just gone. This is a serious issue!
