### ISSUE TITLE
Ste initial settings for shareable linked diagram

### ISSUE THREAD

**Issue by AndrewPixel** [excalidraw/excalidraw#5068]
I'm embedding a shareable link I've exported into a web page. When the web page is displayed the diagram appears as expected but I like to change some of the initial settings. Namely, I need it to:

- hide all the bars (sort of like pressing Alt+R but also, if possible, hiding the export bar and the language bar)
- zoom to fit all the elements. The link is used as a src for an iframe which has a "fixed" size.

Is this possible with an link to a diagram?

**Comment by dwelle** [comment]
hey @AndrewPixel — not possible right now using the `<iframe>` solution. You'd need to integrate the npm package https://www.npmjs.com/package/@excalidraw/excalidraw.

We may consider expanding the API for iframes, but right now we're focusing on the package component.

**Comment by AndrewPixel** [comment]
Thanks for the reply. We don't use npm. It's a bummer I can't just add params to the url (eg, &view=zen&zoom=fit) but, so be it.
