### ISSUE TITLE
creating an empty Text and switching to another element freezes the left menu

### ISSUE THREAD

**Issue by lissitz** [excalidraw/excalidraw#507]
![output](https://user-images.githubusercontent.com/53315888/72858039-c3d29780-3cbf-11ea-9908-5f140a264913.gif)

- Create an empty Text
- Switch to another mode.
- Now the shape properties menu doesn't update, although actions still fire.

creating a new text element and entering some text solves the issue.

**Comment by lorisdev** [comment]
I have I few hours available right now I'll try and fix it !

**Comment by lipis** [comment]
Go for it

**Comment by lorisdev** [comment]
Done !
