### ISSUE TITLE
public path fallback doesn't work

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#5080]
since https://github.com/excalidraw/excalidraw/pull/5078

culprit release: https://codesandbox.io/s/sweet-hamilton-k4vkjb?file=/src/App.tsx (Virgil font doesn't load)
commit before: https://codesandbox.io/s/romantic-franklin-4jorjz?file=/src/App.tsx (Virgil font loads)

**Comment by ad1992** [comment]
It's mostly related to a change in import order of `Excalidraw` due to the above commit, I will look into it.

**Comment by pomdtr** [comment]
Thanks @ad1992 !
