### ISSUE TITLE
CodeSandbox broken

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#512]
It seems that https://github.com/excalidraw/excalidraw/pull/510 broke CodeSandbox (it works on the [preceding commit](https://codesandbox.io/s/github/dwelle/excalibur/tree/csb_test_dc0a4f4)).

https://codesandbox.io/s/github/excalidraw/excalidraw

![image](https://user-images.githubusercontent.com/5153846/72905561-05e7f180-3d31-11ea-8da3-a67cc85e6fd5.png)

Haven't investigated further, so not sure what exactly is the problem.

/cc @tomayac

**Comment by tomayac** [comment]
I'm very sorry 😔. I just cloned and [deployed on Glitch](https://glitch.com/~excalidraw-excalidraw-1), and there it [works fine](http://excalidraw-excalidraw-1.glitch.me/) (apart from an unrelated `ws://` mixed content error when [loaded over https](https://excalidraw-excalidraw-1.glitch.me/)).

I'm not sure what CodeSandBox does differently. Does anyone know how to debug?

**Comment by tomayac** [comment]
OK, I traced this down. In [`browser-nativefs`](https://github.com/tomayac/browser-nativefs), I use a [dynamic import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#Dynamic_Imports) to load either the legacy file handling approach, or the Native File System API ([deep link](https://github.com/tomayac/browser-nativefs/blob/c1058a5873c8068842537f7acbf717e0d9d97f07/src/file-open.mjs#L24)).

If you look at the [deployed version](https://excalidraw.com/), this is the source tree (note the *presence* of `file-save-nativefs.mjs` and `file-open-nativefs.mjs`):
 
![Screen Shot 2020-01-22 at 16 33 28](https://user-images.githubusercontent.com/145676/72907913-06828700-3d35-11ea-88f9-8ae1c5ed3c4a.png)

If you compare to [CodeSandbox's version](https://dnn4h.csb.app/), the dynamically imported files are *missing*: 

![Screen Shot 2020-01-22 at 16 33 42](https://user-images.githubusercontent.com/145676/72907938-0c786800-3d35-11ea-8f61-1377485384bf.png)

I will open an Issue with CodeSandbox.

**Comment by dwelle** [comment]
Mhm... I'm not sure if the dynamic import itself is the problem, because I've manually tried it out and it works, by itself (check https://codesandbox.io/s/floral-lake-ou5wi `index.tsx:201`).

It may be a problem with CodeSandbox & dynamically importing/resolving mjs files, or it may be connected with CodeSandbox & Create-react-app integration issues (which there were many).

:thinking:

**Comment by tomayac** [comment]
Another theory is that it's https://github.com/codesandbox/codesandbox-client/issues/1774.

**Comment by dwelle** [comment]
That's feels more like it :+1:.

**Comment by tomayac** [comment]
This successfully loads in CodeSandbox after https://github.com/excalidraw/excalidraw/pull/523 was merged, but now the opening/closing is broken and throws a console error. It works on Excalidraw.com. ¯\_(ツ)_/¯

**Comment by dwelle** [comment]
As I understand, it only throws on CSB? IMO that's an acceptable compromise (/cc @vjeux), as CSB will be used only for quick & dirt development.

I'll close this for now. Let's see if anyone comes to complain :).

Thanks for working on this!

**Comment by vjeux** [comment]
cc @compulves

**Comment by vjeux** [comment]
cc @codesandbox
