### ISSUE TITLE
Unwanted extra linked text

### ISSUE THREAD

**Issue by inwardmovement** [excalidraw/excalidraw#5131]
There are unwanted text somewhat linked to shape. When I double click on it, it gets back in the shape.
https://app.excalidraw.com/l/8bhzGFB1dlN/1ZZInDpNEXN
![exc-dup-bug](https://user-images.githubusercontent.com/9438102/166134425-156904bc-4697-423d-8305-f88d3133da81.gif)

**Comment by dwelle** [comment]
Hey! Is this something you managed to end up in recently, or is this coming from an older drawing?

If a new drawing, can you reproduce?

**Comment by inwardmovement** [comment]
The drawing was created some months ago, but edited recently (the bug appeared today). Sorry I do not remember what exact steps I did that produced that. Probably something involving duplicating... 

Anyway I deleted the shape and created a new one, so it's not really a problem.

**Comment by dwelle** [comment]
I see. There was a bug previously, but should be fixed now. We might want to repair existing drawings, but likely not many are affected.

**Comment by ad1992** [comment]
closing this as it's resolved, please feel free to reopen if you encounter this again.
