### ISSUE TITLE
Unable to place images in collaboration mode

### ISSUE THREAD

**Issue by SymFlorian** [excalidraw/excalidraw#5137]
When an image is selected in the official excalidraw whiteboard with the live collaboration mode enabled, then the preview of the image is shown but as soon as the user clicks the mouse button to place the image, it disappears completely or it is shown an empty image square like this:
![grafik](https://user-images.githubusercontent.com/58416661/166413020-f06d9ccb-289d-43df-9e5a-08dd6c03c868.png)
The issue can be reproduced with different browsers (Firefox, Chrome) and OS (Linux, Mac, Windows). The issue seems not to appear when the live collaboration mode is not enabled. It does not matter if someone has joined the live collaboration. Just enabling it is enough to see the issue.
In the console tab of the browser no new issue or log entry appears when placing an image which fails:
![grafik](https://user-images.githubusercontent.com/58416661/166413576-986e1f88-fa21-49c2-8a5a-3d78c497242c.png)

**Comment by ad1992** [comment]
@SymFlorian do you mind sharing a recording so its more clear and easy for us to reproduce?

**Comment by SymFlorian** [comment]
@ad1992 I mean the live collaboration feature to see the drawing of other users:
![grafik](https://user-images.githubusercontent.com/58416661/166416562-6b372bf3-f7bd-4a61-a888-58648fd8e3af.png)
As soon as you start the session, the placing of images 
![grafik](https://user-images.githubusercontent.com/58416661/166416740-a211ae59-2569-42d0-abfa-86ae3416f0f4.png)
 is not working (most times)

**Comment by ad1992** [comment]
Yep, I got that, but what I meant is if you could record a video with the same exact steps, that would be great (of course unless it's confidential) as it works for me when I try to add images in collaboration mode as well.

**Comment by SymFlorian** [comment]
Sorry, totally misunderstood you ;)
Here a video where you can see the issue:
https://user-images.githubusercontent.com/58416661/166419231-2927ab2b-f2ba-4804-b36f-83df9540ab75.mov

**Comment by dwelle** [comment]
Can you post the image here if not private? I can't reproduce with any image of mine (huge or small) on Windows or MacOS.

Also, can you check the excalidraw version? (right-click on canvas → stats for nerds → click on version to copy)

**Comment by SymFlorian** [comment]
It seems as if the issue is not 100% consistent, sometimes its better, sometimes worse. On some systems I can see that the image can be placed in the first attempt, but when placing the same image a second time (regardless of deleting it before), then it does not work.
It does not seem to have any correlation to the image used, but nevertheless I can put here two images where the issue appears.

So the repro steps could be:
1. Start a collaboration session
2. Place an image through the image button (9)
3. Place the same image again through the image button (9) --> Cannot be placed

[ExampleImages.zip](https://github.com/excalidraw/excalidraw/files/8609661/ExampleImages.zip)

**Comment by dwelle** [comment]
Thanks for the info.

Does drag & drop (instead of using the file picker) work fine?

The strangest thing is you can repro only when collaborating. Are you sure you can't repro in solo?

**Comment by SymFlorian** [comment]
With drag & drop it works fine, no issues at all. In the solo session it also works fine. Its only the file picker in the collaboration session wich causes the issue.
![dragging](https://user-images.githubusercontent.com/58416661/166462820-ab96e207-60ed-436c-8ce4-3656e2bc4416.gif)
![open](https://user-images.githubusercontent.com/58416661/166462830-f74267f1-da6d-4e7b-ad04-2ddf140a8ab5.gif)

**Comment by Periclod** [comment]
After looking through the code I think I found the issue!

It seems to be a that `pendingImageElement` that is used when inserting images and the corresponding element in the scene are two different instances of the same element. It appears this is caused by [src/excalidraw-app/collab/Portal.tsx#L120](https://github.com/excalidraw/excalidraw/blob/1ed1529f96eebbd744023463abebf5ee18292532/src/excalidraw-app/collab/Portal.tsx#L120) (It's even explained in the comment above!)

When I replace the line with `mutateElement(element, { status: "saved" })` I can't reproduce the issue anymore.

**Comment by dwelle** [comment]
Fix here https://github.com/excalidraw/excalidraw/pull/5322 (preview: https://excalidraw-git-fixpendingimageelementstalereference-excalidraw.vercel.app/). Lemme know if the fix works for you.
