### ISSUE TITLE
Chart not displaying correctly

### ISSUE THREAD

**Issue by noudadrichem** [excalidraw/excalidraw#5149]
Hi, I'm trying to create a chart using:
```
ms,frame
1097,1
424.,2
416,3
377,4
368,5
1075,1
```

This shows a chart like so: 
![image](https://user-images.githubusercontent.com/16288476/167095203-a246f5ca-7131-45ad-ab54-e25ce3a7d8a7.png)

But what I want is to have the X and Y the other way around. So I tried using:
```
frame,ms
1,1097
2,424.
3,416
4,377
5,368
1,1075
```
Where I expect the frame to be on the X as and the ms displayed on the Y. Both these snippets generate the same graph. 

![image](https://user-images.githubusercontent.com/16288476/167095535-4cc57660-dc51-44c6-8f84-1f194e2486bf.png)

**Comment by dwelle** [comment]
Currently we use the first column which has all numeric as the values data, and the other as labels. And in this case we incorrectly parse the `424.` as a non-a-number (due to the trailing `.`).

We should fix this, and we should prefer the second column as values when both columns are numeric.
