### ISSUE TITLE
Shareable link button does not work on Firefox

### ISSUE THREAD

**Issue by fernandoalava** [excalidraw/excalidraw#515]
When the shareable button is pressed nothing happens, the javascript console show an undefined error message. If this option supported on Firefox? If it so I would like to work on fixing this.

**Comment by dwelle** [comment]
Don't see any reason why it shouldn't. Good catch. Go for it.

The FF error with no stack trace :sob:.

**Comment by lipis** [comment]
> The FF error with no stack trace 😭.

Thanks Firefox!!

**Comment by fernandoalava** [comment]
Close this due https://github.com/excalidraw/excalidraw/issues/537
