### ISSUE TITLE
remove element sync error

### ISSUE THREAD

**Issue by nxboo** [excalidraw/excalidraw#5153]
https://user-images.githubusercontent.com/4253172/167235031-a7a0d46a-9092-4072-8534-5b1a661ebedb.mp4

see this video

**Comment by yin-zhang** [comment]
I run into the same problem as the above video.  It seems that when the Eraser is used to delete objects, it's very easy to get inconsistent state like this.  However, if I first use the arrow to select an object, then click the trash can icon to delete the object, then there is no inconsistency at all.  Could there be some bug in the implementation of the eraser?

**Comment by yin-zhang** [comment]
Wow, the response is so fast! You guys are amazing!
