### ISSUE TITLE
My toolbar got moved to the bottom, used to be on the side?

### ISSUE THREAD

**Issue by dennisrcao** [excalidraw/excalidraw#5157]
Hi there, paying supporter of Excalidraw, love what y'all do! 
Was wondering why my toolbar moved to the bottom all of a sudden?
I preferred when it was on the left hand side now I don't know how to change it back.

**Comment by dwelle** [comment]
Hey! Can you show a screenshot? What browser & operating system do you use?

**Comment by dennisrcao** [comment]
<img width="1675" alt="Screen Shot 2022-05-08 at 10 43 14 AM" src="https://user-images.githubusercontent.com/521934/167308626-43d4a581-247a-4b1d-8f84-286da23f0b57.png">
Mac OSX, Desktop on Chrome

**Comment by dennisrcao** [comment]
I'm referring to the bottom toolbar, usually when I select the pencil or text tool, the palette shows up on the left hand side instead of on the bottom. See new screenshot below. 
<img width="1674" alt="Screen Shot 2022-05-08 at 10 44 33 AM" src="https://user-images.githubusercontent.com/521934/167308697-75e8d8a8-7036-4c44-80df-ea9b52f7eb1b.png">

**Comment by dwelle** [comment]
This is the "mobile" view. If this started happening only recently, it's likely the cause is you're zoomed in. Can you check in the url bar if that's the case?

![image](https://user-images.githubusercontent.com/5153846/167309081-e94d1f98-2c50-4ac9-a8dc-3e336e430892.png)

**Comment by dennisrcao** [comment]
You're absolutely correct, this worked. Thank you!
