### ISSUE TITLE
showing Link Prefix icon only  function fail

### ISSUE THREAD

**Issue by TrillStones** [excalidraw/excalidraw#5161]
<img width="927" alt="image" src="https://user-images.githubusercontent.com/32927876/167287167-289fa51e-92a3-4d1f-8e53-a9df680a2dc2.png">

<img width="860" alt="image" src="https://user-images.githubusercontent.com/32927876/167287160-87fa520f-2e5f-4268-b06c-ac19d43056b1.png">

<img width="1146" alt="image" src="https://user-images.githubusercontent.com/32927876/167287208-e1c8ee43-3a62-4889-a9e8-7d93ee1205c3.png">

**Comment by dwelle** [comment]
This relates to obsidian plugin, so you should open an issue there: https://github.com/zsviczian/obsidian-excalidraw-plugin/issues
