### ISSUE TITLE
Support setting element dimensions by hand

### ISSUE THREAD

**Issue by pspeter3** [excalidraw/excalidraw#517]
Allow explicit entry of coordinates / dimensions in text fields from the left pane. The drag handles are great but it would be nice to be able to set them explicitly as well.

**Comment by dwelle** [comment]
I thought about this as possible far-future feature, too, but I don't think we wanna add this now, though.

One of our goals is to keep this app clean, lean, and simple. So we'll see.

Another consideration is the fact that the sloppiness/sketchiness of this app will make precision positioning not that much useful, anyway. But, still may be useful for element dimensions.

**Comment by pspeter3** [comment]
I think it would be useful if you could maybe have a snap mode then? E.g. something that allows you to keep sizes and arrows snapped to a grid?

**Comment by dwelle** [comment]
I've created an issue to track this:

[Snap to grid](https://github.com/excalidraw/excalidraw/issues/521)

There's also:

- [Snap to objects](https://github.com/excalidraw/excalidraw/issues/263)
- [Attached arrows](https://github.com/excalidraw/excalidraw/issues/157)

**Comment by pspeter3** [comment]
Thanks! I'll close this out in favor of #521 and #527

**Comment by dwelle** [comment]
#527 is actually unrelated, and we might still end up implementing this. Let's keep this open.

**Comment by lipis** [comment]
If we want to keep it simple though, we might want to avoid adding more panels with settings.

**Comment by dwelle** [comment]
Yea, we'll see. Doesn't hurt to track this until more people chime in.

I think it the UI can be made to look subtle, and it turns out it's pretty useful.

**Comment by xixixao** [comment]
I think we can close this now that grid mode is in place.

**Comment by tomjamesallen** [comment]
+1 for this - I'd love to be able to click on an object and set it's dimensions based on grid based unit. I've been using excalidraw for DIY project planning.

**Comment by amitnandi** [comment]
+1 for this as well.  Excalidraw is simple/powerful enough to use as a makeshift drawing tool and addition of a simple way to create precise sizing would make it useful for a whole bunch more use cases.

**Comment by bcouetil** [comment]
Actually that is the missing feature that prevents me from using it in slide decks...

This, and the ability to crop images.

**Comment by Thiago-Morais** [comment]
Why is the issue closed if we still can't specify the dimensions?

**Comment by dwelle** [comment]
You can track this here: https://github.com/excalidraw/excalidraw/issues/5932
