### ISSUE TITLE
Live-collaboration retention period

### ISSUE THREAD

**Issue by AvidSeeker** [excalidraw/excalidraw#5175]
Start an excalidraw board, and it will last as long browser cache lasts. (is that correct?)

Start an excalidraw board, start a live-collab session, how long will that session last?

**Comment by DanielJGeiger** [comment]
> Start an excalidraw board, start a live-collab session, how long will that session last?

@AvidSeeker I have used live-collab sessions for entire semesters in teaching with #2993.  So I believe they could last indefinitely.

**Comment by dwelle** [comment]
Yes, collaboration drawings are currently permanent. It's possible that in the future we may start removing drawings that weren't accessed in X months, but it's not planned at the moment, and we'd let everyone know beforehand.
