### ISSUE TITLE
Don't render twice when unnecessary

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#518]
As discussed in https://github.com/excalidraw/excalidraw/pull/309#issuecomment-577375854, we should figure out if `this.setState` unconditionally forces re-render (I believe it does in classical React, but we need to make sure).

If so, then we should remove all `this.forceUpdate` calls that are made right after `this.setState()`, for two reasons:

1. To not re-render twice, unnecessarily.
2. To make intent clear. Otherwise, anyone reading/touching the code won't know what's really going on (if it's not done for side effects etc.), and will need to spend extra time trying to figure it out.

**Comment by vjeux** [comment]
Replacing forceUpdate() with setState({}) may also be enough to remove double rendering

**Comment by vjeux** [comment]
Done
