### ISSUE TITLE
Cannot login to Excalidraw+ on another computer

### ISSUE THREAD

**Issue by Arkoxs** [excalidraw/excalidraw#5189]
I've started a plus account and tried to access my sketches on another computer but I'm only getting an error message.

Oops :(
Workspace doesn't exist or you don't have permission to access it.

Go back to your [dashboard.]

The dashboard is also not accessible.

**Comment by maielo** [comment]
Hey,

could you send us email to support@excalidraw.com. Also please

**Comment by maielo** [comment]
Problem with multiple accounts
