### ISSUE TITLE
Can not see the image uploaded by other in collaboration 

### ISSUE THREAD

**Issue by P9840356** [excalidraw/excalidraw#5194]
when I start the Live-collaboration session , I can see the image which I upload, but others can not see it.
<img width="1274" alt="user1" src="https://user-images.githubusercontent.com/69030794/168423469-835f9fee-3609-4182-a156-83845093a383.png">
![user2](https://user-images.githubusercontent.com/69030794/168423472-acb6031e-4808-4602-be58-5f17c2312e2a.png)

**Comment by dwelle** [comment]
Hello. Looking at the screenshots, there's not much to go by (except that the images don't render as errored, which still could mean as any number of things). To debug further, we'd need more info — best if we could hop in a collab room together. I can see you've messaged on Discord. Once we are both online, we can discuss the details!

**Comment by dwelle** [comment]
Closing as stale. If you're still experience any issues, please comment here and we'll reopen.
