### ISSUE TITLE
Snap to grid

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#521]
Ability to snap to objects to grid (when grid is enabled/shown - I'd probably not make it the default).

![excalidraw_snap_to_grid](https://user-images.githubusercontent.com/5153846/72974081-bd7f1100-3dce-11ea-9059-49d2c1d15195.gif)

This is likely a (far) future feature, but let's track it. Suggested in https://github.com/excalidraw/excalidraw/issues/517.

Related:

- [Snap to objects](https://github.com/excalidraw/excalidraw/issues/263)
- [Attached arrows](https://github.com/excalidraw/excalidraw/issues/157)

**Comment by vjeux** [comment]
I would not want snap to grid, but instead have a snap to other objects.

**Comment by dwelle** [comment]
That's being tracked in #263. WTBS, I'd still not dismiss this altogether. It should certainly not be the default, only when you enable it (e.g. via contextMenu). It can be quite useful for prototyping wireframes: https://mobile.twitter.com/duanebester/status/1220561761964675072/photo/1

**Comment by pspeter3** [comment]
Yeah, I think that having this option would be great!

**Comment by bartek** [comment]
:+1: to some kind of snapping (either grid or other objects)

**Comment by jdestgermain** [comment]
Came across this because I was looking for a feature like this--is there actually already a grid or would that also be part of this feature request (the ability to turn on a grid)?

I think having a reference grid available would help with lining things up even without a snap-to-feature so I am wondering if I missed that.

**Comment by dwelle** [comment]
Yes, displaying grid would be part of this issue I'd say.

**Comment by dwelle** [comment]
So, here's my thinking:

- toggling grid (via `Cmd/Ctrl+'`) should automatically enable/disable snap-to-grid (unlike Figma)
- for a start, grid steps shouldn't be configurable, and be a mutliples of 10 pixels or something (also should take into account `devicePixelRatio`)
- when grid enabled, maybe show dimensions under shape when selected, ala Figma

    ![image](https://user-images.githubusercontent.com/5153846/79633905-b8302900-8167-11ea-8760-eddb79821056.png)

**Comment by AndreKR** [comment]
FYI, this uses `event.ctrlKey && event.keyCode==222`, which is <kbd>Ctrl</kbd>+<kbd>Ä</kbd> on a German keyboard.
