### ISSUE TITLE
this.state.draggingElement is null on excalidraw-lib 0.10 & 0.11

### ISSUE THREAD

**Issue by eMerzh** [excalidraw/excalidraw#5210]
This one is a bit nasty, as it's hard to give an exact reprodcuting path.
Yet, 
we "consistenly" make excalidraw crash at some point with the code sandbox below 👇 
https://codesandbox.io/s/excalidraw-forked-6i6i1d?file=/src/index.js

it give an error like this:
<img width="710" alt="Screenshot 2022-05-20 at 07 49 19" src="https://user-images.githubusercontent.com/177003/169459424-17edb633-7671-4fed-8fd6-0d5225e7404e.png">
s

Arround this line  (compiled)
```
(0,_utils__WEBPACK_IMPORTED_MODULE_34__.resetCursor)(this.canvas);
         this.setState((prevState) => ({
        draggingElement: null,
        elementType: "selection",
        selectedElementIds: Object.assign(Object.assign({}, prevState.selectedElementIds), { [this.state.draggingElement.id]: true }), // <--here
                        }));
```

To reproduce:
there seems to be a "speed component" but tracing lines / arrows " fast-ish ..just like that ... 
drawing looks like this  before crash
<img width="504" alt="Screenshot 2022-05-20 at 07 56 05" src="https://user-images.githubusercontent.com/177003/169460349-89091155-b762-4a70-8ba6-2dce001ccb5d.png">

**Comment by ad1992** [comment]
@eMerzh can you try with the latest version `0.11.0` ?

**Comment by eMerzh** [comment]
@ad1992 oh i changed a bit after this so check if 0.9.0 was also affected and yes it is...
changed back to  0.11 , issue still there ofc ... sorry for the manipulation

**Comment by ad1992** [comment]
In the example it's still `0.9.0`. Also please make sure you update the excalidraw-assets folder as well  since you have set the `window.EXCALIDRAW_ASSET_PATH`, if thats not set, it will fallback to `unpkg`

**Comment by eMerzh** [comment]
hum 🤔  updated ... i think ...
i've remove the EXCALIDRAW_ASSET_PATH and the related assets.

following our testing... might it be related to react 18 🤔

**Comment by ad1992** [comment]
It works fine for me, are you still seeing any issue ?

**Comment by eMerzh** [comment]
@ad1992  yes 

just tried again ...


https://user-images.githubusercontent.com/177003/169498394-7462ab6b-2428-476f-bf06-0d8651ed1017.mov

here is how i repro it

unfortunatelly

**Comment by dwelle** [comment]
Strangely, it's happening on latest as well: https://codesandbox.io/s/excalidraw-forked-6l7wx4?file=/src/App.js, but can't repro in production. I'll make a fix regardless.

**Comment by dwelle** [comment]
Ok, it should be fixed in https://github.com/excalidraw/excalidraw/pull/5216 (https://codesandbox.io/s/excalidraw-forked-eylo0r?file=/src/App.js:36-47).

It won't land in a stable release after we merge the PR, so you'll have to use https://www.npmjs.com/package/@excalidraw/excalidraw-next for the time being

**Comment by eMerzh** [comment]
Cool, thanks for the fix 🎉  ... 
i'll see if i can wait for the next release :)
