### ISSUE TITLE
The nav bar and action bar became tiny

### ISSUE THREAD

**Issue by DanielShterenberg** [excalidraw/excalidraw#5211]
I'm not sure why or how but the nav bar and action bar became so tiny! I can't see anything.
I tried clearing cache and hard-reloading the site but it did not help.

Any suggestions?
![image](https://user-images.githubusercontent.com/5736597/169487293-37aa99a9-aa43-45c4-920f-cca99fc8f0e0.png)

**Comment by ad1992** [comment]
You might have zoomed out :)
can you set the browser zoom level to 100%  ?

<img width="1159" alt="Screenshot 2022-05-20 at 2 45 21 PM" src="https://user-images.githubusercontent.com/11256141/169496685-12597cc6-fcb8-48ee-a879-a3dcf0ecff17.png">

**Comment by DanielShterenberg** [comment]
Wow, I tried using command+0 so many times, and it didn't work.
LOL. Thanks.
Feeling embarrassed :)

**Comment by ad1992** [comment]
> Wow, I tried using command+0 so many times, and it didn't work. LOL. Thanks. Feeling embarrassed :)

haha no worries, this is very common :)
