### ISSUE TITLE
Missing Images

### ISSUE THREAD

**Issue by allanohorn** [excalidraw/excalidraw#5239]
In one of my scenes I added a bunch of screenshots then used excalidraw to comment on top of them. Everything was fine for a week but today all the images won't load and I'm not sure what changed. My others scenes all seem to be working just fine.

![image](https://user-images.githubusercontent.com/17394783/170037030-07e7ec8a-e7c4-4657-9232-824d5c09aa2d.png)

**Comment by zsviczian** [comment]
can you open in markdown view mode and take a look at the filenames? It seems Excalidraw cannot find the files. Do those links in markdown view look ok? if you click them do the images open?

![image](https://user-images.githubusercontent.com/14358394/170038511-9d817a7d-cc92-41ec-b2a5-26eba5019567.png)

![image](https://user-images.githubusercontent.com/14358394/170038380-db3f2468-2dd7-40da-b5fd-ba12c49eb076.png)

**Comment by ad1992** [comment]
By other scenes do you mean using using multiple tabs ?

**Comment by allanohorn** [comment]
<img width="1106" alt="image" src="https://user-images.githubusercontent.com/17394783/170294508-ee3b6698-0f9c-4473-a248-3454801d9e94.png">
On the left hand side you can see different "scenes" (seems to be the excalidraw terminology) and those others have their images rendering just fine

**Comment by dwelle** [comment]
Forgot to get back, but this should have been fixed for some time now. If you're still experiencing any issues, please contact us on `support@excalidraw.com`!
