### ISSUE TITLE
fix: Unable to delete scene from IPad Pro

### ISSUE THREAD

**Issue by danielefiungo** [excalidraw/excalidraw#5244]
Trying to delete a scene, the only observable effect tapping on "delete" button  (from safari or chrome)  is that the modal disappear without deleting the scene.

**Comment by dwelle** [comment]
Oh, you're right. Looking into it!

Btw, for an (often) speedier help, check out the Discord/email support channels you can find in the the user avatar dropdown:

![image](https://user-images.githubusercontent.com/5153846/170351280-d23d2fd4-bd18-4437-ba21-1035e9b9ac21.png)
