### ISSUE TITLE
space stripped when exporting as svg, result in different result (shift to left) from .draw and .svg

### ISSUE THREAD

**Issue by Bfault** [excalidraw/excalidraw#5246]
writing a text in excalidraw like "      test" and exporting it to svg will shift "test" to left (not tested with png)

**Comment by ad1992** [comment]
@Bfault it does work fine for me, sharing an svg 👇🏻 
![space-hello](https://user-images.githubusercontent.com/11256141/170673758-6d5b9065-a6b6-49b5-9cf9-9a2757d79b64.svg)
could you share the drawing for which it didn't work ?

**Comment by Bfault** [comment]
![graph0](https://user-images.githubusercontent.com/58236096/170703330-04e43c09-0d30-477c-8e06-a6e76d027ff8.svg)

it happen on sample_data_token at down left side, then I fix it by remove the leading space. I tried to reproduce but it don't happen anymore.

Looking on the preview that the drawing is ok, must be a problem with my svg viewer

![Screenshot from 2022-05-27 15-06-26](https://user-images.githubusercontent.com/58236096/170705688-35e46e32-3576-481c-a97e-f2871cdcdb3d.png)

 sorry for the inconvenience

**Comment by ad1992** [comment]
no worries 😊
