### ISSUE TITLE
After deleting a first workspace in Excalidraw+, autoredirect stops working

### ISSUE THREAD

**Issue by klimashkin** [excalidraw/excalidraw#5267]
I had created the first workspace upon registration with the wrong name.
So I created another workspace after that and removed the first one.

Since then [app.excalidrow.](https://app.excalidraw.com/) always redirects me to a broken page, which is very annoying

<img width="894" alt="image" src="https://user-images.githubusercontent.com/576077/171771729-bcea9bfe-cbb4-4002-bac9-9ac8eb7c9392.png">

**Comment by ad1992** [comment]
@maielo can you look into this ?

**Comment by maielo** [comment]
Hey, we have shipped a fix. Can you please test it out and let us know if it works for you?

**Comment by klimashkin** [comment]
Thank you, works now!
