### ISSUE TITLE
When logged in on two devices I can't see updates, have to log out and collaborate

### ISSUE THREAD

**Issue by grnat** [excalidraw/excalidraw#5280]
I'd like to be able to have an excalidraw session on a browser and my ipad where the drawings and updates show up on both. So it's like I'm collaborating with myself.

However the current behaviour is that I basically need to manually refresh to see any updates I've made on another device.

I can work around this by signing out on my ipad or using a browser that isn't logged in. I would rather not have to do this though and have it such that I can be logged in on both and see live updates from the other device.

**Comment by ad1992** [comment]
I suppose you are referring to Excalidraw plus ?

**Comment by grnat** [comment]
> I suppose you are referring to Excalidraw plus ?

Correct. Is this something that could be changed so I can draw on my iPad and see the changes on my desktop screen?

**Comment by ad1992** [comment]
We are looking into this, cc @maielo

**Comment by maielo** [comment]
Hey @grnat we have shipped the fixed. Could you please try again?

**Comment by grnat** [comment]
That’s brilliant. Thanks Maielo!
