### ISSUE TITLE
Lock the new elements by default without the use of the lock icon when creating new objects.

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw#529]
Right now it's not very clear what the lock button does and I believe the behaviour when it's locked is the preferable. WDYT?

**Comment by vjeux** [comment]
I don’t think that locking should be the default. There are different use cases that require different behaviors and why we have an easy way to toggle between them.

We do need a better explanation of what this thing does though.

**Comment by dwelle** [comment]
I'd also move the lock button out from the tool bar as was originally suggested (I believe), and make it not look as another shape.
