### ISSUE TITLE
Open canvas in "zoom to fit all elements"

### ISSUE THREAD

**Issue by sojusnik** [excalidraw/excalidraw#5296]
Especially on big canvas, it would be much better to open them in "zoom to fit all elements" (shift + 1) to get a better overview, because at the moment you only see a small area of the canvas, when opening it. Sometimes this area is even blank, because the objects were moved to another place the canvas was started. This is confusing and leads to moments where you think that your canvas was deleted.

**Comment by sojusnik** [comment]
Yeah, we are all unique, as our preferences :)

**Comment by madukan** [comment]
Simply switching between the Markdown view and Excalidraw drawing view resets back to "show-all-content in the drawing". Ref: https://www.youtube.com/watch?v=nMYUnnVkw2g

**Comment by Mrazator** [comment]
Closing in favor of #5296
