### ISSUE TITLE
Update Twitter account and add it to readme

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw#532]
https://twitter.com/excalidraw

- [ ] Title: Excalidraw
- [ ] Logo
- [ ] Background image
- [ ] URL: https://excalidraw.com
- [ ] Add link to README

**Comment by vjeux** [comment]
Let me know if someone wants to manage the twitter account. I have the password

**Comment by lipis** [comment]
I can start and then we'll see.. :)
