### ISSUE TITLE
Pan view using space bar and mouse

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw#533]
In most apps (Figma, Photoshop, Sketch) you can pan the view by pressing spacebar and the pointer changes to hand, and you can move the scene around.

**Comment by voluntadpear** [comment]
Really useful for users without a trackpad

**Comment by dwelle** [comment]
Yep. Note that I've already implemented wheel-drag to pan canvas. But I agree we could also implement it this, too.

**Comment by voluntadpear** [comment]
I'll give this a try

**Comment by dwelle** [comment]
@voluntadpear be sure factor this PR's code out so you can re-use it https://github.com/excalidraw/excalidraw/pull/375/files
