### ISSUE TITLE
How can I locate the element by specific text on the canvas?

### ISSUE THREAD

**Issue by vwagen** [excalidraw/excalidraw#5342]
I had built a large canvas with many elements on it. And I was frustrated when I tried to locate an element by specific text content. Because I had to drag the canvas many times and had to check out each element to find out the one I want.
So, is there any thing like a search box where I can type some text to search my desirable element on the canvas?

**Comment by ad1992** [comment]
Hi @vwagen 👋🏻
Currently we don't have any such feature but this is definitely in the discussion . Closing this in favour of https://github.com/excalidraw/excalidraw/issues/3826

**Comment by vwagen** [comment]
Got it! Thanks so much.

**Comment by vwagen** [comment]
> Hi @vwagen 👋🏻 Currently we don't have any such feature but this is definitely in the discussion . Closing this in favour of #3826


Got it! Thanks so much.
