### ISSUE TITLE
[Feature Request] laser pointer

### ISSUE THREAD

**Issue by xuan-nguyen-swe** [excalidraw/excalidraw#5351]
It would be nice to have a laser pointer mode like Google Jamboard https://youtu.be/Sdphd6DpWfM

**Comment by anatoliibakhtin** [comment]
@nguyenxndaidev Hey 👋! 

if the function of the laser is to draw attention to a certain place in the drawing, then this can be achieved without the introduction of an additional tool using freedraw and then pressing the ctrl + z.

https://user-images.githubusercontent.com/71871141/177032620-0d3aa984-6821-47a4-805e-cf05edce9a22.mp4

**Comment by nguyenxndaidev** [comment]
@anatoliibakhtin I think, it's not convenient. Many times, we want to use the laser tool for a period (some minutes). In this case, we want to concentrate on the discussion without pressing anything except moving the cursor (pen or mouse).

**Comment by LePenseur13** [comment]
I support. This would be a cool feature.
Good Notes had a great implementation of it.

**Comment by topheman** [comment]
I would really like this feature 👍

**Comment by brook-w** [comment]
Is this issue no longer discussed? This function is a great function, I hope to support it

**Comment by dwelle** [comment]
Coming very soon!
