### ISSUE TITLE
Freeform vector tool

### ISSUE THREAD

**Issue by wokalski** [excalidraw/excalidraw#536]
related: https://github.com/excalidraw/excalidraw/issues/24

I would like to suggest a vector "drawing" tool where you can create an arbitrary vector shape by connecting points similar to vector tools in apps such as Sketch. I believe that it would be valuable even without supporting curved lines. I really missed a vector drawing like tool when I wanted to create an app mockup with a notch on top.

**Comment by wokalski** [comment]
I also see it mentioned here:
https://github.com/excalidraw/excalidraw/issues/366#issuecomment-575279919

**Comment by vjeux** [comment]
Agreed! I believe that the multi-point arrow work will be useful there. If the last point is the same as the first point then it becomes a shape and we can add a background to it.

**Comment by dwelle** [comment]
Well, I'm not writing hit testing for that one, that's for sure :sweat_smile:.

**Comment by vjeux** [comment]
We have curved lines so this I would say is done. Let's close it :)
