### ISSUE TITLE
Change the behaviour of shareable link

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw#537]
1. Click on get shareable URL.
2. Input bar appears with `Loading...` and the URL is being generated in the background
3. Once the URL is generated, updates the input with it and have it selected and focused.
4. Try to copy that into clipboard
5. Have a copy to clipboard button like in GitHub UI.
6. After the Dialog is closed the input disappears and the name is back

-----

With this UI we are not using any `alerts` or popups.
------

![image](https://user-images.githubusercontent.com/125676/73088925-e80bbf80-3edd-11ea-8050-e56c4a4491f0.png)

Source: https://excalidraw.com/?id=5193297203036160

**Comment by fernandoalava** [comment]
Yep I like that

**Comment by lipis** [comment]
@fernandoalava are you up for a challenge? Without using clipboard.js

**Comment by fernandoalava** [comment]
Yes, I'm in 💃, just I'm not sure if I can do this by weekend I will try promise

**Comment by lipis** [comment]
No rush.. so let's close the Firfox fix and work on this one.
