### ISSUE TITLE
Add Galician language

### ISSUE THREAD

**Issue by arponpes** [excalidraw/excalidraw#5373]
Hi, I would like to translate the app to Galician. I saw https://github.com/excalidraw/excalidraw/issues/1999 was opened but Galician is not available to translate as far as I can see.

Language picker: Galego

Thanks!

**Comment by ad1992** [comment]
Here you go https://crowdin.com/translate/excalidraw/10/en-gl?filter=basic&value=0

**Comment by arponpes** [comment]
Perfect, I guess we can close the issue. I'll be doing the translation. Thanks!
