### ISSUE TITLE
-bug: Ctrl+Z not working in a collaborative sesion

### ISSUE THREAD

**Issue by bautifrigole** [excalidraw/excalidraw#5375]
Ctrl+Z is not working in most cases when you are in a collaborative sesion.

**Comment by dwelle** [comment]
this is a known limitation of how undo/redo (history) works in multiplayer right now. We'll need to rewrite it, but it will take a some effort.

**Comment by clehene** [comment]
Is this what's causing data loss (can't redo, once I undo), or is that a separate issue?

**Comment by niemeyer** [comment]
Just wanted to add a vote here with some background: Excalidraw seems to be one of the best options for exchanging ideas over a video call while sharing a whiteboard, and the fact it's open source and uses end-to-end encryption puts it pretty much at the top of the list.  The one major drawback preventing its use at the moment is the broken undo/redo, as any simple mistakes become a "oh, damn.. let me fix that" moment in the call.

**Comment by romanr** [comment]
Same here, two days ago lost hours of work!

**Comment by dwelle** [comment]
Hey guys, we'll try to prioritize fixing this (but it's non-trivial). Can you elaborate a bit more on the loss of hours of work due to undo/redo not working in collab?

**Comment by bartekpacia** [comment]
Thank you, I really appreciate it.

It was 2 days ago but I'll do my best:
- I started working on a document on Excelidraw (free version, no account/paid workspace). I didn't save the document locally.
- The meeting started and I shared with my teammates a link to the document
- They joined and clicked a few times and made a small black dot with the `Draw` feature (this is so common on shared drawing boards, lol)
- I had the eraser selected and I accidentally clicked on the _text area_ that contained 3/4 of the content in the whole document. Something like the attached screenshot below but it wasn't divided into paragraphs – it was just a single big text.
  ![Screenshot 2023-05-18 at 10 37 38 PM](https://github.com/excalidraw/excalidraw/assets/40357511/5089e00d-fcf0-4f71-b519-980e34d2b0eb)
- After I deleted it, I tried to use CTRL+Z and the arrows in the bottom left corner, but they just didn't work - nothing was happening. The text was gone for good.

I cannot exclude that between: 
- (t = 0) me deleting the text
- (t = 2) me clicking CTRL+Z in panic trying to revert the delete text

they didn't make some changes (e.g. accidentally creating a black dot) at t = 1.

I wish I could give a more detailed bug report, but that's all I remember.

**Comment by dwelle** [comment]
Thanks @bartekpacia for the details!

**Comment by niemeyer** [comment]
It's easy to see how proper independent undo/redo histories for a single document requires some careful and time consuming work, but this is the foundation of online collaboration. I literally subscribe to this issue in GitHub so I can tell when I'll be able to start using Excalidraw.

**Comment by devnoname120** [comment]
This combined with the lack of history is a MASSIVE issue. This is an absolute deal breaker that makes introducing the tool to my team a no-go.

**Comment by theonlypwner** [comment]
#6926 might be related.

**Comment by theonlypwner** [comment]
Google Drive uses operational transforms, and it supports undo/redo by storing others' changes in the undo stack. It is described here: https://www.youtube.com/watch?v=hv14PTbkIs0

**Comment by devnoname120** [comment]
To be honest it's a shame that this issue isn't prioritized or *at the very least* put a mitigation in place. We are not talking about a new shiny feature here, we are talking about a problem where **users literally lose hours of work without any way to recover**.

Even something as simple as backing up the drawing every 1 minute would already go a very long way. A global undo would also be a very good first step  that would solve 80% of the problem. And someone even did a PR that already implements that! https://github.com/excalidraw/excalidraw/pull/6926

Currently we have the worst of both worlds because of what seems to be decision paralysis from the Excalidraw team.

**Comment by dwelle** [comment]
Status update: we're working on it right now.

**Comment by CMCDragonkai** [comment]
I'm afraid of giving my team full access cause they can edit and delete things by accident, I want to have Excalidraw properly backup all diagrams and have version control. Only then would I expand my membership to include the team accounts.

**Comment by zakx** [comment]
Chiming in here, also lost an hour of work due to this issue. :(

**Comment by Mrazator** [comment]
Status update: as part of [#7348](https://github.com/excalidraw/excalidraw/pull/7348), we've recently shipped support for multiplayer undo/redo on _excalidraw.com_ & will be shipped on _plus.excalidraw.com_ soonish!

Any feedback appreciated, in any case, reach us here or on Discord!

**Comment by niemeyer** [comment]
@Mrazator Thank you very much!  To try it out and in support, I've just subscribed.

**Comment by kirillrocks** [comment]
Still suffering form an issue with Control+Z. Even the manual click on Undo/Redo is not working. Stopping us from using it as often causing to lose work. Not working even in a single session.

**Comment by devnoname120** [comment]
This works great so far, thanks a lot! Will report back if I have any issues.

**Comment by deku0818** [comment]
Just now, while using the Excalidraw plugin in Obsidian, I tried to undo an action with Ctrl+Z. However, all my content was cleared and could not be recovered. Then, I went to another file and pressed Ctrl+Z, which also cleared that file. This has caused me to lose several days of work.
