### ISSUE TITLE
Feature Request: Make the eraser icon more prominent

### ISSUE THREAD

**Issue by wedsonxse** [excalidraw/excalidraw#5382]
Its more like an UX/UI issue, the eraser icon is currently at a very strange position from a user perspective.

In my experience, in the first time i was using the excalidraw, i tought that the eraser icon didnt exist at all

**Comment by LePenseur13** [comment]
Same issue with me

**Comment by artemanufrij** [comment]
In my opinion it make sense to put it into tool bar.

**Comment by artemanufrij** [comment]
Issue can be closed. Icon was moved into tool bar on the top. :+1: 

![Screenshot_20221102_114109](https://user-images.githubusercontent.com/16517095/199469288-375c0e58-372f-42bf-b46f-bebf6b7a4862.png)

**Comment by maielo** [comment]
thanks!

**Comment by wedsonxse** [comment]
Fixed
