### ISSUE TITLE
browser zoom toast false positive when container larger than viewport

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#5438]
When the excalidraw container is larger than viewport, we get a false positive on the browser zoom detection.

Repro: https://codesandbox.io/s/upbeat-montalcini-pxf4dw?file=/src/App.tsx

**Comment by dwelle** [comment]
I'm also getting a lot of false positives when randomly changing viewport dimensions, though mostly in dev. But still.

![image](https://user-images.githubusercontent.com/5153846/180640284-77a37e83-65a0-4bb9-b85d-fb2820bb54b3.png)

**Comment by ad1992** [comment]
closing via https://github.com/excalidraw/excalidraw/pull/5495, we have removed the browsers' zoom popup
