### ISSUE TITLE
[FR] Identical Drag/Click Behavior (straight lines)

### ISSUE THREAD

**Issue by Servinjesus1** [excalidraw/excalidraw#5484]
# Match Behavior Across Drag and By-Click Modes of Drawing

I am a by-click drawer, meaning when I want to place a graphical object (be it line, circle, et cetera), I click once at the starting point (starting vertex, circle center), then again at drawing end. Excalidraw tries to offer an optimized multi-function approach to this: whereas most tools are drag-only, one can drag or by-click place lines and arrows, the former creating single-leg elements with the latter allowing for multi-leg. However, this precludes by-clickers from placing angle-clamped lines, for example, or placing other features like circles by-click. It would be awesome if, where the two aren't specifically unique (i.e. for quicker drawing of single-leg lines), the behavior was identical between drag and by-click methods of drawing. AFAIK, this includes modifying/adding the following features:

1. By-Click Rectangles+Diamonds+Circles (click first for bottom-left vertex/center/center respectively, second for top-right/top-right/center)
    - Essentially, flip Alt and non-Alt behavior
2. Shift-Clamping of By-Click Arrows+Lines
3. Multi-Leg Shift-Clamp Support
    - Probably makes sense to lump into this FR for the sake of compatibility with by-clicks multi-leg behavior.

These features would really help CADdies like me :)

## Similar Issues

This FR is in the spirit of #5255, and my own frustrations trying to draw angle-clamped lines by-click.

**Comment by dwelle** [comment]
> By-Click Rectangles+Diamonds+Circles (click once for bottom-left vertex/center/center respectively, twice for top-right/top-right/center)

Interesting. What should happen when you on the 2nd click, finish the shape on `pointerup` (mouse up)? Whereas while hold-dragging it'd allow you to change the size still?

**Comment by Servinjesus1** [comment]
@dwelle Just so we're clear, I meant "first" and "second" click, not single click and double click (changed my wording in post).

Also, I realized what I want as far as circles/diamonds go is just flipping the Alt behavior with the non-Alt behavior :) It's more intuitive for me, since I usually center these tools about things.

**Comment by Servinjesus1** [comment]
Closing as redundant to #5255. For centered shapes, hold `Alt`.
