### ISSUE TITLE
Is it possible to permanently turn off the zoom pop-up?

### ISSUE THREAD

**Issue by grnat** [excalidraw/excalidraw#5493]
I'm getting pretty over being told about my browser's zoom.

![image](https://user-images.githubusercontent.com/12093361/181213749-0e6810c6-1d89-43fa-9ae0-6e0a79100113.png)

**Comment by ad1992** [comment]
Hi @grnat 👋🏻
There is no way to turn off this popup as of now. But can you tell what is triggering the zoom popup ? And we can try looking in to fixing that.

**Comment by dwelle** [comment]
I think we should unship this until we can come up with something safer (tracking in https://github.com/excalidraw/excalidraw/issues/5438).

**Comment by ad1992** [comment]
closing via https://github.com/excalidraw/excalidraw/pull/5495, we have removed the browsers' zoom popup
