### ISSUE TITLE
Display scene name before "Excalidraw Plus" in page title

### ISSUE THREAD

**Issue by abramdawson** [excalidraw/excalidraw#5496]
When I have multiple scenes open in Excalidraw Plus, I'm unable to see which scene corresponds to which tab since "Excalidraw Plus" is displayed before the scene name. This makes selecting the right tab difficult, and is particularly problematic if multiple scenes start with the same letters/words.

<img width="569" alt="image" src="https://user-images.githubusercontent.com/2624720/181327726-5687dce3-f166-4e49-8962-6b4dbce015fb.png">

I propose placing the scene name as the first item in the page title (i.e. `{scene.name} — Excalidraw Plus` instead of `Excalidraw Plus – {scene.name}`).

This pattern of displaying the item first and brand/product second is common in many other products today (examples below).

<img width="588" alt="image" src="https://user-images.githubusercontent.com/2624720/181316570-659c5d90-56e2-4e4c-a4dd-07f8e26681ed.png">

**Comment by dwelle** [comment]
Good point!

Personally I do not notice this because my tabs end up looking like this pretty fast:

![image](https://user-images.githubusercontent.com/5153846/181374979-3e3ea3b3-5a6d-4f7f-9824-8520a7e83f91.png)

Now fixed!
