### ISSUE TITLE
Allow text boxes

### ISSUE THREAD

**Issue by navakelvin** [excalidraw/excalidraw#5497]
Text boxes allow for better manipulation of information as you can define the limits at which you want the text to make a line break.

![image](https://user-images.githubusercontent.com/77164639/181369482-8f25d3ef-8797-4336-b3c8-0c5eb343402d.png)

For text size manipulation an idea could be contextual buttons that pop up when you select the whole box.

**Comment by dwelle** [comment]
On the roadmap #4267 and we'll get to it soon!
