### ISSUE TITLE
Deleted elements preventing persistence

### ISSUE THREAD

**Issue by ummcheng** [excalidraw/excalidraw#5502]
Hi all, we've forked the Excalidraw client over at https://github.com/peoplerenaissance/excalidraw and have been loving it so far.

Changes in our fork include swapping the backend from Firebase to an HTTP REST API that supports the same persistence operations (among other UI adjustments for our product's use case), and we've had many successful collaborative drawing sessions so far.

Unfortunately, today we discovered a drawing that won't automatically save, which I believe is related to https://github.com/excalidraw/excalidraw/pull/5108, filtering deleted elements prior to persisting:
 
<img width="999" alt="Screen Shot 2022-07-28 at 11 42 35" src="https://user-images.githubusercontent.com/5747974/181581442-fc5e7a8d-78a3-48e0-abad-9c9d48510bf9.png">

For our use case, I'll make a temporary [fix in our fork](https://github.com/peoplerenaissance/excalidraw/commit/746b55362bf620a5e7041399f64169d0500be94a#diff-d57c40d527dc56c4dba8b89685a3b2e2e90c3a09094693a7eaf068ad1d2d76ea) to sync all elements, including deleted ones, but I'd love some pointers into understanding how this might be caused and if we can prevent it in the future, or if we can help contribute to an upstream fix.

Thanks!

**Comment by DanielJGeiger** [comment]
@ummcheng I opened #5108 because over the course of a semester, the boards I taught on stopped saving to Firebase due to deleted elements filling up storage.  It sounds like you're seeing similar symptoms, if for different reasons.  CC @dwelle on the recurrence of scenes failing to save.

**Comment by ad1992** [comment]
@ummcheng could you share little more context on why filtering out deleted elements is an issue ? We don't save the elements which are deleted and is not updated in last 24 hours.  Are you seeing some inconsistency due to this ?

**Comment by ummcheng** [comment]
Appreciate the prompt attention and help from both of you. 

Yes, it seems like somehow the drawing we have saved in storage has deleted elements that have not been updated in the last 24 hours. On the initial load, all of the elements are included in the calculated scene version, which in this case is `7977`. Then when other changes are made, the scene version calculation excludes those deleted elements (in this case resulting in `6643`, and doesn't attempt to the save the scene, even though the scene is now "newer".
 
I haven't fully traced the lifecycle of deleted elements and how they're updated but I wonder if this is the simplified version of what we experienced:

1. A scene is created (no elements, so calculated version is 0).
2. An element is created and added to the scene (calculated version is 1). The scene is saved.
3. The element is deleted and the scene is still saved to storage since the update time is < 24 hours (version 2).
4. 24 hours later, the scene is loaded and the client calculates the scene version is 2 (including the deleted element).
5. When the save handler is called, the scene version is calculated to be 0 since the deleted element is filtered out, and since the version stored is 2, the save is skipped.

Does that sound plausible at all?

**Comment by dwelle** [comment]
> I haven't fully traced the lifecycle of deleted elements and how they're updated but I wonder if this is the simplified version of what we experienced:
> 
> 1. A scene is created (no elements, so calculated version is 0).
> 2. An element is created and added to the scene (calculated version is 1). The scene is saved.
> 3. The element is deleted and the scene is still saved to storage since the update time is < 24 hours (version 2).
> 4. 24 hours later, the scene is loaded and the client calculates the scene version is 2 (including the deleted element).
> 5. When the save handler is called, the scene version is calculated to be 0 since the deleted element is filtered out, and since the version stored is 2, the save is skipped.
> 
> Does that sound plausible at all?

It does sound plausible, and is most like what you're seeing in your project.

This specific problem shouldn't affect excalidraw.com, because we're filtering out the "dead" elements on load before we cache the version:

https://github.com/excalidraw/excalidraw/blob/3d5356cb8edc043a721a5e66167b2814b191ebc2/src/excalidraw-app/data/firebase.ts#L290-L296

Whereas in your project you're not doing so:

https://github.com/peoplerenaissance/excalidraw/blob/746b55362bf620a5e7041399f64169d0500be94a/src/excalidraw-app/data/httpStorage.ts#L112-L117

**Comment by ummcheng** [comment]
Oh wow, thanks so much for digging in our fork and discovering that! We did remove the encryption functionality and I must have totally missed using `getSyncableElements()` on the initial load.

Thanks again for the help even though this doesn't affect upstream Excalidraw! Will close this issue 🎉
