### ISSUE TITLE
React 18 breaks dev-build chart creation

### ISSUE THREAD

**Issue by DanielJGeiger** [excalidraw/excalidraw#5503]
Was the upgrade to React 18 bumpier than believed?  While fixing a charts bug I previously found, I discovered chart creation is broken in development builds (ie `yarn start`), but not in production builds.  Line 58 of `src/components/PasteChartDialog.tsx` throws an error because `svg` is `undefined`.  Reverting to commit 958ebea makes chart creation work again in development builds.

**Comment by ad1992** [comment]
@DanielJGeiger you mean `yarn start` is was broken for you after upgrading to `React  18` ? That shouldn't happen and its working fine. Did you miss running `yarn install` by any chance ?

**Comment by ad1992** [comment]
closed via #5505
