### ISSUE TITLE
Panning on android draws

### ISSUE THREAD

**Issue by sandorex** [excalidraw/excalidraw#5506]
I don't know if android is actually supported or not but whenever i pan with two fingers it draws a line between them if i am using the line tool or the pen
It makes it hard to use as i cannot pan the canvas or even zoom without drawing

**Comment by sandorex** [comment]
This is actually a duplicate of https://github.com/excalidraw/excalidraw/issues/966 any few other issues mention it so i will close it

**Comment by dwelle** [comment]
Yeah. I believe someone from the community wanted to work on this. We'll need to check how it's going.
