### ISSUE TITLE
Same command for different work. `Alt + 'k'`

### ISSUE THREAD

**Issue by theabhayprajapati** [excalidraw/excalidraw#5512]
## Alt + k has two different works. 😔
<img width="243" alt="image" src="https://user-images.githubusercontent.com/88815641/181916096-8068d343-6ee5-44bc-9500-8cde6122c31e.png">

- Alt works properly for **selecting post method**.
- but not for navigating to the **profile page**.

## How can be fixed 👷
Updating the command for any one of the functions can resolve the issue, mostly updating the command for **navigating profile**.

**Comment by dwelle** [comment]
This doesn't look like it relates to Excalidraw — what product are we talking about?

**Comment by theabhayprajapati** [comment]
sorry, I was making an issue with hoppscotch I by mistake sent it here.
