### ISSUE TITLE
improve shape<->cursor alignment for proportional resize / angle clamping

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#5513]
We should improve how we fit/align lines/shapes to the cursor position when creating shapes while holding shift to maintain aspect ratio, or clamp angles.

In the examples below, we want to behave in a way that Figma does (but it applies to most other apps out there).

### rectangles (squares)

Here's excalidraw when creating a square by holding a shift:

![excal_proportional_resize_square](https://user-images.githubusercontent.com/5153846/181919239-6a1e57cc-060d-47fd-88ea-35f6bc09752f.gif)

Here's figma (notice that the cursor always aligns perfectly to the bounding box):

![figma_proportional_resize_square](https://user-images.githubusercontent.com/5153846/181919243-649d1a17-65e0-4f51-86e6-64f85a9aa632.gif)

But, it works correctly even in Excalidraw when the square (or a rectangle) already exists, and you resize it:

![excal_proportional_resize_square_existing](https://user-images.githubusercontent.com/5153846/181919456-6a96b182-38e4-424d-84f2-e7b3c25f6ee3.gif)

### lines/arrows

Excalidraw line angle clamping by holding shift:

![excal_line_angle_clamping](https://user-images.githubusercontent.com/5153846/181919357-e7f84b5d-920b-43d0-9b0b-5555af60d13a.gif)

Figma (notice that the cursor is always best-effort aligned, where you can draw a [normal](https://en.wikipedia.org/wiki/Normal_(geometry)) from the line's tip to the cursor):

![figma_line_angle_clamping](https://user-images.githubusercontent.com/5153846/181919394-7c6c7439-8aaf-46e3-8964-dbb805a982f6.gif)

So we want the lines to be aligned like this (in black are actual lines/cursor position, in red is the ideal):

![image](https://user-images.githubusercontent.com/5153846/181919795-48eb510d-e211-464f-a208-b8b22ba4b2c7.png)

**Comment by ryan-di** [comment]
Here's the cursor alignment fix non-linear generic elements: https://github.com/excalidraw/excalidraw/pull/5516

Working on linear elements cursor alignment next.
