### ISSUE TITLE
Resizing shapes distorts them

### ISSUE THREAD

**Issue by alexforster** [excalidraw/excalidraw#5528]
![excalidraw](https://user-images.githubusercontent.com/104311/182457390-9122d7d9-c207-44ae-a28e-d9010dd7c23f.gif)

Sorry, I don't know how to describe this – please update the issue title/description as appropriate.

**Comment by DDay987** [comment]
I have also noticed this. 
It seems to affect library and user created icons/groupings.

![Example with user created](https://user-images.githubusercontent.com/36208309/183266365-816bcd64-4aac-4ad7-b04c-4bac110ababc.gif)
![Example with library imported](https://user-images.githubusercontent.com/36208309/183266367-7a823124-d0d7-4e45-95a2-3d0dce825f13.gif)

**Comment by dwelle** [comment]
It was happening before, though not with a lot of elements — but it may may have gotten worse. I'll try to take a look soon.

Closing in favor of https://github.com/excalidraw/excalidraw/issues/4001
