### ISSUE TITLE
How do you input text in a object on the iPad?

### ISSUE THREAD

**Issue by ShravanSunder** [excalidraw/excalidraw#5531]
On a desktop, when you create a shape, you can press `enter` and have text in the center of the shape.  This is the `press enter to add text` interaction. The advantage is that the text is immediately grouped with the shape and its much more pleasurable and easier to use excalidraw.

On a touch screen, when you create a shape, i'm unable to input the interaction that would let me enter text in the center of the shape.  

Is there an interaction or something i'm missing? @dwelle  

If not could we add a button on the sidebar?  Like in these actions that enables `press enter to add text`? 
<img width="152" alt="2022 08 03-09 57-Brave Browser Excalidraw" src="https://user-images.githubusercontent.com/5294949/182626682-74919d0a-1dc2-42da-9634-d12939b93da9.png">

Or a touch interaction that allows `press enter to add text`? 

This would make excalidraw much more usable in iPad.  Having an easily shape grouped with text, makes it very easy to create diagrams and shapes that can be moved around.

**Comment by zsviczian** [comment]
double tap the center of the object and start typing.

**Comment by ShravanSunder** [comment]
perfect @zsviczian  thank you!
