### ISSUE TITLE
Shift + drag to resize line in constrained axis not working since the linear elements redesign (#5501)

### ISSUE THREAD

**Issue by karandwivedi42** [excalidraw/excalidraw#5537]
A side effect of #5501 is that I am not able to resize the line while keeping it constrained horizontally. In the new mode, shift + drag is the same as drag and does not keep the motion constrained.

**Comment by dwelle** [comment]
Is it fixed for you here? https://excalidraw-git-fork-ryan-di-line-edit-clamp-excalidraw.vercel.app/ (https://github.com/excalidraw/excalidraw/pull/5527)

**Comment by karandwivedi42** [comment]
Yes 🎉
