### ISSUE TITLE
shareable link not replacing content, but merging

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#5546]
(via @TonyForTheNguyen via Discord)

**Comment by TonyForTheNguyen** [comment]
_Sometimes_ a blank canvas loads when a user clicks the excalidraw JSON link.

### Steps to repro (sometimes):
1. Draw something on excalidraw
2. Click a JSON Excalidraw link such as https://excalidraw.com/#json=AO0CWeSUQb6WD5U4oaqMs,3MJOeSqi6WEpbwULEmLbJA
3. You will be prompted with a dialog `Loading external drawing will replace your existing content. Do you wish to continue?`
4. Click Yes
5. Expectation: The previous canvas will be erased and painted with the JSON content
6. Actual: The previous canvas is not erased && painted with the JSON content

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/8094664/183257557-e903201e-b9a3-47d6-aa93-4bf0e2a97319.png">
