### ISSUE TITLE
React 18 ContextMenu render - error use createRoot instead

### ISSUE THREAD

**Issue by zsviczian** [excalidraw/excalidraw#5551]
I migrated the Obsidian plugin to React 18. 
I changed ReactDOM.render to createRoot - that works ok. I am getting this error when I open the context menu. Interestingly the same error is not thrown on excalidraw.com. Any idea where I should look for the root cause? Or should the ContextMenu render be migrated to createRoot?

![image](https://user-images.githubusercontent.com/14358394/183475562-b2383828-d807-42a0-a256-622beefe3443.png)

https://github.com/excalidraw/excalidraw/blob/2d800feeeb408603f1b8536fd2adafe20f9c397a/src/components/ContextMenu.tsx#L135-L145

**Comment by zsviczian** [comment]
ok. so it is not showing on Excalidraw.com because it is a production build... This function should be upgraded to React 18

**Comment by ad1992** [comment]
yep there are few other places as well eg tests where this warning is shown. But since the app we still want to keep it compatible with React 17 hence we can't remove it from the editor. Though I will fix it in the test.

**Comment by dwelle** [comment]
We don't need to use `React.render` even in v17.

**Comment by ad1992** [comment]
> We don't need to use `React.render` even in v17.

You are right!. Will need some rewrite. Will fix.
