### ISSUE TITLE
[React 18] Chart shading broken in production builds

### ISSUE THREAD

**Issue by DanielJGeiger** [excalidraw/excalidraw#5562]
While making some recent commits to #2993, I noticed the random-color shading of chart backgrounds appears to be broken on production builds (including excalidraw.com), but not on development builds.  I suspect this is a React 18 upgrade regression, similar to #5503.  The following images demonstrate the issue.

From my local machine:
![image](https://user-images.githubusercontent.com/1852529/184172462-0e645317-2427-4835-a3f4-ed37df8283fa.png)

From the Vercel [preview](https://excalidraw-git-fork-danieljgeiger-asciimath-mode-excalidraw.vercel.app/) of #2993:
![image](https://user-images.githubusercontent.com/1852529/184172635-d7817b0f-4d93-402c-9774-b6ab40b5fd93.png)

And from excalidraw.com:
![image](https://user-images.githubusercontent.com/1852529/184173098-68fffcf4-fe9c-495a-89ae-6b3f325481ea.png)

**Comment by ad1992** [comment]
@DanielJGeiger could you share a scene link for this drawing which we can check in production ?

**Comment by DanielJGeiger** [comment]
@ad1992 The issue arises when creating charts by pasting CSV contents from the clipboard.  So, I think a scene link might not help.  Here is what I pasted to generate the charts in this issue:
```
\(x\),\(\bar y\) mean
\(\frac{1}{2}\),1
1,2.5
\(3x^2\),5
6,8.5
```

Both MathJax and the "Crisp" subtype were active in the [Vercel preview](https://excalidraw-git-fork-danieljgeiger-asciimath-mode-excalidraw.vercel.app/).
