### ISSUE TITLE
Excalidraw+ with custom font

### ISSUE THREAD

**Issue by imshenshen** [excalidraw/excalidraw#5572]
need this feature in Excalidraw+, not self-hosted version

**Comment by hulkbig** [comment]
@imshenshen  hi, you can try my fork version: [https://excalidraw-zh.com/](https://excalidraw-zh.com/)

**Comment by imshenshen** [comment]
> @imshenshen hi, you can try my fork version: https://excalidraw-zh.com/
已经在私服做部署修改了
