### ISSUE TITLE
Can't sign-in using github account

### ISSUE THREAD

**Issue by 810123** [excalidraw/excalidraw#5601]
I tired both google and github, neither can sign-in

![image](https://user-images.githubusercontent.com/9276574/185773194-ce972359-17bf-4042-9141-d4b4c4bb2c7f.png)
![image](https://user-images.githubusercontent.com/9276574/185773196-31f0c92e-51bf-45ee-8358-c7def8c1e894.png)

**Comment by dwelle** [comment]
Hi! It looks like it's one of the cases of Firebase being blocked for you for one reason or another, and there's likely not much we can do — apart from migrating to a different host, which is on the roadmap.

If you're behind a company firewall/VPN, then maybe you can do something on your end. If not, then waiting a few days has helped in some cases. 🤷‍♂️

Feel free to contact us at `support @ excalidraw.com` with more details.

**Comment by 810123** [comment]
Thanks, I tried on my mobile, and my personal laptop, the same problem ... crying...
