### ISSUE TITLE
Bug - Images in a note.excalidraw doesn't appear

### ISSUE THREAD

**Issue by selpolselpol** [excalidraw/excalidraw#5605]
Last version of Excalidraw and Obsidian (1.7 and 0.15.9 respectively)

Images in a note with Excalidraw does not appear, but they are still in their folders in Obsidian.

https://user-images.githubusercontent.com/55896022/185801276-43e7bd2d-48a9-44c7-9a34-37ede209cbfe.mp4

[obsidian.md-1661094174551.log](https://github.com/excalidraw/excalidraw/files/9389562/obsidian.md-1661094174551.log)
 -
[obsidian.md-1661094178888.log](https://github.com/excalidraw/excalidraw/files/9389563/obsidian.md-1661094178888.log)
[obsidian.md-1661094181918.log](https://github.com/excalidraw/excalidraw/files/9389564/obsidian.md-1661094181918.log)

**Comment by ad1992** [comment]
cc @zsviczian

**Comment by dwelle** [comment]
@zsviczian also check if those images don't just have a bad `status` (non-`saved`).

**Comment by dwelle** [comment]
Closing as unactionable.
