### ISSUE TITLE
I lost all my data | fedora google chrone | no session

### ISSUE THREAD

**Issue by mangele** [excalidraw/excalidraw#5607]
I have been working on excalidraw. But I never created a session or such; I only used to enter here: https://excalidraw.com/ .  Today when I restarted my linux fedora computer, it upgraded google chrome as well, and all my diagrams are gone! Please do you know if there is anywhere on my computer I should look into? Also,I have the desktop app. 

Btw sorry for bringing this here, but this data is really important for my work and study.

Thanks so much for your time.

**Comment by ad1992** [comment]
Hey so sorry for your loss! Were you using incognito by any chance ? All the data is saved to browser local storage so as long as thats not cleared / you are using incognito mode the data will persist in the browser.

**Comment by mangele** [comment]
Hey, thanks for getting back to me so quickly. No, I wasn't. I think when I restarted my computer, my fedora laptop updated some processes, including google chrome. I realised that because I had to log in again. But when I opened Excalidraw, everything was gone. Is there any path on Linux I can have a look at?
Thanks a lot for your time.

**Comment by ad1992** [comment]
Since the data is lost, there is no way we can recover it since its stored in browser local storage :(. 
By any chance do you have the below setting turned on under Chrome settings -> Privacy and Security -> Cookies and other site data
<img width="689" alt="Screenshot 2022-08-22 at 12 00 59 PM" src="https://user-images.githubusercontent.com/11256141/185854678-0efe1d77-84e9-4567-8a2f-c4f3616497a4.png">

**Comment by mangele** [comment]
I see :(. No, I don't have turned on this option. I guess when my computer updated chrome, my cookies gone together with my excalidraw diagrams, right? So, what is the most secure way to use Excalidraw? besides the paid option?

**Comment by ad1992** [comment]
Yes it looks like all your browser data and site data was removed when updating chrome. 
To avoid in future you can save a copy of your drawings in local 
![image](https://user-images.githubusercontent.com/11256141/185901362-6888b147-ddc1-4713-a421-30ea4a783765.png)
![image](https://user-images.githubusercontent.com/11256141/185901419-3b380405-7491-4a1e-9f5c-fe74ee9c3053.png)

Also you can use shareable links to export your drawings
![image](https://user-images.githubusercontent.com/11256141/185901686-8b528706-71bd-4626-a024-57aa1274f295.png)

**Comment by ad1992** [comment]
closing this, please feel free to reopen if this occurs again
