### ISSUE TITLE
Native application

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#561]
Would be great to wrap excalidraw within electron (or equivalent) and publish it as a native application to the various app stores.

**Comment by voluntadpear** [comment]
What about making it a PWA instead? Android currently supports adding them to the Play Store as [Trusted Web Activities](https://developers.google.com/web/updates/2019/08/twas-quickstart) and hopefully iOS will do the same soon.

On Desktop, Chrome lets you download a desktop shortcut to a PWA.

**Comment by vjeux** [comment]
We should do both :)

**Comment by lipis** [comment]
https://excalidraw.com/?id=5742560236535808 :D

**Comment by bringking** [comment]
I am now obsessed with using this for all my diagram needs at work. I have a little experience with it. Would love to help this effort. Are you thinking this be co-located in this repo? Or in another one?

**Comment by lipis** [comment]
I think it would be more sane to have it in a different repo.

**Comment by bringking** [comment]
@lipis yeah, the tradeoff being some work would need to take place to make the core sharable between the Native and Web app?

**Comment by lipis** [comment]
https://github.com/excalidraw/excalidraw-desktop

**Comment by voluntadpear** [comment]
I can work on make the regular Web version a PWA if you'd agree it'll be useful. cc @vjeux

**Comment by vjeux** [comment]
Yeah, that would be great @voluntadpear !

**Comment by nrgapple** [comment]
A local electron build would be great for all working in a secure environment where reaching out to an external server is not possible for sensitive information

**Comment by dwelle** [comment]
@nrgapple all data sent to our server is encrypted on client, so that our server cannot read it even if it wanted.

![image](https://user-images.githubusercontent.com/5153846/74843222-e8a44400-532b-11ea-9814-1a1186be7ff5.png)

**Comment by nrgapple** [comment]
Thanks @dwelle for the fast response. The encryption feature should work in theory. But convincing management that a change will not happen while using the web that leaks info is hard. Would there be a way to manually build and wrap it in an electron application?

**Comment by dwelle** [comment]
> The encryption feature should work in theory. But convincing management that a change will not happen while using the web that leaks info is hard. 

Not that we send data to our server only when you share your scene via link, and that feature will remain there even in the desktop application --- how else would you want to share your scene with others? Well, you can download it to a JSON file and pass it around manually, but you can already do so in the web app, and no data is leaked to server at all.

> Would there be a way to manually build and wrap it in an electron application?

Well, we're planning to do it ourselves, but not sure about the timeframe. You can of course try to do so yourself, it shouldn't be that hard.

**Comment by j-f1** [comment]
I started a mobile app for iOS:

<img width="200" alt="Screenshot_2020-02-22 19 11 24" src="https://user-images.githubusercontent.com/25517624/75101232-2b258500-55a7-11ea-849d-ab01a38fc2cb.png">

It looks nice but still needs some handling in-app, like additional features to make it more than just a web app (which is forbidden by the app store guidelines) and correctly working around the notch (it currently clips just below it rather than allowing the drawings to scroll into the ears:

![image](https://user-images.githubusercontent.com/25517624/75101249-5c05ba00-55a7-11ea-8c3e-77bb943e2d1d.png)

(PS: the iOS simulator is a great tool for developing mobile sites. Hold option to bring up the pinch tool.)

**Comment by j-f1** [comment]
It also lets me create a mac app that’s 150KB (!)

**Comment by lipis** [comment]
I think we can close that one: https://github.com/excalidraw/excalidraw-desktop

**Comment by dragonDScript** [comment]
I think Electron was too heavy for a simple web wrapper, you could use the system's webview (or a PWA).

**Comment by lipis** [comment]
@dragonDScript We stopped using Electron: https://blog.excalidraw.com/deprecating-excalidraw-electron/

**Comment by dragonDScript** [comment]
I know, thank you anyway.

**Comment by mrdc** [comment]
@j-f1 Hi, is it PWA that was installed on macOS?

@lipis Unfortunately, when using SRware Iron (Chrome based) on macOS 10.15.7 I have no prompts or options to install Excalidraw as an app.

**Comment by dwelle** [comment]
If SRware Iron disables PWAs for whatever reason, nothing we can do about it.

If you care about privacy, use https://brave.com/

**Comment by j-f1** [comment]
@mrdc No, it’s just a basic AppKit app that displays a web view pointing to the Excalidraw website.

**Comment by mrdc** [comment]
> @mrdc No, it’s just a basic AppKit app that displays a web view pointing to the Excalidraw website.

Thanks, I’ve made an app and it’s 11,5MB :/

**Comment by j-f1** [comment]
Here’s the code if you want to test and update it: https://github.com/j-f1/excalidraw-mac

**Comment by solarkraft** [comment]
An Android app would allow the use of high resolution pointer events, which would enable handwriting support. 

(Web browsers are *supposed to* support it, but none on Android do. Maybe lobbying for proper support on that end could accomplish the goal too)
