### ISSUE TITLE
Theme settings are reset after turning a collaboration session on and off

### ISSUE THREAD

**Issue by nikitapozdeev** [excalidraw/excalidraw#5622]
Hi!

I ran into some problem. I chose the "dark" theme, but sometimes after turning the collaboration session on and off, the theme resets to "light".

### Steps to reproduce
1. Clear localStorage and refresh the page.
2. Choose "dark" theme. In localStorage theme also switches to "dark".
3. Start collab session.
4. Refresh the page. Here the theme automatically switches to "light" and that's strange. But in localStorage the theme is still "dark".
5. Stop collab session. After this, the theme in localStorage sets to "light" as well.

### Expected behavior
Theme settings should not be reset after turning a collaboration session on and off.

### System
macOS 12.5.1 (arm64)
Chrome 104.0.5112.101

**Comment by mabdullahadeel** [comment]
It looks like it's a bug 🐛.
I was able to reproduce it on my end.

### System
Windows 10 (21H2)
Chrome Version 104.0.5112.81 (Official Build) (64-bit)

## I am working on the potential fix
