### ISSUE TITLE
help icon disappear ?

### ISSUE THREAD

**Issue by guocf20** [excalidraw/excalidraw#5630]
i'm not good at frontend.  my temp solution  
src/components/Footer.tsx 

      <div
      className={clsx(
          "layer-ui__wrapper__footer-right zen-mode-transition",
           {
            "transition-right disable-pointerEvents": appState.zenModeEnabled,
          },
        )}
      >
      {actionManager.renderAction("toggleShortcuts")}
    </div>

**Comment by dwelle** [comment]
Oops, fixed!
