### ISSUE TITLE
3. 🐞jumping text

### ISSUE THREAD

**Issue by anatoliibakhtin** [excalidraw/excalidraw#5642]
Hello dear developer ! my problem:

3. Jumping text - I didn't see a pattern after which number of clicks or on which part of the block, it starts jumping to the upper left part of the canvas if you've just created the canvas:  

https://user-images.githubusercontent.com/71871141/187664032-2a4b3f07-208f-41db-8236-648572bdbd0c.mp4

Cool if the font doesn't bounce when editing :)

Thank you for your attention !🌼

**Comment by IzMichael** [comment]
I'm also getting this issue on my touchscreen laptop.

**Comment by ad1992** [comment]
> @ad1992 Sorry, most likely you have to choose when and what to close.

Hey no worries, its shipped so closing this issue :)
