### ISSUE TITLE
8. 🐞the buttons are bouncing

### ISSUE THREAD

**Issue by anatoliibakhtin** [excalidraw/excalidraw#5647]
Hello dear developer ! my problem:

8. Buttons bounce - I almost never missed hitting the "undo/redo" buttons, it just seems weird, funny that they're bouncing.

https://user-images.githubusercontent.com/71871141/187638904-13e83cd2-5aa0-4fbb-87ff-9a2db2d6d88d.mp4

![Obsidian_I0NYcjZVkE](https://user-images.githubusercontent.com/71871141/188131396-a5d59533-88ba-4079-8266-e4855b800102.jpg)

It is expected that the same button occupies the same place to use without regard to the interface. 

Thank you for your attention !🌺

**Comment by ad1992** [comment]
This should be fixed by https://github.com/excalidraw/excalidraw/pull/5658

**Comment by anatoliibakhtin** [comment]
very cool, multiplayer development !🌎
