### ISSUE TITLE
feat: consider multiple locked elements as a single group when unlocking

### ISSUE THREAD

**Issue by anatoliibakhtin** [excalidraw/excalidraw#5650]
Hello dear ! My problem:

11. Several locked elements are very difficult and long to unlock, if there are more than 1.

 There is need "fake auto-grouping" of elements, before locking/unlock all instead of clicking on each of the 100 little elements. Double quick click on item - will highlight only one item to unlock. 

https://user-images.githubusercontent.com/71871141/187657401-b1d17430-e161-4d7f-849a-f01143f69e0f.mp4

like the [Miro](https://miro.com/app)
![Obsidian_IOHECXzrTt](https://user-images.githubusercontent.com/71871141/188130745-30d30fb8-0a20-4bbb-b46d-aba926e02046.jpg)

Thank you for your attention !🌸

**Comment by docmars** [comment]
To add, it would be super nice to have an **Unlock All** keyboard shortcut and/or a button somewhere to do this.

**Comment by devagja** [comment]
I have the same problem, was resolved? @docmars solution would be great

**Comment by dwelle** [comment]
> There is need "fake auto-grouping" of elements, before locking/unlock all instead of clicking on each of the 100 little elements. Double quick click on item - will highlight only one item to unlock.

That's an interesting behavior, but I wonder how to implement without adding a completely new concept that's identical to groups, but isn't groups :).

For now, I've added "unlock all" to canvas contextMenu as suggested by @devagja https://github.com/excalidraw/excalidraw/pull/5894

**Comment by anatoliibakhtin** [comment]
Unlock all it's nice
