### ISSUE TITLE
Bug: when resize shape with associated text element, font size changes very much

### ISSUE THREAD

**Issue by pavelpower** [excalidraw/excalidraw#5666]
https://github.com/excalidraw/excalidraw/blob/ad0c4c4c78f4e87e8eae96184a909bc9fec6e1ba/src/element/resizeElements.ts#L510-L511

Solveing: change size of a text element by difference old size and new size of a associated container with this text element

https://user-images.githubusercontent.com/301646/188576833-7af41864-9619-4cec-9f2d-66f9f1912a1b.mov

**Comment by pavelpower** [comment]
https://github.com/excalidraw/excalidraw/pull/5667 - solving

**Comment by alex-kim-dev** [comment]
This has been fixed.

@dwelle probably worth closing this and the pr?
