### ISSUE TITLE
Latency when using a Wacom drawing tablet (CTL-4100WL)

### ISSUE THREAD

**Issue by PapaKryptic** [excalidraw/excalidraw#5668]
There is latency and what appears to be speed ramping when using a Wacom drawing tablet in Windows Ink mode.
This does not happen on the Excalidraw website (At least on Microsoft Edge), and it does not happen in the Excalidraw plugin when Windows Ink is turned off for Obsidian.

It would be quite difficult to capture a video in a way that would be meaningful (it just feels very off), but I would be happy to find a way to do so if it would be helpful.

**Comment by dwelle** [comment]
HI!

> This does not happen on the Excalidraw website (At least on Microsoft Edge), and it does not happen in the Excalidraw plugin when Windows Ink is turned off for Obsidian.

Where does it happen, Excalidraw Plus?

**Comment by PapaKryptic** [comment]
I am going to close the issue. I accidently posted this to the main repo when I meant to post it to a fork.
