### ISSUE TITLE
Crash: 'exit zen mode' button

### ISSUE THREAD

**Issue by erlingal** [excalidraw/excalidraw#5675]
Somewhat unpleasant if you accidentally hit the keyboard shorcut and can't leave :-)

helpers.ts:111 Uncaught TypeError: Cannot read properties of undefined (reading 'getElementsIncludingDeleted')
    at value (manager.tsx:126:27)
    at onClick (Actions.tsx:299:20)
    at Object.Ae (react-dom.production.min.js:54:317)
    at Be (react-dom.production.min.js:54:471)
    ...

**Comment by ad1992** [comment]
@erlingal possible to share the steps to reproduce this ?

**Comment by dwelle** [comment]
No need for repro steps, the zen mode exit button simply doesn't work :)

**Comment by ad1992** [comment]
> No need for repro steps, the zen mode exit button simply doesn't work :)

Good catch David! Thanks for fixing it 🚀
