### ISSUE TITLE
Request: Link to Internal Object

### ISSUE THREAD

**Issue by mathewdegauven** [excalidraw/excalidraw#5685]
Having an infinite canvas is great, but it's easy to get lost sometimes. If we could use the link menu to add an anchor to a shape, then we could create a link that moves the view to that shape.

This could be useful for navigating presentations, as well as navigating wide drawings.

**Comment by dwelle** [comment]
This is part of https://github.com/excalidraw/excalidraw/issues/3276 — it's been laying quite dormant but we still intend to implement this and depending on time constraints, it shouldn't take that long.

(Closing as duplicate.)
