### ISSUE TITLE
Feature: Attach Camera Photos (Mobile)

### ISSUE THREAD

**Issue by 7flash** [excalidraw/excalidraw#5689]

**Comment by dwelle** [comment]
can you elaborate? Doesn't it already work by importing an image? Is the idea that you take a photo directly into Excalidraw?

**Comment by 7flash** [comment]
Take a photo. Native-like dropdown "choose from gallery"/"open camera"

**Comment by zsviczian** [comment]
This is what I see when I click add image on my iPad. Seems to be exactly what you are looking for.

On Android the experience seems to differ depending on the browser. In some cases you can only select images from the library in others you also have the option to take a photo with the camera.

![D07C3445-9462-41CB-8AD3-9543E70BC91F](https://user-images.githubusercontent.com/14358394/190840459-c3133bca-32ce-4037-bc9d-d1f20541cce5.jpeg)

**Comment by dwelle** [comment]
Yes, on my clean Android it works like that as well.

Ultimately I don't think there's even a browser API for this, and if there was and we added our own dropdown, it'd mean that on platforms like iOS pictured above, adding an image would mean going through 2 more or less identical dropdowns.
