### ISSUE TITLE
Can't attach images on Chrome

### ISSUE THREAD

**Issue by breadream** [excalidraw/excalidraw#5730]
Hi,
I'm not able to upload/attach images (Function 9) on Chrome but it works on Safari though.

<img width="1478" alt="Screen Shot 2022-10-01 at 16 43 47" src="https://user-images.githubusercontent.com/8691841/193432121-b1a80f51-2e3f-41f0-a8fc-6ff882a327f2.png">

<img width="1334" alt="Screen Shot 2022-10-01 at 16 44 08" src="https://user-images.githubusercontent.com/8691841/193432119-1c2895d0-7fc7-4489-a0b9-21b814b95f2d.png">

**Comment by dwelle** [comment]
Hi! Can you check whether there are any messages/errors (red) in the developer console (Opt-Cmd-I, make sure you switch to the console tab)?

**Comment by breadream** [comment]
<img width="560" alt="Screen Shot 2022-10-02 at 17 03 31" src="https://user-images.githubusercontent.com/8691841/193482315-c5cffc73-c505-4560-8d90-667e52481a11.png">
Seems like I need to enable Javascript

**Comment by breadream** [comment]
<img width="556" alt="Screen Shot 2022-10-02 at 17 06 27" src="https://user-images.githubusercontent.com/8691841/193482430-b6741884-f5e4-4770-97b5-b75192277635.png">
I guess this caused the issue..?

**Comment by RedHeadphone** [comment]
maybe it's because of any of your chrome extension?

**Comment by breadream** [comment]
probably, now it's working after upgrading my chrome to the latest version [ Version 106.0.5249.91 (Official Build) (arm64)  ]
