### ISSUE TITLE
Feature Request - Toolbar Hide/Unhide

### ISSUE THREAD

**Issue by solomonshalom** [excalidraw/excalidraw#5745]
I would love if somebody could make a PR for this feature where a user can hide the toolbar or un-hide - 
![image](https://user-images.githubusercontent.com/71135230/194535743-3d8cf265-3654-4178-bde2-1e247991eba1.png)
Most preferably, if it can be made a drop-down button, would be cool, maybe here -
![image](https://user-images.githubusercontent.com/71135230/194535887-5187df48-16a6-413b-baa4-074d879097f6.png)

**Comment by alshdavid** [comment]
Agreed! I use Excalidraw with an iPad and stylus pen and this would give me a lot more room to work with.

Currently the toolbar occupies a large portion of the working area encouraging me to draw in lower right corner 

<img width="639" alt="Screen Shot 2022-10-10 at 6 16 26 pm" src="https://user-images.githubusercontent.com/12656294/194815111-80d01ef1-9d61-44dd-89b6-f099c365db19.png">

**Comment by solomonshalom** [comment]
> Agreed! I use Excalidraw with an iPad + stylus pen and this would give me a lot more room to work with.
> 
> Currently the toolbar occupies a large portion of the working area encouraging me to draw in lower right corner
> 
> <img alt="Screen Shot 2022-10-10 at 6 16 26 pm" width="639" src="https://user-images.githubusercontent.com/12656294/194815111-80d01ef1-9d61-44dd-89b6-f099c365db19.png">

Well, hope they add it as a feature!

**Comment by dwelle** [comment]
There's the zen-mode (via context menu or Alt/Opt-Z), but it's not very usable because you won't be able to customize the shape properties.

**Comment by solomonshalom** [comment]
> There's the zen-mode (via context menu or Alt/Opt-Z), but it's not very usable because you won't be able to customize the shape properties.

It's a great feature but I still want to access everything, while having the option to unhide or hide the toolbar

**Comment by dwelle** [comment]
By toolbar, do you mean (2) or (1) as well? In your original post you mention both.

![image](https://user-images.githubusercontent.com/5153846/194894135-8ebc3b74-8ef8-4cd8-827b-99ffcb917347.png)

**Comment by dhfherna** [comment]
I can work on it, Can do you assign me?

**Comment by dwelle** [comment]
@dhfherna what had you in mind? Things like this must be well thought through in terms of UI and UX. We are also very mindful of adding new features to keep our app simple.

Wwe are also in the process of tweaking the UI, so changes like these would have to wait for that effort to finish first.

But we're happy to discuss this further, and we will consider it, for sure.

**Comment by solomonshalom** [comment]
> I can work on it, Can do you assign me?

Hey, Man! I am working on another project based on excalidraw, it's called Skyflow. It's basically the clone with more features, as excalidraw was taking way too much time merging PRs. So, why don't you open up a PR regarding it and I will be merging it @ https://skyflow.vercel.app

@dhfherna :D

**Comment by solomonshalom** [comment]
> By toolbar, do you mean (2) or (1) as well? In your original post you mention both.
> 
> ![image](https://user-images.githubusercontent.com/5153846/194894135-8ebc3b74-8ef8-4cd8-827b-99ffcb917347.png)

Just One, second is needed. The idea being if I were to close it, I can re-open it back on 2

**Comment by dwelle** [comment]
This issue should be fixed by way of our new design.

**Comment by Swoodend** [comment]
> This issue should be fixed by way of our new design.

So was this ever released? I'm having the same problem a year later

**Comment by alshdavid** [comment]
> > By toolbar, do you mean (2) or (1) as well? In your original post you mention both.
> > ![image](https://user-images.githubusercontent.com/5153846/194894135-8ebc3b74-8ef8-4cd8-827b-99ffcb917347.png)
> 
> Just One, second is needed. The idea being if I were to close it, I can re-open it back on 2

This wouldn't work on a tablet as I don't have a spacebar or mouse. Only a stylus and touch controls.
In my use case, a little chevron on the side of toolbar to toggle translating it off screen would be sufficient to open up the workspace

![image](https://github.com/excalidraw/excalidraw/assets/12656294/508fbbdb-f41c-48bf-ad2e-596eb46be003)

**Comment by ramfattah** [comment]
How do we hide the top toolbar?

**Comment by alexandertam15** [comment]
Also - I need a feature to make the top toolbar/side menu toolbar text bigger. Control + should make the toolbar text size bigger as well.

I can barely see what the toolbar is saying as it's so small on my external monitor. Competitor Draw.io has this feature.

**Comment by soapergem** [comment]
Can this issue be re-opened please? It never got a resolution. I just upgraded to Excalidraw+ this week and in some ways it seems like a downgrade now that the left bar is ever present and impossible to collapse. That left bar effectively occupies 15% of the screen and is not present on the free version. I am genuinely surprised there is no way to collapse it yet...

**Comment by dwelle** [comment]
@soapergem if you mean the sidebar with the list of scenes, you can hide it using this button:

![Image](https://github.com/user-attachments/assets/1cae590a-51b0-4e5c-85af-7b02c3b1ee54)

The shape properties panel:

![Image](https://github.com/user-attachments/assets/d9b1e06d-61d2-4c99-a80d-c2dbea03d43a)

Cannot be hidden currently when shapes are selected, though you can use the zen mode (right-click on canvas -> zen mode, or `alt/opt+z`). We'll be improving zen mode at some point so you can still edit shape properties while in it.

**Comment by soapergem** [comment]
Somehow I missed that button. That is exactly what I was looking for; thank you!

**Comment by rehatiel** [comment]
Thank you for adding this!  Such a great software!
