### ISSUE TITLE
flipping freedraw elements upscales it

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#5750]
flipping freedraw elements on x/y axes upscales them. Not sure when it refressed, but it doesn't look like it's related to the version bump (https://github.com/excalidraw/excalidraw/commit/3298aaf0c710b02632442890ea53f481bfaf4f9e).

![excal-bug-flip-freedraw-upscale](https://user-images.githubusercontent.com/5153846/194779419-341e5f9f-70f6-4908-8bd4-b857c7989ebb.gif)

```
{"type":"excalidraw/clipboard","elements":[{"type":"freedraw","version":209,"versionNonce":1565822168,"isDeleted":false,"id":"2mdYBkfpEwqPZOhwnZpp-","fillStyle":"solid","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"angle":0,"x":9691.317316229484,"y":-10564.251073221569,"strokeColor":"#c92a2a","backgroundColor":"#ced4da","width":66,"height":288,"seed":1427009240,"groupIds":[],"strokeSharpness":"round","boundElements":[],"updated":1665349447014,"link":null,"locked":false,"points":[[0,0],[0,-1],[-1,-7],[-5,-15],[-11,-27],[-17,-44],[-24,-64],[-30,-86],[-36,-109],[-40,-130],[-42,-147],[-42,-161],[-42,-174],[-39,-185],[-34,-195],[-29,-200],[-23,-203],[-16,-207],[-9,-209],[-2,-211],[3,-211],[5,-212],[7,-212],[8,-212],[11,-214],[13,-216],[16,-219],[18,-224],[20,-233],[21,-247],[24,-256],[24,-266],[24,-274],[24,-282],[24,-287],[24,-288],[24,-288]],"lastCommittedPoint":null,"simulatePressure":true,"pressures":[]}],"files":{}}
```

**Comment by adarkforce** [comment]
Hi @dwelle, I wanted to start contributing to the project and I've started with this issue. I've noticed that even if the previous code passed all the tests, and the width and height values at the end of the ``` flipElement ``` function where allright,  it didn't trigger the ```mutateElement``` at line 169 correctly. The values changed but the drawing wasn't updating. 

After the flip if you tried to scale the document using the transform handle it would snap back to the right size. 

If I had to make a wild guess I would say that is somehow related with batch updates, but I don't know.
