### ISSUE TITLE
Sandbox example on integrating excalidraw as a cdn package isn't working

### ISSUE THREAD

**Issue by rahulwecp** [excalidraw/excalidraw#5763]
Was trying to integrate excalidraw in my app.
Used this [example](https://codesandbox.io/s/excalidraw-in-browser-tlqom?fontsize=14&hidenavigation=1&theme=dark&file=/src/index.js) given in the docs as reference but the the buttons fail with an error (Attached error pic for reference)
![Screenshot 2022-10-13 at 9 48 43 PM](https://user-images.githubusercontent.com/105492064/195651301-dc489f58-ab70-4d2c-9c0a-f368cd582baa.png)

**Comment by henkealg** [comment]
The current sandbox has an incorrect version dependency for react and react-dom.
This fork contains an quick fix for the issue. I hope it helps someone. 🙂 
https://codesandbox.io/s/excalidraw-in-browser-forked-8zd726

**Comment by ad1992** [comment]
Oops missed this, the demo has been fixed and updated to use React 18 🚀
