### ISSUE TITLE
[Feature Request] Add PageUp & PageDown scroll

### ISSUE THREAD

**Issue by jcezarms** [excalidraw/excalidraw#5765]
Trying to use excalidraw as a whiteboard is amazing, but also something close to the slide experience can be achieved by enabling PgUp/PgDn keys to be used for a 100% viewable screen size scroll. This is related to #253 in a barebones way.

For those still looking for an alternative in the meantime, theres https://github.com/excalideck/excalideck (I particularly don't like the layout too much, but as it's also open source, there's always the possibility of customizing. It's also a bit outdated as of now)

**Comment by DanielJGeiger** [comment]
@jcezarms I think commit f5a84f0 from #2993 should address your request here.
