### ISSUE TITLE
Elements disappear when duplicating

### ISSUE THREAD

**Issue by chenaski** [excalidraw/excalidraw#5767]
I used Cmd-D shortcut, but behavior is the same if I use 'Duplicate' from the context menu.

https://user-images.githubusercontent.com/30154503/195982281-3a7f2f2d-9b72-43d3-aea1-68a530089182.mp4

I tried to reproduce the issue, but haven't got clear results. [Here](https://app.excalidraw.com/l/3r74dmVCrO4/16tKiJoDl9B) when I remove the fourth circle – the two horizontal arrows disappear, but if I try to draw the same thing in a new scene or export and then import – everything works fine.

**Comment by artemanufrij** [comment]
I had same issue if I duplicated some objects

**Comment by dwelle** [comment]
Looks like a race condition in rendering, but cannot reproduce anywhere including the diagram you lined to. If it happens again, can you zoom in and out (`cmd-plus/minu` or using the trackpad/cmd-mousewheel)? If the arrows appear again, then it's indeed a rendering issue.

**Comment by chenaski** [comment]
I reproduced this issue several times in different scenes, but I failed to figure out the certain steps that cause it.

https://user-images.githubusercontent.com/30154503/197421207-efd3e320-3739-4f98-8057-89a56822c9b9.mov

**Comment by chenaski** [comment]
Network payload seems strange for me. Does `elements` mean an array of all the elements presented in the scene?

<img width="1792" alt="Screenshot 2022-10-24 at 01 36 20" src="https://user-images.githubusercontent.com/30154503/197421658-87f535fc-aa16-4e47-9f19-677ab7572be3.png">

I can share a link with edit permission somewhere.

**Comment by artemanufrij** [comment]
@chenaski can you upload your test file? I could test it also on my site.

**Comment by chenaski** [comment]
Yes, but after reimporting everything works fine.

[duplicate-issue.excalidraw.zip](https://github.com/excalidraw/excalidraw/files/9851120/duplicate-issue.excalidraw.zip)

**Comment by dwelle** [comment]
> Network payload seems strange for me. Does elements mean an array of all the elements presented in the scene?

Correct. We also keep deleted elements for now.

So it's a chance that those deleted elements present in your scene may come into play somehow, because exporting to a file removes them before saving.

**Comment by artemanufrij** [comment]
Thank you for the file.

Your test file works fine on my local installation. Can't reproduce it... :/

**Comment by chenaski** [comment]
To reproduce this behavior, I usually did rough actions, something like:
- I created a lot of elements (circles) and arrows between them
- Added some text and grouped it with elements
- After that, I selected and duplicated everything
- At that point I had a lot of circles grouped with text and arrows between them
- Then I tried to duplicate every circle
- Repeated it until I got the error

Generally you need to do a lot of haphazard creation, grouping, and duplication.

**Comment by dwelle** [comment]
Alright, I think I know what's happening. Will take a look at tomorrow.

**Comment by dwelle** [comment]
This fell under the radar, sorry! Will be releasing a fix tomorrow.

**Comment by chenaski** [comment]
Thanks @dwelle, I have faced this issue many times recently (really nasty 😅), very glad to know that it was fixed!

**Comment by dwelle** [comment]
Was fixed, but now it's also deployed! Let me know if you still face any issues ❤️
