### ISSUE TITLE
Request to add new language: Kurdish (ckb_IQ)

### ISSUE THREAD

**Issue by kurdi-dev** [excalidraw/excalidraw#5772]
Hi,

I would like to help and add the Kurdish language (Central Kurdish) to this fantastic project.
Could you please add it to Crowdin?

**Comment by ad1992** [comment]
Here you go @kurdi-dev  https://crowdin.com/translate/excalidraw/10/en-ku

**Comment by kurdi-dev** [comment]
Thank you @ad1992  , I have added the translations.

**Comment by ad1992** [comment]
Thanks, @kurdi-dev!,  closing this
