### ISSUE TITLE
Cannot save as image/export

### ISSUE THREAD

**Issue by petarkolaric** [excalidraw/excalidraw#5773]
Hi, when I try and save to PNG/SVG, I get the following error. I also get the same when I try and export.

This is using Excalidraw+, but I can confirm I'm also getting it in regular Excalidraw.

```
Google Chrome | 106.0.5249.119 (Official Build) (arm64)
OS | macOS Version 12.6 (Build 21G115)
```

![image](https://user-images.githubusercontent.com/16151065/196082821-58bd95cb-ec4f-427b-8bc2-d5f418a8bece.png)
![image](https://user-images.githubusercontent.com/16151065/196082871-4ecbf933-207a-4598-b7ae-dbd4392e92f2.png)

Any help would be appreciated, thanks!

**Comment by ad1992** [comment]
This looks like related to granting permission for the file so we will need to request permission in case the user hasn't given it. Will look into this

**Comment by dwelle** [comment]
@petarkolaric can you check if you don't have file editing permissions disabled?

1. go to `chrome://settings/content`
2. expand `additional permissions`
3. click on `file editing`

  ![image](https://user-images.githubusercontent.com/5153846/199456493-f9e3bebd-b6ea-48a3-9e61-fec5671f5f81.png)

4. should be:

  ![image](https://user-images.githubusercontent.com/5153846/199456530-b4ec20ee-b966-4131-b46d-2e07b90fd2b8.png)

**Comment by petarkolaric** [comment]
Hi @dwelle , I've just checked, and yes - it appears that file editing has been disabled. I am using a machine provided to me by my company and believe this setting is controlled by a corporate policy.

**Comment by dwelle** [comment]
Thanks for confirming! I've created an issue to display a message when such error occurs, so that people have a better idea of what might be going on. https://github.com/excalidraw/excalidraw/issues/5951
