### ISSUE TITLE
Using border on last item created

### ISSUE THREAD

**Issue by darklight9811** [excalidraw/excalidraw#5776]
When I use a box, circle or arrow. If I draw something(`x` or `7`), if I change the width using this tool, it affects the last element created too.

**Comment by dwelle** [comment]
You're talking about when the tools are locked, right? Yes, this seems to be a recent regression.

**Comment by darklight9811** [comment]
@dwelle non lock state

**Comment by dwelle** [comment]
Oh, you're right, I missed you also mentioned box/circle which the bug I was fixing doesn't affect. But, can't repro what you mean then!

**Comment by darklight9811** [comment]
@dwelle the bug was actually fixed, don't know if it was you, but thank you for the attention
