### ISSUE TITLE
[Feat] Make the opacity tool more aesthetic

### ISSUE THREAD

**Issue by solomonshalom** [excalidraw/excalidraw#5777]
Yo!

This is not an urgent issue, but - 
![image](https://user-images.githubusercontent.com/71135230/196633923-dd0a1dab-549a-4eb3-adff-a381b22fe79d.png)
Does this really look aesthetic :,)

Let's make it better :D

**Comment by artemanufrij** [comment]
It looks fine, imo:
![Screenshot_20221019_110514](https://user-images.githubusercontent.com/16517095/196647457-25c199c2-d92c-4c8e-9e95-c6406a7a549e.png)

**Comment by dwelle** [comment]
Hello @solomonshalom, what's your OS and Browser? That looks strange indeed.

**Comment by solomonshalom** [comment]
OH, I am using Opera GX with Windows OS @dwelle

**Comment by dwelle** [comment]
I see. Yeah, at some point we may make the opacity slider to use a custom component, but for now we'll stay with native.
