### ISSUE TITLE
Pasting multi-line as individual text elements

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#5783]
I'm often in a situation where I want to paste many lines that I would like to treat as individual text element but right now it pastes them as one text element.

Use cases:
* When doing re-orgs, I want to paste a bunch of names collected from somewhere else.
* I'm doing a minecraft challenge to try to get every single item of the game. I want to paste all the remaining items and group them to figure out what are the things I have remaining to do.

Proposal:
* If you paste multiline elements without having anything selected, it creates one text element per line. [New Behavior]
* If you double click to create a text element and paste, it pastes it as a single text element. [Already existing behavior]

**Comment by dwelle** [comment]
> If you paste multiline elements without having anything selected, it creates one text element per line. [New Behavior]

I think we should be a bit more conservative here and ask the user what they want to do (using a dialog similar to when pasting a chart).

**Comment by vjeux** [comment]
We could add the instruction to paste in a single element in the toast message. It’s pretty annoying to have to click on a dialog to paste text imo.

**Comment by dwelle** [comment]
Agreed. So let's try it out without the dialog. And perhaps the toast.

**Comment by dwelle** [comment]
We might also add `Cmd/Ctrl-Shift-V` to force paste as plaintext, which will also prevent pasting as chart and other things in the future.

**Comment by adarkforce** [comment]
May I work on it? 
If I understand well the behaviour should be: 

- If clipboard has a text with multple lines, inform the user with a toast that the text can be copied as single splitted lines
- ```CmdOrCltr+Shift+V``` the element is copied splitted.

Should the behaviour be also implemented for copy/paste of text element:

- Clipboard has a text element
- After the user copied a text element a toast should inform the user that there's the possibility to ```CmdOrCltr+Shift+V``` to paste the splitted text element
- ```CmdOrCltr+Shift+V``` the element is copied splitted.

**Comment by dwelle** [comment]
@adarkforce sure thing!

> If I understand well the behaviour should be:
> 
> * If clipboard has a text with multple lines, inform the user with a toast that the text can be copied as single splitted lines
> * `CmdOrCltr+Shift+V` the element is copied splitted.

Not quite. We'd split into multiple elements automatically. The toast would only say that to not split into multiple lines, you an either paste into an existing text element (editor), or use `Cmd-Shift-V`.

Refer to the below diagram:

![image](https://user-images.githubusercontent.com/5153846/197390045-7e047f8b-26d1-4f41-9fb9-c3cce29c3f75.png)

> Should the behaviour be also implemented for copy/paste of text element:

No. When coping text elements, it copies a JSON to the clipboard, not text. The JSON will be interpreted as non-plaintext and handled in (3.1)

**Comment by vjeux** [comment]
Thanks for working on it @adarkforce! Can’t wait to be able to use it <3

**Comment by adarkforce** [comment]
Ok @dwelle @vjeux  I've managed to implement the feature #5786 :D, but... when copy/pasting from the clipboard without intercepting the document "paste" event, you need to allow permission to access the clipboard. 

Here's a little preview of the feature, also any coding advices are welcome. 

https://user-images.githubusercontent.com/50418432/197401924-d432afb7-52e9-462b-a541-86b8ebeec9c0.mov

Also do we need to display the option in the context menu for mobile users?

**Comment by dwelle** [comment]
I've pushed some tweaks and removed the async clipboard API as it's not needed, see comment https://github.com/excalidraw/excalidraw/pull/5786#issuecomment-1288209760.

What we should decide is how much to space out the text elements, and whether to center them:

![image](https://user-images.githubusercontent.com/5153846/197420151-e643338f-3bfb-4009-92d4-bb80ff71ce4a.png)

(1) is single text, (2) is current PR's multi-element text, which visually aligns with (1). I'd also consider (3) for easier manipulation, and (4) based on what we think will be the use case.

Why (3): because the elements are so close together that the bounding boxes overlap:

![image](https://user-images.githubusercontent.com/5153846/197420211-f7174c95-900c-45d5-8ef0-48c59e936a8f.png)

**Comment by adarkforce** [comment]
Playing a little with the feature I haven't experienced any issues selecting the single elements. 

But now that you made me think about it I don't think this would be ideal for mobile devices or when the text is very small.

I think that spacing them would be better for accessibility. 

The text centering emphasizes the separation so I think that is more beautiful, but it also depends on the use case. 

I would vote for 4.

**Comment by vjeux** [comment]
For centering, we should use the currently selected setting for text alignment.

**Comment by dwelle** [comment]
> For centering, we should use the currently selected setting for text alignment.

Interesting idea. I worry that it's not obvious enough and people will wonder why pasting works differently at different times.

Now that I think about it, it's not that hard to align the elements after the fact, no matter the default.

**Comment by adarkforce** [comment]
Now the default alignment for text pasting is that of the settings, it doesn't seem counter intuitive to me. 

Talking about the toast, what about showing the message only once per session (meaning  ```sessionStorage``` session or App lifetime)?

**Comment by dwelle** [comment]
> Now the default alignment for text pasting is that of the settings, it doesn't seem counter intuitive to me.

Trouble is, there's no relation between text alignment and element alignment — hence the (un)intuitiveness.

> Talking about the toast, what about showing the message only once per session (meaning sessionStorage session or App lifetime)?

Good idea!

**Comment by dumblob** [comment]
Shouldn't this whole functionality be rather "split existing text box" (triggered by a button from a menu or the bottom bar) than "paste and immediately split by default"?

To me I expect a pasted text to be somewhat "together" by default (grouping?) and ideally roughly resemble the layout how it looked like when selected at the source (i.e. not just alignment but also e.g. floating around some picture on the web etc.).

**Comment by dwelle** [comment]
Now implemented (https://github.com/excalidraw/excalidraw/pull/5786).

@dumblob we'll see what people will say and if it becomes too surprising/annoying.
