### ISSUE TITLE
Screen goes black when drawing

### ISSUE THREAD

**Issue by lochie154** [excalidraw/excalidraw#5797]
Set up excalidraw in obsidian on my iPad Air (2020) yesterday. It now is going black every time I draw anything on the diagrams and the screen returns to normal once I drag to the left or right.

Video attached below.

https://user-images.githubusercontent.com/48538087/198558189-26c035a5-dcd9-46d9-91ad-d9b3a6765529.MP4

**Comment by ad1992** [comment]
cc @zsviczian

**Comment by ad1992** [comment]
Closing this, @lochie154  please open this issue in https://github.com/zsviczian/obsidian-excalidraw-plugin as it's related to Obsidian.
