### ISSUE TITLE
Editor redesign package issues

### ISSUE THREAD

**Issue by zsviczian** [excalidraw/excalidraw#5814]
I merged the released redesign into the Obsidian fork and still doing the initial testing and issue resolution. So some of these might be consequences of customizations in my fork, but on the surface, these issues seem like they are inherent to the new package:

- renderTopRightUI in mobile view should be part of the mobile-misc-tools-container in my view

https://github.com/excalidraw/excalidraw/blob/7f91cdc0c981ff83b1c4eb9e17e293e0fcd131fa/src/components/MobileMenu.tsx#L114-L116

- even though I am passing the following props
  - export options visible in menu 
  - save to visible in menu
  - open file and Live collaboration are shown in the welcome menu
```typescript
          UIOptions: {
            canvasActions: {
              loadScene: false,
              saveScene: false,
              saveAsScene: false,
              export: { saveFileToDisk: false },
              saveAsImage: false,
              saveToActiveFile: false,
            },
          },
```

![image](https://user-images.githubusercontent.com/14358394/199334177-d6b1827a-f24a-48dd-bcd0-8c044ce226cc.png)

![image](https://user-images.githubusercontent.com/14358394/199334300-bb166085-eff6-490d-9315-ebfbdb52b8bc.png)

- can I customize the welcome text via props? I'd like to replace the Excalidraw plus link as well... (of course I can do that in my fork, but would be better via props)
- can I change links in menu via props (twitter, discord, etc.)?

- language picker is visible in menu (it was not available to packages in previous builds), however selecting a language has no effect

- Should also hide the "save to" button in library.

**Comment by dwelle** [comment]
The redesign has some package regressions such as the language picker as you said, and missing customization options. Which is why we haven't even released a `@next` npm version yet. We'll be fixing that over the coming days/weeks (for a stable release we'll want to introduce a rewritten package API).

We can use this issue to discuss what needs to be customizable / hideable.

**Comment by zsviczian** [comment]
Shall I start a PR to work on these changes?

**Comment by zsviczian** [comment]
@dwelle, 

1) I propose two new package props:
- `renderWelcomeScreen: () => JSX | null;`
- `renderMenuLinks: () => JSX | null;`
If provided they override the default display. Do you agree?

2) what is your view regarding the language dropdown? I would vote for including translations in the package and keep the translations dropdown in the package. Maybe we could add to `UIOptions`: 
```typescript
UIOptions ?: {
  dockedSidebarBreakpoint?: number;
  canvasActions: CanvasActions;
  showLanguageList: boolean;
} ;

**Comment by dwelle** [comment]
> 1. I propose two new package props:

Instead of new props, we plan to introduce a component API similar to `<Sidebar>`. More details soon.

> 2\. what is your view regarding the language dropdown? I would vote for including translations in the package and keep the translations dropdown in the package. Maybe we could add to `UIOptions`:

The translations are technically kept in the package (available via `props.languge`), it's just the language picker that is not. We will expose that as a component as well.

**Comment by dwelle** [comment]
I assume this can now be closed.
