### ISSUE TITLE
Reset Scene Shortcut

### ISSUE THREAD

**Issue by Fausto95** [excalidraw/excalidraw#5818]
Before the redesign, we always had the button for deleting the whole scene accessible with one 1 click. 

Now that we currently need 2 clicks in order to reach the Reset Scene button, it may be interesting to add a shortcut to do so.
I personally attempted to do it but it's not implemented

I would prefer `Shift+Del`.
I've got a commit ready, will open a PR soon.

**Comment by PrathameshAshra** [comment]
I would like to work on this. 
If we press `Clt+ A and Del` it would result the same, so i think we do have a shortcut to reset the screen

**Comment by ashutosh887** [comment]
@Fausto95  I would like to work on this Issue

**Comment by Fausto95** [comment]
@ashutosh887 you can go for it.

**Comment by ashutosh887** [comment]
Sure Thanks. 
Is there any channel to discuss and communicate while facing issues? @Fausto95

**Comment by ashutosh887** [comment]
Please tell @Fausto95

**Comment by ashutosh887** [comment]
Sure Joining @Fausto95
