### ISSUE TITLE
BUG: sticky note grows EXTRA large when pasting a longer paragraph of text

### ISSUE THREAD

**Issue by zsviczian** [excalidraw/excalidraw#5834]
https://user-images.githubusercontent.com/14358394/200132626-10538a7e-c736-410e-8a60-4015a430a758.mp4

**Comment by DanielJGeiger** [comment]
I can confirm this bug on excalidraw.com.  I believe #5834 is independent of #5789.

**Comment by DanielJGeiger** [comment]
From some testing I did on this bug, I think `text` and/or `originalText` in `updatedTextElement` are empty, causing repeated executions of `updateWysiwygStyle()`.

**Comment by DanielJGeiger** [comment]
The empty `text`/`originalText` sets `maxWidth` nearly to `0`.  This causes text wrapping to calculate a height based on single-character widths once `text`/`originalText` are no longer empty.  But I'm not sure why they are initially empty or when they become non-empty.

**Comment by ad1992** [comment]
@zsviczian @DanielJGeiger I have pushed a fix for this, could you test it in https://excalidraw-git-aakansha-fix-paste-bound-text-excalidraw.vercel.app/ ?

**Comment by zsviczian** [comment]
Thanks. Seems to be fixed!
