### ISSUE TITLE
The scaling looks buggy when bound containers resized with maintaining aspect ratio

### ISSUE THREAD

**Issue by ad1992** [excalidraw/excalidraw#5842]
https://user-images.githubusercontent.com/11256141/200243510-dd2d2466-57e7-4a60-b624-a5855d4f97fc.mp4

This happens in single element too when resizing with shift pressed

Solution - We should maintain the same padding of text inside bound containers when scaled

**Comment by dwelle** [comment]
it's a regression introduced in https://github.com/excalidraw/excalidraw/pull/5710

**Comment by ad1992** [comment]
> it's a regression introduced in #5710

will look into this

**Comment by ad1992** [comment]
Doesn't look like a regression due to above PR - I am still able to reproduce in the PR mentioned above

try here https://excalidraw-hbj9n0rca-excalidraw.vercel.app/#json=HuEv-OlZGOBzouXi_Kiu1,bUB2R9T2clYmr1BiamPsDg

**Comment by ad1992** [comment]
ok my bad, its not a regression due to the above PR, this issue is also reproducible before this commit, check here - https://excalidraw-em1u6qf0e-excalidraw.vercel.app/#json=e7886v-Lvp1o6p8L6m06W,4ZMXy0bBBN9bsNaKMhkWjA
