### ISSUE TITLE
Site not responding while exporting the diagram as image

### ISSUE THREAD

**Issue by codingmickey** [excalidraw/excalidraw#5846]
After waiting for a few minutes this pops up... After another few minutes, the site opens the window for exporting as an image. Then clicking as `download as png` again and wait for another few minutes to be ready to download.

Is this issue only with me? I'm using brave and turned off the shields on the site

![image](https://user-images.githubusercontent.com/42518907/200577811-1eab72c3-01b4-4e71-b9df-ed4f2fdeced2.png)

**Comment by ad1992** [comment]
@codingmickey does it happen only on brave? Is it possible to share the drawing if not confidential?

**Comment by codingmickey** [comment]
Only on brave as I tried on chrome and firefox it was laggy but not as slow and unresponsive as Brave.
I cannot share this file sorry about that, maybe this would be because of the large flow diagram?
![image](https://user-images.githubusercontent.com/42518907/200842467-215cf146-ecc1-4770-bdae-90ae1d44ac53.png)
does this qualify as large? idk

**Comment by iosense** [comment]
Hi, this issue continue, could you check ?

I have the same problem. I'm trying yo export as png file, change background to dark mode the browser enter in waiting mode.

**Comment by ad1992** [comment]
Hi @iosense which browser and OS are you using ? Whats the error message you are getting ?

I just tried exporting a [large scene](https://excalidraw.com/#json=zuS1eZ_K4rEcWUM8_OD_9,WkR3LcSjkfSp02Dr-NsLXA) ~4M and it works fine for me.

**Comment by iosense** [comment]
Hi, dwelle.

Elements: 528
Width: 6900
Height: 3707

the problem gets even worse when there are people accessing the shared link.

**Comment by iosense** [comment]
> Hi @iosense which browser and OS are you using ? Whats the error message you are getting ?
> 
> I just tried exporting a [large scene](https://excalidraw.com/#json=zuS1eZ_K4rEcWUM8_OD_9,WkR3LcSjkfSp02Dr-NsLXA) ~4M and it works fine for me.

I'm using Chrome on MacOS Ventura 13 (M1). I'm trying use Firefox and Safari and same problem occurs.

**Comment by iosense** [comment]
<img width="802" alt="Screenshot 2023-03-01 at 02 35 37" src="https://user-images.githubusercontent.com/60938646/222054093-c621f391-70b2-4cec-b2b7-19232fd924c7.png">

**Comment by Yash-Singh1** [comment]
I'm facing this same problem on Google Chrome.

**Comment by dwelle** [comment]
@iosense what I missed in your replies above is you also export on 3x scale.

So the resulting canvas is `(6900*3)x(3707*3)` big, 230,204,700 pixels. It still renders even on my M1, but trying to switch to dark mode indeed waits indefinitely, likely due to memory.

I'd suggest rendering on 1x scale on such large canvases, though even on 1x the dark mode doesn't work on M1. We'll need to move away from using canvas filters for dark mode. There's not much optimization we can do here beyond that. Potentially render to smaller canvases and stitch them together.

**Comment by codingmickey** [comment]
> @codingmickey I'm a bit surprised you are seeing these issues on a 2157x1548px scene though, that's relatively tiny. What machine are you running this on?

```
Device name	codingmickeys
Processor	11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz   1.38 GHz
Installed RAM	8.00 GB (7.73 GB usable)
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display
```

I just got this pop-up when I was exporting the image in the dark theme... otherwise, it was speedy in the normal white theme

**Comment by codingmickey** [comment]
After the new export component, this isn't happening anymore for me so closing this one!
Great work on the speed it's drastically faster while exporting to dark mode now!! 🚀
