### ISSUE TITLE
Panel is not visible

### ISSUE THREAD

**Issue by kuros** [excalidraw/excalidraw#5850]
Steps to reproduce:
1. install minimal theme
2. Install Minimal Theme Settings plugin
3. Choose the dark mode schema as Dracula
4. Setting --> Appearance --> Base color scheme = "Dark"
<img width="1147" alt="Screenshot 2022-11-09 at 9 52 43 AM" src="https://user-images.githubusercontent.com/11554554/200738510-12718c67-d61f-4cc4-b0ca-22d48c307b49.png">

**Comment by ad1992** [comment]
@kuros is this Obsidian?

**Comment by kuros** [comment]
Yes

**Comment by ad1992** [comment]
cc @zsviczian
