### ISSUE TITLE
Pasting in a text field replaces whole text

### ISSUE THREAD

**Issue by sojusnik** [excalidraw/excalidraw#5855]
After a recent update, the text field started to act weirdly. When you paste something into a text field, then the content of this text field is deleted, showing only the newly pasted content. Because of this, you can't add text to existent text within a text field, which is significant regression.

**Comment by DanielJGeiger** [comment]
I believe this is a regression from #5845.  Another #5845 regression I found: the wrapped line breaks get set in `originalText` as well as `text`.
