### ISSUE TITLE
Double rendering of text

### ISSUE THREAD

**Issue by taufiq-dev** [excalidraw/excalidraw#5857]
![20221110_125741.jpg](https://user-images.githubusercontent.com/20721306/201004592-891bc5a1-c1b8-4d45-848d-93db9ff9d456.jpg)

I'm on my work laptop and can't send screenshots outside.

Here I'm facing double rendering of text.
One in its fallback font and one in the rendered font.

OS: MacOS Monterey (12.6.1)
Browser: Chrome (107.0.5304.87) x86_64

**Comment by ad1992** [comment]
Hey are you seeing this in [excalidraw.com](https://excalidraw.com) ? Can you share read-only link with some dummy text ?

**Comment by ad1992** [comment]
closing this as we need more information. Feel free to reopen if it persists
