### ISSUE TITLE
Choose the container selected by user when multiple container intersecting

### ISSUE THREAD

**Issue by ad1992** [excalidraw/excalidraw#5860]
https://user-images.githubusercontent.com/11256141/201027960-c5062a8f-c52e-4d66-a44a-8101b733052f.mp4

Right now we try to compute which container to choose based on the pointer coords and choose the one with the highest z-index. This often leads to choosing the wrong container especially when containers are intersecting. 
Instead, we should always give preference to the container which the user actually selects and that's more intuitive as well.
Miro, whimsical, eraser works the similar way as well irrespective of containers are transparent or not.

**Comment by maielo** [comment]
Yep i agree it should always choose "selected" element.  Current behavior feels buggy.
