### ISSUE TITLE
Feature request: Export image with no background on Obsidian

### ISSUE THREAD

**Issue by gustavindnq** [excalidraw/excalidraw#5864]
Can the option to check or uncheck background be implemented on Obsidian also? 
![image](https://user-images.githubusercontent.com/117943225/201190066-6f395e06-a111-409e-8189-d17952c7c1e1.png)

**Comment by zsviczian** [comment]
@gustavindnq, this feature is there, but in a slightly different way.
- You can set a default for this in plugin settings
- You can override that setting by adding the following frontmatter keys to your drawing in markdown view mode. For more please consult the [Readme](https://github.com/zsviczian/obsidian-excalidraw-plugin/blob/master/README.md).
  - Frontmatter tags to customize image export at a file level [519](https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/519). If these keys are present they will override the default excalidraw embed and export settings.
    - `excalidraw-export-transparent: true`:  true == Transparent / false == with background. 
    - `excalidraw-export-dark`: true == Dark mode / false == light mode.
    - `excalidraw-export-padding`: Specify the export padding for the image
    - `excalidraw-export-pngscale`: This only affects export to PNG. Specify the export scale for the image. The typical range is between 0.5 and 5, but you can experiment with other values as well.

![image](https://user-images.githubusercontent.com/14358394/202917790-91c066b1-271c-495a-bc17-a0bb4afa95d4.png)

**Comment by gustavindnq** [comment]
I understand, thanks brother
