### ISSUE TITLE
BUG: Text is cut at the end of it's box

### ISSUE THREAD

**Issue by maielo** [excalidraw/excalidraw#5866]
Hey,

Text is not shown correctly:

![image](https://user-images.githubusercontent.com/8983870/201393130-655be61a-1fdf-4b16-acb0-28161184e168.png)

tried to copy the element into new scene - there it works
link: https://app.excalidraw.com/l/6rfy1007QOo/98iVvhWxVso

**Comment by ad1992** [comment]
@maielo I can see the emoji is being cut, do you have the original scene where this is reproducible?
This happens when you try to export the drawing ?

**Comment by dwelle** [comment]
I'm pretty sure it's related to https://github.com/excalidraw/excalidraw/pull/5432 and a race condition in font loading.

**Comment by maielo** [comment]
We already found the reason.

How to reproduce:
1. set throttling in network tab
2. disable cache 
3. reload page 

Reason: 
There is some resizing thing going on. 
The virgil font is loaded later but the text resize is done with default font so it has different width.
