### ISSUE TITLE
pasting text sometimes doesn't work

### ISSUE THREAD

**Issue by ptrkcsk** [excalidraw/excalidraw#5867]
to reproduce:

1. enter text mode (<kbd>8</kbd>)
2. click on canvas
3. paste

pasting `abc` works, pasting `123` doesn't work

**Comment by DanielJGeiger** [comment]
I can confirm this on excalidraw.com.  My hunch is this is another regression from #5845.

**Comment by DanielJGeiger** [comment]
@ptrkcsk This should be fixed by #5868.

@ad1992

**Comment by 7flash** [comment]
It happens when I am trying to paste raw text that looks like JSON, then canvas is trying to interpret clipboard content as serialized elements

**Comment by ad1992** [comment]
@7flash it should be fixed in https://excalidraw-q4ew6s3nw-excalidraw.vercel.app/, can you try ?

**Comment by ad1992** [comment]
This should be fixed now. Incase the issue still persists, feel free to reopen this  / create a new issue
