### ISSUE TITLE
images won't load when file is moved

### ISSUE THREAD

**Issue by phospher1** [excalidraw/excalidraw#5875]
Hi Zsolt
 As discussed on Youtube the problem with two files I have moved is that the image doesn't load when moved. I have tried to repeat this with a test file but don't seem to be able to get the same result. However it has happened twice before. Please find the two files
[Negative Emotion Diagram.md](https://github.com/excalidraw/excalidraw/files/10001418/Negative.Emotion.Diagram.md)
[Essence working unfinished diagram.md](https://github.com/excalidraw/excalidraw/files/10001426/Essence.working.unfinished.diagram.md)

Many thanks Simon

**Comment by dwelle** [comment]
Hi. This seems to relate to the Obsidian plugin — issues tracked here: https://github.com/zsviczian/obsidian-excalidraw-plugin/issues

**Comment by phospher1** [comment]
Hi Thanks  Are you able to point to which particular # you think refers to my problem please?
