### ISSUE TITLE
BUG: Sticky Notes container height

### ISSUE THREAD

**Issue by 7flash** [excalidraw/excalidraw#5879]
![eleven15](https://user-images.githubusercontent.com/4569866/201824364-4969625b-64aa-4bbe-824a-b32b0138a185.gif)

Unexpected resizing makes container bigger than it should be to fit text

**Comment by 7flash** [comment]
It happens when Copy-Paste a single string from clipboard (doesn't happen when typing manually)

**Comment by ad1992** [comment]
This is what I fixed a couple of days back. I am not able to reproduce this. Is this happening on the latest https://excalidraw.com/ ? Can you check what is the commit sha ? 
To find the commit sha, you can open the context menu and click on "Stats for Nerds"
<img width="392" alt="Screenshot 2022-11-15 at 10 28 29 AM" src="https://user-images.githubusercontent.com/11256141/201830167-3ec27823-896b-45c9-9bda-94c5b49076a1.png">

**Comment by ad1992** [comment]
@7flash Is this happening on the latest https://excalidraw.com/ ? If yes. can you share the version, browser and OS ?

**Comment by 7flash** [comment]
Thank you @ad1992 it's resolved in a new release, but another issue I noticed https://github.com/excalidraw/excalidraw/issues/5916
