### ISSUE TITLE
Sidebar is not working as expected.

### ISSUE THREAD

**Issue by kobe651jp** [excalidraw/excalidraw#5881]
I'm trying to implement the original sidebar. I browsed to src/excalidraw-app/index.jsx but the sidebar doesn't show up.

Details are in the image below.

Is the Sidebar working? Or am I missing something?

![image](https://user-images.githubusercontent.com/44263972/201853235-72a16df0-b0b2-44a8-aae6-30f7542b4a06.png)

**Comment by ad1992** [comment]
Hey do you mean Sidebar is not working for you in https://excalidraw.com/ ?

**Comment by kobe651jp** [comment]
In my application. 

I'm trying to add my own original component to the original Sidebar and add another function, but isn't this kind of use expected?

```
import {
  Sidebar,
  Excalidraw,
  useHandleLibrary,
  MIME_TYPES,
  sceneCoordsToViewportCoords,
  viewportCoordsToSceneCoords,
  restoreAppState,
  restoreElements,
} from '@excalidraw/excalidraw';
```

**Comment by dwelle** [comment]
The custom sidebar is closed by default. You should either open it on a user action, using the api [toggleMenu()](https://github.com/excalidraw/excalidraw/blob/master/src/packages/excalidraw/README.md#toggleMenu) API: 

```
<button onClick={() => excalidrawAPI?.toggleMenu("customSidebar")}>
  Toggle Custom Sidebar
</button>
```

Check the example app: https://github.com/excalidraw/excalidraw/blob/master/src/packages/excalidraw/example/App.tsx#L684

Or, if you want to have the sidebar open from the start, set `initialData.appState.openSidebar` to `"customSidebar"`.
