### ISSUE TITLE
scrolling doesn't trigger an element resize while creating/resizing an element

### ISSUE THREAD

**Issue by lissitz** [excalidraw/excalidraw#589]
While holding down the mouse button only moving the mouse updates the current element.

![chrome-capture](https://user-images.githubusercontent.com/53315888/73192982-2e555e80-412a-11ea-93d3-4e3e80518bb1.gif)

**Comment by dwelle** [comment]
As I understand you, scrolling (e.g. via mousewheel) while you're still creating an element should update element width/height immediately after scroll, not after you move the mouse again.

**Comment by lissitz** [comment]
Yeah. If #541 is implemented without needing to move the mouse for the scroll to keep going  it will be a bit more noticeable, as one would expect that keeping the mouse still close to the border would resize the element.

**Comment by lipis** [comment]
> As I understand you, scrolling (e.g. via mousewheel) while you're still creating an element should update element width/height immediately after scroll, not after you move the mouse again.

I actually expected that as a result.. I scroll and then adjust the width/height :)

Either case it's an edge case.. let's close this.
