### ISSUE TITLE
pasting non-normalized color into picker doesn't work 

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#590]
When I paste uppercase HEX color, it's normalized to lowercase, but the color isn't set correctly. Moreover, manually editing the color from then on doesn't work either. I then need to paste the normalized form, or pick via color picker.

![excalidraw_picker_paste_bug](https://user-images.githubusercontent.com/5153846/73195770-bc334880-412e-11ea-9e12-dd087050938f.gif)

**Comment by vjeux** [comment]
Probably because this is lowercased in CSS lol

**Comment by dwelle** [comment]
Oh :)
