### ISSUE TITLE
Feature request "Fit to content"

### ISSUE THREAD

**Issue by behnammodi** [excalidraw/excalidraw#5906]
Hi folks,

![Screenshot 2022-11-20 at 14 27 51](https://user-images.githubusercontent.com/1549069/202904886-d30f8c24-3b51-4acc-85df-0814a086c28d.png)

I think we need an additional button here that responsibility is to adjust the zoom level and position to fit all content like `Zoom to fit` in Figma

**Comment by prancoding** [comment]
It already has that functionality. You can press `shift + 1`. This should zoom to fit.

Is this what you are looking for?

**Comment by behnammodi** [comment]
@prancoding Yes, thanks a lot 🙏🏻 so I will close this issue
