### ISSUE TITLE
Unsatisfactory results after paragraph text split

### ISSUE THREAD

**Issue by zhl111** [excalidraw/excalidraw#5917]
Can it be optimized to a suitable state? One line is still one line, otherwise the workload will be heavy
![image](https://user-images.githubusercontent.com/29135984/203348111-56f8df42-602e-474e-bd58-00c0f686f9d6.png)

**Comment by dwelle** [comment]
I assume this is Obsidian related. You can open an issue on their tracker here: https://github.com/zsviczian/obsidian-excalidraw-plugin/issues
