### ISSUE TITLE
bug：choice drift

### ISSUE THREAD

**Issue by zhl111** [excalidraw/excalidraw#5919]
Problems occurred during operation, more than once. My operation is very simple: select text, rotate, move text. There are no other operations. . . I can only solve this problem by turning off obsidian and turning it on again.

https://user-images.githubusercontent.com/29135984/203461546-a78b1713-a263-447c-afcd-4586e5f12dff.mp4

**Comment by dwelle** [comment]
Closing as related to Obsidian. If can reproduce on excalidraw.com, please post steps or shareable link / source for the elements on which we can reproduce.

Otherwise, you can open an issue on https://github.com/zsviczian/obsidian-excalidraw-plugin/issues

/cc @zsviczian
