### ISSUE TITLE
right click not working

### ISSUE THREAD

**Issue by eho9734** [excalidraw/excalidraw#5924]
right click not working on a draw.

**Comment by artemanufrij** [comment]
It works fine to me...

![image](https://user-images.githubusercontent.com/16517095/203731062-4a8e4b17-879d-4d67-880d-05089338e0da.png)

**Comment by eho9734** [comment]
Nothing for me

[image: image.png]

this is a link / you can edit
https://app.excalidraw.com/l/7XeFraXAAdh/8VmjQumJDIm



Le jeu. 24 nov. 2022 à 12:27, Artem Anufrij ***@***.***> a
écrit :

**Comment by dwelle** [comment]
@eho9734 fixed, refresh your tabs! :)
