### ISSUE TITLE
Duplicate multiple elements deteles element

### ISSUE THREAD

**Issue by danielbeutner** [excalidraw/excalidraw#5925]
Hi there,

If I select multiple elements and duplicate them with `Command+d`on element is deleted.

Workaround: As a grouped element it is possible to duplicate without loss.

https://user-images.githubusercontent.com/531853/203758033-8f89b556-e349-44c0-8b6e-42dfdf28e068.mov

If you need more info on that I am glad to help.

**Comment by dwelle** [comment]
I think there's a PR that should be fixing this. Can you check on https://excalidraw-d2na757vo-excalidraw.vercel.app ?

**Comment by danielbeutner** [comment]
The current issue is solved but I found another issue if I drag and duplicate:

https://user-images.githubusercontent.com/531853/203788525-5cef911a-6535-4e75-8d81-7b324a42b06f.mov

**Comment by dwelle** [comment]
> The current issue is solved but I found another issue if I drag and duplicate:

What am I looking at exactly? Can you describe the steps you're doing and what is the expected behavior? And does that happen on excalidraw.com, or specifically in that link I posted?

**Comment by danielbeutner** [comment]
Thanks for your question.

It happend in that link you posted. 

Steps to reproduce:
- Select all elements
- Duplicate via Cmd+d
- Drag duplicate a bit down
- Duplicate the duplicate via Cmd+d

Current behaviour:
- One element (background Ticket for feature one) disappears

Expected behaviour:
- Original element does not change

**Comment by zepster** [comment]
@danielbeutner could u provide your or any broken canvas state? Can not reproduce with random created elements.

**Comment by danielbeutner** [comment]
Hi @zepster ... I tried this again it seems to be solved now. I tested it again on a different machine and it was not reproducable.

Sorry for the trouble. I guess it was a local problem.
