### ISSUE TITLE
rewrite contextMenu to use appState

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#5926]
In https://github.com/excalidraw/excalidraw/pull/5893 we've moved from `React.render` (v17) to `createRoot` (v18), but that broke the editor for apps that use react v17 (which we still list as compatible).

For now, we shouldn't be breaking React 17 apps, so let's instead rewrite the contextMenu to use `appState` and render as part of the normal render lifecycle.

What we need to do:

- instead of calling [`ContextMenu.push()`](https://github.com/excalidraw/excalidraw/blob/1f117995d90a1bb6c452791eff62c3efad66ee61/src/components/ContextMenu.tsx#L115-L144) (see https://github.com/excalidraw/excalidraw/blob/1f117995d90a1bb6c452791eff62c3efad66ee61/src/components/App.tsx#L5993-L6001), set `this.setState({ contextMenu: { options, top, left } })`. So, we'll need to:
- Add an appropriate type to [`AppState`](https://github.com/excalidraw/excalidraw/blob/1f117995d90a1bb6c452791eff62c3efad66ee61/src/types.ts#L93). Only the `options`, `top`, `left` needs to be defined. The other props the `.push()` method currently takes can be read from state/App instance directly.
- render the `ContextMenu` component directly to [`<div className="excalidraw-contextMenuContainer" />`](https://github.com/excalidraw/excalidraw/blob/1f117995d90a1bb6c452791eff62c3efad66ee61/src/components/App.tsx#L592)

**Comment by zsviczian** [comment]
Regarding the move to React18... this issue still needs a proper resolution as well: #5603

**Comment by nihal-ramaswamy** [comment]
hey, can I work on this issue?
