### ISSUE TITLE
proposal: deploy from a `release` branch

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#5936]
Proposal to create a `release` branch and auto-release from there. We'd keep working from and merging to `master`. Once we want to make a release, we'd merge `master` into `release`.

Reasoning:

1) Each release we force-reload clients. If we make 10 releases a day, that's potentially 10 reloads for people. Each reload can be pretty annoying.
2) Each release invalidates SW cache (haven't checked, but hopefully just for the changed build artifacts. But, it would pretty much contain at least the main bundle anyway). Meaning, unnecessary increase in bandwidth for users, and for us.
3) The two reasons above makes us less inclined to make frequent releases. If we want to split a feature into several PRs, we can't (or it's hard to do so). If we want to make several related or stacked PRs, same issue.
4) Same goes for npm releases. If we want to do larger API rewrites, we'd likely need to disable the release action for the duration.
5) Similarly, some heavy CI actions such as deploying to Docker is unnecessarily blocking / slowing down the queue.

/cc @ad1992

**Comment by ad1992** [comment]
Sounds good lets do it!

**Comment by ad1992** [comment]
closed via #5958
