### ISSUE TITLE
Any ideas why Google Translate extension recognizes the site as French?

### ISSUE THREAD

**Issue by gmertk** [excalidraw/excalidraw#595]
![Screen Shot 2020-01-27 at 7 11 15 PM](https://user-images.githubusercontent.com/907281/73205581-2e108f80-4139-11ea-962a-08e19d240bef.png)

**Comment by dwelle** [comment]
:thinking:

**Comment by Fausto95** [comment]
Maybe because @vjeux is French lol

**Comment by Fausto95** [comment]
<img width="364" alt="Capture d’écran 2020-01-27 à 20 49 41" src="https://user-images.githubusercontent.com/23306911/73208489-d4af5d00-4146-11ea-9e36-49534b8dfa97.png">

I'm getting it too even tho my computer is in French

**Comment by lipis** [comment]
Maybe #597

**Comment by dwelle** [comment]
Can anyone still repro this?

**Comment by gmertk** [comment]
I'm not able to repro this anymore. 👍

Closing this issue for now.
