### ISSUE TITLE
Moving text bound to objects became buggy

### ISSUE THREAD

**Issue by sojusnik** [excalidraw/excalidraw#5953]
After a recent update, moving text bound to objects only moves the text, but not the text together with the object. This happens only with text that was created before the update. See [this](https://excalidraw.com/#room=ca28f1ca74bda5dbd7da,U-2mrEVr0c_bSwnHaEziyQ) shared whiteboard as an example. Try to move the text within the box and you'll see that only the text will be moved. But if you create a new box with text in it, then both can be easily moved.

**Comment by dwelle** [comment]
Thanks for the report. Should be fixed now!
