### ISSUE TITLE
High Ms(ping of excalidraw plugin)

### ISSUE THREAD

**Issue by paranjay245** [excalidraw/excalidraw#5984]
<img width="237" alt="image" src="https://user-images.githubusercontent.com/120307516/206897963-8d33bf48-ea00-4e15-b3bf-39733336ba0f.png">

High Ping for each device be it be mac or ipad or windows everywhere i am experiencing high ms

and 

1. I Tried With new vault same issue
2. I Also Tried Formating Mac & With Fresh OS & Vault

**Comment by dwelle** [comment]
Hi! Not sure what this means and whether it's possibly not related to the editor itself, but it's best to post this on their tracker https://github.com/zsviczian/obsidian-excalidraw-plugin/issues
