### ISSUE TITLE
Fill for all shapes doesn't work

### ISSUE THREAD

**Issue by xanderhub** [excalidraw/excalidraw#5986]
![image](https://user-images.githubusercontent.com/33380175/207086398-14e948e1-d981-4cda-b26b-3a013ed1620e.png)
![image](https://user-images.githubusercontent.com/33380175/207087583-36aafcfd-5be4-4069-80b1-a6df72b1a1d0.png)

**Comment by dwelle** [comment]
The fill options show only once you pick a non-transparent background color.

Not sure how you ended up with the screenshot 1 (could be a multiselection where at least one element had a non-transparent bg, but in that case the color input should be empty 🤔)

**Comment by herropaul** [comment]
Not sure if this was intended, but the fill option will appear once you select a background color for a shape. It looks like by default it won't show the fill options because it's transparent by default

**Comment by xanderhub** [comment]
Thanks @dwelle, I didn't notice that there was transparent background enabled.
This fixed my problem
