### ISSUE TITLE
Feature Request: Wireframe capabilities

### ISSUE THREAD

**Issue by andrioid** [excalidraw/excalidraw#599]
Proposal: Add [wiredjs](https://wiredjs.com/) components as elements in Excalidraw to enable easy wireframes.

I realize that this is probably way out of scope. But I would definitely use it for UX mockups if this was added.

**Comment by dwelle** [comment]
The idea of assets was discussed in https://github.com/excalidraw/excalidraw/pull/299.

I don't think we should be adding another library's elements directly. How about we rename this to "Add assets support"?

**Comment by vjeux** [comment]
I’m curious, are you interested in interactivity for those components?

**Comment by andrioid** [comment]
> I’m curious, are you interested in interactivity for those components?

Not at all. Strictly for rough sketches.

**Comment by andrioid** [comment]
@dwelle Thanks for the link. Guess we could call this assets, but I not looking to add images or anything high-fidelity. Another approach could be to add more grouping features and allow the user to save groups into "elements" of their own.

That way we're not adding wiredjs or extra dependencies, just storing and re-using grouped-elements that we drew in Excalidraw.

**Comment by dwelle** [comment]
Yes, user-defined assets could be a thing too. Also, I'd likely implement this as SVGs, not full-blown elements. It has drawbacks (in certain scenarios, won't scale as well), and advantages (less code; no need to maintain; "easy" to implement; in certain scenarios will scale better).

**Comment by lipis** [comment]
We'll mark it as out of scope for now.. we have a library support but is not globally shareable
