### ISSUE TITLE
Button use to escape from full size window mode was hidden by the system buttons

### ISSUE THREAD

**Issue by hoangtrungnguyen** [excalidraw/excalidraw#5991]
![image](https://user-images.githubusercontent.com/47657020/207530494-b2058118-0ea0-4ea2-b06b-e539173ad12f.png)

I am using window 11 on Dell computer. On the top right corner of the screen, the escape button was hidden. Because of that  I unable to escape excalidraw full screen mode, so I have to reopen the Obsidian app and it is very annoy.

I hope you will fix this issue soon. Thank you  !!

**Comment by dwelle** [comment]
What escape button are talking about? Excalidraw uses the browser's native fullscreen behavior, which asks you to use `Esc` to exit the fullscreen (or you can use our `f` shortcut again).

Possibly Obsidian related? /cc @zsviczian

**Comment by Giovy27072** [comment]
I have a similar problem, using ESC nothing appens... So if i enter in full screen mode i get stuck in this mode.

**Comment by dwelle** [comment]
> I have a similar problem, using ESC nothing appens... So if i enter in full screen mode i get stuck in this mode.

Is this excalidraw.com or Obsidian? What's your browser and OS? Does `F` work?

**Comment by Giovy27072** [comment]
> Is this excalidraw.com or Obsidian? What's your browser and OS? Does `F` work?

Obsidian version 1.0.3 (App image package)
OS: Arch Linux x64

If press F Obsidian enters in full screen mode, but excalidraw does not change

**Comment by hoangtrungnguyen** [comment]
> What escape button are talking about? Excalidraw uses the browser's native fullscreen behavior, which asks you to use `Esc` to exit the fullscreen (or you can use our `f` shortcut again).
> 
> Possibly Obsidian related? /cc @zsviczian

I'm using Obsidian on Win 11. I have a solution for it, but it a bit manual. On the image, you move your menu bar to the left side of the screen, after click on the obsidian icon, there is a menu. In the menu, there is a option to minimize the editor. 
![image](https://user-images.githubusercontent.com/47657020/208217199-e5ad85c3-b93d-4075-b7ec-522d3d2d69e6.png)

**Comment by Giovy27072** [comment]
> > Is this excalidraw.com or Obsidian? What's your browser and OS? Does `F` work?
> 
> Obsidian version 1.0.3 (App image package) OS: Arch Linux x64
> 
> If press F Obsidian enters in full screen mode, but excalidraw does not change

i have recorded a small video to show the problem: https://drive.google.com/file/d/19L9CwvkS7MgrZDy4d6lMepjlucz-RGpC/view?usp=sharing

**Comment by dwelle** [comment]
Esc works for me. In any this, this doesn't seem related to excalidraw, but the Obsidian plugin, so best open an issue on their tracker: https://github.com/zsviczian/obsidian-excalidraw-plugin/issues

If it turns out it's related to the excalidraw editor, let us know and we'll reopen.
