### ISSUE TITLE
display message if offline while collaborating

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#5994]
When collaborating and you get offline (e.g network goes down), we should display a message. A toast perhaps.

**Comment by Mattross45** [comment]
Seems like #6049 will fix the issue

**Comment by dwelle** [comment]
> Seems like #6049 will fix the issue

no, that just shows a message if you can't connect or get disconnected from the server for whatever reason. The offline state will need to handled separately!

Feel free to take this up.

Add OP, I think we actually shouldn't use toasts for this. Display a message under the toolbar.

**Comment by Mattross45** [comment]
I can try and take this up, by message under the toolbar, are you thinking about hints or something else ?

**Comment by dwelle** [comment]
> I can try and take this up, by message under the toolbar, are you thinking about hints or something else ?

I'd create a completely custom component for this that we'd render with a `position: fixed` below the toolbar for important messages like this.
