### ISSUE TITLE
Cross-Origin Request Blocked when trying to get a shareable link

### ISSUE THREAD

**Issue by Vinnl** [excalidraw/excalidraw#600]
When I click the "Get shareable link" button, I get an alert window saying "Couldn't create shareable link.", and the following error messages in the console:

> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://json.excalidraw.com/api/v1/post/. (Reason: CORS header 'Access-Control-Allow-Origin' missing).
> 
> Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://json.excalidraw.com/api/v1/post/. (Reason: CORS request did not succeed).

**Comment by dwelle** [comment]
How can we repro this? What exact domain are you on?

**Comment by Vinnl** [comment]
I'm on Excalidraw.com. Other potentially relevant information: Firefox 72.0.1 on Ubuntu 18.04.3. Will do some quick testing in other browsers as well.

**Comment by dwelle** [comment]
Shareable link doesn't work for FF [right now](https://github.com/excalidraw/excalidraw/pull/580), so that explains that part. The CORS I can't explain. Tested on FF and I get nothing like that.

**Comment by Vinnl** [comment]
Hmm, OK, that explains that. It also doesn't work in WebKit-based Epiphany, but also without the CORS error, so I'm guessing that's for the same reason.

**Comment by dwelle** [comment]
In Network tab, it shows (for me at least) tat the CORS for this domain is explicitly enabled:

![image](https://user-images.githubusercontent.com/5153846/73266043-64501c80-41d6-11ea-9f4f-067a0bbcb4ec.png)

**Comment by Vinnl** [comment]
Ah sorry, didn't think to check that, but it seems to fail on the `OPTIONS` call:

![image](https://user-images.githubusercontent.com/4251/73266261-d7f22980-41d6-11ea-9859-a552f973d4ad.png)

**Comment by dwelle** [comment]
Yes, if the OPTIONS fails on CORS, the POST isn't made. Can you please show the `request headers`?

**Comment by Vinnl** [comment]
Sure, here you go:

![image](https://user-images.githubusercontent.com/4251/73266512-4e8f2700-41d7-11ea-92c8-ae7674cf84a0.png)

The weird thing is: in Private Browsing I do see the CORS headers:

![image](https://user-images.githubusercontent.com/4251/73266567-68306e80-41d7-11ea-868a-5dc6c6545fa8.png)

**Comment by dwelle** [comment]
Mhm, in this particular instance there's no CORS issue. The POST contains the correct `access-control-allow-origin`, and the POST is made, too.

**Comment by Vinnl** [comment]
Ah, looking at the difference there, it appears it's looking at the Referer header? In which case I'm guessing the [Smart Referer](https://addons.mozilla.org/firefox/addon/smart-referer/) extension is interfering, which is disabled in Private Browsing.

**Comment by dwelle** [comment]
Mhm, that seems to be it. AFAIK we should be checking `origin`, not `referer` headers.

/cc @lipis

**Comment by lipis** [comment]
https://github.com/excalidraw/excalidraw-json/blob/master/main/main.py#L41

**Comment by dwelle** [comment]
@lipis when we're at it, is it possible/advisable to whitelist `now.sh`/`netlify.com` subdomains so we can test the PRs?

https://deploy-preview-580--excalidraw.netlify.com/
https://excalidraw-d982uqrq9.now.sh/

Not sure if it's possible to whitelist subdomains containing `excalidraw` word (I don't think so).

**Comment by lipis** [comment]
They are already whitelisted.. https://github.com/excalidraw/excalidraw-json/blob/master/main/main.py#L36

**Comment by dwelle** [comment]
I see. But doesn't work for `now.sh` because there's no `vjeux` in the `origin` (or `referer`, so far).

**Comment by lipis** [comment]
I tried and it works from these domains.. are you getting any error creating a shearable link from these URLs?

**Comment by lipis** [comment]
Oh.. I see.. now is not always using vjeux..

**Comment by lipis** [comment]
What about #461?

**Comment by vjeux** [comment]
I'm curious why it uses "vjeux" and not "excalidraw". Does anyone know?

**Comment by lipis** [comment]
Have no idea.. I have no experience with NOW.
