### ISSUE TITLE
[Function request]  Persistent import plug-ins

### ISSUE THREAD

**Issue by dnslin** [excalidraw/excalidraw#6000]
Since I deploy my own excalidraw, I am eager to persist the import of my excalidraw plug-in to my own excalidraw, because as soon as I clear the cache, the excalidraw plug-in will have to be re-imported  And thank you for making it so easy to use

**Comment by DanielJGeiger** [comment]
@dnslin Do you mean plugins for Excalidraw, or Excalidraw as a plugin itself?  If you mean plugins for Excalidraw, that would require a substantial sandboxing system.  If you mean Excalidraw as a plugin, then perhaps you have found a bug.

cc @dwelle @ad1992

**Comment by dwelle** [comment]
Missed this. @dnslin, what can you clarify as per what @DanielJGeiger said?

**Comment by dnslin** [comment]
> 错过了这个。@dnslin, 你能根据什么澄清什么@DanielJGeiger说？

nothing No problem, maybe this applies to me
