### ISSUE TITLE
HamburgerMenu public API

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#6023]
As per discussion in https://github.com/excalidraw/excalidraw/issues/5960, we want to expose public API for customizing HamburgerMenu.

![image](https://user-images.githubusercontent.com/5153846/208890602-c01daf9d-5598-4934-81d8-b939b04d1f22.png)

There are 2 main ideas:

1. Always render default items, and additionally allow to add custom ones.
    
    **Pros:**
    
    - Updates to the app (adding/changing default items) will always be reflected to host apps
    
    **Cons:**
    
    - Hard to allow adding items in between default ones
    - Hard to allow to remove default items you don't want

3. Render the default hamburger menu only if the host app doesn't render by itsels.

    **Pros:**
    
    - Easy to customize everything
    
    **Cons:**
    
    - Updates to the app (adding/changing default items) will not be reflected to host apps — they'll have to track the changes and update the menu by themselves.

**Comment by dwelle** [comment]
I guess let's do it the "customize everything" for now?

1. if `<HamburgerMenu>` not rendered from host app, default to something like this:

    ![image](https://user-images.githubusercontent.com/5153846/208889540-5eb7e8b5-1b13-4a58-bf1e-a229a7e3ce55.png)

2. if `<HamburgerMenu>` rendered from host app, don't render any items inside of it, and require host apps to build it up from the default exported items and their own items.

**Comment by ad1992** [comment]
Yep agreed 👍🏻

**Comment by dwelle** [comment]
To start out:

1. If `<HamburgerMenu>` not rendered, render the default.
2. If rendered, render it empty.
3. Create a `<HamburgerMenu.Item>` component that we'll use for our own hamburgerMenu items, which we'll wrap into their own components and export publicly for people to reuse. And we'll also export the `<HamburgerMenu.Item>` itself so people can build their own custom items.
4. The `<HamburgerMenu.Item>` should take `icon?: React.Node`, `onClick?: () => any`, `shortcut?: string` , and `children` props. `children` being the text or whatever else people want to render. 
5. Also export a `<HamburgerMenu.Separator>`

Example:

```jsx
import { Excalidraw, HamburgerMenu } from "@excalidraw/excalidraw";

return (
  <Excalidraw>
    <HamburgerMenu>
      <HamburgerMenu.ItemOpen/>
      <HamburgerMenu.ItemExportFile/>
      <HamburgerMenu.ItemExportImage/>
      <HamburgerMenu.ItemHelp/>
      <HamburgerMenu.ItemResetCanvas/>
      <HamburgerMenu.Item icon={<SomeIcon/>} onClick={() => console.log("Heisenberg")}>
        Say my name.
      </HamburgerMenu.CustomItem>
      <HamburgerMenu.Separator/>
      <HamburgerMenu.ItemThemeToggle/>
      <HamburgerMenu.ItemCanvasBackground/>
    </HamburgerMenu>
  </Excalidraw>
)
```

**Comment by ad1992** [comment]
In addition, it's better to keep it "Menu" instead of "HamburgerMenu" to keep it short and simple.

**Comment by dwelle** [comment]
Perhaps, though we need to ensure the naming of all the components we'll end up with is clear and distinguishable. Menu is pretty generic (but so is HamburgerMenu).
