### ISSUE TITLE
container text on arrows now has a white background

### ISSUE THREAD

**Issue by zsviczian** [excalidraw/excalidraw#6032]
@ad1992 

https://user-images.githubusercontent.com/14358394/209375516-f2489b2d-f676-4901-8fbe-d7209179d7a4.mp4

**Comment by dwelle** [comment]
Checking blame, this was present from day one of arrow labels. I assume it was forgotten from before proper masking for adding.

**Comment by ad1992** [comment]
Yes this was there from day 1 for labelled arrows. Thanks @zsviczian for catching this!

**Comment by zsviczian** [comment]
That was fixed quickly! You guys are awesome! Thanks.
