### ISSUE TITLE
popover overflows viewport

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#6045]
Popover can overflow the viewport if opened at the edges (e.g. mobile view color picker for the canvas bg). We should either fix the positioning, or migrate to Radix popover directly.

**Comment by fouqueta** [comment]
Hello!
If possible I'd like to try solving this 😊

**Comment by dwelle** [comment]
Hi. This was actually fixed recently for context menu (https://github.com/excalidraw/excalidraw/pull/6433) and is fixed for color picker in https://github.com/excalidraw/excalidraw/pull/6216. So closing, but thanks!

Is there anything else you'd like to work on? What "difficulty" do you feel like taking on?

**Comment by fouqueta** [comment]
My bad! Yes, I'd like to work on easy code modifications if possible. Do you think #6193 (or #6189) could do it?
