### ISSUE TITLE
[new feature] animate line

### ISSUE THREAD

**Issue by mawnir** [excalidraw/excalidraw#6053]
Is there a way to animate the arrows and lines?

**Comment by dwelle** [comment]
No, nothing currently in the works with respect to animations.

But @dai-shi has made an app to take your excalidraw drawings and animate it as a whole: https://dai-shi.github.io/excalidraw-animate/ (https://github.com/dai-shi/excalidraw-animate)

**Comment by mawnir** [comment]
> No, nothing currently in the works with respect to animations.
> 
> But @dai-shi has made an app to take your excalidraw drawings and animate it as a whole: https://dai-shi.github.io/excalidraw-animate/ (https://github.com/dai-shi/excalidraw-animate)

Thank you.. a great tool!
