### ISSUE TITLE
Branch free of tracking 

### ISSUE THREAD

**Issue by RobinSrimal** [excalidraw/excalidraw#6058]
Hi All, 

I am wondering which of the branches is free of tracking components? I would like to build on top of that. 

Thank you for help!

**Comment by dwelle** [comment]
Hi. The npm package does not include any tracking, it's used just for the excalidraw.com app!

**Comment by RobinSrimal** [comment]
But whht if I need to edit the code itself?

**Comment by dwelle** [comment]
No branch. The docker image is built uses a modified build. But now I'm not sure whether it was being stripped properly (I wasn't on the Docker team nor do I use it), or whether it regressed.

In any case, if you plan to fork the repo to make changes, and you still want to be deploying the excalidraw.com app wrapper as opposed to build your app from the package API, then I suggest you delete the tracking code in index.html, or use the `REACT_APP_DISABLE_TRACKING=true` ENV var when building which we're adding to be sure: https://github.com/excalidraw/excalidraw/pull/6059.

We're filtering out non-excalidraw hostname tracking data regardless, so not much would happen.
