### ISSUE TITLE
blog.excalidraw.com/year-three

### ISSUE THREAD

**Issue by anatoliibakhtin** [excalidraw/excalidraw#6064]
It seems that it is time to hang a ready total of 2022 ? It's not vital, so it's up to you, I was interested to read last years totals,  https://blog.excalidraw.com/year-two/ https://blog.excalidraw.com/one-year-of-excalidraw/

Thank you for your work and Happy New 2023 Year🎄

**Comment by dwelle** [comment]
Thanks. Coming out soon!
