### ISSUE TITLE
Excalidraw Plus: Sidebar/Canvas color contrast in dark mode

### ISSUE THREAD

**Issue by pckilgore** [excalidraw/excalidraw#6079]
This is very small, but a lot of times I click into the sidebar in dark mode on accident, because it's low contrast to the canvas color, and wonder why nothing happens.  

![image](https://user-images.githubusercontent.com/2559043/211065982-ef8d683e-6bb4-414e-ac1c-5dc2f9bee3fb.png)

**Comment by dwelle** [comment]
Good point. Fixed 👍 

![image](https://user-images.githubusercontent.com/5153846/211094499-375d7230-9687-49f8-99eb-9b0f18a423cc.png)
