### ISSUE TITLE
Stuck in full screen mode

### ISSUE THREAD

**Issue by Muwenen** [excalidraw/excalidraw#6081]
I don't know why but once I click on the full screen button, I can't go back with ESC. Can I keep the button directly on the canva as a tool?

**Comment by dwelle** [comment]
Hi. Excalidraw doesn't have a fullscreen button per-se. Are we talking about the Obsidian plugin? https://github.com/excalidraw/excalidraw/issues/5991

**Comment by Muwenen** [comment]
yes
