### ISSUE TITLE
Firefox: Boxes with text have unremovable extra line

### ISSUE THREAD

**Issue by phidah** [excalidraw/excalidraw#6093]
When I create a rectangle and add some text, after resizing the rectangle there's a linebreak at the end of the text that can't be removed. This means that the rectangle cannot be made smaller than 2 lines of text in height even though there is just one line of text.

It looks like this:

https://user-images.githubusercontent.com/173517/211386253-99ce2d67-f848-4ce6-8d34-e9081cfb5d86.mp4

Steps to reproduce:
1. Start a blank canvas
2. Make a rectangle approx 4 lines tall
3. Enter a text that is one line
4. Try to make the rectangle 1 line tall

This used to work fine, but some time during the last couple of weeks it has become impossible to remove the line break after the text.

I am on Firefox 108.0.2 on Mac OS 13.1. It works fine in Safari.

Not sure this is the right place to put this, but Excalidraw.com linked here.

**Comment by SkoricIT** [comment]
Can confirm, problem seems to have started recently.
Firefox 108.0.1 (64-Bit) on Manjaro Linux

**Comment by dwelle** [comment]
I can't reproduce myself. Does it reproduce here? https://excalidraw-dq7zpgzuc-excalidraw.vercel.app/

**Comment by sedghi** [comment]
I have this issue sometimes on Chrome

**Comment by phidah** [comment]
> I can't reproduce myself. Does it reproduce here? https://excalidraw-dq7zpgzuc-excalidraw.vercel.app/

The bug is not present on that link. It also seems to be fixed on Excalidraw.com. Will close this issue. Thanks for investigating.

**Comment by SkoricIT** [comment]
The bug is back today, unfortunately.

**Comment by SkoricIT** [comment]
here is a copy of an element that i can't resize in Firefox
`{"type":"excalidraw/clipboard","elements":[{"type":"rectangle","version":2488,"versionNonce":364845990,"isDeleted":false,"id":"ia_obxH7TwWboWNalYDEw","fillStyle":"hachure","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"angle":0,"x":1096.3474401562162,"y":-10.632669529865552,"strokeColor":"#000000","backgroundColor":"transparent","width":122,"height":62,"seed":238737820,"groupIds":[],"roundness":null,"boundElements":[{"type":"text","id":"2TIcwDCx5wyYUi5WInIAj"}],"updated":1673436231227,"link":null,"locked":false},{"type":"text","version":1335,"versionNonce":1462654010,"isDeleted":false,"id":"2TIcwDCx5wyYUi5WInIAj","fillStyle":"hachure","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"angle":0,"x":1133.8474401562162,"y":-5.632669529865552,"strokeColor":"#000000","backgroundColor":"transparent","width":47,"height":52,"seed":716054052,"groupIds":[],"roundness":null,"boundElements":[],"updated":1673436189748,"link":null,"locked":false,"fontSize":20,"fontFamily":1,"text":"save","baseline":44,"textAlign":"center","verticalAlign":"middle","containerId":"ia_obxH7TwWboWNalYDEw","originalText":"save"}],"files":{}}`

**Comment by dwelle** [comment]
@SkoricIT can you post your Excalidraw version? Right-click on canvas -> Stats for nerds -> click on the version to copy and paste it here. Thanks!

**Comment by SkoricIT** [comment]
`2023-01-09T09:24:17Z-6184422`

![grafik](https://user-images.githubusercontent.com/1708378/211810703-ca73ffa6-b09c-4712-854d-dc9a5205b565.png)

**Comment by dwelle** [comment]
Alright, that's latest.

(The code you pasted reproduces for me until to the point I enter the text editor, then it fixes itself.)

**Comment by SkoricIT** [comment]
@dwelle I was thinking maybe a full save file will help. Then i checked the file and it is kind of just almost the same as the single element. Here you go anyway. 
[TestFile-2023-01-12-0947.excalidraw.txt](https://github.com/excalidraw/excalidraw/files/10399776/TestFile-2023-01-12-0947.excalidraw.txt)

**Comment by dwelle** [comment]
Ok, I can reproduce on Firefox 109, but only on MacOS.

Though if I copy out the element, it carries over to other browsers / OS until refresh.

```
{"type":"excalidraw/clipboard","elements":[{"type":"rectangle","version":415,"versionNonce":843745595,"isDeleted":false,"id":"rifiiUPLx1SmEtPBDD8Rf","fillStyle":"hachure","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"angle":0,"x":802.559427752042,"y":551.2852678832888,"strokeColor":"#000000","backgroundColor":"transparent","width":160,"height":58,"seed":1840571515,"groupIds":[],"roundness":null,"boundElements":[{"type":"text","id":"O4zChS_IAngRWYBcyf6Du"}],"updated":1674660937044,"link":null,"locked":false},{"type":"text","version":222,"versionNonce":1416231925,"isDeleted":false,"id":"O4zChS_IAngRWYBcyf6Du","fillStyle":"hachure","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"angle":0,"x":834.059427752042,"y":556.2852678832888,"strokeColor":"#000000","backgroundColor":"transparent","width":97,"height":48,"seed":534115509,"groupIds":[],"roundness":null,"boundElements":null,"updated":1674660937044,"link":null,"locked":false,"fontSize":20,"fontFamily":1,"text":"asdadasd","baseline":41,"textAlign":"center","verticalAlign":"middle","containerId":"rifiiUPLx1SmEtPBDD8Rf","originalText":"asdadasd"}],"files":{}}
```

**Comment by SkoricIT** [comment]
@dwelle Can I help anyhow?

**Comment by dwelle** [comment]
@SkoricIT thanks! Now that we can reproduce we should be good :)

**Comment by ad1992** [comment]
> Ok, I can reproduce on Firefox 109, but only on MacOS.
> 
> Though if I copy out the element, it carries over to other browsers / OS until refresh/edit (as mentioned previously).
> 
> ```
> {"type":"excalidraw/clipboard","elements":[{"type":"rectangle","version":415,"versionNonce":843745595,"isDeleted":false,"id":"rifiiUPLx1SmEtPBDD8Rf","fillStyle":"hachure","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"angle":0,"x":802.559427752042,"y":551.2852678832888,"strokeColor":"#000000","backgroundColor":"transparent","width":160,"height":58,"seed":1840571515,"groupIds":[],"roundness":null,"boundElements":[{"type":"text","id":"O4zChS_IAngRWYBcyf6Du"}],"updated":1674660937044,"link":null,"locked":false},{"type":"text","version":222,"versionNonce":1416231925,"isDeleted":false,"id":"O4zChS_IAngRWYBcyf6Du","fillStyle":"hachure","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"angle":0,"x":834.059427752042,"y":556.2852678832888,"strokeColor":"#000000","backgroundColor":"transparent","width":97,"height":48,"seed":534115509,"groupIds":[],"roundness":null,"boundElements":null,"updated":1674660937044,"link":null,"locked":false,"fontSize":20,"fontFamily":1,"text":"asdadasd","baseline":41,"textAlign":"center","verticalAlign":"middle","containerId":"rifiiUPLx1SmEtPBDD8Rf","originalText":"asdadasd"}],"files":{}}
> ```

@dwelle does this get fixed for you in https://excalidraw-pg2w5kahv-excalidraw.vercel.app/ in ff when you edit ?

**Comment by ad1992** [comment]
@SkoricIT this should be fixed now, can you confirm ? If you try to resize / edit it should get fixed for these elements

**Comment by chrisdoherty4** [comment]
Seems to be fixed on excalidraw.com (MacOS 12.6; FF 102). What's the typical lead time for app.excalidraw.com to get updates?

**Comment by ad1992** [comment]
Awesome, thanks for confirming @chrisdoherty4! Will be shipped in Excalidraw Plus soon today!
cc @dwelle 

Closing this as its fixed
