### ISSUE TITLE
want custom font 

### ISSUE THREAD

**Issue by dragonTalon** [excalidraw/excalidraw#6095]
Chinese fonts are too formal, hope to support custom fonts

**Comment by Harufuu** [comment]
可以加第四种字体，在excalidraw设置页面的最后两项。

**Comment by dragonTalon** [comment]
直接搭建的才有这两项吧

**Comment by dragonTalon** [comment]
> 可以加第四种字体，在excalidraw设置页面的最后两项。

自己搭建的才有这两项吧

**Comment by Tahmasb** [comment]
> 我做了一個 Chrome extension 可以更換自己想要的字體 https://github.com/jcyh0120/excalidraw-custom-font

Where can we find the link of these fonts?
If possible, send a link that contains a list of these fonts

**Comment by DawidWraga** [comment]
Incase anyone is wondering, I spent a while figuring this out but I've found a solution.

I've written an article on how to use custom fonts on excalidraw [here](https://dev.to/dawidcodes/how-to-use-a-custom-font-on-excalidrawcom-4jl4)
