### ISSUE TITLE
Live Collaboration button not there in react  excalidraw component

### ISSUE THREAD

**Issue by sumit0001jnv** [excalidraw/excalidraw#6108]
Create a standalone excalidraw app I can see the live collaboration button on the top right. But if I create a react app and want to add excalidraw as a component then there is no collaboration button. 
How do get that live collaboration button in react component?

<img width="927" alt="excalidraw standalone" src="https://user-images.githubusercontent.com/32199342/212238812-3e8c97dc-12b7-430d-8500-81edc1c0bbc1.png">
<img width="927" alt="excalidraw standalone" src="https://user-images.githubusercontent.com/32199342/212238835-963ce1cb-bf71-40fd-ad47-a1597b8aa172.png">

**Comment by ad1992** [comment]
@sumit0001jnv we have updated the API and introduced a new component [LiveCollaborationTrigger](https://github.com/excalidraw/excalidraw/blob/master/src/packages/excalidraw/README.md#livecollaborationtrigger) which you will need to use to add the collab component. You can try out the `@excalidraw/excalidraw@next` version for the latest changes. 
We will be releasing the stable version very very soon. Here is [CSB example](https://1m7pt.csb.app/) using the `next` version.

**Comment by dwelle** [comment]
@sumit0001jnv note that at present the npm package does not implement the collaboration logic, so adding the button only will not handle that.

**Comment by ad1992** [comment]
closing this as the package is out - you can upgrade to `0.14.1` version of [@excalidraw/excalidraw](https://www.npmjs.com/package/@excalidraw/excalidraw)
