### ISSUE TITLE
ConfirmDialog should be outside MainMenu.

### ISSUE THREAD

**Issue by proke03** [excalidraw/excalidraw#6115]
ConfirmDialog for clearCanvas action needs to stay open when menu is closed.

There is a FIXME comment in the code, but there are no submitted issues so submit it to check.

**Comment by LeGorge** [comment]
I think this was fixed on this commit https://github.com/excalidraw/excalidraw/commit/1db078a3dceb76c53d27932049563ed28a7c4b62 for #6152
