### ISSUE TITLE
Copy to clipboard is broken in Firefox on MacOS

### ISSUE THREAD

**Issue by orlp** [excalidraw/excalidraw#6118]
In Firefox 108.1 on MacOS Monterey 12.6 on an 2021 M1 Macbook the copy to clipboard functionality (shift + option + C) is broken. I get the following error dialog:

<img width="561" alt="image" src="https://user-images.githubusercontent.com/202547/212496390-557b73cc-aad7-48c1-bdfb-b1fec4e8ec7d.png">

In the console the following error is displayed:

<img width="288" alt="image" src="https://user-images.githubusercontent.com/202547/212496279-8203b534-3ea4-4e9a-b590-71f7f6ba055e.png">

The copy to clipboard functionality works on the same machine under Safari.

**Comment by dwelle** [comment]
We should actually not be showing that shortcut in the help dialog on Firefox as it won't work — it's missing the async clipboard API support for this.

**Comment by orlp** [comment]
@dwelle Is there no way to make it work? Isn't there [`clipboard.setImageData()`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/clipboard/setImageData)?

I don't think hiding the shortcut is the solution to go for here.

**Comment by orlp** [comment]
It appears that if you set `dom.events.asyncClipboard.clipboardItem` in `about:config` then `navigator.clipboard.write` becomes available (instead of only having access to `navigator.clipboard.writeText`).

@dwelle Could excalidraw check for the availability of `navigator.clipboard.write`, and if yes, use it? Then users that want it now can simply enable `dom.events.asyncClipboard.clipboardItem` in the config and when it eventually stabilizes Excalidraw is immediately ready.

Here is the current Firefox issue to enable said flag automatically on Nightly: https://bugzilla.mozilla.org/show_bug.cgi?id=1809106.

**Comment by dwelle** [comment]
> @dwelle Is there no way to make it work? Isn't there [`clipboard.setImageData()`](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/clipboard/setImageData) (edit: it appears that is for web extensions)?

correct, that's just for browser extensions.

> @dwelle Could Excalidraw check for the availability of `navigator.clipboard.write`,

We're doing that already. But I also had to rewrite the code a bit to fix another firefox's issue. You can try here: 
![image](https://user-images.githubusercontent.com/5153846/212734433-f03fd186-a3c7-4542-8b27-e24c7c6fe262.png)

**Comment by orlp** [comment]
> You can try here:

I am confused, you linked me a picture? What am I supposed to try?

**Comment by dwelle** [comment]
lol, not checking what I'm pasting 😅

https://excalidraw-git-dwelle-hide-png-copy-help-dialog-excalidraw.vercel.app/

**Comment by orlp** [comment]
@dwelle Thanks for getting this resolved quickly.
