### ISSUE TITLE
Support Github link says Visit Discord

### ISSUE THREAD

**Issue by paudrow** [excalidraw/excalidraw#6119]
<img width="856" alt="Screenshot 2023-01-14 at 4 05 51 PM" src="https://user-images.githubusercontent.com/114802901/212499176-1a6f2628-40ad-4c36-9fca-97b08b3e9e80.png">

When I click the support button, the Github option also says "Visit Discord." The link is correct and takes me here.

**Comment by ad1992** [comment]
Oops, this is a typo!
cc @maielo @barnabasmolnar
