### ISSUE TITLE
Shift resizing shapes make the text alignment flicker

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#6137]
https://user-images.githubusercontent.com/197597/213808766-86d720b0-07e5-4778-a618-af964d5ea6dd.mov

https://excalidraw.com/#json=MBMZxlGvtTj3VNFc3YzWP,mSFQzx6sqmXRuLSO9N9VCQ

**Comment by ad1992** [comment]
closed via #6162
