### ISSUE TITLE
Broken emoji in rectangle if open in some browsers

### ISSUE THREAD

**Issue by szpak** [excalidraw/excalidraw#6145]
I has been using shared canvas for a while without any problem, however, recently I've encountered a situation when (a new group of) people opening canvas/scene in some browsers broke an emoji placed in a rectangle (for all the collaborators). "😃" (and any other used "smile" as well) was replaced by "\ud83d\n\ude03" (or an equivalent).

Before:
![image](https://user-images.githubusercontent.com/148013/213888337-117d3b4e-d212-4054-83df-b1caa7db752e.png)

After:
![image](https://user-images.githubusercontent.com/148013/213888349-ae413b5e-49f2-45be-aa36-d048130ef261.png)

When I analyzed its content exported to JSON (copy-paste), there was:
> "text":"😃" and "originalText":"😃"

and after:
> "text":"\ud83d\n\ude03" and "originalText":"😃"

I was not able to reproduce it with Firefox 108 and Chromium 109 on Linux. People in majority had Edge on Windows, but there is a chance that some other browser could cause that.

I realized it could be hard to track down, so feel free to close it if you have no idea of the reason. Anyway, I report it as some other people could also encountered that and maybe have some more reproducible example.

<details><summary>Full JSON of a "rectangle with text" folded</summary>

OK:
```
{"type":"excalidraw/clipboard","elements":[{"type":"rectangle","version":545,"versionNonce":349246315,"isDeleted":false,"id":"RgMx74nKPZOqKlMtOvOWR","fillStyle":"hachure","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"angle":0,"x":696.9999999999999,"y":233.50000000000003,"strokeColor":"#000000","backgroundColor":"#ced4da","width":48,"height":45,"seed":782852651,"groupIds":[],"roundness":null,"boundElements":[{"type":"text","id":"xrD8X84ZudNu2uGpRDcnU"}],"updated":1674196871752,"link":null,"locked":false},{"type":"text","version":434,"versionNonce":82043237,"isDeleted":false,"id":"xrD8X84ZudNu2uGpRDcnU","fillStyle":"cross-hatch","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"angle":0,"x":702.9999999999999,"y":238.50000000000003,"strokeColor":"#000000","backgroundColor":"#fab005","width":36,"height":35,"seed":1958046213,"groupIds":[],"roundness":null,"boundElements":null,"updated":1674196871752,"link":null,"locked":false,"fontSize":28,"fontFamily":1,"text":"😃","baseline":25,"textAlign":"center","verticalAlign":"middle","containerId":"RgMx74nKPZOqKlMtOvOWR","originalText":"😃"}],"files":{}}
```

Broken:
```
{"type":"excalidraw/clipboard","elements":[{"type":"rectangle","version":447,"versionNonce":1515033481,"isDeleted":false,"id":"LgIVMU1GK09urSnsp573s","fillStyle":"hachure","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"angle":0,"x":1632.3254468253967,"y":217.28174603174602,"strokeColor":"#000000","backgroundColor":"#ced4da","width":47,"height":124,"seed":350337065,"groupIds":[],"roundness":null,"boundElements":[{"type":"text","id":"nj5blpVk7GlsP6nCquF_X"}],"updated":1674196910680,"link":null,"locked":false},{"type":"text","version":335,"versionNonce":1773012359,"isDeleted":false,"id":"nj5blpVk7GlsP6nCquF_X","fillStyle":"cross-hatch","strokeWidth":1,"strokeStyle":"solid","roughness":1,"opacity":100,"angle":0,"x":1640.8254468253967,"y":222.28174603174602,"strokeColor":"#000000","backgroundColor":"#fab005","width":30,"height":70,"seed":285322535,"groupIds":[],"roundness":null,"boundElements":[],"updated":1674196910680,"link":null,"locked":false,"fontSize":28,"fontFamily":1,"text":"\ud83d\n\ude03","baseline":60,"textAlign":"center","verticalAlign":"middle","containerId":"LgIVMU1GK09urSnsp573s","originalText":"😃"}],"files":{}}
```

(btw, it is not the same object, but "similar one")
</details>

**Comment by dwelle** [comment]
This looks like a bug with text wrapping and multibyte codepoints!

**Comment by szpak** [comment]
Cool @dwelle! In my case people were just entering the shared canvas (and probably for some browsers there was not enough space for rendering) and I didn't think it might be so easy to reproduce :-).

**Comment by ad1992** [comment]
closing this via https://github.com/excalidraw/excalidraw/pull/6153
