### ISSUE TITLE
In ImageExportModal ExportButton text(PNG, SVG) not alined correctly on Ipad 

### ISSUE THREAD

**Issue by Nishant-l** [excalidraw/excalidraw#6147]
![IMG_255B5EDA1B7A-1](https://user-images.githubusercontent.com/61119157/213905445-89cd89b8-d67f-407c-80f6-7df7a78d720f.jpeg)

- Using Ipad Air

**Comment by dwelle** [comment]
fixed via https://github.com/excalidraw/excalidraw/pull/6148
