### ISSUE TITLE
 BUG: fuzzy Chinese characters

### ISSUE THREAD

**Issue by scruel** [excalidraw/excalidraw#6171]
**Your environment**
```
SYSTEM INFO:
	Obsidian version: v1.1.9
	Installer version: v0.15.8
	Operating system: Windows 10 Home China 10.0.22000
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: dark
	Community theme: none
	Snippets enabled: 0
	Restricted mode: on
```

**Describe the bug**
Chinese character sometimes can be very fuzzy while adjusting the size of its outer box.

**To Reproduce**
- Click Rectangle
- Draw a Rectangle A
- Double click the center position of A
- Write "基本参数设定"
- Keep changing the size of A

**Expected behavior**
Characters should not be fuzzy.

**Screenshots**
![image](https://user-images.githubusercontent.com/16933298/215421434-a2ef029b-5b26-482c-b8cd-f512f3f56929.png)
![image](https://user-images.githubusercontent.com/16933298/215421453-fb062428-a4f5-44b5-a232-df552f343563.png)
![image](https://user-images.githubusercontent.com/16933298/215421462-982917df-74f9-42e8-a7ac-689c25ea3b49.png)

**Comment by fayeah** [comment]
is it fuzzy? sorry I am not sure :joy:

**Comment by scruel** [comment]
1920x1080 527 mm x 293 mm (23.7")
1920x1080 15.6" LCD (FHD)

**Comment by dwelle** [comment]
I see. Are you using Chrome? I've created a PR attempting to fix this for chromium-based browsers: https://github.com/excalidraw/excalidraw/pull/6186

Test here: https://excalidraw-id3bc1287-excalidraw.vercel.app/#json=47qMGDyfF3arke3jQ6Ixf,EjE80jzDkFO6OHlcjjxLIw
