### ISSUE TITLE
Aligning top left has 0 padding between text and box line

### ISSUE THREAD

**Issue by chrisdoherty4** [excalidraw/excalidraw#6179]
### Description 

When adding text into boxes and aligning the text to one side (anything other than centered) the text pushes right up against the box lines. When the box is resized some padding is added.

**Aligned (before resizing)**

<img width="215" alt="Screen Shot 2023-01-31 at 12 20 44 PM" src="https://user-images.githubusercontent.com/3143682/215848740-5d5b4f55-9769-4499-b1cf-b3ae1b76d1b9.png">

**After resizing**

<img width="206" alt="Screen Shot 2023-01-31 at 12 20 52 PM" src="https://user-images.githubusercontent.com/3143682/215848758-d7474f89-dfd6-4238-a3b8-1847985e28d3.png">

### Environment

MacOS 12
Firefox 102
Excalidraw+

**Comment by ad1992** [comment]
Yes, this  AFAIR is a regression, for other alignments the left/right padding gets removed.
