### ISSUE TITLE
Feature request: create drawing json schema for your configs

### ISSUE THREAD

**Issue by RandomFractals** [excalidraw/excalidraw#618]
see this ticket in keplerGL repo for good reasons why you'd want to do it, if your drawing state config is custom and doesn't use any industry standard formats for it ...

https://github.com/keplergl/kepler.gl/issues/885

**Comment by vjeux** [comment]
I'm not really sure what's the point of having a schema for the internal file format of the file. It seems like it would just makes us move slower. Could you enlighten me?

**Comment by vjeux** [comment]
All the arguments you mentioned are about helping people edit the file with tools. But this is not something we want to support. Only the app/website should edit those files.

**Comment by RandomFractals** [comment]
I think you are still short sighted on that. ok. Let's drop it for now.

You should have good examples, docs, & json schema for your drawing saves, but I am not gonna argue hard about it if you don't see a value in that.

**Comment by RandomFractals** [comment]
> 
> 
> All the arguments you mentioned are about helping people edit the file with tools. But this is not something we want to support. Only the app/website should edit those files.

quick q. re. this bit: so, you don't see devs doing this in vscode with IntelliSense, etc.???

Do let me know so I don't waste my time on trying to set up https://github.com/excalidraw/excalidraw-vscode for devs & I did tell @lipis I don't think you are ready for it yet, but here we are :) ...

**Comment by vjeux** [comment]
My understanding was that you were going to embed excalidraw inside of vscode so that you can draw diagrams within. I didn’t think that you wanted to let people edit excalidraw files as code.

**Comment by vjeux** [comment]
But maybe I misunderstood?

**Comment by RandomFractals** [comment]
I think it should be both if you want to go there
