### ISSUE TITLE
Welcome screen on mobile does not disappear

### ISSUE THREAD

**Issue by merazgasalim** [excalidraw/excalidraw#6184]
Welcome screen on mobile does not disappear and stay on top

**Comment by samifouad** [comment]
also experiencing this problem just today loading it up on my Note 20 phone in Google Chrome

**Comment by ad1992** [comment]
Hmm its a regression introduced in https://github.com/excalidraw/excalidraw/pull/6117

**Comment by ad1992** [comment]
@samifouad @merazgasalim  this should be fixed now

**Comment by samifouad** [comment]
@ad1992 yes it is!! thanks for the fix!! the only other thing I have issue with now is how the menu is cut off on my device while in portrait. seems like UI isn't shrinking like it should. I can make a separate issue for this soon.
![Screenshot_20230202-005311_Chrome.png](https://user-images.githubusercontent.com/6378290/216264307-db4e241d-8ccb-4972-89de-743312390fae.png)

**Comment by ad1992** [comment]
Hey @samifouad sure please create a separate issue for this

**Comment by merazgasalim** [comment]
@ad1992 yes it's fine now. thanks
