### ISSUE TITLE
My library: ability to save drawings to local storage and browse them

### ISSUE THREAD

**Issue by haikyuu** [excalidraw/excalidraw#620]
Something like 
![excalidraw-2020129113118(3)](https://user-images.githubusercontent.com/8558836/73458474-a06db380-4375-11ea-83be-7f8484ed5bdf.png)

**Comment by lipis** [comment]
#583 is doing something similar with the saved ones on the backend.. maybe later we can add this too to the list.

**Comment by lipis** [comment]
Maybe something like this #1543, but storing everything in local storage, we might run out of space.
