### ISSUE TITLE
Exporting scene to SVG breaks numbers written as text  

### ISSUE THREAD

**Issue by oskarlf** [excalidraw/excalidraw#6201]
As written above. When I want to preview an image it changes numbers color to black with a slight sheen. 

![Screenshot from 2023-02-07 11-26-39](https://user-images.githubusercontent.com/120448795/217219907-b7124b2f-8f93-4f95-9ba9-9cd82dea0b05.png)

**Comment by ad1992** [comment]
for me its working fine, @oskarlf can you share the element json so we can reproduce ? (you can copy the element and paste it here)

**Comment by oskarlf** [comment]
Nevermind, I just found out that Debian 11 tends to misinterpret the svg file. When opened in the browser everything works fine.
