### ISSUE TITLE
the problem showed garbled

### ISSUE THREAD

**Issue by Michaela1224** [excalidraw/excalidraw#6203]
When I open the previously saved excalidraw file in obsidian, it always bothers me that there is garble that messes up my original text,
such as 
40 ^NACfZxOrkzAdlUglMiHlQ

40 ^zDkD3JUxpv0dDeieRCps_

1 ^YFAQuSyUQYhGk0uSjsoTo

79 ^d4yZggE7GGtCdUezd-feX

**Comment by ad1992** [comment]
@zsviczian ^
