### ISSUE TITLE
Suggestion: adjusting height and width of a shape separately when multiple shapes selected

### ISSUE THREAD

**Issue by KasparsKursiss** [excalidraw/excalidraw#6205]
I hope I'm note repeating someone, but I could not find any similar suggestion.

When selecting multiple shapes it would be handy to be able to scale them only in their height or width. E.g. when creating a row of lines their height as a group or multiselection can no longer be adjusted, one has to duplicate and re-distribute lines again if one wishes to adjust only their height.

Could this be something others would fine useful and that could be considered for production?

Thanks!

**Comment by ad1992** [comment]
Hey @KasparsKursiss 👋🏻
Could you elaborate on the use case where you want to adjust the dimensions of the shape individually when they are grouped together?

**Comment by KasparsKursiss** [comment]
Hey, Aakansha! In my case I created a horizontal row of vertical lines to use as a grid background for my timeline flowchart ([see here](https://drive.google.com/file/d/1-GY_poWYaD931_lhzBQvePk8Uh8S8Kro/view?usp=sharing)). When I reach a point where I want to exapnd vertically there really are no options but to recreate the grid as opposed to just extending it height while leaving the horizontal spacing intact.

**Comment by dwelle** [comment]
Yeah, definitely on the roadmap. We were actually tracking it way in the past, didn't even realize we closed it: https://github.com/excalidraw/excalidraw/issues/1989

There's a more recent issue we can merge this one into https://github.com/excalidraw/excalidraw/issues/5423

I hope we'll be able to get this done in the upcoming future!
