### ISSUE TITLE
Add /samples or /examples folder with drawings json for devs to try excalidraw ...

### ISSUE THREAD

**Issue by RandomFractals** [excalidraw/excalidraw#621]
see https://github.com/vega/vega-lite/tree/master/examples for example ;)

**Comment by dwelle** [comment]
I'm not sure that having examples as a folder of json files is a good idea because people would need to manually download them and import them to the web app. Better to just have a list of links to scenes hosted on our backend.

**Comment by RandomFractals** [comment]
:) think beyond that. I would like to have it for https://github.com/excalidraw/excalidraw-vscode

**Comment by dwelle** [comment]
Maybe, but then I would this issue (in terms of `json` files) over there.

**Comment by RandomFractals** [comment]
also, it's a good thing to have for testing your drawing web app when you get to set that up ...

so that all known drawings are rendered and don't digress & bugs don't regress as you update your app

**Comment by RandomFractals** [comment]
> 
> 
> Maybe, but then I would this issue (in terms of `json` files) over there.

that's fine, but I think having some samples in your core repo would be best for that ext, desktop app  you want to work on & the rest for devs to see those drawing configs in the core repo first and the satellite app repos can pull from yours for additional test

**Comment by RandomFractals** [comment]
I've seen some good examples other devs posted on dev.to and in other places.

I am just suggesting we catalog them to run tests through and document what's possible with excalidraw already today :)

**Comment by dwelle** [comment]
Yea. But since our schema changes often right now it'd only add burden to keep all the JSON examples up to date. You're thinking too far ahead (sample applies to the JSON-schema issue). Let's wait until Excalidraw matures a bit.

(My opinion.)

**Comment by vjeux** [comment]
I think we should have a gallery with screenshots and optionally links to it. I don’t think it’s necessary to check it in the codebase.

We can start this on the readme

**Comment by RandomFractals** [comment]
> 
> 
> I think we should have a gallery with screenshots and optionally links to it. I don’t think it’s necessary to check it in the codebase.
> 
> We can start this on the readme

that could be a good start. I've seen some good examples on twitter and dev.to 

Let's start there! I am good with taking baby steps on it too :)

**Comment by RandomFractals** [comment]
> 
> 
> Yea. But since our schema changes often right now it'd only add burden to keep all the JSON examples up to date. You're thinking too far ahead (same applies to the JSON-schema issue). Let's wait until Excalidraw matures a bit.
> 
> (My opinion.)

that's just another reason to catalog them and make sure all the drawings created by other devs thus far still work as you iterate on this drawing app prototype. Also, see #623

**Comment by pshihn** [comment]
Don't think this project has a WIKI enabled, but that's a good alternative to keep pages like screenshots/links to samples without polluting the codebase (including readme)

**Comment by RandomFractals** [comment]
either alternative would be fine. I would like to see some good examples or links to them in README.md tho ...

**Comment by lipis** [comment]
If the schema is changing

We can open and re-save them

**Comment by RandomFractals** [comment]
well, actually, you can do even better and version them. again, see how Vega crew does it here: https://github.com/vega/schema

they are pro at that & all I suggest you guys do something similar to set it up for your drawings json config, IntelliSense to kick in in vscode ext. I am gonna give you a hand with, etc.

**Comment by lipis** [comment]
> If the schema is changing
> 
> We can open and re-save them

I have tests in place that changing the snapshots..
