### ISSUE TITLE
changes don't save !

### ISSUE THREAD

**Issue by dumbdreamed** [excalidraw/excalidraw#6219]
hi, i keep getting this error and i  can't save anything.
![image](https://user-images.githubusercontent.com/64626106/218252265-ae7e22a6-6d29-40b8-9e7b-1a7d8e00f4e6.png)

**Comment by LukaHietala** [comment]
Save the image and clear the Excalidraws cache. If that doesn't work, clear your entire browser cache. What is your browser by the way

**Comment by dumbdreamed** [comment]
Thanks for answering, how I can clear the excalidraw cache? my browser is edge

**Comment by LukaHietala** [comment]
> Thanks for answering, how I can clear the excalidraw cache? my browser is edge

I am showing how to do that in chrome, but it works the same way on Microsoft Edge

[Screen recording 2023-02-11 14.52.28.webm](https://user-images.githubusercontent.com/95122845/218259138-8d378546-006a-4cb3-aa30-13a0e15882fd.webm)

**Comment by dumbdreamed** [comment]
I really appreciate it but I have this problem with obsidian, I'm using excalidraw plugin on obsidian. thanks again for your help so far my friend

**Comment by LukaHietala** [comment]
This might be a bug with the Obsidian plugin so I can't really help any futher

**Comment by dumbdreamed** [comment]
you're amazing my friend,really appreciate it
