### ISSUE TITLE
Standardize on drawing .json file name extension

### ISSUE THREAD

**Issue by RandomFractals** [excalidraw/excalidraw#622]
Most dev tools don't invoke plugins based on generic .json configs and if they do, it's just bad by design & UX/XD in general for custom configs like this.

I propose you switch to calling your drawing configs `*.draw.json` || something along those lines to remedy that.

Related: #618

**Comment by RandomFractals** [comment]
Or we can call theme `.scene.json` since I've seen you call your drawings scenes in most tickets in this repo.

I would prefer `.draw.json` since it jives well with your tool name, also not to be confused with draw.io ;) ...

**Comment by dwelle** [comment]
Or we can go full steam ahead and use `.excalidraw.json`.

**Comment by RandomFractals** [comment]
`.excalidraw.json` is a bit too long and wordy for a file ext. name.

Let's just go with `.draw.json` & show draw.io how it's done??? :)

**Comment by RandomFractals** [comment]
also, as a side note: no good drawing apps in VS marketplace yet ...

https://marketplace.visualstudio.com/search?term=draw&target=VSCode&category=All%20categories&sortBy=Relevance

**Comment by dwelle** [comment]
That said, it's not really an extension, just a suggested name (anything left of the last `.` is a name).

**Comment by RandomFractals** [comment]
there are some whiteboard ext's ... https://marketplace.visualstudio.com/search?term=whiteboard&target=VSCode&category=All%20categories&sortBy=Relevance

**Comment by RandomFractals** [comment]
yeah, I know. just sandbagging for out bit to help you guys bring it into vscode ...

**Comment by RandomFractals** [comment]
let's do this. I am gonna map it to `.draw.json` to activate your whiteboard webview in the vscode ext. I am setting up. We can regroup on this once we got some canvas there to work with ;)

**Comment by vjeux** [comment]
If you are going to map it to an extension, let's use `.excalidraw` or `.exca` and drop the json altogether. Let's not use `.draw` as it's very generic.

**Comment by RandomFractals** [comment]
`.exca` is so cryptic. Let's give other devs some time to think about this.

meanwhile, here is a short outline of features I think we can target with that ext.:

https://github.com/excalidraw/excalidraw-vscode/issues/1#issuecomment-580784841

I am adding a refined v. of that list to that repo docs now.

**Comment by dwelle** [comment]
```
.excalidraw
.draw.json
```

Your original suggestion is one char shorter, granted :).

**Comment by RandomFractals** [comment]
:) yeah, I just think we should dream big & your logo has a pen & a sword. both tools I like to draw with ...

I think you can be bold with the devs backing you got so far & take that `.draw` file ext. name & own it!

The `excali` bit was clever branding. I am just thinking why not build on that & compete with draw.io & Figma eventually since based on some open tickets in this repo sounds like you are going to end up there eventually ...

**Comment by RandomFractals** [comment]
also, just prepending your custom file ext. to .json simplifies on many fronts in terms of tooling & trust me I've done it a few times before, so I'd suggest you consider that 'tooling' scenario for online tools, gists & others that do support .json code formatting etc. & just add .draw to it ...

**Comment by RandomFractals** [comment]
@dwelle we can meet at cam03 on your gitter || twitter if you want to chat more about it ...

However, I am about to draw my katana out on that vscode ext. scaffold for you guys ...

So, I do need to know if you are onboard with better docs, samples, json schema & your drawings json file naming before we proceed further.

I do have a few ideas on how you can improve your rendering perf. too, but we can leave it for another day

**Comment by RandomFractals** [comment]
all in favor of `.draw.json` say yay! || put some thumbs up on this & let's move on to fry bigger fish so to speak :) ...

**Comment by lipis** [comment]
I would also go for `.excalidraw`, `draw` is too generic..

**Comment by RandomFractals** [comment]
@lipis ... `I'd suggest you consider that 'tooling' scenario for online tools, gists & others that do support .json code formatting etc. & just add .draw to it ...`

**Comment by RandomFractals** [comment]
even tho I think excalidraw term is unique & cool, I do want you to consider your drawing json specs previews in online tools & elsewere down the road. many have gone down this rabbit hole before.

let's just sleep on it for another day or two. btw, #drawJSON is ripe for taking on Twitter ;)

Cheers!

**Comment by vjeux** [comment]
Let's use `.excalidraw` as a file extension. Even though it is long, it is unique and unlikely to conflict.

**Comment by RandomFractals** [comment]
fine! I'll use drawJSON for some other drawing app.
