### ISSUE TITLE
Excalidraw's Codesandbox isn't opening 

### ISSUE THREAD

**Issue by LukaHietala** [excalidraw/excalidraw#6220]
When you try to open Excalidraw's github repository in Codesandbox it gives an error message "Only a max of 500 modules is allowed in a sandbox"
> https://docs.excalidraw.com/docs/introduction/contributing#option-2---codesandbox

![image](https://user-images.githubusercontent.com/95122845/218255639-5b9ac316-3dbe-4d07-ada4-c2cfb60f8a98.png)

**Comment by LukaHietala** [comment]
I can create a PR that removes Codesandbox option from the docs if needed :)

**Comment by dwelle** [comment]
That's actually an old link. The new Cloud Codesandbox doesn't have that limitation, which we link to from the Development page: https://docs.excalidraw.com/docs/introduction/development#code-sandbox

You can certainly create a PR to align the Contributing page with the latest!
