### ISSUE TITLE
EncryptedIcon does not re-render on language change

### ISSUE THREAD

**Issue by Brikaa** [excalidraw/excalidraw#6222]
![image](https://user-images.githubusercontent.com/40431124/218275850-d6dccce3-2e2a-4063-9242-bbeb741d6f06.png)

**Comment by LukaHietala** [comment]
There are also many other parts of the UI that don't re-render after the language change

![image](https://user-images.githubusercontent.com/95122845/218280954-9c30f2ac-4ce5-4874-83e0-8b50548d435b.png)

**Comment by LukaHietala** [comment]
Now this is really strange.. The link to the text is wrapped around with the i18n `t` function which updates all the text inside to the translated one when language is changed, but it doesn't seem to do it really well on some places.

![image](https://user-images.githubusercontent.com/95122845/218282731-eea4d93f-94e4-45f9-a0e2-1fe94463badb.png)

**Comment by Brikaa** [comment]
The main problem is that "t" is used inside and outside of components. So we can't directly use a hook that gets the t and causes a re-render when it updates.

The current solution they have, according to my understanding, is to put the lang code in a Jotai atom that is used by the App parent component, update this atom from the language selection component (this causes a re-render in the parent App component), detect when the App component re-renders and update the language in i18n (the module responsible for providing "t") if the language is changed.

However, the problem with that is that some children components do not re-render because of children props or memoization. In that case, they do a hack, which is to make these children use the appState context. I think they update this appState context whenever the language changes. This way the children components re-render.

But everytime they do that, they comment above it saying that this is a hack that should be fixed. This is why I haven't opened a pull request.

This bug could be fixed by doing useAppState() in the footer component thing.

**Comment by dwelle** [comment]
@Brikaa correct. Fixed in https://github.com/excalidraw/excalidraw/pull/6224
