### ISSUE TITLE
Create CHANGELOG.md and start publishing release notes

### ISSUE THREAD

**Issue by RandomFractals** [excalidraw/excalidraw#623]
& releases with version numbers and quick recap for your updates and sprints

**Comment by bashbsc** [comment]
![EEE70B14-334E-44D5-9A13-9667B64FCE21](https://user-images.githubusercontent.com/60822169/74088997-a0b82e00-4a9c-11ea-9c92-7a7671eb0234.jpeg)

**Comment by bashbsc** [comment]
Beautiful

**Comment by vjeux** [comment]
This would be great indeed. I don't think we need an issue to track it though, I'm going to close it.
