### ISSUE TITLE
Dark theme looks weird (brown/orange bg) in "Eye Care" mode due to the HUE rotate and inverted colors

### ISSUE THREAD

**Issue by LukaHietala** [excalidraw/excalidraw#6233]
I can't take a screenshot of it because it's a display setting, but the issue title explains the problem. There probably isn't a way to fix this so I am just noting it here

**Comment by Rajdave69** [comment]
Well that's not really an issue with excali. It looks perfect in the conditions it's supposed to be viewed in. Try turning down the eye care mode's strength

**Comment by LukaHietala** [comment]
It's issue with just my own Chromebook so I will close this
