### ISSUE TITLE
Add dev posts using excalidraw to docs to demo what's possible

### ISSUE THREAD

**Issue by RandomFractals** [excalidraw/excalidraw#624]
I've seen some good examples other devs posted on dev.to and in other places.

I am just suggesting we catalog them to run tests through and document what's possible with excalidraw already today :)

_Originally posted by @RandomFractals in https://github.com/excalidraw/excalidraw/issues/621#issuecomment-580331285_

**Comment by lipis** [comment]
we have a blog now and the how to.. we just need to improve them :)
