### ISSUE TITLE
npm page WelcomeScreen overview images broken

### ISSUE THREAD

**Issue by arrickx** [excalidraw/excalidraw#6242]
npm page [WelcomeScreen overview](https://github.com/excalidraw/excalidraw/blob/HEAD/welcome-screen-overview.png) images broken

https://www.npmjs.com/package/@excalidraw/excalidraw?activeTab=readme

**Comment by ad1992** [comment]
Hey @arrickx what do you mean by the welcome screen overview is broken? 

It is working fine in the examples - https://docs.excalidraw.com/docs/@excalidraw/excalidraw/api/children-components/welcome-screen 
Or do you mean in some particular case  its broken ?

**Comment by arrickx** [comment]
![16CD464C-6016-4152-8594-221570837718](https://user-images.githubusercontent.com/24638167/219131952-49ec79c6-cd91-4734-81e8-61c94c9d3834.png)

sorry for using the phone screen shoot.
I’m referring to the excalidraw in the npm package page. https://www.npmjs.com/package/@excalidraw/excalidraw

**Comment by LukaHietala** [comment]
> ![16CD464C-6016-4152-8594-221570837718](https://user-images.githubusercontent.com/24638167/219131952-49ec79c6-cd91-4734-81e8-61c94c9d3834.png)
> 
> sorry for using the phone screen shoot. I’m referring to the excalidraw in the npm package page. [npmjs.com/package/@excalidraw/excalidraw](https://www.npmjs.com/package/@excalidraw/excalidraw)

The welcomeScreen overview image is missing from the Github repo for some reason

**Comment by ad1992** [comment]
Ahh ok, we have moved our official docs to [docs.excalidraw.com](https://docs.excalidraw.com/) so please refer to that. As per the npm package, we will be soon remove it from package readme and package readme would just contain [this](https://github.com/excalidraw/excalidraw/blob/master/src/packages/excalidraw/README.md)

**Comment by arrickx** [comment]
thanks！
