### ISSUE TITLE
Feature request: To enable and disable "read only" on live collaboration.

### ISSUE THREAD

**Issue by GaganGopi** [excalidraw/excalidraw#6245]
Hello team,

It would be great to have the functionality on the application to lock the whiteboard during live collaboration allowing only one user to draw/make changes on the Whiteboard and at the same time to be able to enable it allowing others to join.

I'm not sure if functionality already exists and if it does could you add references to it please.

**Comment by dwelle** [comment]
Hi!

On excalidraw.com, collaboration rooms are edit-only. But we have read/write collab links in [Excalidraw+](https://plus.excalidraw.com).

No plans to add similar things to excalidraw.com as without authentication it'd not be very easy, and require complicating the flow for collaboration — we want to keep the excalidraw.com simple.
