### ISSUE TITLE
split canvas rendering

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#6262]
For performance reasons, we should have at least 2 `<canvas>` elements:

1. one for elements (shapes) themselves. Sitting below.
2. one for UI things, such as selection/bounding boxes, remote client cursors, etc. Sitting above.

UI-related things change more often than elements, which affects performance in hot paths such as displaying remote client cursors on movement.

**Comment by rahul3v** [comment]
exploring the options :)

**Comment by 7flash** [comment]
a beginner question: why do we need canvas when using svg elements?

**Comment by dwelle** [comment]
@7flash for export, not necessarily, but we'll need to properly decouple the SVG renderer from the canvas. For editing purposes, Excalidraw currently doesn't support SVG-only renderer, although it's also a possibility to add in the future.
