### ISSUE TITLE
Feature request: Customizable shortcuts

### ISSUE THREAD

**Issue by dimateos** [excalidraw/excalidraw#6275]
There are a bunch of issues related to user preferences/needs on hotkeys (#6228, #5380...)

A general solution would be to offer the option to change them individually.

**Comment by nttldnknwn** [comment]
+1, the ability to customize hotkeys for tools is really lacking

**Comment by Mrazator** [comment]
Let's track it here https://github.com/excalidraw/excalidraw/issues/3852
