### ISSUE TITLE
Getting blank screen after every stroke on ipad obsidian.

### ISSUE THREAD

**Issue by sugarrat** [excalidraw/excalidraw#6278]
I am trying to upload a video of the issue but it's too large to upload.
Anyway, I'm using excalidraw through obsidian plugin.  The screen goes black after every stroke or shape.  
Anyone encountered this before?

**Comment by ad1992** [comment]
cc @zsviczian ^

**Comment by ad1992** [comment]
closing this as this is related to Obsidian
