### ISSUE TITLE
Ability to toggle the fixed container while editing

### ISSUE THREAD

**Issue by harshsinghatz** [excalidraw/excalidraw#6281]
- Sometimes it is annoying that i cannot get rid of the fixed container on the left while adding objects on the canvas
![image](https://user-images.githubusercontent.com/51085015/221366310-f5722998-73c1-4bba-8b2b-16a97b28251d.png)

Solution:
1. Add a toggle button above the container for visibility

**Comment by dwelle** [comment]
Hi. Doesn't the zen mode (opts/alt-z) solve this?

**Comment by dwelle** [comment]
Closing as duplicate of https://github.com/excalidraw/excalidraw/issues/6257

**Comment by harshsinghatz** [comment]
@dwelle Thanks, Didn't knew that should've waited before creating a PR. my bad!
