### ISSUE TITLE
Shapes are broken after a certain amount of shapes

### ISSUE THREAD

**Issue by abdelouahabb** [excalidraw/excalidraw#6284]
If you keep adding icons to libraries, icon text will be broken :

Before :
![before](https://user-images.githubusercontent.com/2527234/221403556-8c8cb006-9419-416b-955a-845e6eba605a.png)

After : 
![after](https://user-images.githubusercontent.com/2527234/221403568-e8f93b26-5ad0-45fb-9aa8-8edde2f572a4.png)

**Comment by dwelle** [comment]
This actually seems like an SVG rendering regression introduced in https://github.com/excalidraw/excalidraw/pull/6187

/cc @ad1992
