### ISSUE TITLE
Ability to quickly change fill / stroke color with a keyboard shortcut

### ISSUE THREAD

**Issue by emilsjolander** [excalidraw/excalidraw#631]
I would love the ability to quickly change the color of an element using keyboard shortcuts. Currently I need to click around a lot of UI element to get the correct color and then I need to click around the UI again to revert back to the previous color which new elements default to.

I would love the ability to press on an element and then invoke a keyboard shortcut (perhaps`c`) to bring up a color palette picker and then user arrow keys to selected a color and enter to commit to it. This would only change the color of the selected element and not the default color of future elements.

**Comment by vjeux** [comment]
This is a good idea!

**Comment by lipis** [comment]
Or just go through the colors, a shortcut for next color (`j`) and for previous one (`k`) like in GMail for going through emails.

**Comment by vjeux** [comment]
#647 implements arrow keys + keybinding for the color palette

**Comment by j-f1** [comment]
Is this fixed?

**Comment by vjeux** [comment]
The hardest part is fixed: selecting a color via the keyboard. But still need a keybinding to open the color picker itsekr

**Comment by dwelle** [comment]
fixed in https://github.com/excalidraw/excalidraw/pull/3318
