### ISSUE TITLE
Support the translation for Thai language

### ISSUE THREAD

**Issue by ayuthmang** [excalidraw/excalidraw#6311]
The project doesn't open support translation for the Thai language.

This issue is intended to open the translation for the Thai language at https://crowdin.com/project/excalidraw.

**Comment by dwelle** [comment]
https://crowdin.com/translate/excalidraw/10/en-th?filter=basic&value=0 🙏

**Comment by dwelle** [comment]
using `ภาษาไทย` for the [language picker](https://github.com/excalidraw/excalidraw/pull/6314/files#diff-da3684dd2522d9766b6b02310ffa7bf5e68c24a9f0dc3b8b814f03d10dd34babR164), lemme know if there's a better expression!
