### ISSUE TITLE
Text alignment of Arrow doesn't work.

### ISSUE THREAD

**Issue by TIshow** [excalidraw/excalidraw#6316]
Text alignment of Arrow doesn't work below. It depends on the width of textbox.

<img width="733" alt="Screenshot 2023-03-05 at 19 12 43" src="https://user-images.githubusercontent.com/29755556/222954344-8301117c-6e5f-456e-895a-067f1a2712c7.png">

**Comment by ad1992** [comment]
We don't support the alignments for arrow labels as right now it will align only with respect to the dimensions of the text bounding box. 

<img width="438" alt="Screenshot 2023-03-06 at 11 17 47 AM" src="https://user-images.githubusercontent.com/11256141/223028911-4218e4a9-c0e8-4875-9f8a-7b50bd4868bf.png">


Probably we should hide it unless we explicitly support it.

@TIshow how would you expect it to align? the text should move to the extreme left / right of the arrow. 

Though I still think the `text align` property might not be useful for arrow labels as users wouldn't want to move the text to the extreme left. right of the arrow hopefully? But vertical align would be definitely useful to move the labels above / below the arrow.

**Comment by TIshow** [comment]
> We don't support the alignments for arrow labels as right now it will align only with respect to the dimensions of the text bounding box.
> 
> <img alt="Screenshot 2023-03-06 at 11 17 47 AM" width="438" src="https://user-images.githubusercontent.com/11256141/223028911-4218e4a9-c0e8-4875-9f8a-7b50bd4868bf.png">
> 
> Probably we should hide it unless we explicitly support it.
> 
> @TIshow how would you expect it to align? the text should move to the extreme left / right of the arrow?
> 
> Though I still think the `text align` property might not be useful for arrow labels as users wouldn't want to move the text to the extreme left. right of the arrow hopefully? But vertical align would be definitely useful to move the labels above / below the arrow.

I'm referencing source code of Excalidraw currently. It is needed to horizontally align the text on Arrow for me, therefore I tried to modify minimun width of textbox for arrow text.
But it would occur several lame things, for instance, expanded textbox hide the arrow. 

In my opinion, horizontally text alignment for arrow labels is not necessary so far. It should be hidden unless supported it in terms of usability and UX.
 On the other hand, vertical align is useful as you mentions.

**Comment by ad1992** [comment]
Yep I will hide the horizontal text align
