### ISSUE TITLE
Text wrapping issue in containers

### ISSUE THREAD

**Issue by zsviczian** [excalidraw/excalidraw#6318]
https://user-images.githubusercontent.com/14358394/222958110-806dfd5a-702a-4a12-80fa-74cbdac35705.mp4

**Comment by ad1992** [comment]
@zsviczian I am not able to reproduce it, Can you export the element as a link or paste the element ? so I can check

**Comment by zsviczian** [comment]
I can't get my finger on the issue. It seems as if the problem is device and browser dependent. On my MacBook using Chrome the issue is definitely there.  On my windows laptop using Edge I was not able to reproduce the issue. In Obsidian on my laptop the issue is there, on my desktop not... 

Thus I don't have a clear cut process for you how to reproduce the issue. 
- I simply create a rectangle,
- type a few words,
- then shift drag to enlarge the rectangle and the text,
- then delete and edit the text... and sometimes it starts to do this.
 
It seems as if text alignment also had an effect on this, but I might be hallucinating. It seems to start when I switch to center alignment. But can't say for sure. It also depends on words and letters you type. In one case typing "Test text" jumped around, but typing "Why text" in the same sticky note was stable. 

This drawing jumps for me on my MacBook in Chrome, but does not on the same MacBook with Safari. I tried opening the drawing multiple times and the effect is reliably there (and not there)...
https://excalidraw.com/#json=zWiy8lavNX0u2YatAye4p,jIYDDz7GDjFETyS6nvlXSQ

https://user-images.githubusercontent.com/14358394/223180496-633c39cd-5a7e-4e1c-84fc-99aaea592f9c.mp4

**Comment by zsviczian** [comment]
I can't reproduce the issue with Chrome, Edge, or Firefox on Windows 11.

**Comment by zsviczian** [comment]
Similar to the previous example this example produces the same error in Chrome MacOS, but not Safari MacOS or Chrome, Edge, Firefox Windows 11 or Edge Windows 10. However, unfortunately, with this image, the error is present in all Obsidian versions regardless of operating system

https://excalidraw.com/#json=MRsjneUy5gIRKcIdLtNhR,RYoXFMds9L_nubHEPEWdSw

**Comment by zsviczian** [comment]
Chrome on my Samsung S23 ultra produces this result

https://user-images.githubusercontent.com/14358394/223191352-fae3a249-3e1e-428f-964d-c7533d5e456d.mp4

**Comment by zsviczian** [comment]
Finally Obsidian on iOS as well as Edge on iOS produces no errors using this demo image.
Apologies for the many replies, I was adding replies from different devices (5 in total) as I try to get to the bottom of the issue.

My conclusion is that there is definitely some problem with the new text measurements as it is causing errors on some devices not only in Obsidian but using excalidraw.com

**Comment by ad1992** [comment]
> Finally Obsidian on iOS as well as Edge on iOS produces no errors using this demo image. Apologies for the many replies, I was adding replies from different devices (5 in total) as I try to get to the bottom of the issue.
> 
> My conclusion is that there is definitely some problem with the new text measurements as it is causing errors on some devices not only in Obsidian but using excalidraw.com

@zsviczian is this when using shift + resize or just resize ?
If it's related to shift resize then it might be related to scaling the font size. We are disabling it for bound text containers  to align with other apps so in case it's related to shift resize, can you try out if its reproducible in https://github.com/excalidraw/excalidraw/pull/6298 ?

**Comment by zsviczian** [comment]
The issue was introduced with #6187

https://user-images.githubusercontent.com/14358394/223199902-e40e40b6-b245-46c4-9e81-1f71ea0aad8a.mp4

**Comment by ad1992** [comment]
> > Finally Obsidian on iOS as well as Edge on iOS produces no errors using this demo image. Apologies for the many replies, I was adding replies from different devices (5 in total) as I try to get to the bottom of the issue.
> > My conclusion is that there is definitely some problem with the new text measurements as it is causing errors on some devices not only in Obsidian but using excalidraw.com
> 
> @zsviczian is this when using shift + resize or just resize ? If it's related to shift resize then it might be related to scaling the font size. We are disabling it for bound text containers to align with other apps so in case it's related to shift resize, can you try out if its reproducible in #6298 ?

@zsviczian reminder incase you missed, could you please confirm on the above ?

**Comment by zsviczian** [comment]
@ad1992, in [this specific case](https://excalidraw.com/#json=MRsjneUy5gIRKcIdLtNhR,RYoXFMds9L_nubHEPEWdSw), adding an offset of 30 almost solves the issue... of course, this means that the textElementWidth and viewportX calculations are offset for some reason, though I don't see why since that part of the code did not change.

```typescript
      Object.assign(editable.style, {
        font: getFontString(updatedTextElement),
        // must be defined *after* font ¯\_(ツ)_/¯
        lineHeight: `${lineHeight}px`,
        width: `${textElementWidth+30}px`,
        height: `${textElementHeight}px`,
        left: `${viewportX-30}px`,
```

https://github.com/excalidraw/excalidraw/blob/8542c95a7a2b30d88b9a4f71867651fe60a4c7da/src/element/textWysiwyg.tsx#L283-L290

**Comment by zsviczian** [comment]
see my initial solution proposal #6326. I am not fully comfortable with the solution, but it works... and it is similarly messy as your current code:

```typescript
     } else if (isFirefox || isSafari) {
        // As firefox, Safari needs little higher dimensions on DOM
        textElementWidth += 0.5;
      }
```

BTW with this change the above can be removed from the code.

**Comment by ad1992** [comment]
@zsviczian can you try out in #6328 and let me know if it works well ?
