### ISSUE TITLE
data failed to load

### ISSUE THREAD

**Issue by quachtrung** [excalidraw/excalidraw#6358]
i can't open previously logged data on default browser, white screen and loadi sign occurs but data is not restored

**Comment by ad1992** [comment]
@quachtrung please confirm if this happens on [excalidraw.com](https://excalidraw.com) ? Also did you by mistake clear the data and then refreshed ? Or had multiple tabs one of which was cleared ?

**Comment by dwelle** [comment]
closing as not enough informatin
