### ISSUE TITLE
Exporting to Excalidraw+ from Excalidraw Web executes but does Nothing

### ISSUE THREAD

**Issue by Insighttful** [excalidraw/excalidraw#6366]
When signed in to Excalidraw + and selecting Export to Excalidraw + from the web standard Excalidraw account nothing happens. 

No new scene or any indications of anything transferring is shown in the Excalidraw+ account.
![image](https://user-images.githubusercontent.com/116014557/225931246-1d529525-8fc5-4d42-aa4a-8aa0754f66f8.png)

**Comment by dwelle** [comment]
This is strange, we're not tracking any issues with this. Can you check if there are any errors anywhere during the process when you open the developer console (`Opt-Cmd-I` on Mac, or `Ctrl-Shift-I` on Windows). Does What are you seeing exactly?

Does it redirect you to `https://app.excalidraw.com` website, or clicking the button basically doesn't do anything?
