### ISSUE TITLE
All text Invisible when Importing .excalidraw File exported from Excalidraw Web (Free) to Excalidraw +

### ISSUE THREAD

**Issue by Insighttful** [excalidraw/excalidraw#6367]
The goal is to transfer work from Excalidraw Web (free version) to Excalidraw +. Since the transfer option does not work #6366, I attempted to save the scene as a file and import into Excalidraw +.

Upon import all text is invisible. The only way to get it to show is to exhaustively go through every element and double click the text. This is extremely time consuming, and it is hard to remember where the text was in the original file (since it is now invisible.)

![image](https://user-images.githubusercontent.com/116014557/225933241-d59cff78-d1a1-4608-85d8-0f3850136a55.png)

Between #6366 and this issue, these feel like insurmountable blockages for a smooth transition to the paid version.

**Comment by dwelle** [comment]
Hello. Yes, we're aware of this, and it's due to the Excalidraw+ purposely being on a slightly older version right now. It should be fixed in the coming days.

Note, you can still reloading the tab (after the changes are saved) should automatically fix this, too!
