### ISSUE TITLE
layout shift when editing a Text 

### ISSUE THREAD

**Issue by sedghi** [excalidraw/excalidraw#6380]
See below. It is tiny, but certainly annoying

https://user-images.githubusercontent.com/7490180/226419219-99cc2653-39e5-4efa-a831-b4148121892b.mp4

**Comment by dwelle** [comment]
Looks like a regression introduced in https://github.com/excalidraw/excalidraw/pull/6187 /cc @ad1992

**Comment by ad1992** [comment]
@sedghi can you test in https://excalidraw-git-aakansha-baseline-excalidraw.vercel.app/ if its working fine ?
