### ISSUE TITLE
Document `Enter` to edit shape text

### ISSUE THREAD

**Issue by OldStarchy** [excalidraw/excalidraw#6393]
The help menu (`Shift` `/`) lists `Ctrl` `Enter` as the shortcut to edit an element's text, however, the actual shortcut is just `Enter`.

See #6386

**Comment by dwelle** [comment]
Oh, our mistake! Must be because we've recently changed how editing a line works (Enter -> Ctrl+Enter) but forgot to split it in the help menu. Do you want to make a PR?

**Comment by OldStarchy** [comment]
Yes :) I'll find some time to do it over the next few days

**Comment by fouqueta** [comment]
Hi. Is the issue fixed? I will work on this today.

**Comment by dwelle** [comment]
Feel free to take it on @fouqueta! :)
