### ISSUE TITLE
missing user tools

### ISSUE THREAD

**Issue by utopicchaotica** [excalidraw/excalidraw#6401]
In the video for the latest reason, there is a "user" tools section in the popup menu, but I don't see it in mine. Kind of a problem cuz I can't use the new invert colours feature :(

<img width="233" alt="image" src="https://user-images.githubusercontent.com/1484231/228614526-7e371b46-cf90-4527-a3fc-007cfa5e91e3.png">

**Comment by dwelle** [comment]
Hi! This issue relates to the obsidian integration, so best to create it there: https://github.com/zsviczian/obsidian-excalidraw-plugin/issues 🙏
