### ISSUE TITLE
Add support for fixed width text boxes with text wrapping

### ISSUE THREAD

**Issue by petarkolaric** [excalidraw/excalidraw#6402]
Hi there!

This ticket is for a feature request:

Add support for fixed width text boxes with text wrapping.

I use Excalidraw+ a fair bit for fleshing out ideas, and making sure I understand problems I am trying to solve. Part of this process involves writing text around my diagrams with notes and bits of information. Excalidraw does not support wrapping for text boxes, so to put my text over multiple lines I need to insert a bunch of newlines into my text. This is annoying when I want to resize the width of the section, or when I want to copy the text out to another application. It also gets in the way of my flow of getting ideas onto the page.

Thanks :)

**Comment by dwelle** [comment]
Hi! This is on the roadmap.

Until then, you can use text container: create a rectangle, and hit `Enter` or double-click on it. 

![excal-text-containers-showcase](https://user-images.githubusercontent.com/5153846/228773480-53c5d2e5-87f1-4fac-b5f8-9774358c4d50.gif)

There's also a hacky workflow to make the container invisible if you need that:

1. select the container and set stroke to `transparent` (this will make both the container and text invisible)
2. enter/double-click to edit text, and set its stroke color back to black

Better workflow for this is coming.

**Comment by petarkolaric** [comment]
Oh, that's actually a pretty good workaround. I'll use it until the resizable text box comes out. Thanks!

**Comment by GetPsyched** [comment]
I stumbled onto wanting this feature as well. Has this come out yet?
