### ISSUE TITLE
Grid Mode doesn't work

### ISSUE THREAD

**Issue by Reiquem** [excalidraw/excalidraw#6405]
My grid Mode doesn't even activate ! is it just me ?

**Comment by ad1992** [comment]
@Reiquem whats your OS and Browser version ?

**Comment by Reiquem** [comment]
Windows 10. I tried on chrome, mozilla firefox and opera gx

**Comment by dwelle** [comment]
What steps do you take to activate it, context menu or a shortcut? What does happen — any console errors (`opt-cmd-I` on mac or `ctrl-shift-I` on windows)?

**Comment by dwelle** [comment]
Closing as not enough info.
