### ISSUE TITLE
TypeError: Cannot use 'in' operator to search for 'filter' in null

### ISSUE THREAD

**Issue by lmvet-ct** [excalidraw/excalidraw#6406]
Hi, 

When trying to render <Excalidraw  /> with react testing library I get this error  "TypeError: Cannot use 'in' operator to search for 'filter' in null". 

any advice would be greatly appreciated.

Thank you 

![image](https://user-images.githubusercontent.com/116560541/229138564-88fd76e2-3a6b-4a85-b10e-37ce350beb3f.png)

**Comment by dwelle** [comment]
Hi. What do you do exactly, run tests (`yarn test`)?

**Comment by lmvet-ct** [comment]
yes, just yarn test

![image](https://user-images.githubusercontent.com/116560541/229449701-5b2cd173-9e48-4f21-9d25-f3db544ec83c.png)

**Comment by dwelle** [comment]
What's your node version and yarn version?

**Comment by lmvet-ct** [comment]
yarn version: 1.22.19
node version: 19.6.0

**Comment by lmvet-ct** [comment]
I have also tried node versions 14, 16 and 18
