### ISSUE TITLE
[Bug] Tooltip show up in weird font

### ISSUE THREAD

**Issue by thesobercoder** [excalidraw/excalidraw#6408]
As illustrated by the image below, the tooltips are showing in a font inconsistent with the rest of the application;

![Untitled](https://user-images.githubusercontent.com/1915249/229303156-5d2b2e1b-7bd7-42b4-800e-2aae1a958c4c.png)

**Comment by ad1992** [comment]
@thesobercoder this should be fixed via https://github.com/excalidraw/excalidraw/pull/6501
feel free to reopen if it still persists
