### ISSUE TITLE
support wrapping multiple text elements into container at once

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#6418]
The context menu (right click) action of wrapping a text element in a container should work when multiple text elements selected.

I'd also spread out the element if necessary to make them fit without overlap if containerizing would make them not to.

**Comment by ChinmayMhatre** [comment]
Hey sorry, could you give maybe a brief on how I could make this work and what is expected again. I'd love to work on this. I am trying to understand the codebase since I am new to the project, would appreciate any help!

**Comment by ad1992** [comment]
Hey @ChinmayMhatre we support wrapping a single text element in a container via context menu as shown 👇
https://user-images.githubusercontent.com/11256141/230020907-fc8fbdbd-a33c-463b-9be2-2b9fa40b9603.mp4

Now we want to support wrapping multiple text elements in a container via context menu.

**Comment by ChinmayMhatre** [comment]
> Hey @ChinmayMhatre we support wrapping a single text element in a container via context menu as shown 👇 https://user-images.githubusercontent.com/11256141/230020907-fc8fbdbd-a33c-463b-9be2-2b9fa40b9603.mp4
> 
> Now we want to support wrapping multiple text elements in a container via context menu.

Got it! Could you maybe point to where I could start this from or any resource. I am having a bit of trouble understanding the codebase but I really wanna contribute, it would be awesome if you could help me out a bit.

**Comment by dwelle** [comment]
Here's the action that takes care of wrapping the single text element:

https://github.com/excalidraw/excalidraw/blob/d61b3cf83d0a6f174abc27e0e4f5ca5cc6725fdd/src/actions/actionBoundText.tsx#L182-L292

You'll want to update the `predicate` to allow for multiple text elements. And then modify the `perform` function to handle multiple elements.

**Comment by kr-abhi55** [comment]
hey, i want to work on this issue and i'm new to this project

**Comment by priyanshu-kun** [comment]
@dwelle If I'm not wrong, the solution wants to wrap multiple text elements in a single container. When we select multiple texts and right-click them to wrap them into a container, the drawer should suggest a working option to choose is `wrap texts in container` and when we click on that option, should text wrap in a container together?

![Group 1(3)](https://user-images.githubusercontent.com/57032769/230550148-7580e4b1-31db-4e68-8446-315c6f97266b.png)
