### ISSUE TITLE
Add issue and pull request templates

### ISSUE THREAD

**Issue by ChinmayMhatre** [excalidraw/excalidraw#6422]
Adding these would encourage the contributors to provide relevant info in the issue and the PR and would help the maintainers go through the pr's better.

![image](https://user-images.githubusercontent.com/51131670/230296283-1ad43b48-597c-4f55-bf08-c4f4e2329b3f.png)

If approved I would like to work on this

**Comment by dwelle** [comment]
Someone previously suggested doing this (https://github.com/excalidraw/excalidraw/issues/2777), but we still think that it adds unnecessary friction.

Right now I'd actually focus on cleaning the issues up a bit. While the bug/issue/request template could help with auto-labeling, that's generally not the bottleneck.

**Comment by ChinmayMhatre** [comment]
> Someone previously suggested doing this (#2777), but we still think that it adds unnecessary friction.
> 
> Right now I'd actually focus on cleaning the issues up a bit. While the bug/issue/request template could help with auto-labeling, that's generally not the bottleneck.

Makes sense! I'll go through the docs and look out for any addition or changes that could make it easier for contributors
