### ISSUE TITLE
ci: add dependabot

### ISSUE THREAD

**Issue by priyankarpal** [excalidraw/excalidraw#6456]
- In this project, we're using some gh actions but in future if there are any updates needed how many of the gh actions we can update at once manually? 

- so that's why we can add dependabot to update all gh actions if there are any updates needed. 
- Dependabot will create a PR
- Just you need to check & merge it soon.

**Comment by ad1992** [comment]
@priyankarpal we were using Dependabot for a long time and removed it recently as it loads with bunch of PR's which gets harder to maintain with time, hence we try to update the dependencies by ourselves at intervals and its been working well. Though we can revisit this later as needed.

**Comment by priyankarpal** [comment]
> @priyankarpal we were using Dependabot for a long time and removed it recently as it loads with bunch of PR's which gets harder to maintain with time, hence we try to update the dependencies by ourselves at intervals and its been working well. Though we can revisit this later as needed.

ok .
