### ISSUE TITLE
rotated container renders unrotated text

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#6476]
related https://github.com/excalidraw/excalidraw/issues/5858

![excal-bug-rotated-container-text](https://user-images.githubusercontent.com/5153846/232621824-6114e032-accf-49c2-afbb-d3423cf36cff.gif)

**Comment by siddhant1** [comment]
Let me take a crack at this!

**Comment by ad1992** [comment]
@siddhant1 sure go ahead

**Comment by siddhant1** [comment]
@ad1992 attached a [PR](https://github.com/excalidraw/excalidraw/pull/6477)
