### ISSUE TITLE
"Insert image" / drag and drop support for AVIF + WebP

### ISSUE THREAD

**Issue by karlhorky** [excalidraw/excalidraw#6478]
Hi there, first of all, thanks so much for Excalidraw and the ecosystem! Really amazing tool.

1. I noticed that the "Insert image" tool in the top toolbar (shown below) does not support AVIF or WebP:

![Screenshot 2023-04-18 at 10 23 11](https://user-images.githubusercontent.com/1935696/232718388-87c33b4a-3a6b-46d1-bf83-61cd51e85420.png)

When clicking the button, the `.avif` and `.webp` images are grayed out in the Finder:

![Screenshot 2023-04-18 at 10 26 01](https://user-images.githubusercontent.com/1935696/232719164-abe38087-e050-4d93-8ef9-c082f7ba1a82.png)

But tricking the browser with the workaround below of renaming to `.avif.jpg` causes the image to be selectable and displayed in the diagram

Would be great to get support for these new file formats!

2. Drag and drop works with `.webp` images, but not with `.avif` images

**Comment by karlhorky** [comment]
## Workaround

Rename your AVIF images from `.avif` to `.avif.jpg` to trick Excalidraw into inserting them.

The image will be visible in the Excalidraw editor and also in the exported SVG, as long as the device + software viewing the image supports AVIF.

**Comment by dwelle** [comment]
@karlhorky good catch. Can you check if everything works for you fine? https://excalidraw-r6yy0udsb-excalidraw.vercel.app/ (https://github.com/excalidraw/excalidraw/pull/6500)

**Comment by karlhorky** [comment]
Looks good to me! Color reproduction is also better!

**Comment by karlhorky** [comment]
Thanks @dwelle ! 🙌
