### ISSUE TITLE
Tag with version in docker publish

### ISSUE THREAD

**Issue by Nainterceptor** [excalidraw/excalidraw#6507]
Dear Excalidraw team,
Thanks for your software [delivered in permissive license](https://github.com/excalidraw/excalidraw/blob/master/LICENSE)

While I'm currently writing an helm chart to deploy to self-hosted kubernetes cluster (ref #2703), I'm seeing that docker hub contains only "latest" tag, and no other tag seems to be added since ~1 year.

Is it possible to tag with version ?

Anticipated issue : 
1. I'm deploying hightly available deployment with 3 replicas
2. Node hosting replica 1 is down
3. Kubernetes is reallocating to another node, without docker image in cache

-> 2 replica have the version of step 1, the new replica download the latest, with version of the step 3, and users observe version inconsistency.

<details>
  <summary>More reasons</summary>
  Using a versioned Docker tag rather than just the "latest" tag in a Kubernetes deployment context provides several benefits that improve overall deployment stability, predictability, and manageability. Here are some key reasons:

* Reproducibility: Using versioned tags ensures that the exact same image is deployed every time, which guarantees reproducibility. "Latest" is a mutable tag that could point to different images over time, and this can introduce inconsistencies in deployments, making it difficult to identify issues caused by version changes.
* Rollback and roll-forward: In case of a failed deployment or detected issues, using versioned tags allows you to easily roll back to a known, stable version or roll forward to a new version. With the "latest" tag, you cannot guarantee which version you are rolling back or forward to, which can lead to unexpected results.
* Explicitness: Versioned tags make it clear which version of an image is being deployed. This enhances the understanding of what is running in the environment and reduces confusion among team members.
* Dependency management: In a Kubernetes deployment, different components of your application may depend on specific versions of other components. Versioned tags ensure that the right version of each component is deployed and helps to avoid breaking changes introduced by updating to incompatible versions.
</details>

Why not using excalidraw.com ?
We're in France, and excalidraw.com **break** GDPR using Google services without any opt-in.
1. [Source: CNIL](https://www.cnil.fr/en/google-analytics-and-data-transfers-how-make-your-analytics-tool-compliant-gdpr)
2. [GDPR Article 44](https://gdpr-info.eu/art-44-gdpr/)
3. [Matomo blog](https://matomo.org/blog/2022/02/france-google-analytics-gdpr-breach/)
4. [Noyb article](https://noyb.eu/en/edps-sanctions-parliament-over-eu-us-data-transfers-google-and-stripe)

**Comment by ryan-di** [comment]
Hey @Nainterceptor, thanks for the detailed & helpful feedback! Will look into this with the team and get back to you soon.
