### ISSUE TITLE
Provide Angle helpers when rotating elements 

### ISSUE THREAD

**Issue by Sameerkash** [excalidraw/excalidraw#6527]
It'd be a great help if there were angle helpers present when rotating elements along an axis as its often a bit hard to determine if the the element is in a perfect 180 or 90 degrees. 

Below is an example of how it'd look on the platform.

![Screenshot 2023-04-27 at 2 01 04 PM](https://user-images.githubusercontent.com/40424087/234806670-c51950fe-7346-46bb-9c14-0e4cdb748af3.png)

**Comment by ad1992** [comment]
I think the first step would be to just add to Nerd Stats

**Comment by siddhant1** [comment]
I can work on this!

**Comment by dwelle** [comment]
@ryan-di is already working on this in #6382

**Comment by GaganGopi** [comment]
Hello guys, is it possible to see "Angle" within "Stats for nerds" already?

**Comment by ad1992** [comment]
Yes its in progress in #6382 @GaganGopi

**Comment by GaganGopi** [comment]
Perfect. Thank you @ad1992

**Comment by dwelle** [comment]
Angles now shown in the Stats (https://github.com/excalidraw/excalidraw/issues/6527) so for now we'll keep it at that as showing the angle on canvas feels useful only to very specific use cases, and even then you can use the Stats panel.
