### ISSUE TITLE
Integrate a bundle check analyser on gh actions to keep a check on bundle size

### ISSUE THREAD

**Issue by ad1992** [excalidraw/excalidraw#6532]
As we are pushing more code, its better to be aware how its impacting the bundle size
Here are few libraries we can try out

https://github.com/siddharthkp/bundlesize - doesn't look like it has GH actions support
https://github.com/ai/size-limit - It has GH action support and its pretty active

**Comment by snitin315** [comment]
I'll add this.

**Comment by ad1992** [comment]
Go for it @snitin315 🚀
