### ISSUE TITLE
In Browser Collaboration

### ISSUE THREAD

**Issue by Olitrax99** [excalidraw/excalidraw#6543]
Is there a way to use collaboration (connect to a excalidraw-room) when using the "directly in browser" integration?
https://docs.excalidraw.com/docs/@excalidraw/excalidraw/integration#browser

I only have a simple html/javascript page and want to use collaboration. I managed to create the LiveCollaborationTrigger Button but I still have to implement the onSelect/isCollaborating... features. I also can not find the collab modules in this implementation.

**Comment by ad1992** [comment]
@Olitrax99 the npm package doesn't come with collaboration so you will have to implement collaboration in host app. Here is detailed answer on the same https://github.com/excalidraw/excalidraw/discussions/3879#discussioncomment-1110524
For further queries lets discuss in the same link to keep everything at one place
