### ISSUE TITLE
Add tests coverage threshold in pull requests

### ISSUE THREAD

**Issue by ad1992** [excalidraw/excalidraw#6553]
We should add a minimum threshold for test coverage in PR's to make sure the PR's merged at least have some tests if not 100%.

Right now since we don't have any such threshold so its hard to say the coverage and often we need to ask the author to add test.

I think setting  to **65%** threshold would be good to go and later we can increase it.

This would make sure every PR has some tests and will help in avoid bug, better maintenance down the line and increase coverage.

**Comment by siddhant1** [comment]
Let me pick this up and add some checks in CI and add jest coverages

**Comment by ad1992** [comment]
Go for it @siddhant1 🚀

**Comment by snorfyang** [comment]
@siddhant1 Can I help with this? I have some ideas maybe:)

**Comment by siddhant1** [comment]
Hey, just checked this, sure @snorfyang you wanna check the PR and add your comments?https://github.com/excalidraw/excalidraw/pull/6559

**Comment by snorfyang** [comment]
> Hey, just checked this, sure @snorfyang you wanna check the PR and add your comments?#6559

I would like to use another gh action named ```codecov```, and this works well in the PR to my fork.

**Comment by siddhant1** [comment]
This also looks good, I will leave this call to @ad1992!

**Comment by ad1992** [comment]
Thanks @siddhant1 @snorfyang for the PRs. 
To start I think we would like to first keep it minimal and introduce test coverage checks (not marking as required and see how it looks in practice) and later we can surely migrate to codecov or similar tool which gives more and detailed insights. 
Also @snorfyang code cov will be posting comments every time you update the test or does it just post a single comment and keeps updating it ?

**Comment by snorfyang** [comment]
> Thanks @siddhant1 @snorfyang for the PRs. To start I think we would like to first keep it minimal and introduce test coverage checks (not marking as required and see how it looks in practice) and later we can surely migrate to codecov or similar tool which gives more and detailed insights. Also @snorfyang code cov will be posting comments every time you update the test or does it just post a single comment and keeps updating it ?

It just post a single comment and keeps updating it.

**Comment by siddhant1** [comment]
Just saw this, let me update this!

**Comment by Thedineshk24** [comment]
Hey @ad1992 i would like to add test cases for the code which has not covered with test cases.

i know basic of react testing lib, i can learn more and give it a shot add test cases for smaller portion of code & raise PR for that.

**Comment by ad1992** [comment]
Sure @Thedineshk24! You can run `yarn test:coverage` to understand where coverage is significantly low.
For a start, you can try adding tests for [https://github.com/excalidraw/excalidraw/blob/master/src/components/ColorPicker/colorPickerUtils.ts](https://github.com/excalidraw/excalidraw/blob/master/src/components/ColorPicker/colorPickerUtils.ts).

You can create a file `colorPickerUtils.test.ts` in same folder and start writing tests for each util. To check which exact lines are uncovered you can use `yarn test:coverage`

**Comment by ad1992** [comment]
> > Thanks @siddhant1 @snorfyang for the PRs. To start I think we would like to first keep it minimal and introduce test coverage checks (not marking as required and see how it looks in practice) and later we can surely migrate to codecov or similar tool which gives more and detailed insights. Also @snorfyang code cov will be posting comments every time you update the test or does it just post a single comment and keeps updating it ?
> 
> It just post a single comment and keeps updating it.

Do keep your PR open @snorfyang , we will merge the regular GH action and once it works well we can consider migrating to `codecov` as well.
