### ISSUE TITLE
Japanese text input inside a container does not work properly

### ISSUE THREAD

**Issue by eri24w** [excalidraw/excalidraw#6576]
OS: Windows10 or MacOS too
Browser: Chrome 113.0.5672.64 or Edge 113.0.1774.35 too

When I input some Japanese hiraganas and covert it into kanji or katakana inside rectangle or "Wrap text in container" (that's how you input Japanese normally), the output is converted before writing is finished like below:

![JapaneseIssue](https://github.com/excalidraw/excalidraw/assets/105631979/65cf7463-448a-4a5b-a575-946fc6102e23)

In the case above, I expect the text to be "日本語でコミュニケーション", but it is "日本語でこみゅにけーｓｙ御" or “日本語でこみゅにけーｓｙおおｎｎ” instead.

This phenomenon doesn't happen in the case below:
-convert hiraganas directly on the canvas(without any container)
-convert hiraganas into a container of sufficiently large size
Even though I can work around this issue by expanding a container to large size from the begging, I’m having trouble with conversion bugs when adding sentences gradually.

I would be very grateful if you could change it so that the container expands automatically so that it can be used with Japanese IME.

**Comment by ad1992** [comment]
Hi @eri24w we have a similar issue https://github.com/excalidraw/excalidraw/issues/5837
I don't know Japanese so will need your help in understanding it better :) 
So it's breaking / converting the letters where it shouldn't coz of less width of the container ?
How do you think we should fix this ? would you like to take a stab in fixing this ?

**Comment by eri24w** [comment]
Thank you for your swift response :))
It seems that the same issue as Korean one.

**Comment by maruric** [comment]
Hi @ad1992
I work with @eri24w  .

We think that the edit state should not be terminated unintentionally.

After commenting out the following code, the phenomenon no longer occurs.
https://github.com/excalidraw/excalidraw/blob/e619e0605530e2e83db883968aea1435ec15ed18/src/element/textWysiwyg.tsx#LL257C8-L257C8


In most cases, the same value is assigned, but when assigning a different value during Japanese input, the editing seems to be terminated. Would this be helpful?

**Comment by ad1992** [comment]
> Hi @ad1992 I work with @eri24w .
> 
> We think that the edit state should not be terminated unintentionally.
> 
> After commenting out the following code, the phenomenon no longer occurs. https://github.com/excalidraw/excalidraw/blob/e619e0605530e2e83db883968aea1435ec15ed18/src/element/textWysiwyg.tsx#LL257C8-L257C8
> 
> In most cases, the same value is assigned, but when assigning a different value during Japanese input, the editing seems to be terminated. Would this be helpful?

Thanks for sharing @maruric. We cannot remove it rightaway as it will break the flow. But this surely helps and I will look into fixing this.

**Comment by ad1992** [comment]
@eri24w @maruric I have pushed a fix, can you test if it works fine in https://excalidraw-git-aakansha-fix-editable-value-co-6cd4f7-excalidraw.vercel.app/ ?

**Comment by eri24w** [comment]
@ad1992 
Thank you very much for your quick response.
It's working fine now in Japanese :)) It looks like Korean works fine, too.
Thank you!!

**Comment by ad1992** [comment]
> @ad1992 Thank you very much for your quick response. It's working fine now in Japanese :)) It looks like Korean works fine, too. Thank you!!

Awesome 🚀 Thank you for testing it out
