### ISSUE TITLE
Creating text should scroll viewport as needed

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#659]
https://github.com/excalidraw/excalidraw/pull/650 fixes https://github.com/excalidraw/excalidraw/issues/365 only partially. We don't get the scrollbars and stuff, but we also don't see what we're writing (mostly):

![excalidraw_text_overflow2](https://user-images.githubusercontent.com/5153846/73595996-8b805400-451e-11ea-9532-2c7246c3a2d9.gif)

**Comment by vjeux** [comment]
Let’s not call it a bug. You can scroll in a better location if you want to see the rest of the text.

**Comment by vjeux** [comment]
I'll go ahead and close this. I feel like the current behavior is fine. Moving the whole screen may be weird.
