### ISSUE TITLE
Color Picker Selector

### ISSUE THREAD

**Issue by ryantjack** [excalidraw/excalidraw#6590]
First of all, awesome product. Unless I'm just missing something, it would be very helpful to select a color (e.g. palette with eyedropper) rather than just entering a hex value. I have to go elsewhere to preview colors and get the hex code to dump into Excalidraw.

**Comment by dwelle** [comment]
Hey, thanks @ryantjack!

Eyedropper will be added soon! The color-wheel type picker we're holding off on because we see that as introducing significant complexity/friction.

Closing in favor of https://github.com/excalidraw/excalidraw/issues/5582
