### ISSUE TITLE
Allow different options between tools

### ISSUE THREAD

**Issue by gustavnikolaj** [excalidraw/excalidraw#6594]
I would like to have different options for the Edges selected between the Rectangle tool and the Arrow tool.

I mostly use excalidraw to draw quick diagrams, and I want square edges for my Rectangles, and rounded edges for my arrows and lines. But whenever I change it on one of them, it changes the other... Which means that I have to select tool + edge shape for every change of tool.

The behaviour used to be as I want it - but it's been some months since I last used it, so I cannot pinpoint exactly when it changed.

**Comment by dwelle** [comment]
@ad1992 do you remember if we changed this, because I don't 😊

**Comment by gustavnikolaj** [comment]
So quick manual bisecting revealed that the tag `v0.13.0` function as I described the old behavior, and `v0.14.0` and forwards functions as the current behavior.

I am not able to easily narrow it down further, because I don't know the project well enough to anything more than checkout a ref followed by `yarn && yarn start` and testing it in the browser.

---

The difference can be described as this as well:

In v0.13.0 you start the dev server and open the local app.

Then you select the rectangle tool, and observe the Edge styling selected there:

![image](https://github.com/excalidraw/excalidraw/assets/1371503/52f7cf56-4829-4805-8959-f958915b3d38)

Then you select the arrow tool, and observe the Edge styling selected there.

![image](https://github.com/excalidraw/excalidraw/assets/1371503/6d64ff49-2889-4087-b1cd-65e41fc6f195)

---

If you try to do the same on `HEAD`, or `v0.14.0` - or indeed just on the current version deployed on `excalidraw.com` you will notice that the two edge styles are the same - and if you change one, the other will follow.

**Comment by gustavnikolaj** [comment]
I continued the bisecting and found the offending commit: https://github.com/excalidraw/excalidraw/commit/5854ac3eedd66b132a4095fa69e4ccd90b14b30d

If you start the app at `5854ac3eedd66b132a4095fa69e4ccd90b14b30d` you will see the broken behavior where you set edge style of both rectangle and arrow at the same time.

If you start the app at `65d84a5d5a2224323c6717876bba6346414d7dbe` (the [parent commit](https://github.com/excalidraw/excalidraw/commit/65d84a5d5a2224323c6717876bba6346414d7dbe) of the commit mentioned above) you will see the regular behavior where edge stylings can be set independently.



- Last known good commit: https://github.com/excalidraw/excalidraw/commit/65d84a5d5a2224323c6717876bba6346414d7dbe
- First bad commit: https://github.com/excalidraw/excalidraw/commit/5854ac3eedd66b132a4095fa69e4ccd90b14b30d

**Comment by gustavnikolaj** [comment]
Seems to be an unintended side-effect in the commit, as far as I can tell.

**Comment by gustavnikolaj** [comment]
ping @dwelle in case you missed the notifcations :)

**Comment by gustavnikolaj** [comment]
ping @dwelle. Sorry for nagging you again, but it seems this has fallen between the cracks, and I would love to get your thoughts on my findings above.

**Comment by gustavnikolaj** [comment]
Hi @dwelle @ad1992 

I would be happy to contribute a fix, but I would like to know if you think this is indeed a bug or an intended change in behavior before I dig in and familiarize myself with the code.

Your reply will be much appreciated.

**Comment by gustav-olsen-groupone** [comment]
My problem has been addressed indirectly by recent changes, that introduced separate options for arrow styles.

Previously the sharp edges option on boxes would make the arrows sharp and the rounded edges option would make arrows curved. Now they have different options.

While the specific change is still strictly speaking the same, the use-case has been solved by the recent change, so I'll close my issue.
