### ISSUE TITLE
color picker input doesn't close when clicking on canvas

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#6595]
Reproduces both in production and in the new color picker redesign.

![excal-bug-color-picker-stays-open](https://github.com/excalidraw/excalidraw/assets/5153846/5c640531-12e2-4f8b-bd0a-08be5d1b9e44)

Steps

1. select an element & open color picker
2. click on canvas on an empty space (-> `appState.openPopup` is not reset)
3. drag-select any element (-> `appState.openPopup` is not reset)
4. picker re-opens (it was never closed)

Steps (2) & (3) are significant. If if step (2) or (3) you _click_ on an element, the `appState.openPopup` is retained.

I narrowed it down to `handleCanvasPointerDown()` -> `handleSelectionOnPointerDown()` -> `clearSelection()`'s `setState({ selectedElementIds: {} })` (if commented out it starts to work), but haven't gone further. And it's very possible a red herring and not the true cause.

Unclear how the above affects blur/focus state that triggers the `openPopup` reset. I've monkey-patched `event.preventDefault`, `event.stopPropagation`, `event.stopImmediatePropagation`, and `HTMLElement.focus` to track whether and where we call those, but didn't get anywhere either (code below).

```js
const originalPreventDefault = Event.prototype.preventDefault;
Event.prototype.preventDefault = function () {
  console.warn("preventDefault", this);
  originalPreventDefault.call(this);
};

const originalStopPropagation = Event.prototype.stopPropagation;
Event.prototype.stopPropagation = function () {
  console.warn("stopPropagation", this);
  originalStopPropagation.call(this);
};

const originalStopImmediatePropagation =
  Event.prototype.stopImmediatePropagation;
Event.prototype.stopImmediatePropagation = function () {
  console.warn("stopImmediatePropagation", this);
  originalStopImmediatePropagation.call(this);
};

const originalFocus = HTMLElement.prototype.focus;
HTMLElement.prototype.focus = function () {
  console.warn("focus", this);
  originalFocus.call(this);
};
```

**Comment by vsaravind01** [comment]
I took a look at this issue. It's because `updateData` is not triggered anywhere inside `ColorPickerPopupContent`. I'm interested in contributing to this project and I've made a PR on this issue #6599
