### ISSUE TITLE
Link to Docs in help section goes to the GitHub page instead of the docs

### ISSUE THREAD

**Issue by ChinmayMhatre** [excalidraw/excalidraw#6616]
<img width="1074" alt="image" src="https://github.com/excalidraw/excalidraw/assets/51131670/fd19db1c-4db6-423a-b128-89a3ce74e5ea">

The documentation button leads to : https://github.com/excalidraw/excalidraw#documentation

It could be : https://docs-excalidraw.vercel.app.  ?

**Comment by ad1992** [comment]
closed via #6654
