### ISSUE TITLE
Provide a way to change text color of multiple selected element at the same time

### ISSUE THREAD

**Issue by stecydube** [excalidraw/excalidraw#6630]
The only way to change the text color of an element is by double clicking it so that the properties side panel change to allow setting the "stroke" color of the text.

This prevents to be able to modify multiple selected elements text color since double-clicking only works for one element.

I propose having an additional slider in the text section to set the color instead.

**Comment by ad1992** [comment]
@stecydube you can always select the text elements and update the stroke colour at once. Does that not work for you ?

<img width="1078" alt="Screenshot 2023-06-15 at 2 15 50 PM" src="https://github.com/excalidraw/excalidraw/assets/11256141/15061357-7d1a-4044-94df-e04351e0a390">

In case you meant Text containers (text inside a shape) and updating text color for them, we were discussing to introduce a property `text color` for that, I will create an issue for the same

**Comment by ad1992** [comment]
> In case you meant Text containers (text inside a shape) and updating text color for them, we were discussing to introduce a property text color for that, I will create an issue for the same

I have created a separate issue for introducing text color property https://github.com/excalidraw/excalidraw/issues/6681, incase you meant text containers in this issue, feel free to close this one as as the linked issue would take care of it

**Comment by stecydube** [comment]
@ad1992 Yes, I meant text containers 😋

Thanks for creating a ticket to track this 👍
