### ISSUE TITLE
How to disable "sticky" feature

### ISSUE THREAD

**Issue by seriaati** [excalidraw/excalidraw#6631]
I love excalidraw, but there is this very annoying feature.
When I draw a line, then write some text next to it, the text is now "stick" with the line.
![image](https://github.com/excalidraw/excalidraw/assets/61446626/79c76a0a-72c7-4081-a0e7-01f65c8a5eb7)

Whenever I move the text, that line stretches as well.
Is there a way to disable this? If not, can this be added as a feature?

**Comment by ad1992** [comment]
Closing this as I have created a new issue where we will be discussing this and improve the overall UX for arrow binding https://github.com/excalidraw/excalidraw/issues/6685
