### ISSUE TITLE
Terrible rendering in Firefox

### ISSUE THREAD

**Issue by helmbold** [excalidraw/excalidraw#6632]
A few days ago rendering in Firefox looked good (as I was used to), but now it looks very coarse grained and blurry.

This is how it looks in Firefox 113.0.2 on Window 10:
![grafik](https://github.com/excalidraw/excalidraw/assets/5079980/f87a4dbd-b840-43a4-9bc8-f9d858cdecbc)

The same in Edge 113.0.1774.57:

![grafik](https://github.com/excalidraw/excalidraw/assets/5079980/940e648e-8196-4548-8950-440eef870cd5)

**Comment by ad1992** [comment]
It works fine in Mac, probably related to windows
@dwelle can you check how it renders for you in windows?

**Comment by helmbold** [comment]
As I've found out the rendering issue is due to the setting `privacy.resistFingerprinting=true` in Firefox (in `about:config`). For some reason this setting didn't affect excalidraw in the past. If I change this setting to `false` everything looks good again.
