### ISSUE TITLE
SVG loses quality in latest version

### ISSUE THREAD

**Issue by Gazebeaux** [excalidraw/excalidraw#6650]
This is the first time I've ever submitted a GitHub issue, please let me know if I am out of line in any way making this post lol. Anyways, I am lazy and have been using 1.8.22 up until today and an SVG I had in a drawing became incredibly blurry at the same zoom I had it at in 1.8.22 when it looked perfect. For now I've just reverted back to 1.8.22 and the issue is resolved. I honestly would not even know where to begin looking to solve this issue for the latest release, but I thought maybe you'd like it brought up. Maybe I'm doing something wrong, but I haven't changed anything other than updating plugins and I didn't have to turn off any others besides Excalidraw to fix the issue. Great plugin, thanks for your hard work!

**Comment by ad1992** [comment]
@Gazebeaux you are probably referring to some third party plugin which uses Excalidraw ?

**Comment by dwelle** [comment]
@zsviczian I presume obsidian?

**Comment by Gazebeaux** [comment]
Oh my lord, can't believe I forgot to mention that. I think I even remember that there's a separate github page for the Obsidian plugin and I should have posted this there.

**Comment by dwelle** [comment]
Yep, there's https://github.com/zsviczian/obsidian-excalidraw-plugin/issues, unless it turns out it's really a problem in the excalidraw library itself!

**Comment by ad1992** [comment]
closing this as its related to Obsidian, feel free to reopen if this happens in Excalidraw as well
