### ISSUE TITLE
Error Page Unresponsive on Copy To Clipboard of some text

### ISSUE THREAD

**Issue by shivanshu814** [excalidraw/excalidraw#6667]
- [ ] Copy to clipboard as PNG On click it Takes a time and generates Page Unresponsive ,
You can wait for it to become responsive or exit the page.

**Comment by ad1992** [comment]
@shivanshu814 how big is the drawing ? Is it  possible for you to share the drawing ? (In case its not confidential of course )

**Comment by shivanshu814** [comment]
> > @shivanshu814 how big is the drawing ? Is it possible for you to share the drawing ? (In case its not confidential of course )
> 
> yaa sure ![image](https://user-images.githubusercontent.com/97324405/245130416-b4c3ece6-2f0b-4d8e-922a-8d831399a4d5.png)

![image](https://github.com/excalidraw/excalidraw/assets/97324405/2aeb14e1-73d8-41f0-8fce-709a1c8208a0)

**Comment by ad1992** [comment]
@shivanshu814 can you export it to shareable link and post the link here ? From the screenshot it looks like the drawing is huge so that possibly is the reason for page being unresponsive

![image](https://github.com/excalidraw/excalidraw/assets/11256141/ea799846-6127-4fad-b287-6efec172d415)

Or you can actually check the size yourself as well by selecting the drawing and using using Nerd Stats

![image](https://github.com/excalidraw/excalidraw/assets/11256141/7676c386-faab-4834-a5c2-fe00cf00792a)

**Comment by shivanshu814** [comment]
> > @shivanshu814 can you export it to shareable link and post the link here ? From the screenshot it looks like the drawing is huge so that possibly is the reason for page being unresponsive
> > ![image](https://user-images.githubusercontent.com/11256141/245131353-ea799846-6127-4fad-b287-6efec172d415.png)
> > Or you can actually check the size yourself as well by selecting the drawing and using using Nerd Stats
> > ![image](https://user-images.githubusercontent.com/11256141/245131788-7676c386-faab-4834-a5c2-fe00cf00792a.png)
> 
> not able to export it also ![image](https://user-images.githubusercontent.com/97324405/245140426-2c0a9cf1-9f04-4e78-bb2e-39f063e005d1.png) ![image](https://user-images.githubusercontent.com/97324405/245140589-8edd4136-923c-4abd-80ce-39d102b86138.png) using windows 11

content is this much only
![image](https://github.com/excalidraw/excalidraw/assets/97324405/cf9d2f27-3a3c-400a-9753-7e3b100ad4e7)

**Comment by ad1992** [comment]
@shivanshu814 what do you mean by not able to export it ? You are getting error on exporting as well ?
You can just copy the diagram (using ctrl + c / right click copy) and paste it here as well

**Comment by ad1992** [comment]
@shivanshu814 you can click on "Save to" and then it should open up the export dialog from where you can export to shareable link

1.  Click on Preferences menu and then on "Save to"
![image](https://github.com/excalidraw/excalidraw/assets/11256141/0e205cb9-e6b1-490a-bd45-f3fd26455776)

 2. Click on "Export to Link"
  ![image](https://user-images.githubusercontent.com/11256141/245131353-ea799846-6127-4fad-b287-6efec172d415.png)
  
  3. Share that link here

**Comment by dwelle** [comment]
It's possible the canvas to PNG encoding takes too much time on your device, hence the hanging. Although the portion you're trying to export as you're showing on the screenshot isn't that large. What device (or in terms of specs) are you working on?

**Comment by shivanshu814** [comment]
> What device (or in terms of specs) are you working on

windows 11 32 gb ram 2tb storage asus

**Comment by ad1992** [comment]
@shivanshu814 the drawing is actually too big and hence copy to clipboard isn't working, though I am not sure why you aren't seeing the below error 👇🏻  and rather page becomes unresponsive for you

![Screenshot 2023-06-15 at 4 41 25 PM](https://github.com/excalidraw/excalidraw/assets/11256141/10e91a41-be89-4576-ad0e-d2f5c2d61ced)

**Comment by shivanshu814** [comment]
> @shivanshu814 the drawing is actually too big ~ 100Mb and hence copy to clipboard isn't working, though I am not sure why you aren't seeing the below error when trying to copy👇🏻 and rather page becomes unresponsive for you so will have to check that
> 
> ![Screenshot 2023-06-15 at 4 41 25 PM](https://user-images.githubusercontent.com/11256141/246091712-10e91a41-be89-4576-ad0e-d2f5c2d61ced.png)

okay gotcha
