### ISSUE TITLE
Migrate from CRA to Vite

### ISSUE THREAD

**Issue by ad1992** [excalidraw/excalidraw#6684]
We would like to migrate from CRA to Vite due the a couple of reasons

* The Build time of Vite is significantly faster the CRA  
* Hot Module Replacement(HMR)  is faster in Vite as compared to CRA
**Vite doesn't have strict `path` rule that you cannot import anything outside `src` folder line `CRA`. Due to this restriction we have not been able to decouple a lot of code outside src directory.
*  CRA is no longer maintained and not recommended in official [docs](https://react.dev/learn/start-a-new-react-project?ref=asserts.ai)

Here is a nice [article](https://makimo.pl/blog/why-we-use-vite-instead-of-create-react-app/#:~:text=Vite%20uses%20the%20esbuild%20bundler,in%20turn%20makes%20it%20slower.) about metrics in Vite vs CRA. We should try out and check how it works for us to understand better

Initial attempt to integrate Vite in https://github.com/excalidraw/excalidraw/pull/6441 by @wesbragagt

Shippped in https://github.com/excalidraw/excalidraw/pull/6713 and https://github.com/excalidraw/excalidraw/pull/6818

**Comment by codingmickey** [comment]
Hey @ad1992 does this need any help.. I guess this has been completed right?

**Comment by ad1992** [comment]
Yes this was shippped in #6713  and https://github.com/excalidraw/excalidraw/pull/6818
