### ISSUE TITLE
Real-time arrow rendering when creation

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#669]
Would be nice to update the arrow on every mouse move, so it's easier to understand what the final arrow will look like.

https://zwibbler.com/demo/

(It does have a weird arrow position though when just clicked though)

![ezgif-3-b1247a92ecb8](https://user-images.githubusercontent.com/197597/73612694-c4faa300-45a2-11ea-9577-1dd924c4e22b.gif)

https://excalidraw.com/

![ezgif-3-48d787b65136](https://user-images.githubusercontent.com/197597/73612692-c3c97600-45a2-11ea-9232-b2de58910ce9.gif)

**Comment by GasimGasimzada** [comment]
I am closing this issue based on #697
