### ISSUE TITLE
The shortcut key F for fullscreen and the frame tool F conflict.

### ISSUE THREAD

**Issue by yanjieee** [excalidraw/excalidraw#6704]
The shortcut key F for fullscreen and the frame tool F conflict.

**Comment by m-Chetan** [comment]
Shortcut for fullscreen should be F11

**Comment by yanjieee** [comment]
> Shortcut for fullscreen should be F11

![CleanShot 2023-06-23 at 10 22 37@2x](https://github.com/excalidraw/excalidraw/assets/7811777/2fa14083-9eb7-4ab5-a533-364d7f3b02ac)

**Comment by TobTobXX** [comment]
This is the screenshot translated with ChatGPT:

- 前图 (Previous Image): <kbd>Cmd</kbd> <kbd>+</kbd>
- 后图 (Next Image): <kbd>Cmd</kbd> <kbd>-</kbd>
- 置顶缩放 (Zoom to Top): <kbd>Cmd</kbd> <kbd>0</kbd>
- 缩放以适应所有元素 (Zoom to Fit All Elements): <kbd>Shift</kbd> <kbd>1</kbd>
- 缩放到选区 (Zoom to Selection): <kbd>Shift</kbd> <kbd>2</kbd>
- 上下移动页面 (Scroll Pages Up/Down): <kbd>PgUp</kbd>/<kbd>PgDn</kbd>
- 全屏 (Full Screen): <kbd>F</kbd>
- 离线模式 (Offline Mode): <kbd>Option</kbd> <kbd>Z</kbd>
- 显示网格 (Show Grid): <kbd>Cmd</kbd> <kbd>'</kbd>
- 高清模式 (High Definition Mode): <kbd>Option</kbd> <kbd>R</kbd>
- 切换主题 (Toggle Theme): <kbd>Shift</kbd> <kbd>D</kbd>
- 撤销/恢复 (Undo/Redo): <kbd>Option</kbd> <kbd>/</kbd>

Anyway, this is how the shortcut options currently looks:

![image](https://github.com/excalidraw/excalidraw/assets/86106200/e233594d-04f4-442a-8e02-bce858f26e79)

There is no fullscreen command (any more?) in there.

<kbd>F11</kbd> is a browser-native command and should work across all websites, including Excalidraw.

@yanjieee Could you please try out if <kbd>F11</kbd> works for your usecase and either close the issue or comment on what else is needed?
