### ISSUE TITLE
Ability to resize multiple selected elements

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#672]
Would be great to be able to resize multiple selected elements. For example I drew a few shapes but wanted them slightly bigger or smaller. I had to redraw them or painfully resize/move each one by one instead of just resizing.

![image](https://user-images.githubusercontent.com/197597/73613417-5883a200-45aa-11ea-8c07-adadaca14a16.png)

**Comment by lipis** [comment]
Now that we support rotate, it's becoming a bit more difficult as this might change are primitive elements.

Example from Figma..

![Kapture 2020-04-03 at 14 59 10](https://user-images.githubusercontent.com/125676/78358398-cc96f200-75bb-11ea-9843-7295ceca2d2b.gif)

**Comment by dai-shi** [comment]
Even without rotation, those seem new shapes. Maybe only support resizing with keeping the same ratio, at least until polygons are supported?

**Comment by dwelle** [comment]
@dai-shi how are those new shapes? The individual elements would simply be resized by a scale factor.

**Comment by lipis** [comment]
Without rotation is not an issue..

**Comment by dai-shi** [comment]
My bad. Yeah, it's the only issue with rotation.

**Comment by dai-shi** [comment]
Something like this. This is very buggy though.

![rect13](https://user-images.githubusercontent.com/490574/78367001-5961a000-75fc-11ea-81f1-7f34339330dd.gif)

**Comment by lipis** [comment]
I don't mind keeping the promortions for the first iteration and allowing only corner handles!

**Comment by lipis** [comment]
@dai-shi Do you mind opening a PR?

**Comment by dai-shi** [comment]
Sure. It's still experimental code, but I now know that would eventually work out. Also, we need ideas for better UI.

**Comment by lipis** [comment]
I have ideas for better UI.. open the PR and we'll continue there.

**Comment by lipis** [comment]
Closing in favor of #1218.. let's continue there if needed
