### ISSUE TITLE
[Bug] Moving an element in a frame with the keyboard renders the element outside of the frame

### ISSUE THREAD

**Issue by alex-kim-dev** [excalidraw/excalidraw#6736]
### Steps

1. Draw a frame
2. Draw some element inside
3. Move it with keyboard arrow buttons (opt with shift) outside of the frame

[Screencast from 2023-07-04 15-46-12.webm](https://github.com/excalidraw/excalidraw/assets/45559664/8cd33ce9-6db0-4a48-a97e-ed2d6a9582f0)

### Actual

- the element is visible
- it can't be selected via a mouse click or by drawing a selection box

### Expected

One of:

- the element remains a part of the frame, becomes invisible
- the element detaches from the frame, becomes visible & can be selected as usual

**Comment by ad1992** [comment]
cc @ryan-di

**Comment by shubhamku044** [comment]
Can I work on this issue?

**Comment by ryan-di** [comment]
Most likely fixed by #7124 if it hadn't been fixed by some previous PRs.
