### ISSUE TITLE
Canvas Background title when changeViewBackgroundColor = false

### ISSUE THREAD

**Issue by CamTheGoblin** [excalidraw/excalidraw#6738]
When using the Excalidraw component and setting the changeViewBackgroundColor to false. It removes the color selection option but leaves the title "Canvas background" with nothing under it.

code to set changeViewBackgroundColor:
```
<Excalidraw
	UIOptions={{
		canvasActions: {
			changeViewBackgroundColor: false,
		},
	}}
/>
```

what displays:
![image](https://github.com/excalidraw/excalidraw/assets/97644920/4e6d0c7b-d16a-477e-8825-611afcc1c39b)

**Comment by ad1992** [comment]
Thanks for catching this @CamTheGoblin! PR welcome :)

**Comment by Minozzzi** [comment]
Hello everyone, I would like to contribute to this question. Can you assign to me?

**Comment by dwelle** [comment]
Sure @Minozzzi!
