### ISSUE TITLE
Arrow: cap scaling should take into account the entire arrow size

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#674]
We have an optimization for single arrow where the cap size is proportional to the arrow size until it hits a big enough length:

![image](https://user-images.githubusercontent.com/197597/73613549-ba90d700-45ab-11ea-8747-3ddd545c9966.png)

This is useful when the arrow is small. But with multi-point arrows, if the last point is close to the end, then the cap is ridiculously small for no good reason.

**Comment by dwelle** [comment]
To illustrate the last point:

![image](https://user-images.githubusercontent.com/5153846/73613713-9dcec080-45f8-11ea-80a4-25b93f3522b9.png)

**Comment by GasimGasimzada** [comment]
Do you think it should be based on arrow's length or bounds?

![Screen Shot 2020-02-04 at 3 40 36 PM](https://user-images.githubusercontent.com/807231/73741933-be1b8e00-4764-11ea-8676-50c31d6ece58.png)

For example, in the picture above, should we calculate it based on the arrow's length (~2x the size of arrow's bounds) or should we calculate it based on bounds?
