### ISSUE TITLE
proportionally resizing arrow labels results in buggy sizing

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#6744]
Proportionally resizing text containers resizes the bound text as well. That should (?) apply to arrow labels, too, but right now the behavior is a little buggy.

When you resize below the original size, it doesn't resize the text. When you resize above the orig size, it does resize the text.

We should pick one, and keep it consistent.

I'd align with text containers, but maybe there's a good argument to be made to not do this for labeled arrows?

![excal-proportional-resize-labeled-arrows-bug](https://github.com/excalidraw/excalidraw/assets/5153846/6ae665a0-b001-4aaa-8c79-b44acd10b7f9)

/cc @ad1992 @zsviczian @alex-kim-dev

**Comment by alex-kim-dev** [comment]
- I don't think its about the original size. There's a minimum arrow width of 300px set in [getContainerDims()](https://github.com/excalidraw/excalidraw/blob/master/src/element/textElement.ts#L690-L698)

  <details><summary>video</summary>
  
  [Screencast from 2023-07-10 15-50-23.webm](https://github.com/excalidraw/excalidraw/assets/45559664/a235bd17-13b2-4480-9e6e-9372394e793d)
  </details>

  But without that limit the label width is buggy:

  <details><summary>video</summary>
  
  [Screencast from 2023-07-10 16-12-35.webm](https://github.com/excalidraw/excalidraw/assets/45559664/cf3563ac-3967-4ae2-aeec-e2de05da6021)
  </details>

- > I'd align with text containers

  I would too.

I'm exploring the code further

**Comment by alex-kim-dev** [comment]
Let me know what you think about this PR ☝️
