### ISSUE TITLE
Scene rendering doesn't account for browser zoom

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#675]
When you zoom out browser (using `cmd/ctrl + -/+`, the canvas dimensions are not handled correctly, and thus the rendering is off (below, browser is zoomed out to 25%):

![excalidraw_zoom_out_issue](https://user-images.githubusercontent.com/5153846/73614434-57c92b00-45ff-11ea-9d1e-3c1bf2a2575a.gif)

**Comment by enzoferey** [comment]
Looks like working to me now ? We should maybe override the browser's default as we discussed yesterday and use our own zoom now.

**Comment by dwelle** [comment]
This was fixed in your PR, yes.
