### ISSUE TITLE
[Feature] Search tool

### ISSUE THREAD

**Issue by chris-bor** [excalidraw/excalidraw#6758]
It would be nice to have `Search...` tool in order to find proper text on the graph.

**Comment by ad1992** [comment]
@chris-bor do you mean searching text on the canvas similar to https://github.com/excalidraw/excalidraw/issues/3826 ?

**Comment by chris-bor** [comment]
@ad1992 Yes, that's exactly what I mean :+1:

**Comment by ad1992** [comment]
Alright closing this issue in favour of #3826
