### ISSUE TITLE
Delete read-only shareable link content

### ISSUE THREAD

**Issue by kerbumble** [excalidraw/excalidraw#6763]
Hi,

I am unable to find a way to delete/revoke content I had shared through the "Save to...|Export to Link" feature.  If I don't want my data to live on the cloud anymore, is there a way to purge the links I created?

**Comment by kerbumble** [comment]
Sorry, I just found this previous issue before I created this new one:  https://github.com/excalidraw/excalidraw/issues/6730

I emailed support to delete my links, but a self-service UI feature would be greatly appreciated!

**Comment by ad1992** [comment]
@kerbumble thanks for the feedback! Seems like this is resolved so closing. 
Feel free to reopen if it still persists
