### ISSUE TITLE
Option to keep all edges as "sharp" by default

### ISSUE THREAD

**Issue by Harshita-Kanal** [excalidraw/excalidraw#6772]
Thanks for the library!
Currently, when we first create a shape `square`, `diamond`, etc. we see that the edges are rounded, and from what I understood, we can configure it on an element level.
Should we add an app-level prop that could be passed to the `<Excalidraw />` component, that would set the edges as rounded or sharp by default - particularly useful when the app is being used in `zen-mode`?
I would love to help add it if it seems like a valuable addition :)

**Comment by ad1992** [comment]
@Harshita-Kanal you can use the `appState` property in `initialData` for this. 
You can set 👇🏻 

```
appState.currentItemRoundness // for roundness
appState.currentItemRoughness // for sharpness
```
and many such more properties as needed, here is the [full list](https://github.com/excalidraw/excalidraw/blob/master/src/types.ts#L101) of attributes which you can use to customise.

**Comment by Harshita-Kanal** [comment]
This worked, thank you! Closing the issue.
