### ISSUE TITLE
How to add libraries when excalidraw intergration in other system?

### ISSUE THREAD

**Issue by shikelong** [excalidraw/excalidraw#6778]
for example:
1. access the official demo: https:codesandbox.io/s/excalidraw-ehlz3?file=/src/App.tsx
2. reset libraries and click browser libraries
3. redirect to `https://libraries.excalidraw.com/?target=codesandbox&referrer=https%3A%2F%2Fehlz3.csb.app%2F&useHash=true&token=ipMCYiLZswCzg3CXVwOo7&theme=light&version=2&sort=default`
<img width="921" alt="image" src="https://github.com/excalidraw/excalidraw/assets/4499997/dcf04913-a535-4225-845d-9817f8ddd1ea">
4. click on Add to excalidraw button
5. redirect to new page: `https://ehlz3.csb.app/#addLibrary=https%3A%2F%2Flibraries.excalidraw.com%2Flibraries%2Fyouritjang%2Fsoftware-architecture.excalidrawlib&token=ipMCYiLZswCzg3CXVwOo7`
6. check original codesandbox demo, the libraries don't imported.

Does downing library file then opening library a workaround in that case? How to make `Add to excalidraw` works in that case?

**Comment by ad1992** [comment]
@shikelong once you click on "Add to library" you are redirected to the same code sandbox page and it does have the libraries. However we don't store in local storage in demo hence if you refresh its not persisted. So you will need to persist your data in local storage or some backend to achieve the same

**Comment by ashishrai888** [comment]
@ad1992  no it is not working . I have setup excalidraw in my project . when i click on library , it is redirect to excalidraw library page and then when i select any library it again redirect to my page , with some hash in url . But Library still blank , it is not showing anything to library .

**Comment by ad1992** [comment]
@ashishrai888 please refer to the [example code](https://codesandbox.io/p/sandbox/excalidraw-ehlz3?file=%2Fsrc%2FApp.tsx) and replicate the same in your code and it should work. 
In case it doesn't please share a reproducible code-sandbox link so I can look into it.

**Comment by ashishrai888** [comment]
@ad1992  no it is not working . in this [[example code]](https://codesandbox.io/p/sandbox/excalidraw-ehlz3?file=%2Fsrc%2FApp.tsx)  , when i click on browse library ,  it redirect to library page and then after selecting any particular library , it again redirect the page which is blank .

**Comment by ad1992** [comment]
@ashishrai888 it works fine for me, below is a video 👇🏻 

https://github.com/excalidraw/excalidraw/assets/11256141/fd7799a3-90ea-45ff-8d55-f5ca31288a16

Which OS / browser you are using ? Can you share a screen recording as well ?

**Comment by ashishrai8880** [comment]
@ad1992  I am using React class component with CDN link (Excalidraw and React) . useHandleLibrary({ excalidrawAPI });  this hook cannot be used inside class component .   I know this is quite difficult . Below I am attaching some part of code . I have implemented collaboration , Custom Save drawing to database feature . But unable to implement libraries feature in React class component . Is there any such hook for class component also ? . Please Help .                                                                                             
var ROOM_ID;
const loggedInUser = JSON.parse(localStorage.getItem('auth_user'));
// const loggedInUser =  {"mailto:id":43,"firstname":"ashish","lastname":"rai","email":"ashish.rai@codefire.in"} 

const Excalidraw = ExcalidrawLib.Excalidraw;

let ExcaliDrawApi = null;
function excaliDrawApiCallback(data) { ExcaliDrawApi = data }

RComp = React.createElement;

// / Root Component /
class RootComponent extends React.Component {
    constructor(props) {
        super(props);
    }
    render() {
        return RComp(
            React.Fragment,
            null,
            RComp(ExcalidrawWrapper)
        )
    }
}

class ExcalidrawWrapper extends React.Component {
    constructor(props) {
        super(props);

    }

    render() {
        return RComp(
            'div',
            { className: "excalidraw-wrapper", style: { height: '800px' } },
            RComp(ExcalidrawComp)
        )
    }
}

class ExcalidrawComp extends React.Component {

    constructor(props) {
        super(props);

        this.state = {
            isCollaborating: false,
            queryParams: new URLSearchParams(window.location.search),
            socket: null,
            liveUsers: [],
        }

        this.UIOptions = {
            
            export: {
                saveFileToDisk: true,
                onExportToBackend: saveDrawingHandler,
            }
        };
    }

    
    componentDidMount() {
        const { queryParams } = this.state;
        ExcalidrawLib.useHandleLibrary({ ExcaliDrawApi });
    }

    render() {
        return RComp(
            Excalidraw,
            {
                isCollaborating: this.state.isCollaborating,
                excalidrawAPI: excaliDrawApiCallback,
                UIOptions: this.UIOptions,
                initialData: intialDrawing(), // either should be a json or a promise resolving to the json
                onPointerDown: this.onPointerDown,
                // onScrollChange,
                // onPaste,
                // onLibraryChange,
                onLinkOpen,
                // langCode: 'en', // for another lang
                renderTopRightUI: () => RComp(ExcalidrawCollabComp, { socketConnect: this.socketConnect, stopSession: this.stopSession, collaborationTrigger: this.collaborationTrigger, liveUsers: this.state.liveUsers, isCollaborating: this.state.isCollaborating }),
                viewModeEnabled:true,
                zenModeEnabled:true,
                // gridModeEnabled:true,
                // libraryReturnUrl:'' // Set an empty string to disable library icons
            },

            RComp(ExcaliDrawMenu, null, null)
            // RComp(ExcaliDrawMenu , { UIOptions: this.UIOptions } )
        )
    }
}

**Comment by ashishrai888** [comment]
@ad1992  , is there any solution for above problem ?
