### ISSUE TITLE
Idea: allow ChatGPT to create diagrams

### ISSUE THREAD

**Issue by javigomez** [excalidraw/excalidraw#6786]
Hi,

I love Excalidraw. I am very interested in describing complex ideas with diagrams excalidraw is perfect for that task. 

ChatGPT excels in generating text that can be used to construct complex charts with for example MermaidJS. This involves asking ChatGPT to generate a MermaidJS diagram, which I then copy and paste into the MermaidJS editor at https://mermaid.live/. 

This has proven to be quite efficient and seamless. I am very eager to extend this workflow to Excalidraw, leveraging ChatGPT to generate JSON text that could be used to create diagrams in Excalidraw. For instance, I requested ChatGPT to generate a JSON version of a simple Excalidraw diagram, specifically, "two circles connected by a line". Here's what the AI came up with: 

```json
{
  "type": "excalidraw",
  "version": 2,
  "source": "https://excalidraw.com",
  "elements": [
    {
      "type": "ellipse",
      "version": 1,
      "versionNonce": 123,
      "x": 50,
      "y": 50,
      "width": 100,
      "height": 100,
      "strokeColor": "#000000",
      "backgroundColor": "#ffffff",
      "strokeWidth": 2,
      "strokeStyle": "solid",
      "roughness": 1,
      "opacity": 100
    },
    {
      "type": "ellipse",
      "version": 1,
      "versionNonce": 456,
      "x": 200,
      "y": 50,
      "width": 100,
      "height": 100,
      "strokeColor": "#000000",
      "backgroundColor": "#ffffff",
      "strokeWidth": 2,
      "strokeStyle": "solid",
      "roughness": 1,
      "opacity": 100
    },
    {
      "type": "arrow",
      "version": 1,
      "versionNonce": 789,
      "x": 100,
      "y": 100,
      "width": 100,
      "height": 0,
      "strokeColor": "#000000",
      "backgroundColor": "transparent",
      "strokeWidth": 2,
      "strokeStyle": "solid",
      "roughness": 1,
      "opacity": 100
    }
  ]
}
```

While it looks like excalidraw format. I put it in a test.excalidraw file and tried to upload it to the editor. Sadly I got an error:

![error](https://github.com/excalidraw/excalidraw/assets/1375475/3e5f5c69-da4f-41f1-8391-a709a58f1dd7)

But there was not any explanation of what was wrong in the markup. Also I couldn´t find any JSON markup documentation of excalidraw, that would have been enough to give it to ChatGPT to generate valid markup.

> Unfortunately, as a text-based AI, I'm unable to generate valid Excalidraw JSON files due to the limitations mentioned earlier. The JSON format of Excalidraw is likely to be more complex than the example and potentially contains other information about the drawing, such as scene metadata.
> 
> I would recommend creating a drawing in Excalidraw and exporting it as a JSON file to understand the exact structure and format that it requires. Once you have an example of an Excalidraw JSON file, you can use it as a template to create new JSON files that represent different drawings.

Given this, I kindly request the following:

- Could you provide detailed documentation about the exact structure and format that Excalidraw's JSON files require? This would significantly help in generating valid JSON markup for creating diagrams.
- If it's not already in place, could you consider more descriptive error messages when a JSON import fails? This would greatly assist in troubleshooting problematic JSON.

Thank you for considering my suggestions. I believe these enhancements could potentially open up new ways for users to interact with Excalidraw, particularly in combination with text-based AI models.

**Comment by ad1992** [comment]
@javigomez generating Excalidraw diagrams from text is in the pipeline :)

However for the above json, rn the element requires all the mandatory attributes to be passed as specified in the [element types](https://github.com/excalidraw/excalidraw/blob/master/src/element/types.ts) hence its failing as some of the element properties are missing and for the above json its `points` attribute for `arrow` which is missing so after adding `points` it should work

``` js
{
  "type": "excalidraw",
  "version": 2,
  "source": "https://excalidraw.com",
  "elements": [
    {
      "type": "ellipse",
      "version": 1,
      "versionNonce": 123,
      "x": 50,
      "y": 50,
      "width": 100,
      "height": 100,
      "strokeColor": "#000000",
      "backgroundColor": "#ffffff",
      "strokeWidth": 2,
      "strokeStyle": "solid",
      "roughness": 1,
      "opacity": 100
    },
    {
      "type": "ellipse",
      "version": 1,
      "versionNonce": 456,
      "x": 200,
      "y": 50,
      "width": 100,
      "height": 100,
      "strokeColor": "#000000",
      "backgroundColor": "#ffffff",
      "strokeWidth": 2,
      "strokeStyle": "solid",
      "roughness": 1,
      "opacity": 100
    },
    {
      "type": "arrow",
      "version": 1,
      "versionNonce": 789,
      "x": 100,
      "y": 100,
      "width": 100,
      "height": 0,
      "strokeColor": "#000000",
      "backgroundColor": "transparent",
      "strokeWidth": 2,
      "strokeStyle": "solid",
      "roughness": 1,
      "opacity": 100,
      "points":[[0,0],[109.61328125,-0.71484375]]
    }
  ]
}


```

However we are working on simplifying the API in https://github.com/excalidraw/excalidraw/pull/6546 which we will be merging soon and this will help in generating diagrams with minimal better API

**Comment by javigomez** [comment]
Thanks. Exciting times ahead!

Closing the issue
