### ISSUE TITLE
Put back send to back, bring to front on the left menu

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#679]
See twitter discussion: https://twitter.com/levsthings/status/1224116584970629121?s=21

**Comment by sompylasar** [comment]
Despite what's said in the twitter discussion, for more complex diagrams with a lot of overlapping elements that I'm trying to use excalidraw for, I personally feel like I would benefit from a layers panel, at least to select elements there when it's hard to do on the whiteboard.

**Comment by EswaraSatya** [comment]
https://github.com/excalidraw/excalidraw/issues/7468

still it is having this issue means it is not working only
As it is to annoying while using as it is killing the time of the user again need to remove the element and then need to add it again
I hope considering will help user for the better usage
