### ISSUE TITLE
Setup website

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#68]
I just bought excalidraw.com. We should figure out how to setup CI to build and publish it somewhere, either github pages or netlify

**Comment by nanot1m** [comment]
I'll try to setup github pages

**Comment by vjeux** [comment]
Sweet!

Btw, what do you all think about renaming the project to excalidraw? This is unique so we won’t have conflicts with anything else. Excalibur is used in so many contexts

**Comment by vjeux** [comment]
Done, I renamed it

**Comment by vjeux** [comment]
I just created a twitter account for it. Ping me if you want access: https://twitter.com/excalidraw

**Comment by Fausto95** [comment]
Any ideas of a good logo?

**Comment by vjeux** [comment]
Some ideas: https://www.google.com/search?q=sword+pen+logo&sxsrf=ACYBGNTtEws-G2njTFySW8b2rQkkiVL8JA:1578073883153&source=lnms&tbm=isch&sa=X&ved=2ahUKEwi5---p_-fmAhUNnZ4KHa9mCBkQ_AUoAXoECAwQAw&biw=1306&bih=728#imgrc=_

**Comment by vjeux** [comment]
I like those two:

![image](https://user-images.githubusercontent.com/197597/71739600-c2275980-2e0e-11ea-81cb-0e8085e641fe.png)

![image](https://user-images.githubusercontent.com/197597/71739618-cfdcdf00-2e0e-11ea-85ed-d09d47b94b55.png)

**Comment by nanot1m** [comment]
The second one ❤️
![excalibur](https://user-images.githubusercontent.com/9278185/71739640-d9e8f700-2e7b-11ea-8134-32b3ab5d60db.png)

**Comment by vjeux** [comment]
Your robot is so cute!

**Comment by giovannigiordano** [comment]
I like the second one

**Comment by giovannigiordano** [comment]
Later I will configure the CI and the #66 so we will have automatic deploy and testing

**Comment by vjeux** [comment]
I don't know what I did wrong but it doesn't seem to be working :(

![image](https://user-images.githubusercontent.com/197597/71742347-44674c00-2e16-11ea-8986-119437272f39.png)

**Comment by Fausto95** [comment]
We can also use netlify

**Comment by Fausto95** [comment]
> Done, I renamed it

We should also rename these lines: https://github.com/excalidraw/excalidraw/blob/98b158a83ded296c5b9cbc20d70d4a6d7442dde9/src/index.tsx#L16
https://github.com/excalidraw/excalidraw/blob/98b158a83ded296c5b9cbc20d70d4a6d7442dde9/src/index.tsx#L17

**Comment by nanot1m** [comment]
> I don't know what I did wrong but it doesn't seem to be working 😔

It's working now http://www.excalidraw.com

**Comment by vjeux** [comment]
I had to change the github setting to www.excalidraw.com instead of excalidraw.com FYI

**Comment by nanot1m** [comment]
We can make excalidraw.com working too:
https://help.github.com/en/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site#configuring-an-apex-domain

**Comment by vjeux** [comment]
Both are working for me, are they not for you?

**Comment by nanot1m** [comment]
It's working now! (:

**Comment by Fausto95** [comment]
excalidraw.com is not working for me

**Comment by vjeux** [comment]
Both are not working for me on chrome but work on safari. Seems like it's broken for other people https://twitter.com/suchipi/status/1213196775185502208

**Comment by Fausto95** [comment]
@vjeux can we try deploying it on Netlify?

**Comment by vjeux** [comment]
@Fausto95 do you mind if we try tomorrow if gh-pages fails to work?

**Comment by Fausto95** [comment]
I don’t mind!

**Comment by vjeux** [comment]
Just added config for root domain. Hopefully that'll work

![image](https://user-images.githubusercontent.com/197597/71748203-aa5bcf80-2e26-11ea-85bd-ffae58fc2f79.png)

**Comment by Fausto95** [comment]
excalidraw.com is now redirecting to www. 

I think it’s ok now since people can use the app
