### ISSUE TITLE
document excalidraw JSON schema

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#6804]
we should document at least the basic schema structure of the excalidraw JSON object. We should create a new section in the https://docs.excalidraw.com/docs, called "codebase" or similar, and in there a subsection called "excalidraw JSON schemas".

![image](https://github.com/excalidraw/excalidraw/assets/5153846/1889b195-b301-4ed3-a151-57d3d3e326c4)

(link to image: https://excalidraw.com/#json=54XfHr3o90dtOUitxMDQs,osCTni4kYRVRj2JvjF9Zfw)

**Comment by Rajni2002** [comment]
Hi I'm looking forward to work on this issue,
please assign it to me

**Comment by ad1992** [comment]
Sure @Rajni2002 go for it!

**Comment by Rajni2002** [comment]
<img width="1440" alt="Screenshot 2023-07-27 at 1 00 55 PM" src="https://github.com/excalidraw/excalidraw/assets/82713217/fe79ad26-a915-4d9d-8272-a4f2b1c6e200">

@ad1992 correct me is it right ?

**Comment by ad1992** [comment]
@Rajni2002 if you mean the path yes thats right, lets rename to `JSON Schema`, you can create a draft PR and we can discuss it there

**Comment by Rajni2002** [comment]
https://github.com/excalidraw/excalidraw/pull/6817
please have a look on this PR

**Comment by Rajni2002** [comment]
https://github.com/excalidraw/excalidraw/pull/6817

**Comment by Abhishek-90** [comment]
@ad1992 is this issue still available ? @Rajni2002 do you need any help with it? I am up for it.
