### ISSUE TITLE
Shift multi select stopped working with feat: make appState.selectedElementIds more stable #6745

### ISSUE THREAD

**Issue by zsviczian** [excalidraw/excalidraw#6806]
related: https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/1224

@dwelle, seems #6745 had side effects: 

https://github.com/excalidraw/excalidraw/assets/14358394/5925a3bb-fb18-429e-9f6f-69e899eaca53

**Comment by dwelle** [comment]
I noticed yesterday. Will make a fix during today.
