### ISSUE TITLE
Issue while pointing arrow from component item inside frame to component item outside frame

### ISSUE THREAD

**Issue by sagardspeed2** [excalidraw/excalidraw#6816]
So when we want to point some arrow outside frame, the arrow line is not working. the scope of arrow line only in frame, it is not coming outside of frame.

**Comment by ad1992** [comment]
@sagardspeed2 do you mean similar to whats mentioned in https://github.com/excalidraw/excalidraw/issues/6749 ?

**Comment by sagardspeed2** [comment]
@ad1992 yes, it is same.

**Comment by ad1992** [comment]
ok closing it in favor of #6749

**Comment by sagardspeed2** [comment]
Sure @ad1992
