### ISSUE TITLE
[feature] hope to move the convas only need hold on mouse right button

### ISSUE THREAD

**Issue by Ikki-Dai** [excalidraw/excalidraw#6820]
while to do some complex drawing, need to move the convas and have to click the 'hand' in tool bar.
hope to move the convas just need to hold on the right button of mouse

**Comment by dwelle** [comment]
Hi. We'll likely want to use the RMB for a different behavior, but you can pan the canvas using the wheel mouse button or cmd/ctrl+space+drag.

You can refer to the hints below the toolbar:

![image](https://github.com/excalidraw/excalidraw/assets/5153846/e86b5f49-42f0-451f-a974-709a13f78f1a)

**Comment by heliocarbex** [comment]
> while to do some complex drawing, need to move the convas and have to click the 'hand' in tool bar. hope to move the convas just need to hold on the right button of mouse

Like Miro! I think this could be very good.
