### ISSUE TITLE
Website whitelist

### ISSUE THREAD

**Issue by dreamyoak** [excalidraw/excalidraw#6830]
can i have my website whitelisted i need it so i can draw over it
(dreamyoak.xyz)
thanks fr

**Comment by dwelle** [comment]
Hi. Currently the web embeds can't be drawn over (they sit on top), so it wouldn't work the way you expect.

For now we're accepting more generally usable / widely requested embed domains. We'll be reviewing our options and whether we want to allow most domains later. 🙏

**Comment by isConic** [comment]
I've found a reference to the whitelist here: 
https://github.com/excalidraw/excalidraw/blob/5245276409b8d163c656c9d3a5e9028b8322a59b/packages/excalidraw/element/embeddable.ts#L48  

  
As of January 11th 2024 the following web-addresses are whitelisted: 
```
  "youtube.com",
  "youtu.be",
  "vimeo.com",
  "player.vimeo.com",
  "figma.com",
  "link.excalidraw.com",
  "gist.github.com",
  "twitter.com",
  "x.com",
  "*.simplepdf.eu",
  "stackblitz.com",
  "val.town",
  "giphy.com",
  "dddice.com",
```
