### ISSUE TITLE
lock isn't working 

### ISSUE THREAD

**Issue by Himanxu1** [excalidraw/excalidraw#6846]
the lock is the homescreen isn't working !
Not performing anything 
![exc](https://github.com/excalidraw/excalidraw/assets/80101755/f41c6207-83d1-46d4-9e4e-c9311f2359e3)

**Comment by sanskarfc** [comment]
What is the expected behaviour with the lock?

**Comment by ad1992** [comment]
The lock tool is to lock the current shape while drawing so you don't need to switch the tool once you leave the mouse as shown 👇🏻 

https://github.com/excalidraw/excalidraw/assets/11256141/e5e36b37-bd3f-4447-9424-bf2ecce1cb2a

Can you elaborate whats exactly not working ?

**Comment by Himanxu1** [comment]
@ad1992 oh i thought it would lock the canvas for not editing

**Comment by ad1992** [comment]
In that case you can check the lock option for elements under context menu @Himanxu1 

<img width="509" alt="Screenshot 2023-08-03 at 4 21 13 PM" src="https://github.com/excalidraw/excalidraw/assets/11256141/cb2bf0e9-623e-4dfb-b223-2827acf41cb3">
