### ISSUE TITLE
Keep newly created shapes as selected

### ISSUE THREAD

**Issue by nickfreemandesign** [excalidraw/excalidraw#6869]
Hey Excalidraw:

It would be really great to leave the newly created shapes as selected so a user can create the shape then modify the stroke or fill without having to select it once more. In order to change the color of the shape a user must either change the color / stroke first _then_ create the shape, or create the shape, select `v`, click on the shape to select it, then change the color / stroke. 

My apologies if there is already a ticket created for this and thanks for your consideration

**Comment by ad1992** [comment]
@nickfreemandesign once you leave your mouse after drawing, the shape is indeed kept selected. Could you elaborate on what exactly is missing ?

https://github.com/excalidraw/excalidraw/assets/11256141/ef2c6c49-d6d0-4984-a6b5-5ef748493862

**Comment by dwelle** [comment]
@nickfreemandesign  make sure the "tool lock" isn't enabled:

![image](https://github.com/excalidraw/excalidraw/assets/5153846/beb3215d-8f2c-4948-9996-1b1e507c35fe)

**Comment by nickfreemandesign** [comment]
Ah, this was the issue! Thank you for responding to me. I don't have this problem anymore.
