### ISSUE TITLE
cmd+z undo, cmd+c copy, cmd+v paste stop working sporadically on excalidraw.com

### ISSUE THREAD

**Issue by sompylasar** [excalidraw/excalidraw#687]
This might have to do with added keyboard shortcuts.

**Comment by vjeux** [comment]
This is still working for me. Do you have a sequence of steps you can use to repro?

**Comment by sompylasar** [comment]
Hmm, looks like sporadically, now it started working again after I did something... Also when it stops, then cmd+c, cmd+v also don't work.

**Comment by dwelle** [comment]
There's an open PR that rewrites the clip handling. https://github.com/excalidraw/excalidraw/pull/689

You can check the preview if it improves (or makes worse) your situation: https://excalidraw-git-clipboardrewrite.vjeux.now.sh/

**Comment by sompylasar** [comment]
> You can check the preview if it improves (or makes worse) your situation

Thanks! I just need to draw something quickly now so I don't have much time now to reproduce issues, sorry.

I reported the weird behaviors that I noticed related to keyboard shortcuts, it doesn't seem to be related with the actual clipboard behavior which works fine when the shortcuts work.

**Comment by dwelle** [comment]
Yes, the PR touches both. Your issue was likely connected to this: when you open contextMenu, pasting no longer works. That PR should fix this.

**Comment by sompylasar** [comment]
> Your issue was likely connected to this: when you open contextMenu, pasting no longer works.

But does undo work still, or it also stops working after context menu?

Looks like my issue is related to duplicating selection via option+drag, this happened again and not sure how to make it work again.

**Comment by dwelle** [comment]
Oh, I missed this issue is also about history. Yea, I'm seeing some weird stuff.

Can't repro any issues with duplicating selection via drag, and clipboard/history though.

**Comment by dwelle** [comment]
I think this should be fixed by #701. If not, please open a new issue with steps.
