### ISSUE TITLE
Typing into the color picker popup text field causes color selection via hotkey

### ISSUE THREAD

**Issue by sompylasar** [excalidraw/excalidraw#688]
Before typing "d", want to add the opacity component to the color hex code (`#ffffffdd`):
<img width="227" alt="Screen Shot 2020-02-03 at 11 46 30 AM" src="https://user-images.githubusercontent.com/498274/73685404-f6df3880-467a-11ea-82ac-08b79c4f3b7c.png">

After typing "d", green color is selected ("d" stands for green)
<img width="227" alt="Screen Shot 2020-02-03 at 11 46 41 AM" src="https://user-images.githubusercontent.com/498274/73685410-f8a8fc00-467a-11ea-9291-2beeb5a3160d.png">

**Comment by vjeux** [comment]
cc @dwelle 

For "d" stands for green, if you look, the shortcuts mirror the qwerty layout. So you can pick the right color based on keyboard location. If you're using azerty or other layouts, you're out of luck though :(

**Comment by dwelle** [comment]
Umm, we should prevent shortcuts if user is typing into input box, for sure.
