### ISSUE TITLE
querySelector in InteractiveCanvas.tsx is generating type errors

### ISSUE THREAD

**Issue by zsviczian** [excalidraw/excalidraw#6885]
https://github.com/excalidraw/excalidraw/blob/9e0bfd178e77e7a524496aa4fa22d81dd3b4e526/src/components/canvases/InteractiveCanvas.tsx#L108-L110

The approach in the code above does not seem compatible with having multiple instances of Excalidraw in the same window (like in Obsidian)

<img width="881" alt="image" src="https://github.com/excalidraw/excalidraw/assets/14358394/c22cb60d-765d-46f5-84de-70ed153526c2">

**Comment by dwelle** [comment]
Can you create a repro case on codesandbox? I'm rendering two instances and it works fine.
