### ISSUE TITLE
Pressing "shift" when resizing a rectangle sets the aspect ratio to square; releasing it does not reset to non-constrained, keeps square

### ISSUE THREAD

**Issue by sompylasar** [excalidraw/excalidraw#690]
Expected behavior:
- When creating a rectangle, holding shift should make it a square (constrained aspect ratio), releasing shift should reset to unconstrained creating.
- When resizing an existing rectangle, holding shift should constrain to the aspect ratio of the rectangle before resize (not square if it wasn't square); releasing shift should reset to unconstrained resizing.

**Comment by dwelle** [comment]
Yep, we should align it with how most apps do it, as you say.

- 1st point:
    
    ![excalidraw_proportional_resize_1](https://user-images.githubusercontent.com/5153846/73696093-cd0a2e00-46db-11ea-9c8b-812e8357a48b.gif)

- 2nd point:

    ![excalidraw_proportional_resize_2](https://user-images.githubusercontent.com/5153846/73696098-d1cee200-46db-11ea-8894-71f59bf8a6b4.gif)

**Comment by enzoferey** [comment]
Actually different drawing tools use different heuristics on this. I prefer Figma approach on the problem. They always use X axis and they shift between constraint and non constraint when pressing shift without need for movement.

I have implemented initial aspect ratio respect at #768 and if we want to move towards what Figma does we will need to do two things:

1. Store initial resize element and not mutate it. So if you free transform and the move to constraint you have the data required to interpolate the deltas into the constraint move and viceversa.
2. When clicking shift we should apply the heuristics described in previous step so the element being dragged (creation) or resized (edition) gets transformed without need for mouse movement.

**Comment by dwelle** [comment]
What you're showing from figma is IMO identical to what I've shown from Affinity.

**Comment by enzoferey** [comment]
Resizing (second point), yes, creating (first point), no.

Notice that when switching between free and constraints in Affinity current mouseX is not respected (and it's rather a proportion based how much you moved the mouse since mouse down event) and in Figma mouseX is respected at all times (which I personally prefer).

**Comment by dwelle** [comment]
You're right. What Figma does it better.

**Comment by lipis** [comment]
This should be fixed now!
