### ISSUE TITLE
finger coordinates when navigating do not match my expected view

### ISSUE THREAD

**Issue by anatoliibakhtin** [excalidraw/excalidraw#6913]
Dear excalidraw developer hello👋🏻
Please pay attention to the navigation with fingers on the canvas when I move my fingers, the coordinates of the fingers are different from the expected view, so that it gives a feeling of sluggishness-randomness-uncontrollable, video:

https://github.com/excalidraw/excalidraw/assets/71871141/86746e3b-c8b7-4726-983a-236d1ef53e26

Could you fix this or give a reasoned answer why it will not change ? And thanks for your attention!🌳

p.s. navigation with 1 finger is almost what I need, but I move with 2 fingers, not one
https://github.com/excalidraw/excalidraw/assets/71871141/8d30c519-5f59-475c-89be-4221d1a0e949

**Comment by ad1992** [comment]
@anatoliibakhtin thanks for reporting the issue!
could you also share which device/ browser you are using ?

**Comment by anatoliibakhtin** [comment]
> @anatoliibakhtin thanks for reporting the issue!
> could you also share which device/ browser you are using ?

 You're welcome 🤗
Place: [Google Chrome 116.0.5845.92](https://play.google.com/store/apps/details?id=com.android.chrome), [Yandex start 23.72](https://play.google.com/store/apps/details?id=ru.yandex.searchplugin), [Samsung Internet 22.0.3.1](https://play.google.com/store/apps/details?id=com.sec.android.app.sbrowser), [Obsidian-Excalidraw-plugin](https://github.com/zsviczian/obsidian-excalidraw-plugin): Obsidian version: 1.4.6 (105); Excalidraw v1.9.16
Phone: android 9 (samsung SM-G892U)

**Comment by anatoliibakhtin** [comment]
@ad1992 please tell me dear Akashi, are you planning to solve this problem in the near future, or should I ask Zsviczian to make these improvements if he is interested?

Thanks for your attention

**Comment by anatoliibakhtin** [comment]
Good day, @ad1992 ☀️ I am writing to draw attention to this wish. Thanks and have a nice day

**Comment by anatoliibakhtin** [comment]
@ad1992 @dwelle ?

**Comment by dwelle** [comment]
should be fixed in this PR https://github.com/excalidraw/excalidraw/pull/7849 — before it's merged, can you check if it's fixed for you? https://excalidraw-col7hl2fh-excalidraw.vercel.app/

**Comment by anatoliibakhtin** [comment]
Hi, I am very happy to receive this message! 

I checked it out, it fixes the motion on canvas, awesome! It doesn't slow down now! (example in the video, 1 is the old version, 2 is the new version, 3 is google keep) thanks!

https://github.com/excalidraw/excalidraw/assets/71871141/656004b7-9540-4c66-94be-2492e3a406af


For full happiness, could you please see and fix the zoom function working?

Example video below: I put 2 fingers and zoom with one finger. objects are shifting even though they shouldn't. video: 1 old version, 2 new version, 3 google keep

https://github.com/excalidraw/excalidraw/assets/71871141/f8d16ed9-ee32-4beb-850b-65c51faf9ca8

Thanks for your attention!

**Comment by dwelle** [comment]
> Example video below: I put 2 fingers and zoom with one finger. objects are shifting even though they shouldn't. video: 1 old version, 2 new version, 3 google keep

I didn't even notice this. Annoying indeed. Can you open a new issue for this if not already open?
