### ISSUE TITLE
Drag selection: drag left to select touched elements vs. drag right to select fully enclosed elements

### ISSUE THREAD

**Issue by sompylasar** [excalidraw/excalidraw#692]
This video illustrates the two kinds of selection: https://youtu.be/mYq511ZH6gQ 
(source: https://www.cadsessions.com/quick-tip-right-vs-left-drag-selection/ ).

The two selection modes are quite natural in vector editors, so it would be nice in excalidraw to improve UX for crowded pictures.

Currently excaludraw implements the fully enclosed selection only.

**Comment by vjeux** [comment]
Wow, this feels like black magic to change the selection behavior based on the direction of the drag.

It's definitely an issue to only have one type available. Sometimes you want one, sometimes the other. Now... I'm not sure that using the direction as a proxy is a good strategy.

**Comment by sompylasar** [comment]
It's like that in many graphics editors, I'm sure. I was surprised to not find it in excalidraw because this was so intuitive for me to try (heavily used to this feature in other editors).

**Comment by sompylasar** [comment]
Just tried some moder ones, looks like it's not present in Google Slides or Sketch... they both seem to always do touched elements. That's unfortunate.

I'm sure it's present and very helpful in AUTOCAD and Flash.

**Comment by sompylasar** [comment]
Here's from AUTOCAD documentation: https://knowledge.autodesk.com/support/autocad-lt/learn-explore/caas/CloudHelp/cloudhelp/2019/ENU/AutoCAD-LT/files/GUID-243E4DD0-8947-4905-AFE2-BE9B903A8C3F-htm.html

> To create a lasso selection, click, drag, and release the mouse button.
> Do one of the following:
> - Select individual objects by clicking them.
> - Drag from left to right to select all objects that are entirely enclosed in the selection rectangle or lasso (window selection).
> - Drag from right to left to select all objects that are crossed by the selection rectangle or lasso (crossing selection).

**Comment by dwelle** [comment]
Can't say I've ever noticed this behavior in any app. Figma doesn't do this, nor Affinity, (not sure about Adobe), nor Blender 3D. CAD software supposedly does it, but that's pretty pro, and I don't think users of excalidraw would know about this.

That being said, I don't think I ever select from right-to-left (maybe left-handed people do it?).

Ad our model (select only fully enclosed objects): not sure how prevalent this is. Figma doesn't do it, but Affinity does (so we're not alone).

**Comment by vjeux** [comment]
Thanks for the suggestion but this behavior is way too magical to me. The current behavior is not optimal in all the contexts but I believe good enough for most cases. Not planning to change it until we come up with a better solution.

**Comment by tkanarsky** [comment]
I'm gonna put up a PR for this, I'm surprised this isn't standard behavior.
