### ISSUE TITLE
implement multiplayer undo/redo

### ISSUE THREAD

**Issue by lizuncong** [excalidraw/excalidraw#6927]
As we can see in https://github.com/excalidraw/excalidraw/pull/6926. In the collaborative mode, users can only undo and redo their own modifications, and the data synchronized by other terminals cannot be undone.

**Comment by theonlypwner** [comment]
Duplicate of #5375?

**Comment by dwelle** [comment]
Will be fixed soon, actively working on it! 🙏

(for now closing as duplicate as noted above)
