### ISSUE TITLE
What is the bar at the bottom that is on top of the hint system and the language selector?

### ISSUE THREAD

**Issue by GasimGasimzada** [excalidraw/excalidraw#693]
![Screen Shot 2020-02-04 at 1 47 54 PM](https://user-images.githubusercontent.com/807231/73733200-f6b36b80-4754-11ea-8d6f-f29ce4e15d55.png)

**Comment by dwelle** [comment]
That's https://github.com/excalidraw/excalidraw/pull/583. There's a discussion to move it inside the scene menu.

Why it's full-width is a question. What browser are you using?

**Comment by GasimGasimzada** [comment]
I am on Safari. So, this only exists if there is more than one scene, right? Because it doesn't appear in Chrome browser for me...

**Comment by dwelle** [comment]
Yes, it shows only after you load a scene from backend (via `?id=`), so that you can switch between previous scenes you loaded. If you feel like, you can move it to the scene menu in the PR alongside the hint improvements.
