### ISSUE TITLE
Grid is jittery on https://staging.excalidraw.com/

### ISSUE THREAD

**Issue by zsviczian** [excalidraw/excalidraw#6934]
When you zoom in and out the position of the grids change

https://staging.excalidraw.com/

The issue was introduced with the canvas partitioning #6759

**Comment by dwelle** [comment]
Not related to the canvas partitioning. That strange expression was just moved from call site into the `strokeGrid` function in https://github.com/excalidraw/excalidraw/pull/6779, but it must have been incorrectly reverted while resolving conflicts when merging master to the canvas partitioning PR. Thanks for catching this!
