### ISSUE TITLE
Add excalidraw source in  exported PNG and SVG to be able to reimport them later

### ISSUE THREAD

**Issue by allan-simon** [excalidraw/excalidraw#6948]
Use case:  3 month after exporting a PNG you want to edit again in excalidraw and... you lost the original file

Idea: both SVG and PNG format allow for a comment field/metadata fields 

it would be great if the comment use by the .excalidraw format would be present in said field, so that one can reimport a PNG with said metadata, and excalidraw would be able to reload the initial schema from it

**Comment by allan-simon** [comment]
for example that's done by plantuml 

https://plantuml.com/en-dark/faq#0bb4912b52689d3d

>  Furthermore, the diagram data is stored in PNG metadata, so you can fetch it even from a downloaded image.

**Comment by zsviczian** [comment]
Good news! This is already implemented. Or you are looking for something more?

![image](https://github.com/excalidraw/excalidraw/assets/14358394/4d9efc42-e863-4fd4-90a9-85e97bdb2bc9)

**Comment by allan-simon** [comment]
ah nice ! no no that's great, for how long has it been here ? I have some 1 year old png coming from excalidraw that for once was not uploaded on our Wiki along with their .excalidraw so I came directly here but I forgot to check if it had not evolved since
