### ISSUE TITLE
Feature request: export presentation to PDF

### ISSUE THREAD

**Issue by Irubataru** [excalidraw/excalidraw#6949]
As with most presentation frameworks, when you are done giving a presentation, people usually want a copy of it. It would be great if you could export the presentation as a PDF file that you can distribute.

**Comment by Toseef-Ahmad** [comment]
Nice suggestion.!

**Comment by Toseef-Ahmad** [comment]
I'm going to working on it.!

**Comment by carlsverre** [comment]
This is a critical feature to be able to use Excalidraw for conference presentations as most conferences require slides to be submitted via PDF ahead of time. Eventually I hope conferences will accept shared links to presentations, but for now this feature is super important to increase Excalidraw usage at major conferences.

As a short term solution, having the ability to export all slides as numbered images would allow for manual PDF conversion.

Thanks to all the contributors and staff of Excalidraw for making such a fantastic tool. I hope to use it for conference presentations sometime soon!

**Comment by ksdavidc** [comment]
export to video???!! 
- create auto run feature (or does it already exist?)
- Have a way to encode duration of each slide
- record video?? I guess it could be done with screengrab software

**Comment by TobTobXX** [comment]
See also #1800 for exporting PDFs.

**Comment by TobTobXX** [comment]
I'm sorry, I am very confused. Is this https://excalidraw.com/ ? Or what app is this?

**Comment by jan-queralt** [comment]
> I'm sorry, I am very confused. Is this https://excalidraw.com/ ? Or what app is this?

yes, it's Excalidraw+

**Comment by TobTobXX** [comment]
Ah, so it's not available in the free code?
Would the project still be open to a PR to implement it in the open source code?
