### ISSUE TITLE
Firefox doesn't render text on fresh load

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#695]
Steps:

1. open fresh tab in firefox
2. load https://excalidraw.com/?id=5092074957307904
3. text not rendered until new scene render (e.g. try scrolling)

![excalidraw_ff_text_render_bug](https://user-images.githubusercontent.com/5153846/73738186-4b021f80-4744-11ea-875c-d216c6d02285.gif)

**Comment by Fausto95** [comment]
I'm using FF Nightly(`v74.0a1 `) and the text gets rendered on the first try, but the font isn't, I need so click somewhere on the canvas in order to get the good font!

**Comment by dwelle** [comment]
Right. Yes, I didn't dig deep, and I suspected it's font-related. https://github.com/excalidraw/excalidraw/issues/637 seems related except I can't repro that on chrome, and this issue also related to restore from localStorage etc.

**Comment by lissitz** [comment]
Firefox doesn't support `rel=preload` so the font is not initially requested. Calling `newTextElement` creates a span with the font in `measureText` so I guess that triggers the font request after rerender. Firefox doesn't fetch on first render, Nightly does fetch but paints with a fallback font, no idea why they behave differently.

Creating a htmlElement that uses `font-family: Virgil` (`Cascadia` is already used in the page) and rerendering after fonts are ready seems to solve it in both nightly and stable . It's a bit hacky, though...

https://github.com/excalidraw/excalidraw/compare/master...lissitz:csb-1580854589494

**Comment by lipis** [comment]
Is that still an issue?

**Comment by dwelle** [comment]
Hmm, meanwhile it morphed into a different one: it visible renders the text, but in some fallback font, and our Virgil font won't render until the scene is redrawn (the elements `canvas`/`shape` is regenerated). Should we open a new issue for this or track it here?

**Comment by lipis** [comment]
Let's do a new one!
