### ISSUE TITLE
disable reverse binding from shapes to arrows

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#6952]
Currently we binding to arrows bidirectionally, that is you can bind an arrow to a rectangle, but you can also binding a rectangle to an arrow (by dragging).

This results in too many false positives when dragging an element into a vicinity of an arrow auto-binds it which you often don't want.

I'm proposing disabling binding from shape->arrow, and only keep the arrow->shape.

EDIT: poll [here](https://twitter.com/excalidraw/status/1697286297281282324). Seems like vast majority in favor.

**Comment by kavandalal** [comment]
@dwelle  is the issue still open? I want to try.

**Comment by dwelle** [comment]
@kavandalal currently being implemented over at https://github.com/excalidraw/excalidraw/pull/6947 @sjoelee where we're changing the scope of the PR.

**Comment by Prathamesh314** [comment]
I would like to give a try to solve this issue.

**Comment by sjoelee** [comment]
@Prathamesh314 I'm currently working on it, will be updating PR soon.

**Comment by sjoelee** [comment]
PR submitted: https://github.com/excalidraw/excalidraw/pull/6947. Please take a look when you get a chance.
