### ISSUE TITLE
Why is draw on P and Diamond on D ?

### ISSUE THREAD

**Issue by ElliIsmail** [excalidraw/excalidraw#6959]
Hello !

First of all I would just like to preface this by saying that I love the app.

I think that UI/UX would hugely benefit from moving Draw to D and Diamond to something else. I'm pretty confident that Draw is way more used than Diamond and probably by a huge margin. P is just way too far from regular left hand on keyboard + right hand on mouse ? We can at least have maybe something like photoshop with B for brush or pencil or something similar?

Thank you! :D

**Comment by kavandalal** [comment]
Hi @ad1992 , I would like to do this task, can you confirm the new shortcuts ?

**Comment by ElliIsmail** [comment]
Hi!
Thank you for your response :D
I was wondering if you guys did manage to deploy this enhancement ?

Thank you again !

**Comment by dwelle** [comment]
note: the freedraw is now accessible under both `7`, `P`, and `X` (although the `X` is undocumented and may change in the future). We will also allow keyboard customization in the future.
