### ISSUE TITLE
Image links are broken

### ISSUE THREAD

**Issue by orperel** [excalidraw/excalidraw#6978]
Hi team,

Excalidraw+ user here - many drawings of mine display a "n/a image" all of the sudden (gray placeholder, as if the image is not there).

These are all drawings which I've been using for the past weeks with no issues.
The issue even persists with new drawings I started today: pasting an image and switching back and forth to a different drawing shows broken links.

This issue is stopping me from using my drawings at the moment, can you please assist?
Thanks in advance!

**Comment by pikatwinky** [comment]
I don't know if this is related, but i cant embedd none type of image links using Web Embedds. When doing so, i recieve each time the next message 
![image](https://github.com/excalidraw/excalidraw/assets/31860235/dfcc5d46-8630-46ea-9ef6-0f1070a5be22)
I've tried embedding links to jpg, png, gifs, etc

**Comment by dwelle** [comment]
@pikatwinky that's for embedding websites (e.g. youtube links), not images. For images, use this button:

![image](https://github.com/excalidraw/excalidraw/assets/5153846/f3d8949e-7742-48ca-8126-fb382df2df9c)

Or simply copy/paste an image, or drag & drop it on canvas.

---

@orperel sorry for missing the issue over here, but I see you were able to contact us over at Discord. If the issue persists, please reach us over there or over the email (`support@excalidraw.com`). 🙏
