### ISSUE TITLE
Refreshing while mid-arrow creation breaks the app

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#698]
Steps:

1. start creating multi-point arrow
2. refresh browser
3. restores the scene into an undefined state (I can't then create elements etc.)

Note: not related to https://github.com/excalidraw/excalidraw/pull/697

Likely solution: ensure we finalize arrow on `unload` (and possibly `blur` to also fix https://github.com/excalidraw/excalidraw/issues/668).

/cc @GasimGasimzada

**Comment by GasimGasimzada** [comment]
One question that I would like to know about. Do, we need `draggingElement`, `multiElement`, `resizeElement`, `editingElement` in localStorage? Currently, the issue happens because of it.

**Comment by GasimGasimzada** [comment]
#697 I removed these values from appState and everything works fine.

**Comment by dwelle** [comment]
Yep, seems to have fixed it, and I agree -- we shouldn't persist those.
