### ISSUE TITLE
Seed roughjs randomness

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#70]
Unfortunately roughjs will not implement adding a seed for randomness ( https://github.com/pshihn/rough/issues/27 ). That's unfortunate because when we serialize content to disk, we lose the same random options and loading the scene back will look slightly different.

Fear not, we should be able to override Math.random with a custom pseudo random number generator that allows a seed: https://stackoverflow.com/a/47593316/232122, call roughjs and revert it back.

**Comment by dwelle** [comment]
Might also help in #66. WTBS, won't this make shapes look similar (if not identical -- though that would likely require them having the same size)?

**Comment by vjeux** [comment]
The idea is to use the real Math.random() to generate a seed that we will store inside of the element data. So each element is going to have a different seed.
