### ISSUE TITLE
Undo/redo doesn't work if element selected

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#700]
Not sure when this regression was introduced.

Steps:

1. select element
2. resize it
3. `cmd+z`/`ctrl+z` to undo.
4. Doesn't do anything until you deselected.

We're probably preventing it FSR.

**Comment by Fausto95** [comment]
Something related to history!

**Comment by sompylasar** [comment]
Is this a duplicate of #687? Do cmd+c/cmd+v work for you?

**Comment by dwelle** [comment]
Not sure, since in that issue the cause is unclear (no repro steps). Either way, this will be fixed  in #701.

**Comment by dwelle** [comment]
fixed in #701
