### ISSUE TITLE
BUG: Unable to change labels on Frames since Sep 20th Update

### ISSUE THREAD

**Issue by torves** [excalidraw/excalidraw#7023]
Previously I was able to rename the default label of a frame (Frame 1 for example) by double clicking onto the label.
As of Sep 21st I am no longer able to edit frame labels.

Edit:
This was tested on Windows desktop using Firefox and Chrome.
Was unable to reproduce on Android Chrome Mobile (working as intended).

**Comment by mrenner-ML** [comment]
Same here

**Comment by mcndt** [comment]
Same for me in Chrome 116, arm64 build, MacOS.

**Comment by dwelle** [comment]
Hey, forgot about this. On it!
