### ISSUE TITLE
Merging the eyedropper fix to the Obsidian fork I am getting build errors

### ISSUE THREAD

**Issue by zsviczian** [excalidraw/excalidraw#7030]
It seems related to: #7019
@dwelle: I can't figure out what is causing these errors. Do you have any suggestions on where to look?

![image](https://github.com/excalidraw/excalidraw/assets/14358394/8b8434bc-c3ee-4941-9b0b-5e6ea4c9fc89)

**Comment by zsviczian** [comment]
I am not yet sure about why, and not clear about the side effects, but bumping package versions for react types solved the issue for me... maybe just had to reinstall react types because it got corrupted (not sure how though)

package.json old:

```json
  "devDependencies": {
    "@excalidraw/eslint-config": "1.0.3",
    "@excalidraw/prettier-config": "1.0.2",
    "@types/chai": "4.3.0",
    "@types/jest": "27.4.0",
    "@types/lodash.throttle": "4.1.7",
    "@types/pako": "1.0.3",
    "@types/pica": "5.1.3",
    "@types/react": "18.0.15",
    "@types/react-dom": "18.0.6",
```

working:
```json
  "devDependencies": {
    "@excalidraw/eslint-config": "1.0.3",
    "@excalidraw/prettier-config": "1.0.2",
    "@types/chai": "4.3.0",
    "@types/jest": "27.4.0",
    "@types/lodash.throttle": "4.1.7",
    "@types/pako": "1.0.3",
    "@types/pica": "5.1.3",
    "@types/react": "18.2.22",
    "@types/react-dom": "18.2.7",
```

**Comment by dwelle** [comment]
No idea. I reinstalled node_modules just to make sure, but no issues. From the screenshot it does look like React related indeed.

If you face the error again, please reopen, and also list `npm ls @types/react @types/react-dom`.

**Comment by zsviczian** [comment]
I am now merging master changes into the obsidian fork on my mac (previous errors were on my windows desktop). I am again getting React errors... though slightly different, yet similar

<img width="942" alt="image" src="https://github.com/excalidraw/excalidraw/assets/14358394/df5ec8b3-d133-47a7-8a8b-499611148d02">


<img width="506" alt="image" src="https://github.com/excalidraw/excalidraw/assets/14358394/baf3979c-6a6f-4e79-aefc-38d88e287a2a">
