### ISSUE TITLE
A tool to convert arrows to lines and back

### ISSUE THREAD

**Issue by sompylasar** [excalidraw/excalidraw#704]
While there's no multi-point arrows, it might be useful to have a simple toggle when selecting an arrow or a line to convert one to another.

**Comment by dwelle** [comment]
There are multi-point arrows btw (unless you mean something else). Also, this issue should cover this as part of allowing to switch arrow ends (no arrow end included): https://github.com/excalidraw/excalidraw/issues/657

Closing. If you feel it doesn't overlap, lemme know.

**Comment by sompylasar** [comment]
On nice, didn't notice the hint about clicking to start multi-point. It smoothes the curves, so not ideal for my use case, I need sharp turns, and some turns end with arrowheads, so I'm using separate arrows for that and it would be nice to be able to switch arrowheads. That issue seems to fit.
