### ISSUE TITLE
Typo on Homepage of Developer Docs

### ISSUE THREAD

**Issue by atorcode** [excalidraw/excalidraw#7041]
I set out to look through the developer docs in order to learn the codebase when I stumbled upon a fairly prominent typo on the homepage.

Currently, the problematic sentence reads, "Want to build your own app powered by Excalidraw **by** don't know where to start?"

It should say "Want to build your own app powered by Excalidraw **but** don't know where to start?

![excalidraw-typo](https://github.com/excalidraw/excalidraw/assets/95320421/275b5723-4c3b-46e5-9654-8e74aef39334)

Here is the line in the source code that needs to be changed.
![excalidraw-typo-source](https://github.com/excalidraw/excalidraw/assets/95320421/83256c76-7e66-4868-8df4-ee5ea7a10ffe)

May I submit a PR to fix this typo?

**Comment by DanielJGeiger** [comment]
Closing as completed by #7047.
