### ISSUE TITLE
Virgil font for frontend project

### ISSUE THREAD

**Issue by sahajkedia** [excalidraw/excalidraw#7044]
Hi, 
I want to use this font in my react-frontend project. Can you guide me?

**Comment by Smit1610** [comment]
can you please tell in detail what is to be done ?

**Comment by sahajkedia** [comment]
I want to use Virgil font in my react project. How can I do that.

**Comment by Smit1610** [comment]
can you please image where you seen Virgil font ?

**Comment by h3ct0rjs** [comment]
This issue should be closed, is not related to the excalidraw project, you also should use a flag `user-question`.  Just to answer the question you can use the Virgil font as it appears here : 

https://github.com/excalidraw/excalidraw/blob/2e61926a6b0bf01a49db167979ea53a618b0ef2a/src/index-node.ts#L52
and 
https://github.com/excalidraw/excalidraw/blob/2e61926a6b0bf01a49db167979ea53a618b0ef2a/src/index-node.ts#L57

The font assets can be found here : 

https://github.com/excalidraw/excalidraw/tree/2e61926a6b0bf01a49db167979ea53a618b0ef2a/public

@sahajkedia can you close this? 

Best Regards, 
H

**Comment by dwelle** [comment]
@h3ct0rjs that relates to Node.js usage

@sahajkedia you can just link to the font from your index.html file and declare the font-face to use it:

```html
<link
  rel="preload"
  href="/Virgil.woff2"
  as="font"
  type="font/woff2"
  crossorigin="anonymous"
/>
```
```css
@font-face {
  font-family: "Virgil";
  src: url("Virgil.woff2");
  font-display: swap;
}
```

You can ask more questions in Discussions or over at our Virgil font repository https://github.com/excalidraw/virgil

**Comment by sahajkedia** [comment]
Hi,
I tried to use this in my project but this doesn't work.
P.S. I haven't downloaded the Virgil.woff2. Is that required.

Please guide me.

Sahaj

**Comment by h3ct0rjs** [comment]
@sahajkedia create a new discussion  here : https://github.com/excalidraw/excalidraw/discussions 
Regards, 
H
