### ISSUE TITLE
Feature request : Instantly deleted marker

### ISSUE THREAD

**Issue by AbdelazizSharaf001** [excalidraw/excalidraw#7048]
Looking at jamboard.google.com
I found a good tool that follow cursor and appear as it self delete point by point rapidly called Lazer
I think implementing it would be a good addition

![Screenshot_20230927_105341](https://github.com/excalidraw/excalidraw/assets/36330265/b20c2fb8-3b44-455a-a83b-8baa131ffb28)

```[tasklist]
### Alternatives
- [ ] Add Lazer tool
- [ ] Make draw tool act as Laser
```

**Comment by dwelle** [comment]
Will be release next week! https://excalidraw-o1xrjhgtb-excalidraw.vercel.app/ https://github.com/excalidraw/excalidraw/pull/6739

Duplicate of https://github.com/excalidraw/excalidraw/issues/5351
