### ISSUE TITLE
Don't select color input on click

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#705]
From: https://github.com/excalidraw/excalidraw/pull/694#issuecomment-582028913 by @sompylasar

> My preference is against such behavior in any text field, it's so frustrating, I know how to select text (double click or shift home) if I need to delete it, but in excalidraw, if I instead of selecting a swatch decided to use the text field, I usually want to tweak the color, for example add the opacity byte, not always fully replace it (and even if I did fully replace, I have alternatives). This change fixes one aspect of my workflow and breaks/slows down the other, both were mentioned on the bug report.

I actually changed my mind since the PR on this, and agree we probably shouldn't do this.

**Comment by muzakparov** [comment]
@sompylasar Thank you for your feedback! It was just a personal preference. That's why I wasn't sure and asked for feedback. Changing it soon.

**Comment by dwelle** [comment]
@sompylasar no problem :). I wasn't sure myself but didn't see it as an issue until someone elucidated a use case.
