### ISSUE TITLE
Cannot reorder slides in presentation mode

### ISSUE THREAD

**Issue by LucasMoskun** [excalidraw/excalidraw#7058]
Create multiple slides. 

Create a new slide and then drag it somewhere that isn't at the bottom. For example, if there are 18 slides move it to the 10th position.

Start a presentation and start iterating through the slides. The slide you moved will not be shown 10th, it will be shown 18th.

I would expect the slide that I have moved to be displayed at the index it has been dragged to on the sidebar.

**Comment by dwelle** [comment]
We'll look into it, thanks for the report!
