### ISSUE TITLE
Arm64 support?

### ISSUE THREAD

**Issue by steveiliop56** [excalidraw/excalidraw#7059]
What about docker arm64 images?

**Comment by h3ct0rjs** [comment]
@steveiliop56 you can build you docker images for arm64 using the base Dockerfile that exists , you can check here : 


https://www.padok.fr/en/blog/docker-arm-architectures

Regards, 
H

**Comment by steveiliop56** [comment]
Yeah I saw that I was just wondering about you providing an official image...

**Comment by steveiliop56** [comment]
I guess not for now...
