### ISSUE TITLE
Add Python Web Embed like on python.org

### ISSUE THREAD

**Issue by egorvdot** [excalidraw/excalidraw#7062]
Hello!

Could you add a new allowed domain for Python embedding, such as on https://www.python.org/shell/?
python.org integrates with pythonanywhere.com
It would be great to be able to prototype software without having to share the screen.

--
Egor V.

**Comment by h3ct0rjs** [comment]
@egorvdot are you saying to embed [excalidraw.org](https://excalidraw.com/) in python.org ?

Regards, 
H

**Comment by Jatinjain07Dazai** [comment]
I would love to work on it can you assign it to me ?

**Comment by hjimenez-godaddy** [comment]
I can't assign right now, but you can send a pr

**Comment by h3ct0rjs** [comment]
I can't assign right now, but you can send a PR

**Comment by egorvdot** [comment]
@h3ct0rjs no, I’m not.
I want to use Python vanilla console on Excalidraw page in Web Embed.
Can you realise it?

**Comment by developer-gagandeep-singh** [comment]
On which page you want this feature @egorvdot

**Comment by egorvdot** [comment]
@developer-gagandeep-singh Sorry, I don't understand.
I'm talking about REPL on Excalidraw canvas in Web Embed.
![image](https://github.com/excalidraw/excalidraw/assets/47248443/cfc07394-f896-4c7d-8216-0d104398e59b)

I want to past link to Web Embed on online REPL
and get worked Python interpreter like on python.org 
![image](https://github.com/excalidraw/excalidraw/assets/47248443/e68a481d-1686-46fa-995a-d9260841a631)

**Comment by h3ct0rjs** [comment]
Hi @egorvdot In this context,  

I think that it would be better to have a discussion here https://github.com/excalidraw/excalidraw/discussions . 
Since this is not an open issue, can you proceed to close in the meantime, it could be a disscusion. 

Regards, 
H

**Comment by egorvdot** [comment]
@h3ct0rjs Ok!
Issue is closed due to the idea wasn't discussed with team.
