### ISSUE TITLE
Download Issue

### ISSUE THREAD

**Issue by EswaraSatya** [excalidraw/excalidraw#7076]
When trying to download when frame is available on excalidraw canvas frame is not displayed on the downloaded png/svg/image

![image](https://github.com/excalidraw/excalidraw/assets/101344518/dc3e9aa4-5028-463c-b0e0-dd1d19b4f544)

![image](https://github.com/excalidraw/excalidraw/assets/101344518/c6baa78b-b955-406d-b608-380ac3158bd0)

**Comment by Satya2234** [comment]
I would like to work on it

**Comment by dwelle** [comment]
By design, but we are indeed considering rendering frames on export (when not exporting a single frame).

Adding discussion label to make a final decision.

**Comment by dwelle** [comment]
fixed via https://github.com/excalidraw/excalidraw/pull/7210
