### ISSUE TITLE
Issue when pasting text

### ISSUE THREAD

**Issue by JCassio1** [excalidraw/excalidraw#7077]
### **Description**
This is a bug that I have discovered whilst copying and pasting text across the whiteboard. 

### How to replicate

1. Create a square with text inside it
2. Duplicate the square (e.g. using Command + D)
3. Try to replace the text by pasting it in the newly created box

![B29EA845-0042-4FA0-9702-8FD8B6978B72](https://github.com/excalidraw/excalidraw/assets/20714698/4c21aece-000c-49f3-9a72-5e82f12c3c44)

<img width="1335" alt="Screenshot 2023-10-03 at 18 49 14" src="https://github.com/excalidraw/excalidraw/assets/20714698/639b38a0-0a5f-4b53-9541-a0ec6b89e4e9">

**Comment by Anirud2002** [comment]
Hey,
I didn't find any issue with copy and pasting of text. 

Can you give more detailed steps to reproduce the bug?

**Comment by JCassio1** [comment]
Hi!

This is a strange one. I tried again this morning and I could no longer replicate the issue. It only happened yesterday it seems. 

I will be closing this issue and revisit if I experience it again.

Thanks

**Comment by Fausto95** [comment]
I ran to this exact same bug today, trying to find ways to reproduce it.

**Comment by Fausto95** [comment]
Ok, I figured out what happened, my clipboard content was actually an excalidraw element(as text).

We could probably detect if the clipboard content we are pasting into a text element is an excalidraw element perhaps we should disable pasting.
