### ISSUE TITLE
Grid regression introduced with the snapping PR

### ISSUE THREAD

**Issue by zsviczian** [excalidraw/excalidraw#7082]
The issue was introduced with this PR: #6256

https://github.com/excalidraw/excalidraw/assets/14358394/5ca3d9f5-6fb4-4a4a-83a4-ea1a0d82d185

**Comment by TheBrahmnicBoy** [comment]
Especially noticeable with large groups of objects from Excalidraw libraries

![04-10-23   explorer_3755 ](https://github.com/excalidraw/excalidraw/assets/82528318/9a7723ff-324a-4a69-bc2b-f833ea2bfc41)

**Comment by rkjc** [comment]
Thank you, this issue had made Excalidraw unuseable for me.

**Comment by DavidOpDeBeeck** [comment]
Being a paying customer for Excalidraw+ it is pretty astounding that this regression remains unfixed for more than 3 weeks. How is the initial pull request not reverted when this breaks all diagrams using the grid layout.

**Comment by dwelle** [comment]
Apologies, completely flew under the radar. We'll prioritize fixing this!
