### ISSUE TITLE
Migrate away from localStorage

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#711]
I'm not sure how big of a problem this is, but for large scenes, serializing state into localStorage exceeds its quota (5MB) and fails.

For example, this test scene with 4096 elements is ~8MB large when serializing to localStorage: www.excalidraw.com/?id=5461085259825152 (check console to see the error).

We can move to indexedDB to solve this.

For now, this seems to be an edge case, but soon our internal data structure may get more complex and require more space, and thus less elements on a scene may exceed the quota.

**Comment by vjeux** [comment]
We’re currently storing the shapes temporary rendering which is massively bloating the size. We should drop it and recompute it on load.

**Comment by GasimGasimzada** [comment]
#701 Since, this was a small change, I fixed it in this PR.

**Comment by dwelle** [comment]
Removing `shape` decreases the size around 800% in the above scene (~8MB → ~1MB).

**Comment by Fausto95** [comment]
We should migrate it still, if we want to support https://github.com/excalidraw/excalidraw/issues/19

**Comment by dwelle** [comment]
Yea, hence keeping this open. It's not as critical right now, but will be in time (as you note).

**Comment by vjeux** [comment]
We were storing the entire shape in local storage which inflated the scene enormously. Now that we don't anymore, it seems unlikely that people will reach the limit. Let's keep using localStorage for now and if it actually becomes an issue in practice we can reevaluate.

**Comment by dwelle** [comment]
Depending on how we resolve https://github.com/excalidraw/excalidraw/issues/909, this may become relevant. But we can keep it closed for now.
