### ISSUE TITLE
excalidraw canvas group selection reveal bug

### ISSUE THREAD

**Issue by Wlivans** [excalidraw/excalidraw#7116]
When I group selection graphics and delete the grouped graphics, a strange symbol suddenly appears on the excalidraw canvas. When I click excalidraw canvas, it disappears
# Steps To Reproduce
1、Create multiple graph
2、Drag box selection
3、Right click and click group selection
4、delete
<img width="1658" alt="image" src="https://github.com/excalidraw/excalidraw/assets/50228839/059e4864-39ca-4ec9-af43-98954690cc63">

**Comment by SmitDasadia** [comment]
I can confirm that I have encountered the same issue described by @Wlivans. When performing the steps outlined in the initial report, I observed the appearance of a strange symbol on the Excalidraw canvas after deleting grouped graphics. Clicking anywhere on the canvas does indeed make the symbol disappear.
