### ISSUE TITLE
Feature Request: Strikethrough Text (text-decoration: line-through)

### ISSUE THREAD

**Issue by kortina** [excalidraw/excalidraw#7118]
I'm a huge fan of the [Excalidraw VS Code Extension](https://marketplace.visualstudio.com/items?itemName=pomdtr.excalidraw-editor) and have totally switched over from Figma to using this for all sorts of writing tasks.

One feature I miss from Figma is the ability to format text with a strikethrough ( css `text-decoration: line-through;`).

Any chance of getting this added to the Excalidraw extension?

**Comment by ashendge** [comment]
Is there any interest/activity in this issue?

**Comment by Mrazator** [comment]
Closing in favor of #6678

**Comment by Ranjeet-Wadkar** [comment]
is the strike-through feature now added to the browser or vs-code extension?
