### ISSUE TITLE
add props to disable only editor in excalidraw api

### ISSUE THREAD

**Issue by krAbhiDev** [excalidraw/excalidraw#7142]
hey, i am using excalidraw api for making application which simply integrate google drive for auto save files.
so while making this i want to  disable only editor when loading data from server and show loading status instead of editor.

here is is my project 
[repo](https://github.com/krabhi7/excalidraw-drive)

**Comment by dwelle** [comment]
I'd probably just disable `pointer-events` on the editor and display a loading banner (you may set `excalidrawAPI.updateScene({appState: {isLoading: true}})` but there will likely be some race conditions).

**Comment by krAbhiDev** [comment]
> I'd probably just disable `pointer-events` on the editor and display a loading banner (you may set `excalidrawAPI.updateScene({appState: {isLoading: true}})` but there will likely be some race conditions).

i think disabling pointer-events on the editor may be good idea.
thanks for suggestion
