### ISSUE TITLE
Bug: Insert Image Dialog appearing twice.

### ISSUE THREAD

**Issue by David-Carty** [excalidraw/excalidraw#7147]
Tested in Chrome (Version 117.0.5938.152 (Official Build) (64-bit)) and Edge on Windows.

1. Click Insert new image.
2. The file dialog appears.
3. Then a second file dialog appears.

Expected Behaviour

only one file dialog box should appear.

The problem did not occur in Firefox on Windows.

**Comment by ishika2021** [comment]
Hey I would like to work on this bug can you please assign this to me :)

**Comment by dwelle** [comment]
Thanks for the report @David-Carty!

@ishika2021 sorry, but it required some tinkering which I needed to think and test through as I wrote it.

**Comment by dwelle** [comment]
@ishika2021 what needs updating is the docs for `setActiveTool` which now accepts a new prop for `type: "image"` — if you're interested, you can check the PR changes for details (also make sure the PR is opened against `docs-next` branch instead of `master`).
