### ISSUE TITLE
Bug: TypeError: collaborators.forEach is not a function

### ISSUE THREAD

**Issue by pavinduLakshan** [excalidraw/excalidraw#7148]
When trying to load an existing wireframe in excalidraw widget, I'm getting the $subject.

When inspecting, I could find out that the `collaborators` are stored as an object, instead of an empty array in App State. Therefore, the widget throws the $subject.

<img width="359" alt="Screenshot 2023-10-15 at 01 09 26 1" src="https://github.com/excalidraw/excalidraw/assets/41533942/07a6b3b7-2030-44fe-b9b3-71fad03d5a0c">

<img width="1094" alt="Screenshot 2023-10-15 at 01 11 56" src="https://github.com/excalidraw/excalidraw/assets/41533942/d92c0d34-bfb9-408c-923a-961d8a0eac29">

**Comment by Shreya-0999** [comment]
Hey, I would like to work on this bug can you please assign this to me?

**Comment by pavinduLakshan** [comment]
It seems like this issue occurs due to the way I decode the base64 encoded appState to JS object, and not a project bug. Hence closing.

**Comment by 0xsalah** [comment]
Hi @pavinduLakshan, how did you solve this issue?

**Comment by ashishrai8880** [comment]
how did this error you solved ?

**Comment by rmtreks1** [comment]
@ashishrai8880 @salahzsh  - I'm not sure how exactly you're saving the appState, but I found when the collaborators were empty, I was getting an object rather than an empty array. So I changed my saving function to check first then save collaborators as empty array if needed

**Comment by wuguishifu** [comment]
This is definitely still an issue, calling `JSON.stringify(excalidrawApi.getAppState())` creates an object instead of an array for the collaborators entry. This is an Excalidraw issue, as the app state is clearly not being saved as the correct type.

**Comment by Kcin1993** [comment]
I just replace an empty array to fix this issue. 

```
<Excalidraw
  initialData={
    note
      ? {
          elements: note?.excalidraw?.elements,
          appState: {
            ...note.excalidraw?.appState,
            collaborators: [],
          },
          files: note?.excalidraw?.files,
          scrollToContent: true,
        }
      : undefined
  }
/>
```

**Comment by sarthakganguly** [comment]
> I just replace an empty array to fix this issue.
> 
> ```
> <Excalidraw
>   initialData={
>     note
>       ? {
>           elements: note?.excalidraw?.elements,
>           appState: {
>             ...note.excalidraw?.appState,
>             collaborators: [],
>           },
>           files: note?.excalidraw?.files,
>           scrollToContent: true,
>         }
>       : undefined
>   }
> />
> ```

This is the definitive fix actually. At least for the time being.
