### ISSUE TITLE
Error report with latex formular without internet connection.

### ISSUE THREAD

**Issue by zb5700** [excalidraw/excalidraw#7150]
This is a big problem with latex formular! It seems better to be loaded  locally. Or stop reporting that problem below
"LaTeX support did not load. Using fallback solution. Try checking your network connection." 
My excalidraw version is 1.9.2

**Comment by zsviczian** [comment]
This seems Obsidian related. Please note that the Obsidian issue log is here: https://github.com/zsviczian/obsidian-excalidraw-plugin

As for the issue, try selecting a different library host in the plugin settings and restarting obsidian afterward.
![image](https://github.com/excalidraw/excalidraw/assets/14358394/13db46fc-85d5-4fb4-ad29-414298e2c3e9)

**Comment by zsviczian** [comment]
Let's continue the conversation here: https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/1383

**Comment by zb5700** [comment]
Could you give me a choice to use local mathjax? I have already download the mathjax 3.2.1. May be better if you add a configuration for me to choose a local path pointing to mathjax. Because I need to work with excalidraw without internet connection. Thankyou very much.
