### ISSUE TITLE
Persistent Save To Dialog box

### ISSUE THREAD

**Issue by starlove54** [excalidraw/excalidraw#7156]
Issue Description
I have identified an issue, specifically related to the Save To dialog. The problem is that the Save To dialog box does not disappear even after successfully saving the file. This persistence of the dialog creates a user experience issue as it continues to exist even after its intended purpose has been served.

Steps to Reproduce
To replicate this issue, please follow these steps:

1. Click on the hamburger icon located in the top left corner.
2. Choose "Save To" from the menu.
3. A Save To dialog box will appear.
4. Upon clicking "Save to File," another dialog box will open, requesting the path for the file to be saved and the desired file name.
5. After clicking "Save," the Save To dialog box remains visible on the screen, failing to close as expected.

Screenshots: 
1. after performing step 2
<img width="1331" alt="Screenshot 2023-10-16 at 10 42 10 PM" src="https://github.com/excalidraw/excalidraw/assets/24490645/1e062f71-ef59-4e69-b511-2ec8f479e038">

2. after performing step 4
<img width="1331" alt="Screenshot 2023-10-16 at 10 42 00 PM" src="https://github.com/excalidraw/excalidraw/assets/24490645/a53bcbff-2c41-40b1-a764-9fecc7583cb2">

4.after performing step 5
<img width="1331" alt="Screenshot 2023-10-16 at 10 41 37 PM" src="https://github.com/excalidraw/excalidraw/assets/24490645/82ca365e-bf22-4547-95fe-a2f50775ab1a">

This behavior disrupts the user flow and can be confusing to users who expect the Save To dialog to disappear after successfully saving the file.

Thank you for your attention to this matter. I hope this issue can be addressed to enhance the overall user experience of Excalidraw.

**Comment by mvaibhav77** [comment]
Hey @starlove54,
I also think that it disrupts the user flow a little. So I have made a PR request after applying the changes you suggested.

**Comment by starlove54** [comment]
@mvaibhav77 are you sure you are solving the above issue? I checked your changes i could not see it work as intended maybe @dwelle could tell it better

**Comment by mvaibhav77** [comment]
Hello @starlove54, I've made a modification to the application state by setting the openDialog property to null. This change results in the closure of the 'Save to...' dialog box when you click the 'Save to File' button, specifically, not when you select a path and save the file.

**Comment by dwelle** [comment]
fixed in https://github.com/excalidraw/excalidraw/pull/7168
