### ISSUE TITLE
Improve usability using CRDTs

### ISSUE THREAD

**Issue by wsdookadr** [excalidraw/excalidraw#7161]
It would be interesting if #3537 , #1234  were revisited.
There are bugs that surface when two users use the canvas simultaneously.
A good entry point might be checking out [CRDTs](https://crdt.tech/implementations) or this example of a hand-rolled editor [described here](https://jakelazaroff.com/words/building-a-collaborative-pixel-art-editor-with-crdts/).

**Comment by dwelle** [comment]
We're looking into this _right now_ in fact.

Any specific bugs apart from undo/redo not working (on excalidraw.com at all, and in Excalidraw+ working incorrectly)?

**Comment by Mrazator** [comment]
Status update: as part of https://github.com/excalidraw/excalidraw/pull/7348, we've recently shipped improvements for undo/redo on excalidraw.com & will be shipped on plus.excalidraw.com soonish!

Any feedback appreciated, in any case, reach us here or on Discord!

Interestingly, it partly resembles CRDTs (in terms of emitting diffs, applying changes and auto-resolving conflicts), thanks for opening this issue!
