### ISSUE TITLE
Logo for ExcaliDraw

### ISSUE THREAD

**Issue by IfeanyiEkperi** [excalidraw/excalidraw#7175]
Dear Sir,

I am proposing a logo design for ExcaliDraw...

I've looked around, I haven't seen any logo. I can design a logo is less than 48 hours for a versatile logo that resonates with ExcaliDraw audience

**Comment by dwelle** [comment]
🤔

![image](https://github.com/excalidraw/excalidraw/assets/5153846/eb835aa9-3dbb-4aab-9bf5-460ca2c66054)
