### ISSUE TITLE
License of FG_Virgil TTF font

### ISSUE THREAD

**Issue by drupol** [excalidraw/excalidraw#7179]
Hello,

I would like to package this font for the Nix package manager, and I was wondering where to find information about the [`FG_Virgil.ttf`](https://github.com/excalidraw/excalidraw/blob/master/public/FG_Virgil.ttf) font. I guess it's MIT, but I just wanted to have confirmation.

```[tasklist]
### Tasks
```

**Comment by DanielJGeiger** [comment]
Hi @drupol, you can check https://github.com/excalidraw/virgil/blob/main/LICENSE.md: OFL-1.1, rather than MIT.

**Comment by drupol** [comment]
Thanks!
