### ISSUE TITLE
If anyone here can set up the following Jest test, I would really appreciate it

### ISSUE THREAD

**Issue by GasimGasimzada** [excalidraw/excalidraw#718]
```tsx
// someFile.test.tsx
import { App } from './index';

it('works', () => {
  const app = <App />;
}); 
```

I keep getting the following error:

>
> `({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { RoughCanvas } from './canvas';`
>
> SyntaxError: Cannot use import statement outside a module
>
> `import rough from "roughjs/bin/rough";` <- Line where the error occurs

I have tried everything: changing Jest transform, mocking roughjs module. Nothing works. The same issue happens in `browser-nativefs`. I personally think that it is because Jest does not understand ES6; however, setting transform as `babel-jest` or `ts-jest` did not help.

I would appreciate it if someone can help me out with this...

**Comment by Fausto95** [comment]
I will be trying if I get some free time

**Comment by GasimGasimzada** [comment]
Fixed it:) we can close it

**Comment by szamanr** [comment]
@GasimGasimzada please mention how you fixed it, it might help people in the future. e.g. i'm trying to figure out if it's possible to render excalidraw in jest during testing, or if it needs to be fully mocked.
