### ISSUE TITLE
Can't select stroke-fill objects made with the pen tool

### ISSUE THREAD

**Issue by zsviczian** [excalidraw/excalidraw#7191]
https://twitter.com/salastasius/status/1716906523631440181?t=RafRiSNDJL4hOAgn4Bk2Sw&s=19

Create a closed object with the freedraw tool.
Fill it with Hachure (not solid fill)
Try selecting the object by clicking the center.

**Comment by zsviczian** [comment]
regression introduced with #6698

**Comment by dwelle** [comment]
it was introduced in https://github.com/excalidraw/excalidraw/pull/7031
