### ISSUE TITLE
MVP Milestone

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#72]
I created a MVP Milestone where I tagged all the issues that we should implement to have something that would replace my usage of zwibbler. Let's use this issue to discuss priorities and progress :)

https://github.com/excalidraw/excalidraw/milestone/1

**Comment by giovannigiordano** [comment]
We should even add #14, or an alternative solutions to create a bigger canvas.

**Comment by Fausto95** [comment]
I think that it could be nice adding #15 in the MVP

**Comment by vjeux** [comment]
We’re pretty close! Biggest one is the resize handles. Is anyone interested in working on it?

**Comment by giovannigiordano** [comment]
Can we close it? The first milestone has been resolved.

**Comment by vjeux** [comment]
![image](https://user-images.githubusercontent.com/197597/71783490-5115ac80-2f9c-11ea-922d-605ddc774cae.png)

Yayayay.

Time to make a new milestone :)

Great job everyone, I'm super excited about all the progress!
