### ISSUE TITLE
only the arrow is selected, nothing happens when i select square, circle etc

### ISSUE THREAD

**Issue by munish259272** [excalidraw/excalidraw#7203]
![image](https://github.com/excalidraw/excalidraw/assets/834673/2d3638f0-acb2-4915-a27b-4e72e47e1cea)
As you can see above i have made an arrow to the icons that are not getting selected, i have tried single click , double click and just nothing happens

I was able to select the drop down on the last one
![image](https://github.com/excalidraw/excalidraw/assets/834673/3e53481f-e5a9-4827-a629-f9e943f24936)

but after i selected the last one i was unable to select the other icons

I am just starting with excalidraw plugin in obsidian, please help

**Comment by zsviczian** [comment]
Please run "show debug info" from the command palette and share the results with me.
Also, can you explain how you got to this point. What steps did you take?

**Comment by munish259272** [comment]
I just saw the youtube video from `Zsolt's Visual Personal Knowledge Management` and wanted to try this
I am a begginer with all of this, learning obsidian, templater, dataview, so i went ahead with excalidraw when i faced this.

This is the very first time i am using this


`SYSTEM INFO:
	Obsidian version: v1.4.16
	Installer version: v1.4.13
	Operating system: #1 SMP PREEMPT_DYNAMIC Fri Aug 25 09:13:12 EDT 2023 5.14.0-284.30.1.el9_2.x86_64
	Login status: logged in
	Catalyst license: none
	Insider build toggle: off
	Live preview: off
	Legacy editor: off
	Base theme: light
	Community theme: none
	Snippets enabled: 4
	Restricted mode: off
	Plugins installed: 55
	Plugins enabled: 52
		1: Dataview v0.5.61
		2: Advanced Tables v0.19.1
		3: AnkiBridge v0.8.0
		4: Excalidraw v1.9.26
		5: Execute Code v1.8.1
		6: File Color v1.0.3
		7: Highlightr v1.2.2
		8: HTML Tags Autocomplete v0.0.7
		9: Iconize v2.6.1
		10: Image Captions v1.1.0
		11: Jupyter plugin v0.8.5
		12: TikZJax v0.5.1
		13: Text Wrapper v1.0.0
		14: Quick Latex for Obsidian v2.6.3
		15: Simple Note Quiz v1.1.1
		16: Obsidian matrix v1.4.0
		17: Obsidian_to_Anki v3.4.2
		18: MathLinks v0.4.6
		19: Math Booster v1.0.4
		20: Obsidian Charts v3.8.0
		21: Markdown Formatting Assistant v0.4.1
		22: Latex Environments v0.4.2
		23: List Callouts v1.2.0
		24: Desmos v0.6.6
		25: Charts View v1.2.5
		26: Obsidian42 - BRAT v0.7.0
		27: Snippet Downloader v2.0.1
		28: Media Extended v2.11.1
		29: Better Word Count v0.10.0
		30: External Link Opener v1.0.2
		31: Open In New Tab v1.0.9
		32: YTranscript v0.9.1
		33: Shell commands v0.20.0
		34: Juggl v1.4.0
		35: Homepage v3.6.0
		36: Calendar v1.5.10
		37: Periodic Notes v0.0.17
		38: Kindle Highlights v1.9.2
		39: Kanban v1.5.3
		40: Recent Files v1.3.8
		41: Imgur Plugin v2.4.0
		42: Banners v2.0.5-beta
		43: Emoji Toolbar v0.4.1
		44: Style Settings v1.0.7
		45: Templater v1.16.4
		46: Book Search v0.5.11
		47: Paste URL into selection v1.7.0
		48: Natural Language Dates v0.6.1
		49: Hover Editor v0.11.14
		50: Auto Link Title v1.4.1
		51: Workspaces Plus v0.3.3
		52: Text Format v2.2.8

RECOMMENDATIONS:
	Custom theme and snippets: for cosmetic issues, please first try updating your theme and disabling your snippets. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community theme and snippets.
	Community plugins: for bugs, please first try updating all your plugins to latest. If still not fixed, please try to make the issue happen in the Sandbox Vault or disable community plugins.
`

**Comment by zsviczian** [comment]
let's move this discussion over to Obsidian... I've created a new issue where we can continue the conversation [#1402](https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/1402)
