### ISSUE TITLE
Perfectly horizontal cartoonist arrows do not appear with that style

### ISSUE THREAD

**Issue by RiccardoBarbieri** [excalidraw/excalidraw#7231]
I am drawing some sequence diagrams that rely on horizontal arrows and I want to use the cartoonist style, the problem is that when the arrows are horizontal the cartoonist effect does not seem to be applied.
![image](https://github.com/excalidraw/excalidraw/assets/43068188/8b4cc68d-96e5-4fcb-84c6-f32b3559f0cc)
![image](https://github.com/excalidraw/excalidraw/assets/43068188/de31f900-bb22-47d5-b4b0-8966669aa7ed)
The two images show that both the arrows have the exact same configuration.

**Comment by Luke-zhang-04** [comment]
It seems that this is an issue for numerous other shapes. For example, rectangles with sloppiness level 2 look like level 1, and straight lines aren't changed at all. Round shapes like circles don't seem affected.
 
<img width="1281" alt="Screen Shot 2023-11-03 at 16 02 16" src="https://github.com/excalidraw/excalidraw/assets/55749227/0a90cda5-e00b-4e5e-a60b-4a1303446fb2">

**Comment by dwelle** [comment]
It was recently changed so that small shapes have reduced roughness for legibility. The lines are not handled properly though. And perhaps we should tweak the non-line shapes as well.
