### ISSUE TITLE
Adaptive roughness (introduced in #6698) reduces hand-drawn feel

### ISSUE THREAD

**Issue by gendx** [excalidraw/excalidraw#7239]
After trying the latest Excalidraw preview on https://excalidraw.com/, I felt that the hand-drawn feel had disappeared, even with sloppiness enabled. As I understand it, this is due to #6698, which makes the roughness adaptive based on the size of objects.

While I understand the shape legibility concern, I'm missing the "hand-drawn feel" appeal of Excalidraw. Fortunately, it's easy to make a local Docker deployment from a previous release (thank you for that!), but I was wondering if you would consider making the old behavior opt-in for users who prefer the previous design?

**Comment by dwelle** [comment]
We'll be partially addressing that as part of https://github.com/excalidraw/excalidraw/issues/7231
