### ISSUE TITLE
Remove recently loaded scenes

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#724]
The idea of having a history of scenes that were previously worked on is good. This is useful. However, the current design is not. Having a dropdown with a list of random ids is not very intuitive, there's no way to edit it...

We should remove the current implementation and when/if we have a better design, then do it again.

If someone wants to remove some code, this issue is the right one for you :)

**Comment by dwelle** [comment]
In the orig PR I suggested to use scene name (when non-random) + relative date (e.g. `myScene (2 days ago)`). Moving it to the scene menu might also improve the UI issue.

**Comment by GasimGasimzada** [comment]
What about doing something similar to how most design apps create the "Page" system. For example, this is from Figma.

![Screen Shot 2020-02-08 at 12 37 59 AM](https://user-images.githubusercontent.com/807231/74064072-4a4edf00-4a0b-11ea-8b39-a6d485556c09.png)
