### ISSUE TITLE
Can't programatically insert image in Excalidraw's initialData prop

### ISSUE THREAD

**Issue by Miculino** [excalidraw/excalidraw#7240]
Hey there!

I've been trying to integrate Excalidraw into a Next.js project I'm working on.

The goal is to show the user a specific image in Excalidraw. That image is pulled from Sanity and passed down as a prop to a client component.

The following are the code for the React component rendering Excalidraw and also the util function that generates the Excalidraw image element:

```
'use client';

import React, { useEffect, useContext, useRef, useState } from 'react';
import EditorViewContext from '~/lib/contexts/editor-view';
import dynamic from 'next/dynamic';

import { initializePngForExcalidraw } from '~/core/generic/initialize-png-excalidraw';

// Dynamic import for Excalidraw which disables server-side rendering
const Excalidraw = dynamic(
  () => import('@excalidraw/excalidraw').then((mod) => mod.Excalidraw),
  { ssr: false }
);
export default function ChallengePreview({ design } : { design: string }) {
  const { codeFile, preview: { isToggleChecked } } = useContext(EditorViewContext);
  const [srcDoc, setSrcDoc] = useState('');
  const [elements, setElements] = useState([]);

  const codePreviewIframe = useRef(null);

  useEffect(() => {
    if (design) {
      initializePngForExcalidraw(design)
        .then(initializedElements => setElements(initializedElements))
        .catch(error => console.error('Error initializing PNG for Excalidraw:', error));
    }
  }, [design]);

  useEffect(() => {
    const timeout = setTimeout(() => {
      setSrcDoc(`
        <html>
          <head>
            <style>${codeFile.value['css']}</style>
          </head>
          <body>
          ${codeFile.value['html']}
          <script>${codeFile.value['javascript']}</script>
          </body>
        </html>
      `)
    }, 500)

    return () => clearTimeout(timeout);
  
  }, [codeFile.value, codeFile.language, srcDoc])

  return (
    <div className="h-full relative">
      {elements.length > 0 && (
        <Excalidraw onChange={(elements, state) => {
          console.log(elements, state);
        }} initialData={{ elements }} />
      )}
      <iframe 
      id="challenge-preview-iframe"
      style={{ zIndex: `${isToggleChecked ? '-1' : '10'}` }}
      className="bg-white absolute top-0 z-10"
      srcDoc={srcDoc} 
      ref={codePreviewIframe} 
      sandbox='allow-scripts'
      width='100%' 
      height='100%' />
    </div>
  )
}
```

```
export function initializePngForExcalidraw(pngUrl) {
  return new Promise((resolve, reject) => {
    fetch(pngUrl)
      .then(response => {
        if (!response.ok) {
          throw new Error(`Network response was not ok: ${response.statusText}`);
        }
        return response.blob();
      })
      .then(blob => {
        const reader = new FileReader();
        reader.onloadend = () => {
          // Construct an Excalidraw element object with the image data
          const imageElement = {
            type: 'image', // specify the element type as image
            version: 2, // Excalidraw internal versioning, may vary
            versionNonce: Date.now(),
            x: 100, // x-coordinate where the image should be placed
            y: 100, // y-coordinate where the image should be placed
            width: 500, // width of the image (you may want to set this dynamically)
            height: 500, // height of the image (you may want to set this dynamically)
            scale: [1, 1], // scale of the image (1 means no scaling)
            isDeleted: false,
            fillStyle: 'hachure', // the fill style of the image
            strokeWidth: 1, // the width of the stroke
            strokeStyle: 'solid', // the style of the stroke
            roughness: 1, // the roughness of the drawing
            opacity: 100, // the opacity of the image
            groupIds: [], // groups this element belongs to
            strokeColor: '#000000', // stroke color
            backgroundColor: 'transparent', // background color
            strokeSharpness: 'sharp', // the sharpness of the stroke
            seed: Date.now(), // random seed for Excalidraw's internal use
            src: reader.result, // the base64 encoded image source,
          };

          resolve([imageElement]); // Resolve with an array containing our image element
        };

        reader.onerror = () => {
          reject(new Error('Error reading the blob as a data URL'));
        };

        reader.readAsDataURL(blob); // Read the blob as a data URL (base64)
      })
      .catch(error => {
        reject(new Error(`Error fetching the PNG image: ${error.message}`));
      });
  });
}
```

<img width="718" alt="image" src="https://github.com/excalidraw/excalidraw/assets/128690939/7443e30e-9e26-402b-825d-0b95b7b870d7">

This is what I always see - an empty image placeholder. I double and triple checked and if I pass the base URL for the image to an img tag, it renders the image correctly.

Any help is deeply appreciated, thank you! @dwelle

**Comment by Miculino** [comment]
Thanks @ad1992 !

**Comment by Miculino** [comment]
Can someone help me out here for a brief moment? @ad1992  @dwelle ?

**Comment by dwelle** [comment]
Hey, apologies for the delay. Will look into asap!

**Comment by dwelle** [comment]
@Miculino you're setting the image's dataURL as `src` attribute of the element which is not supported. You need to build a `{[imageId]: BinaryFileData}` object and pass it as `files` in the `initialData`:

```tsx
const [initialData, setInitialData] = useState<ExcalidrawInitialDataState>();

useEffect(() => {
  fetch("https://upload.wikimedia.org/wikipedia/en/a/a9/Example.jpg").then(
    (resp) => {
      if (resp.ok) {
        resp.blob().then((blob) => {

          const imageType = blob.type;

          // we support more image types, this is just a quick hack for TS
          if (imageType !== "image/jpeg" && imageType !== "image/png") {
            return;
          }

          getDataURL(blob).then((dataURL) => {
            const fileId = "random-file-id" as FileId;

            const imageElement: ExcalidrawImageElement = {
              // image attributes
              // ------------------
              type: "image",
              id: "random-image-element-id",
              status: "saved",
              fileId,
              // generic attributes
              // ------------------
              version: 2,
              versionNonce: Date.now(),
              x: 200,
              y: 200,
              width: 500,
              height: 500,
              scale: [1, 1],
              isDeleted: false,
              fillStyle: "hachure",
              strokeWidth: 1,
              strokeStyle: "solid",
              roughness: 1,
              opacity: 100,
              groupIds: [],
              strokeColor: "#000000",
              backgroundColor: "transparent",
              seed: Date.now(),
              roundness: null,
              angle: 0,
              frameId: null,
              boundElements: null,
              updated: Date.now(),
              locked: false,
              link: null,
            };

            setInitialData({
              elements: [imageElement],
              files: {
                [fileId]: {
                  mimeType: imageType,
                  id: fileId,
                  dataURL,
                  created: Date.now(),
                },
              },
            });
          });
        });
      }
    },
  );
}, []);

if (!initialData) {
  return null;
}

return <Excalidraw initialData={initialData} />;
```

The way to construct images (or any elements) manually is not good. We _do_ have [convertToExcalidrawElements()](https://docs.excalidraw.com/docs/@excalidraw/excalidraw/api/excalidraw-element-skeleton#converttoexcalidrawelements), but that doesn't cover images at the moment.

**Comment by Miculino** [comment]
Thanks a lot for the explanation and assistance, @dwelle - you're a life saver! (and SaaS saver too)

Everything works perfectly now - can't wait to roll out this feature to the coming users. Keep up the awesome work at Excalidraw!

**Comment by moriccelli** [comment]
Hi! I am doing the same, but do not get the expected result.

```
const INIT_ELEMENT_IMAGE_ID = 'initial-element-image';

const loadInitElement = async (initialElement, isDarkMode, excalidrawAPI) => {
  const imageFile = await renderMarkdownToImageFile(initialElement, isDarkMode);
  
  const dataUrl = await new Promise<string>((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => resolve(reader.result as string);
    reader.onerror = reject;
    reader.readAsDataURL(imageFile);
  });
  
  const element: ExcalidrawImageElement = {
    id: INIT_ELEMENT_IMAGE_ID,
    type: 'image',
    x: 50,
    y: 50,
    width: 500,
    height: 500,
    angle: 0,
    fillStyle: 'solid',
    strokeWidth: 1,
    strokeStyle: 'solid',
    strokeColor: '#000000',
    backgroundColor: 'transparent',
    roughness: 1,
    opacity: 100,
    groupIds: [],
    frameId: null,
    roundness: null,
    seed: Date.now(),
    version: 4,
    versionNonce: Date.now(),
    isDeleted: false,
    boundElements: null,
    updated: Date.now(),
    link: null,
    locked: false,
    status: 'saved',
    fileId: INIT_ELEMENT_IMAGE_ID as FileId,
    scale: [1, 1],
  };
  
  const files = {
    [INIT_ELEMENT_IMAGE_ID]: {
      mimeType: imageFile.type,
      id: INIT_ELEMENT_IMAGE_ID as FileId,
      dataUrl,
      created: Date.now(),
      lastRetrieved: Date.now(),
    },
  };
  
  excalidrawAPI.updateScene({
    elements: [element],
    files,
  });
  
  const updatedFiles = excalidrawAPI.getFiles();
  console.log('Files:', updatedFiles, files);  
  console.log('Updated Files:', updatedFiles);
};

const renderMarkdownToImageFile = async (markdownContent, isDarkMode) => {
  const response = await fetch("https://upload.wikimedia.org/wikipedia/en/a/a9/Example.jpg");
  const blob = await response.blob();

  return new File([blob], 'Example.jpg', { type: 'image/jpg' });
};
```

I didn't use the getDataURL as the function is not available in Vite environment, it is internal. 
The renderMarkdownToImageFile is simplified for testing.
The log returns files as normally structured element, which comply to what I see, when add file from UI. 
But the Updated Files is the empty object. So the file is not accepted for some reason by API. 
Can you please take a look, what might be the problem?

**Comment by rohit-saluja** [comment]
```typescript
const getDataURL = (blob: Blob): Promise<string> => {
  return new Promise((resolve, reject) => {
    const reader = new FileReader();
    reader.onloadend = () => {
      const result = reader.result;
      if (typeof result === 'string') {
        resolve(result);
      } else {
        reject(new Error('Could not convert blob to data URL.'));
      }
    };
    reader.onerror = () => reject(new Error('FileReader error.'));
    reader.readAsDataURL(blob);
  });
};

``` 


This one will work for the above solution

**Comment by v-agrawal-micoworks** [comment]
Hi @dwelle,

I am also trying to do something similar but I think so I am messing up somewhere if possible could you let me know what I am doing wrong

`
          if (dragData.type === 'excalidraw-image') {
                let base64Image;
                let imageType = "image/jpeg"; // Default MIME type
    
                // Fetch the image via backend to avoid CORS issues
                if (!dragData.src.startsWith('data:')) {
                    try {
                        const blob = await imageGet("download_image", { image_url: dragData.src });
    
                        imageType = blob.type;
    
                        // Validate supported image types
                        if (imageType !== "image/jpeg" && imageType !== "image/png") {
                            console.error("Unsupported image type:", imageType);
                            return;
                        }
    
                        base64Image = await onlyBlobToBase64(blob);
                    } catch (error) {
                        console.error("Error converting image:", error);
                        return;
                    }
                } else {
                    base64Image = dragData.src;
                }
    
                // Add the image to Excalidraw
                if (excalidrawAPI) {
                    const currentElements = excalidrawAPI.getSceneElements();
                    const images = currentElements.filter(el => el.type === 'image');
                    const lastImage = images[images.length - 1];
                    const newX = lastImage ? lastImage.x + lastImage.width + 10 : 200;
                    const newY = lastImage ? lastImage.y : 100;
    
                    const img = new Image();
                    img.src = base64Image;
                    img.onload = async () => {
                        const id = `img-${Date.now()}`;
                        const { width, height } = aspectRatio(img.width, img.height);
                        const fileId = dragData.id || `file-${Date.now()}`;
    
                        const imageElement = {
                            id,
                            fileId,
                            type: "image",
                            x: newX,
                            y: newY,
                            width,
                            height,
                            scale: [1, 1],
                            angle: 0,
                            strokeColor: "transparent",
                            backgroundColor: "transparent",
                            fillStyle: "hachure",
                            strokeWidth: 1,
                            strokeStyle: "solid",
                            roughness: 1,
                            opacity: 100,
                            groupIds: [],
                            status: "saved",
                            version: 1,
                            versionNonce: Date.now(),
                            isDeleted: false,
                            boundElements: null,
                            link: null,
                            updated: Date.now(),
                        };
    
                        await excalidrawAPI.addFiles([{
                            id,
                            fileId,
                            dataURL: base64Image,
                            mimeType: imageType,
                            created: Date.now(),
                            lastRetrieved: Date.now()
                        }]);
    
                        const updatedElements = [...currentElements, imageElement];
                        await excalidrawAPI.updateScene({ elements: updatedElements });
    
                        excalidrawAPI.scrollToContent();
                    };
                }
            }
`
