### ISSUE TITLE
画布背景可以支持表格吗

### ISSUE THREAD

**Issue by sxin0** [excalidraw/excalidraw#7254]
如图，画布做成表格的话 内容作方便对齐啥的
![image](https://github.com/excalidraw/excalidraw/assets/29392026/e31818c8-0ea7-4126-955f-fc753d78e9e2)

**Comment by sxin0** [comment]
Ctrl + " 本来就支持网格画布，不好意思 这个提议可以忽略

**Comment by dwelle** [comment]
You can also use snapping (Alt/Opt-S or context menu).
