### ISSUE TITLE
Got super tiny menus

### ISSUE THREAD

**Issue by h-magno** [excalidraw/excalidraw#7275]
Hey there, i was using excalidraw to create a mind map and then i got super zoomed out from the menus and none of my attemps ware able to bring it to normal size. I was using google chrome but then i decided to switch to another one (edge) and it was working fine, but besides beeing annoyng to use 2 navigators, i'm starting to get the same problem with edge, except that it is a little more legible than chrome and still working. Hope someone help me bc it seems to be a simple problem to solve and i love to use excalidraw

![excalidraw-issue](https://github.com/excalidraw/excalidraw/assets/111817322/78266cdf-f772-44c4-9bea-3b55ffd745bf)

**Comment by dwelle** [comment]
Hi. You have most likely zoomed the browser itself. Look for a magnifying glass icon in your address bar:

![image](https://github.com/excalidraw/excalidraw/assets/5153846/a040da23-f16f-4177-8fba-1f7c687d5827)

**Comment by h-magno** [comment]
> Hi. You have most likely zoomed the browser itself. Look for a magnifying glass icon in your address bar:
> 
> ![image](https://user-images.githubusercontent.com/5153846/282330839-a040da23-f16f-4177-8fba-1f7c687d5827.png)

bro thanks a lot, i've spent a couple of hours trying to figure out this
