### ISSUE TITLE
Issue with showSaveFilePicker when downloading PNG

### ISSUE THREAD

**Issue by jozzbruer** [excalidraw/excalidraw#7277]
Steps to reproduce:

1 - Open the application.
2 - Draw your design.
3 - Press CTRL+SHIFT+E to export the image.
4 - Click on "Export PNG."
5 - Observe the error modal

Screenshot:

![Screenshot 2023-11-12 at 11 30 00 PM](https://github.com/excalidraw/excalidraw/assets/21253158/9144bf2a-a73d-44af-af85-a611cc1ffa0c)

**Comment by dwelle** [comment]
Hi, what's your browser and OS?

**Comment by jozzbruer** [comment]
Chrome: Version 118.0.5993.117
MacOS: Sonoma V 14.1.1

Le lun. 13 nov. 2023 à 01:05, David Luzar ***@***.***> a
écrit :

**Comment by dwelle** [comment]
It's possible the exported PNG is too big and thus taking too long to export, which Safari detects as no longer coming from a user intent. Can you check the canvas size so I can try to reproduce (you can right-click on canvas -> stats for nerds -> Scene width & height)?

**Comment by jozzbruer** [comment]
Here we go

Le lun. 13 nov. 2023 à 01:39, David Luzar ***@***.***> a
écrit :

**Comment by dwelle** [comment]
Correction, I mentioned Safari, but what I said would apply to Chrome as well.

> Here we go

Not seeing anything, it probably didn't paste.

**Comment by jozzbruer** [comment]
![Screenshot 2023-11-13 at 1 47 39 AM](https://github.com/excalidraw/excalidraw/assets/21253158/62a59b78-4278-43fa-8a70-97a5493d27c4)
