### ISSUE TITLE
The fall back font for the hand-drawn font, should be the same as normal font

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw#728]
<img width="575" alt="Screenshot 2020-02-07 at 6 09 48 PM" src="https://user-images.githubusercontent.com/125676/74049731-0c36c880-49d5-11ea-9101-4b94a0645142.png">

https://excalidraw.com/#json=5115274223157248,IS0Bi9cNajPwX7WI5QD6pA

**Comment by vjeux** [comment]
We now have most characters that people use. Closing this.
