### ISSUE TITLE
Web page is not loading on Chrome/Edge

### ISSUE THREAD

**Issue by devon-at-memfault** [excalidraw/excalidraw#7292]
I receive a blank screen at app.excalidraw.com. I can only load the base excalidraw.com.
There appears to be a console error (from  a colleague with the same issue)
![image](https://github.com/excalidraw/excalidraw/assets/107696939/b9d025f7-5623-42f9-a35a-8d7e5b5cd19a)

**Comment by simonski** [comment]
+1 👎

**Comment by maielo** [comment]
The issue is with firebase Auth outage - https://status.firebase.google.com/incidents/JH8hiSsfnSZHMdZqFTaC google is working on it

**Comment by dwelle** [comment]
Issue is now resolved. We'll follow up with more details over newsletter tomorrow. 🙏
