### ISSUE TITLE
Paste SVG

### ISSUE THREAD

**Issue by inwardmovement** [excalidraw/excalidraw#7315]
We can import SVGs, but it would be more practical if we could directly paste the SVG code (copied as text) to import, instead of using "insert image".

**Comment by two-plus-two-equals-five** [comment]
Hey @inwardmovement I'm not able to reproduce this issue on my mac (see screen recording): 


https://github.com/excalidraw/excalidraw/assets/84499878/21c2152b-7d65-47c9-8c54-227dc215eb60


What device are you using and am I following the same reproduction steps as you?

**Comment by dwelle** [comment]
that works?

```
<svg xmlns="http://www.w3.org/2000/svg" class="icon icon-tabler icon-tabler-file-type-svg" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M14 3v4a1 1 0 0 0 1 1h4" /><path d="M5 12v-7a2 2 0 0 1 2 -2h7l5 5v4" /><path d="M4 20.25c0 .414 .336 .75 .75 .75h1.25a1 1 0 0 0 1 -1v-1a1 1 0 0 0 -1 -1h-1a1 1 0 0 1 -1 -1v-1a1 1 0 0 1 1 -1h1.25a.75 .75 0 0 1 .75 .75" /><path d="M10 15l2 6l2 -6" /><path d="M20 15h-1a2 2 0 0 0 -2 2v2a2 2 0 0 0 2 2h1v-3" /></svg>
```

**Comment by inwardmovement** [comment]
Yes it works... I don't know why it didn't before. Thanks!
