### ISSUE TITLE
Non-hand-drawn style for rectangles/diamonds/circles?

### ISSUE THREAD

**Issue by tsbertalan** [excalidraw/excalidraw#7317]
I know that the hand-drawn style is a major differentiator for Excalidraw for web usage, but I'm using it via the Obsidian mobile plugin, and I want to be able to draw some rectangles with sharp edges for purposes like floor plans or other geometric drawings. Is there a way to toggle the display style, either per-drawing or as a global setting for the app?

**Comment by kjameer0** [comment]
<img width="739" alt="Screenshot 2023-11-20 at 3 04 22 PM" src="https://github.com/excalidraw/excalidraw/assets/41968688/60b4494b-7f7c-40a6-bafd-f4a6725a06ce">
Select the elements you want to change in Obsidian-Excalidraw and click the palette icon on the bottom left. There you'll see a Sloppiness setting and an Edges setting; you can sharpen your corners and clean up the lines by clicking your preference. Whatever you change those to will be saved and applied to future elements you create so you don't have to reselect your preferences. Let me know if this was confusing at all!
