### ISSUE TITLE
[Question][Table] Unable to auto-align tables

### ISSUE THREAD

**Issue by QuakeWang** [excalidraw/excalidraw#7319]
This is a very bad user experience. When changing content, there is no way to auto-align the borders of the elements, resulting in too much wasted time and no output.

![bug](https://github.com/excalidraw/excalidraw/assets/45645138/592dceca-c693-4027-84e0-d7457c2a42af)

```[tasklist]
### Tasks
```

**Comment by editfund-founder** [comment]
### I love these features when I create tables.
---
### ¹ 😍
![E1](https://github.com/excalidraw/excalidraw/assets/61936162/30a95ff0-97b0-481e-907c-ab10f27d310a)
---
### ² 😍
![E2](https://github.com/excalidraw/excalidraw/assets/61936162/82e6163c-13f8-43d5-9687-50950d63f288)
---

**Comment by QuakeWang** [comment]
> ### I love these features when I create tables.
> ### ¹ 😍
> ## ![E1](https://user-images.githubusercontent.com/61936162/284405564-30a95ff0-97b0-481e-907c-ab10f27d310a.jpg)
> ### ² 😍
> ## ![E2](https://user-images.githubusercontent.com/61936162/284405622-82e6163c-13f8-43d5-9687-50950d63f288.jpg)

I have tried this, but it seems doesn't work in this situation.

**Comment by ryan-di** [comment]
Hey @QuakeWang when you're in the grid mode, snapping to objects is disabled. This is by design, because we want grid mode to take a higher priority. 

You could use the align functions as suggested by @editfund-founder or you could turn grid mode first and then turn on "snap to objects" to align the objects together.

**Comment by QuakeWang** [comment]
> Hey @QuakeWang when you're in the grid mode, snapping to objects is disabled. This is by design, because we want grid mode to take a higher priority.
> 
> You could use the align functions as suggested by @editfund-founder or you could turn grid mode off first and then turn on "snap to objects" to align the objects together.
> 
> Tip: when you select "snap to objects" from the context menu, "grid mode" is turned off automatically.

Thanks a lot, I have found how to use it. It is so powerful tool~~
