### ISSUE TITLE
Aiming to automate the room creation or joining process without relying on the manual popup provided in the UI.

### ISSUE THREAD

**Issue by DineshCodeFlow** [excalidraw/excalidraw#7326]
To seamlessly create or join a room without user intervention through the UI, seeking advice, insights, or any available methods within the Excalidraw ecosystem to achieve this automation.

I've explored the available documentation and functionalities within Excalidraw, but haven't identified a direct solution to automate this process.

I'm reaching out to the Excalidraw community for guidance or any pointers that could assist in automating room creation or joining through GitHub integrations, hidden functionalities, or any workarounds that might not be explicitly documented.

Your contributions, suggestions, or experiences in implementing similar automation within Excalidraw would be immensely valuable to our project's workflow optimization.

**Additional Details:**

If this feature is not currently supported or documented, I'm open to suggestions, tips, or potential directions to explore, such as custom development or upcoming updates that might include this functionality.

Thank you in advance for any assistance or insights you can offer. Your expertise and support are greatly appreciated.

<img width="1436" alt="Screenshot 2023-11-22 at 8 04 38 AM" src="https://github.com/excalidraw/excalidraw/assets/69179167/f7e52466-b693-4c64-ba06-ebdd050fde76">

**Comment by ryan-di** [comment]
Hey @DineshCodeFlow thanks for opening up the issue.

Is your intention to automate the collab process for "excalidraw.com"? If so, we're happy to hear what you have to suggest. 

But please do keep in mind that opening up a live collaboration session is a deliberate action and we would like to keep users informed one way or another.

**Comment by DineshCodeFlow** [comment]
For now it my project specific. The thing is we have product specific platforms whoever opens whiteboard inside the product, become the a collaborator by default in the product. So for this specific requirement popup is not making a sense.

**Comment by DineshCodeFlow** [comment]
I wanted to share an update regarding the automation of room access in Excalidraw. I've managed to solve the challenge by passing the room ID directly within the URL.

To facilitate this process in an Angular environment, here's a snippet of the Angular service I've used:

```
import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class IVGenerationService {

  constructor() { }

  // Generate a 22-character length IV based on a provided string
  generateIVFromSeed(seed: string): Promise<string> {
    // Hash the seed value using SHA-256
    async function sha256(message: string): Promise<string> {
      const msgBuffer = new TextEncoder().encode(message);
      const hashBuffer = await crypto.subtle.digest('SHA-256', msgBuffer);
      const hashArray = Array.from(new Uint8Array(hashBuffer));
      return hashArray.map(b => b.toString(16).padStart(2, '0')).join('');
    }

    // Get a 32-character hexadecimal hash
    async function getHashedValue(): Promise<string> {
      const hashedSeed = await sha256(seed);
      return hashedSeed.substring(0, 32); // Use the first 32 characters of the hash
    }

    // Convert the hexadecimal hash to a 22-character Base64 string
    async function convertToBase64(hash: string): Promise<string> {
      const binaryHash = hash.match(/.{1,2}/g).map(byte => parseInt(byte, 16));
      const iv = btoa(String.fromCharCode.apply(null, new Uint8Array(binaryHash)))
        .replace(/\+/g, '-').replace(/\//g, '_').replace(/=/g, ''); // Ensure URL safety
      return iv.substring(0, 22); // Use the first 22 characters of the encoded hash
    }

    // Generate and return the IV
    return getHashedValue().then(convertToBase64);
  }
}
```

This is how to use this-
```
    this.ivService.generateIVFromSeed(initiativeId)
      .then(iv => {
        const iframeSrc = `http://localhost:3030/#room=${iv},${iv}`;

        const iframe = document.createElement('iframe');
        iframe.setAttribute('src', iframeSrc);
        iframe.setAttribute('frameborder', '0');
        iframe.setAttribute('id', 'dynamicIframe');
```
