### ISSUE TITLE
[BUG]: Unable to integrate excalidraw

### ISSUE THREAD

**Issue by Vishal21121** [excalidraw/excalidraw#7331]
## Description
Getting `process is not defined` error in `main.js` file while integrating excalidraw v0.17.0

**Comment by ad1992** [comment]
Hi @Vishal21121, since v0.17.0, `node` variable is expected, you can read about it [here](https://docs.excalidraw.com/docs/@excalidraw/excalidraw/faq#referenceerror-process-is-not-defined) so please make sure that `process.env.VITE` is accessible and it should work fine

**Comment by Vishal21121** [comment]
Thanks @ad1992 for you help

**Comment by ad1992** [comment]
@Vishal21121 I hope its resolved now. So can I closed this issue ?

**Comment by Vishal21121** [comment]
@ad1992 yeah sure.

**Comment by microdou** [comment]
@ad1992 Thanks, solved my issue!
