### ISSUE TITLE
Shared undo regularly deletes our work

### ISSUE THREAD

**Issue by bobbydigitales** [excalidraw/excalidraw#7353]
When we're in a multi-user document, we regularly delete each other's work. This is very frustrating and makes what is an amazing tool very frustrating to use.

User A: make a new text area and type a load of stuff
User B: at the same time, be sketching
User B: Hit undo a lot to remove their sketches, also unintentionally deletes the large amount of text that User A made.

We're paying for ExcaliDraw+ as a team and this basically makes Excalidraw unusable and very dangerous for us to use as a group, especially in complex documents.

I think a much better approach would be to do what Google Docs does where each user has a server-side undo buffer. Maybe this requires Operational Transforms or CRDT's, but overall it would be better to just be dumb and have each client try and undo only their own things. Having someone else undo your work is incredibly frustrating and will likely lead us to just not use the collaboration features, or potentially just not use Excalidraw at all :(

Another option might be for use to be able to opt out of this behavior? It wouldn't be great, but being able to opt a drawing out of the shared undo buffer would be enough for us.

**Comment by dwelle** [comment]
Apologies for this, we're actively working on it! https://github.com/excalidraw/excalidraw/pull/7348

If you end up losing anything, please let us know on support@excalidraw.com and we'll restore from a revision.

**Comment by Mrazator** [comment]
Status update: as part of https://github.com/excalidraw/excalidraw/pull/7348, we've recently shipped improvements for shared undo/redo on excalidraw.com & will be shipped on plus.excalidraw.com soonish!

Any feedback appreciated, in any case, reach us here or on Discord!
