### ISSUE TITLE
Scenes failing to save excalidraw+

### ISSUE THREAD

**Issue by durtal** [excalidraw/excalidraw#7356]
I'm a plus subscriber but experiencing significant frustration when working on scenes and finding that they're not saving, which means I'm losing work.

Just this evening I've lost an hours work, I'm getting into the habit of taking pngs and svgs of the work, which sort of negates using excalidraw+.

When I inspect the console i do see a lot of failed POST requests, which I assume might be failing to save changes? (Chrome browser on more than one laptop)

Apologies if this isn't the appropriate place to log issues, I couldn't find an email address. Any support would be appreciated.

**Comment by dwelle** [comment]
Hi, can you send us an email to `support@excalidraw.com` so we can look into your specific workspace? — and if you can, please include screenshots of the failing requests 🙏

That said, you may try enabling long-polling from https://app.excalidraw.com/account/preferences as it may be related to VPN/firewall and Firebase :(.

**Comment by durtal** [comment]
Hi @dwelle, thanks for the reply. I'll email the team, love the tool, just frustrating at the moment.

Tom
