### ISSUE TITLE
Hovering Over Buttons Issue

### ISSUE THREAD

**Issue by Sattu2806** [excalidraw/excalidraw#7364]
When hovering over buttons, the descriptions are not instantly displayed. I believe there is an opportunity to enhance this interaction for a smoother and more immediate experience.

https://github.com/excalidraw/excalidraw/assets/127772255/ee944931-fc35-41a8-ab6b-fffc58e4fde6

**Comment by mvaibhav77** [comment]
I think this was intentionally made that way. If a user wants to know details they hover a little longer or else it is not required to show them details every time. This seems like a decent feature to me.
