### ISSUE TITLE
2.0.5 update killed app

### ISSUE THREAD

**Issue by Scouser0001** [excalidraw/excalidraw#7372]
After an update on my iPad excalidraw fails to load. Is there a way to roll back to the previous version

**Comment by Scouser0001** [comment]
That is the obsidian version

**Comment by ShonenAsh** [comment]
You may want to report this issue here:

https://github.com/zsviczian/obsidian-excalidraw-plugin

Sidenote, current obsidian version runs fine for me on the iPad Air 5

**Comment by ad1992** [comment]
As mentioned above @ShonenAsh , please open this issue in https://github.com/zsviczian/obsidian-excalidraw-plugin
