### ISSUE TITLE
[ Bug ] Docker image on Dockerhub not updated for 4 months

### ISSUE THREAD

**Issue by modem7** [excalidraw/excalidraw#7403]
The docker image on Dockerhub hasn't been updated for 4 months.

Given that the latest release is ~3 weeks old, there may be an issue with the github action.

**Comment by agebhar1** [comment]
Indeed https://github.com/excalidraw/excalidraw/actions/runs/7117050046/job/19376898412#step:4:251

**Comment by netFLOw95** [comment]
Does anyone know whether the docker image can now be used with several participants at the same time? The official site still says "At the moment, self-hosting your own instance doesn't support sharing or collaboration features".

**Comment by Montg0mery** [comment]
Any update on this since? It's now almost 7 months since the image was updated: https://hub.docker.com/r/excalidraw/excalidraw/tags

Even though the last release was 3 days ago: https://github.com/excalidraw/excalidraw/releases

**Comment by ad1992** [comment]
> Any update on this? It's now almost 7 months since the image was updated: https://hub.docker.com/r/excalidraw/excalidraw/tags
> 
> Even though the last release was 3 days ago: https://github.com/excalidraw/excalidraw/releases

Waiting for someone to test out the docker build in https://github.com/excalidraw/excalidraw/pull/7430 and then we should be good to merge

**Comment by agebhar1** [comment]
Can confirm the build https://excalidraw-git-fork-agebhar1-feature-gh7403-f-1f6410-excalidraw.vercel.app/

**Comment by FabulousSoldier** [comment]
Any update on this? The image on Docker Hub is now 8 months behind since last update.
