### ISSUE TITLE
remove invisible elements on load

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#741]
Dunno how, but I managed to create an invisible element (rectangle). For good measure, we should remove invisible elements on scene load.

Nevertheless, we should review the logic to find out what case allows for still creating invisible elements.

**Comment by GasimGasimzada** [comment]
Do you have the scene file? Does it actually show that width and height are (0,0) or is it so slow that we just can't see it?

**Comment by dwelle** [comment]
Yep, it's 0/0.

**Comment by GasimGasimzada** [comment]
I just created a PR for it: #754 :) You can merge it if you like. I just added a filter to remove all the invisibly small elements on during `restore`
