### ISSUE TITLE
[Feature request] "command" as alternative for touchpad half click

### ISSUE THREAD

**Issue by petrasl1976** [excalidraw/excalidraw#7427]
Hi,

Would it be possible to add alternative button for touch pad "half click" so it will allow to draw while "command" (Mac OS) buttons is pressed instead of press on touch pad. I think, it would allow draw things more precise as even it is "half press" on touch pad, it still requires some force, which sometimes makes finger to shake and drag wrong direction.

Thanks
PetrasL

**Comment by ryan-di** [comment]
Hey @petrasl1976 thanks for your request. We'll review it later. 

In the mean time, with Mac OS, you could turn on "three finger drag" from "settings > accessibility > pointer control > trackpad options".

With this, you could start drawing with three fingers moving on the trackpad without needing to press the trackpad. This has offered me quite a bit of control and convenience. Hope this helps :)

**Comment by dwelle** [comment]
@petrasl1976 this would require a larger rewrite of our event handling, but more importantly, it'd prevent common operations with those modifiers. E.g. `cmd-drag` would start drawing (or whatever the currently selected tool does) or prevent whatever action the modifiers does by default (e.g. enables snapping) — similar for other modifiers.

As such we're not going to introduce this at the moment.

I'd investigate alternative methods such as the one @ryan-di suggested!

**Comment by petrasl1976** [comment]
Totally makes sense! Thank you for a great tool and replay.

**Comment by petrasl1976** [comment]
Oh, actually I didn't know about the `command` + `click and drag` option in
`excalidraw` and its really cool feature! Thanks for pointing it out to me
:)
But I meant `command` + `mouse cursor movement` (without `click`). Just
`command` button instead of "left mouse click" would be on mouse with
buttons :)

Regards
