### ISSUE TITLE
clarify Readme install steps

### ISSUE THREAD

**Issue by OleksiiPasichnyk** [excalidraw/excalidraw#7434]
README is not completed to provide easy, self guided start up pattern on the local machine.
The app is missing packages when I'm trying to run 
`npm install react react-dom @excalidraw/excalidraw`

please do not pay attention that logs are from Node 20, 18 does the same.

```verbose stack Error: Invalid package name "packages/excalidraw" of package "packages/excalidraw@*": name can only contain URL-friendly characters.
6012 verbose stack     at invalidPackageName (/home/axelp/.nvm/versions/node/v20.10.0/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:111:15)
6012 verbose stack     at Result.setName (/home/axelp/.nvm/versions/node/v20.10.0/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:158:11)
6012 verbose stack     at new Result (/home/axelp/.nvm/versions/node/v20.10.0/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:147:10)
6012 verbose stack     at Function.resolve (/home/axelp/.nvm/versions/node/v20.10.0/lib/node_modules/npm/node_modules/npm-package-arg/lib/npa.js:59:15)
6012 verbose stack     at #nodeFromEdge (/home/axelp/.nvm/versions/node/v20.10.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1048:22)
6012 verbose stack     at #buildDepStep (/home/axelp/.nvm/versions/node/v20.10.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:917:35)
6012 verbose stack     at #resolveLinks (/home/axelp/.nvm/versions/node/v20.10.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1436:32)
6012 verbose stack     at #buildDepStep (/home/axelp/.nvm/versions/node/v20.10.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:783:32)
6012 verbose stack     at #buildDepStep (/home/axelp/.nvm/versions/node/v20.10.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1035:30)
6013 verbose cwd /home/axelp/personal/homelab-kubernetes/projects/excalidraw
6014 verbose Linux 6.6.6-1-liquorix-amd64
6015 verbose node v20.10.0
6016 verbose npm  v10.2.3
6017 error code EINVALIDPACKAGENAME
6018 error Invalid package name "packages/excalidraw" of package "packages/excalidraw@*": name can only contain URL-friendly characters.
```

**Comment by dwelle** [comment]
Hi. I can't reproduce this. Can you share your project or a minimal example, such as on CodeSandbox or StackBlitz?

**Comment by OleksiiPasichnyk** [comment]
It seems that README needs to include additional steps/ or boilerplate setup.

something like
1. switch to the excalidraw proj folder and run 
2. yarn build 
3. yarn run start
The README itself is a bit misleading,

as I was forced to install cross-env as an additional step as a result of failing to start
and running npm/yarn from the root at all does not start the local project 
 
I'm trying to build a docker image based on the Dockerfile in the root and it is failing too =)

Sorry, I'm not FrontEnd, so some questions are expected. 
Actual DevOps here with some knowledge of the FE dev. 

My end goal is to have a localcopy of the project that runs on docker automagically from the scripts without chasing failing module dependencies.
currently it is not a case, unless I'm doing something wrong

**Comment by OleksiiPasichnyk** [comment]
> Hi. I can't reproduce this. Can you share your project or a minimal example, such as on CodeSandbox or StackBlitz?

simple steps I followed
1. clean Ubuntu 22.04
2. copy repository from master
3. run the command above in the root directory of the project

**Comment by OleksiiPasichnyk** [comment]
I will tinked with it and provide my feedback by EOD here

**Comment by dwelle** [comment]
Wait, by your initial post I thought we were talking about the npm package. What you're doing is cloning the repo and trying to run?

**Comment by OleksiiPasichnyk** [comment]
> Wait, by your initial post I thought we were talking about the npm package. What you're doing is cloning the repo and trying to run?

I believe that you are right - it is Readme for the integration, not for the actual application run.

**Comment by dwelle** [comment]
still good point, we should make it clear the readme install steps are about the package, and link to set up steps for the repo itself!
