### ISSUE TITLE
Export as image doesnt work if its a big image

### ISSUE THREAD

**Issue by AdnanCukur** [excalidraw/excalidraw#7456]
I'm getting this error

`Failed to execute 'showSaveFilePicker' on 'Window': Must be handling a user gesture to show a file picker.
`

Scale 1x works, Scale 3x it seems to be "processing" for a couple seconds and then the error window pops up, my guess is that it takes too long to process because of big drawing so chrome doesnt associate the click with the download file event.

Dark mode with scale 1x doesnt work either, with similar behavior as when i try to export it as 3x.

A solution might be to basically just show a "Processing bar" or spinning wheel while its processing and when its done display a download button, similar to how other sites that process images do it.

Windows 11, Chrome Version 120.0.6099.72, tried in incognito, guest mode, company profile, private profile, same issue.

**Comment by tomayac** [comment]
I just commented on a [Chromium bug](https://bugs.chromium.org/p/chromium/issues/detail?id=1516572#c1) where someone was running into a seemingly similar problem.

**Comment by exoriente** [comment]
I have the same issue. A large drawing won't export to PNG, instead showing a pop-up:

> Error
> Failed to execute 'showSaveFilePicker' on 'Window': Must be handling a user gesture to show a file picker.

When I select a part of the drawing and try to export again with `Only selected` enabled it works fine. So it seems to be related to the size of the drawing.

I'm running Excalidraw as a PWA locally.

MacOS Sonoma 14.2 (23C64) | Google Chrome 120.0.6099.234
