### ISSUE TITLE
the pen tool is too thick!

### ISSUE THREAD

**Issue by 9EED** [excalidraw/excalidraw#7467]
i may sound like im being too picky here but it always bugs me how much thicker drawings made using the pen tool look next to the other tools, this makes it almost impossible to use both

to explain what i mean here's a side by side comparison between two lines of the same "stroke width" setting. one is made using the line tool (left) and one made with the pen tool (right)
![image](https://github.com/excalidraw/excalidraw/assets/88392191/4a44371c-9bae-4cb7-8e3d-a86e487d5871)

you actually need to use the thickest line next to the thinnest free drawing pen to get a somewhat close result and thats very impractical to me and leaves no freedom
![image](https://github.com/excalidraw/excalidraw/assets/88392191/fb9478d7-8a35-405b-b61f-79ecf3612d45)

the fix for this should be very simple. as simple as adjusting a few variables but i will leave that to someone more involved. i don't know how such an error could fly for so long

**Comment by hunklin** [comment]
Agree!

**Comment by christopherball** [comment]
This single issue is stopping me using this tool.  It's nearly impossible to cleanly write math because the thinnest available lines are too thick...Here's a related issue from multiple years ago and several code change proposals: https://github.com/excalidraw/excalidraw/issues/3693

**Comment by iamsashika** [comment]
Agree!

**Comment by rapus95** [comment]
Also chiming in since I'm considering Jitsi for private lessons in math. And since Jitsi uses Excalidraw in the backend, I would really love if proper line adjustments were made. Since more line width options were denied in the past because it would go against the rule of simplicity, I want to refer to the proposal of the other issue (#3693) to replace the 3 buttons with a single drawer. Which, at least to me, is even simpler than 3 buttons without being unnecessarily restricting.

**Comment by 5ohue** [comment]
Agreed!

**Comment by CobriMediaJulien** [comment]
I do agree with you. A slider is a lot better. The freedraw lines are too thick and therefore i can´t use it properly. I have to open every drawing and change the strokewidth. There is acutally a obisidian plug in of excalidraw with a smaller pen size and it´s so usefull. They just put 0.75 as strokewidth value which is all i would need or even better, a Slider that maybe just locks in some values.

**Comment by Mrazator** [comment]
Thanks for the feedback! This feature is on our radar, as it was discussed several times, for now closing in favor of #3693.

**Comment by AhmedLilah** [comment]
I'm still suffering from this problem on the latest version of obsidian and excalidraw plugin and the website.

<img width="1064" height="922" alt="Image" src="https://github.com/user-attachments/assets/ad85c052-5174-45de-b855-b3a7b04fbccb" />

I don't know why I can't at least have the pen be of a different stroke size than the other shapes.

even then at least it will be closer but why isn't this solved is still missed with my usability with this app.

**Comment by mibpaz** [comment]
This is still relevant! Thinnest line vs thinnest pencil at 100% zoom.
Makes writing almost unusable unless you're extremely zoomed out (then it doesn't match the shapes)
<img width="173" height="432" alt="Image" src="https://github.com/user-attachments/assets/59d8ce70-fae0-4dc1-8e4c-40fe3b614dd9" />

**Comment by AhmedLilah** [comment]
Isn't this supposed to be just a size parameter and maybe a function of the zoom?

I'm honestly struggling to understand why it's taking that long to fix.

Not that you guys have to fix it. I know you're volunteering your work.

But this doesn't seem to be a major structural issue with the app.

Even if I doubt it'd still be fixable by a variable that controls the thickness.
