### ISSUE TITLE
Prettier support (v2)

### ISSUE THREAD

**Issue by azz** [excalidraw/excalidraw#748]
Excalidraw should have a button to run Prettier on a text block!

**Comment by vjeux** [comment]
Should probably have syntax highlighting first :p 

More seriously, so far I haven’t seen a lot code being used with excalidraw, so not sure how real a use case this is

**Comment by azz** [comment]
I've been using JSON in excalidraw for API examples

![image](https://user-images.githubusercontent.com/1297597/74118491-b732c680-4c0f-11ea-8efd-16c46c0647dd.png)

Syntax highlighting would be awesome!

**Comment by vjeux** [comment]
I'll go ahead and close this, I feel like this is not excalidraw's job to pretty print code. Especially since it would require importing a huge library.
