### ISSUE TITLE
Ask user if he want to continue with unfinished project

### ISSUE THREAD

**Issue by szympajka** [excalidraw/excalidraw#751]
Right now, when user enters Excalidraw page, app will automatically load the scene user were working on previously. This is brilliant, but it doesn't suit every case. I personally more often start new work than continue work on previous scene.

My proposal is to have simple popup (mockup below) which will ask user to continue, or start with new project:

<img width="975" alt="Screenshot 2020-02-10 at 10 45 28" src="https://user-images.githubusercontent.com/19807209/74143562-ee46af00-4bf2-11ea-8728-ee8656f69566.png">

**Comment by lipis** [comment]
Isn't just easier to clean the scene instead of doing that? This will also affect if you refresh the page.. what should we do here?

**Comment by dwelle** [comment]
I agree with @lipis. This also goes against our philosophy (which we haven't written down anywhere yet, so you couldn't have known) to remove all friction when opening excalidraw, and mirrors UI of heavy-duty apps like vector graphics editors, draw.io etc.

So I'm closing this as wontfix.

Nevertheless, thanks for a well-meant and very well illustrated suggestion, so don't let this discourage you from making another ones in the future! :+1:
