### ISSUE TITLE
support `roundness` for images

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#7515]
To add roundness support when rendering HTMLImageElement on canvas, we'll need to add a [clip path](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/clip) likely here:

https://github.com/excalidraw/excalidraw/blob/4249b7dec888711796fac1b043b3e982b35fa647/packages/excalidraw/renderer/renderElement.ts#L313-L329

And use [<mask>](https://developer.mozilla.org/en-US/docs/Web/SVG/Element/mask) when rendering to SVG.

The clip path & mask should align with the algo we use for rectangle roundness.

**Comment by aashirisrar** [comment]
@dwelle kindly review

**Comment by Arav1nd2** [comment]
@dwelle I was drafting an approach to implement this feature. My understanding of the requirements are
1. The image should be clipped
2. The clip mask should be a rectangle ( same as how any other rectangle is drawn in excalidraw ) 

With this I started with the following approach.
1. Compose a `ExcalidrawRectangleElement` based on the dimensions of the image element.
2. First draw the rectangle.
3. Clip the canvas using [clip path](https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/clip) API
4. Render the image

With this approach, I am close the desired outcome however the clipping between the rectangle's strokes. 
<img width="672" alt="Screenshot 2024-01-14 at 9 09 46 PM" src="https://github.com/excalidraw/excalidraw/assets/43083674/99fba938-6339-467d-8a03-688cbaabb2d7">


Wanted to check, am I on the right direction? Or I am looking a totally wrong direction? This is my first attempt to contribute to excalidraw. Pls excuse if the query was too lame 🙈
