### ISSUE TITLE
I am using excalidraw in ,net core project. I want to get selected elements of excalidraw. How can we do that ?

### ISSUE THREAD

**Issue by GurdeepSingh55** [excalidraw/excalidraw#7528]
I am using excalidraw in ,net core project. I want to get selected elements of excalidraw. How can we do that ?

**Comment by p2gdeveloper** [comment]
Some [clues ](https://github.com/excalidraw/excalidraw/blob/a4e5e46dd17e854fbb891d45edcb57405171c861/packages/excalidraw/scene/selection.ts#L168)here perhaps.

**Comment by ad1992** [comment]
Its answered [here] (https://github.com/excalidraw/excalidraw/discussions/6537#discussioncomment-8090898), closing this, @p2gdeveloper in case the answer doesn't help, you can open a QnA in the [GitHub Discussions](https://github.com/excalidraw/excalidraw/discussions)

**Comment by Linkens** [comment]
> I am using excalidraw in ,net core project. I want to get selected elements of excalidraw. How can we do that ?

I'd like to do the same, how did you run excalidraw with asp.net core ? I'im used to use only cdnjs package, not sure how to compile this one
