### ISSUE TITLE
In HTML it is not working Please Help me

### ISSUE THREAD

**Issue by Ahsannaeem405** [excalidraw/excalidraw#7534]
my index.html
<!DOCTYPE html>
<html>
  <head>
    <title>Excalidraw in browser</title>
    <meta charset="UTF-8" />
    <script src="https://unpkg.com/react@18.2.0/umd/react.development.js"></script>
    <script src="https://unpkg.com/react-dom@18.2.0/umd/react-dom.development.js"></script>

    <script
      type="text/javascript"
      src="https://unpkg.com/@excalidraw/excalidraw/dist/excalidraw.development.js"
    ></script>
  </head>

  <body>
    <div class="container">
      <h1>Excalidraw Embed Example</h1>
      <div id="app"></div>
    </div>
    <script type="text/javascript" src="packages/excalidraw/index.js"></script>
  </body>
</html>

my index.js code

const App = () => {
  return React.createElement(
    React.Fragment,
    null,
    React.createElement(
      "div",
      {
        style: { height: "500px" },
      },
      React.createElement(ExcalidrawLib.Excalidraw),
    ),
  );
};

const excalidrawWrapper = document.getElementById("app");
const root = ReactDOM.createRoot(excalidrawWrapper);
root.render(React.createElement(App));

what i get in response 
![error](https://github.com/excalidraw/excalidraw/assets/69482382/5072087d-3a35-455c-8285-47bdf275e6a1)

**Comment by PavBhajiProgrammer** [comment]
The issue with your code is that you are trying to use ExcalidrawLib.Excalidraw in your index.js, but you haven't defined ExcalidrawLib anywhere in your code. Or try using just
 `React.createElement(Excalidraw.Excalidraw),`

**Comment by ad1992** [comment]
@Ahsannaeem405 the [patch](https://github.com/excalidraw/excalidraw/pull/7349) was released in `v0.17.1` for this, can you try loading `https://unpkg.com/@excalidraw/excalidraw@0.17.1/dist/excalidraw.development.js` and it will work.

Here is [CSB](https://h5r6js.csb.app/) for the same as well

Looks like this patch was mistakenly removed in `0.17.2` and hence it doesn't work
cc @dwelle

**Comment by JamMaster1999** [comment]
I have the same exact issue. With 17.1 things are working smoothly but not in 17.2. It would be great if we could have this available in the latest version. 
Thank you so much @ad1992 @dwelle

**Comment by ad1992** [comment]
> I have the same exact issue. With 17.1 things are working smoothly but not in 17.2. It would be great if we could have this available in the latest version. Thank you so much @ad1992 @dwelle

We will release another patch soon, however it's absolutely fine to use `0.17.1` till then :)
closing this as its resolved!
