### ISSUE TITLE
"Self hosted" excalidraw exports SVG with non standard path

### ISSUE THREAD

**Issue by bric3** [excalidraw/excalidraw#7543]
Hi, I'm the developer of the IntelliJ plugin that integrates Excalidraw. 

I recently upgraded excalidraw, I noticed that SVG files have now the "wrong" URL for some assets like the fonts.

```diff
  <svg version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 437.9033836762792 296" width="875.8067673525584" height="592">
    ...
    <defs>
      <style class="style-fonts">
        @font-face {
          font-family: "Virgil";
-         src: url("https://excalidraw.com/Virgil.woff2");
+         src: url("https://excalidraw-jetbrains-plugin//dist/excalidraw-assets/Virgil.woff2");
        }
        @font-face {
          font-family: "Cascadia";
-         src: url("https://excalidraw.com/Cascadia.woff2");
+         src: url("https://excalidraw-jetbrains-plugin//dist/excalidraw-assets/Cascadia.woff2");
        }
      </style>
      
    </defs>
    ...
  </svg>
```

It appears this is related to this change.
* https://github.com/excalidraw/excalidraw/issues/5063

I am actually interested by the opposite. In order to interface the webapp with IntelliJ (and to work offline), Excalidraw is self hosted in the IJ process.

However I would like the SVG files to keep the standard assets path, i.e. the one that goes to excalidraw.com. I looked at the change and I'm not sure it is possible to work around it.

I do understand the original issue, but maybe there should be an option to use the standard paths ?

**Comment by mwopfner** [comment]
It would be great to have a way to define an own url prefix when an svg file is exported.

**Comment by bric3** [comment]
For now I'm working around this by patching the SVG string myself. But this is less than optimal.

**Comment by chowey** [comment]
Even better might be to also allow a locally-installed font:

```
src: url("https://my-url/Cascadia.woff2"),  local("Cascadia"), url("https://excalidraw.com/Cascadia.woff2");
```

**Comment by bric3** [comment]
Hi there, I would like some help regarding this ? This could help the VSCode extension and the JetBrains plugin, which are self-hosted, but still living under the Excalidraw name (as opposed to an hosted app hosted on a different website living under a different name).

Nerd snipping @dwelle :)

**Comment by karlhorky** [comment]
@Mrazator @dwelle now that the new font picker (and font embedding) has been published in https://github.com/excalidraw/excalidraw/pull/8012, how easy would it be to fix font paths for "self-hosted" Excalidraw?

Specifically, I mean the usage of Excalidraw in the Excalidraw VS Code extension by @pomdtr:

- https://github.com/excalidraw/excalidraw-vscode/issues/100

**Comment by Mrazator** [comment]
> how easy would it be to fix font paths for "self-hosted" Excalidraw?

Since the fonts are now inlined as dataurl, this and related issues with incorrect font paths in SVGs should disappear. Recently we've also shipped glyph subsetting (https://github.com/excalidraw/excalidraw/issues/8300), which keeps the data URL as small as possible (containing only glyphs for the used codepoints).

**Comment by bric3** [comment]
> Since the fonts are now inlined as dataurl, this and related issues with incorrect font paths in SVGs should disappear. 
> Recently we've also shipped glyph subsetting (https://github.com/excalidraw/excalidraw/issues/8300), which keeps the data URL as small as possible (containing only glyphs for the used codepoints).

So if I'm reading this correctly, the next Excalidraw release that can we can package in our plugins (either for VSCode, JetBrains, or else) will use the `window.EXCALIDRAW_ASSET_PATH` to use "plugin local" fonts, but the saved files will use a base 64 url like this ?

```
@font-face {
  font-family: "Cascadia";
  src: url(data:font/opentype; base64, [Cascadia glyphs in base64]);
}
```

**Comment by Mrazator** [comment]
Yup

**Comment by pomdtr** [comment]
I tried to pull the changes in the VS Code extension, but I encountered a bunch of issues:

https://github.com/excalidraw/excalidraw-vscode/issues/100#issuecomment-2383705504

Might be worth taking a look

**Comment by bric3** [comment]
I'm waiting on the next excalidraw release, latest was 0.17.3. I know I may miss on new features, but I'm not in capacity to handle any trunk or perform a snapshot release myself.

**Comment by Mrazator** [comment]
Alright, closing as completed. Thanks!
