### ISSUE TITLE
Text alignment

### ISSUE THREAD

**Issue by tu4mo** [excalidraw/excalidraw#755]
Would be great to be able to center or right align multiline text.

**Comment by Fausto95** [comment]
<img width="204" alt="Capture d’écran 2020-02-10 à 20 06 52" src="https://user-images.githubusercontent.com/23306911/74181110-f3cae600-4c40-11ea-86f8-89e482d275d3.png">

You want it centered like the green text?

**Comment by vjeux** [comment]
Yeah, would be nice to be able to set the text bounding box and usual controls to control alignment.

**Comment by yuanworks** [comment]
If it's okay, I would like to work on the text align functionality. _WIP_ 👇 

![excali_text_center](https://user-images.githubusercontent.com/3508123/75094952-c54af480-55ca-11ea-8c39-c94c30d2c12f.gif)

@vjeux great work on excalidraw by the way. Loving it! 💯

**Comment by vjeux** [comment]
For aligning text, we need to change how we compute the bounding boxes. If you look at all the presentation software (keynote, powerpoint...), you draw a rectangle and text is laid out within this rectangle.

We need to do something similar here, where the rectangle is different than the actual text boundary.

**Comment by dwelle** [comment]
Should we add support for multiple alignments in the same PR? https://github.com/excalidraw/excalidraw/issues/791

**Comment by lipis** [comment]
This done!
