### ISSUE TITLE
[discussion] Add option to collaborate

### ISSUE THREAD

**Issue by szympajka** [excalidraw/excalidraw#758]
It would be great to be able to work on the same board with multiple users. It's more an idea placeholder for now, rather than actual task. Would it be inline with Excalidraw development plan? :)

**Comment by vjeux** [comment]
Agreed, that would be great!

**Comment by j-f1** [comment]
JSFiddle uses [TogetherJS](https://togetherjs.com).

**Comment by dwelle** [comment]
@j-f1 interesting project. I tried it on jsfiddle and it sometimes works, sometimes not, and that's just textareas, so I'd be surprised if it worked in our project.

It also seems pretty dead:

- [How can we restart / expand TogetherJS development?](https://github.com/mozilla/togetherjs/issues/1127)

![image](https://user-images.githubusercontent.com/5153846/75072119-1a1d3b00-54f7-11ea-9e0d-c059b4f2abdd.png)

**Comment by vjeux** [comment]
Done!!
