### ISSUE TITLE
Don't regenerate line shape on point commit

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#760]
When you draw multi-point arrow, on each point commit the shape is regenerated, technically unnecessarily. We're already not doing it during shape creation (notice when I move the point before committing it, only the part of the bezier curve that's directly affected is redrawn):

![excalidraw_arrows_commit_redraw](https://user-images.githubusercontent.com/5153846/74242905-0693f800-4cdf-11ea-9ce1-fcdf60479c88.gif)

/cc @GasimGasimzada

**Comment by GasimGasimzada** [comment]
I don't know what you mean. Are you talking about the weird "stutter" when committing points? I will investigate but that is a bit weird because both committing and moving the latest point uses the same logic for shape regeneration.

**Comment by dwelle** [comment]
Yea, I don't think it's a stutter. It distinctly looks like the shape is redrawn.

**Comment by GasimGasimzada** [comment]
Do you know how to prevent that in Roughjs? Maybe something to do with seed value?

**Comment by dwelle** [comment]
No clue on my end :(.

**Comment by vjeux** [comment]
Yeah, this is annoying, I wish we could fix that!

**Comment by pshihn** [comment]
This should be resolved by upgrading to roughjs 4.3.1

**Comment by dwelle** [comment]
Thanks for the fix @pshihn, works great!
