### ISSUE TITLE
Broken shareable link for presentation after moving document

### ISSUE THREAD

**Issue by seigel** [excalidraw/excalidraw#7610]
Here is what I did and where I got stuck.... (I am a plus user)

I created a presentation in "Private".
I went to the "share" menu and created a read-only shareable link for the presentation.
I tested it in an incognito window.  It worked
I pasted it slack, or shared the link.

I organized my documents in excalidraw, i.e. I moved it from private to a more appropriate folder.

People reported that they could not view the presentation!  "Viewing Slide 1/0" or Slide NaN
I tried to recreate the link somehow, but the original is the only thing that is there.  I cannot create a new link

I would expect that I could refresh the link or that the original link would follow the document.

Thanks!

**Comment by maielo** [comment]
Hey @seigel thanks for reporting this!

We can not reproduce it, so I assume it was fixed in many iterations of fixes we made to presentations. 

In case you still can reproduce the issue let us know! (support@excalidraw.com for faster response)
