### ISSUE TITLE
process is not defined

### ISSUE THREAD

**Issue by litttley** [excalidraw/excalidraw#7616]
```
ReferenceError: process is not defined  at ./node_modules/@excalidraw/excalidraw/main.js 
```

**Comment by Lokendra-sinh** [comment]
Could you please outline the steps to reproduce the issue? I would like to know what are you doing and how are you doing it

**Comment by Soliden-96** [comment]
I encountered this error while using Vite.
If that's your case you can find the solution in this section of the documentation: [Excalidraw/Integration/Preact](https://docs.excalidraw.com/docs/@excalidraw/excalidraw/integration#preact)

**Comment by editfund-3rd** [comment]
dev-docs > docusaurus.config.js
```js
process.env.IS_PREACT = "false";

docusaurus3-dotenv?
```

**Comment by litttley** [comment]
> ### 💞🤝Update `dev-docs` from `docusaurus2` to `docusaurus3`
> docusaurus.config.js:
> 
> ```js
> process.env.IS_PREACT = "false";
> .
> .
> .
> 
> //🧐
> //🧐docusaurus3-dotenv?
> ```
> 
> 🙀Error:process is not defined.

yes,this issue is cause in docusaurus3 application

**Comment by ad1992** [comment]
closing this in favor of #7621
