### ISSUE TITLE
Cannot able to change individual letter color in textgroup

### ISSUE THREAD

**Issue by ArshilHapani** [excalidraw/excalidraw#7651]
while writing the text in canvas when we tries to change the color of selected text then it changes the color of whole group text.
![image](https://github.com/excalidraw/excalidraw/assets/108511809/d6004198-f49e-43b7-9a53-e0cbca0e7dc8)
Instead of selected parts it ended up changing the whole textgroup color

**Comment by DongHY1** [comment]
same question

**Comment by ad1992** [comment]
@ArshilHapani this isn't possible right now.  Once we support Rich text editor, decorating parts of text will be possible. Closing in favor of #6678
