### ISSUE TITLE
convertToExcalidrawElements() will lost customData field

### ISSUE THREAD

**Issue by yubinTW** [excalidraw/excalidraw#7654]
Hi, when I use `convertToExcalidrawElements()` to convert `ExcalidrawElementSkeleton` to `ExcalidrawElement`, the `customData` field will disappear.

```typescript
const rawData: ExcalidrawElementSkeleton[] = [
      {
        type: "rectangle",
        x: 100,
        y: 100,
        customData: { createdBy: "user01" },
      },
    ];
const convertedElements = convertToExcalidrawElements(rawData);
console.log("my customData =", convertedElements[0].customData); // undefined
```

`customData` is useful for bringing some information. but when convert the skeleton to excalidraw element, it will disappear.

**Comment by dwelle** [comment]
fixed by https://github.com/excalidraw/excalidraw/pull/7656
