### ISSUE TITLE
change default value the sloppiness: "architect"

### ISSUE THREAD

**Issue by Tahmasb** [excalidraw/excalidraw#7665]
Hello
How can I change the default value of sloppiness to architect?

**Comment by Tahmasb** [comment]
![image](https://github.com/excalidraw/excalidraw/assets/103024706/3d8d5d9d-a611-424c-80df-906d8888275d)

**Comment by ayawai** [comment]
Hello, How did you solve it?

**Comment by Tahmasb** [comment]
with this code
<Excalidraw
        langCode="fa-IR"
        UIOptions={{
          tools: { image: false },
        }}
        initialData={{
          appState: {
            currentItemFontFamily: 2,
            currentItemStrokeWidth: 1,
            currentItemRoughness: 0,
          },
        }}
      />

**Comment by ayawai** [comment]
thank you!!!!!!
