### ISSUE TITLE
Getting error "Couldn't save to the backend database. If problems persist, you should save your file locally to ensure you don't lose your work." while running collaboration-room with excalidraw-0.17.0

### ISSUE THREAD

**Issue by vashishthask** [excalidraw/excalidraw#7678]
I am trying to run excalidraw with excalidraw-room on Windows 10 machine. The connection is established for collaboration and collaboration happens as well but I keep getting an error "Couldn't save to the backend database. If problems persist, you should save your file locally to ensure you don't lose your work." on all browsers using live collaboration. Do I need to set up a backend database as well for collaboration-room as that is not evident from collaboration-room setup instructions?

**Comment by vashishthask** [comment]
The error was happening as persistence store firebase.googleapis.com was blocked in the firewall

**Comment by theoryshaw** [comment]
just an fyi, i'm getting this error as well.
