### ISSUE TITLE
Issues : Generating dist folder

### ISSUE THREAD

**Issue by ChanduSekharB** [excalidraw/excalidraw#7682]
I'm trying to perform Yarn Build. But the build is failing and test cases are failing while looking for the state and they are looking for @types folder in packages

Below are the errors 

Errors  Files
     2  tests/collab.test.tsx:86
     1  ../packages/excalidraw/components/App.tsx:9517
     1  ../packages/excalidraw/components/TTDDialog/common.ts:98
     1  ../packages/excalidraw/element/textWysiwyg.test.tsx:58
    72  ../packages/excalidraw/frame.test.tsx:125
    25  ../packages/excalidraw/tests/align.test.tsx:159
     4  ../packages/excalidraw/tests/binding.test.tsx:38
     4  ../packages/excalidraw/tests/clipboard.test.tsx:144
     1  ../packages/excalidraw/tests/elementLocking.test.tsx:104
     2  ../packages/excalidraw/tests/export.test.tsx:52
    38  ../packages/excalidraw/tests/flip.test.tsx:210
    10  ../packages/excalidraw/tests/history.test.tsx:31
    39  ../packages/excalidraw/tests/linearElementEditor.test.tsx:77
    16  ../packages/excalidraw/tests/zindex.test.tsx:88
✓ 2218 modules transformed.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by ad1992** [comment]
Hi @ChanduSekharB , it works fine in the repository. Could you help with answering below queries 👇
Have you installed all the dependencies?
What exact commands are you running and in which folder ? Also which OS and what is your node version?

**Comment by ChanduSekharB** [comment]
Hi @ad1992 ,

I want to generate excalidraw.development.js and prod.js in my machine. I followed the steps mentioned in document. Now it is building .but I couldn't able to find .js files.

Could you please help with the steps

**Comment by ad1992** [comment]
> Hi @ad1992 ,
> 
> I want to generate excalidraw.development.js and prod.js in my machine. I followed the steps mentioned in document. Now it is building .but I couldn't able to find .js files.
> 
> Could you please help with the steps

If you are pulling the latest code then there are slight changes since we are moving to ESM so you can follow the below 👇
1. Run `yarn` in packages/excalidraw folder - to install all dependencies
2. Run `yarn build:esm` and this will created all the build related files.

Thats all and it should work.

**Comment by ChanduSekharB** [comment]
Hi @ad1992 

Im using windows 11 and latest node version . Still im getting the error.

![image](https://github.com/excalidraw/excalidraw/assets/62057106/e42c6611-442c-4499-9643-51e1dc60575f)

**Comment by ChanduSekharB** [comment]
Thanks it worked
