### ISSUE TITLE
Align items

### ISSUE THREAD

**Issue by nc-rasel** [excalidraw/excalidraw#772]
It's a feature request!  
Would be great If we can align multiple element to left, right, center, middle, top or even bottom by a single click. Basically the way sketch or Adobe XD does. 
For an example I will select multiple rectangle by selection tool and click Align to Left call to action from left tools panel. 
<img width="599" alt="image" src="https://user-images.githubusercontent.com/1910377/74608665-5c1c3a80-510d-11ea-92aa-4548a90a3c9d.png">

**Comment by lipis** [comment]
It's live!

**Comment by georgecrawford** [comment]
Sorry - stupid question, but _where_ is it live? I don't see an align option at https://excalidraw.com/. Is it waiting for some kind of release schedule? Thanks!

**Comment by dwelle** [comment]
You must select at least 2 elements for the align buttons to show up. If it doesn't show up, can you open up the console, paste in `__EXCALIDRAW_SHA__`, and paste it back here?

**Comment by georgecrawford** [comment]
`__EXCALIDRAW_SHA__` is `f64f98b7798003a0da1be665c6fb522cbdf45ddd`.

There are some console errors:
```
Error with Feature-Policy header: Unrecognized feature: '*'.
(index):1 Refused to apply style from 'https://excalidraw.com/app.css' because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enabled.
DevTools failed to load SourceMap: Could not parse content for https://excalidraw.com/static/css/main.74bc6c24.chunk.css.map: Unexpected token < in JSON at position 0
```

<img width="706" alt="2021:02:17-14 39 55" src="https://user-images.githubusercontent.com/84737/108220000-2f3ea100-712e-11eb-9c00-f5abb3fd9d27.png">

**Comment by dwelle** [comment]
Woah, that commit is super old: [Jul 22, 2020](https://github.com/excalidraw/excalidraw/commit/f64f98b7798003a0da1be665c6fb522cbdf45ddd). People often get stale versions until the browser decides it's time to refresh the ServiceWorker, but nothing like that old. Are you on a PWA or a regular browser?

In either case, you can `Cmd/Ctrl+F5` to hard-refresh and get latest version.

**Comment by georgecrawford** [comment]
Woo-hoo! I'm so glad I asked!

Chrome/OS X, regular browser window. I guess it was a badly-cached serviceworker. I've been using it quite a lot and had no idea I was missing on so many months of releases.

Thanks for your help, @dwelle, and the great app.
