### ISSUE TITLE
Excalidraw

### ISSUE THREAD

**Issue by MalysMarcin** [excalidraw/excalidraw#7747]
Hi,
When I copy Frame link from Excalidraw to Obsidian note, there is no preview. Just blank, white rectangle. When I embedd a frame it works normally, only links preview does not.
And it does work on older files, created like 5 months ago. Since a month or sth like that it does not appear.
However, if I click link, it opens linked frame correctly.
Does anyone know what could be the answer?
this works:
![image](https://github.com/excalidraw/excalidraw/assets/123721968/c12355cd-f230-4298-baa4-f54b52ed64a5)
 this does not:
![image](https://github.com/excalidraw/excalidraw/assets/123721968/54086bb4-34a1-47c0-b6cd-18c106bb95c6)

And this is the same with Area or Group elements.

Best regards
Marcin

**Comment by dwelle** [comment]
Hi, best ask on the Obsidian Excalidraw plugin repo directly: https://github.com/zsviczian/obsidian-excalidraw-plugin/issues
