### ISSUE TITLE
Some elements don't appear in export

### ISSUE THREAD

**Issue by sudo-nano** [excalidraw/excalidraw#7751]
For some reason, the attached Excalidraw scene doesn't export properly. Some elements get dropped and don't make it to the export window. This is fixed by grouping all elements in the scene together, except the frames are still missing or improperly rendered. 

## Platform Info 
**Excalidraw Version:** 2024-03-05T22:22:34Z-a38e82f (latest on excalidraw.com as of 6 March 2024)
**OS:** Linux Mint 21.1
**Browser:** Firefox 123.0 (64-bit)

### Screenshot of Canvas: 
![excalidraw_scene](https://github.com/excalidraw/excalidraw/assets/63484662/3bdf5881-6b09-4103-b727-ad7aea506121)

### Screenshot of export screen (elements missing in preview box):
![excalidraw_export](https://github.com/excalidraw/excalidraw/assets/63484662/ed19a97f-f906-4e47-b8fd-a881e73b8920)

### Exported PNG (elements grouped, everything present except incorrectly rendered frames):
![Problem2_PartA](https://github.com/excalidraw/excalidraw/assets/63484662/e85e2343-aa1f-47a4-b33b-ef5fc0cb4cbb)

### Bugged Excalidraw scene (uploaded as zip because GitHub won't take .excalidraw):
[Problem2_PartA.excalidraw.zip](https://github.com/excalidraw/excalidraw/files/14507005/Problem2_PartA.excalidraw.zip)

**Comment by dwelle** [comment]
Thanks for the report @sudo-nano!

**Comment by sudo-nano** [comment]
Of course, thanks for the prompt fix! That was incredibly fast!
