### ISSUE TITLE
Add zoom reset button

### ISSUE THREAD

**Issue by OrenMe** [excalidraw/excalidraw#776]
Sometimes I zoom in or out a lot and I want to instantly go back to zoom scale 1.
Currently there is a keyboard shortcut, but the keyboard shortcuts are not immediately known and it feels a bit unintuitive.
I want to suggest adding a reset button that will appear only upon clicking the zoom in/out, i.e. not being in zoom state 1.
![image](https://user-images.githubusercontent.com/5461862/74644433-f072b580-517e-11ea-983f-0fbc2fd10bb7.png)
![image](https://user-images.githubusercontent.com/5461862/74644447-f9638700-517e-11ea-846b-a133e856210c.png)
![image](https://user-images.githubusercontent.com/5461862/74644481-02545880-517f-11ea-93d0-97fcbf12ee38.png)

Re:keybaord shortcuts - maybe we need a right click action for showing the various keyboard shortcuts? maybe we have this? if not I can open an issue

**Comment by lipis** [comment]
Regarding shortcuts we have an open issue for it: https://github.com/excalidraw/excalidraw/issues/408
