### ISSUE TITLE
Can't turn off pressure sensitivity

### ISSUE THREAD

**Issue by salesp07** [excalidraw/excalidraw#7763]
When using a drawing tablet on excalidraw, the line appears too thick due to pressure sensitivity. I'd love to be able to turn that off.

**Comment by ShonenAsh** [comment]
Yep, it's preventing me from using this gold of an application on my iPad.

**Comment by Sciddie** [comment]
That function would be nice

**Comment by Mrazator** [comment]
Closing as duplicate of #3693.
