### ISSUE TITLE
\n in mermaid to excalidraw renders as \n instead of newline

### ISSUE THREAD

**Issue by skycloudd** [excalidraw/excalidraw#7765]
A `\n` in Mermaid code isnt converted to an actual newline when converted to an Excalidraw diagram

For example:

```
classDiagram
    note "test 123\ntest 456"
```

```mermaid
classDiagram
    note "test 123\ntest 456"
```

Is incorrectly converted to:

<img width="133" alt="image" src="https://github.com/excalidraw/mermaid-to-excalidraw/assets/51929172/0d0f1efa-838e-40ce-abc7-3a2747c9ef45">

I expect `test 456` to be on a new line.

This is the same as excalidraw/mermaid-to-excalidraw/issues/47 but that repo doesn't seem to be as active and I'm not sure whether it was the correct repo for this issue.

**Comment by ad1992** [comment]
closed in favor of https://github.com/excalidraw/mermaid-to-excalidraw/issues/47
