### ISSUE TITLE
Investigate other hosting providers

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#778]
Right now I'm getting a whopping 6 second TTFB on index:

![image](https://user-images.githubusercontent.com/5153846/74825603-81c26300-530a-11ea-92ba-49e3619d9f0c.png)

We don't necessarily need to change providers, but I'd consider striking a deal with Netlify whether they can sponsor us with a higher tier (provided we want to stay free & OSS).

**Comment by vjeux** [comment]
I’m going to try using zeit back when I’m home. cc @rauchg

**Comment by lipis** [comment]
For now I had to pay $14, because we exceeded some minutes on Netlify.. so let's see what we can do with zeit :)

**Comment by dwelle** [comment]
Hold on.. we're even paying for this? What have we exceeded? Build minutes?

**Comment by lipis** [comment]
Just sent them an email.. let's see :) I just didn't want to risk any downtime.. so I entered a credit card.

**Comment by vjeux** [comment]
Zeit seems to be much better now :)
