### ISSUE TITLE
The hint for the multipoint arrows/lines is hidden behind the zoom buttons.

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw#779]
In general we have to rethink these hints.. we should show them a couple of times, or maybe if the user will manage to create a multi point arrow or line, we should stop showing it.. (for his session obviously)

**Comment by vjeux** [comment]
Please send a PR to put the hints just below the shape selector. I believe this is the right thing to do and we don’t need to add a setting to hide them.
