### ISSUE TITLE
Can't sync to device theme

### ISSUE THREAD

**Issue by osbyrne** [excalidraw/excalidraw#7790]
I use excalidraw day and night. When I open it at night, I expect it to be dark like everything else on my device, but instead I get [flashbanged](https://youtu.be/ybaK3y_6YXg?si=xc1NFrn417SFCQ4m).

**Comment by Malix-off** [comment]
I also use a day/night cycle theme, I expect Excalidraw to follow it by default

**Comment by osbyrne** [comment]
![image](https://github.com/excalidraw/excalidraw/assets/68084397/55ba8ce2-12af-4848-992f-dbb7b88ec05e)
it is done!
