### ISSUE TITLE
Undo not working

### ISSUE THREAD

**Issue by sksusha8853** [excalidraw/excalidraw#7799]
In collaboration in excalidraw undo is not working.

**Comment by ghzeni** [comment]
I was saving a selected part of an excalidraw flow and when naming the new file I pressed delete without realising the text wasn't focused yet. This deleted the part I was exporting and even though I was able to save it to png, I wasn't able to undo the deletion and now i'm gonna have to redraw it 🙃

**Comment by CoderJoshDK** [comment]
I am noticing the same undo issue. When in collaboration mode, and there are multiple users active, the undo does not work. However, when the other member became inactive (they had the page open but were AFK // computer sleep), the undo started working again.

**Comment by Mrazator** [comment]
Status update: as part of https://github.com/excalidraw/excalidraw/pull/7348, we've recently shipped improvements for undo/redo on excalidraw.com & will be shipped on plus.excalidraw.com soonish!

Any feedback appreciated, in any case, reach us here or on Discord!
