### ISSUE TITLE
Overide the shortcut Ctrl+S for own function

### ISSUE THREAD

**Issue by leonidlezner** [excalidraw/excalidraw#7807]
Hello!

I'm trying to implement my own backend for working with Excalidraw files. Everything working fine so far, but I can't change the default behavior of the Ctrl+S shortcut. I would like to trigger my own function instead of downloading the .excalidraw file. I've tried following, but it is not working as soon as Excalidraw gets focus.

```
const handleKeyDown = (event: KeyboardEvent) => {
    if ((event.ctrlKey || event.metaKey) && event.key === "s") {
      event.preventDefault();
      save(); // my custom function for sending the content to backend
    }
  };

window.addEventListener("keydown", handleKeyDown);
```

**Comment by leonidlezner** [comment]
I've integrated Excalidraw in a WordPress Plugin. Saving a documents in this plugin means to save it to the backend. I would like to override Ctrl+S, so it can be done using a shortcut. As for today the user can only save by pressing the "Save" button.

More infos on the plugin here:
https://github.com/leonidlezner/excalidraw-wp-plugin

**Comment by kmr-ankitt** [comment]
Can i give this issue a try?

**Comment by parker594** [comment]
const handleKeyDown = (event) => {
  if ((event.ctrlKey || event.metaKey) && event.key === "s") {
    event.preventDefault();
    // Your custom logic here (e.g., send content to the backend)
  }
};

window.addEventListener("keydown", handleKeyDown);

just look over it

**Comment by yalogica** [comment]
> I've integrated Excalidraw in a WordPress Plugin. Saving a documents in this plugin means to save it to the backend. I would like to override Ctrl+S, so it can be done using a shortcut. As for today the user can only save by pressing the "Save" button.
> 
> More infos on the plugin here: https://github.com/leonidlezner/excalidraw-wp-plugin

As variant you can add this option to < Excalidraw />

`UIOptions={{
                            canvasActions: {
                                saveToActiveFile: false
                            }
                        }}`

**Comment by kaguya3222** [comment]
@leonidlezner Agree with above tip from @yalogica , if you need to implement something like custom handling of CTRL + S, then you can disable default behaviour with the above code. I don't see any reason to provide additional API for this, suggest closing 

@Mrazator WDYT?

**Comment by Mrazator** [comment]
Yeah, that should be the way, closing for now

@leonidlezner feel free to re-open if anything
