### ISSUE TITLE
how to initialize a plugin file at start with ".excalidrawlib" file?

### ISSUE THREAD

**Issue by lasivtech** [excalidraw/excalidraw#7809]
I'm trying "loadSceneOrLibraryFromBlob" method. but unable to find right way to do it.

**Comment by louwers** [comment]
See here https://github.com/excalidraw/excalidraw/blob/3e334a67ed43d11c6a5a331f82a847c07ff6175d/dev-docs/docs/%40excalidraw/excalidraw/api/utils/utils-intro.md#loadsceneorlibraryfromblob
