### ISSUE TITLE
Don't regenerate seed on element cloning

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#781]
When we clone an element, be it via `alt+drag` or copy/paste, I believe what the user wants is to keep the exact shape. Currently we generate new `seed` for those new elements, which results in new shape.

Thoughts?

EDIT: mhm, now I noticed this old issue from @vjeux  https://github.com/excalidraw/excalidraw/issues/81 - I guess we have different intuitions :thinking: 

Here's the use case: you create a complex shape composed of multiple elements, if you duplicate the whole group, I reckon you don't expect some lines to suddenly not connect etc. due to the shape being regenerated.

Either way I believe the whole point of duplicating something is for it to look identical.

**Comment by vjeux** [comment]
I disagree, if you duplicate elements you want the lines to be slightly different. This way they all look unique and hand drawn :)

**Comment by dwelle** [comment]
IMO if you want different shape, you draw a new one. But what should you do when you want to *duplicate* the same shape? You're out of luck currently.

Anyway, I don't feel as strongly about this as you, so let's close this :).

**Comment by vjeux** [comment]
For example, I drew a small bomb to represent a regression. I wanted to have a few in a row and copy pasting them gave each of them a unique look at feel, but still looked like bombs.

This is one of the value proposition of excalidraw to me.

**Comment by lipis** [comment]
I also agree with @vjeux. I actually noticed it when cloning elements and was pleasantly surprised that they have different seed..
