### ISSUE TITLE
Integration in Qwik: document is not defined 

### ISSUE THREAD

**Issue by sudipbhujel** [excalidraw/excalidraw#7810]
I am trying to integrate excalidraw in qwik application with qwikify$ wrapper function. But, I am getting `Internal server error: document is not defined` error. How can I make it work? 
`canvas.tsx`
```
/** @jsxImportSource react */
import { qwikify$ } from '@builder.io/qwik-react';
import { Excalidraw } from '@excalidraw/excalidraw';

export const QExcalidraw = qwikify$(Excalidraw);
```

`app.tsx`
```
export default component$(() => {
  return (
      <div style={{"height": "500px"}}>
        <QExcalidraw />
      </div>
  );
});
```

**Comment by ad1992** [comment]
@sudipbhujel I haven't worked with Qwik but from the above error looks like it is rendering on the server hence the `document` isn't defined, so you need to make sure Excalidraw is rendered only on the client as we don't support SSR. 
So can you instead use dynamic import or is there any way to render only on the client side in Qwik?

**Comment by sudipbhujel** [comment]
Thank you for your reply. I removed SSR mode but the problem remains same.

**Comment by sudipbhujel** [comment]
I fixed it using `useSignal` and `useVisibleTask$`,
`app.tsx`
```
const Loading = component$(() => <div>Loading</div>);

export default component$(() => {
  const component = useSignal<Component>(Loading);
  useVisibleTask$(() => {
    component.value = QExcalidraw;
  });

  return (
      <div style={{"height": "500px"}}>
        <component.value />
      </div>
  );
});
```
