### ISSUE TITLE
Text within shape not auto-expanding, clipping early

### ISSUE THREAD

**Issue by levonbrunson** [excalidraw/excalidraw#7816]
On Firefox 124.0.1 (64-bit), Macbook Pro 2017 Intel Chip.
This wasn't a problem before, began occurring recently.

https://github.com/excalidraw/excalidraw/assets/47164443/54854f58-eb17-4c91-9257-51a6d2feaafd

**Comment by Mrazator** [comment]
Are you by any chance of Firefox?

**Comment by levonbrunson** [comment]
I am. The issue appears to be resolved now, closing.
