### ISSUE TITLE
canvas panning not synchronized with zoom correctly

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#782]
Try wheel-dragging or spacebar-dragging.

In the GIF below, notice that the cursor should stay in the same place, but it moves as I drag:

![excalidraw_zoom_pan](https://user-images.githubusercontent.com/5153846/74882500-866d3280-536f-11ea-9e5b-dc53f466efb8.gif)

**Comment by j-f1** [comment]
Interestingly, the error only appears in one direction — the cursor is too far right when zoomed in and too far left when zoomed out.
