### ISSUE TITLE
Typo in the website when we click on share

### ISSUE THREAD

**Issue by kethesainikhil** [excalidraw/excalidraw#7826]
I have noticed a typo in the website when we click on share there should be cannot but instead you have can might be a small issue
![image](https://github.com/excalidraw/excalidraw/assets/70809367/79e185c5-70d6-46e2-bdb2-393d00293248) 

to get that issue just click on share on the top 

I would like to make this change if you assign me this task

**Comment by thiarapr** [comment]
I think that u need to read it carefully it is what it should be.

**Comment by kethesainikhil** [comment]
Yes sorry it's my mistake!
