### ISSUE TITLE
How to express "Intersection" of Sets in Maths ?

### ISSUE THREAD

**Issue by Daaasein** [excalidraw/excalidraw#7843]
![Intersection](https://github.com/excalidraw/excalidraw/assets/80614187/00c35523-afcc-455f-8ee1-7a35fa2e743e)

As the picture, I want to express the intersection of set A and set B. But I cannot find a way to do that.....

If it can be implement, please teach me how.

thanks!

**Comment by Mrazator** [comment]
At the moment there is no "flood fill" function that would easily fill the intersection with some color & pattern. However with a little bit of imagination, one could achieve the same by using fill on the multiline/free draw tools as once those get closed, they could be filled with an arbitrary background (it's kinda unexpected that it might feel like an easter egg). The result looks like this:

![image](https://github.com/excalidraw/excalidraw/assets/20387666/5498d4fa-8c38-4a98-9b5a-0f0f53ec9304)

The scene (also with other options): https://excalidraw.com/#json=jdv8XXt6ya5gRJ6HoULUa,CSFTm3A7K2Wr8d4uYy6Jtw

Check following for more details about multiline background fill: https://github.com/excalidraw/excalidraw/pull/1315
