### ISSUE TITLE
navigating to link is broken

### ISSUE THREAD

**Issue by zsviczian** [excalidraw/excalidraw#7858]
https://github.com/excalidraw/excalidraw/assets/14358394/2c3cadd2-cb01-4109-ab40-93ba23bf7a2c

**Comment by ad1992** [comment]
Looks like this has recently regressed in https://github.com/excalidraw/excalidraw/pull/7804/files 
cc @ryan-di @dwelle

**Comment by mariofontana** [comment]
> 2024-04-06.09-26-20.mp4

I also noticed that if I right click to change the link, it opens the new tab with "about:blank" and I can't change it.

**Comment by sdzialowski-godaddy** [comment]
I think it's fixed now
