### ISSUE TITLE
Why Can't I resize the box width or height wise?

### ISSUE THREAD

**Issue by codingmickey** [excalidraw/excalidraw#7864]
![image](https://github.com/excalidraw/excalidraw/assets/42518907/f5507589-24fd-41fd-9b57-c4f130d61d7b)

**Comment by alsongarbuja** [comment]
@codingmickey from the cutout screenshot you have provided it seems like you are trying to resize the text box which can only be resized in respect with both width and height from the **corner square points**.

The Rectangle `(R or 2)` can be resized from all respects width only, height only or both at same time. You need to hover your mouse over the smal rectangles on the corner or the edges of the boxes

**Comment by Mrazator** [comment]
We always calculate the bounding box based on the text content to make it as small as possible. Would you guys see a use case that does make sense to make the text area resizable, while keeping the text the same size? At the moment it's sort of possible as a side-effect of adding new whitespace (spaces, tabs, enters, etc.) to the content.

**Comment by alsongarbuja** [comment]
As of now for what excalidraw is most useful (which is creating rough sketches and diagrams in simple and fast way) it is not the most concerning issue. It can be closed if @codingmickey doesnot have anything to add on.

**Comment by dwelle** [comment]
This will be shipped tomorrow. Preview: https://excalidraw-gnhq7ih80-excalidraw.vercel.app/
