### ISSUE TITLE
I lost all my excalidraw (maybe due to Arc browser data)

### ISSUE THREAD

**Issue by thomasnpc** [excalidraw/excalidraw#7870]
Hello,
I have been storing a lot of ideas in one Excalidraw tab I have pinned in my Arc Browser.
For some reason, Arc rebooted and removed my browser history... and Excalidraw went blank.
I'd like to understand what happened to try to fix this and retrieve everything I had on my Excalidraw (if that's possible).
Arc Browser seems to save some of the cache in tha Application Support file.
Thanks for helping me!!
<img width="462" alt="image" src="https://github.com/excalidraw/excalidraw/assets/103261665/3c983e01-28f1-4b4a-9259-e42be704f925">

**Comment by JacobRSchwartzCEO** [comment]
Its probably not recoverable

**Comment by Mrazator** [comment]
Hi @thomasnpc, unfortunately, we are unable to recover the scene if the browser suddenly wipes out the data. You can try contacting Arc support, in case it would be still hidden somewhere in the caches.

Nevertheless, next time consider saving and loading your scene to / from a file; or saving your scene inside Excalidraw+.

<img width="820" alt="image" src="https://github.com/excalidraw/excalidraw/assets/20387666/833ded1a-4e12-421e-8a59-b1b548ecccd7">

**Comment by Mrazator** [comment]
That said unless you shared the scene and have a link to it, which isn't the case I suppose.
