### ISSUE TITLE
Mutating element

### ISSUE THREAD

**Issue by gosvoh** [excalidraw/excalidraw#7871]
Text doesn't rerender after calling mutateElement

```
onChange={(elements) => {
  // ...
  mutateElement(textElement, {
    text: newText,
    originalText: newText,
  });

  console.log(`text: ${textElement.text}, originalText: ${textElement.originalText}`);
}
```

https://github.com/excalidraw/excalidraw/assets/8506620/0c0ac371-1e0b-48a8-a75e-a6ac11f7e4ea

**Comment by Mrazator** [comment]
@gosvoh In order to update scene elements and experience the re-render refer to the following API https://docs.excalidraw.com/docs/@excalidraw/excalidraw/api/props/excalidraw-api#updatescene.

Feel free to reopen in case of other issues.
