### ISSUE TITLE
Image got currupt during editing, can't use mouse to select or open context menu

### ISSUE THREAD

**Issue by T3sT3ro** [excalidraw/excalidraw#7878]
I was just adding some shapes, and suddenly the app stopped responding to mouse drag, selection and RMB. Adding new shapes is allowed, but they can't be dragged anymore. The console is spammed with logs and hundreds of sentry post requests. Clearing the canvas and working on new image works again.

Not sure how it happened, I probably was holding a CTRL to align some new shape, but I may have also missclicked something. I think the image data is now corrupt but I don't know where. The new shapes I was adding were orange diamonds on the farthest right.

[Bez tytułu-2023-11-15-1354.excalidraw.txt](https://github.com/excalidraw/excalidraw/files/14944673/Bez.tytulu-2023-11-15-1354.excalidraw.txt)

Here is the image, just remove the `.txt` extension I added to please github.

Possibly relevant error from console:
```
index.js:31 Uncaught TypeError: Cannot read properties of undefined (reading '0')
    at pO (index.js:31:38)
    at b2 (index.js:49:9)
    at Jv (index.js:117:9)
    at z$ (shape.ts:270:25)
    at Nw.getElementShape (App.tsx:4383:13)
    at Nw.hitElement (App.tsx:4563:19)
    at App.tsx:4498:28
    at Array.filter (<anonymous>)
    at Nw.getElementsAtPosition (App.tsx:4498:8)
    at Nw.getElementAtPosition (App.tsx:4442:33)
    at App.tsx:5301:29
    at Object.p9 (react-dom.production.min.js:54:317)
    at y9 (react-dom.production.min.js:54:471)
    at v9 (react-dom.production.min.js:55:35)
    at Tb (react-dom.production.min.js:105:68)
    at nS (react-dom.production.min.js:106:380)
    at react-dom.production.min.js:117:104
    at Pv (react-dom.production.min.js:274:42)
    at Ix (react-dom.production.min.js:52:375)
    at Xp (react-dom.production.min.js:109:469)
    at sv (react-dom.production.min.js:74:59)
    at O9 (react-dom.production.min.js:73:186)
    at HTMLDivElement.r (helpers.js:72:23)
pO	@	index.js:31
b2	@	index.js:49
Jv	@	index.js:117
z$	@	shape.ts:270
getElementShape	@	App.tsx:4383
hitElement	@	App.tsx:4563
(anonymous)	@	App.tsx:4498
getElementsAtPosition	@	App.tsx:4498
getElementAtPosition	@	App.tsx:4442
(anonymous)	@	App.tsx:5301
p9	@	react-dom.production.min.js:54
y9	@	react-dom.production.min.js:54
v9	@	react-dom.production.min.js:55
Tb	@	react-dom.production.min.js:105
nS	@	react-dom.production.min.js:106
(anonymous)	@	react-dom.production.min.js:117
Pv	@	react-dom.production.min.js:274
Ix	@	react-dom.production.min.js:52
Xp	@	react-dom.production.min.js:109
sv	@	react-dom.production.min.js:74
O9	@	react-dom.production.min.js:73
r	@	helpers.js:72
```

the ID of the element causing the error: `NSPNRI1YgbZ0Kx8DQLgCe`. Seems like the `flatness` function assumes there are 4 points from a given offset at points table, but it for some reason starts at offset 18 on a table of size 20.

The likely culprit seems to be `pointsOnBezierCurves` doing some invalid split or assuming the bezier curve can always be split into cubic bezier splines, even though sometimes we are left with fever points. It can also be some unmet assumption that points array divides equally into segments of 4 control points?

(This happens in chrome).

Inside the file, if I remove the `[0, 0]` points to bring `points[]` array sizes to 4 for elements `nL4Hmfh6x3wiyJGfaURIF` and `NSPNRI1YgbZ0Kx8DQLgCe` the program goes back to normal and doesn't crash anymore. But the issue still remains, and idk what caused this ill-sized arrays to be written to file (or are they correct and it's just code that's wrong?)

**Comment by oldManLemon** [comment]
I am basically getting exactly the same errors 

```
Uncaught TypeError: i is undefined
    pO index.js:31
    b2 index.js:49
    Jv index.js:117
    z$ shape.ts:270
    getElementShape App.tsx:4383
    hitElement App.tsx:4563
    getElementsAtPosition App.tsx:4498
    getElementsAtPosition App.tsx:4498
    getElementAtPosition App.tsx:4442
    Nw App.tsx:5301
    React 11
    r helpers.js:72
2 index.js:31:37

```

**Comment by T3sT3ro** [comment]
Inside I removed the [0, 0] points to bring array sizes to 4 for elements `nL4Hmfh6x3wiyJGfaURIF` and `NSPNRI1YgbZ0Kx8DQLgCe`, so that it doesn't crash anymore. But the issue still remains, and idk what caused this ill-sized arrays to be written to file (or are they correct and it's just code that's wrong?)

**Comment by dwelle** [comment]
Fixed in https://github.com/excalidraw/excalidraw/pull/7881
