### ISSUE TITLE
I'm just wondering if we are paying monthly subscription and quite a lot of money why are we not getting what we are paying for?

### ISSUE THREAD

**Issue by najibghadri** [excalidraw/excalidraw#7890]
We are paying 7$ a months per each user to have live synchronization and we can almost never work on the same board at the same time on any board ever. Changes aren't synced even the user's cursor isn't synced I mean I could do that over the internet in a pet project... Can we expect fixes in these or we just pay for things we won't get, bc I see that you have abundance of unaddressed issues too.

**Comment by ryan-di** [comment]
@najibghadri hey there! Totally understand your frustration and we've been actively working on improving this issue. In fact, we're towards the very end of shipping https://github.com/excalidraw/excalidraw/pull/7348, which addresses multi-player collaboration.

**Comment by dwelle** [comment]
Hi @najibghadri — as per our discussion over email, the issue is likely due to a VPN/Firewall blocking our collab server. We can figure out the details in the thread! 🙏
