### ISSUE TITLE
Update latest docker image on dockerhub

### ISSUE THREAD

**Issue by Courtcircuits** [excalidraw/excalidraw#7893]
I use excalidraw on prem with your dockerhub image, but it hasn't been updated for 9 months : https://hub.docker.com/layers/excalidraw/excalidraw/latest/images/sha256-648edf36c55793fdeed475e09a86fb6c16a68783dc442d37d5070adfc0362a8f?context=explore
Could you had a job to push the latest version on dockerhub at every excalidraw update ?

**Comment by AlphaCraft9658** [comment]
I up this!

**Comment by Jogai** [comment]
fixed with #7430

**Comment by ad1992** [comment]
closed with #7430
