### ISSUE TITLE
[Feature] Draggable draw island menu

### ISSUE THREAD

**Issue by AdamLinCodes** [excalidraw/excalidraw#7894]
I've been using excalidraw for while, and I've always found it a bit inconvenient that I can neither hide, nor drag the island menu when drawing. I already have a fix for this and would love the opportunity to help contribute.

Here is the island menu I am refering to:
![Screenshot (63)](https://github.com/excalidraw/excalidraw/assets/108435887/63cdbf8e-acf8-48d1-81c3-1cfb2a661b81)

**Comment by AdamLinCodes** [comment]
I wrote a sulution using react-draggable package, but I think draggable is less desireable than being collapsable.

**Comment by Mrazator** [comment]
Thanks for the suggestion! For now, closing in favor of PR #7722, we will re-open or create a separate issue in case it won't get merged.

**Comment by elagasteratou** [comment]
Hi gang pr is now ready for review please read here https://github.com/excalidraw/excalidraw/pull/7722,
