### ISSUE TITLE
Double text positioning error

### ISSUE THREAD

**Issue by jillesme** [excalidraw/excalidraw#7897]
When creating a new rectangle with some text, every now and then the text looks "doubled". 

See attached gif in action: 
![CleanShot 2024-04-16 at 10 54 53](https://github.com/excalidraw/excalidraw/assets/2955483/772e6692-1047-4d7b-ab24-9bed6a5737cf)

Excuse the generic issue title, I can't think of a better description...

**Comment by louis030195** [comment]
oh this is veryyyyy annoying

**Comment by dwelle** [comment]
We'll fix asap
