### ISSUE TITLE
runtime issue with vite build tool. (process not defined)

### ISSUE THREAD

**Issue by gnaaruag** [excalidraw/excalidraw#7899]
I was trying to integrate @excalidraw/exacalidraw into my typescript + react  app with vite but i get `process is not defined at node_modules/@excalidraw/excalidraw/main.js` during runtime (i am guessing this has to do with vite env variables). have tried going through the docs (and everywhere else) and found nothing of use. is there something that can be done about this?

thank you and also I'm sorry if this is not an appropriate place to submit this.

**Comment by gnaaruag** [comment]
after further digging, the problem seems to be here

in @excalidraw/exalidraw/main.js
```
else if (process.env.NODE_ENV === "production") {
  module.exports = require("./dist/excalidraw.production.min.js");
} else {
  module.exports = require("./dist/excalidraw.development.js");
}
```
this is because how vite handles .env variables
here's a link to the vite doc [https://vitejs.dev/guide/env-and-mode](https://vitejs.dev/guide/env-and-mode)

ill try and work on this on my local setup in the meanwhile

**Comment by ad1992** [comment]
@gnaaruag could you check [this](https://docs.excalidraw.com/docs/@excalidraw/excalidraw/faq#referenceerror-process-is-not-defined) and update your setup ?

**Comment by gnaaruag** [comment]
yup works, sorry to have wasted your time
