### ISSUE TITLE
[Feature] Cut option

### ISSUE THREAD

**Issue by AdamLinCodes** [excalidraw/excalidraw#7900]
It would be really nice to have a cut option so that users can move around there sketches. I use excalidraw and onenote, and the fact that onenote has the cut ability does make the workflow a bit nicer.

**Comment by andrewblum** [comment]
Can I have clarity on what you mean @AdamLinCodes? Cutting / pasting / dragging a selection all work for me.

**Comment by AdamLinCodes** [comment]
> Can I have clarity on what you mean @AdamLinCodes? Cutting / pasting / dragging a selection all work for me. 

Of courae @andrewblum. Essentially it would work like a marker, and you could draw around a section of your sketch that you want to either cut or copy.

**Comment by andrewblum** [comment]
i am interested in looking at this, but I believe this is a replication of https://github.com/excalidraw/excalidraw/issues/6350 which already has some good discussion so I suggest we move over there as close this.

**Comment by AdamLinCodes** [comment]
@andrewblum Yes, ticket #6350  is far more fleshed out. Closing this now
