### ISSUE TITLE
Anchor text element to the left side when typing instead of center

### ISSUE THREAD

**Issue by Tibfib** [excalidraw/excalidraw#791]
Hi all!

I love excalidraw! I keep running into this one issue though. Whenever I type text, the text element is anchored in the center, meaning it grows to the left and the right as I type, instead of just growing to the right as I expect! Is there any way to anchor the text to the left side, instead of the center?

Does anyone else agree that anchoring to the left would be a better UX?

Here's a video demonstrating in case I explained poorly. https://streamable.com/tw1gg

**Comment by lipis** [comment]
Yes, we need to set the text alignment eventually.. We already tracking it in #755

**Comment by lipis** [comment]
Changing the default to the left, will ruin all the previous scenes.. So we might have to keep centre as a default though :)

**Comment by dwelle** [comment]
I think we set position on confirm once and that's it, so we can change the default as we like and it won't break anything.

**Comment by Tibfib** [comment]
Apologies, I was thinking #755 was for text alignment, not the anchoring of the text "box" but I can see how it could be the same.

I would love the default to be left anchored. I can't think of a reason to be center anchored.

**Comment by dwelle** [comment]
@Tibfib no problem. That issue was (still is?) actually about multiline alignment, so who knows. I'd also say text alignment and anchoring is the same issue.

As for use cases, I can't say, but no one really complained until now. I don't think about it myself because I always reposition the text, anyway.

The use case you've shown looks like a great candidate for using multiline (`shift + enter`) instead of adding new lines as new elements, though.

**Comment by Tibfib** [comment]
You're right, shift enter would solve it if I had remembered it was an option. What if I want custom spacing between lines? What if I'm trying to put text inside a rectangle?

https://streamable.com/1qj9g

**Comment by j-f1** [comment]
What if Excalidraw saved the last text alignment you’d set and used it as the default for the next text input? No config option, you can change the default easily, and it’s not that annoying if you want to use a different alignment once.

**Comment by dwelle** [comment]
@j-f1 that's how most (all?) of our properties work right now, so I reckon we'll use that workflow for this, too.

@Tibfib sure, it was just a suggestion for an interim solution. The alignment will be implemented either way.

**Comment by dwelle** [comment]
@Tibfib btw, looking at your 2nd screen share, I can think of another tip what we should convey to people: clicking in the vicinity of the middle of a shape when inserting text keeps the text centered to that shape (well, until you move it).
