### ISSUE TITLE
Allow configuring major grid lines

### ISSUE THREAD

**Issue by pspeter3** [excalidraw/excalidraw#7910]
I would love to be able to set the major grid lines to another number besides `5` depending on the diagram.

**Comment by zsviczian** [comment]
install the Set Grid script.

**Comment by pspeter3** [comment]
Which script is that?

**Comment by zsviczian** [comment]
Sorry. I mixed up the Excalidraw issue log with the Excalidraw Obsidian
issue log. In Obsidian you can add scripts to Excalidraw, and Set Grid does
what you are after. But those are not available on Excalidraw.com

**Comment by Mrazator** [comment]
Closing in favor of #2110
