### ISSUE TITLE
Feature: Allow cropping image when pasted in Excalidraw

### ISSUE THREAD

**Issue by PrathamSikka24** [excalidraw/excalidraw#7912]
Some images I download from the web, need to be cropped. I must crop them in my gallery/photos app and then paste them to excalidraw. I want that I should be able to paste an image from my downloads folder or whatever the path, double click the image and be able to crop it also, the way we do in Google Docs and elsewhere.

**Comment by Mrazator** [comment]
Closing in favor of #4236
