### ISSUE TITLE
Missing field type

### ISSUE THREAD

**Issue by Digital39999** [excalidraw/excalidraw#7913]
I accidentally found out that you can change laser color via untyped property and I wonder why is it not typed?
With that is there also a way to change cursor color?

![image](https://github.com/excalidraw/excalidraw/assets/65065580/3d8bbdc7-6317-427b-80b7-5ab1dbcf7db5)

![image](https://github.com/excalidraw/excalidraw/assets/65065580/10f653dc-336b-4c83-894d-cc99c1a7957d)
![image](https://github.com/excalidraw/excalidraw/assets/65065580/79023641-5a89-44cc-9474-0f543342f0a9)

**Comment by Mrazator** [comment]
There is no particular reason, the types were added later in #7130; soon we will be switching to a new build and the new minor release should include these types.
