### ISSUE TITLE
waring in reactjs

### ISSUE THREAD

**Issue by AsiyaBatool** [excalidraw/excalidraw#7920]
WARNING in ./node_modules/@excalidraw/excalidraw/dist/excalidraw.development.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from "data" URL: data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiLi4vLi4vLi4vbm9kZV9tb2R1bGVzL2Jyb3dzZXItZnMtYWNjZXNzL2Rpc3QvaW5kZXgubWpzLmpzIiwibWFwcGluZ3MiOiI7Ozs7Oz

**Comment by Jiaodaoyi** [comment]
WARNING in ./node_modules/@excalidraw/excalidraw/dist/excalidraw.development.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from "data" URL:   Have you solved this person's problem? Can you provide a solution?

**Comment by Jiaodaoyi** [comment]
Have you solved this person's problem? Can you provide a solution?
