### ISSUE TITLE
Update translations

### ISSUE THREAD

**Issue by j-f1** [excalidraw/excalidraw#795]
I have changed and added several translation keys:

```diff
+labels.layers = "Layers"
+labels.language = "Language"

# open to rewording this or having button text & title be different
-buttons.clearReset = "Clear the canvas & reset background color"
+buttons.clearReset = "Reset the canvas"

# Canvas menu
+buttons.menu = "Menu"
# Finalize multi-point shape
+buttons.done = "Done"
# Shape menu
+buttons.edit = "Edit"
```

I don’t think it’s super urgent to get the translations in, and it’d probably best to wait until mobile support is mostly done, but I wanted to have an issue tracking this.

**Comment by vjeux** [comment]
I was thinking of having a commit hook that regenerates all the translation files by having the same order as the english one and putting null for the keys that are not translated yet. This way it’s going to be easier to find out which translations are missing

**Comment by lipis** [comment]
In theory it should happen automatically now: https://crowdin.com/project/excalidraw

So there is no need to keep track of the translations, it's all visible there :)

#796 <- automatic PR.. it's strange that it's using my username.. I guess they didn't figure out how to do it with bots yet :)

**Comment by j-f1** [comment]
Do we want to add a link to Crowdin somewhere when a non-English language is chosen?

**Comment by lipis** [comment]
In the UI you mean?

**Comment by lipis** [comment]
We definitely have to add it somewhere in the README at least...

**Comment by lipis** [comment]
I think now that we are on Crowding we can close that issue
