### ISSUE TITLE
tax residency certificate for 2024

### ISSUE THREAD

**Issue by dzierzbicki-kamil** [excalidraw/excalidraw#7953]
Good day, I need a tax residency certificate for 2024. Can I request you to send it to me?

**Comment by dwelle** [comment]
Hi, can you send us an email on `support@excalidraw.com`? Thanks!

**Comment by Carlos-Chaves84** [comment]
Hi everyone,
Can I request Github's Tax Residency Certificate for 2024?
Thanks!

**Comment by ktedeev** [comment]
> Hi everyone, Can I request Github's Tax Residency Certificate for 2024? Thanks!

Hi Carlos,
I wanted to check - did Github provide you with its Tax Residency Certificate? 
We want to buy some services from the Github (like Copilot), but we need their Tax Residency Certificate in order to avoid extra local taxes in our country.

**Comment by dwelle** [comment]
@Carlos-Chaves84 @ktedeev btw you may wanna be contacting GitHub for these, as this is an unrelated repository. 😊

**Comment by ktedeev** [comment]
> @Carlos-Chaves84 @ktedeev btw you may wanna be contacting GitHub for these, as this is an unrelated repository. 😊

Oh boy
Sorry for inconveniences, just Googled this thread and thought that this is related to the whole Github. =)
