### ISSUE TITLE
OpenAI Key Not Working

### ISSUE THREAD

**Issue by o6uoq** [excalidraw/excalidraw#7966]
**As an** Excalidraw User
**I want** my OpenAI key to work
**So that** I can continue to use the AI features of Excalidraw

OpenAI does not register that my key is even used, implying there's an issue with Excalidraw using my OpenAPI key to make requests. My OpenAI account has other working API keys, and there's ample credit in the account. I've tried another browser (Safari), same issue.

**Excalidraw AI Settings**
![image](https://github.com/excalidraw/excalidraw/assets/1227896/22d641b0-7229-4448-9c31-09771a405b8b)

**OpenAI Settings**
![image](https://github.com/excalidraw/excalidraw/assets/1227896/1899a44c-23d9-49f8-bead-81df3360e5b4)

**Validity of OpenAI Key**
![image](https://github.com/excalidraw/excalidraw/assets/1227896/9dac2151-fdd1-4ff2-90c5-6a9c09139dd0)

**Comment by simon-johnson-r3** [comment]
I experienced the same. Re-reading the text in the dialog it suggest this is only used for the wireframe to code feature.

**Comment by TylerLMcIntosh** [comment]
Did you ever figure out how to get Excalidraw to correctly call the API? I'm having the same issue

**Comment by o6uoq** [comment]
@TylerLMcIntosh I just went to double check, I can't see the OpenAI API credentials option aka AI Settings anymore?

**Comment by dwelle** [comment]
Forgot to close this as we're no longer exposing the custom token. Initially we had to do it this way because of strict openAI rate limits, and it barred most people from trying it out. It also prevents us from changing models on the fly, or tweaking how it works.

https://github.com/excalidraw/excalidraw/pull/8269

**Comment by o6uoq** [comment]
@dwelle how does one use unlimited tokens for text to AI via Excalidraw?
