### ISSUE TITLE
[Feature Request] Add drawing information to image 

### ISSUE THREAD

**Issue by Nozarno** [excalidraw/excalidraw#7969]
Hello, it's rare to find a tool that works so well, thank you. 
Is it possible to combine the two functions, PNG export and JSON save? To make a single png file that contains both info in the same file, like draw.io / diagrams.net does. 

This makes for a single, editable file.

What's more, if this function is integrated directly into a shortcut like "alt + shift + c". That's really great! 

Thanks for reading my proposal. 

I don't write well in English, so I use DeepL to help me translate. There may be errors in my text

**Comment by Mrazator** [comment]
The functionality you seek is already built-in!

There is no single shortcut for this action, but you can use "cmd + shift + e" to export an image and toggle "Embed scene" as visible in the screenshot, to achieve "combine the two functions, PNG export and JSON save".

<img width="1073" alt="image" src="https://github.com/excalidraw/excalidraw/assets/20387666/c08b7020-1c1e-4e47-9d95-cc326229c2c5">

**Comment by Nozarno** [comment]
Thank
