### ISSUE TITLE
Integrate with Sentry

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#797]
People are starting hitting javascript errors, would be nice to log them on the server so that we can fix them without having people to manually report them

**Comment by dwelle** [comment]
We can't (meaning we must not) log user scene data to sentry, only stack traces, so it might still be valuable to allow people to supply them by creating an issue. Alternatively we can let users send the scene data alongside the sentry error, if they check a box.

Not sure how it'd be implemented.
