### ISSUE TITLE
[Feature] Cut ability

### ISSUE THREAD

**Issue by AdamLinCodes** [excalidraw/excalidraw#7975]
Similar to onenote's cut commands, adding the ability to cut dynamic sections of sketches and move them rather than strict rectangular sections would be very useful.

**Comment by Mrazator** [comment]
Duplicate of #7900

**Comment by AdamLinCodes** [comment]
Apologies for the duplicate issues @Mrazator

**Comment by Mrazator** [comment]
No worries!
