### ISSUE TITLE
Can not show the saved Excalidraw

### ISSUE THREAD

**Issue by Zara-ahmadi** [excalidraw/excalidraw#7978]
I added the Excalidraw inside of my project. I saved the result of the Excalidraw in the database and want to edit it later. 
here is my part of the code that retrieves the saved Excalidraw and shows it in a Modal. 

```
function renderImage(wrapperId, imageData) {
    const wrapper = document.getElementById(wrapperId);
    if (wrapper) {
        const App = () => {
            return React.createElement(
                React.Fragment,
                null,
                React.createElement(
                    "div",
                    {
                        id: 'excalidrawWrapper', 
                        style: { height: "500px" },
                    },
                    React.createElement(ExcalidrawLib.Excalidraw, { initialData: { elements: imageData} })
                ),
            );
        };

        const root = ReactDOM.createRoot(wrapper);
        root.render(React.createElement(App));
    } else {
        console.error('Wrapper element not found:', wrapperId);
    }
}

```
I could not find a way to show it. 

I would appreciate it if someone takes a look.

**Comment by Mrazator** [comment]
I would recommend you to first browse through the excalidraw docs, especially:
1. how to update excalidraw scene - https://docs.excalidraw.com/docs/@excalidraw/excalidraw/api/props/excalidraw-api#updatescene
2. how to listen to excalidraw scene changes - https://docs.excalidraw.com/docs/@excalidraw/excalidraw/api/props/excalidraw-api#onchange

If anything isn't clear, feel free to join us on Discord, where such questions were already discussed multiple times.

In the meantime, we will be soon working on specific guidelines to answer such questions.

**Comment by Zara-ahmadi** [comment]
thank you
