### ISSUE TITLE
obsidian plugin: drawing cursor disapearing when using wacom one table pen

### ISSUE THREAD

**Issue by rodrigor** [excalidraw/excalidraw#7994]
Something weird happens when I use the Obsidian Excalidraw plugin (version 2.1.7). 

When I use any Wacom pen tablet ( like https://www.wacom.com/en-us/products/pen-tablets/one-by-wacom) the Draw cursor doesn't appear. The problem happens only with the draw cursor (as seen in the video below). During the video, I started using the trackpad from my computer, and then the cursor appeared. The cursor appears for every other tool, Rectangle, Diamont, Circle, etc. 
https://github.com/excalidraw/excalidraw/assets/288272/e1c3b83a-7031-4f0b-b170-29e057437c15

Another point: the problem only happens on the Obsidian plugin. The problem doesn't appear on the desktop app or the web interface( excalidraw.com). 

Any insight about what could be happening?

**Comment by dwelle** [comment]
Hi. Usually this is the default behavior of tablets, but it's strange it only does that for the freedraw tool.

But, since it only happens in Obsidian, can you please open an issue in the plugin repository? https://github.com/zsviczian/obsidian-excalidraw-plugin/issues 🙏
