### ISSUE TITLE
Change font

### ISSUE THREAD

**Issue by sonigeez** [excalidraw/excalidraw#7998]
The current font is not readable at all, i suggest we should use some different font

**Comment by dwelle** [comment]
Improvements coming!

**Comment by jiweiyuan** [comment]
> Improvements coming!

@dwelle I'm very excited about this feature. Could you share with me if it supports CJK handwritten fonts?

**Comment by djGrill** [comment]
I landed on this issue because I thought there was only 1 font available on Excalidraw.

However, soon after I realized there are 3 fonts available to choose from (`Font family` setting).

The fonts `Normal` and `Code` look very nice and readable:
<img width="430" alt="Screenshot 2024-06-06 at 10 51 06" src="https://github.com/excalidraw/excalidraw/assets/296969/7bb837b4-b7e2-4a89-877d-f37038a10558">

**Comment by Mrazator** [comment]
> It would be great to have support for Latin letters like `ə` `ö` `ü` `ı` `ğ` `ş` `ç`

@kerimovok the built-in fonts already support extended latin characters, see https://excalidraw.com/#json=1-s5Ar8WKUnTp_kr6b9Vb,-4yahR1qrw5ssgs_6z3Y6w; the only isssue I see is missing `ə`glyph in the hand-drawn font. Please create a separate issue if you would like to add it.

> Could you share with me if it supports CJK handwritten fonts?

@jiweiyuan eventually it's on our radar to also support CJK fonts (or any custom font), but we need to go step by step to not degrade the quality (layout shifts, wrapping stability, etc.). In the first iteration we aim on shipping more alphabetic-based fonts (latin, cyrilic and possibly vietnamese with their extended versions) to choose from.

**Comment by Mrazator** [comment]
We've released a more readable version of Virgil named Excalifont!

https://x.com/excalidraw/status/1846205807068627155

Regarding CJK, the release will be soonish (https://github.com/excalidraw/excalidraw/pull/8530)!

Feel free to give us early feedback, preview is available here:
https://excalidraw-git-mrazator-first-class-support-chinese-excalidraw.vercel.app/
