### ISSUE TITLE
Huge Diagram Rendering issues

### ISSUE THREAD

**Issue by bradwood** [excalidraw/excalidraw#8000]
I am a paying subscriber of Excalidraw+ online. I have one very important, but also extremely HUGE diagram in the app.

This diagram is starting to get slower and slower to use and update, and the rendering of various objects on the canvas occasionally breaks, or fails to finish.

What options do I have to make it work properly again. I can live with the slowness, but not the poor rendering.

Is this a memory problem? And can I do anything to make the browser / tab get more resources?

## Browser/OS:
```
Brave	1.65.123 Chromium: 124.0.6367.91 (Official Build) (64-bit) 
Revision	dd88871b12997b018e3acb2f589713a3ea10338b
OS	Linux
JavaScript	V8 12.4.254.14
User agent	Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36
```

**Comment by dwelle** [comment]
Hi @bradwood, could you write us on `support@excalidraw.com` so we can investigate more closely?

**Comment by bradwood** [comment]
hi @dwelle I did email earlier today but no answer thus far :disappointed:

**Comment by dwelle** [comment]
Hello, we did answer with request for more information. Can you double check your inbox? You can also message us on Discord if need be.

**Comment by bradwood** [comment]
Hi @dwelle I found your email and replied to it, twice, but got nothing back.  Did you receive it?

**Comment by dwelle** [comment]
Hey. Sorry, once a ticket is open for multiple days there's a high chance it'll get deprioritized due to other things. Checking now!
