### ISSUE TITLE
Bug in the UI with Layers Buttons

### ISSUE THREAD

**Issue by bxh-io** [excalidraw/excalidraw#8001]
Just saw a bug with the icons for adjusting the layers in the UI. See pic: 

![Screenshot 2024-05-09 at 09 42 13@2x](https://github.com/excalidraw/excalidraw/assets/939710/198cea74-0a68-4399-b08b-bc2780df86b6)

Thanks so much for everything!

**Comment by dwelle** [comment]
(I love you safari.)
