### ISSUE TITLE
Excalidraw does not work with the Dark Reader plugin for dark mode, can it work with the Dark Reader plugin for dark mode?

### ISSUE THREAD

**Issue by Wang-Mer** [excalidraw/excalidraw#8004]
![image](https://github.com/excalidraw/excalidraw/assets/56023866/1d5e280d-3466-4b81-a333-5726f5e35b67)

**Comment by dwelle** [comment]
Excalidraw has its own dark mode so it may be colliding. Either way, I'd suggest putting excalidraw.com into exclusion list and use our own instead. We support `system` theme as well (from top left menu).

What Dark Reader plugin are you using (what browser/ browser extension) and how are you toggling it the dark mode (using a keyboard shortcut)?

**Comment by Wang-Mer** [comment]
chrome used

**Comment by Wang-Mer** [comment]
The Chrome browser used

**Comment by Wang-Mer** [comment]
![image](https://github.com/excalidraw/excalidraw/assets/56023866/a7d995f3-918e-43a9-ae1c-bcd5b46c5997)
I've figured out how to adjust it, thank you for your reply.
