### ISSUE TITLE
Feature request Excalidraw - zoom on image

### ISSUE THREAD

**Issue by GadidGC** [excalidraw/excalidraw#8005]
I want to be able to click on the image and have it pop up for better viewing.

<img width="1910" alt="image" src="https://github.com/excalidraw/excalidraw/assets/42261651/30cf95a5-e06b-440d-be93-07b1d4c041a1">

**Comment by dwelle** [comment]
You can select an image and press <kbd>Shift-3</kbd> to zoom to it.
