### ISSUE TITLE
Font loaded multiple times

### ISSUE THREAD

**Issue by hausen1012** [excalidraw/excalidraw#8006]
I found through the browser developer tool that the same font was loaded three times, and when I customized a larger font, the first loading was very slow.

![image](https://github.com/excalidraw/excalidraw/assets/50026605/1dbebd0d-7dfc-4b9d-8368-831e2ab8363e)

![image](https://github.com/excalidraw/excalidraw/assets/50026605/2bc5c642-5073-4a99-aa76-4dd6f45fdb9b)

**Comment by Mrazator** [comment]
> I found through the browser developer tool that the same font was loaded three times

We are currently working on optimising this! 

> when I customized a larger font, the first loading was very slow.

It seems your customisation made the font huge 61 kB -> 2.2 MB

**Comment by hausen1012** [comment]
Thank you for your reply.
Yes, because I am using handwritten Chinese font, it is inevitably very large. If it can be optimized to load only once, I think this is acceptable.
Of course, if the official can provide Chinese fonts, this is the best choice! I have to use a custom font now because using the default font makes the image look very incongruous.
Thank you again

**Comment by Mrazator** [comment]
Closing as fonts are now loaded just once thanks to #8012.

Currently in progress for adding built-in Chinese fonts.
