### ISSUE TITLE
Pinch based zoom should be centered at the pinch point, not the center of the canvas

### ISSUE THREAD

**Issue by pshihn** [excalidraw/excalidraw#801]
If I have a circle at the top right, it's tempting to pinch-zoom on the circle but it goes off screen. 
I suggest we keep the zoom related scaling centered at the canvas center, but then *scroll/translate* the canvas to the pinch start point.

**Comment by j-f1** [comment]
Thanks! I thought the pinch-zoom implementation was too simple! Do you know of any guides to implementing this?

**Comment by j-f1** [comment]
<details><summary>Here’s where the code is:</summary>

macOS Safari trackpad pinch:
https://github.com/excalidraw/excalidraw/blob/668f8ec4a6c875e36f2b46934e5bba35da05fc85/src/components/App.tsx#L650-L664

Chrome/FF trackpad pinch, Cmd/Ctrl+scroll:
https://github.com/excalidraw/excalidraw/blob/668f8ec4a6c875e36f2b46934e5bba35da05fc85/src/components/App.tsx#L2040-L2063

Touch pinch: (this might already be OK) 
https://github.com/excalidraw/excalidraw/blob/668f8ec4a6c875e36f2b46934e5bba35da05fc85/src/components/App.tsx#L971-L983

**Comment by j-f1** [comment]
I’m going to merge this with #940 too.
