### ISSUE TITLE
Text tool is gone mad and does not work at all.

### ISSUE THREAD

**Issue by nc-rasel** [excalidraw/excalidraw#802]
@vjeux sorry to tag you here but bro did you check the app? 
it was fine till last night but now broken. 
Select the text tool and try to write you'll see the problem.  :(

**Comment by nc-rasel** [comment]
I tried to reproduce the BUG at `local` to check if its working or not...
I found and paste it here for your reference if it helps you. 

<img width="1130" alt="image" src="https://user-images.githubusercontent.com/1910377/75085185-bcb5d800-5550-11ea-9726-3769626d85dc.png">

<img width="1003" alt="image" src="https://user-images.githubusercontent.com/1910377/75085219-1fa76f00-5551-11ea-97bf-f287ac1013f2.png">

**Comment by vjeux** [comment]
I’m not on a computer so can’t check but this is working fine on mobile.

The error is very weird, it seems to indicate that `contentEditable = “plaintext-only”` is causing the issue.

What browser are you using?

**Comment by j-f1** [comment]
@nc-rasel Does https://deploy-preview-803--nervous-ptolemy-2a7f30.netlify.com work OK for you?

**Comment by nc-rasel** [comment]
@j-f1 and @vjeux 
Yes, its working. Very much appreciated your hard work. 

I am using `Firefox Developer Edition 74.0b6 (64-bit)`
also checked the same in `Safari Version 12.1.1 (14607.2.6.1.1)`
