### ISSUE TITLE
Exit Zen Mode button triggers form submission

### ISSUE THREAD

**Issue by nishanthkarthik** [excalidraw/excalidraw#8029]
Button type is not set to `type="button"`

https://github.com/excalidraw/excalidraw/blob/7d8b7fc14dd8b76c391c95d1e92f0c4236c55576/packages/excalidraw/components/Actions.tsx#L470

---

Found another instance that triggers submission

https://github.com/excalidraw/excalidraw/blob/7d8b7fc14dd8b76c391c95d1e92f0c4236c55576/packages/excalidraw/components/MobileMenu.tsx#L197

**Comment by nishanthkarthik** [comment]
Made #8030

**Comment by dwelle** [comment]
Thanks. Out of interest, how does that manifest?

**Comment by nishanthkarthik** [comment]
In my prototype, the excalidraw widget ended up being embedded inside a html form. Clicking _Exit Zen Mode_ took me to a different page.

**Comment by dwelle** [comment]
Interesting.
