### ISSUE TITLE
Want to clone the next.js version of excalidraw

### ISSUE THREAD

**Issue by master-senses** [excalidraw/excalidraw#8032]
I've been trying to access the version of excalidraw hosted on [vercel](https://vercel.com/sso/access/request?next=%2Fsso-api%3Furl%3Dhttps%253A%252F%252Fexcalidraw-package-example-with-nextjs-gh6smrdnq-excalidraw.vercel.app%252F%26nonce%3Df86b809cdf7add4e6ce762f0bcfece9184802b6f8185075656bfa8cc514635eb&url=excalidraw-package-example-with-nextjs-gh6smrdnq-excalidraw.vercel.app), but I'm unable to do so. How do i use this as a next.js app?

Also, where do I find the code for the OpenAI Integration for the wireframe to code feature?

**Comment by dwelle** [comment]
> I've been trying to access the version of excalidraw hosted on [vercel](https://vercel.com/sso/access/request?next=%2Fsso-api%3Furl%3Dhttps%253A%252F%252Fexcalidraw-package-example-with-nextjs-gh6smrdnq-excalidraw.vercel.app%252F%26nonce%3Df86b809cdf7add4e6ce762f0bcfece9184802b6f8185075656bfa8cc514635eb&url=excalidraw-package-example-with-nextjs-gh6smrdnq-excalidraw.vercel.app), but I'm unable to do so. How do i use this as a next.js app?

Unclear what do you mean by accessing that version, can you elaborate?

As for next.js, we have some [examples](https://github.com/excalidraw/excalidraw/tree/master/examples/excalidraw/with-nextjs), though there are some rough edges around rendering excalidraw inside a Next.js. If you face any issues, you can ask on our [discord chat](http://discord.gg/UexuTaE) or open [a discussion](https://github.com/excalidraw/excalidraw/discussions).

> Also, where do I find the code for the OpenAI Integration for the wireframe to code feature?

Not open source at the moment.

**Comment by master-senses** [comment]
Thank you! Do you have a timeline for when the open ai integration will be open source?

**Comment by dwelle** [comment]
the ai-related code lives in our private monorepo for code-sharing, CICD and other purposes, so it's unlikely to be open sourced on its own. We may expose a simple repo or a component for this in the future, similar to what we do with the collaboration server https://github.com/excalidraw/excalidraw-room, but there's no ETA on this.
