### ISSUE TITLE
New language request

### ISSUE THREAD

**Issue by 6dayspizza** [excalidraw/excalidraw#8047]
I would really like to do a full translation into Swiss German. You are well loved here, and I think everybody (of us Swiss, I mean...) would love this. Any chance this would be acceptable?

**Comment by aashkann** [comment]
@6dayspizza I believe you can go to [contribution page](https://crowdin.com/project/excalidraw) which directs you to [Crowdin](https://crowdin.com/project/excalidraw) and help translating.

**Comment by ad1992** [comment]
@6dayspizza I have added Swiss German (I hope the lang code is correct, let me know if it isn't) to Crowdin so you can start adding the translations here  👇🏻 https://crowdin.com/editor/excalidraw/10/en-dech?view=comfortable&filter=basic&value=3 :)

**Comment by 6dayspizza** [comment]
@ad1992 Awesome, thank you!
