### ISSUE TITLE
People are abusing this stuff to try and defame people

### ISSUE THREAD

**Issue by bloomsirenix** [excalidraw/excalidraw#8053]
not sending links but a report button would be handy

**Comment by dwelle** [comment]
Hey! Can you send us an email on `support@excalidraw.com` with more context so we can assist? Thanks! 🙏

**Comment by bloomsirenix** [comment]
gladly do the tool seems cool tho

**Comment by dwelle** [comment]
closing in favor of https://github.com/excalidraw/excalidraw/issues/8055
