### ISSUE TITLE
Please Whitelist Reddit

### ISSUE THREAD

**Issue by jiweiyuan** [excalidraw/excalidraw#8063]
@dwelle Hi, Currently, Reddit links are not allowed to be embedded. Could you please whitelist Reddit links to enable successful embedding?

The Reddit documentation may be helpful; you can find it here: [Reddit Embed Documentation](https://publish.reddit.com/assets/Reddit_Embed_Documentation.pdf).

If no one is available to address this issue at the moment, I would be happy to create a pull request to resolve it.

Many thanks

**Comment by subhadeep-sengupta** [comment]
Hi @dwelle @jiweiyuan , if no one is working on this issue then I can pick it and solve it.

**Comment by dwelle** [comment]
Yeah, feel free to open a PR for reddit!

Look into `embeddable.ts`, add it to the necessary allowlists. If reddit needs a `srcdoc` or otherwise needs some custom renderer, then write a parser for it so that we don't paste whatever the user pastes verbatim (e.g. check twitter embed).

**Comment by ad1992** [comment]
closed via #8099
