### ISSUE TITLE
Errors adding images to Excalidraw

### ISSUE THREAD

**Issue by Dracopi** [excalidraw/excalidraw#8066]
![image](https://github.com/excalidraw/excalidraw/assets/106590179/35224f54-0037-44a0-b758-725f05be1486)

This error appears out of nowhere when I try to add an image from my vaul, from the browser or from the files on my pc. By following the recommendations it is solved only for the first image I paste in the file, the rest of the images have the same problem.

**Comment by dwelle** [comment]
Hey. Best ask on https://github.com/zsviczian/obsidian-excalidraw-plugin/issues!
