### ISSUE TITLE
Cannot copy to clipboard

### ISSUE THREAD

**Issue by myspace7164** [excalidraw/excalidraw#8092]
I'm not sure if this belongs here but let's see.

I'm using the excalidraw plugin in standard notes. When i try to export the image, or copy to clipboard as png, i get the following error: "Error couldn't copy to clipboard"

I tried both, the flatpak and appimage version of standard notes. Also when using the webapp of standard notes, it works.

**Comment by dwelle** [comment]
Hi. Never heard about Standard Notes, but their desktop apps likely don't support clipboard API we're using to copy to clipboard. You'd have to raise issue with them as we don't have any control over this.
