### ISSUE TITLE
Browse libraries can't load on my devserver?

### ISSUE THREAD

**Issue by Chryseis** [excalidraw/excalidraw#8095]
![image](https://github.com/excalidraw/excalidraw/assets/13757352/ca94a9e3-f92b-476b-aa3f-e87a82468ead)
![image](https://github.com/excalidraw/excalidraw/assets/13757352/75aed836-859b-4b6c-8ef6-52970469d3b0)

**Comment by dwelle** [comment]
We allow only first-party and affiliated apps to be redirected to when installing libraries. We'll also be redesigning the installation flow, soon.

If you want to install excalidraw.com libraries from your custom app, the best bet right now would be to install from the github directly.
