### ISSUE TITLE
allow `props.initialData` to be function

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#8107]
Right now, [`initialData`](https://docs.excalidraw.com/docs/@excalidraw/excalidraw/api/props/initialdata) can be either a `ExcalidrawInitialDataState` or `Promise<ExcalidrawInitialDataState>`. This makes async initialization hard as you need to implement your own [`ResolvablePromise`](https://github.com/excalidraw/excalidraw/blob/master/packages/excalidraw/utils.ts#L540-L556) abstraction.

We should also allow `initialData` to be an initializer function (`() => MaybePromise<ExcalidrawInitialDataState | null>`) similar to `useState(function)`. It will be called only once so host apps don't have to worry about multiple invocations.

**Comment by es-romo** [comment]
Happy to take this one. I'm testing a solution now.

**Comment by dwelle** [comment]
Thanks @es-romo, assigned!

**Comment by kmr-ankitt** [comment]
Is this issue resolved? If not can i have this?

**Comment by es-romo** [comment]
Hey just bumping this @dwelle. The PR is ready for review

**Comment by dwelle** [comment]
added a few notes to the PR!
