### ISSUE TITLE
Not able to see the number of items selected

### ISSUE THREAD

**Issue by LemonadeCodeGirl** [excalidraw/excalidraw#8126]
I would find it useful for this project to have a please fancy the number of items I have selected. I am currently working on this issue, but I just wanted to put this out there.

**Comment by dwelle** [comment]
Hi. You can see the elements from the Stats (<kbd>opt/alt</kbd>+<kbd>/</kbd>).

![image](https://github.com/excalidraw/excalidraw/assets/5153846/8fdbb551-21d2-469e-8b4e-01fb1cbc6135)
