### ISSUE TITLE
Complex Drawing Poor Performance

### ISSUE THREAD

**Issue by jorgedanisc** [excalidraw/excalidraw#8136]
Been using this amazing app for a while and when started experimenting drawing 2D CAD Sketches of certain Architectures here on Excalidraw end up faced with a problem in terms of performance, which led me to explore a little deeper.

Now I understand the whole concept of this project, I totally get that the most important thing is maintaining the simplicity (therefore most users may not need this much complexity). However my case is the following: In a good enough time horizon, users may have big canvasses (due to only using one for everything, at least thats what I see happening/experience) so whether they want it or not this complexity may collapse over time.

## Benchmarks (on M1 Macbook Air 16GB)

Overall Performance gets really bad when a lot of elements on the viewport, even unusable at a certain point (The screen goes blinking)

### On Chrome
- From 4k-8k Object performs quite well, when it gets to 8k starts to struggle
- From 10-14k Objects noticed the FPS dropped significantly (~30FPS)
![Screenshot 2024-06-14 at 01 43 43](https://github.com/excalidraw/excalidraw/assets/103663493/f6e587e0-e61a-4f7c-b429-55fd1a39e21e)

### On Firefox
- From 14k-24k Objects the canvas gets unusable (The screen goes blinking) and it is almost impossible to move items
![Screenshot 2024-06-14 at 01 44 06](https://github.com/excalidraw/excalidraw/assets/103663493/93037907-40bf-4110-a94d-06ede54c03bc)

- Also one thing I noticed on both of these scenarios was that **Mutating and Managing Objects** gets really slow (~10FPS)
> Since the testing files were too big I left them on a **[repo here](https://github.com/jorgedanisc/excalidraw-performance-testing)**

# Possible Solutions

## Rendering

- Leveraging WebGL directly or through a library like **[Pixi.js](https://github.com/pixijs/pixijs)** could boost rendering performance, as I tested on this **[example](https://github.com/AZhur771/excalidraw-webgl)** when someone tried to do it.
- From my research there as been a lot of effort on the rendering side from the team, here is what I noted:
    - Excalidraw already uses 2 Canvas: One for interactability and another as an Background Canvas as of my understanding. This seems to help out a lot in performance, however I do not understand how **mutating objects with a complex canvas** is a bit slow considering this.
    - From what I can see **`culling`**  seems to be already implemented

> Just as reference, found this [interesting showcase](https://antv.vision/infinite-canvas-tutorial/guide/lesson-008) on optimizing `<canvas/>` performance on the web
> 

I believe this problem is not just tied to rendering, therefore I laid out other possible solutions bellow.

## Saving and Storage

- Using Binary instead of JSON for big files:  **[FlatBuffers](https://github.com/google/flatbuffers)** due to the file being way too big with many objects, this way we can use bulk saving still (overwriting the canvas file on local storage), however now we could do it on the IndexedDB (~500MB max) by saving there the FlatBuffer Binary. This wouldn’t change much infrastructure because the AppState/Data Structures of the canvas remain the same, the thing changing would be the export/save and open mechanisms.
    - This would also significantly reduce the `.excalidraw` file size, and if necessary, FlatBuffers support JSON parsing for readability or debugging proposes.
    - FlatBuffers are extremely fast and I believe they could be fitting in this Live Collaboration, fast Canvas Editing scenario.

## Offloading to WebWorkers (If not implemented already)

- Leveraging Parallel Processing with Web Workers to manage intensive computations can free up the main thread, allowing for smoother interaction and rendering. Tasks like real-time rendering calculations or batch processing updates could benefit significantly from this approach.

### Adapting Data Structures (would perhaps be too much overhead)

But just to leave it here if not implemented already: 

- Combine already used on `Scene` structs like `Map` and `WeakMap` with data structures such as spatial indexing (e.g., quadtrees) to manage object interactions and visibility efficiently.
- Employ object pooling to reuse object instances and minimize garbage collection overhead.

Hope the team takes my possible solutions with a grain of salt, I have not worked on the project neither have knowledge of every single details of the implementation, though I research the codebase and the app (testing) and I am just trying to help out. Could be totally wrong here, but just wanted to raise this issue without being “empty handed”.

**Comment by OnSketch-Ai** [comment]
How you create/import such a comlicated Architecture files in Excalidraw?
