### ISSUE TITLE
disable/use default values for paste styles if no styles have been copied 

### ISSUE THREAD

**Issue by lissitz** [excalidraw/excalidraw#814]
Paste styles produces a weird state if no styles have been copied yet.

- Create a new element.
- Select paste styles.
- If it is a text elment or a multielement the app crashes. Otherwise, it pastes empty styles. Trying to change the background color of the element freezes the tab.

**Comment by Fausto95** [comment]
Thanks for filling the issue! 
I’ll come up with a fix
