### ISSUE TITLE
Missing copy paste

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#816]
It turns out I’m using it a lot and not having it is annoying :(

**Comment by lipis** [comment]
Maybe instead of copy paste.. we should introduce a `duplicate` action as other apps have.

**Comment by dwelle** [comment]
@lipis makes sense. Having two buttons where you basically click on one and immediately after click on the other would be crazy (unless the paste button would make your next tap paste on that place, but that's unnecessarily complicating the workflow for no real benefit).

**Comment by j-f1** [comment]
https://fontawesome.com/icons/clone?style=regular

**Comment by vjeux** [comment]
We now have duplicate button which solves a similar purpose
