### ISSUE TITLE
is this best way to export as PDF ? 

### ISSUE THREAD

**Issue by JamieAUS** [excalidraw/excalidraw#8171]
1. Export as PDF
2. Click "Export Image."
3. SVG to File.
4. Inkscape (download third-party app).
5. Open the SVG file.
6. Export as a PDF file.

- (Note: Inkscape does not support the Excalidraw font, so you should download and update the Excalidraw font.)

I tried to find an easy way to export as a PDF file. As someone without a computer background, it was quite tough.

**Comment by ejazkhan10** [comment]
There isn't any support for downloading pdf yet.
But you can use pdfkit + svg to pdfkit libraries to convert the svgs that you generate from excalidraw elements into pdf.

**Comment by kiplingw** [comment]
I agree, it's not straightforward to export to PDF. If a direct export capability was integrated, perhaps with libpoppler, then Excalidraw font could be embedded in the PDF.

**Comment by Mrazator** [comment]
We are embedding our fonts inside SVGs (https://github.com/excalidraw/excalidraw/issues/8300), sadly Inkscape does not seem to support `@font-face` in SVGs (in our case base64 woff2 embedded as data URL). In theory, opening the SVG inside a browser (i.e. chrome), triggering print dialogue with `ctrl/cmd + P` and selecting "Save as PDF" could achieve similar, but that's also by no means particularly straightforward.

---

Anyway, we have an easy PDF export available in our https://plus.excalidraw.com/ version, with support for all our fonts alongside multiple other export options!

<img width="337" alt="Screenshot 2024-08-09 at 10 18 47" src="https://github.com/user-attachments/assets/12beffcf-6728-4186-b9b4-af775bf9390a">

**Comment by kiplingw** [comment]
Thanks @Mrazator. For those who are interested in following the Inkscape upstream issue he mentioned, you can do so [here](https://gitlab.com/inkscape/inbox/-/issues/301).

**Comment by sunsibar** [comment]
@Mrazator , does excalidraw plus support pdf export? I subscribed to plus (on the 14 days trial version now) to get our excalidraw figure exported to pdf, but there's no change in options for export. Has that feature been removed?
