### ISSUE TITLE
Support Custom Elements

### ISSUE THREAD

**Issue by nickinkaty** [excalidraw/excalidraw#8184]
It looks like Excalidraw used to support custom elements. Does Excalidraw still support custom elements?

**Comment by tonhao-dev** [comment]
Yes, you can use `Library` functionally, you can find it in the top right corner
![image](https://github.com/excalidraw/excalidraw/assets/35160032/f2f79c22-6712-40b0-a51f-62dee48a6990)

You can create your self components and save in your library or find components in the community

**Comment by dwelle** [comment]
as per discord, I assume this is a question for the editor package. Currently not possible. Tracking https://github.com/excalidraw/excalidraw/issues/4957. Unclear when we add it, but will certainly happen.
