### ISSUE TITLE
Missing lock

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#819]
That feature is very useful when “drawing” stuff with many lines. I’d love to get it on mobile as well :)

**Comment by yongdamsh** [comment]
I am trying to add a lock button to the mobile version, but with the existing layout, there is no room to place it in a small viewport (e.g. iPhone SE). So how about adding it to the right edge as shown in the screenshot, but is there a better way?

| iPhone 5/SE | iPhone 6/7/8 |
| --- | --- |
| <img width="323" alt="스크린샷 2020-03-22 오후 1 07 05" src="https://user-images.githubusercontent.com/4126644/77242183-058baa00-6c3f-11ea-8277-48b597e8b078.png"> | <img width="414" alt="스크린샷 2020-03-22 오후 1 07 58" src="https://user-images.githubusercontent.com/4126644/77242186-091f3100-6c3f-11ea-9b0a-bd1f088ba230.png"> |

**Comment by vjeux** [comment]
Your screenshot looks good to me :)

**Comment by j-f1** [comment]
How about putting it there but switching back to its desktop position once the screen is wide enough?

**Comment by yongdamsh** [comment]
@j-f1 That would be great. Thanks for the suggestion. Then I'll work like that.
