### ISSUE TITLE
why create a new version of text element onFontsLoaded?

### ISSUE THREAD

**Issue by zsviczian** [excalidraw/excalidraw#8190]
Why are we bumping the version number of text elements on the onFontsLoaded event? Seems to me like unnecessary inflation of the scene version.

```ts
  public onFontsLoaded = (fontFaces: readonly FontFace[]) => {
    if (
      // bail if all fonts with have been processed. We're checking just a
      // subset of the font properties (though it should be enough), so it
      // can technically bail on a false positive.
      fontFaces.every((fontFace) => {
        const sig = `${fontFace.family}-${fontFace.style}-${fontFace.weight}`;
        if (Fonts.loadedFontFaces.has(sig)) {
          return true;
        }
        Fonts.loadedFontFaces.add(sig);
        return false;
      })
    ) {
      return false;
    }

    let didUpdate = false;

    this.scene.mapElements((element) => {
      if (isTextElement(element)) {
        didUpdate = true;
        ShapeCache.delete(element);
        return newElementWith(element, {}, true);
      }
      return element;
    });

    if (didUpdate) {
      this.scene.triggerUpdate();
    }
  };
  ```

**Comment by dwelle** [comment]
I agree that this isn't good and we need to get rid of it, but if I recall, there was some race condition on init (may be reproducible in StrictMode only, but possible in regular conditions as well) where `onFontsLoaded` was executed on one set of ExcalidrawElements which busted the element canvas cache using those, but the init render happened with another set of elements which was already cached.

Can't repro now. Let's fix that in a different way if it happens again. https://github.com/excalidraw/excalidraw/pull/8191
