### ISSUE TITLE
Missing home screen icon

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#820]
I added the website to my home screen on iOS but it took a crappy screenshot of the app instead of using an icon.

![F272D3A0-76DB-47C3-84B6-8321C9C922D7](https://user-images.githubusercontent.com/197597/75125786-bf592000-566b-11ea-9221-03376d5b846e.jpeg)

**Comment by j-f1** [comment]
I know this is `apple-touch-icon` for iOS but I don’t know the equivalent for Android. I think we have to make a manifest file?

**Comment by lipis** [comment]
Yes, manifest file is the way..

**Comment by Fausto95** [comment]
Working on this via: https://github.com/excalidraw/excalidraw/pull/842
