### ISSUE TITLE
[Bug] Browser language is Chinese, but the default display language is English

### ISSUE THREAD

**Issue by DDDDD12138** [excalidraw/excalidraw#8202]
### Here are my language settings:

![image](https://github.com/excalidraw/excalidraw/assets/43703884/6fcf510b-dee5-41bb-a500-8d376dce200c)

### However, the default displayed language is English

![Screenshot 2024-07-04 003046](https://github.com/excalidraw/excalidraw/assets/43703884/bee17406-bc7e-498b-a1b1-15987861c035)

### Expectation

I hope it can automatically display in Chinese, rather than being set manually.

**Comment by dwelle** [comment]
Hi. We are using language detection, but it appears that when you set your preferred language to generic "chinese", we don't match it to any existing translation.

Fixed in https://github.com/excalidraw/excalidraw/pull/8205
