### ISSUE TITLE
Wrong resize points for multi-line shape

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#821]
I drew an ellipse with multi point lines.

I would expect to be able to resize it horizontally and vertically but I only can vertically.

The resize handles should be at the corner, not center.

![C79DE830-250A-44CD-840F-BEB27C4DF453](https://user-images.githubusercontent.com/197597/75125991-c0d71800-566c-11ea-8f20-0e98613d0423.png)

**Comment by j-f1** [comment]
Can you share a repro link?

**Comment by vjeux** [comment]
The resize handles not working issue has been fixed. However on mobile I just can’t resize using the middle ones. The corners work fine.


https://excalidraw.com/#json=6006050574565376,mvGX2Gd-D7FRidmBID8MOg

**Comment by vjeux** [comment]
This is fixed.
