### ISSUE TITLE
Add to homescreen isn’t working offline

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#822]
First time I tried to put something on the homescreen. It felt fine as an app but unfortunately got the sad news when tried to load it on a plane.

I have no idea how to make it offline available but I figure there must be a settings somewhere.

![E2B8CD6E-B495-4293-A56F-AD4034217688](https://user-images.githubusercontent.com/197597/75130015-e0783b80-5680-11ea-80fa-6f52118f0c82.png)

**Comment by j-f1** [comment]
I think we just need to make a service worker. Or a native app. Or both!

**Comment by kbariotis** [comment]
Working on https://github.com/excalidraw/excalidraw/pull/1286, should be merged soon.
