### ISSUE TITLE
Have a different opacity for border and background

### ISSUE THREAD

**Issue by Alex88360** [excalidraw/excalidraw#8237]
Right know the opacity slider is defined for both the background and the borders.
It would be more convenient to have one slider for the background and one for borders.

**Comment by dwelle** [comment]
Hi. I don't think this would add enough value to justify complicating the UI in this way. What you can do currently is add opacity to the color itself: append two HEX chars `##` after the HEX color to add opacity (it's in hexadecimal, so 50% opacity would be 7F, e.g. for red color it's `FF00007F`). Or use `rgba(255,0,0,0.5)` syntax.
