### ISSUE TITLE
Shift between two object on two different screen size

### ISSUE THREAD

**Issue by CAnto64** [excalidraw/excalidraw#8248]
Hello 
I have a the same excalidraw canva on two different devices. Those two have different screen size and even if the all the elements drawn have the same coords, they aren't on the same place on the canva which is very annoying. 
Any way to fix that ? Any help is appreciated !!

**Comment by dwelle** [comment]
Hi, can you give more context? Is this excalidraw.com or Excalidraw+? Can you share the drawing?

**Comment by CAnto64** [comment]
I did some kind of collaboration tool with a socket.io server 
When something is drawn, I send a message to the server to add programmatically the object. 
So it's the same object with the same coords etc.
Here is the example : 
![image](https://github.com/user-attachments/assets/ce700a72-9e95-43b9-a1f2-a4c366a3003f)
![image](https://github.com/user-attachments/assets/5285c35f-c754-436e-b76e-72237073c607)
It's the same object with the same coords but on two different screens with two different sizes and I have this shift. ( which sometimes is bigger )
I thought it could come from that part of my code but after changing it, it did nothing
![image](https://github.com/user-attachments/assets/5b75be1a-6b1a-4db2-ad44-518d830999d5)

**Comment by dwelle** [comment]
Could you make a small repro case on CodeSandbox please?

**Comment by CAnto64** [comment]
Hey sorry 
Had some issues, finally find out that it came from the device itself. Don't really know why but it handles bad the coordinates, trying to figure why but that's ok with others devices 
Ty !!
