### ISSUE TITLE
Text color is not changing

### ISSUE THREAD

**Issue by Glitch-guy0** [excalidraw/excalidraw#8249]
while writing text by default it uses black color when i highlight the text and try to change the color it doesn't change,

https://github.com/user-attachments/assets/e11cb0f8-3b6b-4ec5-9105-b91532b13f12

**Comment by Glitch-guy0** [comment]
It works when you select the text-box as a whole, but like when you are still writing midway highlight and then change it won't work.

https://github.com/user-attachments/assets/0ea1d9ea-5528-4b17-a528-e6b15961289c

once i got to know about this not a big deal, because you can't highlight a word and change the color, but applies to the whole block.

**Comment by Mrazator** [comment]
Hi, there has been some regression lately, which should be fixed with https://github.com/excalidraw/excalidraw/pull/8012 soon.

For a workaround, just select an element and change a colour (single click - no double-click nor enter, which enters the text editing mode).
