### ISSUE TITLE
Can't change text to white

### ISSUE THREAD

**Issue by Daemon-Fadi** [excalidraw/excalidraw#8255]
Video: https://www.loom.com/share/9b21c56bf0d44467abc0666803a0adef?sid=d79f6d43-5c88-402b-bd59-b0a5d04bb2c9

**Description**
Expected Behavior: Can select text and then change color to white
Bug: Can choose white, dialog disappears but white color is not applied. Happens with other colors
Reproducible: Yes (Tried 8 times).

**Comment by Mrazator** [comment]
Hi, there has been some regression lately, which should be fixed with #8012 soon.

For a workaround, just select an element and change a colour (single click - no double-click nor enter, which enters the text editing mode).

**Comment by Mrazator** [comment]
Duplicate of #8249.
