### ISSUE TITLE
Arrows with text have a severe detrimental impact on freedraw performance

### ISSUE THREAD

**Issue by zsviczian** [excalidraw/excalidraw#8257]
Originally raised for the Obsidian plugin ([#1893](https://github.com/zsviczian/obsidian-excalidraw-plugin/issues/1893)), but the same is present on Excalidraw.com

https://github.com/user-attachments/assets/d087be9c-bd1e-4c1a-8536-7ac642ccc1b6

**Comment by zsviczian** [comment]
notice the CPU load for the chrome process

https://github.com/user-attachments/assets/0414a290-c36d-4f4f-b1ff-abe0854d6bd4

**Comment by gauravgautamapptile** [comment]
hey @zsviczian I am not a contributor. But I was curious so I recorded a performance profile in chrome.

<img width="1456" alt="Screenshot 2024-07-22 at 8 40 27 AM" src="https://github.com/user-attachments/assets/6e3ba318-a0d8-4efc-808f-cac1f3c55ef0">

I see that while dragging and moving on each frame there is some garbage collection going on. This is probably what eventually overwhelms the browser as the number of arrows goes up. Im not saying Ill take a deeper look but it does seem like there is something there that can be optimized for better performance.

This zoomed in view shows there are multiple GC's lasting more than a few ms on a macbook pro m1. This is one frame, and this is happening on every frame. This would also explain the CPU spike you are seeing I think. But ill have to look deeper to be sure at all (and again Im not a contributor, this is just a guess because Im curious).

<img width="1075" alt="Screenshot 2024-07-22 at 8 43 53 AM" src="https://github.com/user-attachments/assets/d66e6d12-e441-4c38-95fc-890c50b8fbcf">

**Comment by ad1992** [comment]
Thanks for reporting this @zsviczian! I will look into this.

I am not seeing this issue in text containers so probably this could be related to the way the labels are being rendered (updating coords of text along with container element vs calculating coords during render) as that's the major diff between labeled arrows and text containers implementation.

**Comment by dwelle** [comment]
@ad1992 I was re-checking the renderer, and yes, while we calculate coords from the bound container, there shouldn't be any blocker from caching both elements on the same canvas. Though I dimly recall we've gone over this and there was a reason for not doing it — perhaps also related to performance during some operations that invalidated both? Though nothing that makes much sense to me now. Do you remember the reason?

**Comment by ad1992** [comment]
I have pushed a perf improvement and it works much better for me, can someone try it out here and let me know?

https://excalidraw-git-aakansha-fix-labeled-arrow-perf-excalidraw.vercel.app/#json=TVewArjSDX8Eh9Tsquq33,7IbL43nXlxrvuVOB0x6Xnw

**Comment by zsviczian** [comment]
I love your test drawing :)

I am on a fairly low-powered laptop right now. I can confirm that [your fix](https://excalidraw-git-aakansha-fix-labeled-arrow-perf-excalidraw.vercel.app/#json=TVewArjSDX8Eh9Tsquq33,7IbL43nXlxrvuVOB0x6Xnw) works much better than the same on [excalidraw production](https://excalidraw.com/#json=o60sTFm-83lEKdLHMZo5-,A1Xc973WB3lpj6faof9ZUQ). On my laptop the test image on excalidraw production moves once every 10-15 seconds rendering it completely unusable. The one with the fix lags severely, but at least usable (one refresh roughly every second maybe even more frequent)

But freedraw performance, even if I only have 10 arrows degrades to choppy lines.
Also the arrow disappears temporarily when adding a label.

**Comment by zsviczian** [comment]
there is an issue with rotation in the fix

https://github.com/user-attachments/assets/d84bf38f-b440-4545-aa8a-74d926a4cbe5

**Comment by dwelle** [comment]
Can confirm the perf is much better.

> But freedraw performance, even if I only have 10 arrows degrades to choppy lines.

We'll work on that separately. @ryan-di will actually be taking it up in the coming ~week.

**Comment by zsviczian** [comment]
Why not cache the arrow and the label in elementwithcanvas? I guess the issue is with rotating the text to counter the rotation of the arrow, so text is always readable. Since renderelement includes a rotation, the text container with the background should be rotated -element.angle in element with canvas, that would result in the right rotation during rendering.

Am I missing something?

**Comment by dwelle** [comment]
> Why not cache the arrow and the label in elementwithcanvas? I guess the issue is with rotating the text to counter the rotation of the arrow, so text is always readable. Since renderelement includes a rotation, the text container with the background should be rotated -element.angle in element with canvas, that would result in the right rotation during rendering.

Oh now I remember. Yeah, that was the reason for not caching on the same element. Rotated elements are not redrawn on their cached canvases, instead they're rotated when bitmap-copying onto the main canvas. If we wanted to make that work with labels we'd have to bust the cache on rotation.

**Comment by zsviczian** [comment]
why would the counter rotation of the text not work?
And why do we have the rotation by angle during render? to improve the performance of the rotation operations?
In that case an option could be to pre-rotate arrows with labels in elementwithcanvas and similar to now where there is a condition isArrowElement && hasBoundedText you could drop the cache and regenerate the elementwithcanvas for the arrow with label and omit rotation in renderelements

I would trade poor rotation performance for arrows any day for poor overall performance. Rotation happens rarely, panning, zooming, freedraw scribble all the time.

**Comment by dwelle** [comment]
> I would trade poor rotation performance for arrows any day for poor overall performance. Rotation happens rarely, panning, zooming, freedraw scribble all the time.

Agreed.

**Comment by ad1992** [comment]
> why would the counter rotation of the text not work? And why do we have the rotation by angle during render? to improve the performance of the rotation operations? In that case an option could be to pre-rotate arrows with labels in elementwithcanvas and similar to now where there is a condition isArrowElement && hasBoundedText you could drop the cache and regenerate the elementwithcanvas for the arrow with label and omit rotation in renderelements
> 
> I would trade poor rotation performance for arrows any day for poor overall performance. Rotation happens rarely, panning, zooming, freedraw scribble all the time.

I have fixed the issues and it should be good now.
For rotation I am currently updating the cache, probably that's what you meant above as well.

**Comment by ad1992** [comment]
closed via #8267
