### ISSUE TITLE
BUG: Sometimes a blank key will cause a line break in the text.

### ISSUE THREAD

**Issue by kin30528** [excalidraw/excalidraw#8258]
**Your environment**
Win 10
Firefox v128.0 64bit Excalidraw v0.17.3
Obsidian v1.6.7 Excalidraw v2.29

I found that if there is a space in a sentence, it will often lead to the text after the space to be replaced by a new line, I guess it may have something to do with the incompatibility of the Chinese writing language with the English rules, as far as I know, a Chinese word will be regarded by the system as a letter of the English, which leads to the Chinese article to follow the rules of the English, and encountered the situation that the Chinese sentence is forced to break the line for a blank key.

**Obsidian**
Simple Vault: [test.zip](https://github.com/user-attachments/files/16237436/test.zip)
![圖片](https://github.com/user-attachments/assets/10e510df-83e9-4440-b2e9-a37f19b8b527)

This is a long time for me to cause trouble, I hope you can help me solve this problem, thank you for making this best plugin!

**Web**
![圖片](https://github.com/user-attachments/assets/ac811951-3da6-4db0-b1e8-6aaa85ab3ae3)

**Expected behavior**
![Expected behavior](https://github.com/user-attachments/assets/706a84b8-3bfa-4a71-9ce6-1f640b191a19)
![Expected behavior_1](https://github.com/user-attachments/assets/170eeb7b-f39c-423b-b6b3-ffe1068199db)

**Comment by Mrazator** [comment]
We will be releasing support for the whole CJK soonish, which should fix also this issue! (https://github.com/excalidraw/excalidraw/pull/8530)

Feel free to give us early feedback, preview is available here:
https://excalidraw-git-mrazator-first-class-support-chinese-excalidraw.vercel.app/
