### ISSUE TITLE
On click does not open Main Menu dropdown

### ISSUE THREAD

**Issue by ArmanGharibyan93** [excalidraw/excalidraw#8262]
When I click on MainMenu component dropdown doesn't open. May be someone had this problem before as well and can help me?
![image](https://github.com/user-attachments/assets/0756947b-c94f-4c87-b95a-0d8d023a9838)
I use:
"@excalidraw/excalidraw": "^0.17.3", 
 "react": "^18.3.1",
 "react-dom": "^18.3.1",
![image](https://github.com/user-attachments/assets/89f5c904-bcc5-421e-bfed-4f9437592e2c)

**Comment by dwelle** [comment]
Can't repro on 0.17.6 or 0.17.3: https://codesandbox.io/p/sandbox/excalidraw-mainmenu-zrrjx3?file=%2Fsrc%2FApp.tsx%3A12%2C12

**Comment by ArmanGharibyan93** [comment]
@dwelle  I tried with versions 0.17.6 or 0.17.3 0.17.0 the same thing. Maybe you have some ideas what can cause that bug in my side?

**Comment by dwelle** [comment]
No clue. If you can reproduce in CodeSandbox (with as much of your code as needed), that would help.

**Comment by ArmanGharibyan93** [comment]
@dwelle I found what causing the problem, but at the moment not sure how to fix it come from conflict of class. If I remove dropdown-menu class
![image](https://github.com/user-attachments/assets/0e72febd-4aae-4bad-a0d4-12a8dd710562)
I see items
![image](https://github.com/user-attachments/assets/da43248b-3646-458c-b629-2ca5b0284af3)
this class name come from another library, because I use module system.
I need to find way change one of that class names

**Comment by ArmanGharibyan93** [comment]
class coming from "bootstrap": "^5.1.3", library

**Comment by akashjpal** [comment]
I ran it locally, and it just working fine

**Comment by benridev** [comment]
@ArmanGharibyan93 thank you for your clue.
I also had the same problem, and just solved it by adding below css:
```
.excalidraw .dropdown-menu{
    display: unset !important;
    padding: unset !important;
}
```

**Comment by ArmanGharibyan93** [comment]
@benridev yes your code worked for me as well. Thank you too for this easy way solution.
![image](https://github.com/user-attachments/assets/6509c02d-b64d-48f1-bfb6-f6e3c85596a5)

**Comment by ArmanGharibyan93** [comment]
This code solving the problem https://github.com/excalidraw/excalidraw/issues/8262#issuecomment-2260720194
