### ISSUE TITLE
Facing issue in Excalidraw 

### ISSUE THREAD

**Issue by Nickpanchal** [excalidraw/excalidraw#8271]
![Screenshot (204)](https://github.com/user-attachments/assets/b2a20bb5-35dd-4ce9-8c1d-b75e5b6be126)

### Why does this always happen when I draw a circle?

**It's a BUG, I guess.. please solve it as soon as possible.**

Does anyone face this same issue?

**Comment by Mrazator** [comment]
Excalidraw mimics handwriting style for all the elements, defaulting to *Artist* sloppiness, which under the hood leverages https://roughjs.com/. Hence this imprecision is there intentionally, though it might deserve some improvements in the future.

You can eliminate the hand-drawn feel by decreasing sloppiness to **Architect** style, as shown in the recording:

https://github.com/user-attachments/assets/66261130-fc36-4f1a-8158-38162a2b813b

**Comment by Nickpanchal** [comment]
okay :)
