### ISSUE TITLE
Binding area flickering in dark mode when connected arrow edge control point is moved with SHIFT pressed

### ISSUE THREAD

**Issue by mtolmacs** [excalidraw/excalidraw#8281]
![flicker](https://github.com/user-attachments/assets/1c8ebf7e-43c7-41cd-b496-de7ee3596753)

It should not show the binding area to be consistent with the behavior when SHIFT is not pressed while moving the edge control point.

**Comment by lalitcap23** [comment]
attempting

**Comment by rothardo** [comment]
Could you please let me know if this issue has been resolved? I’m interested in working on it and would like to understand if it can be reassigned or if someone is still actively addressing it. Thank you!

**Comment by mtolmacs** [comment]
@rothardo it's not resolved, so go ahead and take it on.

**Comment by rothardo** [comment]
@mtolmacs can you please assign this to me, and let me know in more detail to go about this issue, 
as I have few questions on this one, starting with does it happen only in dark mode, or does it happen in the light mode too?

**Comment by rothardo** [comment]
reproducing this one is tricky, may I know more details on reproducing the same?

**Comment by mtolmacs** [comment]
Doesn't seem to be happening anymore, so closing it.
