### ISSUE TITLE
Fonts no longer load

### ISSUE THREAD

**Issue by zadeviggers** [excalidraw/excalidraw#8290]
When I am using an adblocker that blocks requests to Google domains, the fonts no longer load, and everything is in a serif font.
It looks like this is because the fonts are being loaded from Google Fonts domains.

This didn't use to be a problem until the last week or so.

Possible solutions:
- Vendor the fonts (i.e., self-host them on your domain). This means that adblockers will allow them to load, even if only the three default fonts are vendored.
- Include a keyword like `cursive`, `sans-serif` or `monospace` in the `font-family` for the three default fonts. This would mean that even if external fonts are blocked, it could fall back to a system font that's close enough.

Ideally, both proposed solutions would be implemented so that even if the self-hosted fonts don't load, a reasonable fallback is available.

Browser: Firefox 128 (with uBlock origin configured to block requests to Google domains)
OS: macOS 15 (beta) 

![image](https://github.com/user-attachments/assets/c79b778a-e982-454f-aef9-686708b4c950)

**Comment by Mrazator** [comment]
Most of the fonts are now hosted on our digital ocean CDN, there is a [PR](https://github.com/excalidraw/excalidraw/pull/8286) adding a fallback to our excaldraw.com domain which should solve issues to the selected code font (Comic Shanns) in the screenshot, as well as most of the other fonts (new Excalifont and old Virgil, Helvetica & Cascadia).

Could you try https://excalidraw-git-mrazator-fonts-fallbacks-excalidraw.vercel.app/?

About the Google fonts (Nunito and Lilita One), could you confirm these are still not loaded on the above domain?

<img width="495" alt="image" src="https://github.com/user-attachments/assets/d773c769-c9f9-4049-b3ec-333d93c15444">

**Comment by zadeviggers** [comment]
Yep, everything except Nunito and Lilita One work on the linked site!

**Comment by dwelle** [comment]
@zadeviggers hi, you're stating:

> Browser: Firefox 128 (with uBlock origin configured to block requests to Google domains)

Do you also block domains from DigitalOcean such digitaloceanspaces.com?

> Yep, everything except Nunito and Lilita One work on the linked site!

These two fonts are served from Google fonts, and currently there isn't a fallback for them.

**Comment by Mrazator** [comment]
Reading https://github.com/gorhill/uBlock/wiki/Per-site-switches#no-remote-fonts:

> Keep in mind, though, that this rule blocks all first-party and third-party fonts. As a lighter alternative, you can also choose to allow first-party fonts and block only third-party fonts by adding the filter

Looks like `uBlock` by default blocks also first-party fonts, so fallbacks won't help unless users have specific filters to allow requests within the same domain.

Anyway, we've added the fallbacks for our self-hosted fonts (soon to be released), as it also solves other similar network-related issues.

For Google fonts, such as Nunito and Lilita One, we are not adding fallbacks for now. Although we will consider self-hosting them in the future.
