### ISSUE TITLE
Comic Shanns related issues

### ISSUE THREAD

**Issue by Mrazator** [excalidraw/excalidraw#8327]
Consider the following comparison between Cascadia and Comic Shanns. It's apparent Comic Shanns isn't truly mono-spaced.

![cascadia-comic shanns](https://github.com/user-attachments/assets/8bf15f84-c79c-4adf-8771-d8ceb27a2c4b)

```
Sphinx of Black Quartz, Judge My Vow!!! Sphinx of Black Quartz, Judge My Vow!!! Sphinx of Black Quartz, Judge My Vow!!! 
12345678901234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789
[                                                                                                                     ]
In a constant-width font, the 117 spaces between the [] above would make the line start/end points align perfectly!
```

The numbers alignment seems to be way off as well. E.g.:

<img width="604" alt="Screenshot 2024-08-06 at 11 31 07" src="https://github.com/user-attachments/assets/18a8304a-5e54-4682-b43a-aff884e8f26b">

Extended Latin glyphs like `Č, Ř, Ě` are incorrect.

![Untitled-2024-08-05-2003](https://github.com/user-attachments/assets/c21eed1a-c97d-4dab-a533-a8539b009e32)

Some other glyphs are incorrect, like "¿" - "questiondown" :

![image](https://github.com/user-attachments/assets/98bb9207-f2d2-4ed6-9cd8-f5dad58ea3a2)

Could we find an OFL-like licensed fork solving most of these issues? E.g.:

1. https://github.com/dtinth/comic-mono-font
2. https://github.com/shannpersand/comic-shanns
3. https://github.com/kaBeech/serious-shanns
4. https://github.com/jesusmgg/comic-shanns-mono

---

Once we find the right alternative, let's also:
- split all the fonts into multiple chunks
- update preloads which include the hashes rn
- separate fonts into a `FontFamilyName` subfolder

**Comment by rudeyak** [comment]
A couple of beautiful options that are OFL:

https://github.com/tonsky/FiraCode
https://github.com/JetBrains/JetBrainsMono
https://github.com/source-foundry/Hack (MIT license)
https://github.com/rubjo/victor-mono (has cool cursive italics and a bunch of weights)
