### ISSUE TITLE
Issue with Rectangle lines being inconsistent 

### ISSUE THREAD

**Issue by Sahil-Gulihar** [excalidraw/excalidraw#8341]
![image](https://github.com/user-attachments/assets/16b361cb-7484-4c38-a582-b3080e188254)

**Comment by dwelle** [comment]
By design, since one of the main features of Excalidraw is a hand-drawn look. You can disable this by setting sloppiness to "Architect":

![image](https://github.com/user-attachments/assets/04cd72de-bc8d-47f1-aeb6-7de5ffef1616)
