### ISSUE TITLE
feat: Improve fast flowchart creation

### ISSUE THREAD

**Issue by lightningRalf** [excalidraw/excalidraw#8349]
Building on the functionality described in #8329, I would like to request the ability to specify the type of symbol to be created while holding down the Ctrl key.

Example:
I have a square node selected, and I want to create a diamond next. By pressing `Ctrl + Arrow Key + 3`, I would create a diamond.
To create another square, I would press `Ctrl + Arrow Key + 2`.
If I press `Ctrl + Arrow Key` again, a square is created since the current node is a square.
This enhancement would provide more flexibility in designing flowcharts by allowing users to directly control the type of node they create while maintaining the streamlined workflow provided by the existing keyboard shortcuts.

**Comment by mtolmacs** [comment]
There is a PR #8533 which will bring shape change functionality to Excalidraw, which will make it possible to quickly set the type of the element as you lay out flowchart elements.

**Comment by lightningRalf** [comment]
This PR #8533 got closed without implementing. Or is there a second PR that attempted the same thing?
