### ISSUE TITLE
Lines are missing in exported SVG

### ISSUE THREAD

**Issue by nelangovan** [excalidraw/excalidraw#835]
Both horizontal and vertical lines are missing in the exported SVG while PNG export is fine,
I tried  in Chrome, Firefox and Opera. All have same problem.

![Screenshot from 2020-02-24 09-51-09](https://user-images.githubusercontent.com/4423751/75173988-00dddf80-56ed-11ea-8747-8a59d62fd190.png)

Exported SVG: 
![Screenshot from 2020-02-24 09-51-33](https://user-images.githubusercontent.com/4423751/75173976-fa4f6800-56ec-11ea-8c1e-4cdef1e112a8.png)

**Comment by dwelle** [comment]
I'll make a fix.

**Comment by nelangovan** [comment]
Thanks. Working now.
