### ISSUE TITLE
Canvas not loading - React + Vite + TS

### ISSUE THREAD

**Issue by mbj36** [excalidraw/excalidraw#8373]
Hello team,

I am trying to use excalidraw npm package, here is my code - https://stackblitz.com/edit/vitejs-vite-bdutvi?file=src%2FApp.tsx,vite.config.ts&terminal=dev

Canvas is not loading for me, i don;t even see any issue on console

Version - 0.17.6

**Comment by mbj36** [comment]
@dwelle Not sure, what am i doing wrong here, do check it once!

**Comment by VijinV** [comment]
@mbj36 

To resolve the issue, you must wrap the component in a `<div>` and apply specific width and height values through CSS. Here's an example:

```jsx
function App() {
  return (
    <div className='canvas'>
      <p>Excalidraw</p>
      <Excalidraw />
    </div>
  );
}
```

And the corresponding CSS:

```css
.canvas {
  width: 1000px;
  height: 1000px;
}
```

**Comment by mbj36** [comment]
Thanks @VijinV That worked, I am wondering why is it not mentioned in documentation

**Comment by dwelle** [comment]
@mbj36 we do mention it, but maybe we should put it elsewhere to make it more clear: https://docs.excalidraw.com/docs/@excalidraw/excalidraw/installation#dimensions-of-excalidraw

**Comment by mbj36** [comment]
Yes, if you take a look at this example - https://docs.excalidraw.com/docs/@excalidraw/excalidraw/integration#module-bundler, if i copy and try to run it, it won't work, since it doesn't have `width` style

**Comment by dwelle** [comment]
width should be unnecessary, only height is needed. At least as far as I'm aware of. That said, docs do mention both, to be on the safe side.
