### ISSUE TITLE
Keyboard arrow keys stop to move elements when the group includes an elbow arrow

### ISSUE THREAD

**Issue by zsviczian** [excalidraw/excalidraw#8387]
@mtolmacs: Select the group in this picture then use the arrow keys on the keyboard to reposition it.

https://excalidraw.com/#json=__6cUUURXnFVvL1ef-4V8,YgPZa44O29ormXNu2MoI2w

**Comment by zsviczian** [comment]
Having looked at the code I concluded that this is not a bug, but a too restrictive feature. However, we can make the restriction more targeted/relaxed even without touching the arrow move logic. The keyboard move should only be restricted if the start or end element is not part of the selection.

**Comment by mtolmacs** [comment]
I agree, I'd say this is an unintended effect of limitations applied to elbow arrows.

**Comment by zsviczian** [comment]
This is my proposed solution: #8392
