### ISSUE TITLE
add arrow start/end variations

### ISSUE THREAD

**Issue by darrenjennings** [excalidraw/excalidraw#839]
Would be nice to have arrow start/end feature (or some variation of configuring an arrow) so that you don't end up with arrows like this:
![image](https://user-images.githubusercontent.com/5770711/75201737-47582c00-5737-11ea-9a7a-a8003fe168b0.png)

This is how it looks in sketch:
![image](https://user-images.githubusercontent.com/5770711/75202055-1f1cfd00-5738-11ea-85ef-3bacf418be18.png)
![image](https://user-images.githubusercontent.com/5770711/75202063-23491a80-5738-11ea-9060-ffbaffa7da81.png)

**Comment by dwelle** [comment]
related:

- [Option to change position of Arrow Points](https://github.com/excalidraw/excalidraw/issues/657)
- [Feature request: Support for "crow's foot" arrows](https://github.com/excalidraw/excalidraw/issues/616)

**Comment by vjeux** [comment]
Closing in favor of #616 which is very similar.
