### ISSUE TITLE
Digits in monospaced font are not properly spaced

### ISSUE THREAD

**Issue by j2kun** [excalidraw/excalidraw#8397]
(Paying customer, love the product!)

You can see this issue in the screenshots below, where I'm trying to align a grid of numbers

![image](https://github.com/user-attachments/assets/bbbde2d3-53f7-4c79-a737-3b8244ffca6d)

![image](https://github.com/user-attachments/assets/43f8b7c2-fc21-4d32-8390-86f4dffd7d9a)

**Comment by camfowler** [comment]
Similarly, I paste markdown tables or code snippets. These rely on a monospaced font to render with correct alignment. When the font changed to Comic Shanns, the alignment broke. 

E.g.

```
| col 1   |   date | col 2       |   quantity |   date_2 |   date_3 |
|---------|--------|-------------|------------|----------|----------|
| val 1   |   2000 | abc123      |         01 |     2001 |     0202 |
| val 2   |   2000 | Lorem ipsum |         01 |     2001 |     0202 |
```

Renders as:

<img width="638" alt="image" src="https://github.com/user-attachments/assets/cecedf17-e8fd-4c49-873a-c4115f7db515">

I don't mind the new font, although the main reason I select the "code" font is to render with correct alignment, so having monospace is very helpful.

Keep up the great work team - absolutely love Excalidraw, you are doing a great job.
