### ISSUE TITLE
Frames sequence number doesn't work

### ISSUE THREAD

**Issue by Bobatev** [excalidraw/excalidraw#8398]
I'm running Excalidraw v2.3 and use almost daily framing tool for my presentation. I noticed that sequence number (part of frames' name) haven't been working for a while. All frames are named "frame" but Slideshow script still recognizes the order properly. Is that normal?

**Comment by ryan-di** [comment]
Yes, it's to be expected since we decided to move away from having sequence number in the naming.

**Comment by Bobatev** [comment]
Perfect, good to know :).
