### ISSUE TITLE
Add text formatting

### ISSUE THREAD

**Issue by busy-duck** [excalidraw/excalidraw#8400]
Currently, it seems that text formatting is limited to changing font size.
Are there plans to add text formatting options (e.g., bold, italic, thin, strike-through, etc) in a future release?

I understand that this might be a limitation of the typeface, but since it is managed by Excalidraw, I thought it was worth asking (as I understand it, the font used is managed by excalidraw, at least it is in the same github repository...).

**Comment by Mrazator** [comment]
It's on the roadmap! Let's track it here #5138
