### ISSUE TITLE
Copy to clipboard text does not change on clicking it

### ISSUE THREAD

**Issue by dheereshagrwal** [excalidraw/excalidraw#8418]
When you click copy to clipboard in the export options, the text should change to copied, and the copy file icon should also change.

Video attached for reference

https://github.com/user-attachments/assets/7435d750-7e01-44bf-9ba6-fd20ee83aa70

**Comment by faizan0717** [comment]
Instead can we give a toaster ?

because changing name and icon is not good if there are multiple attempts to copy

**Comment by dheereshagrwal** [comment]
@faizan0717 
The text will change back to "Copy to Clipboard" after 2 seconds. That's a standard way to do it.
