### ISSUE TITLE
Cannot Read Length When Opening File

### ISSUE THREAD

**Issue by acafourek** [excalidraw/excalidraw#843]
Today, when attempting to open two Excalidraw exports, I would select the file locally and click "open" in the browser dialog and see a console error of `actionExport.tsx:82 TypeError: Cannot read property 'length' of undefined` and the file does not load to the UI.

The exports were generated from the site sometime 3-5 weeks ago and a local parser confirmed that they are valid JSON

Perhaps related to #632?

Full console error:
```
actionExport.tsx:82 TypeError: Cannot read property 'length' of undefined
    at $ (sizeHelpers.ts:5)
    at data.ts:346
    at Array.filter (<anonymous>)
    at dt (data.ts:346)
    at data.ts:145
    at new Promise (<anonymous>)
    at data.ts:144
    at u (runtime.js:45)
    at Generator._invoke (runtime.js:271)
    at Generator.forEach.e.<computed> [as next] (runtime.js:97)
```

### System info

Mac OSX 10.15.3 
Chrome 79.0.3945.13
Cookies + JS enabled

[Excali-Examples.zip](https://github.com/excalidraw/excalidraw/files/4262672/Excali-Examples.zip)

**Comment by dwelle** [comment]
Thanks for the report, will have a fix shortly.

**Comment by acafourek** [comment]
Fastest bug fix on the internet today, thanks! 🚀
