### ISSUE TITLE
When selecting an arrow, the extremities are not updated on the selector

### ISSUE THREAD

**Issue by Aqueuse** [excalidraw/excalidraw#8453]
When I click on an arrow, I would like that the selected arrow would be well represented in the selector. 

For example 

![Capture d’écran 2024-09-01 090820](https://github.com/user-attachments/assets/9a0dc82a-948a-4bd8-a960-9dc7d1180359)

I would like that this was the correct/selected extremities of the arrow selected.

Not sure if it is clear enough, don't hesitate to ask me more precisions.

Thank you for the amazing job ❤️

**Comment by mtolmacs** [comment]
@Aqueuse can you still reproduce it? I just tried it in various combinations on excalidraw.com and it shows the arrowhead statuses properly.
