### ISSUE TITLE
Bug: convertToExcalidrawElements on type: "frame" ignores x and y properties when manually set

### ISSUE THREAD

**Issue by RobertK0** [excalidraw/excalidraw#8461]
when initializing `<Excalidraw />` with 
```
initialData = {
  elements: convertToExcalidrawElements([
    {
      type: "frame",
      children: [],
      x: 300,
      y: 300,
      height: 100,
      width: 100,
    },
  ]),
};
```

x and y values are ignored no matter what, as they seem to be calculated from children, only workaround I found around this, is not to use `convertToExcalidrawElements`, but instead just to drop in raw data as `initialData` and it renders fine

**Comment by dwelle** [comment]
I'd always prefer user-defined values for `x`/`y`/`height`/`width`. Checking https://github.com/excalidraw/mermaid-to-excalidraw, it shouldn't cause any issues. /cc @ad1992

**Comment by dwelle** [comment]
We handle frames specially:

https://github.com/excalidraw/excalidraw/blob/f4dd23fc31e218298bacce3ab39c2556fd12e639/packages/excalidraw/data/transform.ts#L719-L773

Here you mentioned you didn't want to complicate the frame use case:

https://github.com/excalidraw/excalidraw/pull/7205#discussion_r1378571137

As for the mermaid-to-excalidraw, I was checking if we don't rely on some implicit behavior there, and it doesn't seem so.

As such, changing the code linked above to prefer the user-supplied values should be safe.

**Comment by ad1992** [comment]
> We handle frames specially:
> 
> https://github.com/excalidraw/excalidraw/blob/f4dd23fc31e218298bacce3ab39c2556fd12e639/packages/excalidraw/data/transform.ts#L719-L773
> 
> Here you mentioned you didn't want to complicate the frame use case:
> 
> [#7205 (comment)](https://github.com/excalidraw/excalidraw/pull/7205#discussion_r1378571137)
> 
> As for the mermaid-to-excalidraw, I was checking if we don't rely on some implicit behavior there, and it doesn't seem so.
> 
> As such, changing the code linked above to prefer the user-supplied values should be safe.

Yes I think should be fine, we can give preference to user values always irrespective of how the actual diagram turns out to be. I will raise a PR for the same.
