### ISSUE TITLE
Change the backend URL to point to json.excalidraw.com

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw#847]
Right now they are point directly to appspot.com URLs

https://github.com/excalidraw/excalidraw/blob/master/src/scene/data.ts#L26-L29

Something in the configuration of ZEIT, Google Domains and App Engine, that I couldn't figure out why is not working.

The following URLs should point to:

<img width="396" alt="Screenshot 2020-02-28 at 1 56 40 PM" src="https://user-images.githubusercontent.com/125676/75550431-2abb3d00-5a32-11ea-9be8-7f6e01839b58.png">

- https://json.excalidraw.com (currently loads the app)
- https://excalidraw-json.appspot.com (actual URL)

--------

### PS. We recently switched from Netlify to ZEIT, and might disruption might occur in the next few hours.. Just be patient, we are on it.

**Comment by vjeux** [comment]
Done!
