### ISSUE TITLE
Copy the shereable link instantly if possible when showing the message.

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw#848]
<img width="447" alt="Screenshot 2020-02-28 at 2 08 44 PM" src="https://user-images.githubusercontent.com/125676/75551172-d913b200-5a33-11ea-9d93-020b91e9521a.png">

### Current behaviour

The user should manually copy the selected URL.

### Prefered

The link should be already copied

**Comment by dwelle** [comment]
I thought the auto-copy-to-clip was removed for a reason (not sure what it was). /cc @vjeux

**Comment by lipis** [comment]
I think it's still OK to implement it, wherever it's supported.

**Comment by vjeux** [comment]
Let's not do that. I don't like when websites/app mess up with my clipboard.
