### ISSUE TITLE
Add anonymous google analytics events for user's actions

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw#851]
It will help us possibly update the UI and adjusted based on the results.

https://support.google.com/analytics/answer/1033068?hl=en

_Please update this List accordingly if you like._

| Category   | Action       | Label          | Value | Description             |
| ---------- | ------------ | -------------- | :---: | ----------------------- |
| General    | Load         | JSON           |   1   | When user click Load    |
| General    | Save         | JSON           |   1   | When user clicks Save   |
| General    | Export       | Dialog         |   1   | When user clicks Export |
| General    | Reset        | Canvas         |   1   | Reset the canvas        |
| General    | Background   | {ColorName}    |   1   | Reset the canvas        |
| General    | Zoom         | Zoom In        |   1   |                         |
| General    | Zoom Out     | Zoom Out       |   1   |                         |
| General    | Zoom Reset   | Zoom Reset     |   1   |                         |
| Export     | File         | PNG            |   1   |                         |
| Export     | File         | SVG            |   1   |                         |
| Export     | Clipboard    | JSON           |   1   |                         |
| Export     | Shareable    | Link           |   1   |                         |
| Properties | Stroke       | {ColorName}    |   1   |                         |
| Properties | Background   | {ColorName}    |   1   |                         |
| Properties | Fill         | {FillType}     |   1   |                         |
| Properties | Stroke Width | {StrokeWidth}  |   1   |                         |
| Properties | Sloppiness   | {Sloppiness}   |   1   |                         |
| Properties | Opacity      | {Opacity}      |   1   |                         |
| Main       | Selection    | Select         |   1   |                         |
| Main       | Rectangle    | Select         |   1   |                         |
| Main       | Diamond      | Select         |   1   |                         |
| Main       | Ellipse      | Select         |   1   |                         |
| Main       | Arrow        | Select         |   1   |                         |
| Main       | Line         | Select         |   1   |                         |
| Main       | Text         | Select         |   1   |                         |
| Main       | Lock         | Select         |   1   |                         |
| Locale     | Language     | {LanguageCode} |   1   |                         |

**Comment by vjeux** [comment]
Honestly, I don't know what we would do differently based on this data. I'd rather not collect it in order to help with our story around privacy.

**Comment by kbariotis** [comment]
@vjeux well privacy is one thing for sure and monitoring is another and it depends on where we draw the line.

A use case could be monitoring the average local storage size. Based on the number we can take a decision on https://github.com/excalidraw/excalidraw/issues/1543 and on https://github.com/excalidraw/excalidraw/issues/1280.

Also monitoring the average number of collaborators/latency could help us understand where we have performance issues and whether they critical or not.

**Comment by vjeux** [comment]
I'm open to adding monitoring in order to answer specific questions. You seem to have a concrete use case where average local storage size would be useful, so this is fine. This original issue was about adding blanket list of logging without clear use cases.
