### ISSUE TITLE
The current "code" fonts are "ruined"

### ISSUE THREAD

**Issue by AayushSameerShah** [excalidraw/excalidraw#8551]
Just have a look at this:
![image](https://github.com/user-attachments/assets/fb66c78f-c9df-4639-9370-d6b3029de7dd)

They are not common-width fonts anymore! It is all misaligned and looks "un-soothing" to the eyes.

Please revert to some consolas or some other `actual code font` for this purpose! 

Thanks

**Comment by DevMhrn** [comment]
I would like to work on this issue , please assign it to me

**Comment by AayushSameerShah** [comment]
@DevMhrn have it!

**Comment by rudeyak** [comment]
Related: https://github.com/excalidraw/excalidraw/issues/8331

**Comment by Mrazator** [comment]
Duplicate of #8327
