### ISSUE TITLE
Couldn't save to the backend database - does Excalidraw+ Fix this?

### ISSUE THREAD

**Issue by acrylicus** [excalidraw/excalidraw#8552]
Hi - we have started using Excalidraw collaboratively and have noticed that nearly every diagram we make hits some limit leading to "Couldn't save to the backend database".

We are happy to pay to fix this issue with Excalidraw+, but I can't see anything online about upgrading leading to more storage on the backend database. Can someone confirm if the paid version resolves this?

**Comment by dwelle** [comment]
Hi. Yes, the database we're using on excalidraw.com is a 1MB limit. Also the collaboration here isn't meant for long-term/large diagrams.

On Excalidraw+, there's no limit such as this.
