### ISSUE TITLE
Text disappears when closing the color picker popup until the user double clicks on the canvas

### ISSUE THREAD

**Issue by zsviczian** [excalidraw/excalidraw#8558]
I was consistently able to reproduce the issue on MacBook Safari, but only once on Windows Chrome. The issue also consistently happens in Excalidraw Obsidian.

https://github.com/user-attachments/assets/e12381b4-a4c0-4ca0-9349-0fe6c81ad8e9

Steps to reproduce:
1) create a text element
2) double click the text element to start editing
3) click the color picker and open the color picker popup
4) don't select a color, but click the canvas

The text disappears until you double-click on the canvas to start editing a new text element.

Based on debugging the issue is that even though `editingTextElement` is set to null `onSubmit`, there is a race condition somewhere that resets `editingTextElement` with the previous value, thus at the end of the submit `editingTextElement !== null`.

https://github.com/excalidraw/excalidraw/blob/3fe1883f3f6bc45592f2aa6c721af6694e61935f/packages/excalidraw/components/App.tsx#L4740-L4743

Adding the following after the code above solves the issue, but of course this is not the solution we want... just to confirm that the issue is indeed this race condition:

```ts
  setTimeout(()=>{
    if(this.state.editingTextElement) {
      this.setState({
        newElement: null,
        editingTextElement: null,
      });
    }
  });
  ```

**Comment by ObstinateM** [comment]
Hey, opened a PR #8624 to fix it
