### ISSUE TITLE
fix: Triggering panel when undo or redo is clicked.

### ISSUE THREAD

**Issue by rahul-ramesh-chandra** [excalidraw/excalidraw#8577]
https://github.com/user-attachments/assets/cbcd52b8-cfb5-4beb-92dd-62b1604921ab

Whenever i click on redo or undo button, panel is automatically triggered. It might be great if panel is triggered only when any canvas element is clicked.

**Comment by dhruvkjain** [comment]
is this issue up for grabs? @rahul-ramesh-chandra

**Comment by Shiwang0-0** [comment]
@rahul-ramesh-chandra but is there a need to do so? panel view makes it easy to change whatever user wants ( without clicking on the canvas again ) thus saving user's time. also when object changes while doing undo, it highlights/selects the object, which is similar to selecting that object which then ultimately opens up the panel. if we remove the panel opening part it will be just selecting the object and then how are we suppose to edit it ?

**Comment by Mrazator** [comment]
The attached video can't be played, though from what you are describing that's the intended behavior. Undo goes back in time also for past selections (which trigger the panel). Meaning if you select three elements in a row, each undo will take you back to previous selection, with the panel displaying properties specific to each element.
