### ISSUE TITLE
"Export to PNG" with "Embed Scene" not working with app.excalidraw.com

### ISSUE THREAD

**Issue by thewisenerd** [excalidraw/excalidraw#8580]
this is a weird bug, and does not affect excalidraw.com.

i have tried "force-refresh"-ing my app.excalidraw.com, and trying this in incognito, another browser, and such. nothing got "embed scene" working. breakpointing with the minified JS, I have the following;

all code is surrounding this block;
https://github.com/excalidraw/excalidraw/blob/47ee8a00945793340bb20715b2f383a4c3da2139/packages/excalidraw/data/index.ts#L154-L176

I have app.excalidraw.com, at `/assets/index-gDyAgSvQ.js`, with

```javascript
        if (A === "png") {
            let r = kR(i);
            return e.appState.exportEmbedScene && r.then(o => Promise.resolve().then( () => (aK(),
            sK)).then( ({encodePngMetadata: s}) => s({
                blob: o,
                metadata: yR(e.elements, e.appState, e.files, "local")
            }))),
            tK(r, {
                description: "Export to PNG",
                name: n.name,
                extension: "png",
                fileHandle: n.fileHandle
            })
        } else if (A === "clipboard")
```

while excalidraw.com, at `/assets/index-CcA2bwaB.js` has

```javascript
    if (e === "png") {
        let f = mp(u);
        return n.exportEmbedScene && (f = f.then(h => xe( () => Promise.resolve().then( () => z2), void 0).then( ({encodePngMetadata: p}) => p({
            blob: h,
            metadata: Yf(t, n, r, "local")
        })))),
        C2(f, {
            description: "Export to PNG",
            name: a,
            extension: "png",
            fileHandle: l
        })
    } else if (e === "clipboard")
```

the cause of the issue seems obvious, but the reason this happened is not; the minified javascript for app.excalidraw.com does not have the variable reassignment (`blob = blob.then()`) while the excalidraw.com one does.

please let me know if you need any more information regarding this.

**Comment by askadityapandey** [comment]
The `app.excalidraw.com` code should be updated to properly reassign the `blob` (or r in the minified version) when `exportEmbedScene` is true.

**Comment by thewisenerd** [comment]
can confirm that this is now fixed; thanks!
