### ISSUE TITLE
Discord Invite is invalid

### ISSUE THREAD

**Issue by ukpagrace** [excalidraw/excalidraw#8589]
I tried joining the discord channel, but it's link invalid

**Comment by ritikrai00** [comment]
Hi @ukpagrace, thanks for reporting the issue. I’ve checked the Discord invite link, and it seems to be valid.

**Comment by ukpagrace** [comment]
![Image](https://github.com/user-attachments/assets/93ff99b1-680e-4430-a808-a44599b4d4ab)
This from the ReadMe

**Comment by ritikrai00** [comment]
For me its working fine![Image](https://github.com/user-attachments/assets/8b0421dd-2889-431e-9145-2249b73a42d0)

**Comment by ukpagrace** [comment]
It's working on my phone, it's my laptop what was having the issue. Wonder why

**Comment by dwelle** [comment]
Works for me on desktop. Must be some Discord bug 🤷‍♂️. I'm closing for now as I'm not sure there's anything actionable.

You can also try this one: discord.gg/hW3cc5yKSh
