### ISSUE TITLE
Configuration of gh-pages

### ISSUE THREAD

**Issue by giovannigiordano** [excalidraw/excalidraw#86]
WIth the #75 I  ahve added the automatic deploy to GH pages but it is not working.
I have used this [action](https://github.com/JamesIves/github-pages-deploy-action).
As said in the PR should configure github pages to pick content from the branch `gh-pages`, because the deploy is not working for now.
Maybe there is a problem with the secrets, in the README of the repo, is suggested to create personal access token to make it work.

@vjeux

**Comment by vjeux** [comment]
![image](https://user-images.githubusercontent.com/197597/71753873-cf593e00-2e38-11ea-8dd8-42d7d6631124.png)

**Comment by vjeux** [comment]
Just added you admin of the repo, feel free to edit things to make it work!

**Comment by nanot1m** [comment]
@giovannigiordano can you point to errors in the logs? Couldn't find any
