### ISSUE TITLE
Support copying SVG to clipboard

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#860]
As mentioned in https://github.com/excalidraw/excalidraw/issues/386#issuecomment-581444340, I haven't been able to support copying `image/svg+xml` to clipboard which apps such as desktop vector editors could consume.

That being said, Figma supports this by copying plaintext SVG to clipboard which it seems the vector editors are smart enough to paste as SVG, so we can do the same.

One problem is, since it's plaintext, we can't simply copy it on `Cmd + C` because then (if we migrate to [system clipboard](#859)) it would replace the elements JSON we use in-app.

One solution is to do what Figma does, and that is to allow copying SVG via special contextMenu item:

![image](https://user-images.githubusercontent.com/5153846/75612990-03936700-5b29-11ea-946e-8e5318699555.png)

Later, when/if `image/svg+xml` support (which is [specced](https://w3c.github.io/clipboard-apis/#writing-to-clipboard) with some security caveats) is added to async clipboard API, we can switch to that.

**Comment by vjeux** [comment]
We now have Copy, Copy as PNG. Adding Copy as SVG would make sense as well.
