### ISSUE TITLE
Images don't load on Firefox

### ISSUE THREAD

**Issue by KwiatekMiki** [excalidraw/excalidraw#8600]
firefox 130.0.1 on left chrome 129.0.6668.70 on right
![Image](https://github.com/user-attachments/assets/76e79f82-2d6c-4831-af87-b53e48bc6878)
[excalidrawfile.zip](https://github.com/user-attachments/files/17267304/excalidrawfile.zip)

os: linux (pop!_os)

**Comment by Shiwang0-0** [comment]
works fine for me on ubuntu .![Image](https://github.com/user-attachments/assets/093e071b-a457-46c5-8833-072b11657ec6)

**Comment by KwiatekMiki** [comment]
it fixed itself
