### ISSUE TITLE
vercel部署ui出错

### ISSUE THREAD

**Issue by zy111x** [excalidraw/excalidraw#8604]
![Image](https://github.com/user-attachments/assets/20c313fe-fb3a-4e62-9f8e-7cdfe70f9f4c)
为什么我在vercel上部署的ui界面是这样？

**Comment by XINGYE391** [comment]
同楼主问题，请问解决了么

**Comment by Mrazator** [comment]
> Why is the UI interface I deployed on Vercel like this?

Looks like what you deployed is our nextjs example: https://github.com/excalidraw/excalidraw/tree/master/examples/excalidraw/with-nextjs
