### ISSUE TITLE
Very less font and colour options

### ISSUE THREAD

**Issue by MakuShraddha** [excalidraw/excalidraw#8607]
There are only few font and colours options availabe ,it can be added with atleast of 10 choices

**Comment by nadjascodejourney** [comment]
Hey, can you assign me to this issue? If yes, where do I find the Toolbar with the stroke and color options in the code? I already checked the files and somehow, I couldn´t find it or perhaps I have overlooked it. Thank you!

**Comment by Mrazator** [comment]
Thanks for the feedback, it is on the roadmap!
