### ISSUE TITLE
Line connect overlap with shape

### ISSUE THREAD

**Issue by nguyendinhkhiem123** [excalidraw/excalidraw#8635]
When I use the elbow arrow to connect two shapes, the elbow arrow accidentally overlaps other shapes and I can't edit the elbow arrow.

Here is a demo

https://github.com/user-attachments/assets/e6c73909-9f2c-4064-880a-b20b6cfdfe26

**Comment by anchor54** [comment]
Please Assign this issue to me

**Comment by Mrazator** [comment]
@mtolmacs has this in the backlog, so in the near future, it should be possible to edit the elbow arrow!

**Comment by seabeya** [comment]
:waiting_emoji:

![Image](https://github.com/user-attachments/assets/100c6650-acc4-4f1a-9686-6b03dd9c9e75)

**Comment by seabeya** [comment]
Solved with: https://github.com/excalidraw/excalidraw/pull/8952
