### ISSUE TITLE
Cannot move objects using mouse in Microsoft Edge browser

### ISSUE THREAD

**Issue by RobsKanbanZone** [excalidraw/excalidraw#8640]
As of today I cannot move objects using the mouse cursor.
I can select and resize, but not move.

Moving objects using cursor keys works just fine.

I have tried different things like toggling grid on/off, snap to objects on/off, Zen mode and changing Grid step. Nothing made a change and my objects remain unmovable.

**Comment by RobsKanbanZone** [comment]
It is working fine on my Android phone. 
My desktop browser is Microsoft Edge, that could be a clue perhaps?

**Comment by therealhamad** [comment]
https://github.com/user-attachments/assets/1d88b66b-4753-41ad-b7bd-640902448cdf
works fine over here in edge.
meaning the problem is not from the server side.
check browser config

**Comment by RobsKanbanZone** [comment]
> https://github.com/user-attachments/assets/1d88b66b-4753-41ad-b7bd-640902448cdf works fine over here in edge. meaning the problem is not from the server side. check browser config

Thanks man! I just cleared browser cache and cookies and it started working again :)
