### ISSUE TITLE
编辑器api

### ISSUE THREAD

**Issue by handsome-xiaowang** [excalidraw/excalidraw#8644]
请问有提供undo,redo copy，delete的编辑器api吗

**Comment by Mrazator** [comment]
Undo / redo is not exposed, but `history` is, so it should be trivial exposing it (assuming you would fork it, or prepare a PR).
Copy is not exposed, when forking you could get to it through the `actionManager` and `actionCopy`.
Delete could be implemented with `updateScene`, marking all items with `isDeleted`: `true`.
