### ISSUE TITLE
线上的dist 内部js 可以换成本地的吗

### ISSUE THREAD

**Issue by qgyd** [excalidraw/excalidraw#8665]
https://unpkg.com/@excalidraw/excalidraw@0.17.6/dist/excalidraw-assets/locales/zh-CN-json-069c304b5011429be615.js 这个在中国访问的有些慢,可以换成本地的打包地址吗,如何操作,这个项目是VUE的通过 veaury 组件嵌合使用这个组件的

**Comment by Mrazator** [comment]
You might try adding a `window.EXCALIDRAW_ASSET_PATH` as described in https://docs.excalidraw.com/docs/@excalidraw/excalidraw/installation#static-assets.
