### ISSUE TITLE
doesn't select a created item while the Lock is on

### ISSUE THREAD

**Issue by imanzaker** [excalidraw/excalidraw#8668]
the created item is not selected while the lock icon is on. it deprives you of making quick edits on every single item on the way you're adding the same item unless select the item by the click that takes your time and intrupts your working procedure.

**Comment by Mrazator** [comment]
ATM this is by design and changing it would create a breaking change. Selection means being also in the selection mode, while with a lock you can change the properties of the next shape / arrow, which is essential for drawing / writing.
