### ISSUE TITLE
Message : Couldn't decrypt data

### ISSUE THREAD

**Issue by ElisouG** [excalidraw/excalidraw#8669]
Dear Excalidraw Team,

I didn't save my work to disk (my fault). I did so on Wednesday and was able to reopen it yesterday, but not today. I received the following message: “Excalidraw.framalab.org says Unable to decrypt data”.

When I go to my history, I see a thumbnail of my work before I click on it.

Has my work been lost forever?

Kind regards,

Elise

**Comment by Mrazator** [comment]
Hi Elise, it looks like you are not on our official https://excalidraw.com/, but on a third-party https://excalidraw.framalab.org/, which is not managed by us. We don't even have "Unable to decrypt data" error message.

Anyway, you can try to open the .excalidraw file on https://excalidraw.com/ (if you have it).

If you don't have one, then it gets a bit complicated, but you might still access your data if you:
1. go to https://excalidraw.framalab.org/ 
2. open "Developer Tools" (check the note below on how to do that)
3. copy value inside "Application" tab > "Local storage" > https://excalidraw.framalab.org/ > "excalidraw"
4. go to https://excalidraw.com
5. open "Developer Tools`
6. paste the copied value inside "Application tab" > "Local storage" > https://excalidraw.com/ > "excalidraw"
7. refresh https://excalidraw.com/

![Image](https://github.com/user-attachments/assets/530c0767-d473-4314-82d5-ab2446a76b8e)

> To open the developer console in Google Chrome, open the Chrome Menu in the upper-right-hand corner of the browser window and select More Tools > Developer Tools. You can also use Option + ⌘ + J (on macOS), or Shift + CTRL + J (on Windows/Linux).

For further questions feel free to reach me on [Discord](http://discord.gg/UexuTaE)!

Or try to reach out to folks at Framalab.

**Comment by ElisouG** [comment]
Dear Mrazator,
Thank you very much for your quick response even though I was on a third party site.
I followed your steps, retrieved my work and saved it.
Thank you very much!
Kind regards,
Elise
