### ISSUE TITLE
BUG: No change in background color

### ISSUE THREAD

**Issue by kumar1397** [excalidraw/excalidraw#8670]
When i am trying to change the background color of the canvas by clicking on the color palet, it is not changing.
Video for preview:
https://github.com/user-attachments/assets/b2a5ca69-0f0a-4ee2-825a-77ef87d664a6
Please assign me this issue under hacktoberfest to solve.
Thank you

**Comment by Mrazator** [comment]
This is not a bug, as the background color is only applied when the starting and ending points intersect (similar to the line). We should however come up with some better UX, though likely we just cannot hide it, as a user should have an option to select the background before he draws a complex shape. If you have some ideas on how to resolve it.

**Comment by kumar1397** [comment]
ok
thank you
