### ISSUE TITLE
BUG: Lilita font face is not honored in SVG export if both Lilita and ExcaliFont are present

### ISSUE THREAD

**Issue by zsviczian** [excalidraw/excalidraw#8677]
@Mrazator 

![Image](https://github.com/user-attachments/assets/9cbc863b-364b-4d1f-8787-e704de8df0e4)

Export:
![Image](https://github.com/user-attachments/assets/51f8bd94-9829-4ef6-a957-57b42adee793)

**Comment by zsviczian** [comment]
In this case the `@font-face {font-familiy: Lilita One;...` is simply omitted from the SVG export.

**Comment by zsviczian** [comment]
seems to only happen with the combination of Lilita and ExcaliFont.
If Lilita is paired with another font or is alone the font is correctly included in the css.
If other fonts are paired with Excalifont they are also properly included.

**Comment by Mrazator** [comment]
Thanks, will check later today

**Comment by Mrazator** [comment]
Good catch! This should be it https://github.com/excalidraw/excalidraw/pull/8641/commits/183aca61042332a59c9e614e3ed45088228d29c2

**Comment by zsviczian** [comment]
I confirm https://github.com/excalidraw/excalidraw/commit/183aca61042332a59c9e614e3ed45088228d29c2 solves the issue.

I recommend looking into #8678 as well, though arguably a less burning issue..

**Comment by Mrazator** [comment]
Fixed in https://github.com/excalidraw/excalidraw/pull/8641
