### ISSUE TITLE
clearing localstorage keeps the content

### ISSUE THREAD

**Issue by lorypelli** [excalidraw/excalidraw#8679]
Reproduction steps:
1. Go to https://excalidraw.com/#json=5649116445016064,yOfExolZoMhtGnysT3-LWA
2. Try reloading the page (the content remains, as expected)
3. Open devtools and clear localstorage
4. Reload again and it still remains (at least for me)

**Comment by dwelle** [comment]
Clearing canvas through devtools isn't the official way to clear the canvas. Though it works anyway. What I assume is happening is after you clear the localStorage from devtools, you click back inside the app which triggers another autosave.

To clear canvas the proper way, you can do so from main main (top left) -> clear canvas, or simply select all -> delete.

**Comment by lorypelli** [comment]
> Clearing canvas through devtools isn't the official way to clear the canvas. Though it works anyway. What I assume is happening is after you clear the localStorage from devtools, you click back inside the app which triggers another autosave.
> 
> To clear canvas the proper way, you can do so from main main (top left) -> clear canvas, or simply select all -> delete.

I reload with `F5`, and the url doesn't include anymore `json` to take the draw

**Comment by mtolmacs** [comment]
I just tested this myself and it works as intended. Here's what I did to avoid accidentally reloading excalidraw.com right after cleaning localstorage. I use Firefox, but I'm sure you can find the browser-specific instructions for others as well:

1. Created a couple of elements in excalidraw.com and Save to... -> Shareable link
2. Cleared the canvas via Menu -> Reset the canvas, reload excalidraw and check local storage and confirm it's empty
3. Followed these instructions from[ Mozilla to clear all data](https://support.mozilla.org/en-US/kb/storage) related to excalidraw.com (this way excalidraw cannot re-save content!).
4. Went back to excalidraw.com and confirmed that the canvas is clear and localstorage is reset back to no elements (`excalidraw` property is empty array `[]`).
