### ISSUE TITLE
Command palette

### ISSUE THREAD

**Issue by j-f1** [excalidraw/excalidraw#869]
It would be great to have a VS Code/Atom style command palette opened with meta+shift+P that allows for fuzzy searching of all the available commands (maybe we could spice it up with icons, colors, and descriptions!) and keyboard-only access to everything without having to remember shortcuts.

Relatedly, similar functionality could be added to the color picker such that color names could be typed into the hex entry box.

**Comment by lipis** [comment]
That would be awesome actually :)

**Comment by j-f1** [comment]
It might also be useful to make the first element of the context menu be “Search commands…” so the palette is more easily discovered. We could also have a permanent button though.

**Comment by lipis** [comment]
I think we're going to reject this as way too crazy for a drawing app, that you need to have your hand on the mouse anyway!
