### ISSUE TITLE
BUG: Regression with image cropper - serious performance degradation when many images are in the scene

### ISSUE THREAD

**Issue by zsviczian** [excalidraw/excalidraw#8692]
#8613  introduced a major performance degradation when there are many images in the scene. Here's a sample file:

https://github.com/user-attachments/assets/4f44374d-9f14-4f89-a312-345aca3e20d0

**Comment by dwelle** [comment]
Interesting, didn't catch that. Though there are a few other issues, including SVG export, so it's not quite ready for prime time. Good to know about the perf regression, so we'll fix that before release as well!
