### ISSUE TITLE
[ISSUE] - Cannot leave the shape while drawing

### ISSUE THREAD

**Issue by sundaram-pro** [excalidraw/excalidraw#8712]
I noticed that when we draw an arrow, it is sometime impossible to complete that and the arrow streches all the way to whatever we click or move the mouse too. Please see the video for more reference

Also note that other functions inside the page like side panel and top bar also dont work

https://github.com/user-attachments/assets/1738243e-075b-4994-912a-f298ba9a10cd

**Comment by Mrazator** [comment]
You've entered the multi-point mode, to finalize the line, press `Enter` or `Esc`.

Note that if you would drag (click-down, move, click-up) instead, you would get a two-point arrow finalized automatically.
