### ISSUE TITLE
feature request: allow watching youtube videos/playlists and local videos/m3u8 while drawing

### ISSUE THREAD

**Issue by backpropogated** [excalidraw/excalidraw#8727]
i would like to request a feature that enables users to watch youtube videos, playlists, local videos, or m3u8 streams while using the drawing tool in excalidraw. 

#### current limitation:
currently, users must switch between different applications or tabs to watch videos and draw simultaneously. this can disrupt the creative flow and make it challenging to take notes or illustrate concepts while engaging with video content.

#### use case:
allowing users to view videos while drawing would greatly enhance productivity, especially for educators and content creators. for instance, a teacher could play a tutorial video in the background and annotate key points or concepts in real time, making lessons more interactive and dynamic. many people already take conspects in excalidraw, and this feature would further enhance that capability.

#### proposed solution:
- integrate a video player within excalidraw that supports youtube links, local video files, and m3u8 streams.
- allow users to resize and position the video player within the drawing canvas, so they can easily refer to the video content while drawing.

#### why this matters:
this feature would significantly improve the user experience by combining video content consumption with real-time drawing. educators, students, and content creators often use videos as learning tools; being able to annotate or illustrate alongside would enhance comprehension and retention. 

by implementing this functionality, excalidraw can cater to a broader audience and become a versatile platform for interactive learning and collaboration, ultimately leading to more engaging and effective sessions.

thank you for considering this request! i believe that adding this feature would not only enhance individual workflows but also elevate the overall value of excalidraw as a powerful educational tool.

**Comment by Mrazator** [comment]
Hi, you can play youtube videos right inside the scene.

https://github.com/user-attachments/assets/7d591476-1671-4f55-84e1-2bf0ab79096f

https://excalidraw.com/#json=EhtGXhZk1EG3CGdpSAFvM,RpzyRq4xLNSwRip4ZZqvIA

In it's also possible to screen share now, i.e. in case you would like to have the video synced for all users.

https://x.com/excalidraw/status/1841886708008419572
