### ISSUE TITLE
Bug: SVG Scaling issue with image cropping

### ISSUE THREAD

**Issue by zsviczian** [excalidraw/excalidraw#8729]
@dwelle, legacy drawings that include SVGs without the width and height attribute get scaled incorrectly. Here's an example: [Untitled-2024-10-28-2103.excalidraw.zip](https://github.com/user-attachments/files/17548411/Untitled-2024-10-28-2103.excalidraw.zip)

Load this excalidraw to https://staging.excalidraw.com and resize the svg.

re: #8710

**Comment by dwelle** [comment]
Will take a look tomorrow. But it doesn't seem related to #8710, rather the #8613 itself as it can be reproduced there already: https://excalidraw-gfa5xk5ry-excalidraw.vercel.app/#json=OgEtPh49zeqt6__0Zfsk7,QB_FZ3u4noVBAeLYa6MXSA
