### ISSUE TITLE
# 🐛 No Recent Drawings or History Option – Feature Needed

### ISSUE THREAD

**Issue by santyadavcoder** [excalidraw/excalidraw#8738]
**Issue raised by:** `santyadavcoder`

---

#### Problem
Currently, there’s no way to access recent drawings or any history in Excalidraw. If I close my browser, I lose my work and can’t pick up where I left off. This affects workflow, especially when working on multiple drawings.

#### What I’d Love to See
- A **Recent Drawings** or **History** option to access my previous sessions quickly.
- This would help users continue or reference past work without recreating or saving everything manually.

#### Steps to Reproduce
1. Open Excalidraw, create a drawing.
2. Close the browser/tab.
3. Reopen Excalidraw – there’s no option to access previous work.

---

### 🌟 Suggestion
Implement a basic **Recent Drawings** feature that could:
- Use local storage for recent sessions.
- (Or even better!) Use cloud storage if supported, so work is accessible across devices.

Thanks for considering this!

**Comment by santyadavcoder** [comment]
i lost my recent work flow so please imliment this feauter

**Comment by dwelle** [comment]
Hi. The data should be saved to browser automatically, so closing/reopening the tab/browser should load your previous drawing.

If that doesn't happen, you must be either working in the Incognito Mode, or have some extension that auto-clear browser data (if you didn't do so yourself).

What browser are you using?

**Comment by santyadavcoder** [comment]
i use chrome browser  😃

i am mentor i use excalidraw for teaching purpose [but i think they need to enable the future save the data not only in local machine but for cloud storage it will enhance user experience 🫡
