### ISSUE TITLE
Can I use the exdalidraw in Nodejs server side?

### ISSUE THREAD

**Issue by dingiyan** [excalidraw/excalidraw#8747]
Hello, I want to design in browsers and save the excalidraw json schema to server's database, then, I want to use nodejs server side app render a png image by json schema.
I view the doc and npm packages, but not found about this feature.
please help me. thanks

**Comment by Mrazator** [comment]
You are likely looking for `https://www.npmjs.com/package/@excalidraw/utils`.

You could use `exportToBlob` server-side to render into PNG, but you would need to provide a server-side canvas implementation, implementing APIs like https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob. Also, you could possibly run the whole thing inside Puppeteer - might be slow but good enough.

Another option is to run `exportToSvg` and then render into PNG with `https://github.com/linebender/resvg`, though it has some limitations on its own, like registering .ttf for each font-family, to render fonts properly.

Either way, it's not completely out-of-the-box.

**Comment by pranavmappoli** [comment]
@Mrazator I think exportToBlob also wont work in server side right ?
So , is there any exports work in server side ?
