### ISSUE TITLE
Feature request: text styling within same block

### ISSUE THREAD

**Issue by marcospgp** [excalidraw/excalidraw#8752]
It would be great to be able to format text separately within the same block, so that multiple blocks aren't required for something like this:

![Image](https://github.com/user-attachments/assets/986a6ee2-3b61-401a-8f9e-b5dc5c2f9abf)

One can imagine many other use cases such as highlighting text with different colors, underlining, and so on

**Comment by Mrazator** [comment]
We will have it at some point. Closing as duplicate of https://github.com/excalidraw/excalidraw/issues/5138.
