### ISSUE TITLE
Gets super laggy the moment dark mode is on.

### ISSUE THREAD

**Issue by ShimShon1** [excalidraw/excalidraw#8780]
Everything in the canvas becomes super laggy and unresponsive the moment I switch to dark mode.
happening on chrome, firefox and firefox developer edition. least severe one is chrome but also super laggy.

 https://github.com/user-attachments/assets/89f8e309-b41e-42ad-b61a-a42c97344fa3

**Comment by Mrazator** [comment]
Let's track it here https://github.com/excalidraw/excalidraw/issues/7332
