### ISSUE TITLE
react dispatcher issue

### ISSUE THREAD

**Issue by SohamChatterG** [excalidraw/excalidraw#8781]
not compatible with

    "next": "^15.0.3",
    "next-themes": "^0.3.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0",

**Comment by astongemmy** [comment]
I'm having a similar experience when i use the package combination below;

```
"dependencies": {
    "@excalidraw/excalidraw": "0.17.3",
    "next": "15.0.3",
    "react": "^18.3.1",
    "react-dom": "^18.3.1"
  }
```

However, downgrading `@excalidraw/excalidraw` to version `0.17.0` solves the problem.

```
"dependencies": {
    "@excalidraw/excalidraw": "0.17.0",
    "next": "15.0.3",
    "react": "^18.3.1",
    "react-dom": "^18.3.1"
  }
```

**Comment by xjasonsong** [comment]
@astongemmy got stuck on this issue for 1 hour, you are a life saver, thank you!

**Comment by havocthehobbit** [comment]
got the same issue when I was migrating to React 19  from 18.2.0 . @astongemmy 's , workaround solution of downgrading to "@excalidraw/excalidraw": "0.17.0", worked for me too .

**Comment by dwelle** [comment]
merging into https://github.com/excalidraw/excalidraw/issues/8923
