### ISSUE TITLE
[feat] Add Grouping feature

### ISSUE THREAD

**Issue by Arslan2214** [excalidraw/excalidraw#8797]
At 1st place, I can't understand why there is no grouping button, I mean most of time we need it.

## Problem, I face
Most of time while, I'm teaching my students I need to group two or more shapes together, So I can move then as single entity. But I was amazed to watch that there is no such feature.

## Some Relatable examples
Well, There are many example of this feature, Most commonly it is available at **MS Office** and in **Canva**. While it is also available in most others tools.

It will be huge, If someone add this feature. 🙂

**Comment by samuelzxu** [comment]
Hi! I think you actually can group shapes together to move them together, it's just shift+clicking all the objects you want to select. Alternatively you can use the select tool to select multiple shapes in a rectangle.

**Comment by Mrazator** [comment]
Groups are already in:

https://github.com/user-attachments/assets/c1626c6d-8dc8-437b-b49f-2cb69b2613a4
