### ISSUE TITLE
Loss of focus after creating a rectangle

### ISSUE THREAD

**Issue by ahmadawais** [excalidraw/excalidraw#8806]
hey folks, awesome project. 

Recently, started having this issue which has made it hard to work with excalidraw.

BEFORE: What used to work

1. Press `r` and create a rectangle
2. Press `enter` and add text in it

NOW: keyboard access is not great now
1. Press `r` and create a rectangle
2. Press `enter` nothing happens
3. Try to select the box and it starts creating new rectangle coz we had pressed `r`
4. Press `v` and then select the box and then press `enter` to start adding text

As you can see this is a major pain when using boxes and adding text to explain something — especially when you're doing it live in a video

**Comment by Mrazator** [comment]
Do you have "lock" enabled?

![Image](https://github.com/user-attachments/assets/e441230e-800c-4150-90ad-3d69cbf31468)

**Comment by ahmadawais** [comment]
You're absolutely right. I didn't know that. Thanks a lot.
