### ISSUE TITLE
Hyperlink 404 not found

### ISSUE THREAD

**Issue by AdityaPGit** [excalidraw/excalidraw#8814]
The shield icon on the bottom right corner shows 404 error on clicking. [This](https://plus.excalidraw.com/blog/end-to-end-encryption) is the link of the button it points to

![Image](https://github.com/user-attachments/assets/0c181bc1-a3fa-4ec7-bcab-8ce7d19389a1)

![Image](https://github.com/user-attachments/assets/4ebb8060-d93a-4044-bb51-dfbd15d778d0)

**Comment by dwelle** [comment]
Fixed, thanks for the report!
