### ISSUE TITLE
Image crop: confusion in resizing image crop area and image size

### ISSUE THREAD

**Issue by imanzaker** [excalidraw/excalidraw#8821]
By starting cropping an image it gets us a rectangle that has a sharp blue sign at every corner so we can resize this rectangle to determine what area of the image is going to be in the cropped image. We can resize this area with mouse and the properties pan shows the exact width and height of the crop area, but when we want to change its Dimensions directly in the properties pan it changes the original image dimensions, not the crop area rectangle.
https://github.com/user-attachments/assets/51a749e3-1f0a-4ee4-9056-58d163a24115

**Comment by Mrazator** [comment]
cc @ryan-di
