### ISSUE TITLE
Reset canvas crashes

### ISSUE THREAD

**Issue by Mrazator** [excalidraw/excalidraw#8840]
https://github.com/user-attachments/assets/6a093070-61b3-4c65-9756-58b177d80a77

**Reproduction**
1. Open Arc / Chrome with the below version
2. Go to excalidraw.com
3. Reset canvas

**Actual result**
- Incognito tab ends up with a white screen.
- Regular tab ends up crashing. 

M1 MacOS:
- Arc with Chromium Engine Version 131.0.6778.70
- Chrome with 131.0.6778.71

**Comment by dwelle** [comment]
Can't repro.

Chrome Versions tested:

129.0.6668.101 (Official Build) (arm64)
131.0.6778.70 (Official Build) (x86_64)
131.0.6778.86 (Official Build) (arm64)

**Comment by aryyh** [comment]
Also have this issue. Chrome tab crashes with error code 5, including incognito mode.
- Chrome Version 131.0.6778.86 (Official Build) (arm64)
- MacOS 14.6.1 (23G93)
