### ISSUE TITLE
Pressing alt while moving an element creates duplicate

### ISSUE THREAD

**Issue by Jonhyog** [excalidraw/excalidraw#8856]
If you press the Alt key while moving an element, a duplicate is created at the element's initial position. One might encounter this problem while enabling snapping (Alt + s) and moving an element at the same time.

Spamming Alt while moving the element only creates a duplicate at the first time alt is pressed.

Also, if you left click on the element, hold down the mouse button but don't move your mouse and then press Alt it does not happen.

![Image](https://github.com/user-attachments/assets/3d41588a-5b2b-4364-a0da-554efdf811c2)

**Comment by ritk20** [comment]
Duplication on alt + drag is a desired behaviour.

I can see how it will affect snapping enabling, but if you wish to snap while dragging, I think you can just use Ctrl key.
