### ISSUE TITLE
Opacity option and Undo/Redo bug

### ISSUE THREAD

**Issue by oybekx3d** [excalidraw/excalidraw#8861]
Hi. If I set Opacity from full to none, all steps are recorded in Undo Redo actions, maybe change state after user releases the mouse button [ might need to add preview function, where it does change state temporarily while user slides the slider ]. Good luck, have a nice day

**Comment by Mrazator** [comment]
Hi, it shouldn't be exactly every single step recorded as there are only 10 steps in the opacity slider. Though I agree, there might still be too many.

**Comment by oybekx3d** [comment]
> Hi, it shouldn't be exactly every single step recorded as there are only 10 steps in the opacity slider. Though I agree, there might still be too many.

Yes theres like 10 steps or so but its quite inconvinient, I slid it from none to full but still when I press undo it slowly changes which is probably not intended
