### ISSUE TITLE
Use 3D touch/long press to open context menu on mobile

### ISSUE THREAD

**Issue by j-f1** [excalidraw/excalidraw#887]
Part of #138. We should use something like [Pressure.js](https://pressurejs.com) to gracefully handle devices old and new that don’t support force.

**Comment by dwelle** [comment]
On Android long-press already opens context menu. Not on iOS? As for 3D-touch, didn't Apple deprecated it (which would make supporting it not that useful, in the long run).

**Comment by j-f1** [comment]
It has been removed from the newest devices, but we should support it for the devices that have it. Long press does not open the context menu.

**Comment by MehediH** [comment]
@j-f1 Would love to look into this and try to implement it if you'd like!

**Comment by j-f1** [comment]
That would be great @MehediH!

**Comment by MehediH** [comment]
@j-f1 Hey! please check out #1769, let me know what you think! I ended up not using Pressure.js, and added basic support instead so it at least triggers the context menu on long-press on iPhones. The context menu also seems to be resulting in the satisfying haptic feedback you get w/ Taptic Engine on the modern iPhones.
