### ISSUE TITLE
For configurable AI functions, maybe you can try this fork

### ISSUE THREAD

**Issue by KwokKwok** [excalidraw/excalidraw#8888]
For configurable AI functions, maybe you can try this fork
repo is here: https://github.com/KwokKwok/excalidraw
or try it online:  https://draw.kwok.ink

for now, you can specify baseUrl、VLM、LLM

![Image](https://github.com/user-attachments/assets/e5c4aa88-65b0-4698-b82a-a72b3d3cbea3)

**Comment by Raboo** [comment]
Why an unmaintained fork instead of a pull request?
