### ISSUE TITLE
Option to lock sizes within a group

### ISSUE THREAD

**Issue by AdityaPGit** [excalidraw/excalidraw#8893]
Currently, when a group of items is scaled, all items inside the group are scaled proportionally. There is no feature to lock the dimensions of specific items within the group.

**Feature Request:**
Add an option to lock the dimensions of individual items in a group so they remain unchanged during group scaling. This would provide more flexibility when working with grouped elements, especially when certain items need to maintain their original size.

**Comment by Mrazator** [comment]
Isn't ungrouping, scaling just the rectangle, and grouping again essentially what you want?

**Comment by AdityaPGit** [comment]
In the GIF, I meant that if you scale a group of items, everything inside the group scales together. There's no feature to "lock" an item's size, so even if you want one item to stay the same, it will still scale when the group does.

**Comment by AdityaPGit** [comment]
Should I delete this issue and recreate one? Seems kinda confusing I guess

**Comment by AdityaPGit** [comment]
My issue was very confusuing so I updated it. I hope it is much understandable now
