### ISSUE TITLE
How does the DOCKER version save files on the server?

### ISSUE THREAD

**Issue by gamersky998** [excalidraw/excalidraw#8899]
Because I change presentations anytime and anywhere, I hope that I can directly access the link to see the notes I have written before, instead of having to manually load local files every time.

**Comment by Mrazator** [comment]
By default excalidraw is purely local, meaning it does not store anything on the server. Storing to the server is by default enabled in shared scenes, but you would need to roll out your own collaboration to do that. There have been several discussions on this topic https://github.com/excalidraw/excalidraw/issues/1772.
