### ISSUE TITLE
420 errors, though the application is working

### ISSUE THREAD

**Issue by scalenow** [excalidraw/excalidraw#8906]
Why am I  getting  420 errors, though the application is working 

followed the commnd 

https://docs.excalidraw.com/docs/introduction/development

Clone the repo
git clone https://github.com/excalidraw/excalidraw.git

Install the dependencies
yarn

Start the server

yarn start

regards
Abhi

ERROR(TypeScript)  Argument of type 'readonly NonDeletedExcalidrawElement[]' is not assignable to parameter of type 'ElementsMapOrArray'.
  Type 'readonly NonDeletedExcalidrawElement[]' is not assignable to type 'readonly ExcalidrawElement[]'.
    Type 'NonDeletedExcalidrawElement' is not assignable to type 'ExcalidrawElement'.
      Type 'Readonly<{ id: string; x: number; y: number; strokeColor: string; backgroundColor: string; fillStyle: FillStyle; strokeWidth: number; strokeStyle: StrokeStyle; roundness: { ...; } | null; ... 15 more ...; customData?: Record<...> | undefined; }> & { ...; } & { ...; }' is not assignable to type 'ExcalidrawElement'.
        Type 'Readonly<{ id: string; x: number; y: number; strokeColor: string; backgroundColor: string; fillStyle: FillStyle; strokeWidth: number; strokeStyle: StrokeStyle; roundness: { ...; } | null; ... 15 more ...; customData?: Record<...> | undefined; }> & { ...; } & { ...; }' is not assignable to type 'ExcalidrawSelectionElement'.
          Property 'index' is missing in type 'Readonly<{ id: string; x: number; y: number; strokeColor: string; backgroundColor: string; fillStyle: FillStyle; strokeWidth: number; strokeStyle: StrokeStyle; roundness: { ...; } | null; ... 15 more ...; customData?: Record<...> | undefined; }> & { ...; } & { ...; }' but required in type 'Readonly<{ id: string; x: number; y: number; strokeColor: string; backgroundColor: string; fillStyle: FillStyle; strokeWidth: number; strokeStyle: StrokeStyle; roundness: { ...; } | null; ... 16 more ...; customData?: Record<...> | undefined; }>'.
 FILE  /root/miniconda3/envs/excalidraw/excalidraw/packages/excalidraw/tests/test-utils.ts:204:5

    202 |   const { h } = window;
    203 |   const selectedElementIds = getSelectedElements(
  > 204 |     h.app.getSceneElements(),
        |     ^^^^^^^^^^^^^^^^^^^^^^^^
    205 |     h.state,
    206 |   ).map((el) => el.id);
    207 |   const ids = elements

 ERROR(TypeScript)  Argument of type 'readonly ExcalidrawElement[]' is not assignable to parameter of type 'readonly NonDeletedExcalidrawElement[]'.
  Type 'ExcalidrawElement' is not assignable to type 'NonDeletedExcalidrawElement'.
 FILE  /root/miniconda3/envs/excalidraw/excalidraw/packages/excalidraw/tests/zindex.test.tsx:111:9

    109 |       ...selectGroupsForSelectedElements(
    110 |         { ...h.state, ...appState, selectedElementIds },
  > 111 |         h.elements,
        |         ^^^^^^^^^^
    112 |         h.state,
    113 |         null,
    114 |       ),

[TypeScript] Found 420 errors. Watching for file changes.

**Comment by ryan-di** [comment]
In the editor, for elements, we have the basic type `ExcalidrawElement`, but on top of it we also have more specific types like `NonDeletedExcalidrawElement`. Please make sure that you check out the types, what they mean and how they are intended to be used, and provide the right types (or type cast) accordingly. 

You could also join our [discord channel](https://discord.com/invite/UexuTaE), where you could refer to past questions and get help from other developers using the Excalidraw package there.

**Comment by scalenow** [comment]
@ryan-di  just installed excalidraw and recieved 426 errors in the console though the application running fine .Can you please help.Sorry did not understnad your message above     129 |
    130 |     const searchInput = await querySearchInput();
    131 |

 ERROR(TypeScript)  Property 'state' does not exist on type 'App'.
 FILE  /root/miniconda3/envs/excalidraw/excalidraw/excalidraw/packages/excalidraw/tests/search.test.tsx:137:20

    135 |
    136 |     await waitFor(() => {
  > 137 |       expect(h.app.state.searchMatches.length).toBe(1);
        |                    ^^^^^
    138 |       expect(h.app.state.searchMatches[0]?.matchedLines?.length).toBe(4);
    139 |     });
    140 |

 ERROR(TypeScript)  Property 'state' does not exist on type 'App'.
 FILE  /root/miniconda3/envs/excalidraw/excalidraw/excalidraw/packages/excalidraw/tests/search.test.tsx:138:20

    136 |     await waitFor(() => {
    137 |       expect(h.app.state.searchMatches.length).toBe(1);
  > 138 |       expect(h.app.state.searchMatches[0]?.matchedLines?.length).toBe(4);
        |                    ^^^^^
    139 |     });
    140 |
    141 |     updateTextEditor(searchInput, "ext spli");

 ERROR(TypeScript)  Property 'state' does not exist on type 'App'.
 FILE  /root/miniconda3/envs/excalidraw/excalidraw/excalidraw/packages/excalidraw/tests/search.test.tsx:144:20

    142 |
    143 |     await waitFor(() => {
  > 144 |       expect(h.app.state.searchMatches.length).toBe(1);
        |                    ^^^^^
    145 |       expect(h.app.state.searchMatches[0]?.matchedLines?.length).toBe(6);
    146 |     });
    147 |   });

 ERROR(TypeScript)  Property 'state' does not exist on type 'App'.
 FILE  /root/miniconda3/envs/excalidraw/excalidraw/excalidraw/packages/excalidraw/tests/search.test.tsx:145:20

    143 |     await waitFor(() => {
    144 |       expect(h.app.state.searchMatches.length).toBe(1);
  > 145 |       expect(h.app.state.searchMatches[0]?.matchedLines?.length).toBe(6);
        |                    ^^^^^
    146 |     });
    147 |   });
    148 | });

 ERROR(TypeScript)  Argument of type 'readonly NonDeletedExcalidrawElement[]' is not assignable to parameter of type 'ElementsMapOrArray'.
  Type 'readonly NonDeletedExcalidrawElement[]' is not assignable to type 'readonly ExcalidrawElement[]'.
    Type 'NonDeletedExcalidrawElement' is not assignable to type 'ExcalidrawElement'.
      Type 'Readonly<{ id: string; x: number; y: number; strokeColor: string; backgroundColor: string; fillStyle: FillStyle; strokeWidth: number; strokeStyle: StrokeStyle; roundness: { ...; } | null; ... 15 more ...; customData?: Record<...> | undefined; }> & { ...; } & { ...; }' is not assignable to type 'ExcalidrawElement'.
        Type 'Readonly<{ id: string; x: number; y: number; strokeColor: string; backgroundColor: string; fillStyle: FillStyle; strokeWidth: number; strokeStyle: StrokeStyle; roundness: { ...; } | null; ... 15 more ...; customData?: Record<...> | undefined; }> & { ...; } & { ...; }' is not assignable to type 'ExcalidrawSelectionElement'.
          Property 'index' is missing in type 'Readonly<{ id: string; x: number; y: number; strokeColor: string; backgroundColor: string; fillStyle: FillStyle; strokeWidth: number; strokeStyle: StrokeStyle; roundness: { ...; } | null; ... 15 more ...; customData?: Record<...> | undefined; }> & { ...; } & { ...; }' but required in type 'Readonly<{ id: string; x: number; y: number; strokeColor: string; backgroundColor: string; fillStyle: FillStyle; strokeWidth: number; strokeStyle: StrokeStyle; roundness: { ...; } | null; ... 16 more ...; customData?: Record<...> | undefined; }>'.
 FILE  /root/miniconda3/envs/excalidraw/excalidraw/excalidraw/packages/excalidraw/tests/test-utils.ts:204:5

    202 |   const { h } = window;
    203 |   const selectedElementIds = getSelectedElements(
  > 204 |     h.app.getSceneElements(),
        |     ^^^^^^^^^^^^^^^^^^^^^^^^
    205 |     h.state,
    206 |   ).map((el) => el.id);
    207 |   const ids = elements

 ERROR(TypeScript)  Argument of type 'readonly ExcalidrawElement[]' is not assignable to parameter of type 'readonly NonDeletedExcalidrawElement[]'.
  Type 'ExcalidrawElement' is not assignable to type 'NonDeletedExcalidrawElement'.
 FILE  /root/miniconda3/envs/excalidraw/excalidraw/excalidraw/packages/excalidraw/tests/zindex.test.tsx:111:9

    109 |       ...selectGroupsForSelectedElements(
    110 |         { ...h.state, ...appState, selectedElementIds },
  > 111 |         h.elements,
        |         ^^^^^^^^^^
    112 |         h.state,
    113 |         null,
    114 |       ),
