### ISSUE TITLE
Request to have the precise setting functions for image size and interval added.

### ISSUE THREAD

**Issue by PShiYou** [excalidraw/excalidraw#8911]
Hello, I really like the hand-drawn style of Excalidraw. These past few days, I wanted to draw a precise-sized picture. When using it, I found that I couldn't directly set the exact length and width of the image and the precise interval between two images.

**Comment by ryan-di** [comment]
Hi @PShiYou Glad that you're enjoying Excalidraw! There are a couple of things you can do:

You can use the stats panel to precisely manipulate a shape or shapes (using `option + /` or select from the context menu when you right click on an empty part of the canvas with no elements selected)

In addition, you can also use snapping to align elements (which you can toggle using `option + s`). 

To discover "hidden" functions, we suggest that you take a look at the help dialog or search for a particular function that you might have in mind in the command palette (shortcut: `cmd + /`).
