### ISSUE TITLE
Feature Request: Manage Multiple Canvases and Folders

### ISSUE THREAD

**Issue by Abh1noob** [excalidraw/excalidraw#8934]
It would be great to have a feature for managing multiple canvases and organizing them into folders. This could include:
- A dashboard or list view for canvases.
- Folder creation, renaming, and deletion.

Benefits
This feature would enhance organization, streamline workflows for multi-canvas projects, and improve collaboration by making it easier to manage related sketches.

We can manage this in browser storage itelf

Would love to hear thoughts on this idea and I would like to contribute myself towards this

**Comment by Mrazator** [comment]
> A dashboard or list view for canvases.
Folder creation, renaming, and deletion.

Actually, we have all of this inside https://plus.excalidraw.com/. There are no plans currently to extend the editor, other than possibly adding a tabs support https://github.com/excalidraw/excalidraw/issues/1543.
