### ISSUE TITLE
Export as PNG does not copy the Dark theme when exporting.

### ISSUE THREAD

**Issue by theashishmaurya** [excalidraw/excalidraw#8944]
## Reproduction:
- Toggle to dark mode.
- Try creating a simple text or anything.
- Select the Content.
- Right-click and click on the export as PNG. 

## ScreenShot
1- The content on canvas.
<img width="490" alt="Image" src="https://github.com/user-attachments/assets/f9a09fb1-4d56-4907-858c-e615a4d43ee7" />

2- The exported Image
![Image](https://github.com/user-attachments/assets/1ca885fb-5aa9-4ecb-b67d-7742a44565a9)

**Comment by dwelle** [comment]
Export theme (which can be toggled in the Export dialog from main menu) is separate from UI theme. But we're getting enough complaints we'll likely be changing this.

**Comment by theashishmaurya** [comment]
Closing this issue as it got solved using this, Thanks
![Image](https://github.com/user-attachments/assets/e67e2599-2997-4bb3-8f9c-7913c96d2e41)

**Comment by RafaelZasas** [comment]
@theashishmaurya  This does not work when exporting slides as png.
That would be great.
