### ISSUE TITLE
Search text in the canvas

### ISSUE THREAD

**Issue by jxs1211** [excalidraw/excalidraw#8950]
I have a big canvas including lots of pic and text, how can I search text I want efficiently in excalidraw?

**Comment by ryan-di** [comment]
Hey @jxs1211, you could search text on canvas with "Find on canvas", which you can toggle either by searching for it in the command palette "cmd + /" or with toggle it directly with "cmd + f".

**Comment by jxs1211** [comment]
> Hey [@jxs1211](https://github.com/jxs1211), you could search text on canvas with "Find on canvas", which you can toggle by searching for it in the command palette ("cmd + /") or open it directly with "cmd + f".

Cool, I found it, thank you for your help.

**Comment by ryan-di** [comment]
You're welcome!
