### ISSUE TITLE
Issue with Revoking Shared Links or Access

### ISSUE THREAD

**Issue by theia13** [excalidraw/excalidraw#8953]
I'm encountering an issue with revoking shared links or access in Excalidraw. After sharing a file via a link or through live collaboration, there doesn't seem to be a clear or effective way to remove or revoke access for others who have the link or are part of the session.

Steps to Reproduce
1. Create or open an Excalidraw file.
2. Share the file using the "Share Link" or "Live Collaboration" feature.
3. Attempt to revoke access or disable the sharing link.

**Comment by dwelle** [comment]
Yes, currently the links only can be deleted by contacting us on `support@excalidraw.com` with the link id (the key, which is after the comma, can be omitted: `#json=id,key`)

**Comment by theia13** [comment]
> Yes, currently the links only can be deleted by contacting us on `support@excalidraw.com` with the link id (the key, which is after the comma, can be omitted: `#json=id,key`)

Thank you for your prompt response to my concern. I appreciate your help in addressing the issue.
