### ISSUE TITLE
Put the toolbar to the center of the empty area instead of the actual center.

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw#896]
<img width="832" alt="Screenshot 2020-03-10 at 1 50 32 AM" src="https://user-images.githubusercontent.com/125676/76267020-0f420480-6272-11ea-817f-d4268c735b52.png">

**Comment by j-f1** [comment]
Do we want to center the whole shebang or just center the Island and tack the lock onto the side?

**Comment by nanot1m** [comment]
Hey @lipis 
Can you clarify why the toolbar should be shifted to the right?
Currently we have 3 col layout
![excalidraw-202031021757](https://user-images.githubusercontent.com/9278185/76270523-cee48580-6275-11ea-809c-a4eae24a4602.png)

And if we will move to 2 columns, toolbar would be floating somewhere in the right side
![excalidraw-202031021757-2](https://user-images.githubusercontent.com/9278185/76270595-0a7f4f80-6276-11ea-96de-7846c3a6ac28.png)

**Comment by nanot1m** [comment]
Maybe if we stick the shape selector to the right layout would be more balanced
![excalidraw-202031021757-3](https://user-images.githubusercontent.com/9278185/76270717-7a8dd580-6276-11ea-9b78-c2a163049a1d.png)

**Comment by dwelle** [comment]
Putting the shapes to the right would mean you need to move cursor & eyes from one end of the screen to the other. Not good for larger screens.
