### ISSUE TITLE
Automatically center on the content when connecting to a shared room

### ISSUE THREAD

**Issue by petehunt** [excalidraw/excalidraw#899]
If you're joining a shared room, people might be drawing on parts of the canvas outside of the viewport. It would be nice to center the canvas on the drawing on page load so users don't get confused.

**Comment by dwelle** [comment]
Center on content in general (as we currently do on load from file/url), or center on what the other user(s) are drawing?

**Comment by petehunt** [comment]
i think centering on the content in general as we already do would be good enough. not sure though :)
