### ISSUE TITLE
Rendering and export are broken when a save file contains a "selection" element with non-zero size

### ISSUE THREAD

**Issue by sompylasar** [excalidraw/excalidraw#900]
See demo video (sorry for the FPS, had to convert to GIF):
![excalidraw-broken-20200310](https://user-images.githubusercontent.com/498274/76334994-189e9180-62b1-11ea-8642-443de0cdf07d.gif)

After bisecting to 5256096d76be4685d3a6f06e2be4926d0b0a9def I found out that the culprit is this `context.translate(` call in this `renderElement` function. It applies the translation to the canvas when the caller's loop over elements encounters a "selection" element, but does not revert the translation back after drawing the selection, so all the elements in the element array preceding the non-zero-size "selection" element remain on their positions, and the following ones get translated.
```
export function renderElement(
  element: ExcalidrawElement,
  rc: RoughCanvas,
  context: CanvasRenderingContext2D,
  renderOptimizations: boolean,
  sceneState: SceneState,
) {
  const generator = rc.generator;
  switch (element.type) {
    case "selection": {
      context.translate(
        element.x + sceneState.scrollX,
        element.y + sceneState.scrollY,
      );
      const fillStyle = context.fillStyle;
      context.fillStyle = "rgba(0, 0, 255, 0.10)";
      context.fillRect(0, 0, element.width, element.height);
      context.fillStyle = fillStyle;
      break;
    }
```

Then I found such a "selection" element in the save file I was loading which had one "selection" element with "height" of 1 (not zero):
```
  {
      ...
      "type": "selection",
      "x": 219,
      "y": 642,
      "width": 0,
      "height": 1,
      ...
    },
```

Looks like that code triggered because this other piece of code did not filter out such a "selection" element when the file was restored via `restore` in `restore.ts`:
```
export function isInvisiblySmallElement(element: ExcalidrawElement): boolean {
  if (element.type === "arrow" || element.type === "line") {
    return element.points.length < 2;
  }
  return element.width === 0 && element.height === 0;
}
```

A separate question is how such a non-zero-size "selection" element got into the save file (and then to the localStorage), and what is the purpose of this translation when drawing a selection.

"Broken" save file (contrived to highlight the issue, don't mind repeated "seed" and almost-repeated "id"s):
```
{
  "type": "excalidraw",
  "version": 1,
  "source": "https://excalidraw.com",
  "elements": [
    {
      "id": "6S5FSXXsnaIrNVIUavJb0",
      "type": "rectangle",
      "x": -600,
      "y": -600,
      "width": 200,
      "height": 600,
      "strokeColor": "#e60000",
      "backgroundColor": "#e60000",
      "fillStyle": "hachure",
      "strokeWidth": 1,
      "roughness": 1,
      "opacity": 100,
      "seed": 549830127,
      "points": []
    },
    {
      "id": "zfthBG-S3gUqjbJ26R8If",
      "type": "selection",
      "x": 200,
      "y": 500,
      "width": 0,
      "height": 1,
      "strokeColor": "#495057aa",
      "backgroundColor": "#087f5b",
      "fillStyle": "solid",
      "strokeWidth": 2,
      "roughness": 1,
      "opacity": 100,
      "seed": 595091438,
      "points": []
    },
    {
      "id": "6S5FSXXsnaIrNVIUavJb1",
      "type": "rectangle",
      "x": -500,
      "y": -500,
      "width": 300,
      "height": 400,
      "strokeColor": "#e67700",
      "backgroundColor": "#e67700",
      "fillStyle": "hachure",
      "strokeWidth": 1,
      "roughness": 1,
      "opacity": 100,
      "seed": 549830127,
      "points": []
    },
    {
      "id": "6S5FSXXsnaIrNVIUavJb2",
      "type": "rectangle",
      "x": -100,
      "y": -200,
      "width": 400,
      "height": 200,
      "strokeColor": "#e67700",
      "backgroundColor": "#e67700",
      "fillStyle": "hachure",
      "strokeWidth": 1,
      "roughness": 1,
      "opacity": 100,
      "seed": 549830127,
      "points": []
    },
    {
      "id": "6S5FSXXsnaIrNVIUavJb3",
      "type": "rectangle",
      "x": -50,
      "y": -150,
      "width": 400,
      "height": 200,
      "strokeColor": "#e67700",
      "backgroundColor": "#e67700",
      "fillStyle": "hachure",
      "strokeWidth": 1,
      "roughness": 1,
      "opacity": 100,
      "seed": 549830127,
      "points": []
    }
  ],
  "appState": {
    "viewBackgroundColor": "#ffffff"
  }
}
```

CC @vjeux

**Comment by vjeux** [comment]
cc @dwelle

**Comment by vjeux** [comment]
Thanks so much for the detailed investigation!!

We had a bunch of issues with selection not being terminated correctly, for example if you alt tab while selecting. Then you get an empty one in the state that would never go away.

We're no longer storing selection as part of the elements list so that no longer an issue but we should filter out the selection object from saved files that were affected.

**Comment by dwelle** [comment]
@sompylasar thanks for the report. While this has now been fixed, it's not yet released since we've moved to a different release strategy (not directly from `master`). Will let you know once this lands.
