### ISSUE TITLE
Right clicking while on the canvas messes up selection

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#91]
If we right click on the canvas, then I think that onmouseup isn't triggered and we're no longer deleting the selection object.

![image](https://user-images.githubusercontent.com/197597/71756244-9a9eb400-2e43-11ea-99da-c0d32bb5cb8d.png)

Maybe we should listen to context menu as well and clean things up there. Worst case, would be nice to clean up on mousedown if we haven't received mouseup.

**Comment by nanot1m** [comment]
![excalidraw-5](https://user-images.githubusercontent.com/9278185/71764521-9e493e00-2f0a-11ea-9c7b-3731ddd47811.png)

I'll try to fix it
