### ISSUE TITLE
Remote pointers not cleared on user disconnect

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#910]
Steps:

1. open https://excalidraw-git-roomdialog.excalidraw-team.now.sh/#room=42eee5595d9ed7ad7ec8,1nh-ao-36E9Q50THWN7XiA in 2 tabs
2. close the 2nd tab
3. remote pointer persisted in 1st tab

**Comment by vjeux** [comment]
Looks like art though :p
![image](https://user-images.githubusercontent.com/197597/76452004-9b951a00-638d-11ea-954c-2c96815e4bc1.png)

**Comment by vjeux** [comment]
This has been fixed in master
