### ISSUE TITLE
Display collaborator count

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#911]
![](https://user-images.githubusercontent.com/197597/76439401-962dd480-6379-11ea-9b94-6b3b807d5c1f.png)

**Comment by j-f1** [comment]
Alternate proposal:

<img src="https://user-images.githubusercontent.com/25517624/76453513-61d20c80-63a9-11ea-9531-ff38434b8b0b.png" width=95>

**Comment by vjeux** [comment]
@j-f1 I'm not sure if it's a joke or not. In any case, I believe that the UI of excalidraw should not look hand-drawn. I want to make sure that there's a clear separation between the UI (not hand drawn) and the content (hand drawn).

**Comment by dwelle** [comment]
I'm pretty sure it was a quick mock up. I wouldn't take it on face value :).

**Comment by j-f1** [comment]
Yep, just a mock-up of using a badge style.
