### ISSUE TITLE
Collaborators count sometimes off by one

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#914]
Can't repro, but often enough when I start a session the `collaboratorsCount` is set to `2`, while no one else is connected.

I've checked the codebase, and the [remote server](https://github.com/excalidraw/excalidraw-room/blob/master/index.ts), but can't find any glaring mistake.

So keep an eye out.

**Comment by dwelle** [comment]
I'm getting often now when connecting/disconnecting (closing/reopening/refreshing tabs). Seems like there maybe some bug in the socket implem. Dunno.

**Comment by vjeux** [comment]
Have you seen this again since all the changes?

**Comment by dwelle** [comment]
Here's steps to reproduce multiple collaborators.

1. start a session
2. open the session in 2nd tab
3. hit `F5` multiple times. Try spamming the `F5` fast, and if it doesn't work spam it more slowly.

![image](https://user-images.githubusercontent.com/5153846/76710481-2c5e5380-6708-11ea-8eb6-7e82c2b9e651.png)

It seems it creates several sockets that are kept for the duration of the 2nd tab being open. When I close the 2nd tab, the sockets are slowly killed off and the 1st tab converges to `1` connection, again.

**Comment by j-f1** [comment]
We could have heartbeat pings every few seconds and evict clients if they don’t respond

**Comment by dwelle** [comment]
I think that's already happening (when we close the tab, the sockets get killed off in a while). It seems the tab somehow keeps the sockets open across refreshes. But if that's the case, it may be a bug in the browser, and we won't be able to do anything about it. In fact, this is likely the case: I can't repro in Firefox, only Chrome. So maybe investigate further and open a crbug.

**Comment by lipis** [comment]
Let's reopen if someone will mention it again.
