### ISSUE TITLE
loading empty-elements scene from file throws

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#922]
Not sure why this was added in https://github.com/excalidraw/excalidraw/pull/678:

https://github.com/excalidraw/excalidraw/blob/2db2f3f5e41651df1b11736037bcbbd4bd3df500/src/data/blob.ts#L41-L43

Note that it's currently possible to save empty-elements file, so it's weird that you can't import it back in.

/cc @Fausto95

**Comment by kbariotis** [comment]
This should be fixed on the latest master.
