### ISSUE TITLE
[IDEA] ASCII Export

### ISSUE THREAD

**Issue by jaredpalmer** [excalidraw/excalidraw#923]
It would be cool if we could somehow export to ASCII so that folks can use for markdown/code comment diagrams

**Comment by vjeux** [comment]
I think it would be cool, I have absolutely no idea how to make that happen though :(

**Comment by lipis** [comment]
I'm not sure if that's feasible or worth doing it in the end of the day!

If anything just use this: http://asciiflow.com

**Comment by lipis** [comment]
I think it's far fetched for now :)

**Comment by richard5334** [comment]
imo this feature would be ground breaking. It would allow to finally have a decent diagram at the top of source files lol
