### ISSUE TITLE
`selectedElementIds` not updated

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#927]
Ids not updated (i.e. removed from the object) on who knows how many operations, e.g. removal.

Also, there's some weird thing going on: try to drag one object around. It adds some random (?) id to the object on every mouseUp. I think it's because we're creating temp objects on every `pointerDowwn`.

**Comment by vjeux** [comment]
Is it still an issue after @petehunt changes?

**Comment by dwelle** [comment]
There's still the issue of adding to the map temp elements on `pointerdown`, and not clearing them until selection change. It's not causing any issues that I know of right now, but it may in the future. Dunno.

![excalidraw_selectedIds](https://user-images.githubusercontent.com/5153846/76709497-70008f80-66ff-11ea-8f37-0365a99ea08a.gif)

**Comment by cyan33** [comment]
I have a fix for this one. Submitting the PR (Not confident it's the correct fix though). :)

**Comment by dwelle** [comment]
fixed via https://github.com/excalidraw/excalidraw/pull/1017
