### ISSUE TITLE
Text gets cut off

### ISSUE THREAD

**Issue by gaearon** [excalidraw/excalidraw#929]
Create this text:

```js
let ship = {
  pilot: {
    name: 'Jim'
  }
};
```

Result:

<img width="210" alt="Screenshot 2020-03-13 at 02 17 11" src="https://user-images.githubusercontent.com/810438/76583357-e1a6c680-64d0-11ea-8868-6b06ddb9e981.png">

`im` is cut off.

**Comment by j-f1** [comment]
No repro on mobile

![image](https://user-images.githubusercontent.com/25517624/76584400-2e2ed980-64b2-11ea-8f74-fe4c7beb2179.png)

**Comment by gaearon** [comment]
I can repro on desktop Chrome.
