### ISSUE TITLE
Showing an indication of where other people's cursor are when offscreen

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#935]
Would be great to show at the edge of the screen where someone's cursor is. This way when interacting with someone you know where they are looking and drawing stuff.

**Comment by j-f1** [comment]
I don’t think you can track cursors when they’re off screen. Maybe just hide them on `pointerleave`?

**Comment by vjeux** [comment]
I'm talking about viewport difference. If someone is looking at the right part of the scene and you're looking at the left one. Would be great to show an indication that the person is looking somewhere else.

**Comment by j-f1** [comment]
Would it be useful to be able to click the cursor indicator to center the cursor on the screen? Or maybe match pan&zoom values.
