### ISSUE TITLE
Show transient state

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#937]
When people are writing text, drawing arrows or moving stuff around, you don't get any updates. This would be nice to lift that restriction as it would make the app feel more real time.

- [x] Mouse move during creation
- [x] Moving objects
- [x] Resize
- [ ] Text updates 
- [ ] Selection

**Comment by dwelle** [comment]
https://github.com/excalidraw/excalidraw/pull/936 somedoes does this as a side effect. Not for multi-elements though because that could cause problems.

**Comment by vjeux** [comment]
My thinking about this is that all the transient state we have could be moved off of the elements array and into its own storage. Then we can sync this per "collaborator" in a read-only way.

**Comment by vjeux** [comment]
For resize, I don't have a good answer but I'm not too worried about it, this is a much less frequent operation than initial drawing.

**Comment by j-f1** [comment]
Also moving things

**Comment by petehunt** [comment]
i have a fix for most of this

**Comment by vjeux** [comment]
The last thing remaining that I know about is textWysiwyg

**Comment by j-f1** [comment]
fwiw Google Sheets doesn’t attempt to show transient text, although Google Slides does: https://youtu.be/7mI2Tc8smpA

**Comment by vjeux** [comment]
I feel like it's a big miss right now to now show it. It kinda breaks the "live" experience.

**Comment by dwelle** [comment]
I wouldn't worry too much about what Google does because Google is widely known to have very bad UX.

**Comment by vjeux** [comment]
> I wouldn't worry too much about what Google does because Google is widely known to have very bad UX.

Let's try to avoid generic statements like this. Google is a big company that builds a lot of products. Some have good UX, some less. Let's try to evaluate the actual behaviors rather than the people/company building them.

**Comment by dwelle** [comment]
Sure, I was just trying to say that we should evaluate this feature on its own, not on a basis of arguing from authority. But yea, I may have come of as aggressive :(.

**Comment by vjeux** [comment]
Going to close this in favor of specific issues
