### ISSUE TITLE
Hint: Double click to write text

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#938]
This is not obvious and would be beneficial to people

**Comment by dwelle** [comment]
Would need to be shown pretty much all the time, unless we want to show this only when `text` shape is selected (though in that particular case it wouldn't even apply to that tool).

**Comment by vjeux** [comment]
I would show it when text tool is selected. Saying that you don't need to select it and just double click anywhere.

**Comment by j-f1** [comment]
It just needs to be clear that you can double-click anytime, or single-click when the text tool is selected.
