### ISSUE TITLE
Remote pointer sometimes doesn't show

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#946]
No clue how to repro. Just refresh a tab to regenerate a user. Sometimes that user doesn't have a pointer (in the other tab) for the whole session (the scene syncs normally).

Will need to investigate code.

**Comment by vjeux** [comment]
Sometimes, when developing locally, the user count works but the scene doesn't get updated. I don't know what to make of that. We also don't really have much logging so it's hard to know what's going on.

**Comment by petehunt** [comment]
i have a fix
