### ISSUE TITLE
Set mouse update to be volatile

### ISSUE THREAD

**Issue by vjeux** [excalidraw/excalidraw#951]
socket.io has a concept of volatile message that can be dropped. We should use that for mouse move events.
https://socket.io/docs/#Sending-volatile-messages

**Comment by vjeux** [comment]
cc @petehunt, @idlewinn

**Comment by idlewinn** [comment]
I looked into this - There's no support for client side volatile messages yet, and with the current implementation we can't know what kind of update there is on the server.

https://github.com/socketio/socket.io-client/issues/283
https://github.com/socketio/socket.io-client/pull/1292
https://github.com/socketio/socket.io-client/pull/821

**Comment by idlewinn** [comment]
We could add a new "volatile-broadcast" event, and send all volatile updates through this new broadcast (still encrypted) server-side. Thoughts on this?

**Comment by petehunt** [comment]
@idlewinn i think adding a `volatile-broadcast` event is a great idea

**Comment by MadlyFX** [comment]
@idlewinn +1 for Volatile broadcast event

**Comment by dwelle** [comment]
I believe this is already implemented.

client:

https://github.com/excalidraw/excalidraw/blob/1b9b824c708edd9745858362e7024b4f99e32d30/src/components/App.tsx#L1137

server:

https://github.com/excalidraw/excalidraw-room/blob/30ca34249023e25fee38f6478437ce750e38a49a/src/index.ts#L57

reopen if I'm wrong
