### ISSUE TITLE
Add a translation for Korean 

### ISSUE THREAD

**Issue by yongdamsh** [excalidraw/excalidraw#960]
I'd like to contribute to Korean translation in Crowdin. Can you set up a new locale for this?

**Comment by j-f1** [comment]
Set up: https://crowdin.com/translate/excalidraw/10/en-ko. Let us know if you encounter any issues!

**Comment by lipis** [comment]
@yongdamsh Is Korean in Korean: 한국어?

**Comment by yongdamsh** [comment]
@lipis Yes!

**Comment by lipis** [comment]
Thank you! We'll use that once you have more translation in.. :)
