### ISSUE TITLE
Middle-click-and-drag causes undesired paste when moving around the canvas

### ISSUE THREAD

**Issue by gustavopch** [excalidraw/excalidraw#961]
# Steps
1. Open Excalidraw.
2. Make sure there's something in your clipboard.
3. Middle-click-and-drag to move around the canvas.
4. When you release the click, what's in your clipboard will be pasted to the canvas.

# Environment:
- System: Arch Linux 5.5.6-arch1-1
- Display manager: X.Org X Server 1.20.7
- Window manager: i3 version 4.18 (2020-02-18)
- Browser: Google Chrome Version 80.0.3987.122 (Official Build) (64-bit)

**Comment by dwelle** [comment]
Cannot repro. By something in you clipboard, do you mean text (and thus what is pasted is a text element) or an excalidraw element?

**Comment by gustavopch** [comment]
@dwelle You won't be able to reproduce on Windows. I think it's something related to how Xorg manages the clipboard.

Look, if I copy `this message`, go to Excalidraw and try to move around the canvas, it's pasted where my cursor is when I release the middle-click:
![image](https://user-images.githubusercontent.com/10941958/76704545-76b7e400-66b8-11ea-9c7b-9b33a09735d7.png)

**Comment by dwelle** [comment]
What do you think is the root cause, and how would you want us to fix this? If it pastes text, then it suggests the `paste` event is being triggered for you. AFAIK we triggered the event (keyboard/mouse). Even if we could, some users may not want us to prevent mouse pasting (if they have it mapped to mouse somehow).

One possible solution is to detect whether the paste happened in the vicinity of `mouseup` event, but that seems brittle and we could still be preventing possibly valid cases :/.

**Comment by gustavopch** [comment]
@dwelle I've cloned the repo and inspected the `event` received by `pasteFromClipboard` at: 

https://github.com/excalidraw/excalidraw/blob/e1e2249f577d73229902ad23ad76b2c880a39350/src/components/App.tsx#L663

It's just a regular "paste" event. Exactly the same as I get with `Ctrl+V`. So I guess Excalidraw can't really do anything here and I'll have to tweak my system to stop pasting stuff on middle-clicks.

**Comment by vincent-paing** [comment]
> @dwelle I've cloned the repo and inspected the `event` received by `pasteFromClipboard` at:
> 
> https://github.com/excalidraw/excalidraw/blob/e1e2249f577d73229902ad23ad76b2c880a39350/src/components/App.tsx#L663
> 
> It's just a regular "paste" event. Exactly the same as I get with `Ctrl+V`. So I guess Excalidraw can't really do anything here and I'll have to tweak my system to stop pasting stuff on middle-clicks.

Following [this answer](https://askubuntu.com/a/872165) helps me solved this
