### ISSUE TITLE
Resizing messes up multi-point lines

### ISSUE THREAD

**Issue by keyz** [excalidraw/excalidraw#973]
Not sure if this is a regression...

![ezgif-1-37c38738f66f](https://user-images.githubusercontent.com/2268452/76737399-f039eb80-6725-11ea-9a8e-6fb4f0cfe0cf.gif)

repro: https://excalidraw.com/#json=5419770895663104,6V0pnKrRHUwBnufr4kCD4w

**Comment by dwelle** [comment]
It wasn't working ideally, but definitely not like this. The regression seems to have been introduced in https://github.com/excalidraw/excalidraw/pull/955 during rewrite to immutable objects I believe.

/cc @petehunt
