### ISSUE TITLE
Massive perf regression

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#977]
It seems that https://github.com/excalidraw/excalidraw/pull/959 introduced a huge perf regression even for relatively tiny scenes.

- target commit https://github.com/excalidraw/excalidraw/commit/35ce1729cc5a122f8924181b6c62448dfd976c12#comments (https://excalidraw-rhlegs9n6.now.sh/) (perf regression)
- commit before https://github.com/excalidraw/excalidraw/commit/e1e2249f577d73229902ad23ad76b2c880a39350#comments (https://excalidraw-qgosqln0b.now.sh/)

Test plan:
- open each commit & import (drag & drop) these files: [perf_test_scenes.zip](https://github.com/excalidraw/excalidraw/files/4337364/perf_test_scenes.zip) (includes small scene, and bigger scene)
- select all (`Cmd + A`)
- drag the elements around

Before (small scene):

![excalidraw_perf_regr_before](https://user-images.githubusercontent.com/5153846/76743511-0621cd80-6773-11ea-9130-d74b87c6a7d2.gif)

![image](https://user-images.githubusercontent.com/5153846/76744483-93b1ed00-6774-11ea-97ca-7cc6da2f9dff.png)

After (small scene):

![image](https://user-images.githubusercontent.com/5153846/76744489-97457400-6774-11ea-962a-38cb790a8665.png)

![excalidraw_perf_regr_after](https://user-images.githubusercontent.com/5153846/76743516-091cbe00-6773-11ea-8987-fc51731237b0.gif)

Note that there are big perf issues on scenes even smaller than that.

/cc @petehunt

**Comment by vjeux** [comment]
![image](https://user-images.githubusercontent.com/197597/76813682-f7a8d580-67b5-11ea-8d52-1905d46cd209.png)

looks like it's doing multiple commits on mouse move and each of them has a ton of smaller updates. Looking into it

**Comment by vjeux** [comment]
Yeah, it calls componentDidUpdate once per element that is being dragged...

**Comment by vjeux** [comment]
Fixed by #984 and #986

**Comment by dwelle** [comment]
props on the fix @petehunt & @vjeux :+1:

**Comment by petehunt** [comment]
sorry i keep breaking stuff! :)

**Comment by dwelle** [comment]
We all are :). We gotta write them tests!
