### ISSUE TITLE
Undo only works once

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw#988]

**Comment by Fausto95** [comment]
![undo-duplication](https://user-images.githubusercontent.com/23306911/76837788-6b3cf800-6833-11ea-88ce-e0134b6c9b0f.gif)
It's working for me

**Comment by lipis** [comment]
Actually it doesn't matter if it's duplicate or not.. I can only undo once. Either using Cmd+Z or the buttons (when the width is too small).

Chrome/macOS latests.

**Comment by dwelle** [comment]
Can repro. Also redo doesn't work at all.

**Comment by lipis** [comment]
We need E2E tests :)
