### ISSUE TITLE
Doubleclick to insert text should deselect parent element

### ISSUE THREAD

**Issue by dwelle** [excalidraw/excalidraw#994]
Not a huge problem, but doesn't look right, and has weird behavior in some edge cases.

### test plans

Scenario A:

1. Select empty-fill rectangle.
2. Doubleclick inside it to create text.
3. Should deselect rectangle.

Scenario B:

1. Doubleclick inside background-filled rectangle to create text.
2. It selects the rectangle, and keep it selected during editing the text. It should deselect the rectangle, instead.

**Comment by cyan33** [comment]
Hey @dwelle! I'd love to take a look at this!

**Comment by cyan33** [comment]
Fix is up. Looking forward to folks' input since I'm still not totally sure what's the expected behavior is.
