### ISSUE TITLE
Add shortcut for LockIcon

### ISSUE THREAD

**Issue by yongdamsh** [excalidraw/excalidraw#997]
It seems that there's no shortcut assigned to `LockIcon`. If so, do you have any plans to add a shortcut? I'd like to take on that task.

**Comment by Fausto95** [comment]
What would be a good shortcut for it?

**Comment by yongdamsh** [comment]
How about combining the two keys to prevent accidental selection? I'm thinking `Shift + L`.

**Comment by dwelle** [comment]
I'd rather go with non-printable combo. E.g.: `Cmd/Ctrl + L`. This will override browser  default (focus url bar), at least on Windows, thus you'll have to `event.preventDefault()` it. But I think we're good. This hotkey is used in the wild a lot (e.g. in markdown editors to insert link, such as on StackOverflow).

```
event[KEYS.CTRL_OR_CMD] && event.key === "l"
```

**Comment by lipis** [comment]
we have single letter shortcuts for all the elements from that bar.. why not just `L`?

**Comment by dwelle** [comment]
`L` is for line tool :).

**Comment by dwelle** [comment]
Or we can go with something different, such as `Q` or `` ` ``.

**Comment by lipis** [comment]
Right.. a single letter and maybe assign a number as well.. O C K

**Comment by dwelle** [comment]
I'd go with something that's reachable by left hand resting in position. So my vote is either `Q` or your proposal `C`.

**Comment by yongdamsh** [comment]
Since `LockIcon` affects shape selection when activated, I thought of it as a combination of two keys to use it more carefully.
But, as @dwelle said, it's better to use `Q` or ``` ` ``` key because usability is more important. Then I will proceed to `Q`. Would it be okay?

**Comment by dwelle** [comment]
Go ahead. We can hash it out in the PR :).
